### ISSUE TITLE
Website for latest vs stable release

### ISSUE THREAD

**Issue by peterdesmet** [r-lib/pkgdown#1002]
pkgdown builds a site for the current version of package. Is there a way to build from earlier versions and allow users of the site to toggle between the documentation of those versions?

E.g. between the latest dev (x.x.x.9xxx) and stable (latest CRAN version), similar to how ReadTheDocs supports this: https://python-dwca-reader.readthedocs.io/en/latest/ vs https://python-dwca-reader.readthedocs.io/en/stable/

**Comment by jayhesselberth** [comment]
There's no way to do this efficiently but may revisit for next release (#943).

If you use development style versioning and set `mode: auto` then you'll get two sites at the root and in `/dev`.

See:

https://pkgdown.r-lib.org
https://pkgdown.r-lib.org/dev

**Comment by peterdesmet** [comment]
Didn't know about `mode: auto`! This is more than sufficient for my use case! 👏 Agree with #943 that some cross ref between dev and stable releases would be nice.
