### ISSUE TITLE
Default pkgdown theme contrast

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1003]
Disclaimer: I was told about contrast yesterday, so I know very little.

On http://wave.webaim.org/report#/https://pkgdown.r-lib.org/index.html (click on contrast) it seems that contrast is too low 

* in the navbar

* for comments in code chunks.

Should a darker shade be used in these places?

Related to #782

**Comment by maelle** [comment]
If the changes suggested are welcome,

For the comments the line that'd need to be changed is https://github.com/r-lib/pkgdown/blob/04e3f6ee259b17bed7246f237652e4ba7d6742d4/inst/assets/pkgdown.css#L202 (with a darker shade, but how much darker?)

The navbar colors are bootstrap default, maybe one could add 

```
.navbar-default .navbar-nav > li > a {
    color: newcolor;
}
```

to pkgdown.css?

I see Bootstrap docs mention the contrast might be too low by default. https://getbootstrap.com/docs/4.3/getting-started/accessibility/#color-contrast but I don't know if the default color of the navbar in newer Bootstrap versions (cf #894) is better.

**Comment by hadley** [comment]
How about `#444` for the links in the navbar, and `#666` for comments. We could also make the background colour a little lighter, maybe `#fafafa`? Do you want to make the change?

**Comment by hadley** [comment]
Oh, but we can't override the default theme colours in `pkgdown.css` because that would be applied across all themes.

**Comment by maelle** [comment]
So where could the change happen?

**Comment by hadley** [comment]
I don't recall how the theming system works, but presumable we'd either have to change the default theme, or make one of our own.

**Comment by maelle** [comment]
> Oh, but we can't override the default theme colours in pkgdown.css because that would be applied across all themes.

I now realize this is actually what I'd like to happen. :grin: E.g. when working on the rOpenSci pkgdown template, I noticed the lack of contrast and would prefer it to be solved in pkgdown default, than to solve it in my theme. I also think it's good if the default that might appear in themes (that don't override the color of comments) has a good enough contrast. Is the issue with applying the change across all themes that it is sort of a breaking changes for folks who've developed their themes?

**Comment by hadley** [comment]
I meant something slightly different: if we set the text colour it will be applied across all themes, regardless of what their background colour is (ie it might decrease the contrast if the theme uses a dark background). 

I would be fine changing the css for a given theme, assuming that’s possible with the current design (I don’t remember exactly but aren’t they coming from another site?)

**Comment by jayhesselberth** [comment]
You could change the contrast for *just* the pkgdown site by including and making changes in an `extra.css` file.

I don't think you want to make changes to `inst/assets/pkgdown.css` because they could clash with different bootswatch themes used on other sites.

**Comment by maelle** [comment]
I think I understood the issue now, thanks! :relieved: 

So for my own pkgdown themes/templates I will tweak colors directly and not wait for an "upstream fix". :wink:

What about pkgdown's default theme, where should the change occur?

**Comment by hadley** [comment]
The colours come from the bootstrap default, so I don't think there's an easy way for us to change this globally (without potentially making some existing pkgdown sites less usable).
