### ISSUE TITLE
Conflict in title

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1004]
My PR #997 named the parameter to override the page title "title" which introduced a conflict, see e.g. https://r-hub.github.io/rhub/ 

I'll make a PR renaming that parameter since there was already a role for a parameter called title.

**Comment by hadley** [comment]
Why don't we make it `title` under the `home` category?

```R
home:
  title: "This is my package title"
```

I've realised that this is actually quite important for SEO — since CRAN doesn't like "package" or "in R" in package titles, most packages really need to customise this.

**Comment by hadley** [comment]
Lets keep discussion in the original issue: #957
