### ISSUE TITLE
Parameterize a package template?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1006]
When the template of a pkgdown website is a _package_, what happens is that the assets are copied.

https://github.com/r-lib/pkgdown/blob/0b2c27d41b869ac31b6a46815940f55b12f6171f/R/init.R#L70-L72

I wonder whether this step could be made more complex to be able to parameterize the template. I'd like to be able to e.g. add a warning banner to the website based on the development status, i.e. the config could look like

```yaml
template:
  package: rotemplate
  status: concept
```

and based on this the assets from `rotemplate` would be rendered like what happens in `usethis` with `whisker`.

https://github.com/r-lib/usethis/blob/a330ed9c39fd4d76b0d2f1bbf32d32cdd8eb8c18/R/template.R#L60-L63

Is this something of interest for `pkgdown` or should I rather write my own wrapper around `pkgdown::init_site()`?

**Comment by hadley** [comment]
I think you should write your own wrapper.
