### ISSUE TITLE
Figures in examples are always rendered on a white background

### ISSUE THREAD

**Issue by thomasp85** [r-lib/pkgdown#1007]
It appears that all figures rendered as part of the example sections in the docs are with a fixed white background. This means that you can't control background colour/transparency through the `figures:` yaml setting.

Digging into it, the `recordedplot` returned by `as_data()` already has a white background, so any device setting will get drawn over. I have been unable to figure out why this is happening (you can make transparent background in knitr, so it doesn't appear to be a limitation in the evaluate package).

This would be really nice to have for pages that uses a non-white background theme e.g. https://ambient.data-imaginist.com (compare the from page figures with the references)

**Comment by Bisaloo** [comment]
My understanding is that it's a deliberate choice as this explicitly set by `pkgdown.css`:

https://github.com/r-lib/pkgdown/blob/d01672efa3baa80fd7ab238b7143080b0daf49a4/inst/assets/pkgdown.css#L177-L181

In pavo, I removed the white background by creating a `extra.css` file with the following content (https://github.com/rmaia/pavo/commit/2f72d553e12e0e84decc7b25627885ac49c5016f)

```css
pre .img img {
  background: none;
}
```

<details><summary>Before</summary>

![Screenshot from 2019-08-28 16-29-08](https://user-images.githubusercontent.com/10783929/65499355-c235c600-debd-11e9-8f49-1b8cdca45e3c.png)

</details>

<details><summary>After</summary>

![Screenshot from 2019-08-28 16-29-26](https://user-images.githubusercontent.com/10783929/65499354-c235c600-debd-11e9-9af2-768f80845d30.png)

</details>

I can also submit a PR to change this in pkgdown if necessary but as I said, it seems like a deliberate choice so I'll wait for more input before doing so.

**Comment by thomasp85** [comment]
This is not about css settings though. This is about the background colour of the raster image being created

**Comment by Bisaloo** [comment]
I'm not sure what you mean. The fact I was able to change this only by tweaking the css file seems to show the opposite, doesn't it?

Here's what happens if I edit the css for your website:

![Screenshot from 2019-09-24 11-31-21](https://user-images.githubusercontent.com/10783929/65499930-bc8cb000-debe-11e9-93e0-3555d23cbb08.png)
