### ISSUE TITLE
Help add privacy policy when Google Analytics is being used

### ISSUE THREAD

**Issue by emilyriederer** [r-lib/pkgdown#1009]
I love that `pkgdown` makes it easy to add Google Analytics to the website. This seems like it could provide useful insights to package developers into what users are finding interesting or useful.

One "gotcha" of using Google Analytics is that it puts the onus on users to create a privacy policy. However, many package developers may not realize this or have access to legal resources to consult on complete and correct language to include. 

Would there be a benefit to making `pkgdown` more opinionated about this? Some options might include:

- Including in the docs where Google Analytics is mentioned a call-out about a Privacy Policy being needed and instructions on how to add one
- Taking an opinionated approach of providing a message/warning or throwing an error if the `ganalytics` parameter is being used without a `PRIVACY.md` file existing
- Ideally, consulting with RStudio legal resources to determine a boiler plate text for said policy (obvious this would be a YMMV). This could live somewhere in either `pkgdown` or perhaps `usethis` could even take on a `use_privacy_policy()` function.

The third option could also be useful for `blogdown` which has the same issue.

I'd be interested in helping out if any of these options seems desirable! 🙋 Thank you so much for this amazing package!

---

FWIW: For my [`pkgdown` site for `projmgr`](https://emilyriederer.github.io/projmgr/), I added a policy by adding a `PRIVACY.md` file to my repo and adding the following to my `_pkgdown.yml`:

```
home:
  links:
  - text: "Site Privacy Policy"
    href: PRIVACY.html
```

For the text, I borrowed the same verbiage I found on the [US House of Representatives](https://www.house.gov/privacy-policy) website regarding Google Analytics since I do not have a legal background to write the language myself.

**Comment by hadley** [comment]
Would you mind explaining in a bit more detail? e.g. Why does it puts the onus on the user to create a privacy policy?

**Comment by emilyriederer** [comment]
Apologies in advance if I'm wrong here. I will caveat that this is definitely not an area of expertise but just something I began to worry about recently. There seems to be uncertainty surrounding around how personal websites using Google Analytics are affected by GDPR as the definition of a "Data Controller" seems fairly broad. 

A quick search on "GDPR google analytics" turned up quite a few hits from the past year around requirements and recommendations. Upon further research, I find only conflicting opinions about how this pertains to personal sites like blogs (and, by extension, presumably pkgdown). 

For examples:

A [Hacker News thread](https://news.ycombinator.com/item?id=16824921) cites an article from GDPR:
> Article 2 of the GDPR says: 2. This Regulation does not apply to the processing of personal data: (c) by a natural person in the course of a purely personal or household activity.

However, it is still not totally clear that online activity like managing a website fits this definition. For example [the website SmartBlogger](https://smartblogger.com/gdpr/#seven_easy_steps) seems to believe differently. Their article engs with tips on how to make Google Analytics *more* compliant, but I'm still not entirely clear if that alone is sufficient without also being transparent in informing visitors.

**Comment by hadley** [comment]
It's not clear to me that this actually necessary. However, I think it would be appropriate to add a sentence or two the documentation to make sure that people are aware of the issue.

**Comment by emilyriederer** [comment]
When making a PR to the documentation, do you prefer the PR to include just the updated `.R` file or also the corresponding updates to the `.Rd`?

**Comment by jayhesselberth** [comment]
Please run `devtools::document()` to update the Rd file too. Thanks
