### ISSUE TITLE
Function auto-linking in titles breaks navbar

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1013]
You can reproduce this issue with the following test vignette:

```
---
title: "Test: Autolink in title"
---

# Test `build_article()` function

```

<details>
<summary>Screenshot of output</summary>

![Screenshot from 2019-05-10 13-50-38](https://user-images.githubusercontent.com/10783929/57525347-c1dfc880-732a-11e9-9c3e-eee7d8c2e5db.png)

</details>

- The navbar is broken (extra `\n` and strange styling) and links to a 404 page

**Comment by jayhesselberth** [comment]
Related to #948

**Comment by Bisaloo** [comment]
Oh, you're right. I think this is actually a duplicate. Feel free to close it!

**Comment by Bisaloo** [comment]
@jayhesselberth, #1046 didn't fix the navbar issue, see for example https://rafaelmaia.net/pavo/articles/pavo-2-importing_processing.html#the-aggplot-function where we use `pkgdown` dev version.

**Comment by jayhesselberth** [comment]
Thanks, opened a new issue in #1067

**Comment by jayhesselberth** [comment]
This should be fixed, can you confirm?

**Comment by Bisaloo** [comment]
Yes, it worked! Thank you!
