### ISSUE TITLE
Make links in changelog permanent

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1015]
Currently, links to subsections (such as `New features`) in changelog will change over time, which makes it difficult to link to a specific item and ensure that the reader will reach the intended block.

For example, in the pkgdown changelog (https://pkgdown.r-lib.org/news/index.html), the `New features` section of pkgdown 1.2.0 can be linked via https://pkgdown.r-lib.org/news/index.html#new-features and the `New features` section of pkgdown 1.1.0 via https://pkgdown.r-lib.org/news/index.html#new-features-1.

But if the `New features` section is added for a new version at some point in the future, the link to the `New features` section of pkgdown 1.2.0 will become https://pkgdown.r-lib.org/news/index.html#new-features-1 and the link to the `New features` section of pkgdown 1.1.0 https://pkgdown.r-lib.org/news/index.html#new-features-2.

**Comment by hadley** [comment]
These anchors are autogenerated by pandoc so I think they're going to be tough to fix. If this is important to you, could you just add `{#new-features-1.2}` yourself?

**Comment by Bisaloo** [comment]
Yes, I could do it for my own packages but I don't think it's a very satisfying solution. 

For example, I noticed this issue when I tried to link to a specific news item from fs in #1014. Manually adding this anchor to my own packages wouldn't have helped in this case. And most package developers won't know about this issue or bother tweaking their changelog for this.

**Comment by hadley** [comment]
Hmmmm true.

**Comment by jayhesselberth** [comment]
I think [anchors.js](https://www.bryanbraun.com/anchorjs/) might solve this.

**Comment by maelle** [comment]
There's now a function `tweak_news_heading()` for other reasons: some more tweaking might fit in there? Making a slug of the heading & adding the version name, adding it as ID.

**Comment by hadley** [comment]
Yeah, that'd be great.
