### ISSUE TITLE
Odd links in TOC

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#1017]
I don't know the correct vocabulary to describe what I'm seeing, so I'll just link to an afflicted  gargle vignette:

https://gargle.r-lib.org/articles/how-gargle-gets-tokens.html

Look at the TOC in the right sidebar. The "dummy links" that have no text seem to link to the desired targets. The more proper looking links, with text, mostly result in a 404.

**Comment by jennybc** [comment]
It would be easy to believe that the challenge is because my level 2 headers also coincide with the names of functions in the package.

**Comment by jayhesselberth** [comment]
This is another example of #948.
