### ISSUE TITLE
Option to disable knitting readme.md

### ISSUE THREAD

**Issue by jeroen** [r-lib/pkgdown#1019]
We're automatically building pkgdown sites for all 400+ ropensci packages (non interactively).

Many packages seem to have pre-rendered example code in the `readme.md` that doesn’t work out of the box. It would be useful to support a `_pkgdown.yml` option which lets the author opt-out of knitting the `readme.md`, i.e. convert it to index.html as is.

I had actually expected that the code would only be knit if it was an `Rmd` file and not for `md` files. One could also consider making this the default behavior.

**Comment by jayhesselberth** [comment]
I'm surprised a README.md is knit. Does it happen to have Rmd style chunks in it (i.e. ` ```{r ...}``` `?

What do you mean the code doesn't work out of the box? knitr tries to run it and it throws an error?

**Comment by jeroen** [comment]
You are right, I think this happens for projects that have both a `README.md` as well as a `README.Rmd` file. In this case Github shows the former but pkgdown knits the Rmd.

**Comment by hadley** [comment]
@jeroen this is handled by #1028, right/

**Comment by jeroen** [comment]
Yes it is, thanks.
