### ISSUE TITLE
improve error message for bad vignette paths

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#1025]
currently, when I provide a bad path to a custom `articles:` section in my `_pgkdown.yml`, I get a a somewhat misleading error message.

For example, 

```
articles:
  - title: "Foo"
    contents:
      - wrong_filename
```

on `pkgdown::build_site()` will yield:

```
In '_pkgdown.yml', topic must be a valid R expression.
Problem topic: `wrong_filename`
```

I think I understand that this makes technical sense, but it can be confusing for the user.
I initially set off on the wrong track, futzing around with `"` valid R object names etc.

I'll be happy to take a crack at this if you think this makes sense.

**Comment by hadley** [comment]
Yeah, I think that would be very helpful — the references section suffers from the same problem.
