### ISSUE TITLE
rebuilding identical articles creates different metadata in images and PDFs

### ISSUE THREAD

**Issue by jackwasey** [r-lib/pkgdown#1026]
This may not be pkgdown, but every time I rebuild articles, any images end up have PNG metadata updated, which results in spurious diff, and thus pollutes the git repo when checked in. Same is true for PDFs as can be seen using `exiftool`.
e.g., by diffing `identify -verbose a.png` and `identify -verbose b.png`, I see:

## a
>      date:create: 2019-05-14T14:02:16-04:00
>      date:modify: 2019-05-14T14:02:16-04:00

## b
>      date:create: 2019-05-14T14:08:43-04:00
>      date:modify: 2019-05-14T14:08:43-04:00

**Comment by jayhesselberth** [comment]
Yeah every time the pkgdown internal site is built, it triggers a diff on the vignette PDFs. Ideas for how to fix?

**Comment by jackwasey** [comment]
I thought pandoc might be the culprit, but it doesn't seem like it is possible to set, e.g. a PDF ModDate field. It just gets written. I'm on pandoc 2.2.1 on Ubuntu and 2.7.2 with homebrew, MacOS. Both show same issue. I don't exactly know when this started happening. In addition, it doesn't seem to happen for every PDF vignette in my package. It looks like it might update these fields if they exist, otherwise leave them as they were for PDF. The PDF I have is pre-built, and hasn't changed: I have a minimal Rnw which generates the PDF for the package just by including the pre-built PDF. It is this one which is changing date each time, including all the PNG images (with updated metadata) that it needs.

**Comment by jackwasey** [comment]
Forget that: the article in question is building directly from the Rmd, and adding the create and modify timestamps.

**Comment by jackwasey** [comment]
Pandoc uses https://hackage.haskell.org/package/JuicyPixels-3.2.7/docs/Codec-Picture.html to read and write PNG, but I don't see anything about whether creation or modification dates can be omitted or changed.

**Comment by jackwasey** [comment]
The following in the preamble works.
```
  \pdftrailerid{}
  \pdfsuppressptexinfo-1
  \pdfinfoomitdate1
```
However, it does not work for documents created by chunks, e.g. using the pdf or cairo_pdf devices, which delegate PDF production to R, and there is apparently no way to control the contents of these with device options.

See:
https://tex.stackexchange.com/questions/440270/how-to-get-pdftex-to-have-same-pdf-output-for-each-run-on-the-same-input https://superuser.com/questions/130347/how-do-i-produce-bytewise-consistent-documents-with-pdflatex and http://texdoc.net/texmf-dist/doc/pdftex/manual/pdftex-a.pdf

**Comment by Bisaloo** [comment]
For figures produced by Rmarkdown chunks, it should be possible to remove the date metadata with a [knitr hook](https://yihui.name/knitr/hooks/)

**Comment by Bisaloo** [comment]
Something like that should work as far as I can tell. This can probably be improved as I'm not really familiar with hooks and it currently looks a bit awkward.

````r
```{r}
knitr::opts_chunk$set(mtime = TRUE)
knitr::knit_hooks$set(mtime = function(before, options, envir) {
  if (before) 
    return()
  num = options$fig.num
  if (length(num) == 0 || num == 0) return()  # no figures
  ext = tolower(options$fig.ext)
  paths = knitr:::all_figs(options, ext)

  knitr:::in_base_dir(
    lapply(paths, function(x) {
      fs::file_touch(x, access_time = as.Date("1980-01-01"))
    })
  )
  return()
})
```
````

**Comment by hadley** [comment]
I think this is outside the scope of pkgdown — unfortunately R's graphics devices tend to embed date-time in the metadata.
