### ISSUE TITLE
Combine test vignettes

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1030]
Would be nice to curb the proliferation of test vignettes. Everything but the PDF vignettes could be merged into a combined test vignette.

**Comment by hadley** [comment]
We could also just carve them out into a separate (sub) menu. It's nice to keep them simple.

**Comment by hadley** [comment]
Or maybe we should figure out how to check just these vignettes back into git — that makes the more useful as regression tests.
