### ISSUE TITLE
Allow pkgdown/index.Rmd or custom path for index

### ISSUE THREAD

**Issue by nteetor** [r-lib/pkgdown#1031]
I really appreciate the option to use a `pkgdown/` folder thus avoiding extra files in the top-level package directory. However, as far as I can tell, if one wants to use `index.Rmd` as an alternative to `README.md` the index file may only live in the package's top-level directory. If supporting a `pkgdown/index.Rmd` file or a custom path option in the pkgodown config is a possibility I am happy to put in a PR. 

e.g.
```yaml
home:
  path: pkgdown/index.Rmd
```

**Comment by hadley** [comment]
Fixed by #1184
