### ISSUE TITLE
factor out deploy_local to bash script for GitHub actions

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#1038]
The git work done by `deploy_local()`, `github_clone()` and `github_push()` has some overlap with the bash script in the language-agnostic [GitHub action for GitHub Pages](https://github.com/maxheld83/ghpages).

(The action and bash script still needs quite some improvement but is used by all sorts of projects, not just R).

If there's some interest, I'd be happy to look into this, perhaps this is something that can be factored out of pkgdown.

It should still be able to run locally, and it should be possible to take on the bash script/function *without* taking on the entire ghactions package as a dependency.

**Comment by hadley** [comment]
Now done in `deploy_to_branch()`
