### ISSUE TITLE
Purge articles that no longer exist

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#1040]
Otherwise the pkgdown is vulnerable to dead links after renaming article file names or removing articles.

**Comment by jayhesselberth** [comment]
Can you use `clean_site()` and then `build_site()`?

**Comment by krlmlr** [comment]
Would you recommend this for unattended CI builds?

**Comment by jayhesselberth** [comment]
I've never tested it on a CI build but I think it should work.

**Comment by krlmlr** [comment]
`clean_site()` keeps `dev/` and `CNAME`, which seems fine for most cases. Thanks!
