### ISSUE TITLE
Make contributing guide and code of conduct more prominent when available?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1044]
When available, could/should the pages "CONTRIBUTING" and "CODE_OF_CONDUCT" be highlighted from the sidebar/navbar by default? Maybe as a "community" section to [use GitHub's words](https://github.com/r-lib/pkgdown/community)?

E.g. at the moment https://pkgdown.r-lib.org/CODE_OF_CONDUCT seems to be linked from the bottom of the README only and I'm not sure where https://pkgdown.r-lib.org/CONTRIBUTING is linked from.

**Comment by jayhesselberth** [comment]
Yeah these could be surfaced more deliberately. Putting them is a dedicated "community" sidebar section seems reasonable to me.

**Comment by maelle** [comment]
Ping me if a PR is welcome. :-)

**Comment by maelle** [comment]
Happy to make a PR if the feature is welcome (I'd be an user :smile_cat: ).

**Comment by jayhesselberth** [comment]
Go ahead with a PR. I think I'd put the section between "Links" and "License". We might have to slightly reduce the side of the sidebar headers to make it all fit.

**Comment by maelle** [comment]
> We might have to slightly reduce the side of the sidebar headers to make it all fit.

Why? It seems to fit right now in my PR but I might be missing something.
