### ISSUE TITLE
Add option to track with Matomo/Piwik

### ISSUE THREAD

**Issue by tobyhodges** [r-lib/pkgdown#1054]
As well as tracking with Google Analytics, it would be great to have an easy way to add tracking by Piwik/Matomo (https://matomo.org/) for sites built with pkgdown. This is something that I and some of my colleagues might be interested in working up a PR for. But want to check for guidance/discussion here first before we spend time on it. Is this a feature that you'd be interested in including?

**Comment by jayhesselberth** [comment]
This should be implemented in a custom template. See https://github.com/r-lib/pkgdown/pull/984#issuecomment-469677052.

**Comment by tobyhodges** [comment]
Ah, ok, thanks for the pointer and sorry for the duplication: I should have searched the previous PRs as well as the Issues.
