### ISSUE TITLE
If version header contains a link, date is prepended instead of appended

### ISSUE THREAD

**Issue by burgerga** [r-lib/pkgdown#1058]
My NEWS file was originally formatted according to https://keepachangelog.com/en/1.0.0/ where each version header includes a link to a github code comparison (which I really like, especially since changelogs are often incomplete): 

```
# shinyTime [1.0.0.9000]

# shinyTime [1.0.0]

## Major changes 

- Input time with minutes rounded to the nearest user-specified multiple

# shinyTime [0.2.1]

## Minor changes

- Updated style to match other shiny inputs

- Added input validation so that the time returned is always a valid 
time (invalid values are set to 0)

# shinyTime [0.2.0]

## Minor changes

- Added support for input in the %H:%M format (without seconds)

## Bug fixes

- Fixed padding problem on keyboard input

- Keyboard input now properly causes change events

# shinyTime 0.1.0

- Initial release
 
[1.0.0.9000]: https://github.com/burgerga/shinyTime/compare/v1.0.0...HEAD
[1.0.0]: https://github.com/burgerga/shinyTime/compare/v0.2.1...v1.0.0
[0.2.1]: https://github.com/burgerga/shinyTime/compare/v0.2.0...v0.2.1  
[0.2.0]: https://github.com/burgerga/shinyTime/compare/v0.1.0...v0.2.0
```

However the weird thing is, for versions that have a link, the date shows before the version, which doesn't look good:

![image](https://user-images.githubusercontent.com/907362/58984802-31d25900-87da-11e9-8773-0f376cf2b7f1.png)

**Comment by jayhesselberth** [comment]
Supported news bullet styles are described in the [style guide](https://style.tidyverse.org/news.html#organisation-2) and will be implemented by #1036.

Not sure how hard it would be to accommodate this format but we could take a look.
