### ISSUE TITLE
pkgdown::build_site() Error : Can't find DESCRIPTION

### ISSUE THREAD

**Issue by seymakalay** [r-lib/pkgdown#1059]
Hello, 
I am following this link "https://www.emilyzabor.com/tutorials/rmarkdown_websites_tutorial.html"
and at the end I am getting this error,
 pkgdown::build_site() Error : Can't find DESCRIPTION
where I am doing wrong?
Many thanks in advance,,,,

**Comment by cderv** [comment]
`pkgdown` is for building website from package documentation. You need to work in a package project. That is why it is looking for a DESCRIPTION.

The link you provided presents several options for website with R. `pkgdown` is the one for package website. Are you following this one ? 

For this type of question (not a bug or a feature request), prefer https://community.rstudio.com; This is better suited for questions, and a large community ready to help you !
