### ISSUE TITLE
Old installed version of library used to build site

### ISSUE THREAD

**Issue by maximilianmordig** [r-lib/pkgdown#1061]
It happens often that the vignettes include a call like
```library(rtables)```
The `README.Rmd` has this problem as well. It does not make sense to use `devtools::load_all` which is only called in `pkgdown::build_reference` because the vignettes should run standalone.

In my opinion, this should use the current library that is developed rather than the last installed library.

As a workaround, I have the following code to temporarily install the package in question:
```
build_pkgdown_website <- function(pkg_dir) {
  withr::with_dir(pkg_dir, {
    withr::with_temp_libpaths(
      code = {
        utils::install.packages(".", repos = NULL, type = "source")
        devtools::document(".") # document=TRUE below is not working in some circumstances
        pkgdown::build_site(".", document = TRUE, lazy = TRUE, seed = 1)
      }
    )
  })
}
```

**Comment by cderv** [comment]
FWIW @maximilianmordig I encountered once this issue and found that `devtools::build_site()` is correctly using the dev version. it installs the dev version of the 📦 before using `pkgdown::build_site`
https://github.com/r-lib/devtools/blob/2778b0d9ea112e31290164c8aa909b6787799fa9/R/build-site.R#L12
```r
function (path = ".", quiet = TRUE, ...) 
{
  check_suggested("pkgdown")
  save_all()
  pkg <- as.package(path)
  withr::with_temp_libpaths(action = "prefix", code = {
    install(pkg = pkg$path, upgrade = "never", reload = FALSE, 
      quiet = quiet)
    if (isTRUE(quiet)) {
      withr::with_output_sink(tempfile(), pkgdown::build_site(pkg = pkg$path, 
        ...))
    }
    else {
      pkgdown::build_site(pkg = pkg$path, ...)
    }
  })
}
```

It seems like the function you wrote. can it be useful to you too ? 
Note sure why pkgdown and devtools have both the function that behave a bit differently. 

Also the last dev version of pkgdown replace the `document` argument by a `devel = TRUE`. You should see the NEWS and test again to see if this arguments changes you use case.
From doc on `devel`
>  If TRUE (the default), assumes you are in a live development environment, so automatically runs devtools::document() and **loads package with devtools::load_all()**. If FALSE, does not re-document, and uses the installed version of the package for examples.

Hope it helps.
