### ISSUE TITLE
Docs should show "devel" (not "development")

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#1072]
See the section [Development mode](https://pkgdown.r-lib.org/reference/build_site.html?q=mode#development-mode) in the help for `build_site()`.

In a few places, it suggests that "development" is a valid value for `mode` but when I use it, I see:

```
> pkgdown:::build_site_external()
Error : development$mode` in `_pkgdown.yml must be one of auto, release, devel, or unreleased
```

So I think "devel" should be used instead.

*I would send a PR but I'm struggling to get the pkgdown tests to pass right now. Once I got xml2 installed from a PR, I still saw lots of timeout problems for some tests. Maybe it's just a random thing.*

**Comment by jayhesselberth** [comment]
At some point this was fixed and is updated in the development docs:

https://pkgdown.r-lib.org/dev/reference/build_site.html#development-mode

**Comment by jennybc** [comment]
Aha, thanks.

Now that I know cran.r-project.org is down, that is clearly the explanation for my inability to pass `R CMD check`. Not sure if that means there's some rationalization that might be a good idea re: test skipping.
