### ISSUE TITLE
pkgdown::build_site fails when r-project.org is down

### ISSUE THREAD

**Issue by gvegayon** [r-lib/pkgdown#1073]
# Description of the error

`build_site` fails when *.r-project.org cannot be fetched (checked with the web browser). Here is the output from a fresh R package created following [this](https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md#package-reprexes)

```r
> pkgdown::build_site()
══ Building pkgdown site ═══════════════════════════════════════════════════════════════════════════════
Reading from: '/tmp/RtmpLjTZZT/test'
Writing to:   '/tmp/RtmpLjTZZT/test/docs'
── Initialising site ───────────────────────────────────────────────────────────────────────────────────
Copying '../../../usr/local/lib/R/site-library/pkgdown/assets/docsearch.css' to 'docsearch.css'
Copying '../../../usr/local/lib/R/site-library/pkgdown/assets/docsearch.js' to 'docsearch.js'
Copying '../../../usr/local/lib/R/site-library/pkgdown/assets/link.svg' to 'link.svg'
Copying '../../../usr/local/lib/R/site-library/pkgdown/assets/pkgdown.css' to 'pkgdown.css'
Copying '../../../usr/local/lib/R/site-library/pkgdown/assets/pkgdown.js' to 'pkgdown.js'
Writing '404.html'
── Building home ───────────────────────────────────────────────────────────────────────────────────────
Writing 'authors.html'
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Resolving timed out after 10000 milliseconds
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Resolving timed out after 10000 milliseconds
```
# Source of the problem

As mentioned, this fails during `build_site`, and in particular, when calling `repo_link`. I think the error is here

https://github.com/r-lib/pkgdown/blob/5a70d7edc6d7f09255c8e255c5ab044c7d25e72f/R/build-home-index.R#L121-L129 

# Possible solution

I think it can be fixed by first wrapping `httr::http_error` and `httr::HEAD` with `tryCatch` as I do here:

https://github.com/r-lib/pkgdown/blob/bf63442a36499183441ab7aeaf5fd071e34a1b99/R/build-home-index.R#L121-L144

**Comment by karthik** [comment]
As a temporary solution, I just replaced line 121 with `cran_url <- paste0("https://cran.rstudio.com/package=", pkg)` and installed locally to make everything work. I believe it would work better with cran_url as an arg that could be overridden from the default as a function arg.

**Comment by gvegayon** [comment]
I thought about it but wasn't sure how to better expose that since from what I saw, that function is not exported.

**Comment by jayhesselberth** [comment]
We could make the cran URL configurable via `_pkgdown.yml`:

``` yaml
cran: https://cran.rstudio.com/
```

and update `build_home_index` to use it.

**Comment by gvegayon** [comment]
> We could make the cran URL configurable via `_pkgdown.yml`:
> 
> ```yaml
> cran: https://cran.rstudio.com/
> ```
> 
> and update `build_home_index` to use it.

Still, need to check for timeout errors

**Comment by hadley** [comment]
Looking at the code it seems like we've already switched to a more robust url and added some error handling, so I'm going to close this issue.

**Comment by LJFRIESE** [comment]
... Is this what's happening right now?

I'm trying to build pkgdown site and none of the _local/_external options seem to work. 

![image](https://github.com/r-lib/pkgdown/assets/135739244/8aa64e7e-5b2a-4a4c-b3e6-d268613f5e33)

![image](https://github.com/r-lib/pkgdown/assets/135739244/652ed36a-9233-4cde-a0e3-0e7a36927660)

**Comment by hadley** [comment]
It seems to be back up again, so you should be ok again now.

**Comment by LJFRIESE** [comment]
Yep, it's all good now. I can't pretend to know what all the interdependencies are in the build_ pieces, but it would be great to have a fallback option. It was very confusing to realize that the build_ functions require CRAN, and more generally an internet connection, for functioning. Makes sense when CRAN is the end goal, but I am only developing for local-use.
