### ISSUE TITLE
Take deployment branch into account when linking to files

### ISSUE THREAD

**Issue by asardaes** [r-lib/pkgdown#1074]
I have a `docs` branch where I push to whenever I want to update the site. Nevertheless, all the files (vignettes, R source, NEWS) that have links point to the master branch. It's a minor thing, but I think it would be nice if the links pointed to the branch that was active during deployment.

**Comment by asardaes** [comment]
My idea was to have a specific branch (`docs` in my case) that would be used to deploy the site, to avoid updating it on every commit and, for the most part, keep the documentation for the latest CRAN version visible. The Travis configuration is pretty easy, one just needs something like:

```
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: docs
```

where `branch` specifies which branch is "allowed".

When the site is built, some links are created. For example, the documentation entries in the Reference tab have a line "Source: `R/some_file.R`" linking to the file where the function source is present. Same goes for vignettes and changelog. These links always point to `master`, so the linked files could run out of sync or stop existing entirely until `docs` is fast-forwarded. That's why I thought it would be nice to create the links based on the git branch that was active at the time of deployment. It's probably a very special use case, so it might not be worth it if doing it is too complicated.

**Comment by hadley** [comment]
Yeah, I think unfortunately this is too complicated to be worth implementing at this time.
