### ISSUE TITLE
`mode: auto`  is ignored when using `deploy_site_github()`

### ISSUE THREAD

**Issue by mcanouil** [r-lib/pkgdown#1078]
Using `build_site()` and `mode: auto` in `_pkgdown.yml` allow to have an 'danger' label for development version.
But, when using `deploy_site_github()` and Travis CI, the parameter is just ignored, allowing the website to be published with x.x.x.9000 version as a "release" version.

It would be great, to have `mode: auto` working with `deploy_site_github()`.

I don't know (yet) how the version is parsed inside pkgdown, but [deploy-site.R#L123](https://github.com/r-lib/pkgdown/blob/master/R/deploy-site.R#L123) seems to be a start to allow `mode:  auto` with `deploy_site_github()` and Travis CI.
If I manage to understand the version parser and deploy thing, I'll make a PR.

**Comment by jayhesselberth** [comment]
Do you have a live website that illustrates this problem?

**Comment by mcanouil** [comment]
Yes, sorry it's everywhere as far as I can tell, here are few examples:
https://magrittr.tidyverse.org/
https://mcanouil.github.io/NACHO/ 
https://gganimate.com/

**Comment by jayhesselberth** [comment]
The pkgdown website itself uses `mode:auto` and `deploy_site_github()` and tags the version badge correctly ([released](https://pkgdown.r-lib.org/) and [development](https://pkgdown.r-lib.org/dev/) versions).

**Comment by mcanouil** [comment]
I don't know what I did wrong, but it appears to be correct once I changed the version:
https://mcanouil.github.io/NACHO/
https://mcanouil.github.io/NACHO/dev/
