### ISSUE TITLE
Cannot install devtools in r due to processx version not being updated

### ISSUE THREAD

**Issue by abodnahk** [r-lib/pkgdown#1080]
I am trying to install devtools but getting an error as follows

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace 'processx' 3.3.1 is being loaded, but >= 3.4.0 is required
Calls: <Anonymous> ... namespaceImportFrom -> asNamespace -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'callr'
* removing 'C:/Users/R-user/Documents/R/win-library/3.6/callr'
Warning in install.packages :
  installation of package ‘callr’ had non-zero exit status 

I read on some thread that I need to update processx package but I don't know how I go about it. I tried installing processx with dependecies=TRUE but that also didn't work. Can anyone help?

**Comment by jayhesselberth** [comment]
Does this work?
``` r
# install.packages("remotes")
remotes::install_github("r-lib/processx")
```
If not you're better off sorting this out at community.rstudio.com.

**Comment by abodnahk** [comment]
this didn't work but i posted a query at rstudio community, thanks for your help!
