### ISSUE TITLE
MPL license not displayed properly

### ISSUE THREAD

**Issue by asardaes** [r-lib/pkgdown#1084]
Example [here](https://asardaes.github.io/table.express/index.html). Not sure why it displays like `MPL/1.1/'>MPL/1.0/'>MPL/1.1/'>MPL-2.0`

**Comment by jayhesselberth** [comment]
Same problem with https://github.com/Rdatatable/data.table/pull/3677

**Comment by jayhesselberth** [comment]
This is because the `SSS` field in the license db isn't defined for `MPL`, so you can't look up `License: MPL-2.0`. Just need to adjust the tibble for MPL licenses.

``` r
library(tidyverse, quietly = TRUE)
library(fs)

path <- path(R.home("share"), "licenses", "license.db")
db <- tibble::as_tibble(read.dcf(path))

db[db$Abbrev == "MPL" & !is.na(db$Abbrev), ]
#> # A tibble: 3 x 12
#>   Name  Abbrev Version SSS   OSI   FSF   File  URL   FOSS  Extensible
#>   <chr> <chr>  <chr>   <chr> <chr> <chr> <chr> <chr> <chr> <chr>     
#> 1 Mozi… MPL    1.0     <NA>  open… free… <NA>  http… yes   <NA>      
#> 2 Mozi… MPL    1.1     <NA>  open… free… <NA>  http… yes   <NA>      
#> 3 Mozi… MPL    2.0     <NA>  open… free… <NA>  http… yes   <NA>      
#> # … with 2 more variables: Restricts_use <chr>, Note <chr>
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
