### ISSUE TITLE
Parsing \dontrun fails with conditionals

### ISSUE THREAD

**Issue by agila5** [r-lib/pkgdown#1087]
I tried running the examples in the documentation of the do function (https://github.com/tidyverse/dplyr/issues/4394 ) and they seem to work fine. I think that the issue in the documentation is linked to the pkgdown package. The examples with \dontrun fails if they are surrounded by conditionals like

```r
if (TRUE) {
\dontrun{
something
}
}
```

**Comment by IndrajeetPatil** [comment]
Related to https://github.com/r-lib/pkgdown/issues/976

**Comment by agila5** [comment]
I think the problem is that `pkgdown` does not run examples properly if there are both conditional statements (like if clauses) and \dontrun as you can see on the [dplyr website](https://dplyr.tidyverse.org/reference/do.html) or https://github.com/tidyverse/dplyr/issues/4394. If you manually run the examples in the `do()` function help page they all run just fine so it's not a problem of the examples. They fail only on the website help page. 

I tried to create a minimal example of this problem [forking](https://github.com/agila5/foofactors) the foofactors repository (since this is the simplest example of an R package I know) and I modified it creating two new functions: `fbind_dontrun()` and `fbind_if_dontrun()`. They are identical to `fbind` but I modified the examples with `\dontrun{...}` and `if (TRUE) \dontrun{...}`. If you run `pkgdown::build_site()` and look at the examples of `fbind_dontrun()` and `fbind_if_dontrun()` you should the same behaviour I described above:

<img width="514" alt="test_if_dontrun_example" src="https://user-images.githubusercontent.com/22221146/63760421-9247d280-c8bf-11e9-82ac-2a69c91134ff.png">

I hope it's clear.
