### ISSUE TITLE
document ways to link to other pkgdown sites more prominently

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#1088]
We just had a bit of a hard time with TDD participants figuring out how to link to other pkgdown url (a vignette, in our case) on the same website.

Between the [linking syntax in markdown-roxygen2](https://cran.r-project.org/web/packages/roxygen2/vignettes/markdown.html) and `autolink_html()` it can be a little hard to figure out what to link how.
(Linking via roxygen2 is very different from `autilink_html()` obviously, but users might expect it in *one* place).

Feel free to close if this is an isolated impression.

Would be happy to add a PR as a suggestion for this.

cc @rivaquiroga

**Comment by jayhesselberth** [comment]
There is already a linking vignette in the [dev version](https://pkgdown.r-lib.org/dev/articles/linking.html); it's focus is linking between pkgdown websites but a section on linking to internal pages would be helpful.

This section might include:

- referencing specific internal pages by file name or URL
- linking to vignettes specifically with `vignette("pkgdown")`.
- others?

**Comment by maxheld83** [comment]
my bad, I missed that @jayhesselberth.

Perhaps a link to the link syntax in roxygen2 [with markdown](https://cran.r-project.org/web/packages/roxygen2/vignettes/markdown.html) and [without](https://cran.r-project.org/web/packages/roxygen2/vignettes/formatting.html#links)
