### ISSUE TITLE
Automatically edit .Rbuildignore to add ^docs$ in the package for which build_site is run

### ISSUE THREAD

**Issue by talgalili** [r-lib/pkgdown#1093]
The .Rbuildignore file needs to have ^docs$ in it so that the CRAN checks would NOT complain about the rouge folder "doc" in the root.

**Comment by cderv** [comment]
It seems that it is already there
https://github.com/r-lib/pkgdown/blob/e3cee56df1eaa875b86171427a3a0eb3d5157b71/.Rbuildignore#L4-L6

Did you mean something else ?

**Comment by jayhesselberth** [comment]
We could `usethis::use_build_ignore("docs/`) in `build_site()`.

**Comment by cderv** [comment]
@talgalili it make sense now, I did not understand that at first!

This is what `usethis::use_pkgdown` is doing and what I use to set up pkgdown inside a package. 

Do you think this is not enough ?

In fact, in pkgdown history, this topic has been already dealt in #710 but a step back has been taken in #865 toward documentation on this topic  https://pkgdown.r-lib.org/reference/init_site.html#build-ignored-files

> We recommend using usethis::use_pkgdown() to build-ignore docs/ and _pkgdown.yml. If use another directory, or create the site manually, you'll need to add them to .Rbuildignore yourself. A NOTE about an unexpected file during R CMD CHECK is an indication you have not correctly ignored these files

**Comment by talgalili** [comment]
@cderv 
I think there are two main options (probably already considered):
1) have `usethis::use_pkgdown` run automatically when running `build_site` (I think this option is the best, possibly with a parameter that by default says TRUE)
2) Add this line to the main README.md doc (having it mentioned only in ?init_site is not enough, since the default instruction is to simply run `build_site`, even though this, out of the box, will lead to a fail in the CRAN check).

What do you think? (should we proceed with option 1 or 2 moving forward)
