### ISSUE TITLE
Use textVersion arg of citEntry to build the text from authors.html

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1096]
See e.g. pavo:

* `authors.html`: http://rafaelmaia.net/pavo/authors.html
* `CITATION` file: https://raw.githubusercontent.com/rmaia/pavo/cfcd0b8a30014c13973c326fb280282c451496f7/inst/CITATION

One would expect the text on http://rafaelmaia.net/pavo/authors.html to be:

```Maia R., Gruson H.,  Endler J. A., White T. E. 2019. pavo 2: new tools for the spectral and spatial analysis of colour in R. Methods in Ecology and Evolution, 10(7), 1097-1107```

 as specified by the `textVersion` argument of `citEntry` in the `CITATION` file. But it instead reads: 

```Maia R, Gruson H, Endler JA, White TE (2019). “pavo 2: new tools for the spectral and spatial analysis of colour in R.” Methods in Ecology and Evolution, 10. ```

**Comment by jayhesselberth** [comment]
Closed by #1137
