### ISSUE TITLE
Cleaning the docs/reference folder from the files that may be generated by the examples of the documentation

### ISSUE THREAD

**Issue by choisy** [r-lib/pkgdown#1097]
In this minimalist [repexpkgdown](https://github.com/r-and-gama/repexpkgdown) R package, there is one function, `hello()`, and the example of its documentation creates a file on disk. A consequence of this is that, when using the `pkgdown` package to generate a website for the `repexpkgdown` package, the file created by the example of the `hello()`function is created in the `docs/reference` folder, which we would like to avoid. Is there a way to automatically avoid this?
Thanks for help.

**Comment by jayhesselberth** [comment]
You can prevent the example from running with `\dontrun`:

```r
#' @examples
#' \dontrun{
#' write.csv(mtcars, "mtcars.csv")
#' }

```

**Comment by choisy** [comment]
Yes, we thought of that too, but `\dontrun` is not a satisfying solution for us as we would like the examples to be run when we look at the documentation of the functions. What we are doing now is that we have a wrapper around the `pkgdown::build_site()` function that cleans the `docs/reference` folder after the site is built. We were thinking that adding such a cleaning functionality directly to the `pkgdown::build_site()` function would be something you may consider.

**Comment by hadley** [comment]
You won't be able to get a package on CRAN if it writes to the working directory; I think that suggests this isn't pkgdown's problem to handle.

(Thanks for the minimal reprex package!!)

**Comment by choisy** [comment]
Ah? Thanks for the info about CRAN!
(and thanks for pkgdown too!)
