### ISSUE TITLE
List non-exported functions separately?

### ISSUE THREAD

**Issue by cboettig** [r-lib/pkgdown#11]
The latest iteration of staticdocs look great, love that it pulls in my readme.md file.  

I write Roxygen documentation for internal functions as well as those I export for the user, but it's rather confusing to see them all listed together in the output documentation (perhaps that's the standard R manual behavior -- shows I don't browse the pdf manuals much).  It would be great if these could be listed as "internal" or not shown?  

Also minor issue: seems like staticdocs is missing an import/dependency on the `markdown` package at the moment.

**Comment by wlandau-lilly** [comment]
What about other keywords? Could these be used to categorize different functions in the reference section? I picture the code like this:

```r
#' foo
#' @export
#' @keywords group1
foo <- function(...){...}

#' bar
#' @export
#' @keywords group1
bar <- function(...){...}

#' baz
#' @export
#' @keywords group2
foo <- function(...){...}
```

which would generate a `_pkgdown.yml` with:

```r
- title: group1
  contents:
  - '`foo`'
  - '`bar`'
title: group2
  contents:
  - '`baz`'
```

**Comment by wlandau-lilly** [comment]
I realize that each function may have multiple keywords. Maybe we could just use the first one for the `title`?
