### ISSUE TITLE
incorrect tabular to HTML conversion

### ISSUE THREAD

**Issue by espinielli** [r-lib/pkgdown#1100]
I created a tiny [`testpackage`](https://github.com/espinielli/testpackage) R package (a little bit like  `{pkgdown}tests/testthat/assets/site-empty`) in order to make the issue I am experiencing reproducible.
(It can be freely used should it be of inspiration to implement a testcase/fix.)

The package has just one `f.R` file defining an empty function with a table (tabular) in its description section. 
It is possible to see that the `man/f.Rd` file is correctly generated. 

Here is a screenshot of the relevant help page in RStudio:

![help-rstudio](https://user-images.githubusercontent.com/891692/62541435-0dd2d880-b85a-11e9-992a-2b6941a0b94f.png)

Inspecting the underlying HTML (which I think is generated on the fly?) in the RStudio IDE you see the relevant correct HTML.

![help-inspected-rstudio](https://user-images.githubusercontent.com/891692/62541551-4672b200-b85a-11e9-9923-08bb98314abd.png)

On the other hand when the site is built via `pkgdown::build_site()` the table is incorrectly produced (and the **Description** and **Usage** headings are missing but that seems to be a design choice in `pkgdown` generation of the help page):

![help-pkgdown](https://user-images.githubusercontent.com/891692/62541607-64d8ad80-b85a-11e9-8db5-099f8f46573d.png)

Also from the generated HTML is possible to see the troubled HTML (see in the `docs/reference/f.html`). Here is a screenshot from the Chrome inspector:

![help-inspected-pkgdown](https://user-images.githubusercontent.com/891692/62541775-be40dc80-b85a-11e9-9beb-d35bf79b0e35.png)

**Comment by jayhesselberth** [comment]
This table renders correctly for me using current master. At least one bug related to table rendering was [fixed](https://pkgdown.r-lib.org/dev/news/index.html#improvements-to-rd-translation) in the development version.

**Comment by espinielli** [comment]
Yes, I confirm that latest on master fixes the problem.
(I am going to use the github version in my TravisCI build/site build till next CRAN will come out)
Thanks!
