### ISSUE TITLE
Missing bootswatch themes

### ISSUE THREAD

**Issue by sharlagelfand** [r-lib/pkgdown#1102]
these bootswatch themes aren't working in `pkgdown`:
* [pulse](https://bootswatch.com/pulse/)
* [sketchy](https://bootswatch.com/sketchy/)
* [minty](https://bootswatch.com/minty/) 
* [solar](https://bootswatch.com/solar/)
* [litera](https://bootswatch.com/litera/)
* [materia](https://bootswatch.com/materia/)

ty!

edit: unless pkgdown, like shiny, only supports bootstrap 3 - in which case it makes sense why these new themes don't work!

**Comment by ms609** [comment]
The link to the minty theme is

https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/minty/bootstrap.min.css

So it appears that the version 4 themes are not available -- presumably this is more complex than just updating a link?

**Comment by Bisaloo** [comment]
@ms609, see https://github.com/r-lib/pkgdown/pull/1111 for the current discussion / work to migrate to bootstrap 4
