### ISSUE TITLE
DOI Rd macro is broken with pkgdown

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1113]
As far as I can tell, this was working before because I never noticed this issue.

`\doi{}` Rd macro is broken in pkgdown pages, as shown in https://rafaelmaia.net/pavo/reference/voloverlap.html#references

https://github.com/rmaia/pavo/blob/fdb12447e31bed7a8cf01cc1c43aff15fd3a6530/R/voloverlap.R#L64-L65

gives

> Maia, R., White, T. E., (2018) Comparing colors using visual models. Behavioral Ecology, ary017 character(0)doi: 10.1093/beheco/ary017

**Comment by Bisaloo** [comment]
I tried to have a look but can't pinpoint the exact source of the issue, sorry.

Maybe related to this??? No idea.

```r
test <- tools::parse_Rd("~/pavo/man/voloverlap.Rd", encoding = "UTF-8")
```

> Maia, R., White, T. E., (2018) Comparing colors using visual models.
Behavioral Ecology, ary017 \Sexpr[results=rd,stage=build]{tools:::Rd_expr_doi("10.1093/beheco/ary017")}

```r
set_classes(test)
```

> Maia, R., White, T. E., (2018) Comparing colors using visual models.
Behavioral Ecology, ary017 \Sexpr[results=rd,stage=build]{tools:::Rd_expr_doi("#1")}10.1093/beheco/ary017[results=rd,stage=build]{tools:::Rd_expr_doi("10.1093/beheco/ary017")}

```r
set_class(test)
```

> Maia, R., White, T. E., (2018) Comparing colors using visual models.
Behavioral Ecology, ary017 \Sexpr[results=rd,stage=build]{tools:::Rd_expr_doi("10.1093/beheco/ary017")}

**Comment by hadley** [comment]
Just tried this now and it seemed fine.
