### ISSUE TITLE
build_news could optionally not add CRAN release date

### ISSUE THREAD

**Issue by jangorecki** [r-lib/pkgdown#1118]
Adding date to CRAN releases in while rendering `news/index.html` is a nice feature.
Yet if NEWS.md has already those dates in the content, then it makes that information duplicated.
One option is to remove dates from NEWS.md, so `news/index.html` will have only the one it produces. The downside of it is that readers of NEWS.md directly (not html on pkgdown website) won't have date information available.
Would be useful to have an option in yaml file to disable generation of those dates.

**Comment by MichaelChirico** [comment]
As noted in this comment, there also seems to be an issue w parsing dates being handled inconsistently:

https://github.com/Rdatatable/data.table/pull/3677#issuecomment-526429871

Shall I file a separate issue for that?

**Comment by yiluheihei** [comment]
Add a parameter directly in `build_news(add_cran_date = TRUE)`? And if the cran dates have been in `NEWS.md`,  set the `add_cran_date = FALSE` to avoid building duplicated dates.   

`add_cran_date = TRUE`
![屏幕快照 2019-08-31 下午6 50 04](https://user-images.githubusercontent.com/6010251/64063233-20a3b780-cc24-11e9-8c94-366322d86efd.png)

`add_cran_date = FALSE`
![屏幕快照 2019-08-31 下午6 49 41](https://user-images.githubusercontent.com/6010251/64063238-2c8f7980-cc24-11e9-8385-8a7cdf113e40.png)

@hadley What about your opinion?

**Comment by hadley** [comment]
I think it's better to add parameters to the yaml (so the way pkgdown is run is captured by git), rather than the function.

**Comment by yiluheihei** [comment]
add parameter (e.g. `add_cran_date`) to `_pkgdown_yml` to control whether add cran date to the  `news/index.html`

```
news: 
  - add_cran_date: TRUE
```

**Comment by hadley** [comment]
Sounds good, thanks!
