### ISSUE TITLE
vignettes Rmd figures missing, could be embedded into html

### ISSUE THREAD

**Issue by jangorecki** [r-lib/pkgdown#1120]
Vignettes that are being build with pkgdown are not matching vignettes that are built during package building.

----

- During package built when vignette is being rendered figures produced in Rmd code chunks are embedded in resulting html.

https://jangorecki.gitlab.io/-/data.table/-/jobs/282035528/artifacts/bus/integration/cran/library/data.table/doc/datatable-sd-usage.html

- On the other hand when pkgdown renders vignette it expects figures to be available externally to html, for example under the location used by `fig.path` Rmd chunk option.

https://jangorecki.gitlab.io/-/data.table/-/jobs/282035528/artifacts/bus/integration/cran/articles/datatable-sd-usage.html
note two missing plots, one which is present was not produced by Rmd code chunk

----

IMO pkgdown should behave consistently to how R handle that, or at least give an option for that. Maybe there is such option already?

**Comment by hadley** [comment]
Are you overriding the default Rmarkdown options? The process by which a vignette is injected into the pkgdown site is delicate/fragile because it requires carefully stitching together two templating systems (pandoc and pkgdown/whisker). This means we have relatively little ability to handle vignette customisation, but it should work out of the box for vignettes that use `html_vignette`.

**Comment by MichaelChirico** [comment]
Here's the YML for the [vignette in question](https://github.com/Rdatatable/data.table/blob/master/vignettes/datatable-sd-usage.Rmd):

```
title: "Using .SD for Data Analysis"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
    number_sections: true
vignette: >
  %\VignetteIndexEntry{Using .SD for Data Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
```

**Comment by hadley** [comment]
Oh it's actually the setup chunk that's the problem: https://github.com/Rdatatable/data.table/blob/master/vignettes/datatable-sd-usage.Rmd#L16-L25

**Comment by jangorecki** [comment]
thanks @hadley
removing `fig.path` from individual chunks and from initial `knitr::opts_chunk$set` solved the problem.
https://jangorecki.gitlab.io/data.table/library/data.table/doc/datatable-sd-usage.html
https://jangorecki.gitlab.io/data.table/articles/datatable-sd-usage.html
