### ISSUE TITLE
Add timestamp when site was built

### ISSUE THREAD

**Issue by jangorecki** [r-lib/pkgdown#1122]
Somewhere in the footer, maybe next to

> Site built with pkgdown 1.3.0.9100.

there could timestamp added

**Comment by jayhesselberth** [comment]
Probably better in the site `pkgdown.yml` file.

**Comment by hadley** [comment]
I was thinking we could make it available as a template variable, but not use it in the default template

**Comment by hadley** [comment]
Looking at this now I think putting in `pkgdown.yml` is probably all we need
