### ISSUE TITLE
Links don't work in the linking vignette

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1124]
The dplyr links aren't generated in the [rendered version](https://pkgdown.r-lib.org/dev/articles/linking.html):

https://github.com/r-lib/pkgdown/blob/5f6ce0c2f503737c5d875657ab29234f6600aaae/vignettes/linking.Rmd#L29-L30

But I just confirmed that the dplyr links are fine in a local build. Maybe an issue with the deploy on travis?

**Comment by hadley** [comment]
I bet it's because dplyr isn't installed. Let me change it.
