### ISSUE TITLE
avoid warning about documented but unexported functions?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pkgdown#1132]
I have some unexported functions in my package, documented with roxygen. When I call `pkgdown::build_site()`, I see:

```
── Building function reference ─────────────────────────────────────────────────
Warning: Topics missing from index: bootstrap, isolate, renv-package, run, update
```

But these are topics associated with un-exported functions; that is, it's expected that these don't show up in the index.

I'm guessing this is more complicated than it looks at first glance since there isn't necessarily any direct mapping between a piece of R documentation and an actual exported R object / function.

(of course this is just a warning and everything else works fine so not really very high priority)

**Comment by hadley** [comment]
Generally we don't document unexported functions. Maybe you just need `@noRd` or `@keywords internal`?
