### ISSUE TITLE
build_home(): reduced priority for "index.Rmd" in pkgdown v1.4

### ISSUE THREAD

**Issue by mrustl** [r-lib/pkgdown#1136]
While in [pkgdown v1.3](https://github.com/r-lib/pkgdown/releases/tag/v1.3.0) the priority for building the home **index.html** was as follows: 
https://github.com/r-lib/pkgdown/blob/42971af1df065ab4e804ce3ee741192468c8bbd4/R/build-home-index.R#L9

It was changed with [pkgdown v1.4](https://github.com/r-lib/pkgdown/releases/tag/v1.4.0)  to: 
https://github.com/r-lib/pkgdown/blob/383c7eebf71667bd0265248caec618606e99454f/R/build-home-index.R#L8

In order to be backward compatible, it would be great if the priority could be changed back to the one used in pkgdown v1.3 or as follows:

`c("index.md", "index.Rmd", "README.md",  "README.Rmd") `

This would be really helpful as our > 40 company open-source R package repositories (https://kwb-r.github.io/status), which all use **pkgdown**, rely on the fact that **index.Rmd** is prioritised higher than **README.md**

**Comment by hadley** [comment]
pkgdown no longer renders `.Rmd` to `.md`, so I don't think changing the order of that vector will help you. Instead, I think you'll need to add a `rmarkdown::render()` in your deployment process.

**Comment by mrustl** [comment]
@hadley thanks for explaining this. This was not obvious for me as the pkgdown v1.4 documentation just mentions: 

> build_home() no longer re-builds README.Rmd 
https://pkgdown.r-lib.org/news/#new-features

In addition listing the ".Rmd" files in build_home_index() is counterintuitive:
https://github.com/r-lib/pkgdown/blob/383c7eebf71667bd0265248caec618606e99454f/R/build-home-index.R#L8

For being more explicit on this I propose https://github.com/r-lib/pkgdown/pull/1140
