### ISSUE TITLE
Failed to parse example code using the %in% operator

### ISSUE THREAD

**Issue by jranke** [r-lib/pkgdown#1149]
When building my [reprex package](https://github.com/jranke/percent.sign) containing the `%in%` operator in the example code of the help file, I get

```
── Building function reference ─────────────────────────────────────────────────
Loading percent.sign
Reading 'man/test_percent_sign.Rd'
Writing 'reference/test_percent_sign.html'
Warnmeldungen:
1: Unknown tag: COMMENT/tag 
2: Failed to parse example for topic 'test_percent_sign' 
```

The first warning is issued in the function `can_parse()` because the example tag contains a line tagged `COMMENT` instead of `RCODE`. So the problem seems to be caused when the pkgdown representation of the Rd file is created.

**Comment by hadley** [comment]
That's not valid `.Rd` code because you didn't escape the Rd comment symbol

<img width="458" alt="Screenshot 2019-09-19 at 7 20 16 AM" src="https://user-images.githubusercontent.com/4196/65243443-fc622a80-daad-11e9-8533-b99e76c5f43b.png">

**Comment by jranke** [comment]
Ah, I see, sorry for the noise!
