### ISSUE TITLE
Do not show \testonly{} examples

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdown#1162]
These are for testing only... so I don't think they have to be in the manual.

**Comment by hadley** [comment]
The problem (IIRC) is dealing with the whitespace that they leave behind (outside of the `\testonly{}`)

**Comment by gaborcsardi** [comment]
You mean if the whole `\examples{}` block is `\testonly{}`? Or which whitespace? I guess we could just omit it completely from the output (but run it), unless the whole section is `\testonly{}` in which case we can remove the section altogether, no?

**Comment by hadley** [comment]
There's a fairly detailed comment in the commit that did this

**Comment by hadley** [comment]
Superseded by #1236, I think
