### ISSUE TITLE
Function reference: source url when package is in a subdirectory

### ISSUE THREAD

**Issue by erikcs** [r-lib/pkgdown#1164]
When building the package reference section for a R package that is not in the root folder of a github repo the <Source: "github link to .R file"> link does not take this into account.

Example:

The package is stored under [github.com/"package-name"/r-package/grf](https://github.com/grf-labs/grf/tree/master/r-package/grf), but the [Source: "filename.R"](https://grf-labs.github.io/grf/reference/regression_forest.html) link in Reference links directly to the repo root folder.

Is it possible to append this information somewhere when pkgdown generates the Source url?

Thank you very much (for a great package)

**Comment by StrikerRUS** [comment]
Hi @erikcs !

Please take a look at this my comment: https://github.com/r-lib/pkgdown/issues/1152#issuecomment-536182165. Maybe it can help you.

**Comment by erikcs** [comment]
Thank you @StrikerRUS, that worked great! (duplicate of #1152)
