### ISSUE TITLE
Amend vignette-name rule for "Get Started"?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/pkgdown#1166]
This question was spurred by this vignette naming discussion at r-lib/usethis#830 - the gist was:

If a package name has a dot, e.g. `acme.data`, we cannot have a vignette with the same name because vignette names cannot contain dots. The motivation was to have a "Get Started" article on a pkgdown site.

As far as I know, the dot is the only legal delimiter character (non alphanumeric) in a package name.

To get around this, could the pkgdown rule be amended to "strip" any dots from package names? 

This way, a package `acme.data` could have a pkgdown "Get Started" vignette named `acmedata.Rmd`. 

Here's (what I think is) the operative line:

https://github.com/r-lib/pkgdown/blob/d1d10cf597185491e399a161038d7f6bb4e90809/R/navbar.R#L71 

Could something like this be useful?

```r
# strip dots to allow matching for packages with dots in the name
pkg_intro <- vignettes$name == gsub("[.]", "", pkg$package) 
```

If so, happy to make a PR. Thanks!

**Comment by hadley** [comment]
Yes, that sounds reasonable, and a PR would be helpful, thanks!

**Comment by maelle** [comment]
A related question/feature request (hence my asking here): could the "Get started" rule also apply to article names i.e. if there's a non-vignette article called pkg.Rmd, could it be detected?

**Comment by hadley** [comment]
@maelle from a quick look at the code, I think should already be the case? Specifically, how is your article not a vignette?

**Comment by maelle** [comment]
Sorry if I'm missing something. It's under [vignettes/articles](https://github.com/ropensci/ropenaq/blob/master/vignettes/articles/ropenaq.Rmd) ([website](https://docs.ropensci.org/ropenaq/))

**Comment by maelle** [comment]
I'm now also wondering whether it'd make sense to have these live under articles/filename.html instead of articles/articles/filename.html. :thinking: but this is getting off topic for this issue. For info I used `usethis::use_article()`.

**Comment by hadley** [comment]
Oh no I remembered; the vignette "name" includes the path, so you get `article/packagename` which doesn't match.

**Comment by maelle** [comment]
Thank you 😺

**Comment by k-tatgenhorst** [comment]
As I am researching another naming issue for vignettes I stumbled on this. I can see how this solution could lead to naming collisions:   acme.data could some perhaps later create an acmedata package?
Just a thought, I see this is closed.
