### ISSUE TITLE
manual "seealso" entry does not produce links

### ISSUE THREAD

**Issue by jangorecki** [r-lib/pkgdown#1172]
in Rd file `seealso` section
```Rd
\seealso{
  \code{\link{shift}}, \code{\link{data.table}}
}
```
renders to a urls properly using base R html manual [(example)](https://rdatatable.gitlab.io/data.table/library/data.table/html/shift.html) while it does not render to urls in pkgdown [(example)](https://rdatatable.gitlab.io/data.table/reference/froll.html)

**Comment by hadley** [comment]
I can't reproduce this locally, so I think you're going to have to make a minimal reprex 😞

**Comment by hadley** [comment]
Please feel free to open a new issue if you can figure out a reprex.
