### ISSUE TITLE
h2 should not be sticky

### ISSUE THREAD

**Issue by slowkow** [r-lib/pkgdown#1181]
I was just reading https://pkgdown.r-lib.org/reference/build_home.html when I noticed a bug.

It appears that one of the `<h2>` elements is sticky, but it should not be.

Here's what I see:

![ezgif com-optimize](https://user-images.githubusercontent.com/209714/69200053-003f1700-0b08-11ea-9506-8435ff0bdb42.gif)

**Comment by maelle** [comment]
The header has the same ID ("sidebar") as the actual sidebar. The actual sidebar is styled by

https://github.com/r-lib/pkgdown/blob/d0b233e7966dc86c2b315f880deead3c7f9a5a02/inst/assets/pkgdown.css#L103-L122

One could rename the header, or rename the actual sidebar maybe?
