### ISSUE TITLE
table colgroup col width

### ISSUE THREAD

**Issue by slowkow** [r-lib/pkgdown#1182]
I made a table in a file `vignettes/examples.Rmd`. I'm not happy with the width of the columns.

Specifically, the first column is set to 20% but I would like it to be 25%.

```html
<table class="table">
<colgroup>
<col width="20%">
<col width="16%">
<col width="64%">
</colgroup>
```

Questions:

1. How are these percentages calculated?
2. How can I override the defaults with my own preferences?

**Comment by hadley** [comment]
I suspect its pandoc doing this, well before it gets to pandoc — you might try looking at the rendered vignette locally.
