### ISSUE TITLE
Breaking api change in rmarkdown

### ISSUE THREAD

**Issue by jeroen** [r-lib/pkgdown#1187]
Our pkgdown builds started failing with:

```r
Error in rmarkdown::find_external_resources(input_path, "UTF-8") : 
  unused argument ("UTF-8")
```

Looks like rmarkdown [has dropped the encoding parameter](https://github.com/rstudio/rmarkdown/commit/3f92bec302262389a9d4e4e39b7e99c5dc7a269d) in `find_external_resources()`.

**Comment by hadley** [comment]
Looks like UTF-8 always was the default, so just removing this argument shouldn't cause any problems.

**Comment by cderv** [comment]
This is a change in current dev version of rmarkdown for 1.19 and reported in [NEWS](https://github.com/rstudio/rmarkdown/blob/master/NEWS.md#rmarkdown-119)

`encoding = "UTF-8"` was the default but there is not more `encoding` argument in `rmarkdown::find_external_resources`
https://github.com/rstudio/rmarkdown/commit/3f92bec302262389a9d4e4e39b7e99c5dc7a269d#diff-f50368e00f0f6725e3e6fd6ea9982408L53

`pkgdown` used the default but used it by specifying the `encoding` argument
https://github.com/r-lib/pkgdown/blob/923eea8c4379e200640a8c98578e82d335561478/R/rmarkdown.R#L48-L50

there should not be an issue with current `rmarkdown` CRAN version, and a fix should be apply for this breaking change for next version - other part of the code should be check too I guess.
