### ISSUE TITLE
links of references in readme not parsed 

### ISSUE THREAD

**Issue by ferroao** [r-lib/pkgdown#1199]
Hi, this is unexpected:

readme, refs at the end with links. https://gitlab.com/ferroao/idiogramFISH
pkgdown: same readme with refs without links: https://ferroao.gitlab.io/idiogramFISH/

best,

**Comment by hadley** [comment]
I suspect you need to wrap them in `<>` if you want them formatted as links.

**Comment by ferroao** [comment]
Seems this has been fixed in pkgdown
