### ISSUE TITLE
Suggestion: Use more sensible default value for pkgdown.internet

### ISSUE THREAD

**Issue by AshesITR** [r-lib/pkgdown#1202]
https://github.com/r-lib/pkgdown/blob/b7ca56bf8a40fc9166b3f44b50b85b341c3d1cdb/R/utils.r#L117

The default for `pkgdown.internet` is `TRUE` meaning you always need to set `options(pkgdown.internet = FALSE)` if you're offline and remember to turn it back on when you go back online.

Since `pkgdown` needs `curl` anyway I suggest setting the default value to `curl::has_internet()`. That way, `pkgdown` will use an available internet connection by default but not error out if there is no internet connection.

The required change would be minimal (change the line to `getOption("pkgdown.internet", default = curl::has_internet())`). I will gladly submit a PR if that is necessary.

**Comment by hadley** [comment]
Checking for the presence or absence of the internet is not a simple test, so I don't think this would be a good idea.

**Comment by AshesITR** [comment]
Well, it is implemented by a DNS resolution attempt for google.com.
One could try accessing cloud.r-project.org - the domain that will cause the error message anyway.
