### ISSUE TITLE
README badges in `README` are not getting rendered

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#1207]
- README: https://github.com/IndrajeetPatil/ipmisc/blob/master/README.md

![image](https://user-images.githubusercontent.com/11330453/72661375-68f82200-39d9-11ea-9261-2985cfccaed5.png)

- pkgdown: https://indrajeetpatil.github.io/ipmisc/

![image](https://user-images.githubusercontent.com/11330453/72661380-76ada780-39d9-11ea-8897-b7e991deabb8.png)

**Comment by hadley** [comment]
@IndrajeetPatil you have filed many issues across the tidyverse and you appear to be systematically failing to put in any real effort into solve your problems yourself. Obviously the badges work just fine for many other packages, so you could start by figuring out what makes your readme different.

**Comment by IndrajeetPatil** [comment]
For anyone who might run into this issue in the future, `pkgdown` will not render `README` badges if the first heading of `README` starts with backticks. I am not sure why.

The current **workaround** is to literally add anything before the first heading and that will make the badges re-appear on the website. 

For example, I got the badges to [reappear](https://indrajeetpatil.github.io/ipmisc/) by including `x` before the first heading:

![image](https://user-images.githubusercontent.com/11330453/74876504-14dbb700-5364-11ea-94be-ea4c7ce603be.png)

**Comment by maelle** [comment]
In such cases I'd recommend adding delimiters to the badges paragraph see e.g. https://github.com/r-hub/rhub

https://github.com/r-lib/pkgdown/pull/996/files
