### ISSUE TITLE
Paragraph flattening adds excess paragraph tags

### ISSUE THREAD

**Issue by nteetor** [r-lib/pkgdown#1208]
I've been struggling with this problem, which for the longest time I assumed was buried in rmarkdown or pandoc. 

The `flatten_para()` pkgdown helper is adding excess paragraph tags, which can produce unwanted html markup in the generated reference pages.

This is the output you would see using a `buttonGroupInput()` in a shiny app. 

<img width="707" alt="image" src="https://user-images.githubusercontent.com/3228369/72669695-2b0ff380-3a03-11ea-8da6-25ea77b27007.png">

This is what I see on the pkgdown generated page.

<img width="704" alt="image" src="https://user-images.githubusercontent.com/3228369/72669689-1895ba00-3a03-11ea-9fe7-87895a441551.png">

Here is the markup from the generated page.

```html
<div id="flavors" class="yonder-button-group btn-group btn-group-info d-flex" role="group">
<button type="button" class="btn" value="mint"><p></p>
<p>Mint
</p></button>
<button type="button" class="btn" value="strawberry"><p></p>
<p>Strawberry
</p></button>

. . .
```

The markup `<button type="button" class="btn" value="mint">Mint/button>` is converted into 
`<button type="button" class="btn" value="mint"><p></p><p>Mint</p></button>`.

I will see about adjusting the rules of `flatten_para()` to better account for this case. An "easy" check might be to ignore text inside `<!--html_preserve-->`. I'm not certain this is actually easy because it may not be simple to check the context of a potential paragraph location.

**Comment by nteetor** [comment]
For further details please refer to the reprex I've added to the PR.

**Comment by nteetor** [comment]
Here is a live example, https://nteetor.github.io/cascadess/reference/background.html#buttons.

**Comment by nteetor** [comment]
Here is another example, https://nteetor.github.io/cascadess/reference/font.html#weights. I was puzzled to see the fonts were not changing.

![image](https://user-images.githubusercontent.com/3228369/100270959-59f9ce80-2f1e-11eb-90a7-6d2ab21e39be.png)

The text is dropped into one paragraph and the class attribute given to another paragraph. 

![image](https://user-images.githubusercontent.com/3228369/100271427-13f13a80-2f1f-11eb-91cc-49a0e1357565.png)

**Comment by nteetor** [comment]
I'm not coding much these days. I couldn't even say if the problem still exists. I can close the issue or leave it open on the chance someone has a similar problem.

**Comment by hadley** [comment]
In that case, it's probably better to just close, since it doesn't seem to be a widespread problem. Sorry I didn't manage to fix it when you were working on it 😞

**Comment by nteetor** [comment]
Looks like there's a related issue in htmltools, https://github.com/rstudio/htmltools/pull/308
