### ISSUE TITLE
help() should redirect to pkgdown documentation if reference is available, not to rdrr.io 

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/pkgdown#1210]
In my NEWS.md file from https://styler.r-lib.org/dev/news/index.html, I have this

> [...] See `help("caching")` for details. [...]

I can't / don't want to use `caching()` because it's a topic ([source](https://github.com/r-lib/styler/blob/master/R/ui-caching.R#L24-L36)), not a function you can all from the package. Also, I like `help()` (potentially with the pkg argument) because it a valid R command and will work when reading `README.md` or `NEWS.md` from R. 

When clicking on the highlighted `help("caching")`, I am directed to https://rdrr.io/r/utils/help.html (online documentation for `help`), not the pkgdown help site for caching (e.g. https://styler.r-lib.org/dev/reference/caching.html).
I assume that pkgdown falls back to rdrr.io for any function that is not defined in the package, also `help(<function name >)` but in that case, it would be nice to just redirect to the https://styler.r-lib.org/dev/reference/caching.html. Can we make it behave the same as `?<function name >`? This already works well with pkgdown (at least in [`NEWS.md`](https://styler.r-lib.org/dev/news/index.html#styler-1-1-1) of styler it seems).

***
Here is the screenshot from the news html page:

![Screenshot 2020-01-19 at 15 10 31](https://user-images.githubusercontent.com/10477073/72682501-d7b6a780-3acd-11ea-86f9-047121636b49.png)

**Comment by hadley** [comment]
We should fix the `help()` link, but why can't you use `?caching` here?

**Comment by lorenzwalthert** [comment]
You mean I should write `?caching` in `News.md`? I could yes, it would also solve the problem, but I thought I'd report this anyways. If low, prio, feel free to close.

**Comment by hadley** [comment]
As I said, we should fix it, I just wanted to check there wasn't some reason that `?` wouldn't work for you.

**Comment by lorenzwalthert** [comment]
Thanks.
