### ISSUE TITLE
Should pkgdown have a delete_site() function?

### ISSUE THREAD

**Issue by cboettig** [r-lib/pkgdown#1211]
`pkgdown` automatically adds a lot of files to a user's repository.  Many users may not be quite sure what files are created by `pkgdown` (as opposed to, say, created by the many other similar helper functions in the`r-lib` / `devtools` universe).  I am a huge fan of these functions, but I also think it would be consistent with that same motivation of automating the creation from the R command-line if we could also automate the clean-up.  e.g. it would be great if there was a function like `delete_site()` (or maybe `remove_site()` that would reverse the effects of `build_site()`, that could remove components added by pkgdown.  Or perhaps there is a good reason not to do this? Or maybe deleting is too fraught with risk of removing something that wasn't auto-magically created?

**Comment by maelle** [comment]
There's https://pkgdown.r-lib.org/reference/clean_site.html but I'm not sure that's what you were after.

**Comment by cboettig** [comment]
I overlooked that!  very nice.  I think`pkgdown` also creates `_pkgdown.yml` (though it's empty by default?), and I think `pkgdown/` (for favicons), (and presumably updates .Rbuildignore though I suppose that's harmless).  not sure if those should be purged as well?  

@maelle clearly I'm looking for a nice workflow to allow us to quickly swap in the nice `ropensci`-built pkgdown docs in place of whatever I may have created pre-onboarding, so maybe it's good not to delete these other things anyway

**Comment by hadley** [comment]
I don't think `pkgdown/` or `_pkgdown.yml` can be deleted automatically as these are things that the user has explicitly created; they're not automatically generated as part of a routine pkgdown build.
