### ISSUE TITLE
strange behaviour of \eqn

### ISSUE THREAD

**Issue by ferroao** [r-lib/pkgdown#1212]
Hi, I have seen something unexpected.
In the R help (Rd) `\eqn{\mum}` is seen correctly as μm, while in pkgdown (reference) gives error "\mum" (in red)
In contrast  `\eqn{\mu m}`  is seen separated (μ m) in R help (not wanted), while not-separeted in pkgdown: μm.

**Comment by hadley** [comment]
I asked a local latex expert who said `\mu m` would be the usual way of doing this in latex, so I think pkgdown is in the right here.
