### ISSUE TITLE
Add submenu capability

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/pkgdown#1213]
Working with @wendtke at tidyverse dev day, we would like to propose our own issue.

Currently, it is not possible to make sub-menus on pkgdown sites, as you can with regular RMarkdown sites: rstudio/rmarkdown#721. I propose that this be fixed by adding [some css (see `inst/rmd/h/default.html`)](https://github.com/rstudio/rmarkdown/pull/1426/files) to the [pkgdown css file](https://github.com/r-lib/pkgdown/blob/master/inst/assets/pkgdown.css).

Here's an [example](https://ijlyttle.github.io/pkgdownsubmenu/) using [`extra.css`](https://github.com/ijlyttle/pkgdownsubmenu/blob/master/pkgdown/extra.css).

**Comment by jayhesselberth** [comment]
Sounds good, please include a sub-menu config example in the docs.

**Comment by ijlyttle** [comment]
Sounds reasonable; @wendtke is working on a PR.  

Perhaps a few lines could be added to [this yaml example](https://github.com/r-lib/pkgdown/blob/134033d9d744c548c6fbe297bc0fbd1a2f498e83/R/build.r#L153), which would appear [here](https://pkgdown.r-lib.org/reference/build_site.html#yaml-config-navbar).
