### ISSUE TITLE
relative paths of external images in vignette "articles" are not built correctly if folder names contain spaces

### ISSUE THREAD

**Issue by carloscinelli** [r-lib/pkgdown#1218]
This is related to: https://github.com/r-lib/pkgdown/issues/1027

After cloning the repository for `rvest`, I figured out what might be explaining Thierry's problem, which I was also facing. 

It seems that when folder names have spaces (for instance `my folder`), then `build_site()` does build the html with the correct figure paths. 

To reproduce the problem, you can do the following:
- Clone `rvest`
- Include the `rvest` folder inside a folder with a space between names (for instance `my folder/rvest`)
- Run `pkgdown::build_site()`

Then you will see that the figures will not have the correct relative paths.

**Comment by carloscinelli** [comment]
For those currently facing the problem, the easiest solution is to move your project to a folder without spaces.

**Comment by hadley** [comment]
Yes, unfortunately we can't currently support packages with spaces in their paths.

**Comment by thierrygosselin** [comment]
> Yes, unfortunately we can't currently support packages with spaces in their paths.

that was my problem with  #1027, the folder was in Dropbox or iCloud...
