### ISSUE TITLE
development version removed sidebar TOC highlighting 

### ISSUE THREAD

**Issue by carloscinelli** [r-lib/pkgdown#1219]
I'm not sure if this is intended, but the current development version of `pkgdown` here on GitHub removed the automatic sidebar TOC highlighting as you scroll down a post.

I noticed that when reproducing the issue of https://github.com/r-lib/pkgdown/issues/1218 . To reproduce this, you can just clone Rvest and build the site using the default theme with the development version. Then remove the package, reinstall from CRAN, and build the site again.

**Comment by hadley** [comment]
I just looked at https://pkgdown.r-lib.org/dev/articles/linking.html and it seems fine to me.
