### ISSUE TITLE
Markdown content in <details></details> no longer parsed

### ISSUE THREAD

**Issue by peterdesmet** [r-lib/pkgdown#1220]
We've been using the [`<details><summary>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) syntax to collapse more specific installation instructions in the README of our package:

```md
<details>
<summary><strong>Installing Docker</strong></summary>

1. Go to [Docker Desktop](https://www.docker.com/products/docker-desktop).
2. Download Docker for Windows or Mac (free login required) and follow the installation instructions. Note that Docker for Windows requires Microsoft Windows 10 Professional or Enterprise 64-bit: installing Docker _Toolbox_ for previous Windows versions will not work.
3. Open the Docker application. The Docker (whale) icon will appear in your menu or task bar and indicate if it is running correctly.
4. Make local drive(s) available for Docker containers:
    * On Windows: right click the Docker icon > `Settings` > `Shared drives` > Select the drive(s) where you will be processing radar files > Click `Apply`.
    * On Mac: click the Docker icon > `Preferences` > `File sharing` > Add the drive(s) where you will be processing radar files > Click `Apply & Restart`.
5. In R do `check_docker()`.
6. You can now use the bioRad functionality that requires Docker.
</details>
```

Which in pkgdown 1.3.0 rendered nicely as:

<img width="747" alt="pkgdown-1.3.0" src="https://user-images.githubusercontent.com/600993/74340211-ce0b2180-4da5-11ea-9125-1ad7471dec4c.png">

In pkgdown 1.4.1 the Markdown in the `<details>` section is no longer parsed however:

<img width="741" alt="Screenshot 2020-02-12 at 14 37 54" src="https://user-images.githubusercontent.com/600993/74340301-f2ff9480-4da5-11ea-8663-078525270f18.png">

I assume the content is now just parsed as regular HTML. But it was a nice feature that Markdown was parsed in `<details>`: can this be brought back?

**Comment by hadley** [comment]
I just tried it out and it worked fine for me.

**Comment by peterdesmet** [comment]
Odd, I just tried it again (pkgdown 1.4.1) and I still have the same issue. I hope it can be reproduced by:

1. Copy/paste the following somewhere in README.md:

```
<details>
<summary>Heading</summary>

1. Item 1 with [link](https://github.com)
2. Item 2 with `code`

</details>
```

2. This renders fine on GitHub:

<details>
<summary>Heading</summary>

1. Item 1 with [link](https://github.com)
2. Item 2 with `code`

</details>

3. This renders as follows when running `pkgdown::build_home()` or `pkgdown::build_site()` for `pkgdown 1.4.1`:

<img width="671" alt="Screenshot 2020-03-12 at 13 29 50" src="https://user-images.githubusercontent.com/600993/76521673-93101280-6465-11ea-9ba7-859d07d84519.png">

**Comment by hadley** [comment]
Hmmm, weird, now I see the same problem as you.
