### ISSUE TITLE
Sidebar id #sidebar can be shared with section titles

### ISSUE THREAD

**Issue by peterdesmet** [r-lib/pkgdown#1222]
## Issue

1. The pkgdown documentation for `build_home()` has a section title called "Sidebar": https://pkgdown.r-lib.org/reference/build_home.html
2. Section titles automatically get an anchor, in this case `#sidebar`
3. The navigation sitebar in a pkgdown website has that same `#sidebar` ID however, with `position: sticky;`
4. That css gets applied to the section, resulting in the following when scrolling down:

<img width="1008" alt="Screenshot 2020-02-14 at 10 44 34" src="https://user-images.githubusercontent.com/600993/74520495-fca90980-4f17-11ea-91c8-725e5754bb13.png">

## Potential solution

To avoid name clashes, I would use `#pkgdown-sidebar` for the pkgdown sidebar or reference it in relation to its parent container: `... > #sidebar`

**Comment by jayhesselberth** [comment]
Dup of #1181. Fixed in master.
