### ISSUE TITLE
build_home() is not copying figures

### ISSUE THREAD

**Issue by gustavdelius** [r-lib/pkgdown#1225]
The documentation for `build_home()` advises users to store images in `man/figures`. Then build_home() converts links to `man/figures` to links to `docs/reference/figures`. However it does not copy the images from `man/figures` to `docs/reference/figures` and hence all image links stop working.

**Comment by hadley** [comment]
Currently the expectation is that `build_reference()` copies those files. If you're not running `build_site()`, I think it's up to you to make sure you're copying them some other way.

**Comment by gustavdelius** [comment]
I agree that it is easy enough to just call `build_reference()` in addition to `build_home()`, but it is not currently easy for the user to find out that this is needed. So I have submitted a new pull request #1239  to add that information to the section on images on the help page for `build_reference()`.
