### ISSUE TITLE
Improve article index

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1227]
As the number of vignettes in a package grows (e.g. <https://dplyr.tidyverse.org/dev/articles/>), the articles drop down becomes a less attractive way of selecting articles. It also fails to provide any context for the articles, so unless the title is immediately descriptive, it's hard to tell which vignette is most likely to help.

The most natural way to resolve this problem was suggested by @jennybc — scrap the dropdown, and instead use the same tools to organise the articles page as the reference page. This would make it possible to control the order of articles, separate them into categories, and provide an additional text description.

**Comment by jennybc** [comment]
A nice-to-have would be a function that uses the article metadata to inline an annotated, intentionally ordered  (not alphabetical), hyperlink-y bullet list of the articles.
I think this basically exposes the logic behind how the article index would be made anyway. But this allows you to use it elsewhere, such as in the README, index, or Get started article. I think reminding people of all the articles is one of those things where “do repeat yourself” holds.

**Comment by hadley** [comment]
We apparently already have some ability to group and order vignettes: https://pkgdown.r-lib.org/reference/build_articles.html#yaml-config. So I think we're missing two pieces:

* Some easy way to turn off the default navbar dropdown so instead it just takes you directly to the articles index.  Maybe something like this?

    ```yml
    articles:
      navbar: false
    ```
    
* Some way to display additional details about each article. This could either live in `_pkgdown.yml`, but might be better to put in the yaml metadata of the original articles. Maybe call it `abstract`?

**Comment by hadley** [comment]
I'm not sure how to accomplish your second request — currently we don't expect you to take a dependency on pkgdown (since it's pretty hefty) so I don't see how you would call such a function if it existed.
