### ISSUE TITLE
custom css for vignettes

### ISSUE THREAD

**Issue by fmmattioni** [r-lib/pkgdown#1229]
Hi! I have noticed that `pkgdown` somehow doesn't recognize any `css` that we might define in a specific vignette.

For example:

```yml
---
title: "Intro'"
output: 
  rmarkdown::html_vignette:
    css: style.css
vignette: >
  %\VignetteIndexEntry{Intro}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
```

When I try to knit it myself to preview the output it works, but when I `pkgdown::build_site()` the `css` doesn't get recognized.

Anything I might be missing?

**Comment by fmmattioni** [comment]
OK, I have just realized that these all should be inside `extra.css` in the `pkgdown/` folder.. correct?

**Comment by cderv** [comment]
Did you saw this about the behavior of pkgdown ? 
https://pkgdown.r-lib.org/reference/build_articles.html#yaml-header

I think you need to set the option 
```yaml
pkgdown:
  as_is: true
```
so that articles are rendered as you set in their yaml header. 

Could it be what you are looking for ?

**Comment by hadley** [comment]
Thanks @cderv!
