### ISSUE TITLE
Combining external images with vignettes to make pkgdown article

### ISSUE THREAD

**Issue by jeffwong-nflx** [r-lib/pkgdown#1231]
There is a similar, closed issue here: https://github.com/r-lib/pkgdown/issues/1027 which I feel is incomplete.

I have a package with a `vignettes` folder. Inside that folder is another folder called `images`. In the .Rmd I use `knitr::include_graphics(<full path to image file>)` in an Rmd chunk to display the image.
When I knit the vignette, the images render. However, if I use pkgdown the resulting article does not render the images.

I believe this is because the `docs` directory created by pkgdown needs to copy the images from `vignettes/images/`. I can see that the article's .html source file is trying to reference an image located in `images/<my_image.jpg>`, but there is no such directory called `images` inside `docs`. How can I trigger pkgdown to do a copy based on `<full path to image files>` ?

**Comment by hadley** [comment]
See details at https://pkgdown.r-lib.org/reference/build_articles.html#external-files
