### ISSUE TITLE
Think about release workflow

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1248]
* Release to CRAN
* Tag commit — triggers build of main site
* Blog about it
* Add release blog post to releases 
* If `mode: auto` link to blog post only appears in dev version of site

**Comment by hadley** [comment]
Another problem is if you build the NEWS soon after receiving the CRAN email, the NEWS page doesn't get a release date: https://pkgdown.r-lib.org/news/index.html#pkgdown-1-5-0-unreleased

**Comment by jayhesselberth** [comment]
It's hacky but you can fix the NEWS issue on the v1.5.0 page by temporarily changing DESCRIPTION version to 1.5.0, rebuilding site, and using `deploy_site_github()`.

This would add the blog post and update the "Unreleased" status on the v.1.5.0 NEWS page.

**Comment by hadley** [comment]
Yeah, I was thinking more that we should engineer some solution that doesn't require the back.

**Comment by maelle** [comment]
For packages without an associated blog should there be support for NEWS pages & an RSS feed?

**Comment by hadley** [comment]
@maelle that's out of scope I think.

**Comment by maelle** [comment]
Too bad but understandable (given the existing tooling for building actual blogs). :grin:

**Comment by hadley** [comment]
We have resolved this by making writing the blog post part of the pre-release process. In our experience, if you write the blog post _after_ submitting to CRAN, you will inevitably discover some small problem that means you want to do a patch release. This is reflected in latest `usethis::use_release_issue()` checklists.
