### ISSUE TITLE
autolinking for external packages broke

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1250]
Links are missing for `devtools::install_github()` and `usethis::use_pkgdown()` on the [dev home page](https://pkgdown.r-lib.org/dev/).

But `install.packages()` and `pkgdown::build_site()` are linked.

**Comment by hadley** [comment]
Hmmmm, works for me locally. Is something going wrong with the pkgdown action?

**Comment by hadley** [comment]
Ah the problem is that neither usethis nor devtools are installed so pkgdown can't find their urls. This isn't a regression, so I've removed the 1.5 milestone, but I'm not sure how we should resolve this.

**Comment by jayhesselberth** [comment]
You mean aren't installed locally? Or aren't installed by pkgdown?

I'm don't that explains it, because neither usethis nor devtools were installed by the stable version, but they're linked on its home page: https://pkgdown.r-lib.org/

**Comment by hadley** [comment]
I think the previous travis workflow installed devtools.

To fix this problem in the long run, instead of using `find.package()` in `remote_metadata()` we should download and parsed the DESCRIPTION from cran (e.g. https://cloud.r-project.org/web/packages/ps/DESCRIPTION).

**Comment by jayhesselberth** [comment]
Perhaps the github action could install usethis and devtools before the build so that the live pkgdown site will have those functions correctly linked?

**Comment by hadley** [comment]
We could, but they're pretty hefty dependencies. Maybe we could add some way to manually register packages? Or maybe we should just always register devtools since many packages will use it in the readme?

**Comment by jayhesselberth** [comment]
Does github actions cache packages that are installed during a build (like travis does)?

**Comment by hadley** [comment]
Yes it does, but it's still a large number of packages, and it seems like a lot of work just to get two links on the home page 😄

**Comment by hadley** [comment]
I'll figure out something for this release though. I'm thinking about maybe aiming for a release late next week?

**Comment by jayhesselberth** [comment]
Sounds good.

**Comment by hadley** [comment]
Oh, it's not just the package URL that's needed, it's the complete documentation index (in order to map from function name to documentation topic).  That makes it considerably harder to solve the problem at the pkgdown level, so maybe it's just easier to install devtools and usethis.
