### ISSUE TITLE
Extra images in home page sidebar

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1255]
There's a few duplicate RStudio images on the bottom of https://pkgdown.r-lib.org/dev/  in the sidebar under "Dev status".

**Comment by hadley** [comment]
@flying-sheep can you please take a quick look at this, just to make sure this wasn't from your PR?

**Comment by flying-sheep** [comment]
It probably was, easily fixed though. The only problem is that the test fails for weird reasons: https://github.com/r-lib/pkgdown/pull/1174#discussion_r395805457

**Comment by flying-sheep** [comment]
Sorry! I didn’t realize you can pass elements and still do a document-wide search!
