### ISSUE TITLE
Code warnings on the website are printed in native language, not English

### ISSUE THREAD

**Issue by hbaniecki** [r-lib/pkgdown#1261]
What I see in RStudio console running one of the examples in my package (EN language):
![image](https://user-images.githubusercontent.com/32574004/77230627-cead8980-6b95-11ea-9d03-3393763f28ce.png)
What i see on the website in `Reference>*>examples` section (PL language):
![image](https://user-images.githubusercontent.com/32574004/77230619-c3f2f480-6b95-11ea-9aee-4455519a5a86.png)

I have just updated the `pkgdown` package. It wasn't like this before. Not a big deal, but I was wondering if there is any way to enforce EN language.

**Comment by hadley** [comment]
How are you building the site?

**Comment by hbaniecki** [comment]
Using `pkgdown::build_site()` in RStudio console.

**Comment by hadley** [comment]
Then you should be able to set `Sys.setenv(LANGUAGE = "en")` before running to force the errors to appear in English.
