### ISSUE TITLE
Citation links no longer generated

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1265]
#1137 introduced an issue where a formatted citation is no longer on the citations page.

See: https://valr.hesselberthlab.org/authors.html where a link should be above the TEX block. There is an empty `<p>` element on the page where the link should be.

One issue is that `format(cit, style = "textVersion"))` returns an empty string for me. Not sure what the intended effect was here, need some digging.

**Comment by jayhesselberth** [comment]
I think we want to revert to `html`. `style = 'text'` achieves the intended effect, but IMO it's more useful to have the HTML link to the published paper rather than simple text formatting.

**Comment by Bisaloo** [comment]
Because of https://github.com/r-lib/pkgdown/issues/1096#issue-473966499 I think. I can test alternatives if you have another solution in mind.

**Comment by jayhesselberth** [comment]
@Bisaloo I now see why that `<p>` is blank on my page — I don't have a `textVersion` field in my [`CITATION` file](https://github.com/rnabioco/valr/blob/master/inst/CITATION).

The fact that `format(cit, format = 'html')` generates a DOI link (as long as `doi` is defined) that takes you to a published version is very useful. 

One alternative would be to fall back to `html` if `textVersion` is not defined.
