### ISSUE TITLE
How to control the sidebar (Table of Content) font-size

### ISSUE THREAD

**Issue by genomaths** [r-lib/pkgdown#1269]
Hi there
I have been trying (unsuccessfully) to control the sidebar (Table of Content) font-size in the printed HTML files from the Rmd files throughout 'CSS' in several way. It seems to be that there exist an internal control in the package of it. I basically gave up trying myself. The result is an "ugly sidebar" (see for example, https://genomaths.github.io/methylit/articles/MethylIT.html). Could you please give me some tips on how to fix this issue?

**Comment by jayhesselberth** [comment]
Here's the [TOC CSS](https://github.com/r-lib/pkgdown/blob/master/inst/assets/pkgdown.css#L179-L232), which tweaks some of the stock [bootstrap-toc.css](https://github.com/r-lib/pkgdown/blob/master/inst/assets/bootstrap-toc.css).

If I delete your site's extra.css file, your site renders fine, so there's something in that file that's causing the issue. Try deleting sections of that file to isolate the problem.

**Comment by genomaths** [comment]
Thanks a lot. It works; as you said.
