### ISSUE TITLE
unable to deploy from the GitHub version

### ISSUE THREAD

**Issue by kevinwang09** [r-lib/pkgdown#1271]
Hi, I am trying to use the `deploy_site_github` method in combination with travis. 

I noticed that whenever I use the GitHub version (the latest being r-lib/pkgdown@b8434e54fd4894211218bdca75730b7dd3af30e1) I would get [this error](https://travis-ci.org/github/kevinwang09/mcvis/jobs/666680827#L3027)
```
error: the requested upstream branch 'origin/gh-pages' does not exist
```

However, if the CRAN version of `pkgdown` was installed, [this problem goes away](https://travis-ci.org/github/kevinwang09/mcvis/builds/666685003).

The difference between the two commits is [here](https://github.com/kevinwang09/mcvis/commit/e165c4ccb809b4b11d5931e1b2aa15c69920f765).

**Comment by hadley** [comment]
@jimhester can you take a look please?

**Comment by jimhester** [comment]
Should be fixed by my PR.

Also why are you setting `tarball = "."` in your `.travis.yml` file? This should not be necessary.
