### ISSUE TITLE
pkgdown 1.5.0 does not render / evaluate R code chunks

### ISSUE THREAD

**Issue by strengejacke** [r-lib/pkgdown#1282]
For instance, R code in vignettes or the examples from help-pages are not evaluated, thus all results are missing. Reverting back to pkgdown 1.4.1 solved the issue. I've heard from other people having the same issues, so it might not be a specific personal setup.

**Comment by hadley** [comment]
Is this the same as #1278? If so we can't reproduce it, so we need more than a vague indication that other people are having the same problems.

**Comment by strengejacke** [comment]
I'm not sure if it's related to #1278. Here's an example:

Affected paragraph in the vignette:
**Computing the de-meaned and group-meaned variables**

* this is the vignette: https://github.com/easystats/parameters/blob/master/vignettes/demean.Rmd
* website rendered with pkgdown 1.4.1: https://easystats.github.io/parameters/articles/demean.html (html-source: https://github.com/easystats/parameters/blob/8e220b82008f59d41dfbb18234698ca61171ccc6/docs/articles/demean.html#L159)
* website rendered with pkgdown 1.5.0: http://htmlpreview.github.io/?https://github.com/easystats/parameters/blob/pkgdown-problem/docs/articles/demean.html  (html-source: https://github.com/easystats/parameters/blob/e50d4b63b87709ef8f4bdb67f618a0a39c136a0b/docs/articles/demean.html#L166) - you can see that there is something missing


Another example:
First code-chunk is affected...

* related vignette: https://github.com/easystats/parameters/blob/master/vignettes/model_parameters_standardized.Rmd
* website rendered with pkgdown 1.4.1: https://easystats.github.io/parameters/articles/model_parameters_standardized.html
* website rendered with pkgdown 1.5.0: 
http://htmlpreview.github.io/?https://github.com/easystats/parameters/blob/pkgdown-problem/docs/articles/model_parameters_standardized.html

**Comment by jayhesselberth** [comment]
Your package is too big to easily debug. Here's what I see locally:

https://naughty-swartz-8a258c.netlify.com/

github htmlpreview does not seem to render the site correctly, I recommend [using netlify](https://pkgdown.r-lib.org/dev/CONTRIBUTING.html#netlify).

**Comment by strengejacke** [comment]
> github htmlpreview does not seem to render the site correctly

That was just for a quick demonstration, the bug (you can see the missing parts in the html file (source code) directly also occurs in the locally created files as well after uploading to GitHub websites.

But your site renders differnetly again (and probably correct?), I'll download the current dev-version of pkgdown and report what I have found out.

**Comment by strengejacke** [comment]
Ok, these are the (visual) differences:

Rendered with version 1.4.1:
![3](https://user-images.githubusercontent.com/26301769/78161584-f7f7d080-7445-11ea-934c-54278a9cd23c.png)

Rendered with version 1.5.0 and 1.5.0-dev:
![1](https://user-images.githubusercontent.com/26301769/78161669-1cec4380-7446-11ea-85e4-bb8dbf676091.png)

Your example:
![2](https://user-images.githubusercontent.com/26301769/78161619-0940dd00-7446-11ea-857c-f94c46d1e105.png)


As you can see, the first example is as expected. 2nd example misses code chunk and sidebar has wrong CSS. Your example show code chunk, but sidebar has wrong CSS.

**Comment by jayhesselberth** [comment]
I'm not sure what you mean by wrong CSS. The TOC changed to bootstrap-toc in 1.5.0.

**Comment by IndrajeetPatil** [comment]
I can reproduce this issue in a minimal reprex package:
https://indrajeetpatil.github.io/minimalReprex/

- `README` input:

![image](https://user-images.githubusercontent.com/11330453/78165020-009ed580-744b-11ea-832e-0842ad59694b.png)

- `pkgdown` output:

![image](https://user-images.githubusercontent.com/11330453/78164996-f8469a80-744a-11ea-8ee3-99c6a86eaef4.png)

**Comment by jayhesselberth** [comment]
@IndrajeetPatil this is what I see when I build your reprex; seems OK for me:

https://pensive-raman-9450f6.netlify.com/

**Comment by IndrajeetPatil** [comment]
@jayhesselberth My guess is that this issue seems to affect only `pkgdown` websites hosted via GitHub. 

This is the only common thread I see among everyone who is facing this issue. My package websites, @strengejacke's websites, websites mentioned in #1278 are all `github.io`, while your examples are with `netlifly.com`.

This issue always occurs with rendering code chunks in the presence of `<-` operator, as noted also in https://github.com/r-lib/pkgdown/issues/1278#issuecomment-606138502.

**Comment by hadley** [comment]
@IndrajeetPatil the specific host is unlikely to cause any differences. It's more likely to be how you are building the site.

**Comment by strengejacke** [comment]
I used `pkgdown::build_site()` to build the sites, and both locally and on GitHub there are these issues. Rendering issues are expected in the sense that the generated HTML files from pkgdown 1.5.0 do not contain the full HTML code (see my links to the html-source-code files above).

I have no idea why this happens and why output is different from the generated pages by @jayhesselberth and my try to generate the pages?

**Comment by IndrajeetPatil** [comment]
> It's more likely to be how you are building the site.

Me and everyone else facing this issue. 
I have been building all websites using `pkgdown::build_site()` and this change in output occurred when I upgraded from `pkgdown 1.4.0` to `1.5.0`, so pretty sure it has nothing to do with how I am building it since I haven't faced this issue before.

**Comment by hadley** [comment]
Here is a fully reproducible repo: https://github.com/hadley/rendertest. I don't see any problems with rendering at https://hadley.github.io/rendertest/reference/test.html (on the README, in the article, or on the reference page). You can see exactly what code is run to build the site: https://github.com/hadley/rendertest/runs/553246043?check_suite_focus=true#step:9:1.

**Comment by TiagoOlivoto** [comment]
Thanks for the efforts in solving this issue!
I've cloned [Hadley's repo](https://github.com/hadley/rendertest), and ran pkgdown::build_site()
Bellow, a screenshot of the article "test" in my machine.

![mine](https://user-images.githubusercontent.com/34458429/78206063-3310f880-7474-11ea-87d3-deff565948d9.png)
And following the screenshot of the same article in [Hadley's rendered page](https://hadley.github.io/rendertest/reference/test.html)

![Hadley](https://user-images.githubusercontent.com/34458429/78206700-f514d400-7475-11ea-824e-a22323c218f4.png)

It really seems this is a local problem, which I have no idea about that.

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.2 (2019-12-12)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  Portuguese_Brazil.1252      
#>  ctype    Portuguese_Brazil.1252      
#>  tz       America/Sao_Paulo           
#>  date     2020-04-02                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
#>  callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.2)
#>  cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.0)
#>  devtools      2.2.2   2020-02-17 [1] CRAN (R 3.6.2)
#>  digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.3)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.5.3)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
#>  fs            1.3.2   2020-03-05 [1] CRAN (R 3.6.3)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.3)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.5.3)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.1)
#>  knitr         1.28    2020-02-06 [1] CRAN (R 3.6.2)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.0)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.2)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.2)
#>  processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.2)
#>  ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.2)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.1)
#>  remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.2)
#>  rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.3)
#>  rmarkdown     2.1     2020-01-20 [1] CRAN (R 3.6.2)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.2)
#>  stringi       1.4.6   2020-02-17 [1] CRAN (R 3.6.2)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.2)
#>  testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.5.3)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.0)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.6.1)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 3.6.2)
#> 
#> [1] D:/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.2/library
```

<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by IndrajeetPatil** [comment]
Hmm, I have no other guesses then. 

For what it's worth, I have updated my minimal reprex package demonstrating this issue with session info, which might be of some help:
https://indrajeetpatil.github.io/minimalReprex/

**Comment by IndrajeetPatil** [comment]
If I clone Hadley's `rendertest` repo and run `pkgdown::build_site()` locally on my machine, I still see the same problem:

![image](https://user-images.githubusercontent.com/11330453/78219936-da1b8180-74c0-11ea-9ce0-2a1fb667b2d1.png)

**Comment by hadley** [comment]
I've added session info + pandoc version to my test vignette: https://hadley.github.io/rendertest/articles/test.html

It doesn't make sense to put this information in the README, since will capture the information about the computer used to build the README.md, not the computer used to turn the README.md into html.

**Comment by hadley** [comment]
@TiagoOlivoto do you see the same problem if you have an expression like `1 < 2`?

**Comment by strengejacke** [comment]
I just forked your repo, updated to pkgdown 1.5.0 and re-build the site using `pkgdown::build_site()`:

https://github.com/strengejacke/rendertest

https://strengejacke.github.io/rendertest/articles/test.html

**Comment by IndrajeetPatil** [comment]
Okay, comparing Hadley's [test](https://hadley.github.io/rendertest/articles/test.html) and my identical [test](https://indrajeetpatil.github.io/minimalReprex/articles/test.html) vignette session infos, I see the following differences that _might_ explain the difference:

- MacOS versus Windows 
- `fs 1.3.2` versus `fs 1.4.0` 
- `R 3.6.3` versus `R devel` 
- pandoc `2.7.3` versus pandoc `2.9.2.1` (unlikely)

@TiagoOlivoto and @strengejacke Are you also working on Windows machines?

**Comment by strengejacke** [comment]
I just updated pandoc from 2.7.2 to 2.9.2.1, same result:

https://strengejacke.github.io/rendertest/articles/test2.html

**Comment by TiagoOlivoto** [comment]
> @TiagoOlivoto do you see the same problem if you have an expression like `1 < 2`?
@hadley I have no problems with `1 < 2`. The code is also rendered correctly if I change `< -` with `=` 
![Hadley2](https://user-images.githubusercontent.com/34458429/78255595-de9a6700-74cd-11ea-9059-c158e3e4e029.png)

Answering to @IndrajeetPatil, I'm working on a Windows 10 x64 machine.

**Comment by hadley** [comment]
Interesting, I was wondering if `<-` was problematic because of html escaping, but that doesn't seem likely if `<` is ok.

**Comment by hadley** [comment]
@TiagoOlivoto could you please try running this code on your machine:

``` r
pkgdown:::context_set("package", "test")
pkgdown:::highlight_text("x <- 1 + 2")
#> [1] "<span class='no'>x</span> <span class='kw'>&lt;-</span> <span class='fl'>1</span> + <span class='fl'>2</span>"
```

**Comment by TiagoOlivoto** [comment]
> ```r
> pkgdown:::context_set("package", "test")
> pkgdown:::highlight_text("x <- 1 + 2")
> #> [1] "<span class='no'>x</span> <span class='kw'>&lt;-</span> <span class='fl'>1</span> + <span class='fl'>2</span>"
> ```

@hadley here is the results

``` r
pkgdown:::context_set("package", "test")
pkgdown:::highlight_text("x <- 1 + 2")
#> [1] "<span class='no'>x</span> <span class='kw'>&lt;-</span> <span class='fl'>1</span> + <span class='fl'>2</span>"
```
<sup>Created on 2020-04-02 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


I've been trying to change some commands randomly to see the results, and I noticed that if I just run the code and store the results into an object, the code is rendered correctly. If I try calling that object, the problem then arose. 
* The code
![code](https://user-images.githubusercontent.com/34458429/78278442-6db67780-74ec-11ea-8cb1-68f2a05d1777.png)
* The rendered site
![rendered](https://user-images.githubusercontent.com/34458429/78278506-84f56500-74ec-11ea-9b78-6a7b1eb0175c.png)

**Comment by hadley** [comment]
I just realised I used the wrong session info call —  you want to see all the pkgdown dependencies, not the packages used in the current session: https://hadley.github.io/rendertest/articles/test.html

**Comment by hadley** [comment]
Build rendertest site on windows using github actions, and yup, I see the same problem: https://github.com/hadley/rendertest/blob/gh-pages-win/index.html#L82

**Comment by strengejacke** [comment]
But would you say it is related to GitHub, or to Windows, or is the reason for this bug still difficult to locate?

**Comment by hadley** [comment]
The only difference between the two runs is that one is on Windows and one is on mac. That strongly suggests that it's some extremely weird bug on windows.

**Comment by hadley** [comment]
Thanks to @gaborcsardi we now have a simple reprex:

``` r
pkgdown:::context_set("package", "test")
pkgdown:::highlight_text("x <- 100\r\nx")
#> [1] "x <- 100\r\nx"
pkgdown:::highlight_text("x <- 100\nx")
#> [1] "<span class='no'>x</span> <span class='kw'>&lt;-</span> <span class='fl'>100</span>\n<span class='no'>x</span>"
```

<sup>Created on 2020-04-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
I'll work on a fix, and then plan for a patch release late next week.
