### ISSUE TITLE
Issues in deploying website (possibly related to Travis-CI dpl v2)

### ISSUE THREAD

**Issue by GegznaV** [r-lib/pkgdown#1289]
Lately, Travis-CI started to fails deploying **pkgdown** website of my packages. I did not change any Travis-CI configuration until that. But I noticed, that current configuration (that worked until recently) created with `usethis::use_pkgdown_travis()` (https://github.com/r-lib/usethis/issues/1092) issues warnings:

![image](https://user-images.githubusercontent.com/12725868/78535907-9775e400-77f5-11ea-834e-6023c0d70660.png)

Thus I tried 2 versions of settings: with `skip_cleanup: true` present and with the line deleted from `.travis.yml` file. In both cases I faced failure.

In my opinion, the most appropriate parts of Travis-CI log files in both cases

***

<details>
<summary>Travis-CI log with `skip_cleanup: true` present </summary>
── Deploying to GitHub Pages ────────────────────────
Running git remote -v

origin	https://github.com/mokymai/bio.git (fetch)

origin	https://github.com/mokymai/bio.git (push)

Running git push --force origin 'HEAD:gh-pages'

remote: Invalid username or password.

fatal: Authentication failed for 'https://github.com/mokymai/bio.git/'

Error: System command 'git' failed, exit status: 128, stdout & stderr were printed

 Stack trace:

 1. pkgdown::deploy_site_github()

 2. pkgdown:::deploy_to_branch(pkg, commit_message = commit_message,  ...

 3. pkgdown:::github_push(dest_dir, commit_message, remote, branch)

 4. pkgdown:::with_dir(dir, { ...

 5. base:::force(code)

 6. pkgdown:::git("push", "--force", remote, paste0("HEAD:", branch))

 7. processx::run("git", c(...), echo_cmd = echo_cmd, echo = echo,  ...

 8. throw(new_process_error(res, call = sys.call(), echo = echo,  ...

 x System command 'git' failed, exit status: 128, stdout & stderr were printed 

── Removing worktree ───────────────

Running git worktree remove /tmp/RtmpdTaTn8/file3946f591dad

Execution halted

Script failed with status 1

failed to deploy
</details>

I think the issue is here: **`fatal: Authentication failed`**

***

<details>
<summary>Travis-CI log with `skip_cleanup: true` removed </summary>

Installing deploy dependencies

Successfully installed dpl-script-1.10.15

1 gem installed

dpl.2

Preparing deploy

Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.

Saved working directory and index state WIP on (no branch): 474e81a Update .travis.yml

dpl.3

Deploying application

Already up to date!

HEAD detached at 474e81a

Untracked files:

  (use "git add <file>..." to include in what will be committed)

	bio.Rcheck/

	bio_0.0.4.1.tar.gz

nothing added to commit but untracked files present (use "git add" to track)

Dropped refs/stash@{0} (d5eb3c28d88ff4acdc761882dba7c36aab3eab3e)

Script failed with status 1

failed to deploy

</details>

In this case, I found no meaningful message:
```
Script failed with status 1
failed to deploy
```

***

How can automatic deployment of **pkgdown** website be fixed?

**Comment by jayhesselberth** [comment]
A similar travis deploy issue was fixed in #1276.

Until the next release is out, please update your travis config to use `remotes::install_github("r-lib/pkddown")`.
