### ISSUE TITLE
Can’t bind data because some arguments have the same name

### ISSUE THREAD

**Issue by jeroen** [r-lib/pkgdown#1290]
Some packages are giving this error since pkgdown 1.5 for example the [textreuse](https://github.com/ropensci/textreuse) pkg: ([log file](https://dev.ropensci.org/job/textreuse/70/console))

```
Can’t bind data because some arguments have the same name
```

The problem appears during the evaluation of `match_env(topics)` here:

https://github.com/r-lib/pkgdown/blob/0bac47a98bc35718079c04bfe299c54d6c6b3605/R/topics.R#L8

The problematic topics is in row 17:

```r
> match_env(topics[17,])
Error during wrapup: Can't bind data because some arguments have the same name
```

This is what it looks like:

```r
> as.list(topics[17,])

$name
reexports.Rd
 "reexports"

$file_in
[1] "reexports.Rd"

$file_out
[1] "reexports.html"

$alias
$alias$reexports.Rd
[1] "reexports" "meta"      "reexports" "meta<-"    "reexports" "content"
[7] "reexports" "content<-"
```

I think the problem is that `alias` above contains duplicates?

**Comment by hadley** [comment]
Yeah, that's probably it. If you need a fix in the interim, I'm pretty sure the duplicated aliases are a bug in old roxygen2.

**Comment by jeroen** [comment]
OK thanks, I'll tell the affected packages to roxygenise.

**Comment by hadley** [comment]
Minimal reprex:

``` r
topic <- list(
  name = c(reexports.Rd = "reexports"),
  file_in = "reexports.Rd",
  file_out = "reexports.html",
  alias = list(
    reexports.Rd = c("reexports", "meta", "reexports", "meta<-")
  )
) 
pkgdown:::match_env(topic)
#> Error: Can't bind data because some arguments have the same name
```

<sup>Created on 2020-04-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jeroen** [comment]
Thanks.
