### ISSUE TITLE
v1.5.0: Breaking changes in sidebar

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/pkgdown#1293]
Hi, I'm having some trouble updating my `extra.css` file to reflect breaking changes introduced in the latest pkgdown v1.5.0 update.

For reference, here's my custom pkgdown CSS file shared across my packages:
https://github.com/steinbaugh/steinbaugh.github.io/blob/master/css/pkgdown.css

Note that `div#sidebar` has changed to `div#pkgdown-sidebar` in v1.5.0.

In the previous version, the sidebar HTML was rendered as such:

```html
  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
    <h2>Contents</h2>
    <ul class="nav nav-pills nav-stacked">
      <li><a href="#arguments">Arguments</a></li>
      <li><a href="#value">Value</a></li>
      <li><a href="#details">Details</a></li>
      <li><a href="#note">Note</a></li>
      <li><a href="#examples">Examples</a></li>
    </ul>
  </div>
```

source: https://github.com/acidgenomics/syntactic/blob/v0.3.8/docs/reference/camelCase.html

In the latest update, the structure of the sidebar has changed:

```html
  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">
    <nav id="toc" data-toggle="toc" class="sticky-top">
      <h2 data-toc-skip>Contents</h2>
    </nav>
  </div>
```

source: https://github.com/acidgenomics/syntactic/blob/v0.3.9/docs/reference/camelCase.html

I'm assuming the sidebar table of contents (TOC) list is now handled by some type of JavaScript code. What is the CSS class I should use to target the navigation elements? Previously we could use `ul.nav-pills` or `ul.nav-stacked`. The current output is a bit of a regression in my opinion, as the source code doesn't contain the navigation elements in the HTML anymore.

**Comment by mjsteinbaugh** [comment]
Potentially related issues:
- #1254

**Comment by jayhesselberth** [comment]
Yes the sidebar TOC is now handled by [bootstrap-toc](https://afeld.github.io/bootstrap-toc/). 

The stock CSS is here: https://github.com/r-lib/pkgdown/blob/master/inst/assets/bootstrap-toc.css

And pkgdown-specific tweaks are here:

https://github.com/r-lib/pkgdown/blob/cb9866146685f6924b67c2b95a97a9637e934714/inst/assets/pkgdown.css#L179-L230

**Comment by mjsteinbaugh** [comment]
Awesome thanks @jayhesselberth !
