### ISSUE TITLE
Clean the site deployed to the branch

### ISSUE THREAD

**Issue by hbaniecki** [r-lib/pkgdown#1297]
Hi,
I am using `gh-actions` with `deploy_to_branch()`. Is there any way to automatically clean the branch (e.g. after changing vignette file names)? `clean_site()` does that locally, so it would be neat to have a `clean_branch_site()` function.

**Comment by jayhesselberth** [comment]
I've seen this happen and it would be nice to deploy a completely new site.

We could add a `clean` argument to the `deploy_` functions, and if `clean = TRUE` then remove (`git rm`) all tracked files before building the new site.
