### ISSUE TITLE
Idea: `browse_package()`

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#1303]
**EDIT: This was aimed to be an issue in usethis, not pkgdown. Can someone please transfer it? Thanks and sorry.** 😆 

I often find myself in the situation wanting to browse the pkgdown site of a package rather than its GitHub or CRAN site.

I am currently using `browseURL(desc::desc_get_urls()[1])` for this which opens the pkgdown site if it exists in the URL field and comes first. If missing, the GitHub page is opened. If no URL field exists, it errors obviously.

Some pkgs do not have a URL field at all and while `usethis::browse_github()` already falls back to `usethis::browse_cran()`, I have the feeling that a wrapper function like `browse_package()` could be helpful.

Essentially it would try to look for a pkgdown page first, fall back to the GitHub page and last to the CRAN page.

**Comment by jayhesselberth** [comment]
Closed by https://github.com/r-lib/usethis/issues/1102

**Comment by pat-s** [comment]
> Closed by r-lib/usethis#1102

This is a different FR. I'll open this one again in {usethis} then.
