### ISSUE TITLE
Preformatted sections don't render the `%>%` and `<- `correctly

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#1311]
In the `@details` section of my documentation I'm using roxygen2's new inline markdown feature to render this block:

```
#' ```{r}
#' on_5th_of_the_month <- monthly() %>%
#'   recur_on_mday(5)
#'
#' on_tuesday <- weekly() %>%
#'   recur_on_wday("Tuesday")
#'
#' rbundle() %>%
#'   add_rschedule(on_5th_of_the_month) %>%
#'   add_rschedule(on_tuesday)
#' ```
```

It looks fine in R's help file:

![Screen Shot 2020-04-24 at 11 13 30 AM](https://user-images.githubusercontent.com/19150088/80228204-bdd0b780-861c-11ea-9c07-073ddfacf682.png)

But pkgdown seems to be double escaping something to cause the `<-` and `%>%` to be recognized as greater than and less than signs.

<img width="592" alt="Screen Shot 2020-04-24 at 11 16 07 AM" src="https://user-images.githubusercontent.com/19150088/80228405-02f4e980-861d-11ea-8333-dda4631d22fd.png">

Note that the examples section below seems to be rendering everything correctly.

I also don't think this is specific to the inline markdown feature. Just using a preformatted block by removing the `{r}` part also causes this problem.

Here is a link to the rendered page
https://davisvaughan.github.io/almanac/reference/rbundle-add.html

**Comment by jayhesselberth** [comment]
What happens if you manually remove the escaping in the Rd file? (change `\%>\%` to `%>%`)

https://github.com/DavisVaughan/almanac/blob/04bfd997ade484ffddc6ec43accdc9d7e77fe337/man/rbundle-add.Rd#L60-L61

**Comment by DavisVaughan** [comment]
That gives:

```
on_5th_of_the_month &lt;- monthly() <!-- %&gt;% -->
  recur_on_mday(5)
```

**Comment by jayhesselberth** [comment]
Minimal reprex:

``` r
library(pkgdown)
rd2html("\\preformatted{\\%>\\%}")
#> [1] "<pre>%&amp;gt;%</pre>"
```

<sup>Created on 2020-04-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
