### ISSUE TITLE
build_site does not seem to build reference docs well that have unicode in them

### ISSUE THREAD

**Issue by davidhodge931** [r-lib/pkgdown#1315]
There is unicode in my reference documenntation of my package, specifically n-dashes. 

When I use `build_site()`, it renders the reference material with a series of warnings related to this.
#> Warning: conversion failure on '10–50' in 'mbcsToSbcs': dot substituted for <e2>

When I then rebuild the reference material with `build_reference(lazy = FALSE)`, they go away.

I am not sure why this is, and whether it is a bug associated with `build_site` or not

**Comment by jayhesselberth** [comment]
Can you please provide a small reprex illustrating the problem?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
