### ISSUE TITLE
CSS is different in Rstudio vs outputted .html files

### ISSUE THREAD

**Issue by jeffwong-nflx** [r-lib/pkgdown#1316]
When I run `pkgdown::build_site` in Rstudio I see code that is formatted with single backticks (`) shows up with a red font. This is great. But when I look at the outputted html file that I would upload, I see the CSS for "\<code\>" is 

```
pre, code {
  background-color: #f8f8f8;
  color: #333;
}
```

which is actually black on top of grey (not a good color combination). Using pkdown 1.5.1, R 3.6.3, Ubuntu 18.04

**Comment by jayhesselberth** [comment]
You can override default appearances by adding CSS to `pkgdown/extra.css`.

**Comment by jeffwong-nflx** [comment]
Shouldn't the view in RStudio be the same as the outputted files?
