### ISSUE TITLE
HTML not stripped from page title

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#1318]
Beginning of roxygen2 comment block:

```
#' \R's fundamental data type at C level
#'
#' @description
#' (...)
```

leads to this html page (please notice the html code surfacing in the html rendered output):

![snap](https://user-images.githubusercontent.com/19862384/80705383-3c769a80-8ade-11ea-867f-453890857f82.png)

It works fine though in RStudio's help page:

![snap](https://user-images.githubusercontent.com/19862384/80705477-6af47580-8ade-11ea-98f1-ed65cf145238.png)

So it seems that backslash in `\R` is messing up the parser.

**Comment by hadley** [comment]
The problem is that the page `<title>` includes `<span class="R">R</span>` which is not valid HTML.
