### ISSUE TITLE
separator included before first entry in Articles navbar dropdown

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pkgdown#1319]
Let me know if a reprex would be useful. As an example:

https://github.com/rstudio/renv/blob/da66b72a77a1708053f5cc659db6b0396ac99e0c/_pkgdown.yml#L66-L86

This generates the navbar:

<img width="305" alt="Screen Shot 2020-05-04 at 3 22 44 PM" src="https://user-images.githubusercontent.com/1976582/81019489-9c8d7980-8e1b-11ea-8d02-56ff3fcd0619.png">

IMHO the first separator (displayed before `Introduction`) should be removed.

**Comment by kevinushey** [comment]
Thanks @maelle!

**Comment by maelle** [comment]
@kevinushey note that this will only be fixed for Bootstrap 4 so you'll need to switch. https://pkgdown.r-lib.org/dev/articles/customization.html#getting-started-1

**Comment by maelle** [comment]
(and thank you for the bug report!)
