### ISSUE TITLE
github action for pkgdown fails on dashboardthemes dependency

### ISSUE THREAD

**Issue by OceaneCsn** [r-lib/pkgdown#1324]
Hello, 
I have set up a github workflow for pkgdown with `usethis::use_github_action("pkgdown")`.
Unfortunately the job fails with the following error :

> github-actions / pkgdown
.github#L1
(converted from warning) package ‘dashboardthemes’ is not available (for R version 4.0.0)

The logs and workflow file can be found here : [https://github.com/OceaneCsn/DIANE/runs/681419120?check_suite_focus=true](https://github.com/OceaneCsn/DIANE/runs/681419120?check_suite_focus=true)

There is no error when I run `pkgdown::build_site()` locally (on Windows 10).

Any idea if there is something I can do to make the github action work?

**Comment by cderv** [comment]
I don’t think dashboardthemes is on cran. Just on GitHub here
https://github.com/nik01010/dashboardthemes

It means your package has a non CRAN dependency. In your DESCRIPTION you need to use the Remote field to make sure that the dependency is found by remotes for installation.
See  https://remotes.r-lib.org/articles/dependencies.html

The step installing dependency will then know how to find this one. 

Hope it helps.

**Comment by OceaneCsn** [comment]
You're right. 
Thank you for helping with this issue, that was not caused by pkgdown at all.
