### ISSUE TITLE
How can I setup without the use of usethis?

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/pkgdown#1330]
If I want to use pkgdown, I should not need an additional package to set it up. There should be a self contained setup function within pkgdown to get things started.

**Comment by jayhesselberth** [comment]
You can just run `pkgdown::build_site()` too, but you'll have to manually gitignore/Rbuildignore some files.

@hadley perhaps the README should be rearranged to emphasize that usethis serves a utility purpose.
