### ISSUE TITLE
`{pkgdown}` does not work with `{showtext}`

### ISSUE THREAD

**Issue by thomas-neitmann** [r-lib/pkgdown#1331]
Please see my issue open in the `{showtext}` repo: yixuan/showtext#36. I am not sure whose "responsibility" this is.

**Comment by thomas-neitmann** [comment]
I found out that to make `{showtext}` work with Rmarkdown you have to set the `fig.showtext` chunk option, i.e.
```r
kntir::opts_chunk$set(fig.showtext = TRUE)
```
This can easily de done for the README and vignettes but where would you specify this for the examples?

**Comment by jayhesselberth** [comment]
It's not currently possible to set chunk options in specific examples. This might be fixed by #1256.

**Comment by thomas-neitmann** [comment]
I found a workaround to make `{showtext}` work with `{pkgdown}` which I described [here](https://github.com/yixuan/showtext/issues/36#issuecomment-634863727).

**Comment by hadley** [comment]
I think #1320 should also resolve this (albeit through a slightly different mechanism).
