### ISSUE TITLE
Other ways to exclude Rmd files while building articles

### ISSUE THREAD

**Issue by rickhelmus** [r-lib/pkgdown#1336]
Hello,

I am using both `pkgdown` and `bookdown` for my R package. For this I need to exclude a set of `Rmd` files in order to build the website that are only used by `bookdown`. The way to go was by prefixing these files with an underscore, however, ironically enough `bookdown` recently also started to ignore files prefixed with an underscore. Is there way around it? Currently I am temporarily re-naming files, but this is obviously quite messy :-(

Thanks,
Rick

**Comment by jayhesselberth** [comment]
We should probably provide a way to specify excluded files in the pkgdown config file that is independent of a file prefix.

**Comment by hadley** [comment]
You can also exclude vignettes from becoming articles by adding to `.Rbuildignore`. It's not clear to me that we need a third mechanism. I'd want to know more about how exactly you are attempting to use bookdown and pkgdown together before we consider adding any new code.

**Comment by salim-b** [comment]
@hadley I have a `TODO.md` in the package's root dir which I've added to `.Rbuildignore`. pkgdown always builds this to `TODO.html`. How would I tell pkgdown to ignore it instead?
