### ISSUE TITLE
Document "get started" vignette better

### ISSUE THREAD

**Issue by bblodfon** [r-lib/pkgdown#1339]
Hi!

While looking at the pkgdown site, I was trying to understand how to create the [Get started](https://pkgdown.r-lib.org/articles/pkgdown.html) page. Note that I haven't yet create a vignette though a have authored a couple of R packages and I was going a little "quick" about it :) It took me some time, but If I now understand correctly, creating a vignette with the same name as the package will result in the "Get started" tab by default, right? 

I think it would be nice to mention this in the [doc, articles section](https://pkgdown.r-lib.org/articles/pkgdown.html#articles-1) and save some time for the next person who tries this!

BR, John.

**Comment by hadley** [comment]
Made this more prominent in the `build_articles()` docs 😄
