### ISSUE TITLE
Docsearch can not search for function names

### ISSUE THREAD

**Issue by gustavdelius** [r-lib/pkgdown#1341]
Currently the documentation search with algolia's docsearch appears not to index the "Usage" field of a manual page. This is a problem because this is usually the only place where the name of the function is mentioned on the man page. So for example it is not possible to search on the pkgdown site for the `template_articles()` function:
![screenshot_4](https://user-images.githubusercontent.com/1340713/83789463-ab6f8200-a68e-11ea-960e-d4c5653061da.png)

The problem may be that the usage field is inside a `<pre>` tag. Is there some way to tell algolia to index it nevertheless?

**Comment by jayhesselberth** [comment]
We'd need to update the docsearch json here:

https://github.com/r-lib/pkgdown/blob/aeb1cfb080f566b32da6613b6e12c13eb743daff/inst/templates/config-docsearch.json#L56

Changing the value to `".contents .usage .fu"` might be a better choice as it would grab the function name from the usage statemtn.

**Comment by gustavdelius** [comment]
@jayhesselberth , thanks for thinking about this so quickly. But wouldn't the change to the selector simply change what is displayed in the search result, rather than changing what part of the page is indexed?
I would have changed
https://github.com/r-lib/pkgdown/blob/aeb1cfb080f566b32da6613b6e12c13eb743daff/inst/templates/config-docsearch.json#L64
to
`      "text": ".contents p, .contents li, .contents .usage .fu"`
But I am probably misunderstanding how docsearch works.

**Comment by jayhesselberth** [comment]
You might be right, will need to test it out.

**Comment by gustavdelius** [comment]
I am probably wrong. I can't tell from the docsearch documentation at https://docsearch.algolia.com/docs/config-file. But is the only way to test it out to make a pull request to algolia, then see what effect it had, then make another pull request, and so on? Or do you have a better way to test it out?

**Comment by jayhesselberth** [comment]
There's a command line tool to test it locally. I'll get to it soon, for now please don't submit a PR to the pkgdown algolia config.

**Comment by gustavdelius** [comment]
Thanks. One thing to keep in mind is that some pages contain several .usage .fu elements because they document several functions.

**Comment by gustavdelius** [comment]
@jayhesselberth, are you still planning to test this?

**Comment by jayhesselberth** [comment]
Don't have time these days. This may be superseded by #1407 anyway.
