### ISSUE TITLE
Intra-package functions are being linked to rdrr.io

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#1353]
This uses dev pkgdown through a github actions workflow.

The `workflows::add_formula()` function is specific to workflows, but on the workflows dev site it is being linked out to rdrr.io.
https://workflows.tidymodels.org/dev/reference/add_formula.html

@hadley mentioned this might have something to do with the switch to downlit

**Comment by hadley** [comment]
I think the root cause is that the option that tells downlit not to link to the "current" page isn't being set correctly.

**Comment by hadley** [comment]
Can also see on pkgdown itself: https://pkgdown.r-lib.org/dev/reference/build_reference.html#topic-matching. But I don't see when I render locally 🤔

**Comment by hadley** [comment]
I'm pretty sure I found the root cause, but since I can't reproduce locally I'll have to wait until the dev site re-builds to be sure.

**Comment by hadley** [comment]
Yup, fixed 😄
