### ISSUE TITLE
documentation on toc depth

### ISSUE THREAD

**Issue by statnmap** [r-lib/pkgdown#1357]
I see in the documentation that we can define the toc depth in articles: https://pkgdown.r-lib.org/reference/build_articles.html  
I tried to add this option directly in my _pkgdown.yml, also in the yaml header of my vignette, but it seems there is no effect.  
Could you add a little more information in the documentation of this "build_articles()" function to know exactly where to add this option ?

**Comment by statnmap** [comment]
If I explore the code of function, the only place I can see the source of `toc_depth` is through `pkg$meta$toc$depth`:
https://github.com/r-lib/pkgdown/blob/42dbedc387fd0e7b88409cbd38486c1efa7820b3/R/build-articles.R#L304

which means that the information should be added in `_pkgdown.yml` as follows:
```yaml
toc:
  depth: 3
```

This is what I did, but there is no effect on the TOC in pkgdown.  
You can try the following reprex:

```r
# Create fake package
temp_dir <- tempdir()
pkg_path <- file.path(temp_dir, "fake.pkg")
dir.create(pkg_path)
usethis::create_package(path = pkg_path, open = FALSE)

# Create meta yaml
yaml_file <- file.path(pkg_path, ".pkgdown.yml")
cat("toc:
  depth: 4", file = yaml_file)

# Create vignette with multiple titles
dir.create(file.path(pkg_path, "vignettes"))
cat('---
title: "Title"
author: "Sébastien Rochette"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\\VignetteIndexEntry{Title}
  %\\VignetteEngine{knitr::rmarkdown}
  %\\VignetteEncoding{UTF-8}
---
    
# Title 1a  

## Title 2a  

### Title 3a  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

### Title 3b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

## Title 2b
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

# Title 1b  

## Title 2a  

### Title 3a  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

### Title 3b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

## Title 2b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

# Title 1c  

## Title 2a  

### Title 3a
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

#### Title 4a
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

#### Title 4b
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

#### Title 4a
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

### Title 3b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

## Title 2b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

', file = file.path(pkg_path, "vignettes", "my_vignette.Rmd"))


# Build pkgdown
pkgdown::build_site(pkg = pkg_path)
```
This always conduct to a TOC of depth 2
![image](https://user-images.githubusercontent.com/21193866/86796310-bee78180-c06e-11ea-96b1-1ab5f0480d36.png)

**Comment by jayhesselberth** [comment]
This option has no effect because bootstrap-toc now generates the TOC. We should remove the option.

You might be able to achieve the behavior by modifying the [TOC scope](https://afeld.github.io/bootstrap-toc/#options); you would place relevant code in `pkgdown/extra.js`.

**Comment by statnmap** [comment]
Thank you for the answer. I am not enough comfortable with Javascript.  
I write my modified reprex here, and we'll see later if I find a solution.  

```r
# Create fake package
temp_dir <- tempdir()
pkg_path <- file.path(temp_dir, "fake.pkg")
dir.create(pkg_path)
usethis::create_package(path = pkg_path, open = TRUE)

# Create meta yaml
yaml_file <- file.path(pkg_path, ".pkgdown.yml")
cat("toc:
  depth: 4", file = yaml_file)

# Create vignette with multiple titles
dir.create(file.path(pkg_path, "vignettes"))
cat('---
title: "Title"
author: "Sébastien Rochette"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\\VignetteIndexEntry{Title}
  %\\VignetteEngine{knitr::rmarkdown}
  %\\VignetteEncoding{UTF-8}
---
    
# Title 1a  

## Title 2a  

### Title 3a  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

### Title 3b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

## Title 2b
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

# Title 1b  

## Title 2a  

### Title 3a  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

### Title 3b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

## Title 2b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

# Title 1c  

## Title 2a  

### Title 3a
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

#### Title 4a
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

#### Title 4b
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

#### Title 4a
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

### Title 3b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

## Title 2b  
', paste(sample(c(" ", letters), 300, replace = TRUE), collapse = "") , '

', file = file.path(pkg_path, "vignettes", "my_vignette.Rmd"))

# Change TOC
dir.create(file.path(pkg_path, "pkgdown"))
cat('(function($) {
$(function() {
  var navSelector = "#toc";
  var $myNav = $(navSelector);
  Toc.init({$scope: $("h3")});
  $("body").scrollspy({
    target: navSelector
  });
});
})(window.jQuery || window.$);
', file = file.path(pkg_path, "pkgdown", "extra.js"))



# Build pkgdown
pkgdown::build_site(pkg = pkg_path)
```

**Comment by maelle** [comment]
@statnmap bootstrap-toc doesn't support more than two levels in the TOC https://github.com/afeld/bootstrap-toc/issues/27 so unless pkgdown no longer uses bootstrap-toc one day, it is not possible to change the TOC depth.

**Comment by moodymudskipper** [comment]
FYI @maelle the vignette still says it's possible : https://pkgdown.r-lib.org/reference/build_articles.html

![image](https://user-images.githubusercontent.com/18351714/115230493-ba2f1e00-a114-11eb-9627-237d644d681d.png)

**Comment by jayhesselberth** [comment]
@moodymudskipper those changes will only appear in the dev docs for now: https://pkgdown.r-lib.org/dev/reference/build_articles.html

**Comment by salim-b** [comment]
> bootstrap-toc doesn't support more than two levels in the TOC [afeld/bootstrap-toc#27](https://github.com/afeld/bootstrap-toc/issues/27) so unless pkgdown no longer uses bootstrap-toc one day, it is not possible to change the TOC depth.

There are several PRs that attempt to implement a depth > 2 in bootstrap-toc:

- https://github.com/afeld/bootstrap-toc/pull/36
- https://github.com/afeld/bootstrap-toc/pull/37
- https://github.com/afeld/bootstrap-toc/pull/52

But no reaction on those from the author. The project [appears to basically be deprecated/unmaintained](https://github.com/afeld/bootstrap-toc/pull/74) for several years now.

So the best way forward would probably be to

1. let the ToC markup be generated by pkgdown (with the additional upside of making it appear for site visitors with JS disabled)
2. use Bootrap's native [scrollspy](https://getbootstrap.com/docs/5.3/components/scrollspy/) functionality.
