### ISSUE TITLE
`build_site()` fails when a Sexpr is in the Title

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#1359]
This only happens in the development version of pkgdown, it works with the CRAN version.

I have used a `\Sexpr` line in the Title, like this:

```r
#' \Sexpr[stage=render,results=rd]{"hi"} Test
#'
#' @description
#' Hi there
#'
#' @export
test_fn <- function() {
  1
}
```

`build_site()` fails with:

```r
> pkgdown::build_site()
Error: Context `src_path` has not been initialised
```

A backtrace:

```r
> rlang::last_error()
<error/rlang_error>
Context `src_path` has not been initialised
Backtrace:
  1. pkgdown::build_site()
  2. pkgdown::as_pkgdown(pkg, override = override)
  4. pkgdown:::package_topics(pkg, package)
  5. purrr::map_chr(rd, extract_title)
  6. pkgdown:::.f(.x[[i]], ...)
  6. purrr::detect(., inherits, "tag_title")
 13. pkgdown:::flatten_text(., auto_link = FALSE)
 15. purrr::map_chr(x, as_html, ...)
 17. pkgdown:::as_html.tag_if(.x[[i]], ...)
 19. pkgdown:::as_html.tag(x[[2]])
 20. pkgdown:::flatten_text(x, ...)
 21. purrr::map_chr(x, as_html, ...)
 23. pkgdown:::as_html.tag_Sexpr(.x[[i]], ...)
 25. pkgdown:::context_get("src_path")
```

A reproducible test package where this occurs is here:
https://github.com/DavisVaughan/testpkgdowntitle/blob/master/R/test.R

It seems like this happens because `as_pkgdown()` calls `package_topics()` to build the topics. `package_topics()` tries to extract all the titles with `extract_title()`, which tries to convert each title to HTML with `as_html()`. When it hits this title, `as_html.tag_Sexpr()` is run, but the context variable `src_path` hasn't been initialized yet.

**Comment by DavisVaughan** [comment]
I imagine the removal of this chunk caused the issue!
https://github.com/r-lib/pkgdown/commit/4ff2db58f991412835b474e0b130709ff57ee670#diff-6601b3777eda1f614d07d4a5f606d4c1L108-L111

**Comment by jayhesselberth** [comment]
#1318 and #1344 are also related
