### ISSUE TITLE
`vignette("my-vignette")` doesn't autolink in function docs

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#1360]
With dev pkgdown, `vignette()` doesn't autolink when in function docs like:

```r
#' Test
#'
#' @description
#' Hey go look at my `vignette("test1")`.
#'
#' @export
```

I assume this is a downlit bug.

Here is a test package that you can check this on
https://github.com/DavisVaughan/testpkgdownvignette

With CRAN pkgdown, this does autolink, however I had to actually install the package and then run `build_site()` to get it to autolink, which smells like another bug in the CRAN version.

Installing the package and then running `build_site()` with dev pkgdown does not fix this issue.

**Comment by hadley** [comment]
Pretty sure this is the same problem as #1353
