### ISSUE TITLE
FR: Development mode "preview"

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#1361]
as an extension of "auto".

- x.y.z version: to `docs/` 
- x.y.z.9000 version, main branch: to `docs/dev`
- x.y.z.9000 version, other branch: to `docs/preview/<branch-name>`

Similar to Netlify preview, without having to host at Netlify. Useful gimmicks:

- clean stale previews
- if branch has an associated pull request, post a comment with link to preview

Related: #1057.

**Comment by hadley** [comment]
It's an interesting idea, but it's hard to see what would clean up the branches when they're done, and I think #1373 is going to be higher priority in the short- to medium-term.
