### ISSUE TITLE
Issues with NEWS

### ISSUE THREAD

**Issue by royfrancis** [r-lib/pkgdown#1363]
If I have NEWS like this:

```
# mypackage 1.1.1

* bla bla

# mypackage 1.1.0

* more bla bla

# mypackage 1.0.0

* even more bla bla
```

The page works and the TOC is organised like

```
1.1.1
1.1.0
1.0.0
```

The problem with this is that the TOC is non-nested and gets too long. What I would like is a nested TOC like this:

```
1.
 1.1
  1.1.1
 1.0
   1.0.0
```

So, I tried to change my headers to 

```
# 1.x
## 1.1.x
### 1.1.1

* bla bla

### 1.1.0

* more bla bla

## 1.0.x
### 1.0.0

* even more bla bla
```

but nothing works, the page nor the TOC.

Next question is if I need to keep maintaining two identical files NEWS and NEWS.md in my R package?

**Comment by jayhesselberth** [comment]
pkgdown implements the structure of NEWS prescribed by the [tidyverse style guide](https://style.tidyverse.org/news.html#organisation-3).

You only need to maintain NEWS.md.
