### ISSUE TITLE
Can't autolink to private packages

### ISSUE THREAD

**Issue by mstr3336** [r-lib/pkgdown#1366]
Hi there.

My organization hosts an instance of GH enterprise. 

## The Process

The current trajectory for autolinking is as follows (correct me if I'm wrong) 

Read URL from package DESCRIPTION, for example:
```r
URL: https://pages.github.sydney.edu.au/speed-extract/mandrake/
```

Resolve `{url}`/pkgdown.yml , use the links given here to help configure autolinking.

For example, `DESCRIPTION$URL` gives: 

https://pages.github.sydney.edu.au/speed-extract/mandrake/pkgdown.yml

```yaml
pandoc: '2.10'
pkgdown: 1.5.1.9000
pkgdown_sha: ~
articles: []
last_built: 2020-07-22T05:05Z
urls:
  reference: https://pages.github.sydney.edu.au/speed-extract/mandrake//reference
  article: https://pages.github.sydney.edu.au/speed-extract/mandrake//articles
```

* `urls$reference` gives https://pages.github.sydney.edu.au/speed-extract/mandrake//reference
* `urls$article` gives https://pages.github.sydney.edu.au/speed-extract/mandrake//articles

pkgdown figures out the rest. 

## The problem with this process and enterprise hosted repos

This would be great, however, you will find that if you click on https://pages.github.sydney.edu.au/speed-extract/mandrake/pkgdown.yml

you will be given a challenge-response asking you to sign in.

curl says:

```
curl -I "https://pages.github.sydney.edu.au/speed-extract/mandrake/pkgdown.yml"
```

```
HTTP/1.1 302 Moved Temporarily
Server: GitHub.com
Date: Wed, 22 Jul 2020 06:27:49 GMT
Content-Type: text/html
Content-Length: 138
Location: https://github.sydney.edu.au/sessions/_auth_request_bounce?return_to=https%3A%2F%2Fpages.github.sydney.edu.au%2Fspeed-extract%2Fmandrake%2Fpkgdown.ym
```

So, `pkgdown` is never going to resolve those links. 

## Potential Fixes / Accomodations

I wonder, then, whether there are other ways pkgdown could accomodate linking enterprise hosted packages. 
A few jump out:

* __1__ Allowing `pkgdown.yml` (The one deployed wherever our pkgdown site is deployed, eg  https://pages.github.sydney.edu.au/speed-extract/mandrake/pkgdown.yml ) to be built into the package (Removing it from `.Rbuildignore` ) s.t if it is found, its url links are resolved automatically.
* __2__ If `pkgdown` attempts to resolve `DESCRIPTION$URL`/pkgdown.yml , and fails, pkgdown can make its best-effort based off of `DESCRIPTION$URL` to set up some "standard" links, such as:
  ```
  # base_url <- DESCRIPTION$URL
  urls$reference <- file.path(base_url, "reference")
  urls$article <- file.path(base_url, "articles")
  ```

These fall-backs might allow a best-effort linking for package's whose `description$url` field cannot be resolved publicly. I personally don't see too much harm in building a `pkgdown.yml` into installed R packages, so I think this could accomodate those of us who can't host all of our work publically. 

Cheers!

**Comment by mstr3336** [comment]
I think I'd better migrate this to https://github.com/r-lib/downlit

**Comment by mstr3336** [comment]
@hadley , i see you've triaged this / marked this as a valid feature request 

PR #1367 , in conjunction with downlit#29 (or downlit#30 , will check when not on phone) aim to address this, by simply allowing a setting for to `pkgdown.yml` metadata to `inst`

The corresponding behavior in downlit checks for installed metadata on failed dial-out to the linked websites.

**Comment by hadley** [comment]
I've just quickly triaged the issue and I haven't thought deeply about it, but the basic approach seems reasonable.
