### ISSUE TITLE
R source links don't work with GitLab subgroups

### ISSUE THREAD

**Issue by dfsnow** [r-lib/pkgdown#1368]
Links to R source files are incorrect when a site is built using a GitLab URL that has a subgroup. 

Using `_pkgdown.yml` settings:

```
destination: public
url: https://ccao-data-science---modeling.gitlab.io/packages/assessr/
```

See example page [here](https://ccao-data-science---modeling.gitlab.io/packages/assessr/reference/cod.html).  Check the source link to `R/formulas.R` .

The actual link goes to `https://gitlab.com/ccao-data-science---modeling/packages/blob/master/R/formulas.R`

The correct link is `https://gitlab.com/ccao-data-science---modeling/packages/assessr/blob/master/R/formulas.R`

**Comment by hadley** [comment]
We don't use GitLab ourselves, so have limited ability to support it. We'd be happy to review a PR though!
