### ISSUE TITLE
Is it possible to disable execution of both vignettes and examples?

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/pkgdown#1374]
I tried to disable execution of both vignettes and examples by running with examples=FALSE and by redefining the navbar in the yaml file not to contain vignettes, like this

navbar:
  structure:
    left:  [home, intro, reference, news]

but it seems that pkgdown is still trying to execute both. Is there a way to prevent those to be executed?

**Comment by hadley** [comment]
If you don't want code in your vignettes to be executed in certain circumstances, I'd recommend doing something like:

```R
if (identical(Sys.getenv("IN_PKGDOWN"), "true"))
  knitr::opts_chunks$set(eval = FALSE)
```
