### ISSUE TITLE
Suggestion: provide an option to turn the warnings of check_missing_topics() into errors.

### ISSUE THREAD

**Issue by ThierryO** [r-lib/pkgdown#1378]
I would find this useful when running in CI to make sure that the pkgdown website covers all helpfiles.

Possible implementations:

- via argument in `_pkgdown.yml`
- via environment variable cfr `NOT_CRAN`.
- via extra argument

I'd suggest three possible states:
- `never` (default, alias: `FALSE`)
- `non-interactive`
- `always` (alias: `TRUE`)

I'm happy to send a PR.

**Comment by hadley** [comment]
Hmmm, maybe it could default to `true` if `CI` is true. Then you wouldn't need a separate env var, just an option. 

A PR would be great 😄

**Comment by ldecicco-USGS** [comment]
FYI, when CI is TRUE is exactly the time I don't want this to error 🙃. I'm trying to make my online documentation (created from a github action) to be as clean and user-friendly as possible. So, purposely leaving off some of the lesser-used functions (but I'd still like to have those help files available to more power-users who are more familiar with native R help files)

So, is there anyway in a within:
```r
pkgdown::deploy_to_branch(new_process = FALSE)
```
to specify ignore the check_missing_topics?

**Comment by hadley** [comment]
@ldecicco-USGS those topics can have `@keywords internal` so they don’t appear in the index.
