### ISSUE TITLE
'Error: Failed to render RMarkdown' in pkgdown GitHub action

### ISSUE THREAD

**Issue by ngreifer** [r-lib/pkgdown#1379]
I'm using `pkgdown` to make a website for my package, `cobalt`. The [website](https://ngreifer.github.io/cobalt/index.html) is up and running, but when I push to GitHub, the `pkgdown` [test](https://github.com/ngreifer/cobalt/runs/995579082) fails with the following error:

```
── Building articles ───────────────────────────────────────────────────────────
Writing 'articles/index.html'
Reading 'vignettes/cobalt_A0_basic_use.Rmd'
Writing 'articles/cobalt_A0_basic_use.html'
Reading 'vignettes/cobalt_A1_other_packages.Rmd'
##[error]Error: Failed to render RMarkdown
```

This looks like it's an issue with my Appendix 1 vignette, but the Rmarkdown seems to render just fine locally (using `knit` in RStudio) and on [the package website](https://ngreifer.github.io/cobalt/articles/cobalt_A1_other_packages.html) itself. There doesn't seem to be anything unusual about the block of code where it appears to error. Thanks for your help.

**Comment by hadley** [comment]
I've made a fix to the development version — it's unlikely to actually resolve the problem, but it at least now prints the complete RMarkdown error instead of just the first 1000 characters. That will hopefully allow you to figure out what's going on.

**Comment by ngreifer** [comment]
Thanks for doing that. I was able to see the full error, and it was this:

```
Loading required package: tcltk
##[error]Error: package or namespace load failed for 'tcltk':
 .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: X11 library is missing: install XQuartz from xquartz.macosforge.org
Quitting from lines 308-315 (cobalt_A1_other_packages.Rmd) 
Error : package 'tcltk' could not be loaded
```

Not sure how this can be resolved within the GitHub Action environment.

**Comment by kpj** [comment]
@ngreifer: https://github.com/r-lib/actions/issues/78#issuecomment-611733294 might be the solution you're looking for.
