### ISSUE TITLE
Check Mark Buttons not rendered correctly

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#1380]
It seems the check mark buttons are not rendered correctly in Chromium or Brave (it works in Firefox though).

As an example take the documentation website of timetk: https://business-science.github.io/timetk/index.html.

### In Brave or Chromium I see it like this:

![chromium_brave](https://user-images.githubusercontent.com/19862384/90469152-f63a5b00-e10f-11ea-85a8-e71263ca8060.png)

### In Firefox it works though:

![firefox](https://user-images.githubusercontent.com/19862384/90469207-19fda100-e110-11ea-9f65-db5296ddb741.png)

### Rendered GitHub Markdown works in any browser

https://github.com/business-science/timetk/

![md_gh](https://user-images.githubusercontent.com/19862384/90469300-5b8e4c00-e110-11ea-9f29-5e1781da75a6.png)

### Browser versions

Chromium: Version 84.0.4147.125
Brave: Version 1.12.64 Chromium: 83.0.4103.116
Firefox: Version 79.0

**Comment by hadley** [comment]
It looks fine for me in safari and chrome, and the page just has literal embedded emoji, so I don't see how pkgdown could be involved here.
