### ISSUE TITLE
deploy_to_branch overwrites the current list of branches tracked

### ISSUE THREAD

**Issue by tanho63** [r-lib/pkgdown#1382]
Hi! I was trying to track down an issue with my `git fetch -a` command and I think it's due to the behaviour of this particular line in the deploy_to_branch function.

https://github.com/r-lib/pkgdown/blob/eae56f08694abebf93cdfc0dd8e9ede06d8c815f/R/deploy-site.R#L158

This has the effect of replacing the default "fetch" line in the git config from `fetch = +refs/heads/*:refs/remotes/origin/*` to `fetch = +refs/heads/gh-pages:refs/remotes/origin/gh-pages`, as in this screenshot:

![image](https://user-images.githubusercontent.com/38083823/90561426-b22a7300-e16e-11ea-9f37-2b5253a953b5.png)

This creates some issues in terms of fetching other remote branches that aren't yet on the local machine - namely, I have to manually reset this line back to the original wildcard format.

Is it possible that the "--add" flag described here https://git-scm.com/docs/git-remote#Documentation/git-remote.txt-emset-branchesem would resolve this issue?

**Comment by hadley** [comment]
@jimhester does adding `--add` seem harmless to you? Context is https://github.com/r-lib/pkgdown/blob/eae56f08694abebf93cdfc0dd8e9ede06d8c815f/R/deploy-site.R#L133-L180.

**Comment by jimhester** [comment]
I don't know, I am not sure that using `--add` would fix the issue with shallow clones on travis, which is why this was added.

**Comment by tanho63** [comment]
Hi @jimhester, my understanding of the reference page was that deploy_to_branch was for local use to push to git (see https://pkgdown.r-lib.org/reference/deploy_site_github.html)

**Comment by adamhsparks** [comment]
I've come across the same issue having had the same understanding that @tanho63 has expressed here.

**Comment by eeholmes** [comment]
This is also causing me headaches.  Using `git("remote", "set-branches --add", remote, branch)` instead would fix it.

Also I had the same understanding as @tanho63 as to what `deploy_to_branch` does and I find it useful for that purpose. But now I need to run `pkgdown:::git("remote", "set-branches", remote, "*")` after I run `deploy_to_branch()` to fix my repo settings. Note, I also use `deploy_to_branch()` within a GitHub Action and it works fine there, but in some cases I use it locally. When used locally, the `git("remote", "set-branches", remote, branch)` is causing problems.

**Comment by hadley** [comment]
I now think it's better than pkgdown get out of this altogether, as in https://github.com/r-lib/pkgdown/issues/1756.
