### ISSUE TITLE
system-specific rdrr.io links are not resolved correctly

### ISSUE THREAD

**Issue by zeileis** [r-lib/pkgdown#1388]
When adding links to documentation on rdrr.io, pkgdown does not resolve system-specific links correctly.

In more detail: Some packages have system-specific Rd documentation files in `man/unix/*.Rd` and/or `man/windows/*.Rd` which are preserved with the `unix/` and `windows/` directories on rdrr.io. However, pkgdown currently does not include these directories when generating the links to rdrr.io.

Example: Including a link to `parallel::mclapply` links to
<https://rdrr.io/r/parallel/mclapply.html>
rather than
<https://rdrr.io/r/parallel/unix/mclapply.html>

Note: In Rd markup this is often coupled with `#ifdef` tags, see: <https://github.com/r-lib/pkgdown/issues/1384>

**Comment by hadley** [comment]
Any idea where I can find this data? It doesn't seem to be in the info returned by help:

    x <- help("mclapply", package = "parallel")
    str(x)
    #>  'help_files_with_topic' chr "/Library/Frameworks/R.framework/Versions/3.6/Resources/library/parallel/help/mclapply"
    #>  - attr(*, "call")= language help(topic = "mclapply", package = "parallel")
    #>  - attr(*, "topic")= chr "mclapply"
    #>  - attr(*, "tried_all_packages")= logi FALSE
    #>  - attr(*, "type")= chr "text"

<sup>Created on 2020-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by zeileis** [comment]
My understanding is (but I haven't tried to dig deeper here) that the _installed_ help does not know whether it is system-specific or not. So to infer it you might need the source package. Maybe it is an easier workaround to talk to the rdrr.io folks and suggest to link the system-specific pages to the parent directory? If possible all pages and in case of conflicts the unix page only?

**Comment by hadley** [comment]
@ihowson is this something you might be interested in adding?

**Comment by ihowson** [comment]
I've updated rdrr.io to handle this better. If you go to e.g.

- https://rdrr.io/r/parallel/mclapply.html
- https://rdrr.io/cran/sfsmisc/man/Sys.ps.html

it will redirect to the the page in the system-specific dir, preferentially `unix`. 

I didn't find any examples in the R builtin docs where there were name collisions (e.g. `unix/foo` and `windows/foo`). If you come across any cases where rdrr.io is guessing the subdir incorrectly, please let me know.

Does this help?

**Comment by zeileis** [comment]
Thanks, this is much appreciated and solves the problem for our package.

An example for name clashes is `png` in `grDevices` for which both of these exist:
<https://rdrr.io/r/grDevices/unix/png.html>
<https://rdrr.io/r/grDevices/windows/png.html>
The new redirection resolves to the former - as intended:
<https://rdrr.io/r/grDevices/png.html>

So to me this all looks good, thanks again.

**Comment by hadley** [comment]
Closing this since rdrr is now handling it 😄
