### ISSUE TITLE
Add web pages with package dependencies graph and function dependencies graph à la 'pkgnet'

### ISSUE THREAD

**Issue by paulponcet** [r-lib/pkgdown#1396]
The `pkgnet` package (https://github.com/uptake/pkgnet) provides methods to create reports on recursive package dependencies and dependency relationships between functions within the package (through graphs and tables). This information is valuable for a package user, who can e.g. see immediately how complex a given package can be. 

It would be a great feature of `pkgdown::build_site()` to add pages on these two kinds of dependencies to the site created.

**Comment by hadley** [comment]
I think if you want this, you could just include it in a vignette. Unfortunately, I don't think it's a good fit for this package:  developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
