### ISSUE TITLE
Suggestion: option to open external links in a new tab

### ISSUE THREAD

**Issue by davidchall** [r-lib/pkgdown#1397]
Would it be useful to have a pkgdown option that causes external hyperlinks to open in a new tab? The idea is that the user won't lose their browser tab on the documentation site.

AFAIK this would be as simple as introducing some conditional logic to the `a()` function, which checks if `href` is outside the domain of the pkgdown site and then adds `target = "_blank"`. 

https://github.com/r-lib/pkgdown/blob/ecce89ed7fc0bfe4a2ec6e2fdc9285f238e13e7c/R/html-build.R#L1-L3

**Comment by hadley** [comment]
Unfortunately I really dislike sites that take away the ability for the user to choose this, so I'd really prefer not to add to pkgdown.
