### ISSUE TITLE
Greek letters in figures not getting rendered properly with `pkgdown 1.6.0` on R-devel (Windows machine)

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#1400]
Minimal reprex package here (with session info):
https://indrajeetpatil.github.io/minimalReprex/articles/test.html#issue-1400-1

- **Observed** (web browsers used: _Chrome_ and _Firefox_):

![image](https://user-images.githubusercontent.com/11330453/92447981-46a95380-f1b8-11ea-8f63-7a6e55fcba1c.png)

- **Expected**:

![image](https://user-images.githubusercontent.com/11330453/92448033-59bc2380-f1b8-11ea-85c8-dc385af5533f.png)

**Comment by aphalo** [comment]
I see the same in my packages. Problem also affects axis labels. This is under Windows 10 x64 Pro. R 4.0.2 x64. 'pkgdown' 1.6.1. Build of pkg documentation also takes much longer than before. 
Downgrading to  'pkgdown' 1.5.1 fixes the problem.

**Comment by thomasp85** [comment]
What do you get when you call `systemfonts::match_font("Symbol")`?

**Comment by aphalo** [comment]
``` r
systemfonts::match_font("Symbol")
#> $path
#> [1] "C:\\Windows\\Fonts\\symbol.ttf"
#> 
#> $index
#> [1] 0
#> 
#> $features
#> NULL
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aphalo** [comment]
``` r
Sys.getlocale()
#> [1] "LC_COLLATE=English_Finland.1252;LC_CTYPE=English_Finland.1252;LC_MONETARY=English_Finland.1252;LC_NUMERIC=C;LC_TIME=English_Finland.1252"
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by aphalo** [comment]
``` r
sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=English_Finland.1252  LC_CTYPE=English_Finland.1252   
#> [3] LC_MONETARY=English_Finland.1252 LC_NUMERIC=C                    
#> [5] LC_TIME=English_Finland.1252    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] compiler_4.0.2  magrittr_1.5    htmltools_0.5.0 tools_4.0.2    
#>  [5] parallel_4.0.2  yaml_2.2.1      stringi_1.5.3   rmarkdown_2.3  
#>  [9] highr_0.8       knitr_1.29      stringr_1.4.0   xfun_0.17      
#> [13] digest_0.6.25   rlang_0.4.7     evaluate_0.14
```

<sup>Created on 2020-09-17 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by thomasp85** [comment]
This is an issue in ragg (I would argue it is an issue in Windows but that won't get me far🙂). Closing here https://github.com/r-lib/ragg/issues/51 is tracking the same issue in the ragg repo
