### ISSUE TITLE
Auto-linking vignette doesn't work for tibble

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#1401]
Tested with 2f3094c5d522e78aa0a8796f75638f4081fe2829.

``` r
downlit::downlit_md_string('`vignette("tibble", package = "tibble")`')
#> [1] "`vignette(\"tibble\", package = \"tibble\")`\n"
```

<sup>Created on 2020-09-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment]
Looks like I messed this up during the conversion to downlit 😬
