### ISSUE TITLE
Disable creation of "Get Started" section

### ISSUE THREAD

**Issue by lbusett** [r-lib/pkgdown#1405]
Hi, 

  I was wondering if it is possible in any way to disable the creation of the "Get Started" section when a vignette with the name of the package is present within "vignettes". I looked around in the documentation but it does not seem so. 
If so, would you consider adding that possibility in the future? 

 thanks in advance for looking into this, 

Lorenzo

**Comment by hadley** [comment]
You can suppress it in the navbar following the details at https://pkgdown.r-lib.org/reference/build_site.html#yaml-config-navbar
