### ISSUE TITLE
pkgdown version 1.6 is not compatible with gif objects

### ISSUE THREAD

**Issue by arisp99** [r-lib/pkgdown#1406]
Hello all!

I recently updated `pkgdown` from version 1.5.1 to 1.6.1 and found that the update caused problems with vignette building. In particular, gif objects, in my case the result of `gganimate`, cause `pkgdown::build_site()` to error.

I have created a [small package](https://github.com/arisp99/PkgdownExample) on github to showcase this issue. When `pkgdown::build_site()` is run on `pkgdown` version 1.5.1, the article builds. However, when `pkgdown::build_site` is run on `pkgdown` version 1.6.1, an error message appears.

The vignette run and the error message can be found below.

``` r
library(PkgdownExample)
library(gganimate)
#> Loading required package: ggplot2

# Create a static ggplot
p <- ggplot(iris, aes(x = Petal.Width, y = Petal.Length)) +
  geom_point()

plot(p)
```

![](https://i.imgur.com/0TZRrKw.png)

``` r

# Animate the plot
p + transition_states(Species, transition_length = 2, state_length = 1)
```

![](https://i.imgur.com/vmjUARc.gif)

<sup>Created on 2020-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Error message:
```
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 18-29 (Example.Rmd) 
Error : Unsupported device
--------------------------------------------------------------------------------
Error : Failed to render RMarkdown
Error: callr subprocess failed: Failed to render RMarkdown
Type .Last.error.trace to see where the error occured
```

Looking at the changelog of the `pkgdown` package, I suspect this error has something to do with the newly introduced usage of the `ragg` package. It does not seem that `ragg` has a function to draw to a gif file, but I may be misunderstanding the error message.

Any insight would be much appreciated!

**Comment by jeroen** [comment]
I'm running into the same problem. As a workaround you can add this to your `_pkgdown.yml` file:

```
figures:
   dev: grDevices::png
```

**Comment by hadley** [comment]
It's not clear why changing the default device would break gganimate. I think you should follow up on the gganimate side.

**Comment by jeroen** [comment]
I think thomas has already fixed this.

**Comment by jeroen** [comment]
For future reference: https://github.com/thomasp85/gganimate/commit/68871ec21d5e4e6c58ea445e578b25a5e25d46f1
