### ISSUE TITLE
Consider local searching

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1407]
Using [fuse.js](https://fusejs.io).  Would need to generate single `search.json` file from entire site. (Might be able to reuse some of the existing search config by using xml2 to extract from generated xml2). Can still use algolia autocomplete (https://github.com/algolia/autocomplete.js/)

**Comment by hadley** [comment]
A few notes to self after implementing search for bookdown

---

There are four basic parts to implementing the search:

* The search data — a json file generated from R with xml2. Each searchable fragment needs some way to identify it (file name, linkable id, user facing description) and the contents to search.

* The search index, https://fusejs.io, which takes the search data and user query and returns matching fragments. Fuse is very fast and provides all the features we need.

* The search UI, https://github.com/algolia/autocomplete.js/#datasets, which presents results to the user.

* In page highlighting, http://markjs.io/, which shows what you've searched for after you've navigated to the new page.

The key challenge when rolling your own search is to think about what is the "the unit of searching". For vignettes (and the readme), this is relatively straightforward (based on bookdown experience): it's a section. For documentation, it's a bit trickier, but I think we'd want to index parameters individually, and then sections in the rest of the page.

**Comment by maelle** [comment]
Notes from reading Stork docs https://stork-search.net/docs/build
The search index file is built by Stork itself. " a serialized, compressed blob that the Stork Javascript library will download and parse. It usually has the .st file extension, and is roughly the size of a JPEG." So it means adding a system dependency. :thinking:

**Comment by maelle** [comment]
Discussion in bookdown repo https://github.com/rstudio/bookdown/issues/1031

**Comment by maelle** [comment]
On top of the system dependency, having another tool build the search index might not be optimal (even if it's configurable), as we might prefer using our own XPath selectors etc.

**Comment by maelle** [comment]
Need to think about where to build the search index. If I update an article, do I expect the search index to be updated, or would I expect only build_site() to do that.

**Comment by hadley** [comment]
I'd suggest a new exported `build_search()` that would be called by `build_site()` (i.e. make it a new top-level function). That also makes for an obvious place to hang the docs.

**Comment by maelle** [comment]
at the moment the sitemap excludes some pages, was that a design choice? E.g. the changelog, authors page, contributing guide.

**Comment by maelle** [comment]
The sitemap could be built after building all the things, and be

```r
  urls <- paste0(
    url,
    fs::path_rel(
      fs::dir_ls(pkg$dst_path, glob = "*.html", recurse = TRUE),
      pkg$dst_path
    )
  )
```

**Comment by hadley** [comment]
@maelle I doubt it; probably just a bug.

**Comment by maelle** [comment]
It is also due to the fact the sitemap is currently built in `init_site()`, it might make sense to move this step to the end of `build_site()` which I am doing in a branch.

**Comment by hadley** [comment]
I don't think the sitemap is very useful/important so please spend as little time on it as possible.

**Comment by gustavdelius** [comment]
Jay Hesselberth suggested that this issue supersedes issue #1341 in that this new search will properly index also the "Usage" section of the man pages so that one can search for function names. Is that correct?

**Comment by maelle** [comment]
Yes I will go through the search-labelled issues to make sure bugs are fixed. (so please let it open :-) )

**Comment by maelle** [comment]
Note mainly to self: I am going to have to make pkgdown.js a Mustache template because the location of the search index depends on the development mode (i.e. `/search.json` vs `/dev/search.json`).

**Comment by maelle** [comment]
I am now wondering whether there are cases where the development website is not at the same domain as the production website. :thinking:

**Comment by maelle** [comment]
instead of making pkgdown.js a Mustache template I might use a data attribute instead.

**Comment by maelle** [comment]
should Algolia remain an option? cc @cderv

**Comment by maelle** [comment]
> The key challenge when rolling your own search is to think about what is the "the unit of searching". For vignettes (and the readme), this is relatively straightforward (based on bookdown experience): it's a section. For documentation, it's a bit trickier, but I think we'd want to index parameters individually, and then sections in the rest of the page.

Isn't the unit of searching anything under a header with an id (the most precise headers above a piece of content) :thinking: A good thing is that arguments already have an id.

**Comment by maelle** [comment]
although argument ID's have space at the moment.

**Comment by maelle** [comment]
With fuzzy matching, it might be good if highlighting depended on the results, not the query.

**Comment by maelle** [comment]
E.g. "new_procass" would return the right results but not the right highlighting at the moment.

**Comment by maelle** [comment]
But it's probably a bit complicated and not too bad. :grin:

**Comment by maelle** [comment]
what configuration options for users?

* maybe the ability to exclude some paths (regex) from the search index.
