### ISSUE TITLE
Make 'eval.expr = TRUE' explicit in the call to 'yaml::yaml.load_file()'

### ISSUE THREAD

**Issue by paulponcet** [r-lib/pkgdown#1408]
To read the `_pkgdown.yml` file, the function `yaml::yaml.load_file()` is called. This function has an argument `eval.expr` that currently defaults to `TRUE` (`yaml` version `2.2.1`). However, as per the function documentation: 

    There is a built-in handler that will evaluate expressions that are tagged with the ‘!expr’ tag. 
    Currently this handler is enabled by default, but the handler is being disabled by default in an 
    upcoming version for safety and security reasons. If you do not explicity set the eval.expr 
    argument to TRUE, you will get a warning if an expression is evaluated. 

Thus, for compatibility purposes, and in order to anticipate a next release of `yaml`, it would be desirable to set explicitly the argument `eval.expr` to `TRUE`.

**Comment by hadley** [comment]
I don't think we want to be executing yaml, so if anything we'd set the `eval.expr` to `FALSE`.
