### ISSUE TITLE
Hover on footnotes to see content?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1410]
Feature request inspired by @Bisaloo (who suggested it for rOpenSci website a while back) 

Could one click on footnote numbers in the text to see the content without scrolling down?

Example of a JS library that does that https://www.npmjs.com/package/littlefoot h/t @jemus42

**Comment by hadley** [comment]
Likely to happen as part of #1409

**Comment by maelle** [comment]
https://kazzkiq.github.io/balloon.css/
