### ISSUE TITLE
pkgdown issue for GitHub actions

### ISSUE THREAD

**Issue by strengejacke** [r-lib/pkgdown#1412]
I'm not sure where to best place this issue, or if this is a pkgdown issue at all... I have a GitHub-repo (https://github.com/easystats/see) and am using GitHub actions to automatically build the website (https://github.com/easystats/see/blob/master/.github/workflows/pkgdown.yml). This worked well for quite a long time, however, now I get this error and am not sure how to resolve it, or where to ask for help or where to find a solution, so I started trying here.

```
Error in value[[3L]](cond) : 
  cannot pop the top-level viewport ('grid' and 'graphics' output mixed?)
--------------------------------------------------------------------------------
##[error]Error: Failed to render RMarkdown
Backtrace:
    █
 1. └─pkgdown::deploy_to_branch(new_process = FALSE)
 2.   └─pkgdown::build_site(...)
 3.     └─pkgdown:::build_site_local(...)
 4.       └─pkgdown::build_articles(...)
 5.         └─purrr::walk(...)
 6.           └─purrr::map(.x, .f, ...)
 7.             └─pkgdown:::.f(.x[[i]], ...)
 8.               └─pkgdown:::render_rmarkdown(...)
```

(source: https://github.com/easystats/see/runs/1149265534)

Does anybody have a clue why this happens?

**Comment by hadley** [comment]
No idea, sorry, but I'd try by updating to the latest version of the pkgdown workflow, which seems robust in my experience.

**Comment by strengejacke** [comment]
You mean the workflow file directly from this repository? (https://github.com/r-lib/pkgdown/blob/master/.github/workflows/pkgdown.yaml)

**Comment by strengejacke** [comment]
I just realized the `pkgdown.yaml` from the pkgdown-repo (https://github.com/r-lib/pkgdown/blob/master/.github/workflows/pkgdown.yaml) is identical to the one from my repository, except this one line:

```r
options(rmarkdown.html_vignette.check_title = FALSE)
```

**Comment by hadley** [comment]
Our standard templates live in https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml

**Comment by strengejacke** [comment]
Thanks! I'll try it out.

**Comment by strengejacke** [comment]
Great, updating the yaml template seems to have resolved the issue!
