### ISSUE TITLE
Support shared lib folder for htmlwidgets in articles

### ISSUE THREAD

**Issue by crazycapivara** [r-lib/pkgdown#1417]
I am building a pkgdown site where I use the same htmlwidgets in multiple articles.

For every article a sub folder like `article_name_files` is created containing the JavaScript files of the widget.
This blows up the documentation because files are duplicated.
In the yaml header of rmarkdown documents you can define the lib folder:

```
output:
  html_document:
    lib_dir: libs
``` 

But this does not seem to work in pkgdown. I also tried with:

```
pkgdown:
  as_is: true
```

and then adding the ouput section above. But it creates the output folder in the `vignettes` folder instead of the `docs/articles` folder.

Do I miss something?

**Comment by hadley** [comment]
Given that disk space is incredibly cheap, I think unfortunately it's unlikely to be worth the time to figure out exactly how to make this work.
