### ISSUE TITLE
Vignette source links do not account for custom destinations

### ISSUE THREAD

**Issue by JedGrabman** [r-lib/pkgdown#1420]
Vignette articles contain a line "Source: <link to source code>" directly below the title. When a value is set for destination in _pkgdown.yml, the article is still successfully created, but it seems to break the generated URL for these links.

Example:
Our package is at [covidcast/R-packages/covidcast/](https://github.com/cmu-delphi/covidcast/tree/main/R-packages/covidcast/)
In [_pkgdown.yml](https://github.com/cmu-delphi/covidcast/blob/main/R-packages/covidcast/_pkgdown.yml) we set `destination: ../../docs/covidcastR/`

The source link in the [generated article](https://cmu-delphi.github.io/covidcast/covidcastR/articles/covidcast.html) leads to the non-existent
https://github.com/cmu-delphi/covidcast/blob/main/vignettes/covidcast.Rmd

instead of the proper
https://github.com/cmu-delphi/covidcast/blob/main/R-packages/covidcast/vignettes/covidcast.Rmd

Desired behavior:
The source links automatically take into account the destination to generate the proper link
OR
An option to specify the relative location of a package to the github repo root (or some similar option to change the creation process of generating links).

**Comment by hadley** [comment]
I don't see the connection between `destination` and the generated source urls. I think you're actually looking for the repo arguments? https://pkgdown.r-lib.org/reference/build_site.html#yaml-config-repo
