### ISSUE TITLE
Insecure mixed content detected

### ISSUE THREAD

**Issue by samuel-rosa** [r-lib/pkgdown#1422]
I have got the following warning from Netlify:

Insecure mixed content detected

Although you have enabled HTTPS on your site, we’ve detected some content that’s still being served over an HTTP connection. Learn more about mixed content.

In software/febr/index.html:

    Insecure img urls:
        http://www.repostatus.org/badges/latest/active.svg
        http://www.rdocumentation.org/badges/version/febr
        http://cranlogs.r-pkg.org/badges/febr?color=brightgreen

I am guessing that this needs to be solved internally. Please let me know if I can help, e.g. preparing a pull request.

**Comment by maelle** [comment]
These are the links in your README badges, I made a PR there :-)
