### ISSUE TITLE
Creating a custom menu with override

### ISSUE THREAD

**Issue by tonytrevisan** [r-lib/pkgdown#1423]
It does not appear possible to create a custom menu using override. I can get to the point where the menu will show with a drop down, but when I try to populate it, I get an error.

The code that works to create an empty menu:

```R
pkgdown::build_site(override = list(
  navbar = list(structure = list(right = c('test_menu','github')),
                components = list(test_menu = list(text = 'Test Menu', 
                                                   menu = list())))))
```
![image](https://user-images.githubusercontent.com/45466366/96467327-cb947d80-11f8-11eb-8a14-f2c58ae5a025.png)

When I try to populate the menu, I get the error: Error : $ operator is invalid for atomic vectors
```R
pkgdown::build_site(override = list(
  navbar = list(structure = list(right = c('test_menu','github')),
                components = list(test_menu = list(text = 'Test Menu', 
                                                   menu = list(text = 'Item 1', href = 'https://pkgdown.r-lib.org/'))))))
```
![image](https://user-images.githubusercontent.com/45466366/96467382-d8b16c80-11f8-11eb-9a3c-b61f08f7273a.png)

**Comment by hadley** [comment]
I'd recommending getting it working in yaml, then using `yaml::read_yaml()` to figure out exactly what R data structure it wants.

**Comment by tonytrevisan** [comment]
Thank you Hadley. I took your suggestion and figured it out with some trial and error.

```R
pkgdown::build_site(override = list(
  navbar = list(structure = list(left = c(testmenu = c('one','two')),
                                 right = c('github')),
                components = list(test_menu = list(text = 'Test Menu', 
                                                   menu = list(one = list(text = 'Item 1', href = 'https://pkgdown.r-lib.org/'),
                                                               two = list(text = 'Item 2', href = 'https://pkgdown.r-lib.org/')))))))
```
![Screen Shot 2020-11-03 at 9 09 27 PM](https://user-images.githubusercontent.com/45466366/98061051-10cfc680-1e19-11eb-886f-00cfe7f730af.png)
