### ISSUE TITLE
fail to build in GitLab CI with `Error in strsplit(cnd$stderr, "\r?\n") : non-character argument`

### ISSUE THREAD

**Issue by statnmap** [r-lib/pkgdown#1424]
The site is correctly built locally but when we send it to the CI it fails for some vignettes with this error:  
```
Error in strsplit(cnd$stderr, "\r?\n") : non-character argument
```
I suspect this has something to do with line-ending character between Windows and Linux. However, everyone verified they have set it to `LF` in RStudio global options.  
At first, changing the Docker container helped solved the error once or twice, but now it keeps coming back for some files, even with empty vignettes. Also, when I develop inside the Docker container, it compiles correctly.  

I am not able to provide a reproducible example, but I can share the repository and the Ci log file : https://gitlab.com/rdes_dreal/propre.rpls/-/jobs/803092186  
Also, if you look at the history of the CI, you can follow when I started to fail : https://gitlab.com/rdes_dreal/propre.rpls/-/pipelines?page=1&scope=all&ref=dev  
I know that without the reprex, it can be difficult to spot the problem, but I am looking for new directions to look for.   
Thank you

**Comment by statnmap** [comment]
Maybe it is better to first try to discuss this on community. So I opened a question there to see if this is really a {pkgdown} bug : https://community.rstudio.com/t/fail-to-build-in-gitlab-ci-with-error-in-strsplit-cnd-stderr-r-n-non-character-argument/85405

**Comment by hadley** [comment]
I doubt this has anything to do with line-endings, and given that I don't see that use of `strsplit()` anywhere in pkgdown, it likely is occurring elsewhere. I'd recommend starting by getting a traceback.
