### ISSUE TITLE
pkgdown::build_site() fails if rsconnect directory in vignettes/

### ISSUE THREAD

**Issue by DavidPatShuiFong** [r-lib/pkgdown#1425]
This seems to be the same problem as https://github.com/r-lib/pkgdown/issues/315, which was fixed with 956ea1a50ba8993f6345659de66cfa30c8d53ec5, but I still see an error message with `pkgdown` version 1.6.1 . I am using Linux.

```r
> pkgdown::build_site()
Error in readLines(con, warn = FALSE) : cannot open the connection
In addition: Warning messages:
1: In base::file(file, encoding = "UTF-8") :
  'raw = FALSE' but './vignettes/rsconnect/documents/dtedit.Rmd' is not a regular file
2: In readLines(con, warn = FALSE) :
  cannot open file './vignettes/rsconnect/documents/dtedit.Rmd': it is a directory
> packageVersion("pkgdown")
[1] ‘1.6.1’
```

My package is `dtedit`, and I have uploaded a version of the vignette to Rpubs.

As a result, there is a `rsconnect/documents/dtedit.Rmd/rpubs.com/rpubs.com/rpubs` directory (not a file) in the `vignettes/` directory.

`pkgdown::build_site()` works well if I move the `rsconnect` directory in `vignettes/` somewhere else.

**Comment by hadley** [comment]
Quick reprex:

```R
fs::dir_create("vignettes/rsconnect/documents/dtedit.Rmd/rpubs.com/rpubs.com/rpubs")
pkgdown::build_articles()
```
