### ISSUE TITLE
Articles TOC on mobile devices not available

### ISSUE THREAD

**Issue by mrcaseb** [r-lib/pkgdown#1431]
As far as I know the sidebar toc is not available on mobile devices (I assume it's depending on display width). 

It would be especially helpful to copy hyperlinks to sections from within the toc (on mobile devices of course).

Did I miss how to add the toc to mobile devices or is it not implemented, yet?

**Comment by hadley** [comment]
There's no place to put a TOC on mobile, and unfortunately the anchors hang off to the left. This will get resolved as part of #1409 where I update pkgdown with what I learned on http://mastering-shiny.org/.
