### ISSUE TITLE
Aliases starting with `@` are not included in reference index

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgdown#1436]
I think this is a bug since they are documented to be included:

```r
#' * A **list of topics** (`contents`), which generates one row for each topic,
#'   with a list of aliases for the topic on the left, and the topic title
#'   on the right.
```

This seems to fix it: https://github.com/lionel-/pkgdown/commit/c14cf12294cb7311405c4327dab589ff5d422a2d

I can open a pull request if this is indeed a bug and the patch looks reasonable.

**Comment by lionel-** [comment]
oops that's only the case when the aliases start with `@`.

**Comment by hadley** [comment]
Related to #1624 — the common thread is we want to document things that aren't functions (or even exist as objects in the package), and thus don't appear in the usage. Maybe there would be some way to side load this information to usage? 

Anyway, I'm going to close for now, but the general idea remains alive in https://github.com/r-lib/roxygen2/issues/1170
