### ISSUE TITLE
pkgdown build/deploy action fails; can't find package mentioned in README but otherwise unused

### ISSUE THREAD

**Issue by kjhealy** [r-lib/pkgdown#1438]
I have a data package, [covdata](https://github.com/kjhealy/covdata), that I build every few days. It passes R CMD check. Normally, its [website](https://kjhealy.github.io/covdata) is deployed to `gh-pages` by a pkgdown GitHub action. The action is identical to the `pkgdown.yaml` example in `r-lib/actions`. Today the action started to fail with the following error:

```
Error in find.package(package, lib.loc) :  there is no package called ‘drat’
Calls: <Anonymous> ... find_vignette_package -> <Anonymous> -> find.package
11 Removing worktree 11111111111111111111111111111111111111111111111111111111111
Running git worktree remove \
  /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/RtmpMX9uKh/file74515d6f867
Execution halted
```

The [drat package](http://dirk.eddelbuettel.com/blog/code/drat/) is mentioned in the [README.Rmd](https://github.com/kjhealy/covdata/blob/6868321ec74f94da384c1338d832f05ae28e0509/README.Rmd) and [README.md](https://github.com/kjhealy/covdata/blob/6868321ec74f94da384c1338d832f05ae28e0509/README.md) files. It's mentioned as an option for installing the package with `install.packages()`, as an alternative to `install_github()`. However, `drat` is not part of the actual package in any way. The only place it is mentioned is in the README. In the course of trying to diagnose the problem, I also made sure that the mention in the `Rmd` file does not happen in a code chunk: it's just pure markdown. (Previously it had been in a code chunk with the `eval = FALSE` option set in the chunk header.)

So I'm not sure why this is happening. Why is pkgdown or GitHub action complaining it can't find this package?

**Comment by kjhealy** [comment]
On further investigation I found that the problem went away if I either (a) Deleted all references to `drat` in the `README.Rmd` file (recall that these just references in pure Markdown, not in R code chunks), _or_ (b) Added `drat` to the "Suggests" section of the `DESCRIPTION` file.  I should investigate more to see if mentioning but not calling other packages in `README.Rmd` triggers a similar error.

**Comment by hadley** [comment]
I'm pretty sure that this was a bug in downlit that has now been fixed.
