### ISSUE TITLE
Add a trailing slash to enable Netlify redirects

### ISSUE THREAD

**Issue by apreshill** [r-lib/pkgdown#1439]
Hi @hadley,

We ran into trouble using [Netlify 200 rewrite redirects](https://docs.netlify.com/routing/redirects/redirect-options/) and pkgdown sites. To make it work, we needed to inject a teensy bit of JavaScript (written by @gadenbuie) into the pkgdown template. 

```
<script>
  if (!/(\/|html?)$/.test(window.location.href)){
    window.location.replace(window.location.href + '/');
  }
</script>
```

But, adding it inside `extra.js` won't help because it also won't be found due to the missing trailing slash problem. Here was @cderv's solution as a PR:

<https://github.com/apreshill/quillt/pull/3>

That is probably all you need to know, but I'll use the rest of this issue to "document" the play-by-play too, in case others run into the same trouble. Unfortunately, Netlify has no way to redirect the same url minus the trailing slash, so if you don't include the trailing slash in the url you see a site without CSS. The Netlify docs clearly state: 

> “You cannot use a redirect rule to add or remove a trailing slash.”

There is this related community discussion thread: <https://community.netlify.com/t/bug-in-non-trailing-slash-rewrite/452>

Explanation courtesy of @gadenbuie:

> The pkgdown site doesn't include the leading slash (i.e., `/quillt`, the package name we tested with) so when the page at `https://pkgs.rstudio.com/quillt` references `rmd.css,` the browser looks for it in the current path. This is normally the right thing to do, but here's where the redirect messes things up. Because the trailing slash isn't added, the browser thinks the current base path is `https://pkgs.rstudio.com/` without the `quillt`. So it looks for `https://pkgs.rstudio.com/rmd.css` instead of `https://pkgs.rstudio.com/quillt/rmd.css`.

**Comment by cderv** [comment]
It could be interesting to have this included into the pkgdown template for `home.html` or at least having an option to include it. 

Currently we included a `in-header-home.html` template in our pkgdown template **quillt**
https://github.com/rstudio/quillt/blob/master/inst/pkgdown/templates/in-header-home.html

Usually you want that your server adds a trailing / if missing. Having it in the pkgdown template would making work no matter where the site is hosted.

For us, this is interesting to allow rewrites / redirects to work without the url in adress bar changing and/or having assets incorrectly loading. 

See difference with or without trailing slash
* https://pkgs.rstudio.com/learnr
* https://pkgs.rstudio.com/learnr/ 

Or 
* https://deploy-preview-6--rstudio-pkgs.netlify.app/learnr
* https://deploy-preview-6--rstudio-pkgs.netlify.app/learnr/

Adding this by default for all pkgdown website could be interesting, but at least allowing to add such redirects would help customize some of the existing website.
