### ISSUE TITLE
get _pkgdown.yml url: from DESCRIPTION

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#1445]
I understand that something like 

```yaml
url: https://subugoe.github.io/hoad/
```

in the `_pkgdown.yml` is necessary for proper cross-linking (and search?).

I'd imagine that this info is already included in the `DESCRIPTION` `URL` for many projects.

I'm on a bit of a quest to reduce duplication in code, and this is a small but somewhat confusing one.

Of course, as a complication, `DESCRIPTION` `URL` can include *many* URLs, not just the public-facing pkgdown one.
But I think it's a reasonable assumption that whichever of these `URL`s is *not* `github.com` or in any event, the same host as `BugReports`, *is* probably the public facing pkgdown site.

In my projects I now infer the `_pkgdown.yml` `url:` field like so:

```r
get_url_from_desc <- function() {
  all_urls <- desc::desc_get_urls()
  gh_urls <- sapply(all_urls, is_gh_url)
  public_urls <- all_urls[!gh_urls]
  public_urls[1]
} 

is_gh_url <- function(url) {
  httr::parse_url(url)$hostname == "github.com"
}
```

Would be happy to draft a PR to that effect.

**Comment by hadley** [comment]
This seems backwards to me, because you can't set the DESCRIPTION url until you have a website. And as you note, inferring from the url is dangerous and seems like to generate false positives across the spectrum of packages that currently use pkgdown.
