### ISSUE TITLE
Meta name option for Google Search Console

### ISSUE THREAD

**Issue by sarahemlin** [r-lib/pkgdown#1449]
<img width="626" alt="Screen Shot 2020-11-23 at 1 35 30 PM" src="https://user-images.githubusercontent.com/55722001/100022107-74ee0680-2d97-11eb-909f-3c20ac391bd7.png">

Hi,

I'm working on connecting RStudio's sites, many of which are made with pkgdown, to Google Search Console, which allows us to see metrics on what users search for on Google to get to a particular site.  In order to verify a site through the Search Console, the GA tracking code needs to be set up in a specific way that would necessitate editing the <head> tag on a pkgdown website.  Since editing the generated code is [not recommended](https://github.com/rstudio/keras/blob/master/website/index.html), it would be helpful for any pkgdown user to have a field in which to enter the Search Console tag:
<meta name="google-site-verification" content="#generated_code"
I've attached a screen shot of what it looks like on the admin side for Search Console users.  

Thanks,
Sarah

**Comment by jayhesselberth** [comment]
Would you mind pasting in the actual meta tag from above? Want to confirm its structure; it only needs `name` and `content`?

**Comment by sarahemlin** [comment]
Hi @jayhesselberth

Here's an example from one site: 
<meta name="google-site-verification" content="_nn6iIe-a6x6IctOWCeXNuyDOOO1_GvlSIpGnavx7fo" />

Hopefully that helps!  

Thank you,
Sarah

**Comment by jayhesselberth** [comment]
I don't think you pasted anything?

**Comment by jayhesselberth** [comment]
nm, it's hidden by the issue HTML. PR #1450 is ready to go.
