### ISSUE TITLE
build-home-index should not add the cran link automatically

### ISSUE THREAD

**Issue by stefanoborini** [r-lib/pkgdown#1451]
We have internal packages that happen to have names that are present on CRAN. This results in pkgdown arbitrarily adding the cran link to a package that has absolutely nothing to do with the CRAN package.

pkgdown should not do that, or at least it should be disabled by default and provided as an option.

**Comment by maelle** [comment]
I think that if you use the option `pkgdown.internet` the CRAN link won't be added https://pkgdown.r-lib.org/reference/build_site.html#options.

From a quick look into where `has_internet()` is used, it might really just affect CRAN things since the downlit packages does not use the option?

**Comment by hadley** [comment]
I think this is out of scope for pkgdown, unfortunately.

**Comment by stefanoborini** [comment]
> I think this is out of scope for pkgdown, unfortunately.

How can it not be in scope for pkgdown? it's literally something that pkgdown does that is not supposed to do.

**Comment by hadley** [comment]
Here's a longer explanation for you: Creating internal packages with the same name as CRAN packages is not a common activity. We have to balance the limited developer time that we can spend on pkgdown in ways that we judge will help the largest number of people. I don't believe that disabling autolinking to CRAN package is likely to help a significant number of people apart from you.

**Comment by stefanoborini** [comment]
Any company that uses the software that your company makes will have internal packages, because companies don't like revealing their trade secrets. This aside, the fact is that it is poor design to assume and take decisions you can't take, and guess wrong by doing so. pkgdown has a design flaw, and it remains regardless of the fact that you decide unilaterally to ignore the feedback from one of your customers and dismiss it as not an issue.
