### ISSUE TITLE
Link to function not working for last function in a table

### ISSUE THREAD

**Issue by jrosen48** [r-lib/pkgdown#1455]
The way pkgdown can identify functions with references and link to them is awesome!

In [the README for the konfound package](https://github.com/jrosen48/konfound/), there is a table with functions for the package in different cells.

![Screen Shot 2020-12-05 at 1 49 50 PM](https://user-images.githubusercontent.com/4596214/101260853-c5068a80-3700-11eb-9151-77c5f7df5aae.png)

When that section of the README is rendered for the pkgdown site ([available here](https://raw.githubusercontent.com/jrosen48/konfound/master/README.Rmd)), all of the functions except for the last one (in the last row, and last column of the second table) link to their associated reference. 

![Screen Shot 2020-12-05 at 1 50 22 PM](https://user-images.githubusercontent.com/4596214/101260873-e5cee000-3700-11eb-8353-9f1d246bfed3.png)

[The raw code](https://raw.githubusercontent.com/jrosen48/konfound/master/README.md) seems to be fine; there doesn't seem to be anything different. Do you have any idea why there is this issue?

**Comment by Bisaloo** [comment]
My guess is that it's due to the missing closing parenthesis

**Comment by jrosen48** [comment]
I don't see a missing closing parenthesis: https://raw.githubusercontent.com/jrosen48/konfound/master/README.Rmd

**Comment by jrosen48** [comment]
addressed by PR from @Bisaloo
