### ISSUE TITLE
SVG images do not load in vignette

### ISSUE THREAD

**Issue by royfrancis** [r-lib/pkgdown#1458]
If I have a simple vignette like this:

````
---
title: "Title"
output: 
  rmarkdown::html_vignette:
    number_sections: true
---

```{r,include=FALSE}
knitr::opts_chunk$set(dev="svg")
```

```{r}
plot(iris$Sepal.Length,iris$Petal.Length)
```
````
The output has missing images.

![Screenshot from 2020-12-22 23-14-52](https://user-images.githubusercontent.com/5083500/102938172-0db59600-44ac-11eb-900e-b5faa98bd6dd.png)

Removing chunk option `dev="svg")` seems to make it work. This took a long time to figure out because I thought it was something to do with knitr paths.

R version 4.0.0  
pkgdown_1.6.1

**Comment by jayhesselberth** [comment]
Have you tried also setting `fig.ext` as in https://github.com/r-lib/pkgdown/issues/693#issuecomment-438060509

**Comment by royfrancis** [comment]
Yes! Adding `fig.ext="svg"` includes the images correctly. Thanks!
