### ISSUE TITLE
Menu icon is broken

### ISSUE THREAD

**Issue by royfrancis** [r-lib/pkgdown#1460]
The Github icon on the navbar is broken for me. It looks like this:

![Screenshot from 2020-12-27 19-16-56](https://user-images.githubusercontent.com/5083500/103177169-56889880-4878-11eb-89ef-eee74821e5bd.png)

Digging into this a bit, I noticed that icon span looks like below.

`<span class="fas fa-github fa-lg"></span>`

Changing class `fas` to `fa` or `fab` makes it work.

`<span class="fa fa-github fa-lg"></span>`

![Screenshot from 2020-12-27 19-16-27](https://user-images.githubusercontent.com/5083500/103177203-9780ad00-4878-11eb-8359-f65306e6ee4c.png)

Perhaps the issue is with the default style used in this line:

`navbar.R:144:menu_icon <- function(icon, href, style = "fas") {`

But in some other places, I also see `style="fab"` being used.

`navbar.R:74:    menu$github <- menu_icon("github", pkg$github_url, style = "fab")`

Anyway, is there some way to change the style through `build_site()` or the yml file or something?
Thanks.

R 4.0.0  
pkgdown_1.6.1

**Comment by jayhesselberth** [comment]
The font awesome class for [github is `fab`](https://fontawesome.com/icons/github?style=brands) and the icon is fine on the pkgdown homepage with class `fab`. 

Have you tried `clean_site()` and then `build_site()`? Wondering if there are older header specifying a previous FA version.

**Comment by royfrancis** [comment]
Hmmm. Here is an example that is not on my computer or even my website at all. I see the same issue (As of now 18-Jan-2021).

https://patchwork.data-imaginist.com/

![Screenshot from 2021-01-18 10-20-16](https://user-images.githubusercontent.com/5083500/104896113-fe285080-5976-11eb-8661-fcb39a075417.png)

The github icon appears as is a broken link in firefox. It is completely invisible in Chrome (but still clickable). The span class is `fas fa-github fa-lg`. This was a reason that I thought it was not a local issue just for me. 

Anyhow, I have fixed it by replacing `fas fa-github fa-lg` with `fab fa-github fa-lg` in all html files. 

I will also look into if it's a caching issue as you have mentioned.

**Comment by davidski** [comment]
I think this is a problem with older sites generated from pre-1.4.0 versions of pkgdown. The GitHub icon is typically controlled via the `navbar` stanza in your `_pkgdown.yml` file. There's an icon line that many folks (myself included) probably have as ` - icon: fa-github fa-lg`. With the changes to FontAwesome's class system, that line needs to be re-written as ` - icon: fa-github fa-lg fab`. pkgdown 1.4.0 updated the template generation process to include the `fab` class.

You can see this missing class on Patchwork's _pkgdown.yml file, which has the old syntax [here](https://github.com/thomasp85/patchwork/blob/79223d3002e7bd7e715a270685c6507d684b2622/_pkgdown.yml#L41).

**Comment by jayhesselberth** [comment]
This should be fixed by upgrading pkgdown and then running `clean_site()` and `build_site()`. Please re-open if you have further issues.
