### ISSUE TITLE
Navbar dropdown broken

### ISSUE THREAD

**Issue by jscott6** [r-lib/pkgdown#1461]
Suppose you have a vignette example.Rmd with a YAML header as follows:

```r
---
title: "example"
output:
  bookdown::html_document2
pkgdown:
  as_is: true
---
```
The navbar dropdowns (for example the Articles section) do not work from docs/articles/example.html. Removing `as_is: true` appears to fix the problem. This occurs using pkgdown version 1.6.1, but does not happen with 1.5.1. You can find a minimal example package [here](https://github.com/jscott6/pkg).

**Comment by maelle** [comment]
I can see this in https://pkgdown.r-lib.org/articles/test/output.html

I am not sure it is a pkgdown version problem, I assume it is because the bootstrap CSS&JS files are included twice (once by pkgdown, once by `bookdown::html_document`).

**Comment by hadley** [comment]
Maybe we need to revisit the `theme` issue.
