### ISSUE TITLE
Update pkgdown usage search query

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#1462]
[This link](https://github.com/search?q=pkgdown.css+in%3Apath&type=Code) on the README now reports that pkgdown is used by over 173 million packages (!).

**Comment by Bisaloo** [comment]
https://github.com/search?l=&q=filename%3Apkgdown.css&type=code

?

**Comment by Bisaloo** [comment]
The problem is that it only counts packages that use the `docs/` approach, not the currently recommended `gh-pages` branch approach.

**Comment by hadley** [comment]
173 million packages seems totally plausible to me 🤣

**Comment by hadley** [comment]
I wonder where all the false matches are from. Is this just a temporary glitch with the github search index/api?

**Comment by hadley** [comment]
Looks like this is back to the expected ~5k

**Comment by hadley** [comment]
I think this new search might be an underestimate because search only covers the main branch, not the gh-pages branch where many site will live.

**Comment by hadley** [comment]
Maybe https://github.com/search?q=filename%3A_pkgdown.yml+path%3A%2F&type=Code ?

**Comment by hadley** [comment]
Or maybe this: https://github.com/search?q=filename%3Apkgdown.yml%22+-pandoc&type=Code

The problem is that `filtename:_pkgdown.yml` also matches the generated `doc/pkgdown.yml` so I exclude a word that always occurs in `docs/pkgdown.yml` but should be rare in `_pkgdown.yaml`
