### ISSUE TITLE
/man and /reference and figures

### ISSUE THREAD

**Issue by topepo** [r-lib/pkgdown#1472]
The [build home](https://github.com/r-lib/pkgdown/blob/e1e46f2e13c7efdb17bc4eae40bc3779c2b0b517/R/build-home.R#L64) file has: 

> `@section Images and figures`:  If you want to include images in your `README.md`, they must be stored somewhere in the package so that they can be displayed on the CRAN website. The best place to put them is `man/figures`. If you are generating figures with R Markdown, make sure you set up `fig.path` as followed:

It looks like the site pages convert or copy the `man` directory to one called `reference` for the README file, but not for articles. 

For example, the [`rules` vignette](https://github.com/tidymodels/rules/blob/4af59ef30b5dca9556f1ad1a36f4a57b4cab7672/vignettes/Cubist-and-RuleFit.Rmd#L32) does this and results in a broken link. However, [this line](https://github.com/r-lib/vctrs/blob/41f841e1a86684cf6a5a56ad8c7747aaa5a781bc/vignettes/type-size.Rmd#L329) in the `vctrs` docs works but it looks like this is due to vestigial `man` files being left around.

**Comment by john-harrold** [comment]
I'm experiencing this problem as well. The only way I can get images to work  in my vignettes is to uuencode them:

```
b64_png          = knitrdata::data_encode("file.png"         , encoding="base64")
``` 

And then just spit that encoded image out:

![Example Image.](data:image/png;base64,`r b64_png`){width=600px}

The main drawback here is that it doubles the size of my images because there are essentially two copies of each image. The original image file and the encoded image in the vignette. I'd be happy to hear of any work arounds you have.

**Comment by dmurdoch** [comment]
I just tried the following workaround, and it seems to work:  

You can commit `man/figures/file.png` to the `gh-pages` branch as well as the main branch, and it will be available on the web page.  

There are still some significant issues:  if you are in the `dev` version of the web page, the relative path to the figure is different than if you are in the release version, and if you make changes to the figure they will need to be manually saved again in the branch.  But you can avoid having two copies of the figure in your tarball.

**Comment by john-harrold** [comment]
I looked into the different files that are being generated. My problem is that the figures are being placed into the articles directory but the html for the vignettes that's being generated has a `src` value that looks like:

```
<img src="../../../../../path/to/repo/vignettes/image.png"/>
```
The `../../` stuff goes back to my home directory. I have no idea why it's doing that. I thought about it and the hack that I'm using just reads in every html file in `docs/articles`, searches for the string `../../../../../path/to/repo/vignettes/` and replaces it with `""`. It's part of the build script and doesn't take any time at all, so it seems to work pretty well.

**Comment by hadley** [comment]
@john-harrold I suspect your problem is different. I'd recommend creating a minimal reprex (as in https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md#package-reprexes) and then filing a new issue.

**Comment by Shelmith-Kariuki** [comment]
Hi, 

I guess I faced a similar issue to what Max Khun faced, where my pkgdown website logo was kind of not been found when running RMD Check on GitHub actions (See the first screenshot). 

I have updated pkgdown to the latest version to try sort out the issue and now, the logo is being distorted (see the second screenshot) while it should appear as in the third screenshot (the pkgdown website as of end of day Friday). Please help

![image](https://user-images.githubusercontent.com/37449624/144809683-4e0c534b-7c85-4583-8f83-3ed7b3e634fb.png)

![image](https://user-images.githubusercontent.com/37449624/144809779-d6543a25-5600-48dc-aa26-32a788835e87.png)

![image](https://user-images.githubusercontent.com/37449624/144809910-0abbb605-13c4-4edc-be0d-bf04531ffdac.png)

**Comment by hadley** [comment]
@Shelmith-Kariuki this issue is unrelated. You need to set the width of your logo, not the height.

**Comment by Shelmith-Kariuki** [comment]
I meant, I was facing the issue that Max was (I guess) and in the process of sorting it out through updating pkgdown, it distorted the logo ... but I will change the dimension issue now. Thanks
