### ISSUE TITLE
 hook_ffmpeg uses absolute path for the output video

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1474]
Reprex:

````r
dir.create("vignettes")
usethis::use_description()
write(
"---
output: rmarkdown::html_document
---
```{r, animation.hook='ffmpeg'}
for (i in 1:2) {
  pie(c(i %% 2, 6), col = c('red', 'yellow'), labels = NA)
}
```
",
"vignettes/test.Rmd"
)

pkgdown::build_article("test")

source <- readLines("docs/articles/test.html")
grep("webm", source, value = TRUE)
# > [1] "<video width=\"700\" controls loop><source src=\"/home/hugo/Projects/Current/docs/articles/test_files/figure-html/unnamed-chunk-1.webm\"></source></video>"

# This is not an error in rmarkdown
write(
"---
output: 
  rmarkdown::html_document:
    self_contained: false
---
```{r, animation.hook='ffmpeg'}
for (i in 1:2) {
  pie(c(i %% 2, 6), col = c('red', 'yellow'), labels = NA)
}
```
",
"vignettes/test.Rmd"
)

rmarkdown::render("vignettes/test.Rmd")
source <- readLines("vignettes/test.html")
grep("webm", source, value = TRUE)
# > [1] "<source src=\"test_files/figure-html/unnamed-chunk-1.webm\" />"
````

Real-life example:

https://bisaloo.github.io/semaforos/articles/semaforos.html

The video is not found because it uses the absolute path from the GitHub actions worker:

`<source src="/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/Rtmp2ClLqS/file13f914c9ce93/articles/semaforos_files/figure-html/unnamed-chunk-3.webm">`

The path in this case should be:

`<source src="articles/semaforos_files/figure-html/unnamed-chunk-3.webm">`

**Comment by hadley** [comment]
Isn't this a problem with `hook_ffmpeg`?

**Comment by Bisaloo** [comment]
I don't think so. Or at least, not in isolation from pkgdown. See https://github.com/yihui/knitr/issues/1953 and the second part of my reprex. `hook_ffmpeg` used with `rmarkdown::render()` produces a relative path. It's only in combination with pkgdown that it produces an absolute path.

**Comment by hadley** [comment]
Ok. Unfortunately the chances of me looking into this are basically zero (given that I'd never even heard of `hook_ffmpeg`) before. So I'm going to close the issue to avoid giving you any false hope 😄
