### ISSUE TITLE
Add a sitrep/check function?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1478]
Like what blogdown has now. E.g. the function could tell you the URL field is missing from the configuration and DESCRIPTION.

**Comment by maelle** [comment]
I saw that `usethis::use_pkgdown()` has an useful hint.

**Comment by hadley** [comment]
Yeah, I think that would be reasonable. We'd start with:

* Checking that `url` is defined in `_pkgdown.yml`
* If defined, checking that it's also present in the `Url` field

**Comment by maelle** [comment]
Would `build_site()` run it? Probably not? Wondering when it'd be used.

**Comment by hadley** [comment]
I think you'd run it if auto-linking wasn't working for your site.
