### ISSUE TITLE
Formatting after \item{} entries lost in \value{} section.

### ISSUE THREAD

**Issue by wviechtb** [r-lib/pkgdown#1479]
Say the `\value{}` section looks like this:

    \value{
       An object of class \code{"blah"}. The object is a list with the following elements:
       \item{x}{some element.}
       \item{y}{some element.}
    
       Any formatting \code{here} is lost.
       \item{z}{however \code{this} is rendered correctly.}
    }

As noted above, the `\code{here}` will not be rendered as `<code>here</code>` in HTML. However, formatting in additional `\item{}` entries is rendered correctly.

**Comment by hadley** [comment]
This isn't what's documented for `\value`:

> If a list with multiple values is returned, you can use entries of the form
> 
> \item{comp_i}{Description of comp_i.}
> for each component of the list returned. Optional text may precede this list (see for example the help for rle).

But I guess even `rle()` uses multiple text blocks: https://github.com/wch/r-source/blob/trunk/src/library/base/man/rle.Rd#L39-L46
