### ISSUE TITLE
Error: <template> does not contain 'inst/pkgdown/templates/BS3'

### ISSUE THREAD

**Issue by apreshill** [r-lib/pkgdown#1496]
👋 @maelle!

I'm building a pkgdown site from a custom template:

https://github.com/apreshill/quillt

@cderv and I are revamping the rmarkdown pkgdown site with this new template, and noticed this new error in our GHA build using dev pkgdown:

https://github.com/apreshill/rmarkdown/runs/1889402801?check_suite_focus=true#step:8:52

```
Error: Error: quillt does not contain 'inst/pkgdown/templates/BS3'
Execution halted
Error: Process completed with exit code 1.
```

**Comment by hadley** [comment]
Maybe we need to fall back to the bare template directory if there's no BS3/BS4 subdirs?
