### ISSUE TITLE
Typo in `build_reference` documentation

### ISSUE THREAD

**Issue by fangzhou-xie** [r-lib/pkgdown#1504]
Thanks for this wonderful package! 

I was using this package to build a package website of my own R package and I noticed that there is a typo in the `build_reference` function documentation. Namely, there is an extra backtick `` ` `` in [line 132](https://github.com/r-lib/pkgdown/blob/master/R/build-reference.R#L132).

By having that extra backtick `` ` ``, the documentation on argument `topics` is not displaying properly.

Thanks.

**Comment by hadley** [comment]
Would you like to do a PR?

**Comment by fangzhou-xie** [comment]
I have created the PR (#1505). Thanks!
