### ISSUE TITLE
Repeated accessible-code-block-0.0.1/empty-anchor.js for all articles

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1509]
The file accessible-code-block-0.0.1/empty-anchor.js is present once by article, it might make sense to only include it once & fix the path in all articles?

**Comment by maelle** [comment]
Or maybe pkgdown could do what this script does (adding aria-hidden to anchors in code).

**Comment by maelle** [comment]
Pandoc version above which the aria-hidden tag is added by Pandoc https://pandoc.org/releases.html#pandoc-2.10.1-2020-07-23

**Comment by maelle** [comment]
https://github.com/rstudio/rmarkdown/issues/2051

**Comment by hadley** [comment]
Closing, since I think you're right that this should be handled upstream in rmarkdown.
