### ISSUE TITLE
Add a contribution field for authors?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1511]
I.e. one could not only add an URL and HTML but also a contribution string e.g. "Jane Doe created the package to win a bet and maintained it until she became a baker in 2018", that'd be used for the authors page.

**Comment by maelle** [comment]
And when it is present, even if all authors are listed in the sidebar, there'd be a link to the authors page from the sidebar, "More about authors".

**Comment by maelle** [comment]
Maintainer change for good/dramatic reasons would be an use case for sure but there might be other use cases such as adding a human touch. 🤔

**Comment by hadley** [comment]
Apart from the comments field in `person()`?

**Comment by maelle** [comment]
Right maybe another field isn't useful. Maybe one would store different/complementary info there, and with a better format?

In any case in the presence of comments maybe there could be a link to the authors page even when all authors are in the sidebar? I.e. amending the logic of `needs_page`.

**Comment by hadley** [comment]
Amending the needs_page logic sounds good to me.
