### ISSUE TITLE
<details> element and padding

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#1514]
looks odd on https://pillar.r-lib.org/dev/articles/printing.html#header-body-footer-1, screenshot taken from region just above the link. The padding between the disclosure widget and the subsequent text is smaller than that between widget and preceding text:

![Screenshot from 2021-02-20 17-25-31](https://user-images.githubusercontent.com/1741643/108602152-c448d080-73a0-11eb-9720-8558ab9cd2b6.png)

**Comment by hadley** [comment]
Need to match margin to other block elements.
