### ISSUE TITLE
custom footer in template package seems to be overriden by default footer

### ISSUE THREAD

**Issue by cderv** [r-lib/pkgdown#1518]
Found in packages using **quillt** template. 

We have a custom footer (https://github.com/apreshill/quillt/blob/master/inst/pkgdown/templates/footer.html#L2)
This should also break packages using **tidytemplate** (https://github.com/tidyverse/tidytemplate/blob/master/inst/pkgdown/templates/footer.html#L2)

It does not appear anymore using dev version of **pkgdown**. From a discussion with @maelle it could come from https://github.com/r-lib/pkgdown/commit/1ca166905f1b019ed4af9642617ea09fa2b8fc17

To see what happens, we should have this, as currently in https://pkgs.rstudio.com/rmarkdown/ not recently built
![image](https://user-images.githubusercontent.com/6791940/108738637-2259ed00-7534-11eb-9a2b-5c1028b1abe6.png)

but we have this in a recent build (https://pkgs.rstudio.com/bookdown/)
![image](https://user-images.githubusercontent.com/6791940/108738799-43224280-7534-11eb-813f-49c43f7e544f.png)

I confirm that changing the template file fix the issue: https://github.com/apreshill/quillt/pull/7

Should we do that ? Or is it a regression as it seems to be ? 
It seems a `footer` variable could be set in YAML for templates (quillt and tidytemplate) to overwrite the default one. Seems no more possible this way with the change in **pkgdown**

cc @apreshill

**Comment by cderv** [comment]
From @maelle comments on slack, this seems to be a whisker behavior not expected 
Copying as is the reprex:
``` r
data <- list(
  yaml = list(footer = "my footer yay"),
  footer = list(left = "left", right = "right")
)
whisker::whisker.render(
  '{{#yaml}}{{{footer}}}{{^footer}}BLOP.{{/footer}}{{/yaml}}',
  data
)
#> [1] "my footer yay"
data <- list(
  yaml = list(id = "pof"),
  footer = list(left = "left", right = "right")
)
whisker::whisker.render(
  '{{#yaml}}{{{footer}}}{{^footer}}BLOP.{{/footer}}{{/yaml}}',
  data
)
#> [1] "left,right"
```

<sup>Created on 2021-02-22 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>

**Comment by maelle** [comment]
I could rename the footer list something else like footer_data.
It'd be nice to be able to use "footer of yaml not other footer" in whisker, I'll look into this. 
Thanks!

**Comment by maelle** [comment]
From Mustache docs 

"The most basic tag type is the variable. A {{name}} tag in a basic template will try to find the name key in the current context. If there is no name key, the parent contexts will be checked recursively. "

(Taking notes as I read)

**Comment by maelle** [comment]
So it seems the solution is using "." in the template, and one can drop the "yaml" borders.

```
{{{yaml.footer}}}{{^yaml.footer}}{{#package}}{{name}}{{/package}} is built for <strong>R Markdown</strong>, an ecosystem of packages for creating computational documents in R. Learn more at <a href="https://rmarkdown.rstudio.com">rmarkdown.rstudio.com</a>.{{/yaml.footer}}
```


Cf reprexes

``` r
whisker::whisker.render(
  '{{{yaml.footer}}}{{^yaml.footer}}BLOP.{{/yaml.footer}}',
  data = list(
  footer = list(left = "left", right = "right")
  )
)
#> [1] "BLOP."

whisker::whisker.render(
  '{{{yaml.footer}}}{{^yaml.footer}}BLOP.{{/yaml.footer}}',
  data = list(
  yaml = list(id = "pof"),
  footer = list(left = "left", right = "right")
  )
)
#> [1] "BLOP."

whisker::whisker.render(
  '{{{yaml.footer}}}{{^yaml.footer}}BLOP.{{/yaml.footer}}',
  data = list(
  yaml = list(footer = "my-footer"),
  footer = list(left = "left", right = "right")
  )
)
#> [1] "my-footer"
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>

**Comment by maelle** [comment]
For completeness, the syntax could use a $ rather than a dot if pkgdown called `whisker::whisker.render()` with `strict=FALSE`

``` r
whisker::whisker.render(
  '{{{yaml$footer}}}{{^yaml$footer}}BLOP.{{/yaml$footer}}',
  data = list(
  yaml = list(footer = "my-footer"),
  footer = list(left = "left", right = "right")
  ),
  strict = FALSE
)
#> [1] "my-footer"

whisker::whisker.render(
  '{{{yaml.footer}}}{{^yaml.footer}}BLOP.{{/yaml.footer}}',
  data = list(
  yaml = list(footer = "my-footer"),
  footer = list(left = "left", right = "right")
  ),
  strict = FALSE
)
#> [1] "BLOP."
```

<sup>Created on 2021-02-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9001)</sup>

**Comment by maelle** [comment]
https://github.com/tidyverse/tidytemplate/pull/54

**Comment by maelle** [comment]
I can't find anything about "dot notation" (which can also be "dollar notation") in Mustache docs but I see it is implemented in both the JS and Ruby libraries.

**Comment by cderv** [comment]
It seems it is not documented in the Manual but directly in the specs (from comment https://github.com/mustache/mustache/issues/129#issuecomment-111313923): https://github.com/mustache/spec/blob/master/specs/interpolation.yml#L124-L180

**Comment by maelle** [comment]
Besides fixing the quillt/tidytemplate templates I wonder what actions need to be taken here.

* Opening an issue/PR in whisker to add a mention of the Mustache specs in the docs?
* Should pkgdown call `whisker::whisker.render()` with `strict=FALSE` i.e. do we want to use dots or dollars in the templates for the dot notation? https://github.com/r-lib/pkgdown/issues/1518#issuecomment-784102237
