### ISSUE TITLE
class=external-link overrides custom CSS classes

### ISSUE THREAD

**Issue by apreshill** [r-lib/pkgdown#1519]
Hi @maelle 👋 

I'm noticing (again with quillt 😭 ) that my custom CSS class is being overwritten. For example, I have a hover highlight for all `class="thumbnail"` images on this page:
https://pkgs.rstudio.com/distill/articles/examples.html

But using dev version, the `thumbnail` is lost, all I see is: `class="external-link"`
https://pkgs.rstudio.com/blogdown/articles/articles/examples.html

cc @cderv 

If it helps, here is my code to generate those examples: https://apreshill.github.io/quillt/reference/examples.html

Related to issue #1491 #881

**Comment by hadley** [comment]
@maelle we just need to paste the new class on, rather than overriding

**Comment by maelle** [comment]
@apreshill Thanks for the bug report and your patience!
@hadley I just needed to... use the corresponding helper function correctly. 

PR opened, with a test. :sweat_smile:
