### ISSUE TITLE
Add canonical urls to pkgdown sites

### ISSUE THREAD

**Issue by apreshill** [r-lib/pkgdown#1527]
See: https://moz.com/learn/seo/canonicalization

Example in the YAML for distill:
https://rstudio.github.io/distill/blog_workflow.html#canonical-urls

**Comment by hadley** [comment]
Why do we need this? i.e. what's creating the duplicate pages?

**Comment by apreshill** [comment]
This is a small n need, but our use case is pkgdown sites deployed on GitHub Pages where we'd like to transition to a new url. For pkgs.rstudio.com, sites need to originate in the same org in Netlify, so in some (small) repos, we'll have 2 urls leading to the same pkgdown site: the url we want, and the old GH pages url. There doesn't seem to be an "easy" way to do redirects from a GH pages url elsewhere, so it would be nice for search engines to know which url is the preferred one.

**Comment by hadley** [comment]
Hmmmm, since this is a very specific need, I'd prefer to try and solve it with the theme first — since you can now insert arbitrary data before/after the existing `<head>` components, maybe it's just a matter of figuring out what data is missing from whisker?

**Comment by apreshill** [comment]
Thanks! I'll give it a try.
