### ISSUE TITLE
Cannot center align table in pkgdown

### ISSUE THREAD

**Issue by a-beretta** [r-lib/pkgdown#1544]
Hello,

I'm developing a `pkgdown` site which will include some vignettes for internal use, but I'm facing a problem.

It seems not possible to center align tables generated using the `kable` package.

Here is a simple example:

```
df <- dt <- mtcars[1:5, 1:6]
df %>% 
  kbl(caption = "A table ...", align = "lcccccc") %>%
  kable_styling(full_width = F,
                font_size = 13)
```

If I build the vignette using knitr, the table is center aligned. However, if I run `pkgdown::build_site()`, the same table is always left aligned. I tried to add `fig.align = "center"` in the chunk's options and to add `position = "center"` to `kable_styling(),` without solving the issue.

Is there another trick to do this maybe?

Here is the YAML inside the vignette:

```
title: "TITLE"
author: "AUTHOR"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    toc: true
    number_sections: false
vignette: >
  %\VignetteIndexEntry{TITLE}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: bibliography.bib
link-citations: yes
```

**Comment by dmurdoch** [comment]
Have you tried following the instructions in https://pkgdown.r-lib.org/reference/build_articles.html ?  By default `pkgdown` uses its own output format, but that help page describes how to override its choices.

**Comment by maelle** [comment]
I've just had a quick look at this, and realized CSS wouldn't help, sorry for the wrong tip from earlier. Cf #1712

**Comment by hadley** [comment]
Unfortunately it looks like the approach that kable uses to align tables is currently incompatible with pkgdown, and making it work would require some fragile css/html hackery that I'd prefer not to implement unless there's a widespread demand for it.
