### ISSUE TITLE
Downlit not run on articles?

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1556]
e.g. https://googlesheets4.tidyverse.org/articles/articles/messages-and-errors.html

**Comment by maelle** [comment]
that vignette above is about unexported helpers, I see links in e.g. https://googlesheets4.tidyverse.org/articles/articles/write-sheets.html (but maybe I'm missing something else)

**Comment by hadley** [comment]
Oh I wasn't specific enough — in (e.g.) the output of the first chunk, we don't see any of the formatting applied by cli.

**Comment by maelle** [comment]
how should it look like?

![image](https://user-images.githubusercontent.com/8360597/110792246-6d356d80-8273-11eb-8906-eb406ef089f6.png)

**Comment by jennybc** [comment]
Here are screenshots 😱 that show what the interactive experience of this styling is. Note the colors of the cli symbols.

<img width="578" alt="Screen Shot 2021-03-11 at 10 23 04 AM" src="https://user-images.githubusercontent.com/599454/110835614-e1601900-8253-11eb-9d36-25f00757ad85.png">

See how the main text is in white (or default color) and Sheet names are blue and worksheet or range names are green? These distinctions, between main text and styled text and between text styled 2 different ways (`.file` vs `.field`), are completely lost by downlit.

<img width="669" alt="Screen Shot 2021-03-11 at 10 24 18 AM" src="https://user-images.githubusercontent.com/599454/110835758-14a2a800-8254-11eb-8ee0-10b045e48de9.png">

**Comment by jennybc** [comment]
It should the same as it does in, say, examples:

https://googlesheets4.tidyverse.org/reference/range_read.html

Why do the vignettes and article not get same styling as examples? Here's another article where the messages are complete "flat".

https://googlesheets4.tidyverse.org/articles/articles/write-sheets.html

**Comment by maelle** [comment]
So fixing this issue might warrant adding downlit stuff in a knitr hook?

**Comment by maelle** [comment]
It might even be easier to set hooks for warnings and messages.

**Comment by hadley** [comment]
We could do this using the same technique as hugodown (e.g. `hugdown:::knit_hooks`), but I think it would be quite a bit of work, and I'm not sure how it would interact with HTML widgets or other custom options that folks might be using. The current implementation is rather hacky because knitr is not quite flexible enough.

**Comment by hadley** [comment]
It will be resolved.

**Comment by krlmlr** [comment]
FWIW I'm using https://github.com/tidyverse/tibble/blob/master/R/fansi.R as a stop gap for now.

**Comment by hadley** [comment]
If this happens will need to build `README.Rmd` ourselves.

**Comment by hadley** [comment]
This turned out to be much less complex than I had feared — it was mostly just turning crayon/cli on in articles, and then handling the pain of `\033` in xml.
