### ISSUE TITLE
Don't make messages bold

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1557]
e.g. remove https://github.com/r-lib/pkgdown/blob/dd94073575aaee2fd480892d24dfe0be85f81a03/inst/assets/pkgdown.css#L308

**Comment by maelle** [comment]
@hadley in BS4 there's no rule on message. Should we fix the BS3 assets?

**Comment by hadley** [comment]
Already done in #1644?

**Comment by maelle** [comment]
right :woman_facepalming:
