### ISSUE TITLE
Small documentation improvement request for setting up Google Analytics

### ISSUE THREAD

**Issue by cbailiss** [r-lib/pkgdown#1560]
Thanks for a great package.

The current pkgdown guidance for setting up Google Analytics (GA) is based around Universal Analytics (UA) properties:
https://pkgdown.r-lib.org/reference/build_site.html?q=ganalytics#arguments

I was setting up tracking into a newer GA4 property and the current pkgdown guidance doesn't quite fit now (and the "tracking id" link on the above page links to an older GA UA docn page) - which all left me puzzled for a couple of minutes.

For UA the property ID is specified in the pkgdown yaml config file.
By contrast, GA4 has the concept of data streams, and the ID used in the pkgdown yaml file is the Measurement ID in the Web Stream for the property.  Example screenshot attached.

The data then happily flows through to GA.

Updating the guidance would help future users setting up tracking into GA4 properties.
There are several GA docn pages for setting up tracking for GA4 - so it would make sense to add a link to the following page or one of the pages underneath:
https://support.google.com/analytics/topic/9303319?hl=en&ref_topic=9143232

![image](https://user-images.githubusercontent.com/11745789/110779757-d610eb80-825b-11eb-95e3-95115d446e1a.png)

**Comment by hadley** [comment]
I think we'll unify the treatment of Google analytics with other platforms, so this will become part of #1547.
