### ISSUE TITLE
Add copy-paste button to all code blocks in reference pages?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1564]
E.g. YAML examples in https://pkgdown.r-lib.org/reference/build_site.html

Highlighting the blocks would be nice too, but the copy-paste button would be really useful.

**Comment by hadley** [comment]
Yeah, seems like a good idea.

**Comment by maelle** [comment]
I wonder whether the syntax highlighting should happen in roxygen2 or here. It'd be easier starting from the original Markdown block but one could retro-engineer it. :thinking:

**Comment by maelle** [comment]
Note to self, this is where pre-formatted tags are handled by pkgdown https://github.com/r-lib/pkgdown/blob/a068586d33ec11787013d25e3f12c0d5c0ae4b2a/R/rd-html.R#L436
