### ISSUE TITLE
autolinking and rdname

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1576]
https://github.com/r-lib/usethis/issues/1392

**Comment by maelle** [comment]
probably a tweak needed in package.R

**Comment by maelle** [comment]
If I replace the line below (in `package_topics()`)

https://github.com/r-lib/pkgdown/blob/95af5d4a327e90eb0450b8d7f672c6c4c94882a0/R/package.r#L136

with

```r
name = fs::path_ext_remove(file_out)
```

cf #1577

I get the correct link.

Now, I am not too sure I have not broken other things. 

In any case it seems the topic index is not exactly what it should be for downlit to produce the correct link.

If I look at the `pkg$topics` for usethis, "tidyverse.Rd" is the only Rd for which the name and filename are different. usethis uses `@name bla` to create bla.Rd, and in most cases the other things described with `@rdname bla` come after that and in the same file, whereas things described with `@rdname tidyverse` come in other files.

**Comment by maelle** [comment]
I am also wondering if it's an unexpected behavior of roxygen2?

```
\name{use_tidy_github_actions}
\alias{use_tidy_github_actions}
\alias{tidyverse}
```

wouldn't one expect tidyverse to be the name, after all?

**Comment by hadley** [comment]
It seems like something should be using `fileout` rather than `name`? Agreed, that this also looks like a weirdness in roxygen2.

**Comment by maelle** [comment]
that's what I implemented in https://github.com/r-lib/pkgdown/pull/1577 but I was wondering whether it'd break other things.

I had opened an issue in roxygen2 as well.

**Comment by dmurdoch** [comment]
I believe the `\name{}` field is displayed in the top left of the standard help page display.  It's also used to sort the entries in the PDF manual (which is why the `lattice` package has such weird names). I think this is a bad design, but failed to change it when I tried a few years ago.

I'm pretty sure your patch or mine would be safe here.

**Comment by dmurdoch** [comment]
One difference between yours and mine:  I think yours makes bigger changes, in that it changes the `name` field, whereas mine ignores it.
