### ISSUE TITLE
Renaming "Articles" in menu

### ISSUE THREAD

**Issue by chrarnold** [r-lib/pkgdown#1578]
What is the easiest way to renaming the "Articles" text in the main menu to say "Vignettes"? I am able to do so with explicitly defining the structure of the menu with navbar:, left: and then providing text and href. However, this then seems to lead to the articles" section in the config yaml to be ignored. I want to keep the nice submenu under "Articles" with the description etc, but I dont find a way currently to combine both.

Thanks!

**Comment by hadley** [comment]
We'll consider this as part of our general efforts to improve localisation, but I don't think it's a particularly good idea — most viewers of your site will be looking for "articles", and by changing the name you will break their ability to pattern match.
