### ISSUE TITLE
Can't install pkgdown 1.6.1 from CRAN on Ubuntu 20.04

### ISSUE THREAD

**Issue by pachamaltese** [r-lib/pkgdown#1592]
After installing the dependencies via APT, it still fails:
```
--------------------------- [ANTICONF] --------------------------------
Configuration failed to find the harfbuzz freetype2 fribidi library. Try installing:
 * deb: libharfbuzz-dev libfribidi-dev (Debian, Ubuntu, etc)
 * rpm: harfbuzz-devel fribidi-devel (Fedora, EPEL)
 * csw: libharfbuzz_dev libfribidi_dev (Solaris)
 * brew: harfbuzz fribidi (OSX)
If harfbuzz freetype2 fribidi is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a harfbuzz freetype2 fribidi.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
-------------------------- [ERROR MESSAGE] ---------------------------
<stdin>:1:10: fatal error: hb-ft.h: No such file or directory
compilation terminated.
```

**Comment by maelle** [comment]
Not a solution but note that these are the system dependencies of textshaping https://cran.r-project.org/web/packages/textshaping/index.html (that pkgdown indirectly depends on via ragg).

In the GHA workflow for pkgdown, pak is used to install system dependencies https://github.com/r-lib/pkgdown/blob/672b8fc2d10d98ed9bab242c2af56662e5983e9b/.github/workflows/R-CMD-check.yaml#L68 but then I have no idea whether it'd be any different than what you get via APT.

**Comment by hadley** [comment]
Did you try installing `libharfbuzz-dev` and  `libfribidi-dev` as the error suggested?  Otherwise, you can try the binaries from https://packagemanager.rstudio.com.
