### ISSUE TITLE
pkgdown build_sites ignores .Rbuildignore

### ISSUE THREAD

**Issue by wolski** [r-lib/pkgdown#1593]
pkgdown::build_sites attempts to build `.Rmd` files in the `vignettes` directory, listed in the `.Rbuildignore` file.

The package build ignores all files listed in `.Rbuildignore` (https://blog.r-hub.io/2020/05/20/rbuildignore/)

This is an excerpt of my `.Rbuildignore` which should exclude these two Rmd files. They are not built when running R CMD build. 
However, `build_sites` does include them.

```
vignettes/Grp2Analysis_MissingInOneCondition\.Rmd$
vignettes/Grp2Analysis\.Rmd$
```

And this is the error produced by `pkgdown::build_site()`:

```
Reading 'vignettes/Grp2Analysis.Rmd'
Writing 'articles/Grp2Analysis.html'
Reading 'vignettes/Grp2Analysis_MissingInOneCondition.Rmd'
-- RMarkdown error -------------------------------------------------------------
Quitting from lines 17-23 (Grp2Analysis_MissingInOneCondition.Rmd) 
Error in ggplot(NAinfo, aes(x = name, y = nrProteins)) : 
  object 'NAinfo' not found
--------------------------------------------------------------------------------
Error : Failed to render RMarkdown
In addition: Warning messages:
1: In has_crop_tools() : 
Tool(s) not installed or not in PATH: ghostcript
-> As a result, figure cropping will be disabled.
2: In has_crop_tools() : 
Tool(s) not installed or not in PATH: ghostcript
-> As a result, figure cropping will be disabled.
Error: callr subprocess failed: Failed to render RMarkdown
Type .Last.error.trace to see where the error occured
```

If anyone wants to reproduce the problem, the package I am trying to build the _sites_ for is available from here:
www.github.com/wolski/prolfqua

**Comment by dmurdoch** [comment]
`pkgdown` shouldn't ignore files based on `.Rbuildignore`:  some files (e.g. `README.Rmd`) need to included in the website but should be ignored in the package build.

I think there are currently two ways to ignore a file in the vignettes  directory:  start the name with an underscore, e.g. `_ignored.Rmd`, or add an `articles` section to your `_pkgdown.yml` file that lists only the files you want to include, e.g.

```
articles:
- title: These are the vignettes to include
  contents:
  - includeThis
  - andThis
```

This will lead to a warning about files you've skipped; maybe there should be a way to list files to ignore as well.

**Comment by hadley** [comment]
As @dmurdoch says, this is by design as you may want vignettes that appear on your website but are not included in the package (because, e.g., they generate large images).
