### ISSUE TITLE
Potential improvements to tutorials page

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [r-lib/pkgdown#1601]
The following would be nice improvements to the tutorials page of a pkgdown site:

- Nested lists, e.g. being able to collect a number of tutorials under a subheader that you can define in `_pkgdown.yml`.
- Thumbnails (screenshots) of each tutorial to be displayed so the page looks more like a gallery. Ideally, this would be automated (or semi-automated with an additional function one must run before building the page), but it could also be that the package author adds thumbnail images.

**Comment by maelle** [comment]
For this & possible cards for the article index, I'm wondering how it'd be combined with metadata (e.g. if you have an image as metadata for a tutorial, is it the thumbnail https://pkgdown.r-lib.org/articles/metadata.html#article-metadata-1 -- not even sure this works for tutorials).

**Comment by apreshill** [comment]
Wanted to link to this issue b/c some kind of bootstrap-based cards functions may be added to bslib (https://github.com/rstudio/bslib/issues/297). We used this for the quillt template, like: https://pkgs.rstudio.com/blogdown/articles/articles/examples.html

populated from a YAML file: https://github.com/rstudio/blogdown/blob/master/vignettes/articles/examples.yml

**Comment by hadley** [comment]
Superseded by #1899
