### ISSUE TITLE
Error in example reprex in CONTRIBUTING 

### ISSUE THREAD

**Issue by debruine** [r-lib/pkgdown#1625]
On the [CONTRIBUTING](https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md) page (also the [link when you open your first issue](https://github.com/r-lib/pkgdown/blob/3dd1a1ad7740977491241c89eee15d9b58e75866/.github/CONTRIBUTING.md)), the code for the reprex contains:

```
tmp <- file.path(tempdir(), "test")
usethis::create_package(tmp, open)
```

`open` is a function and causes the error
> Error: `fields` must be a list, not 'function'.

I'm not sure if open should be removed, set to TRUE, or set to FALSE (I'm having trouble with both T and F when trying to make a reprex).

**Comment by maelle** [comment]
Thanks for reporting the inconsistency!

In #1620 and #1471 the argument open was removed. As reprexes are run in non interactive sessions, the default would be it's not opened when running reprex. Now, when working on the code for the reprex, you probably will run the code line by line and not with reprex? 

Sometimes people go a step further and put a reprex repo on GitHub with the built website in there e.g. https://github.com/r-lib/pkgdown/issues/992#issuecomment-493613953, I wonder whether this should be documented in the contributing guide.
