### ISSUE TITLE
Q: Suggested workflow for NEWS.md rendering on package release?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/pkgdown#1628]
Hello,

I am using `development: mode: auto` for a dev and CRAN website.  The issue is that the call to https://crandb.r-pkg.org/googleAnalyticsR/all to determine the CRAN release date for the NEWS is not there until a few days after I've released, so now the [dev version has the date](https://code.markedmondson.me/googleAnalyticsR/dev/news/index.html) but the [CRAN version does not](https://code.markedmondson.me/googleAnalyticsR/news/index.html)

I tried rerunning the CD pipeline for the CRAN commit, but it didn't re-render the NEWs as its not changed.  

Should I add an explicit `build_news()` to the CI pipeline so it will build each push?  Will that avoid the caching?

The only option I see at the moment is to rollback the version, commit, then roll forward again which is a bit unoptimal.  Perhaps I should just wait until the CRAN update is live at the r-pkg.org link before incrementing to the dev version? 

I just wondered if you had tips on how you do it. :)

**Comment by hadley** [comment]
I'd say this is exactly #1248 :smile:
