### ISSUE TITLE
add external link icon by default for external links in the navbar?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1630]
both nav items and the dropdown.

**Comment by maelle** [comment]
example where I'd have expected it, somehow: http://openintrostat.github.io/openintro/index.html

**Comment by hadley** [comment]
Couldn't the user be responsible for that? (Do we have an easy way to have icon + text?)

**Comment by mine-cetinkaya-rundel** [comment]
I agree that it would be useful to indicate you're being sent elsewhere, and ideally, there would be a way to indicate "open in new tab" (or is there already?)

**Comment by maelle** [comment]
> Couldn't the user be responsible for that?

I liked the idea of having it by default.

>  (Do we have an easy way to have icon + text?)

It doesn't seem so, I'll check soon-ish.

> I agree that it would be useful to indicate you're being sent elsewhere, and ideally, there would be a way to indicate "open in new tab" (or is there already?)

I think I remember it's viewed as bad practice. :thinking:

**Comment by hadley** [comment]
Yeah, I expect that users know how to use the appropriate browser invocation to open in a different tab if they want that.

**Comment by maelle** [comment]
One can specify both text and icon, but in that case, the icon comes before the text which sounds logical when it's not an external link icon. 

![image](https://user-images.githubusercontent.com/8360597/115527178-1d45bf80-a291-11eb-9e03-57f124cb2d65.png)

https://github.com/r-lib/pkgdown/blob/46764c0dba9c847957120d0bd687862346db9e98/R/navbar.R#L265

**Comment by hadley** [comment]
I'm not sure this is worth it, given all the other work that we have to do.
