### ISSUE TITLE
should pkgdown BS4 templates use section tags instead of div with a section class?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1640]
https://developer.mozilla.org/en/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines

**Comment by maelle** [comment]
And I wonder whether the sidebar should be an aside.

**Comment by hadley** [comment]
Isn't the sidebar more typically a `<nav>`? I'm not sure if it makes sense to use `<aside>` for the homepage and `<nav>` for every other page.

**Comment by maelle** [comment]
Oh right!
