### ISSUE TITLE
Opt in to "spin" support for examples?

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1646]
So that, e.g.

```R
#' @examples
#' ## Heading 1
#' # This is some beautiful *code*
#' 1 + 2
```

becomes:

````
## Heading 1
This is some beautiful *code*

```r
1 + 2
#> [1] 3
```
````

Would need to provide some way to preview locally, which might make it more of a roxygen2 feature.

**Comment by maelle** [comment]
why would one use this rather than Rmd for other sections of the Rd?
