### ISSUE TITLE
Consider only using the Rd name in the search results

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1650]
instead of page title

**Comment by dmurdoch** [comment]
Be careful about that:  Rd files have a filename, a name in `\name{}`, and a title in `\title{}`.  R's help function doesn't search on the` \name` or filename, though users can see `\name` displayed in help pages.  This confuses some users, who remember seeing info in the "foo" page, but ?foo doesn't find it again.  That's also true for `\title`, but at least `??foo` would work if "foo" was part of the title.

For examples, see the lattice package, e.g. lattice::xyplot has the unhelpful `\name{B_00_xyplot}` .

**Comment by hadley** [comment]
Ok, I think that kills this idea (which was mine anyway); the other problem of course is that a Rd file might document multiple files, and the name will also be uninformative then.
