### ISSUE TITLE
use different quotes in docs for github shell

### ISSUE THREAD

**Issue by jessekps** [r-lib/pkgdown#1660]
In  the  [deploy site docs](https://pkgdown.r-lib.org/reference/deploy_site_github.html) you use single quotes

```
git commit --allow-empty -m 'Initial gh-pages commit'
```
On windows (in the shell opened by Rstudio) only double quotes work
```
git commit --allow-empty -m "Initial gh-pages commit"
```
I'm reasonably sure linux etc. will also accept double quotes but haven't tested

**Comment by hadley** [comment]
This is now superseded (https://pkgdown.r-lib.org/dev/reference/deploy_site_github.html) so the point is moot.
