### ISSUE TITLE
How to put content in tabs?

### ISSUE THREAD

**Issue by JamesHWade** [r-lib/pkgdown#1667]
I have attempted to create tabs following [this R Markdown Cookbook section](https://bookdown.org/yihui/rmarkdown-cookbook/html-tabs.html), but the tabs render as sequential entries in the rendered website.

My goal is to demonstrate the use of a package in both R and python. Any advice?

Here's what I would like to do:

```
## Results {.tabset}

### Tab 1

<example using R>

### Tab 2

<example using python>

```

**Comment by maelle** [comment]
I don't think it's possible out of the box at the moment. In rmarkdown, tabsets work thanks to a script (and CSS) added by rmarkdown.

* [style](https://github.com/rstudio/rmarkdown/blob/145046175c721af185aa6ba3ecc9262f12dc7369/inst/rmd/h/default.html#L290)
* [script](https://github.com/rstudio/rmarkdown/blob/145046175c721af185aa6ba3ecc9262f12dc7369/inst/rmd/h/navigation-1.1/tabsets.js)

In pkgdown, one would probably have to use [Bootstrap tabs](https://getbootstrap.com/docs/4.6/components/navs/#tabs), i.e. adding some more HTML tweaking to mimick the necessary HTML structure.

```html
<nav>
  <div class="nav nav-tabs" id="nav-tab" role="tablist">
    <a class="nav-link active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Home</a>
    <a class="nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</a>
    <a class="nav-link" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false">Contact</a>
  </div>
</nav>
<div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">...</div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">...</div>
  <div class="tab-pane fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">...</div>
</div>
```

**Comment by JamesHWade** [comment]
Thanks for the pointer, @maelle. I have been playing around with but not yet had success. I can get tabs to appear but no content. I'll keep playing with it.

**Comment by maelle** [comment]
Oh, what I meant is that maybe pkgdown should do the transformation to this html structure needed by Bootstrap, but maybe it's a too niche feature.
If you use this html structure above directly your vignettes probably only work as pkgdown articles not as vignettes (and its a bit cumbersome compared to the R Markdown recipe). 🤔

**Comment by maelle** [comment]
draft PR #1694
