### ISSUE TITLE
Floating hex logo on reference pages with long h1s

### ISSUE THREAD

**Issue by apreshill** [r-lib/pkgdown#1679]
This may be more of a me problem (I should shorten my h1s!), but I'm noticing that on pages where those are longer, the hex logo levitates above the border line:

https://bakeoff.netlify.app/reference/bakers.html

<img width="1193" alt="Screen Shot 2021-05-10 at 5 28 47 PM" src="https://user-images.githubusercontent.com/12160301/117740400-36b59980-b1b5-11eb-8e52-6b1e0532e8d5.png">

Compared to:

https://bakeoff.netlify.app/reference/baker_results.html

<img width="1193" alt="Screen Shot 2021-05-10 at 5 29 41 PM" src="https://user-images.githubusercontent.com/12160301/117740453-551b9500-b1b5-11eb-83cf-c60ff0daf8a0.png">

**Comment by maelle** [comment]
Ouch I need to revise the logic of this. Thank you!!

**Comment by hadley** [comment]
I'd rather keep the hex logo at a fixed place on each page, and just accept that if you have a wrapped heading, the line won't be perfectly aligned with the logo.
