### ISSUE TITLE
Changelog / News Contents (pkgdown dev version)

### ISSUE THREAD

**Issue by mcanouil** [r-lib/pkgdown#1680]
Hi,

Level one headings are not rendered in the table of contents produced with the dev version of pkgdown.
With usual level 1 heading for release: https://umr1283.github.io/umr1283/news/index.html
![image](https://user-images.githubusercontent.com/8896044/117809592-a16edf80-b25e-11eb-8bf1-90404d60a813.png)
With release version as level 2 headings: https://umr1283.github.io/umr1283/dev/news/index.html
![image](https://user-images.githubusercontent.com/8896044/117809650-b5b2dc80-b25e-11eb-9c7e-09b840a3b7a0.png)

Is that on purpose? if so, I am guessing this will break changelog page for many pkgdown website and will need to be reflected in {usethis} (e.g., use_version functions)

**Comment by mcanouil** [comment]
Efficient! ;)

**Comment by mcanouil** [comment]
> Something to keep in mind too if one day pkgdown keeps website of different releases.

Some kind of time machine for website documentation, is a great idea ^^

**Comment by maelle** [comment]
I'll stop working now, so I'll come back to fixing this later this week. In any case thanks a ton for helping find TWO bugs today!

Reg what you call time machine the relevant issue is #1373 :slightly_smiling_face:
