### ISSUE TITLE
Lost support for htmlwidgets

### ISSUE THREAD

**Issue by JakeVestal** [r-lib/pkgdown#1689]
In summary, [this example](https://urldefense.com/v3/__https://pkgdown.r-lib.org/dev/articles/test/rendering.html*widgets__;Iw!!OToaGQ!68j6WDmxURdxAxpUJwk2YYl29dpQAP8_QSaPPjbPj8R89rYpZO1gikdwsIYhurzmhHTf$) no longer works.

I think it’s incredibly powerful and very important for the pkgdown project to be able to include interactive graphs. That could really be huge for the package and I’d love it if we could get this functionality back!

Did it break somewhere along the line or was this feature purposefully taken out? And if the latter, what’s the updated for guidance on adding an interactive graph (plotless, ggplot2, dysgraphia, etc) to a GitHub Pages pkgdown site?

**Comment by dmurdoch** [comment]
You need to use the devel versions of `pkgdown` and `downlit` and a so far unmerged PR for htmlwidgets to get support in a `pkgdown` site.  Details are here:  https://dmurdoch.github.io/rgl/articles/pkgdown.html .  That article is about `rgl`, but the same problems happen with any other `htmlwidgets` package.

I don't know when it worked, I haven't been using it for that long.  I'd guess you were using `knitr` to produce documents (it supports `htmlwidgets`), not the `pkgdown` special document format.

**Comment by JakeVestal** [comment]
@dmurdoch: Thanks for the help. I spun up this site to aid in my understanding of this whole topic: https://jakevestal.github.io/live.graphs.with.pkgdown/

To my mind, it looks like the **secret sauce** needed to support live graphs in GitHub Pages is: 
1) Installing the right versions of _downlit_, _pkgdown_, _rgl_, and _htmlwidgets@rglpatch_
2) Adding the right files to /inst: JavaScript resources, data, templates, etc
3) Installing the required software in the pkgdown.yaml Git workflow

If the goal is to regain a pkgdown page's ability to handle interactive graphics in GitHub, then it seems like `usethis::use_pkgdown_github_pages()` should be able to handle those three tasks on its own, pulling the right files and adding the code blocks as need be.

Glad to help, of course.

**Comment by dmurdoch** [comment]
It's a little simpler than your instructions suggest:

1.  `rgl` isn't needed unless you want `rgl` graphics on your page.
2. You shouldn't need to add any files to `inst`:  packages that work with `htmlwidgets` will already do that.
3. You don't really need to use the Github workflow, you can build and deploy your site locally using `pkgdown::deploy_to_branch()`.

I have to say I like your LICENSE agreement (https://github.com/JakeVestal/live.graphs.with.pkgdown/blob/master/LICENSE.md); I hope everyone using the MIT license modifies it in the same way.

**Comment by dmurdoch** [comment]
Actually I was wrong:  This commit:  

commit 55fde80bf03a1e6ef901045b77af9f13fe19c5f5
Author: Hadley Wickham <h.wickham@gmail.com>
Date:   Fri May 14 07:22:39 2021 -0500

    Move <pre> wrappers into R code (#1673)
    
    Part of a bigger push towards consistency across roxygen2/downlit/pkgdown.

does appear to have broken htmlwidgets and rgl support.  I'll see if I can track down what broke.
