### ISSUE TITLE
Make border-color depend on body-color and body-bg instead of being gray by default?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1697]
Cc @apreshill

**Comment by maelle** [comment]
This probably needs a pkgdown-specific variable. It's `"border-color" = "mix($body-color, $body-bg, 20%)"` in the PR.

**Comment by maelle** [comment]
Actually that's something bslib does with fg and bg.

**Comment by maelle** [comment]
I.e. I mean

``` r
red_theme <- bslib::bs_theme(version = 4, fg = "red", bg = "yellow")
vanilla_theme <- bslib::bs_theme(version = 4)

bslib::bs_get_variables(red_theme, c("dark", "light", "gray-500", "border-color"))
#>         dark        light     gray-500 border-color 
#>    "#FF3300"    "#FFE600"    "#FF8000"    "#FFB200"
bslib::bs_get_variables(vanilla_theme, c("dark", "light", "gray-500", "border-color"))
#>         dark        light     gray-500 border-color 
#>    "#343a40"    "#f8f9fa"    "#adb5bd"    "#dee2e6"
```

<sup>Created on 2021-07-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maelle** [comment]
And `$body-color` itself defaults to `$gray-900`. Not sure what `$fg` itself is used for.

**Comment by hadley** [comment]
I think we can leave `border-color` this with the bs defaults (i.e. `gray-300`)
