### ISSUE TITLE
Dropdown focus color background color

### ISSUE THREAD

**Issue by apreshill** [r-lib/pkgdown#1698]
See: https://github.com/r-lib/pkgdown/issues/1678#issuecomment-845829915

It looks like the dropdown active background color pulls from `primary` currently:

```
.dropdown-item.active, .dropdown-menu > li > a.active, .dropdown-item:active, .dropdown-menu > li > a:active {
	color: #FCFBF9;
	text-decoration: none;
	background-color: #272B30; # this is my primary var
}
```

Example:
https://romantic-chandrasekhar-05bd8d.netlify.app/articles/examples.html

https://user-images.githubusercontent.com/12160301/119207238-633da100-ba52-11eb-9e9e-bd0ab36137dc.mov

> What do you think about having the dropdown active background color follow secondary, if set? (then it would match the hover background color) (dropdown variables here: https://github.com/rstudio/bslib/blob/e0503c6/inst/lib/bs/scss/_variables.scss#L781)

**Comment by maelle** [comment]
Thanks for the super precise report!

It works if I set `dropdown-link-active-bg` in the configuration, which is weird as its default value should be `$component-active-bg` and this is set to secondary. :thinking:

**Comment by maelle** [comment]
I might be missing something in bslib docs, I was hoping re-setting `component-active-bg` would reset the variables that depended on it, but maybe that's actually good behavior. :thinking: 

``` r
theme <- bslib::bs_theme()
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#007bff"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#007bff"
theme <- bslib::bs_add_variables(
      theme,
      "component-active-bg" = "$secondary",
      .where = "declarations"
    )
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#6c757d"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#007bff"
```

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by maelle** [comment]
For ref

![image](https://user-images.githubusercontent.com/8360597/119364770-87e28480-bcaf-11eb-9c3c-8a1e0a0a94b6.png)

**Comment by maelle** [comment]
@cpsievert sorry for pinging you here, I have a bslib question that I hope wasn't covered in the docs this time: does it seem clunky to you to

* set `component-active-bg` to `$secondary` as below

```r
  # map secondary to component-active-bg
  # unless a value was set by the user
  if (is.null(pkg$meta[["template"]]$bslib$`component-active-bg`)) {
    bs_theme <- bslib::bs_add_variables(
      bs_theme,
      "component-active-bg" = "$secondary",
      .where = "declarations"
    )
  }
```

* then set `dropdown-link-active-bg` to `$component-active-bg` as below

```r
  # dropdown-link-active-bg
  if (is.null(pkg$meta[["template"]]$bslib$`dropdown-link-active-bg`)) {
    bs_theme <- bslib::bs_add_variables(
      bs_theme,
      "dropdown-link-active-bg" = "$component-active-bg",
      .where = "declarations"
    )
  }

```

`dropdown-link-active-bg` is already supposed to inherit from `$component-active-bg` but it isn't reset after I change `$component-active-bg`.

**Comment by maelle** [comment]
Note that `dropdown-link-active-bg` _is_ reset if `component-active-bg` is reset later

``` r
theme <- bslib::bs_theme()
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#007bff"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#007bff"
theme <- bslib::bs_add_variables(
      theme,
      "component-active-bg" = "pink"
    )
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>              "pink"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>                  "pink"
```

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by maelle** [comment]
To ensure inheritance, I should re-set `component-active-bg` *twice*

``` r
theme <- bslib::bs_theme()
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#007bff"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#007bff"
theme <- bslib::bs_add_variables(
      theme,
      "component-active-bg" = "$secondary",
      .where = "declarations"
    )
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#6c757d"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#007bff"

theme <- bslib::bs_add_variables(
      theme,
      "component-active-bg" = as.character(
        bslib::bs_get_variables(theme, "component-active-bg")
        )
    )
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#6c757d"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#6c757d"
```

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

**Comment by maelle** [comment]
Which means that the easiest solution might be

``` r
theme <- bslib::bs_theme()
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#007bff"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#007bff"

theme <- bslib::bs_add_variables(
      theme,
      "component-active-bg" = as.character(
        bslib::bs_get_variables(theme, "secondary")
        )
    )
bslib::bs_get_variables(theme, "component-active-bg")
#> component-active-bg 
#>           "#6c757d"
bslib::bs_get_variables(theme, "dropdown-link-active-bg")
#> dropdown-link-active-bg 
#>               "#6c757d"
```

<sup>Created on 2021-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

I'll stop experimenting here.

**Comment by hadley** [comment]
Primary isn't used in many places, so I'm going to consistently use it for hover on sidebar + navbar.
