### ISSUE TITLE
Using ggplot to print a graphic inside a function doesn't seem to work when using a return() in the function

### ISSUE THREAD

**Issue by p-carter** [r-lib/pkgdown#1709]
I'm using pkgdown 1.6.1.

When using ggplot2 inside a function, in an .Rmd file, if I include a return at the end of the function, a graph that should appear in the generated .html does not appear when I use pkgdown::build_site(). If I remove the return, the graph appears in the html.

Here is a simple example Rmd file:

---
title: "test"
output: rmarkdown::html_vignette
vignette: > 
  %\VignetteIndexEntry{test}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
                                                                                                                                                                                       
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
printFn <- function(){
library(ggplot2)
data("midwest", package = "ggplot2")
ggplot(midwest, aes(x=area, y=poptotal))

#return() # if I uncomment this, graph output in the html is removed
}

printFn()

**Comment by hadley** [comment]
The explicit return means that you return NULL instead of the plot. This is unrelated to pkgdown; you’ll see the same problem if you run your function interactively.

**Comment by dmurdoch** [comment]
That's just how ggplot2 graphics (and other grid graphics) works:  the graph is produced when the result of the ggplot call is printed.  You never printed your graph.

**Comment by p-carter** [comment]
Is there a way that I can print using ggplot inside a function in the way that I described so that it appears in the generated html, and return something in the same function?

Thanks.

**Comment by p-carter** [comment]
Thank you.
