### ISSUE TITLE
More control on missing topic errors/warnings

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdown#1716]
I like to have some topics in articles, and also in the manual. In the proper manual, not as vignettes, as vignettes are less accessible, especially from the console. `@keywords internal` is also not great, because I do want them in the index.

So I propose we have an entry in the config file, where you can just list topics that are ignored on purpose.

**Comment by StevenMMortimer** [comment]
Historically, `@keywords internal` has been the only suggested solution for this problem (see #1132 and #1378). Would love to see that change.

**Comment by hadley** [comment]
Maybe we could just have a special section name that's not displayed on the reference page.

**Comment by gaborcsardi** [comment]
Yeah, that would work great, I think.

**Comment by hadley** [comment]
Two options:

* Drop any section with title "Internal" (like keywords)
* Drop any section with title starting with `_`  (like vignettes)

Any preference?

**Comment by gaborcsardi** [comment]
Very slightly prefer the first.
