### ISSUE TITLE
Extra space in vignette code chunks

### ISSUE THREAD

**Issue by ayushnoori** [r-lib/pkgdown#1718]
Hi, thanks for developing such a fantastic package! I have encountered one issue: I see extra space added at the beginning of each code chunk in my vignette. For example:

![image](https://user-images.githubusercontent.com/43010710/120900650-d0246f80-c5ea-11eb-8335-f8203c7c96ae.png)

Please see the full vignette [here](https://www.ayushnoori.com/brainstorm/articles/brainstorm.html) which features several additional example. Inspecting the HTML suggests that the issue may be with the `<code class="sourceCode R"></code>` element. I would appreciate any guidance on how to fix. Thanks again!

**Comment by jayhesselberth** [comment]
Remove the blank line at the beginning of all of your code chunks.

**Comment by ayushnoori** [comment]
Thanks for the advice, @jayhesselberth. I don't see this behavior when including a blank line in the beginning of code chunks outside of `pkgdown` (please see example below). Is this to be expected?

![image](https://user-images.githubusercontent.com/43010710/121285888-edc83200-c893-11eb-910c-4fa32740ad06.png)

The above code chunk generates the following, with no extra space:

![image](https://user-images.githubusercontent.com/43010710/121285949-059fb600-c894-11eb-9324-e275469341db.png)

**Comment by ayushnoori** [comment]
@jayhesselberth, following up with this quick question. Thanks again!

**Comment by dmurdoch** [comment]
The blank lines are controlled by the `strip.white` chunk option in `knitr`.  Have you tried setting it explicitly to `TRUE`?  

I think `TRUE` is the default, but maybe you've changed that somehow.  In my own vignettes, I'm not seeing this problem.  But I'm using the devel version of `pkgdown`, not 1.6.1 as you used in your example.

**Comment by ayushnoori** [comment]
Thanks for the advice, @dmurdoch. I figured out the issue - the `pkgdown` vignette template included the following code chunk at the beginning by default:
```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
After removing this code chunk or commenting out `collapse = TRUE`, the whitespace is stripped as expected. Interestingly, `collapse = TRUE` did not actually make the code chunks collapsible, perhaps due to the Bootswatch theme I am using? Regardless, thanks for pointing me in the right direction!

**Comment by dmurdoch** [comment]
The `collapse=TRUE` option doesn't make code chunks collapsible, it collapses source and output into the same block.  But it looks like a `knitr` bug that it also affects white space stripping.

**Comment by dmurdoch** [comment]
It's definitely a `knitr` bug, but has been fixed in the devel version, which you can get using `remotes::install_github("yihui/knitr")`.

**Comment by ayushnoori** [comment]
I see. Will do!
