### ISSUE TITLE
Add manual checks of test reference pages & articles to a release_bullets() function?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1721]

**Comment by maelle** [comment]
This was for pkgdown development, adding an internal `release_bullets()` function with the item "Check the test reference pages and articles". This way the usethis-created release TODO list would include that.

It was in case it was really important to check those before releases but I don't know? 

(How could I think that issue title was clear?! :sweat_smile: )

**Comment by hadley** [comment]
Can you be more explicit about what we'd check?

**Comment by maelle** [comment]
Nothing more specific "nothing amiss". What are the test reference topics and test articles for, in general?

**Comment by hadley** [comment]
I think we should probably slowly accumulate a list of "manual tests" (i.e. things we've been unable to automate) and add a reminder to check those in the release process.

**Comment by hadley** [comment]
I'm moving more of the vignettes to automated tests so I don't think we need to do this now, but we certainly should if we introduce more manual tests.
