### ISSUE TITLE
Built site with development: mode: unreleased, but CRAN download link remains in sidebar

### ISSUE THREAD

**Issue by dcnorris** [r-lib/pkgdown#1723]
Newer versions of package [precautionary](https://dcnorris.github.io/precautionary/index.html) use compiled [Rust](https://www.rust-lang.org) code that is apparently too sexy for CRAN. So I would rather that my `pkgdown` site not link to the old version on CRAN.

The `pkgdown::build_site` [documentation](https://pkgdown.r-lib.org/reference/build_site.html) states

>        • *unreleased* (‘mode: unreleased’). Site is written to docs/.
>          Version in navbar gets the "danger" class, and a message
>          indicating the package is not yet on CRAN.

and indeed this does occur on mouseover of the orangey-red package version. Logically, the "Download from CRAN at ..." link at top of sidebar should also be omitted. (Or is there a further config step I should implement to suppress that link?)

---
EDIT: Here's the [_pkgdown.yml](https://github.com/dcnorris/precautionary/blob/fef5894a5a4eedb0b4650392082fe87e4692ca9a/pkgdown/_pkgdown.yml) file I used.

**Comment by maelle** [comment]
The "unreleased" mode really only used for the version badge.

A possible workaround to prevent the link to CRAN is to use the option `pkgdown.internet` cf https://github.com/r-lib/pkgdown/issues/1451#issuecomment-825715981

Locally if I run

```r
options("pkgdown.internet" = FALSE)
build_home()
```

I see no CRAN link.

**Comment by dcnorris** [comment]
Thanks, @maelle. I'd rather keep the semantics of my build as declarative as possible, and `pkgdown.internet=FALSE` seems to have motivations (and consequences?) that go beyond that link. I can probably just use a Makefile to patch `docs/index.html` after each `build_site()`.

**Comment by maelle** [comment]
Right, tweaking HTML is always a solution, pkgdown itself tweaks HTML a lot. :-)
