### ISSUE TITLE
Implementing YML configs through override

### ISSUE THREAD

**Issue by laresbernardo** [r-lib/pkgdown#1728]
Hi! I've been using Github Actions to build [my `lares` package site](https://laresbernardo.github.io/lares/) with `pkgdown` for a while now. I've tried to implement Google Analytics into my site without using a `_pkgdown.yml` file [by using the `override` parameter when running `pkgdown::deploy_to_branch`](https://github.com/laresbernardo/lares/blob/master/.github/workflows/pkgdown.yaml#L58). Also tried adding the template's `bootswatch` argument within the list on `override` but no effect. 
Am I doing something wrong here? Reading the documentation this should have worked just fine.
Thanks fo your suppot!

**Comment by maelle** [comment]
A wild guess: can you try using the argument `clean=TRUE`?

**Comment by laresbernardo** [comment]
Hi @maelle thanks for the suggestion! I tried using `clean=TRUE` and still it wasn't included on the [site](https://laresbernardo.github.io/lares/index.html)'s [header](view-source:https://laresbernardo.github.io/lares/index.html).
Any further ideas on why is it not working? Any suggestion is more than welcome. Thanks 🙏

**Comment by maelle** [comment]
It'll need further exploration. (here in this repo :eyes: )

In the meantime as a workaround it'd make sense to add a configuration file. :wink: By the way the URL of your website should be in the configuration file, in DESCRIPTION and in the GitHub repository description.

**Comment by maelle** [comment]
I think the bug comes from

https://github.com/r-lib/pkgdown/blob/b94fe3407a0b40a968425a64cdf7ae0c6705b1b1/R/deploy-site.R#L132

There's an override parameter. Later when the website is built, the other override isn't used at all.

**Comment by maelle** [comment]
I wonder whether it'd be easier to handle in the code if the override parameter was an explicit parameter of `deploy_to_branch()` this way it'd be combined with `list(destination = dest_dir)` with `pkgdown:::modify_list()`. :thinking: End of my exploration, sorry to not help more for now!

**Comment by laresbernardo** [comment]
You're a great code detective @maelle I guess your parameter proposal would be great to have! What would be the next step?

On the other hand, I'm not quite sure on what you meant by having the website URL on 1. configuration file (the YML file?), 2. DESCRIPTION (`URL` parameter?), 3. Github repository description (someplace particular? I do have the "documentation" button that leads you to the website). Is this a requirement for anything to work or simply good practice?

Thanks for taking the time!!

**Comment by hadley** [comment]
The intent of the override parameter is for the occasional interactive override; it’s not a replacement for providing a yaml file. So while we can fix this bug, your use of override is “off label”.

**Comment by hadley** [comment]
Closing since we're going to revisit how this function works in #1756
