### ISSUE TITLE
Bug in topic linking?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1733]
Via https://github.com/tidyverse/ggplot2/issues/4540 @yutannihilation

**Comment by maelle** [comment]
This is a case where using "file_in" is wrong as there are two .R files feeding the same .Rd.

**Comment by maelle** [comment]
@yutannihilation actually can you try building the website with the latest pkgdown version? (from this repo) it seems to be fixed?

**Comment by maelle** [comment]
i.e. it'd be similar to #1576

**Comment by yutannihilation** [comment]
Thanks, let me try.

**Comment by yutannihilation** [comment]
I confirmed the topics are linked correctly with the dev version of pkgdown. Thank you for the advice!

https://yutannihilation.github.io/ggplot2/dev/reference/theme.html

**Comment by maelle** [comment]
Awesome, great to know it works for ggplot2 too!
