### ISSUE TITLE
Indicate dependence on development versions 

### ISSUE THREAD

**Issue by gustavdelius** [r-lib/pkgdown#1739]
The current development version of pkgdown requires downlit version 0.2.1.9000. It would be helpful if such dependencies could be indicated in the DESCRIPTION file. That would have saved me some time figuring this out myself.

**Comment by dmurdoch** [comment]
Don't these lines do that?

    Remotes: 
        r-lib/downlit

**Comment by gustavdelius** [comment]
Hi @dmurdoch, that alone does not check which version is installed. I think what is needed is a
```
Depends:
    downlit (>= 0.2.1.9000)
```

**Comment by dmurdoch** [comment]
It certainly shouldn't use `Depends` (`Imports` is appropriate), but some sort of version requirement does make sense.

**Comment by hadley** [comment]
We generally assume that folks installing from GitHub use one of the tools that recognise the remotes field so don’t otherwise record this info (unless it’s important for some specific reason).

**Comment by gustavdelius** [comment]
You are right. Had I used `devtools::install()` instead of RStudio's "Install and Reload" button to install my clone of pkgdown then I would have been prompted to upgrade the downlit package. I had not actually realised that RStudio's button does not use devtools. So I have learned my lesson.
