### ISSUE TITLE
match number in `has_concept` and `lacks_concepts`

### ISSUE THREAD

**Issue by mikeroswell** [r-lib/pkgdown#1745]
Minor! if you have a moment, I think it would be great to add an alias to either `has_concept` or `lacks_concepts` or both so that when users intuitively do number agreement, their YAML header just works. I stumbled, with a header kind of like this:

```
reference:
- title: Estimation
- contents:
  - lacks_concept(c("Visualization"))
- title: Visualization
- contents:
  - has_concept("Visualization")
```

Thanks!

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, it's a bit too specialised to make it on to our development roadmap. I'd be happy to review a PR, but we won't work on it ourselves.
