### ISSUE TITLE
Dev version not rendering correctly with GitHub Actions

### ISSUE THREAD

**Issue by mfherman** [r-lib/pkgdown#1748]
I'm trying to set up GitHub Actions to build a pkgdown site for my package. I used [this template](https://github.com/r-lib/actions/blob/master/examples/pkgdown.yaml) and everything was working well. But, then I wanted to try to use the dev version of pkgdown because I love the new template. I am able to get actions to build the site with the dev version of pkgdown, but it seems like the references to the `deps/` directory which contains bootstrap, jquery, etc. are incorrect and so the site is displayed with pretty much no formatting (see [here](https://csgjcresearch.github.io/csgjcr/)).

When I examine the HTML generated by pkgdown, the links to the dependencies  begin `private/deps/...`, but there is no `private/` directory on the branch with the pkgdown site.

https://github.com/CSGJCResearch/csgjcr/blob/a7d30d2ab548d5f2273237e21932fa87ecb027a9/index.html#L11-L14

Additionally, when I build the site locally (i.e not using GH actions), it builds correctly and contains links to the correct folder with the dependencies.

I'm very much a GH actions beginner, so I'm not sure if it's something in the configuration there or a pkgdown issue.

I posted this question on [RStudio Community](https://community.rstudio.com/t/dev-version-of-pkgdown-not-rendering-correctly-with-github-actions/112933), but haven't received any responses over there.

**Comment by maelle** [comment]
:wave: @mfherman! 

I can't explore right now but I know of another package whose website seemed to build correctly on GHA, here's the workflow: https://github.com/OpenIntroStat/openintro/blob/master/.github/workflows/pkgdown.yaml :thinking:

**Comment by mfherman** [comment]
It's working now 🎉! Honestly not sure where the issue was in the original workflow I was using to build and deploy the site, but using the one you linked to worked with my repo. Thanks @maelle!
