### ISSUE TITLE
Sidebar missing for articles pages

### ISSUE THREAD

**Issue by p-carter** [r-lib/pkgdown#1750]
Hi,

when I build my website using pkgdown, there is no sidebar created. I get a sidebar elsewhere on the generated website.

I think I should get one, I can see sidebars on articles sections on several well known pkgdown generated websites.

I tried stripping down the pkgdown configuration for the website to something very minimal, but it's still missing.

I also tried reinstalling devtools and roxygen2.

I'm not sure how to make this reproducible as I'm unsure where the problem is. 

I was just wondering if there's something obvious I'm not doing. I've tried looking for info on this but I can't find anything.

Thanks in advance.

**Comment by maelle** [comment]
:wave: @p-carter! What pkgdown version are you using and is your package source public? Also, by sidebar you mean the table of contents?

**Comment by hadley** [comment]
Closing, since no response.
