### ISSUE TITLE
bad graphics state error from example

### ISSUE THREAD

**Issue by GeoBosh** [r-lib/pkgdown#1751]
After adding the last example in `https://github.com/GeoBosh/sarima/blob/master/man/tsdiag.Sarima.Rd` I get error from pkgdown:
```
pkgdown::build_site()
-- Installing package into temporary library -----------------------------------
== Building pkgdown site =======================================================
...
...
Reading 'man/tsdiag.Sarima.Rd'
Error : Failed to parse Rd in tsdiag.Sarima.Rd
ℹ invalid graphics state
Error: callr subprocess failed: Failed to parse Rd in tsdiag.Sarima.Rd
ℹ invalid graphics state
```
There are no problems with `R CMD check` and interactively. This can be seen from GHA's at https://github.com/GeoBosh/sarima/actions. The only change in commit `ba0784a` (last commit at the time of writing this) was to uncomment the last example in `man/tsdiag.Sarima.Rd`. The previous commit was fine. The check and covr actions in commit `ba0784a`  are also fine but pkgdown throws the above error. The rendered page at `https://geobosh.github.io/sarima/reference/tsdiag.Sarima.html` is from the previous commit.

The relevant function, `tsdiag.Sarima` is in `R/fitTools.R`. it changes the graphics state with `layout()`. In the offending example the call to `layout()` uses argument `heights`.

**Comment by hadley** [comment]
Can you try clearing your GitHub cache please?

**Comment by GeoBosh** [comment]
If this is about the GitHub actions cache, from what I see online it would take some time to get my head around it.

**Comment by hadley** [comment]
To "clear" the cache change 1 to 2 on these two lines: https://github.com/GeoBosh/sarima/blob/master/.github/workflows/pkgdown.yaml#L32-L33

And for my reference, here's the full traceback:

```
ℹ invalid graphics state
Backtrace:
     █
  1. └─pkgdown::deploy_to_branch(new_process = FALSE)
  2.   └─pkgdown::build_site(...)
  3.     └─pkgdown:::build_site_local(...)
  4.       └─pkgdown::build_reference(...)
  5.         └─purrr::map(...)
  6.           └─pkgdown:::.f(.x[[i]], ...)
  7.             ├─base::withCallingHandlers(...)
  8.             └─pkgdown:::data_reference_topic(...)
  9.               └─pkgdown:::run_examples(...)
 10.                 └─pkgdown:::highlight_examples(code, topic, env = env)
 11.                   └─downlit::evaluate_and_highlight(...)
 12.                     ├─downlit:::replay_html(...)
 13.                     └─downlit:::replay_html.list(...)
 14.                       ├─downlit:::replay_html(parts[[i]], ...)
 15.                       └─downlit:::replay_html.recordedplot(parts[[i]], ...)
 16.                         └─pkgdown:::fig_save(x, fig_id())
 17.                           ├─base::do.call(fig_save, c(list(plot, name), context_get("figures")))
 18.                           └─(function (plot, name, dev = "ragg::agg_png", dpi = 96L, dev.args = list(), ...
 19.                             └─pkgdown:::with_device(dev, c(args, dev.args), plot)
 20.                               ├─base::print(plot)
 21.                               └─grDevices:::print.recordedplot(plot)
 22.                                 └─grDevices::replayPlot(x)
 ```

**Comment by GeoBosh** [comment]
Thanks, I made the suggested changes to the pkgdown workflow, seemingly the result didn't change.

 Indeed, it is just base R graphics, using `layout()` to split the graphics window plus `on.exit()` to restore the graphics state, When argument `layout` is supplied, as in the reprex above, the call is ` do.call("layout", layout)`.

**Comment by hadley** [comment]
Hmmmm, can you please try using a different graphics device to eliminate the chance that this might be a ragg bug? You should be able to do so by adding this to your `_pkgdown.yml`:

```R
figures:
   dev: grDevices::png
```

**Comment by hadley** [comment]
Actually I can reproduce it outside of pkgdown:

``` r
library(sarima)
#> Loading required package: stats4
ap.arima <- arima(log(AirPassengers), order = c(0,1,1), seasonal = c(0,1,1))
tsdiag(ap.arima, 
  plot = c(1:3), 
  layout = list(matrix(1:3, nrow = 3), heights = c(1,2,2))
)

x <- recordPlot()

path <- tempfile(fileext = ".png")
png(path, width = 900, height = 700, res = 300)
replayPlot(x)
#> Error in value[[3L]](cond): invalid graphics state
dev.off()
#> quartz_off_screen 
#>                 2
```

<sup>Created on 2021-10-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Hopefully this is enough for you to debug at your end.

**Comment by GeoBosh** [comment]
Thanks for looking into this and the reprex. I wouldn't have got close to doing something like this.
