### ISSUE TITLE
Dead links in pkgdown documentation

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#1752]
Links to `error_cnd()`, `cnd()`, `warning_cnd()` and `message_cnd()` lead to https://rlang.r-lib.org/reference/error_cnd.html, which is a 404. The correct link is https://rlang.r-lib.org/reference/cnd.html.

You can see this on https://rlang.r-lib.org/reference/cnd_signal.html.

However, it seems to work fine using `?rlang::cnd_signal` and then clicking on the link.

Additionally, these functions seem to be missing from pkgdown reference index.

Feel free to move this issue to another repo is this is caused by a bug in another package (possibly pkgdown or downlit).

**Comment by hadley** [comment]
@lionel- can you please try updating the pkgdown workflow?

**Comment by lionel-** [comment]
Done in https://github.com/r-lib/rlang/commit/46a5a7df but this doesn't seem to have resolved the issue.

**Comment by hadley** [comment]
Bigger examples also look ok:

``` r
cat(downlit::highlight(r"(
  rlang::warning_cnd()
)"))
#> 
#>   <span class='nf'>rlang</span><span class='nf'>::</span><span class='nf'><a href='https://rlang.r-lib.org/reference/cnd.html'>warning_cnd</a></span><span class='o'>(</span><span class='o'>)</span>
cat(downlit::highlight(r"(
  library(rlang)
  warning_cnd()
)"))
#> 
#>   <span class='kr'><a href='https://rdrr.io/r/base/library.html'>library</a></span><span class='o'>(</span><span class='nv'><a href='https://rlang.r-lib.org'>rlang</a></span><span class='o'>)</span>
#>   <span class='nf'><a href='https://rlang.r-lib.org/reference/cnd.html'>warning_cnd</a></span><span class='o'>(</span><span class='o'>)</span>
```

<sup>Created on 2021-09-28 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by hadley** [comment]
But I can reproduce it by running this code in rlang:

```R
pkgdown::init_site()
pkgdown::build_reference(topics = "cnd_signal")
```

**Comment by hadley** [comment]
The problem is in the topic index that pkgdown generates:

```R
pkg <- pkgdown::as_pkgdown(".")
subset(pkg$topics, name == "error_cnd")
#'  A tibble: 1 × 11
#'   name      file_in file_out alias        funs         title                     rd           source keywords concepts internal
#'   <chr>     <chr>   <chr>    <named list> <named list> <chr>                     <named list> <name> <list>   <list>   <lgl>   
#' 1 error_cnd cnd.Rd  cnd.html <chr [4]>    <chr [4]>    Create a condition object <Rd>         <chr … <chr [1… <chr [0… TRUE    
```

**Comment by hadley** [comment]
Ooooh the problem is that it's generating `file_out`  from the file name, not the `\name{}`.

**Comment by maelle** [comment]
I vaguely remember using the name created other problems.

**Comment by maelle** [comment]
ah no it was something else https://github.com/r-lib/pkgdown/commit/93303d30bb0d467ba706f5490ad41e5105841d0c

**Comment by hadley** [comment]
But `build_reference_topic()` uses `topic$file_out`, so maybe the question is "why isn't `cnd.html` being written"? But that would imply an inconsistency with `downlit::href_topic()` which uses the package index.  Regardless, the root cause seems to be confusion whether the file name of the topic should match the file name or the `\name{}` of the Rd.

**Comment by hadley** [comment]
Or did I just talk myself into a circle? The problem is that `error_cnd()` should link to `cnd.html`, not `error_cnd.html`.

**Comment by hadley** [comment]
Yeah, and when I run it locally with dev pkgdown, it works correctly. But now that I understand the root cause is in pkgdown, this is bringing back a vague memory that we did fix something related.
