### ISSUE TITLE
Preventing R CMD INSTALL . from running on Github

### ISSUE THREAD

**Issue by alanaw1** [r-lib/pkgdown#1754]
First, I apologise if this is the wrong platform for me to post my question. I could not find any other platform that seems appropriate.

I currently use pkgdown to document and generate an accompanying webpage for my R package. Whenever I make a new commit and push, pkgdown triggers an installation of my package via `R CMD INSTALL .`.  Unfortunately my package does not seem to install properly, with Github informing me that `Error: package or namespace load failed` has occurred.

![Screen Shot 2021-08-23 at 10 14 24 AM](https://user-images.githubusercontent.com/29695123/130490103-41bf740a-18de-4a23-8b7d-78dfe2504151.png)

For context, I don't face an issue when installing my package on my local computer (running `R CMD INSTALL .`) while I am in the repo directory. (My computer uses MacOS 10.13.6.) 

I would like to disable the `R CMD INSTALL .` step and all downstream steps whenever I push a commit to Github. If I understand correctly, I can do so by editing the _pkgdown.yml file. Unfortunately I do not know what I should include there to accomplish my goal.

Would someone mind troubleshooting this? Thanks.

**Comment by hadley** [comment]
Unfortunately we don't have the resources to troubleshoot why your package fails to build on Github, but installing the package is a key part of the pkgdown process, and is not something we are likely to change.
