### ISSUE TITLE
`build_news` issues

### ISSUE THREAD

**Issue by samuel-marsh** [r-lib/pkgdown#1763]
Hi,

I'm having issues with my News.md document rendering properly on my previewed pkgdown site.  If I knit the News.md separately it works just fine.

However, when I run `build_site()` and then click on header where it should be this is what appears:
![image](https://user-images.githubusercontent.com/38284410/133113697-1b2cbd7a-9c01-4e40-9217-b91a4f30bcb5.png)

If I click on News.md link I get a 404 error page.

However, what I noticed is that in the `docs/` folder I have a file/folder of `news/index.html` and that html file is what is getting rendered in the site preview.  However in the `docs/` folder itself is another file `News.html` which is properly rendered html of my News.md file (Cut off for brevity).
![image](https://user-images.githubusercontent.com/38284410/133114399-c462e8bc-aa20-43b7-8e6c-a00e54e1c1a0.png)

Problem is I don't understand why `build_site`/`build_news` are not properly rendering/linking to the correct file to display on the site.

Pkgdown novice so might be something very obvious but google is failing me currently.

Thanks!
Sam

**Comment by hadley** [comment]
Do you have `News.md` or `NEWS.md` ?

**Comment by samuel-marsh** [comment]
It was `News.md`.  I just tried deleting News.md and the entire docs folder.  Saving new NEWS.md (with same content saved via Atom).  Then running `build_site` again.

The pkgdown preview site looks identical except now it the hyperlink is "Source: NEWS.md".

However, there is no longer a separate html file inside the docs folder.

If I preview NEWS.md alone (view Preview button in RStudio) it renders as expected.

I should add in case it's helpful running this on
R3.6.2
Mac OSX Catalina
Pkgdown v1.6.1 (from CRAN)
_pkgdown.yml file only contains manual annotation/ordering of the Reference page.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Hi @hadley 

Sorry meant to close and leave message!!!  After bunch of testing I solved the issue (at least most of the time, some of the time it still has the issue).  Couldn't pin the rendering on anything in particular while I was trying to come up with reprex.  If I figure out what the cause was I'll be sure to repost!  Appreciate the response!!!

Best,
Sam
