### ISSUE TITLE
YAML front matter not being passed to output format

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/pkgdown#1767]
Hi,

I am trying to include some arbitrary HTML pages in my `pkgdown` website - in other words, HTML documents rendered with a format that is not `rmarkdown::html_vigenette()` and also does not inherit or combine with the `pkgdown` website at all. Just a totally independent HTML document that I want to be available in `docs/articles/...`

I have the R Markdown file located in `vignettes/examples/example.Rmd` where the YAML front matter looks something like this:
````yaml
---
title: "Untitled"
pkgdown:
  as_is: true
output: 
  mypkg::my_format:
    key: "value"
---
````

When rendering this by clicking knit or any other method, the key-value pair gets passed on just fine. When building this article with `pkgdown::build_articles()`, the key-value pair is missing and I get the following error:
```
-- Building articles ------------------------------------------
[WARNING] Deprecated: markdown_github. Use gfm instead.
Reading 'vignettes/examples/example.Rmd'
-- RMarkdown error --------------------------------------------
Error in charToRaw(key) : 
  argument "key" is missing, with no default
---------------------------------------------------------------
Error: Failed to render RMarkdown
Run `rlang::last_error()` to see where the error occurred.
```

Am I doing something wrong?  Is there something different about how `pkgdown` renders this file? Is it not just calling `rmarkdown::render()` under the hood? I appreciate any help.

For added context, I also have followed this guidance:
> If you want to include an article on the website but not in the package (e.g., because it’s large), you can either place it in a subdirectory of vignettes/ or add it to .Rbuildignore (and make sure that there’s no vignettes: section in the yaml header). In the extreme case where you want to produce only articles but not vignettes, you should add the complete vignettes/ directory to .Rbuildignore and ensure that DESCRIPTION does not have a VignetteBuilder field.

**Comment by maelle** [comment]
I wonder it would help to replace https://github.com/r-lib/pkgdown/blob/705ff7c650bb1c7d46d35e72f27ad093689e2f29/R/build-articles.R#L261 with the use of `rmarkdown::default_output_format()`. :thinking:

**Comment by mattwarkentin** [comment]
Hi @maelle,

Thanks for the response! I have been spinning my wheels and was really starting to think I was using `pkgdown` for very off-label usage. 

Am I correct to assume that I should be able to able to render an article to literally any format with `as_is: true`? Or if that isn't the current behaviour, should it be?

My package creates new R Markdown formats and I was hoping to be able to include rendered examples in the `pkdown` website. To this end, I was hoping `pkgdown` would render these articles to the exact format defined in the YAML header, but otherwise do very little else as far as templates/themes/etc. Just render the article and move it to wherever it needs to be (e.g. `docs/`). It seems like there should be a mechanism for this but I have had a difficult time.

**Comment by hadley** [comment]
No, unfortunately you can't expect to render literally any document format with pkgdown; there's a bunch of stuff we have to do to make a vignette work right inside of a pkgdown site.

**Comment by mattwarkentin** [comment]
Thanks for the reply. I guess I was being too hyperbolic about literally any format. Am I misunderstanding what `as_is: true` is meant to do? My new format is a thin wrapper around `rmarkdown::html_document`. `pkdown` seems to be okay with PDF formats, why is this the case?

**Comment by hadley** [comment]
Unfortunately, few people use custom rmarkdown formats for vignettes and there's a lot of variety in the formats that people do want to use, so I don't currently think we have the development budget to spend on getting it working.
