### ISSUE TITLE
Change default tooltip in release mode?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1768]
Via https://github.com/r-lib/usethis/issues/1482#issuecomment-920185526 by @jennybc 

> Yes, I think that tooltip should either be smart enough to say "released" or "dev" version (and be correct) or it should admit it doesn't know and be more vague / descriptive ("package version", "documented version", etc.).

**Comment by hadley** [comment]
So the root cause of this is that `meta_development()` assumes `mode` is "release" unless informed otherwise. I think the easiest fix is probably just to not set the tooltip unless mode is explicitly set.
