### ISSUE TITLE
how to suppress console output in function example documentation?

### ISSUE THREAD

**Issue by drwilkins** [r-lib/pkgdown#1781]
In a typical markdown document, I would be able to turn of warnings and messages from the console from being printed in my document with `knitr::opts_chunk$set(warning=FALSE, message=FALSE)`

How do I do this for my roxygen2-styled examples in my functionName.R files? For example, I have a rather complicated function that calls on a number of other functions with complicated output. This leads to a rather ugly help document.

I simply want to prevent all console output from being rendered in the Reference documents being generated by pkgdown::build_site()

**Comment by hadley** [comment]
The goal of the examples is to render exactly as the user would see in the console, so if you think the example output is ugly, I'd recommend adding `quiet = TRUE` argument or similar so that the user (and your examples) can suppress the output.
