### ISSUE TITLE
Output plots in help files are incorrect when a legend is added

### ISSUE THREAD

**Issue by dfriend21** [r-lib/pkgdown#1794]
I'm using `pkgdown` to generate a website for my package. One of the `plot()` functions in my package adds a legend to the side of the plot (in the margin). When running it in R (and outputting the plot to a file) it works just fine. But when the plots are created for the 'Examples' section of the help files, the legend is not being placed correctly.

I've come up with a reproducible example. It uses a very simple function that adds a legend to an existing plot, using the user coordinates (from `par("usr")`) to place the legend in the margin. After a lot of trial and error, I've found that the error seems to occur when `asp` and either `xlim` or `ylim` is set. The example makes a 2 x 2 plot grid showing the outputs with different parameters used for `plot()` and outputs it to a file - I dug through some of the package code (especially the `fig_save()` function in `R/figure.R`) and was able to derive the parameters being used when `pkgdown` makes the plots. I used these parameters to save the plot to a file, using the same graphics device as `pkgdown` (`ragg:agg_png()`). I should also note that I'm not setting any of the `figures:` parameters in `_pkgdown.yml`.

``` r
add_lgd <- function(){
  rast <- as.raster(hcl.colors(100))
  usr <- par("usr")
  rasterImage(rast, 
              xleft = usr[2],
              ybottom = usr[3], 
              xright = usr[2] + .2, 
              ytop = usr[4],
              xpd = TRUE)
}

ragg::agg_png("~/path/to/file/example.png", width = 1400, height = 866, res = 192, bg = NA)

par(mfrow = c(2,2))
plot(1,1, main = "default")
add_lgd()

plot(1,1, xlim = c(0,1), ylim = c(0,1), asp = 1, main = "xlim = c(0,1), ylim = c(0,1), asp = 1")
add_lgd()

plot(1,1, xlim = c(0,1), asp = 1, main = "xlim = c(0,1), asp = 1")
add_lgd()

plot(1,1, ylim = c(0,1), asp = 1, main = "ylim = c(0,1), asp = 1" )
add_lgd()

dev.off()
```

The output looks like this:

![example](https://user-images.githubusercontent.com/7896671/135164688-a6ffc257-acf0-432e-bfb1-08e0aade79f3.png)

I put the example code in the `@examples` section of the Roxygen documentation of one my R files and removed the calls to `ragg::agg_png()` and `dev.off()`. I then used `pkgdown::build_site()` to build the website. Here's the image that `pkgdown` creates:

![plot-22](https://user-images.githubusercontent.com/7896671/135165047-d42f4779-9004-431d-9aec-5c5ba5fff4ea.png)

As you can see, the legend bar is displayed differently than when I manually saved the plot to a file even though I used the same graphics device with the same parameter settings. In particular, when `ylim` and `asp` are set it the legend appears on top of the plot. I tried every combination of these parameters, and if `asp=1` is used without `xlim` and `ylim`, it works fine. And the same goes when I used `xlim` and/or `ylim` without `asp`.

I'm at a loss as to what's happening and how to fix it, although I'm guessing it has something to do with the fact that I'm using `par("usr")` to determine where to place the legend.

Here's the output of `sessioninfo::session_info()`:

```
─ Session info ───────────────────────────────────────
 setting  value                       
 version  R version 4.1.1 (2021-08-10)
 os       macOS Catalina 10.15.7      
 system   x86_64, darwin17.0          
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Los_Angeles         
 date     2021-09-28                  

─ Packages ───────────────────────────────────────────
 package     * version date       lib source        
 cachem        1.0.5   2021-05-15 [1] CRAN (R 4.1.0)
 cli           3.0.1   2021-07-17 [1] CRAN (R 4.1.0)
 codetools     0.2-18  2020-11-04 [1] CRAN (R 4.1.1)
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.1.0)
 evaluate      0.14    2019-05-28 [1] CRAN (R 4.1.0)
 fastmap       1.1.0   2021-01-25 [1] CRAN (R 4.1.0)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.1.0)
 htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.1.0)
 knitr         1.34    2021-09-09 [1] CRAN (R 4.1.0)
 lattice       0.20-44 2021-05-02 [1] CRAN (R 4.1.1)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.1.0)
 memoise       2.0.0   2021-01-26 [1] CRAN (R 4.1.0)
 pkgdown     * 1.6.1   2020-09-12 [1] CRAN (R 4.1.0)
 ragg        * 1.1.3   2021-06-09 [1] CRAN (R 4.1.0)
 raster        3.4-13  2021-06-18 [1] CRAN (R 4.1.0)
 Rcpp          1.0.7   2021-07-07 [1] CRAN (R 4.1.0)
 rlang         0.4.11  2021-04-30 [1] CRAN (R 4.1.0)
 rmarkdown     2.9     2021-06-15 [1] CRAN (R 4.1.0)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.1.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.1.0)
 sp            1.4-5   2021-01-10 [1] CRAN (R 4.1.0)
 systemfonts   1.0.2   2021-05-11 [1] CRAN (R 4.1.0)
 textshaping   0.3.5   2021-06-09 [1] CRAN (R 4.1.0)
 withr         2.4.2   2021-04-18 [1] CRAN (R 4.1.0)
 xfun          0.26    2021-09-14 [1] CRAN (R 4.1.0)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.1.0)

[1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
```

UPDATE: right after I posted this I came across this page:  https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md#package-reprexes
which describes how to make a reprex for `pkgdown`. So I took the code above and put it into a test package. The code is at https://github.com/dfriend21/testpackage. The `pkgdown` website is at https://dfriend21.github.io/testpackage/ and the relevant page is https://dfriend21.github.io/testpackage/reference/example.html.

The `example()` function contains the code required to output the plot to the file system. It has one parameter - `filepath`. And in the 'Examples' section of the documentation for `example()` I put the example code without the `ragg::agg_png()` and `dev.off()` statements so that it shows up in the 'Examples' section.

**Comment by hadley** [comment]
I think unfortunately that this is something you're likely to have to figure out on your own, as we haven't heard of any other instances of this problem which means it's some unlucky interaction between your plotting code and the way downlit renders examples. 

One place to start would be with `recordPlot()`/`replayPlot()`, which is what the evaluate package (which is used by downlit, which is used by pkgdown) uses to capture plots. If you capture and replay the plot do you see the same problem? If so, that suggests something is going wrong in your plotting code, and would give you a faster way to iteratively discover the problem.

**Comment by dfriend21** [comment]
Thanks for the response and for the suggestion to checkout `recordPlot()` and `replayPlot()` - when I captured and replayed the plot the same problem occurred. I'll investigate further, and I'm thinking I'll have to rewrite how I'm adding the legend.

I'm closing this issue since it isn't a 'pkgdown' issue. Thanks for the help, though - you definitely pointed me in the right direction.
