### ISSUE TITLE
Errors when parsing markdown files

### ISSUE THREAD

**Issue by dieghernan** [r-lib/pkgdown#1800]
Hi, 

Since the upgrade to v 1.9000.9000.9000 I see an issue on homepage (parsed from README):

```

#> HernangÃ³mez D (2021). _giscoR: Download Map Data from GISCO API 

```
On previous versions it was "Hernangómez", without escaping. Also other characters as "©" now are parsed as "Â©".

https://ropengov.github.io/giscoR/

On v 1.6.1.9001. this was parsed correctly, see https://dieghernan.github.io/nominatimlite/

```

citation("nominatimlite")
#> 
#> To cite the 'nominatimlite' package in publications use:
#> 
#> Hernangómez D (2021). _nominatimlite: Interface with 'Nominatim' API
#> Service_. doi: 10.5281/zenodo.5113195 (URL:
#> https://doi.org/10.5281/zenodo.5113195), R package version 0.1.1, <URL:
#> https://dieghernan.github.io/nominatimlite/>.
#> 
#> A BibTeX entry for LaTeX users is
#> 
#>   @Manual{,
#>     title = {nominatimlite: Interface with 'Nominatim' API Service},
#>     year = {2021},
#>     note = {R package version 0.1.1},
#>     version = {0.1.1},
#>     author = {Diego Hernangómez},
#>     doi = {10.5281/zenodo.5113195},
#>     url = {https://dieghernan.github.io/nominatimlite/},
#>   }

```

**Comment by dieghernan** [comment]
Maybe related with https://github.com/r-lib/pkgdown/commit/b9db0360b4dbbb9a80da657099d8dd25058ac556 🤔?

**Comment by dieghernan** [comment]
It is not restricted to README, see https://ropengov.github.io/giscoR/LICENSE.html:


```
Version 3, 29 June 2007
Copyright Â© 2007 Free Software Foundation, Inc.Â <http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license document, but changing it is not allowed.

Preamble
The GNU General Public License is a free, copyleft license for software and other kinds of works.

The licenses for most software and other practical works are designed to take away your freedom to share and change the works. By contrast, the GNU General Public License is intended to guarantee your freedom to share and change all versions of a programâto make sure it remains free software for all its users. We, the Free Software Foundation, use the GNU General Public License for most of our software; it applies also to any other work released this way by its authors. You can apply it to your programs, too.

...


For the developersâ and authorsâ protection, the GPL clearly explains that there is no warranty for this free software. For both usersâ and authorsâ sake, the GPL requires that modified versions be marked as changed, so that their problems will not be attributed erroneously to authors of previous versions.


```

**Comment by maelle** [comment]
The error is somewhere in `markdown_path_html()` :female_detective:

**Comment by maelle** [comment]
(which was changed in the PR you mentioned above)

**Comment by maelle** [comment]
At

https://github.com/r-lib/pkgdown/blob/1803229326669a2734c5f9ad564a39f0012f6ded/R/markdown.R#L63

The signs are still fine.

After https://github.com/r-lib/pkgdown/blob/1803229326669a2734c5f9ad564a39f0012f6ded/R/markdown.R#L64

they are not.

Maybe the HTML should be read like in `update_html()`.

**Comment by maelle** [comment]
Noting that `update_html()` via the functions it uses, assumes UTF-8, and if instead of ` xml <- xml2::read_html(html_path) ` above I add the same encoding then things look fine.

**Comment by maelle** [comment]
And it used to be the case in the Markdown transforming function.

https://github.com/r-lib/pkgdown/blob/ff06f4fb444ac4c7cc6219177d87986994026124/R/markdown.R#L27

**Comment by hadley** [comment]
@maelle do you minding sharing the reprex you presumably created so I can turn it into a test?

**Comment by maelle** [comment]
@hadley sorry, I simply cloned the repo mentioned in the report. :sweat_smile:
