### ISSUE TITLE
BS4: `run_dont_run` doesn't have effect on `deploy_to_branch`

### ISSUE THREAD

**Issue by dieghernan** [r-lib/pkgdown#1801]
Hi:

When I build locally my site with `pkgdown::build_reference(run_dont_run = TRUE)` the behaviour is the one expected, i.e. examples with `\dontrun{}` are run.

However, when deploying to GitHub Pages the examples are not run, see https://ropengov.github.io/giscoR/reference/gisco_clear_cache.html#examples.

pkgdown version: 1.9000.9000.9000.

GH action [link](https://github.com/rOpenGov/giscoR/blob/main/.github/workflows/rogtemplate-gh-pages-clean.yaml). Relevant lines:

https://github.com/rOpenGov/giscoR/blob/92b4dcc85b616252e3829fe327b276bf89e66716/.github/workflows/rogtemplate-gh-pages-clean.yaml#L45-L49

```yaml
      - name: Deploy package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = TRUE, run_dont_run = TRUE, lazy = FALSE)'

```

**Comment by maelle** [comment]
It seems the `...` aren't passed

https://github.com/r-lib/pkgdown/blob/8a0332494bfd1edd015dbea701de4d2bc8c5d7b7/R/deploy-site.R#L132

If I follow https://github.com/r-lib/pkgdown/issues/1756 + https://github.com/r-lib/pkgdown/issues/1611#issuecomment-926899563 correctly the idea ultimately is that the workflow files will contain a direct call to the `build_site_github_pages()` function.

**Comment by dieghernan** [comment]
Hi @hadley, still no luck with this. I even deleted the branch and restarted it with `run_dont_run` 😞 .
https://ropengov.github.io/giscoR/reference/gisco_clear_cache.html#examples

Maybe you can try on this very own repo, I see a regression test here:
https://pkgdown.r-lib.org/dev/reference/test-dont.html

It hasn't run, but maybe is due to your repo deployment config.

Many thanks, hope I could help you all to catch some bugs

**Comment by dieghernan** [comment]
Deleting my previous comment. I updated the cache version on GH Actions and now it’s working. Thanks!
