### ISSUE TITLE
Make it easier to use organization-wide COC and contributing guide?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1802]
The visibility pkgdown gives to the COC and contributing guide is great. Would it make sense for pkgdown to detect, for packages with a GitHub repo, whether there's an organization wide COC / contributing guide (".github files")?

However, I understand that it'd add to the code (and something that'd need to be escaped when there's no internet / no GH token) and that there are at least two workarounds
* copy the files before building the site;
* using https://pkgdown.r-lib.org/dev/reference/build_home.html#sidebar.

**Comment by hadley** [comment]
This just feels out of scope for pkgdown to me; I really don't like the idea of it having to figure out which files should be included that aren't already on your computer.
