### ISSUE TITLE
Multiple reference pages

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgdown#1845]
The reference button would be a drop-down menu that gives access to multiple reference pages, a bit like the Articles button gives access to multiple vignettes.

This would help:

- Large packages that cover multiple domains. For instance in rlang there would be one reference for NSE, one for error handling, etc.

- Packages that export functions for different audiences. For instance dplyr exports functions for data analysis and functions for developers of extensions.

**Comment by hadley** [comment]
Given the new rlang site design, do you still think this is necessary?

**Comment by lionel-** [comment]
I think this would be helpful for rlang and dplyr, and probably many other websites.

For rlang the current state is already good but having sectioned references would increase the clarity of the package domains and make it easier to discover functions. For dplyr this would allow us to include a reference aimed at developers without cluttering the index, there are currently many unreferenced functions.

**Comment by hadley** [comment]
I'm worried that splitting across multiple pages fundamentally makes this less of an index (i.e. you can no longer `ctrl + F` to search all functions/descritpions). For dplyr, maybe we should have a "For developers" top-level section at the bottom of the page?

**Comment by lionel-** [comment]
Good point, there's a tradeoff between discoverability and searchability. Maybe we could have a full reference section that serves as an index? I'm fine closing this and sleep on the idea until it comes up again if you'd like.

**Comment by hadley** [comment]
Yeah, let's live with what we have for a while, and re-open later if needed.
