### ISSUE TITLE
Test improvements

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#1854]
* [ ] Automatically set `quiet = TRUE` in tests so `expect_output()` can be removed
* [ ] Automatically set `cran_dates: false` in tests
* [ ] Define `html_fragment()` to replace `xml2::read_xml("<body>...</body>")`

**Comment by maelle** [comment]
It'd be nice for `build_site()` to have a quiet argument too, that `cat_line()` could use.

**Comment by maelle** [comment]
Related #2330

**Comment by hadley** [comment]
Closing this because it's 3 years later and I think this has mostly been done (or at least these problems are no longer actively bugging me)
