### ISSUE TITLE
Translation cause a crash of R in some functions when doing YAML conversion

### ISSUE THREAD

**Issue by cderv** [r-lib/pkgdown#1877]
This happens with last pkgdown version which include translation, and I believe this is due to the new translation system

As I am running on a French computer, any work I do with pkgdown will now apply translation. It will sometimes add accentuated characters like `References` -> `Référence`.

`template_navbar()` will create a list of component of the navbar, but will now translate them. So for example, `menu$reference$text` is now `Référence`. The crash happens from `navbar_components()` in the `print_yaml` call
https://github.com/r-lib/pkgdown/blob/6a412e3a9d2d12d43e6b24eb25b97633ec350cda/R/navbar.R#L93-L116

This is because `yaml::as.yaml(menu)` will cause a crash. This is a known issue in `yaml` R package I believe 
https://github.com/viking/r-yaml/issues/90

The encoding of `menu$reference$text` is unknown. Setting it to UTF8 (`enc2utf8(menu$reference$text)` solves the issue. 
Maybe it should be encoded to utf8 all the time ? (in `tr_`) ?

I think pkgdown will need to deal with this somehow in all the function where translated word can end up into YAML. 

I did not come up with a reprex specific to pkgdown, as the reprex is the one for `yaml` package issue.

**Comment by hadley** [comment]
Thanks for reporting this!

**Comment by cderv** [comment]
I can confirm the issue is fixed now.
