### ISSUE TITLE
More navbar customization?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1882]
Two questions that I'm guessing might be a bit too niche for the package and actual candidates for custom templates.

* Should it be easier to incorporate an image (say, a logo that's not an icon) in the navbar without using a custom template? At the moment, HTML tags in custom components are HTML escaped. 
* Should it be possible to also move the package name and version (to e.g. include some sort of logo on the left)?

**Comment by maelle** [comment]
Maybe that part of the navbar (left of the left elements i.e. package name and version) could be in a separate template so it'd be easier to override without reproducing the whole navbar?

**Comment by hadley** [comment]
Oh yeah, that's a good idea!
