### ISSUE TITLE
Catch roles that aren't translated

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pkgdown#1883]
Roles [without a translation](https://github.com/r-lib/pkgdown/blob/3912737f46bf1f9f04ce59ee333b685d7bff599f/R/build-home-authors.R#L198-L211) appear as `NA` in the author section of the sidebar, e.g.

``` r
pkgdown:::role_lookup(c("res", "ccp", "aut"))
#> [1] NA       NA       "author"
```

`"ccp"` (Conceptor) is a role that happens to be used in a couple packages I maintain; I noticed `"res"` (Researcher) when searching GitHub to gauge how widely `"ccp"` is used. Both seem to have enough usage to warrant a translation.

Whether or not you decide to add those two roles to the role lookup list, it might be useful to remove `NA` values or to fall back on the English term from `utils:::MARC_relator_db` for roles not explicitly translated.

**Comment by hadley** [comment]
I dropped the list of MARC roles back to what CRAN supports; I could probably add these back in as special cases.
