### ISSUE TITLE
TOC in articles not rendered properly with devel-`{pkgdown}`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#1886]
Minimal reprex website:
https://indrajeetpatil.github.io/minimalReprex/articles/test2.html

# with default bootstrap version

For example, if my vignette TOC has the following structure:

![image](https://user-images.githubusercontent.com/11330453/140726199-a5c213b9-bd07-4c4c-b762-60dc514a6135.png)

It is rendered as:

![image](https://user-images.githubusercontent.com/11330453/140725977-0c8e8c7d-d4f4-4018-a290-20464cd4d126.png)

# with `bootstrap: 5`

The TOC is rendered as expected with defaults.

But if I specify `bootswatch` theme (e.g. to have dark background) as specified [here](https://github.com/r-lib/pkgdown/blob/d1a64f28518dc83905c6dc36ce68eeaaa80d3505/vignettes/customise.Rmd#L62-L67)), it leaves out section titles:

![image](https://user-images.githubusercontent.com/11330453/140729066-47ea5ee1-06a3-4e86-a4a1-e56c0760c934.png)

**Comment by hadley** [comment]
Probably because you've used multiple `<h1>`; pkgdown only expects one (generated by the article title).

**Comment by IndrajeetPatil** [comment]
> pkgdown only expects one (generated by the article title)

Oh? Somehow missed this. It works with the CRAN version, but I guess that is serendipitous.

At any rate, I tried with `<h2>` and `<h3>`, and it looks good! Thanks.
