### ISSUE TITLE
A small tabset oddity

### ISSUE THREAD

**Issue by jonkeane** [r-lib/pkgdown#1889]
Thanks to @maelle (#1694) tabsets work fantastically in vignettes which is really great. They should also work (and mostly do) in other places like the home page from `readme.md` But I'm noticing one oddity. I can't quite tell if this is a bootstrap problem or something else going on.

I made a basic [example package showing this](https://jonkeane.github.io/simple-package/index.html). By default the R tab is selected, but if you scroll past it (on both safari and chrome), the css features that show that it's selected (rounded box, grey background, different color type) disappear (though the tab content remains). I also included an identical tabset in [the vignette](https://jonkeane.github.io/simple-package/articles/a-vignette.html) which works just fine and one can scroll past it without changing the selection indications.

https://github.com/jonkeane/simple-package has the source of the simple package.

**Comment by hadley** [comment]
Hmmm, so before scrolling down:

```html
<a data-bs-toggle="tab" id="r-tab" href="#r" role="tab" aria-controls="r" aria-selected="true" class="nav-link active">R</a>
```

And after scrolling down:

```html
<a data-bs-toggle="tab" id="r-tab" href="#r" role="tab" aria-controls="r" aria-selected="true" class="nav-link">R</a>
```

So something is stripping the active class.

**Comment by maelle** [comment]
Expected HTML markup https://getbootstrap.com/docs/5.1/components/navs-tabs/#javascript-behavior

**Comment by maelle** [comment]
The behaviour works on the homepage if using a README table of contents :exploding_head: 

E.g. 

```yaml
home:
  sidebar:
    structure: [links, toc, license, community, citation, authors, dev]
```

I tried this because that's the only JS thing that is different between the default homepage and a default vignette.

**Comment by maelle** [comment]
The fix is probably to not include the bootstrap-toc JS if there's no TOC otherwise it mixes with other things?!

**Comment by maelle** [comment]
Site I obtained with my pkgdown branch https://hopeful-lewin-04de2a.netlify.app/

**Comment by maelle** [comment]
(thanks a lot @jonkeane for the precise bug report & reprex!)

**Comment by maelle** [comment]
I do see an error in the console for the website mentioned above though. (from pkgdown.js)

**Comment by maelle** [comment]
That's because pkgdown.js has the line Toc.init

**Comment by maelle** [comment]
I updated my PR and the Netlify preview.

**Comment by jonkeane** [comment]
Oh wow, that was quick! And it looks like it works perfectly. Thank you!

**Comment by hadley** [comment]
Is this maybe the same problem as #1959?
