### ISSUE TITLE
Unnest articles in the `vignettes/articles` directory

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pkgdown#1892]
Storing non-vignette articles in the `vignettes/articles` directory is a convenient way to isolate articles and assets that shouldn't be included in the installed package. It's also the default behavior of `usethis::use_article()` — to place new articles in a `vignettes/articles` directory and to ensure an entry exists in `.Rbuildignore` to ignore the articles directory.

The downside of this approach is that pkgdown moves articles to `<root>/articles/<path inside vignettes>`, resulting in URLs like `<root>/articles/articles/examples.html`.

One example:

- pkgdown: https://reprex.tidyverse.org/articles/articles/rtf.html
- source: [vignettes/articles/rtf.Rmd](https://github.com/tidyverse/reprex/blob/master/vignettes/articles/rtf.Rmd)

I understand that this is mostly cosmetic and that it might not be desirable to change the default behavior since many public URLs probably include `articles/articles`. Perhaps new behavior of moving these articles to `articles/` could be opt-in behind a config option with a default value that might change in the future. Or maybe the new redirects feature could be used to mitigate the downstream issues of simplifying the URL.

One way in which this isn't just cosmetic is that, as a user following the lead from `use_article()`, there's a sense that `vignettes/articles/` is _special_. For the most part, wherever pkgdown handles links I wouldn't have noticed the URL, but I had a hard time anticipating the final path of shared assets and was surprised to discover the extra `articles/`.

**Comment by hadley** [comment]
I like the idea of moving them up a level, and then automatically adding redirects.
