### ISSUE TITLE
Allow templates to be provided in the `pkgdown/` directory

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pkgdown#1893]
A package author might want to make limited changes to a parent pkgdown template, or perhaps provide an additional customization for a template.

Much like hugo accepts custom layout templates at the site level that take precedence over the global theme's layout, I'd like to propose that templates in a `pkgdown/templates` directory in a package's project take precedence over the templates provided by the template defined in `_pkgdown.yml` or those provided by `pkgdown` directly. The end result is that it becomes easier to make small modifications without needing the additional infrastructure of a package or without having to make upstream modifications to the template package.

If this seems reasonable, I'd be happy to provide a PR. I have a working local implementation that adds `path(pkg$src_path, "pkgdown", "templates")` to the front of the [`template_candidates()`](https://github.com/pkgdown/pkgdown/blob/3912737f46bf1f9f04ce59ee333b685d7bff599f/R/templates.R#L33) paths here:

https://github.com/r-lib/pkgdown/blob/3912737f46bf1f9f04ce59ee333b685d7bff599f/R/templates.R#L39-L42

Since `template_candidates()` doesn't take `pkg` as an argument, we'd need to update the function signature and ensure that `src_path` is passed down through [`find_template()`](https://github.com/r-lib/pkgdown/blob/3912737f46bf1f9f04ce59ee333b685d7bff599f/R/templates.R#L1-L5) from its calling functions, much like how `templates_dir` is handled currently.

**Comment by hadley** [comment]
Yeah, that seems reasonable.
