### ISSUE TITLE
Custom templates based on the `content-article` template

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/pkgdown#1894]
Somewhat building on the feature request in #1893, it'd be useful to advanced users of pkgdown to be able to create additional content layout templates. 

I imagine the source content would be written, stored, and processed in all the same places and ways that articles are currently, but instead of using the `content-article.html`, they could use an alternative template chosen via an option in the YAML frontmatter of the article.

As a hypothetical example, the article stored in `vignettes/gallery.Rmd` might start with

```markdown
---
title: Gallery of Examples
content_type: gallery
---
```

that would cause `render_page_html()` to find and use a `content-gallery.html` template rather than `content-article.html`, throwing an error if an appropriate content template can't be found.

(The `content_type` YAML key is just a first draft name suggestion, of course.)

**Comment by hadley** [comment]
I guess I don't see why an article would want to change the contents of the template outside of the main content block. Can you provide an example of where you'd use this?

**Comment by gadenbuie** [comment]
The two-column layout works great for typical articles, but it would be great to allow the additional flexibility to other layouts. Because the main content block is added inside the main column, an author wanting to write content with an alternative layout would need to create a custom template (hosted in a package, etc. hence the overlap with #1893).

In my case, I'm working on re-implementing an examples gallery — https://rstudio.github.io/learnr/examples.html — that feels very constrained when contained inside both `.col-md-9` and `.contents`. 

This was the motivating example for me, but after reading through the BS5 `content-article.html` template again, I'm wondering if an alternative resolution would be to make the `.col-md-9` class and the entire `#pkgdown-sidebar` conditional on the TOC being included? This seems reasonable in the BS5 template since the TOC is the only thing included in the article sidebar.

https://github.com/r-lib/pkgdown/blob/8122179c440692487eda000d6542d7734a37d36d/inst/BS5/templates/content-article.html#L49-L55

That would be small change that would give authors the flexibility to do whatever they want in the content block without having to modify the template.

The one minor issue though, is that we constrain `.contents` to `max-width: 50rem`, which makes sense for text content but would also be too constraining for custom layout scenarios (or the gallery). Users could either include a `<style>` tag to reset the `max-width` property of `.contents` or we could conditionally include `.mw-100` when there isn't a TOC. Neither feels like a perfect solution but I prefer the first option since I think it will be best for the largest number of people.
