### ISSUE TITLE
anchor link icons not shown for top-level default sections

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pkgdown#1909]
This is rendered with `renv` as of https://github.com/rstudio/renv/tree/36846af68980bcd18a847b61e470361f7617ba27, using latest development version of `pkgdown`.

<img width="1391" alt="Screen Shot 2021-11-15 at 10 45 37 AM" src="https://user-images.githubusercontent.com/1976582/141837112-8ba13bb3-4c7f-4789-b89f-e9f076003363.png">

Note that the `-1` suffix is included on element IDs, and no anchor icon is displayed when mousing over the `Argument` section text.

**Comment by hadley** [comment]
Is this bs3 or bs5?

**Comment by kevinushey** [comment]
> Is this bs3 or bs5?

I hadn't opted into using bootstrap 5 yet, so I guess still Bootstrap 3?

I don't see the issue with Boostrap 5 though, after adding `template: bootstrap: 5` to my `_pkgdown.yml`.

**Comment by hadley** [comment]
Yeah, I'm pretty sure this isn't a regression so I'm not going to fix it. The bs5 templates apply the anchors in a much more robust way.
