### ISSUE TITLE
Broken crosslinks

### ISSUE THREAD

**Issue by c4f3a0ce** [r-lib/pkgdown#1910]
I am using `pkgdown` 1.6.1

I created a simple project like https://github.com/c4f3a0ce/pkgdowncrosslinks with the following content:

```r
setGeneric("bar", function(x) {
  standardGeneric("bar")
})


#' A dummy class
#'
#' @slot foo character
#'
#' @family Foo functions
#' @docType class
#'
setClass("Foo", slots = c(foo = "character"))

#' A dummy method
#'
#' @param x Foo
#'
#' @family Foo functions
#' @aliases bar,Foo-method
#'
#' @export
setMethod(
  "bar",
  signature(x = "Foo"),
  function(x) {}
)
```

When I build site, main [index uses correct links](https://github.com/c4f3a0ce/pkgdowncrosslinks/blob/87e1b2702afc80e736d2b9f084cbda2fc5a2b02c/docs/reference/index.html#L137) 

```html
          <p><code><a href="bar-Foo-method.html">bar(<i>&lt;Foo&gt;</i>)</a></code> </p>
```

but [see also section of `Foo`](https://github.com/c4f3a0ce/pkgdowncrosslinks/blob/87e1b2702afc80e736d2b9f084cbda2fc5a2b02c/docs/reference/Foo-class.html#L128) doesn't.

```html
<code><a href='bar,Foo-method.html'>bar,Foo-method</a></code></p></div>
```

**Comment by hadley** [comment]
This appears to be fixed in the development version.
