### ISSUE TITLE
Caption text face different between Chrome & Safari

### ISSUE THREAD

**Issue by samuel-marsh** [r-lib/pkgdown#1913]
Hi,

Having an strange issue regarding the face of text in figure captions.  I'm not 100% this is pkgdown error but guessing I'm missing something to put in pkgdown setup to make this work.

Basically, I have captions for figures that are written like this:
```
{r echo=FALSE, fig.align='center', fig.height=8, fig.width=13, fig.cap="***A.** Default for `VariableFeaturePlot_scCustom` labels features by default.  Plot can be modified by changing function parameters: **B.** Setting `label = FALSE`, **C.** Setting `repel=TRUE` for feature names, **D.** Setting `y_axis_log=TRUE` to plot y-axis in log scale.*"}
```

The goal is to have the entire caption text italicized but the panel tags (A, B, etc) bolded as well.  When you view the site with Safari this appears correct:
![image](https://user-images.githubusercontent.com/38284410/142214336-d96f00ae-5e06-4f73-90ba-c2a08a334b20.png)

However with Chrome it is only italicized with no bold text:
![image](https://user-images.githubusercontent.com/38284410/142214411-943d28ef-72be-4d04-ac91-f8c973431c99.png)

Website can be found here for reference:
https://samuel-marsh.github.io/scCustomize/articles/Gene_Expression_Plotting.html

I should mention that I also have a html snippet in the Rmd to control caption text size (not sure if that could be effecting things only in Chrome though...)
```
<style>
p.caption {
  font-size: 0.9em;
}
</style>
```

Versions:
R4.1.2
pkgdown 1.6.1

Thanks!
Sam

**Comment by hadley** [comment]
The html looks correct and using chrome devtools verifies that the text has bold weight and italic style. That suggests to me it's something to do with the font stack — maybe you're not getting the "bold" + "italic" font and safari is automatically creating one while chrome is not? It seems unlikely to be a pkgdown issue, so unfortunately you'll need to debug this on your own.

**Comment by samuel-marsh** [comment]
Ya something weird going on it seems.  Appreciate you taking time to respond!!
