### ISSUE TITLE
Duplicated reference pages

### ISSUE THREAD

**Issue by dmurdoch** [r-lib/pkgdown#1916]
Package `rgl` has a single help page documenting five different functions.  The `_pkgdown.yml` entries are separate:

```
- subtitle: Primitive shapes
- contents:
  - points3d
  - lines3d
  - segments3d
  - triangles3d
  - quads3d
```

but in fact there's just one page referenced.  When I did the last release of `rgl` back in August, the reference page combined all of these into one entry.  See https://dmurdoch.github.io/rgl/reference/index.html , which has

```
Primitive shapes
--
points3d() lines3d() segments3d() triangles3d() quads3d() | Add primitive shape

```

Using today's devel build of `pkgdown`, I get duplicated entries.  See https://dmurdoch.github.io/rgl/dev/reference/index.html , which has

```
Primitive shapes
--
points3d() lines3d() segments3d() triangles3d() quads3d() | Add primitive shape
points3d() lines3d() segments3d() triangles3d() quads3d() | Add primitive shape
points3d() lines3d() segments3d() triangles3d() quads3d() | Add primitive shape
points3d() lines3d() segments3d() triangles3d() quads3d() | Add primitive shape
points3d() lines3d() segments3d() triangles3d() quads3d() | Add primitive shape
```

It is recognizing the duplication by putting all the function names on each line, but forgetting to remove the unnecessary copies.

**Comment by dmurdoch** [comment]
By bisection, this appears to have originated in commit 705ff7c650bb1c7d46d3 back on Sept 1.

**Comment by hadley** [comment]
This is #1875 too, I think?
