### ISSUE TITLE
TOC active highlighting jumps items

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1919]
It's more a remark than a bug report, at least I think so. On e.g. https://pkgdown.r-lib.org/dev/reference/build_tutorials.html (where some items from the TOC don't have much content) when scrolling down on a large screen, "arguments" is never highlighted, it's either "Usage" or "YAML config".

**Comment by hadley** [comment]
Yeah, I don't there's anything we can do about that — the sections just aren't long to ever be detected as "active".
