### ISSUE TITLE
Copy button in Usage sections

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1920]
On e.g. https://pkgdown.r-lib.org/dev/reference/build_site.html the copy-paste button is above the code chunk. Is this expected?

Since the header is in the div "hasCopyButton", a side-effect is that the code remains available in reader mode.

**Comment by hadley** [comment]
And missing button in https://pkgdown.r-lib.org/dev/reference/test-verbatim.html (first block generated from `\preformatted`)

**Comment by hadley** [comment]
Looks like an interaction between `pre()` and the expectations of `tweak_reference_highlighting()`
