### ISSUE TITLE
Tabset + asis option

### ISSUE THREAD

**Issue by SESjo** [r-lib/pkgdown#1926]
I'm not sure if that's an issue or just not the right way to do it, but since tabset now works in vignettes (thanks @maelle), I leave that here (feel free point me elsewhere!)
When trying to automatically create tabset using `results='asis'` option, it works well, but it also adds a tab named as the code itself... I'm not sure I explain it well, so using the [basic example package](https://github.com/jonkeane/simple-package) made by @jonkeane, you can see in the vignette what's happening:
![image](https://user-images.githubusercontent.com/7326661/143953683-f38bd77e-0487-4409-8089-8ccecec84bfd.png)
Source code: https://github.com/SESjo/simple-package/blob/main/vignettes/a-vignette.Rmd
Website: https://sesjo.github.io/simple-package/articles/a-vignette.html

**Comment by hadley** [comment]
Use `echo = FALSE`?

**Comment by SESjo** [comment]
I could have sworn I tested that... but apparently not! Thanks for the solution :)
