### ISSUE TITLE
Autolinking of functions not working?

### ISSUE THREAD

**Issue by samuel-marsh** [r-lib/pkgdown#1938]
Hi,

I'm having small issue with the autolinking for function calls on the website of the package the functions are from.  According to pkgdown [autolinking article](https://pkgdown.r-lib.org/articles/linking.html) it seems that bare function calls should be auto linked.
i.e. from the .Rmd:
https://github.com/r-lib/pkgdown/blob/3e17275dfe27b1176d9cb596f679c23808d7b3d7/vignettes/linking.Rmd#L20-L24

However, it seems when my pkgdown site builds it only creates autolinks within R code chunks and not text outside the chunks.
See example here:
https://samuel-marsh.github.io/scCustomize/articles/Iterative_Plotting.html

.Rmd file is obviously linked but example of relevant text section I'm referring to looks like this:
https://github.com/samuel-marsh/scCustomize/blob/f9fc7697dd05af0dc4208949fe0f438f52e1c988/vignettes/Iterative_Plotting.Rmd#L48-L50

R chunks work though (even when code not actually run).
From the sme .Rmd/Vignette: 
https://github.com/samuel-marsh/scCustomize/blob/f9fc7697dd05af0dc4208949fe0f438f52e1c988/vignettes/Iterative_Plotting.Rmd#L72-L75

I feel like maybe I'm missing something really simple but any help would be appreciated!

Thanks!
Sam

Same issue with both pkgdown 1.6 and 2.0.0 builds.  Site currently built with 2.0.0

**Comment by maelle** [comment]
Does adding the URL to the config file fix the problem? https://github.com/samuel-marsh/scCustomize/pull/11

Cf https://pkgdown.r-lib.org/reference/pkgdown_sitrep.html

**Comment by hadley** [comment]
What do you expect to be linked that isn't?

**Comment by hadley** [comment]
(You don't have `()` on the functions calls, which is required for auto-linking to work)

**Comment by samuel-marsh** [comment]
@hadley oh of course.  I knew I was missing something simple.  Thanks!!
