### ISSUE TITLE
Korean translations 

### ISSUE THREAD

**Issue by mrchypark** [r-lib/pkgdown#1944]
I got news pkgdown version 2.0.0 has translations.

Congratulation!

how about Korean?(lang: kr)

I can start.

**Comment by hadley** [comment]
That would be lovely, thanks! The translation tooling is a bit in flux, so I hope you don't mind being a bit of guinea pig — but any feedback you have will help make this process easier for future translators.

You'll need to first get the dev version of potools and pkgload:

```R
devtools::install_github("MichaelChirico/potools")
devtools::install_github("r-lib/pkgload")
```

Then read the intro to potools for translators: https://michaelchirico.github.io/potools/articles/translators.html

Next you can run `potools::po_create("kr")` and fill in the translations in `po/R-kr.po`.

To check your work, you can add `lang: kr` to `_pkgdown.yml` then run:

```R
potools::po_compile()
devtools::load_all()
build_home() # or build_site()
```

That will build a local Korean version of the pkgdown site which should open automatically in your browser.
