### ISSUE TITLE
Search seems to lack the package name in the url

### ISSUE THREAD

**Issue by urswilke** [r-lib/pkgdown#1945]
Thank you for the update to 2.0.0!

I already updated one of my packages to use the new version, which was super easy:

https://urswilke.github.io/ggbenjamini/

It seems that in the search bar, the urls of the found results lack the package name, i.e.
when I, for instance, search for "bezier" and click on the first result, I get a 404, pointing to 

https://urswilke.github.io/reference/df_bezier_skeleton.html?q=bezier#null

which should be

https://urswilke.github.io/ggbenjamini/reference/df_bezier_skeleton.html?q=bezier#null

if I understand correctly.

**Comment by maelle** [comment]
:wave: @urswilke 

Search needs the package URL to be in the configuration: https://github.com/urswilke/ggbenjamini/pull/1 (source https://github.com/r-lib/pkgdown/blob/953a87771f74e405f2e648750b1b74db1806770a/R/build-search-docs.R#L115)

**Comment by urswilke** [comment]
Thank you for your super quick help!

Works like a charme now.
