### ISSUE TITLE
build_news needs specially formatted NEWS.md

### ISSUE THREAD

**Issue by rmflight** [r-lib/pkgdown#1947]
In pkgdown 1.6.1, `build_news` rendered fine with any kind of heading. As in I could have NEWS.md containing:

```
# v 0.0.2

* more bugs!

# v 0.0.1

* bugs fixed
```

However, as of v 2.0.1, that seems to have changed. The above contents in NEWS.md will render an empty page. Instead, it has to be formatted like this in NEWS.md:

```
# packageName 0.0.2

* more bugs!

# packageName 0.0.1

* bugs fixed
```

I'm not sure how many other people were using a simpler format of NEWS.md as I was, but it would be nice if the docs or vignette for `bulid_news` had more information on the required formatting.

**Comment by maelle** [comment]
What also doesn't work is having all h2. Maybe it should work.

**Comment by maelle** [comment]
#1967

**Comment by Al-Murphy** [comment]
Hey! I ran into what I think is the same issue with a GHA check on my Bioconductor R package: https://github.com/neurogenomics/MungeSumstats/runs/4522582120?check_suite_focus=true

Is a fix likely to be released soon or is there a work around for time being? I'm constricted since Bioconductor enforces standards on the NEWS file

**Comment by kevinushey** [comment]
I ran into this too with reticulate: https://raw.githubusercontent.com/rstudio/reticulate/main/NEWS.md

```
> pkgdown::build_news()
-- Building news ----------------------------------------------------------------------
Error: Invalid NEWS.md: bad nesting of titles
```

Presumedly because these are H2 rather than H1 headers.

**Comment by privefl** [comment]
I'm having a similar issue, where some headers do not render.

E.g. https://github.com/privefl/bigsnpr/blob/e72fa27b7bb4486b542505c46454ffcd21e5fa18/NEWS.md?plain=1#L71-L73 in https://github.com/privefl/bigsnpr/blob/e72fa27b7bb4486b542505c46454ffcd21e5fa18/docs/news/index.html#L155-L160.

Problem is still there after updating to latest GitHub version of {pkgdown}.

**Comment by maelle** [comment]
@privefl that header is for "bigsparser" but the package is "bigsnpr" hence its not being recognized.

Side note: in general it's better to open a new issue.

**Comment by privefl** [comment]
Yes, but I want to also show some important new releases of another package, of which my package is very dependent on.
I am pretty sure this was working before v2.

**Comment by privefl** [comment]
Should I expect this not to be fixed? (i.e. working as with v1.6.1)

**Comment by hadley** [comment]
@privefl you seem to expect a special case that was only ever supported by accident and we don’t plan to support going forward.
