### ISSUE TITLE
How to update the site for released version of a package

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#1950]
I'm using

```
development:
  mode: auto
```

more often these days, which means there's two version of the site, e.g. one for the released version of the package https://gmailr.r-lib.org and another for the development version of the package https://gmailr.r-lib.org/dev/.

But sometimes you need to update the released site, even though the package version in current source has already advanced to a development version. My most recent example was needing to backport some documentation changes and pkgdown config fixes to gmailr's released site.

This issue is a reminder to us to document how to do this.

**UPDATE**: I gradually realized that our existing pkgdown GHA workflow is capable of doing this. You just need to create a branch that reflects the source state you want to pkgdown-render from ~and push a tag pointing to that ref. I'm going to delete or hide the notes about my journey to this realization~. *Update: read on for what to do with this branch.*

**Comment by jennybc** [comment]
I've ended up doing this several more times and decided to use more proper Git methods.

Basic idea: check out the `gh-pages` branch into a Git worktree.

<https://git-scm.com/docs/git-worktree>

Key idea is in this example there:

```
$ git worktree add -b emergency-fix ../temp master
$ pushd ../temp
# ... hack hack hack ...
$ git commit -a -m 'emergency fix for boss'
$ popd
$ git worktree remove ../temp
```

---

I used a non-RStudio terminal for work in `gh-pages` and kept RStudio focused on `main` or another temporary branch.

### Checkout `gh-pages` locally

FYI I generally don't have a local `gh-pages` branch.

In a terminal, with working directory set to the relevant package (vroom, in this example):

```
git worktree add ~/tmp/vroom-gh-pages gh-pages
cd ~/tmp/vroom-gh-pages
git pull
```

The `git pull` was necessary because I'd actually made a commit on `main`, causing a commit on `gh-pages` *after* the initial `git worktree add` call. In any case, it can't hurt to `git pull`.

### Go back in time to the CRAN release

Here I work in a terminal in RStudio, in the package's project (still vroom in this example).

```
git checkout -b update-pkgdown-1-5-7 v1.5.7
git cherry-pick bd5e87f92006ab0932e0fc7aeb91d011665ceb4d
```

Substitute the tag of the most recent released version and change the branch name accordingly.
The `git cherry-pick` stands for any and all fixups you want to apply.
In this case, it was all isolated in a single commit, that only touched `_pkgdown.yml`.

### Re-build the site for the CRAN release

Here I'm in the R Console in RStudio, in the package's project.
`dest_dir` is the directory in which you've checked out the `gh-pages` worktree.

```r
dest_dir <- "~/tmp/vroom-gh-pages/"
pkgdown::build_site_github_pages(
 dest_dir = dest_dir,
 new_process = TRUE,
 clean = TRUE,
 install = TRUE
)
```

I then see lots of messages like this, but at this point, I think they are a false alarm (??):

```
Warning messages:
1: Missing images in '/Users/jenny/rrr/vroom/MAINTENANCE.md': 'logo.png'
ℹ pkgdown can only use images in 'man/figures' and 'vignettes'
2: Missing images in '/Users/jenny/rrr/vroom/LICENSE.md': 'logo.png'
ℹ pkgdown can only use images in 'man/figures' and 'vignettes'
3: Missing images in 'README.md': 'logo.png'
ℹ pkgdown can only use images in 'man/figures' and 'vignettes'
```

As evidence, the vroom [LICENSE](https://vroom.r-lib.org/LICENSE.html) looks fine to me, i.e. I see the logo.

### Update `gh-pages` locally

Here we're working in the non-RStudio terminal, still on the `gh-pages` worktree.

Have a look around, at the diffs and then stage it all:

```
git status
git add -A
```

In the vroom case, for some reason a GIF was being deleted that seems necessary, so I unstaged that deletion:

```
git reset -- taylor.gif
```

Commit and push!

```
git commit -m 'Manually update released site v1.5.7'
git push
```

### Clean up

In the non-RStudio terminal, where you're working on the `gh-pages` worktree, switch back to the previous working directory (or at least some *other* working directory) and then delete the worktree:

```
cd -
git worktree remove ~/tmp/vroom-gh-pages
```

If you have chosen to not stage all the changes (as I did when I retained `taylor.gif`), you might need to force removal:

```
git worktree remove --force ~/tmp/vroom-gh-pages
```

In RStudio, check out your default branch.
You could delete the time-travel branch (`update-pkgdown-1-5-7` in this example) at this point or leave it around for a while, in case you need to do another fixup of the released site.
You almost certainly want to delete the local `gh-pages` branch.

**Comment by jennybc** [comment]
Another reflection: you'll have to decide how much to worry about whether all other relevant packages are at the "correct" version in your local library. For tidyverse / r-lib maintainers, specifically, you should probably make sure `tidyverse/tidytemplate` is up-to-date 😬

**Comment by jennybc** [comment]
As I refined my process, I realized it would be best to build the updated site on GHA. As I thought about what such an action needed to do, I realized our existing action is already equipped for exactly this scenario 🙈

So **THAT** is what we need to document!

```yaml
on:
  push:
    branches: [main, master]
    tags: ['*']
```

The `tags` part of of the workflow trigger is why this already works. It also means that anyone who doesn't realize this could rebuild and deploy their (dev?) site unintentionally, just by pushing a tag. It's possible we should make the triggering `tags` a bit less general and adopt some sort of naming convention for tags meant to tickle pkgdown.

---

Create a branch based on the most recent CRAN release. This example is from vroom.

```
git checkout -b update-pkgdown-1-5-7 v1.5.7
git cherry-pick bd5e87f92006ab0932e0fc7aeb91d011665ceb4d
```

Substitute the tag of the most recent released version and change the branch name accordingly.
The `git cherry-pick` stands for any and all fixups you want to apply.

Push this branch to GitHub.

Create a tag at `HEAD` of this branch and push it too.

```
git tag pkgdown-update-released-site
git push origin pkgdown-update-released-site
```

This will trigger our pkgdown GHA and, since the version in `DESCRIPTION` will be recognized as a release, it will rebuild and deploy the released site.

**Comment by hadley** [comment]
I'm not sure we want to encourage people to use tags in this way; it feels like using a side-effect of making a tag. Maybe we can add some other trigger?

We definitely should restrict the default tag building: https://github.com/r-lib/actions/issues/450

**Comment by jennybc** [comment]
This discussion unfolded further in https://github.com/r-lib/actions/issues/450 and https://github.com/r-lib/actions/pull/451.

The end result is that our pkgdown GHA workflow now looks more like this:

```
on:
  push:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:
```

The `release` section handles "normal" releases (assuming they happen in chronological order).

`workflow_dispatch` gives us a very flexible manual trigger. As described in https://github.com/r-lib/actions/issues/450#issuecomment-987257297, you can trigger a released site rebuild from a branch from the browser. With an API call, you trigger a released site rebuild from a branch or a tag. We could build `workflow_dispatch` out a bit more with a wrapper function and/or formal inputs.

**Comment by hadley** [comment]
Given the changes to the action, does pkgdown need to do anything?

**Comment by hadley** [comment]
Hmmm maybe we need a "publishing" vignette that could cover this (and more). I won't work on it for the next patch release, but we should do at some point in the future.

**Comment by jennybc** [comment]
Sounds good. I feel like vignettes are basically decoupled from the release cycle anyway, esp. for a web-oriented package.
