### ISSUE TITLE
Support for Algolia with Boostrap: 5

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/pkgdown#1960]
I want to use `boostrap: 5` and Algolia at the same time because it gives more context to the search (see below). In the [vignette](https://pkgdown.r-lib.org/articles/search.html#bootstrap-3-algolia), it seems like these two can't be used together. Is it possible to make this happen or was there a deliberate decision not to support this?

![Screenshot 2021-12-08 at 22 30 55](https://user-images.githubusercontent.com/10477073/145287368-3cb4c892-f17f-4757-bed5-9ba5082db606.png)
![Screenshot 2021-12-08 at 22 30 38](https://user-images.githubusercontent.com/10477073/145287415-8f6aacdd-4e1f-4fa5-a9c1-62ee2cc7a49a.png)

**Comment by hadley** [comment]
It was a deliberate decision based on the development time available to us. Given the relatively limited usage of the algolia search, it's probably unlikely this will ever climb up high enough on my to do list that I'll work on it.
