### ISSUE TITLE
Error : Didn't recognize Bootstrap version: 5

### ISSUE THREAD

**Issue by erikarasnick** [r-lib/pkgdown#1962]
I installed the most recent version of pkgdown (2.0.1) and tried to run `build_site()` and got the following error: 

`
Error : Didn't recognize Bootstrap version: 5 
`

I have reproduced this error in a minimal package [here](https://github.com/erikarasnick/testpackage). 

Steps I took:
1. created this package with `usethis::create_package("~/desktop/testpackage")`
2. created one `.R` file. 
3. ran `pkgdown::build_site(new_process = FALSE, preview = FALSE)` which worked fine but used Bootstrap 3. 
here is a subset of the output: 
`
Copying '../../Library/R/4.0/library/pkgdown/BS3/assets/bootstrap-toc.css' to 'bootstrap-toc.css'
Copying '../../Library/R/4.0/library/pkgdown/BS3/assets/bootstrap-toc.js' to 'bootstrap-toc.js'
Copying '../../Library/R/4.0/library/pkgdown/BS3/assets/docsearch.css' to 'docsearch.css'
Copying '../../Library/R/4.0/library/pkgdown/BS3/assets/docsearch.js' to 'docsearch.js'
Copying '../../Library/R/4.0/library/pkgdown/BS3/assets/link.svg' to 'link.svg'
Copying '../../Library/R/4.0/library/pkgdown/BS3/assets/pkgdown.css' to 'pkgdown.css'
Copying '../../Library/R/4.0/library/pkgdown/BS3/assets/pkgdown.js' to 'pkgdown.js'
`
4. I want to use BS5, so I tried running `usethis::use_pkgdown` get the the `.yaml` file with
`url: ~
template:
  bootstrap: 5`

5. Ran `pkgdown::build_site(new_process = FALSE, preview = FALSE)` and got this output

`-- Installing package into temporary library ----------------------------------------------------------------------
== Building pkgdown site ==========================================================================================
Reading from: '/Users/RASV5G/Desktop/testpackage'
Writing to:   '/Users/RASV5G/Desktop/testpackage/docs'
-- Initialising site ----------------------------------------------------------------------------------------------
Copying '../../Library/R/4.0/library/pkgdown/BS5/assets/link.svg' to 'link.svg'
Copying '../../Library/R/4.0/library/pkgdown/BS5/assets/pkgdown.js' to 'pkgdown.js'
Error: Didn't recognize Bootstrap version: 5
`

**Comment by maelle** [comment]
Thanks for the super precise bug report! I think it's because pkgdown is lacking a minimal version for bslib. Can you please try re-installing bslib?

**Comment by erikarasnick** [comment]
Just wanted to give the update that updating bslib worked for me! Thanks!
