### ISSUE TITLE
Easy way to generate "other" section for references

### ISSUE THREAD

**Issue by mikeroswell** [r-lib/pkgdown#1964]
Trying to set up the references section, and unsure what to add in the _pkgdown.yml file so the references section is comprehensive without explicitly listing all the functions that aren't categorized elshewhere (see e.g. [https://stackoverflow.com/q/45886789/8400969](https://stackoverflow.com/q/45886789/8400969). Would be great to have a user-friendly way to have a catchall for exported functions not listed elsewhere in the reference!

**Comment by hadley** [comment]
We now have `check_pkgdown()` to list all the functions that you're missing; so I think fixing this is less important than when it was filed.
