### ISSUE TITLE
`Links` section title is cropped

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgdown#1975]
https://rlang.r-lib.org/index.html currently looks like this:

<img width="429" alt="Screenshot 2021-12-21 at 16 23 22" src="https://user-images.githubusercontent.com/4465050/146954920-bcdaf923-70c1-493f-8b7d-33a1425bce03.png">

Maybe a tidytemplate issue?

**Comment by hadley** [comment]
Yeah, and it's already filed 😄
