### ISSUE TITLE
how about support global site?

### ISSUE THREAD

**Issue by mrchypark** [r-lib/pkgdown#1979]
for example, r-pkg.io/<github-username>/<reponame-is-package-name>.

This is a common method of collecting and providing information about websites built with pkgdown.

I inspired go.dev

they have no central repository like cran but central doc site.

R have some central doc site but not like pkedown.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for pkgdown: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
