### ISSUE TITLE
False warning for missing images

### ISSUE THREAD

**Issue by BartJanvanRossum** [r-lib/pkgdown#1980]
Building the website for https://github.com/Biometris/statgenSTA/tree/develop using the series of commands below gives me this warning.
_Missing images in 'README.md': 'reference/figures/README-layoutPlot-1.png', 'reference/figures/README-mapPlot-1.png', 'reference/figures/README-boxPlot-1.png', 'reference/figures/README-scatterPlot-1.png', 'reference/figures/README-basePlot-1.png', 'reference/figures/README-spatialPlot-1.png'
i pkgdown can only use images in 'man/figures' and 'vignettes'_ 

The 'missing' images mentioned are the ones that we just created by the build_readme() command and they are all present in man/figures. The website looks fine, and the images are included, so this warnings seems redundant. I really don't know at all what triggers it.

I tried the CRAN version of pkgdown and the main branch from github, but the warnings are the same. 

```r
devtools::build_readme()
pkgdown::clean_site()
pkgdown::build_site()
```

This seems somewhat related to #1943, however seems about including images directly from files whereas my images are generated using plot functions.

**Comment by hadley** [comment]
Same as #1977
