### ISSUE TITLE
Depends on withr >= 2.4.0

### ISSUE THREAD

**Issue by ValValetl** [r-lib/pkgdown#1982]
## Issue
pkgdown fails to work if a version of the package `withr` is installed which does not export the function `local_seed` as it is called in function `examples_env`. See [this changelog](https://github.com/r-lib/withr/releases/tag/v2.4.0). 
## Fix
This could be fixed by adding `withr (>= 2.4.0)` to the DESCRIPTION file.

**Comment by hadley** [comment]
Do you want to do a PR?
