### ISSUE TITLE
doi: auto-linkage breaks markdown links

### ISSUE THREAD

**Issue by ms609** [r-lib/pkgdown#1983]
My R package contains a [README.md](https://github.com/ms609/Ternary#readme) file with the string
`doi:[10.5281/zenodo.1068996](https://dx.doi.org/10.5281/zenodo.1068996)`, formatted as necessary for the link to resolve in the README page on GitHub.

But when this page is [rendered by pkgdown](https://ms609.github.io/Ternary/dev/), I see:

[doi:\[10.5281/zenodo.1068996](https://doi.org/[10.5281/zenodo.1068996)](https://dx.doi.org/10.5281/zenodo.1068996).

Apparently the `[` is being interpreted as part of a DOI and pkgdown is trying to auto-link it.

Could the regexp used to auto-link DOIs be expanded to be more precise, e.g. `doi:10\.\d+`?

**Comment by hadley** [comment]
Minimal reprex:

```R
xpath_xml(
  markdown_text("doi:[10.5281/zenodo.1068996](https://dx.doi.org/10.5281/zenodo.1068996)"),
  "//p"
)
```

...

The problem goes away when I remove the `+autolink_bare_uris` option to pandoc, so I think this is really outside of the control of pkgdown. I'd recommend hyperlinking the whole thing so it doesn't look like a uri (i.e. `doi:`)
