### ISSUE TITLE
Add Danish language option

### ISSUE THREAD

**Issue by LDalby** [r-lib/pkgdown#1985]
Hi and happy New Year!

I can see from the blog post on the release of pkgdown 2.0.0 that translations are now possible. I'd like to add Danish as an option since this would be very handy for some of our internal work at AU. 

Could you point me in the right direction for this?

**Comment by hadley** [comment]
Sure! Thanks for working on this 😄 The translation tooling is a bit in flux, so you'll need to start by getting the dev version of potools and pkgload:

```R
devtools::install_github("MichaelChirico/potools")
devtools::install_github("r-lib/pkgload")
```

Then read the intro to potools for translators: https://michaelchirico.github.io/potools/articles/translators.html

Next you can run `potools::po_create("dk")` and fill in the translations in `po/R-dk.po`.

To check your work, you can add `lang: dk` to `_pkgdown.yml` then run:

```R
potools::po_compile()
devtools::load_all()
build_home() # or build_site()
```

That will build a local Korean version of the pkgdown site which should open automatically in your browser.

**Comment by LDalby** [comment]
A Korean version? I certainly hope not 😉 

I'll see if I can get this going asap. Thanks for the help so far.

**Comment by LDalby** [comment]
Right, this is done now.
I guess you'd like the PR to only contain the `R-dk.po` file right?

**Comment by hadley** [comment]
@LDalby whatever is easiest for you.
