### ISSUE TITLE
Improve error message "Can't find url"?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#1986]
Error that happens on a package with e.g. one article and no URL in the configuration (the redirects building fails).

**Comment by hadley** [comment]
Can you give a bit more context?

**Comment by maelle** [comment]
Steps to reproduce

* Create a package via `usethis::create_package()`.
* Add an article to it via `usethis::use_article()`.
* Try running `pkgdown::build_site()`.

Then as redirects are built for all articles since #1911, and there's no configuration file therefore no URL, the error from https://github.com/r-lib/pkgdown/blob/b273ac6e9057e5c5abcf45730e8f8770de0e890c/R/build-redirects.R#L16 is "Can't find URL". The user should therefore create a configuration file, and add the website URL to it.

I am actually not sure where things should be clarified. Had the steps included `usethis::use_pkgdown()`, the error message would mention the configuration file (therefore making the error message a bit clearer).

* Should something be done/messaged/documented at the `usethis::use_article()` stage.
* Should some warning be added to the docs of `build_articles()`.
* Should `pkgdown_field()` add something like "nor any pkgdown configuration file" when there's no configuration file, 
* Should `build_redirects()` error differently.

Or maybe it's just a too niche edge case! I got this error when trying to locally build the pkgdown website of a package whose website is built externally, if I remember correctly, hence the absence need for an URL in a pkgdown configuration.

**Comment by hadley** [comment]
I think we could make `article_redirects()` return `NULL` if the `url` isn't set. I think that's fine because it implies that the website probably hasn't been published and hence the redirects aren't needed.
