### ISSUE TITLE
tweaks to default pkgdown site layout?

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pkgdown#1989]
These are obviously subjective, so please feel free to discard these if you think they're not really an improvement or not worth doing.

Using `pkgdown`'s own page as an example...

<img width="1328" alt="Screen Shot 2022-01-04 at 4 11 14 PM" src="https://user-images.githubusercontent.com/1976582/148140740-11dad5da-ab02-451b-bced-0224a22c5e0a.png">
 
- The alignment of the package name + package version could be improved. (I would prefer to see the package name + version vertically aligned.)
- The navbar list items could use some extra padding, and spacing away from the package name + version.
- The vignette text could be separated a little bit more from the vignette title header.

For example:

<img width="831" alt="Screen Shot 2022-01-04 at 4 16 58 PM" src="https://user-images.githubusercontent.com/1976582/148141188-5b16cf48-437c-4b23-a455-5609154c359a.png">

Obviously users could make these changes themselves, but IMHO these changes might be worth considering for the default layout.

**Comment by hadley** [comment]
I'll take a look — the main challenges are making the default appearance look better without harming the ability to customise as needed and my css skills.

**Comment by hadley** [comment]
1. Looks like `align-items: baseline;` will do it
2. Could add `class="me-1"` to each `li.list-item` in HTML or `gap: 0.25rem` to `.navbar-nav` in CSS, but it doesn't feel that cramped to me and horizontal space is at a premium in the navbar (especially when folks at extra items), so unless you feel strongly, I'd prefer to leave as is. (You can pretty easily customise for your own site with `pkgdown/extra.scss` if needed).
3. Change `ms-2` to `ms-3`
