### ISSUE TITLE
Should H1 in articles be added to TOC

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2004]
Example https://github.com/maelle/blabla/blob/main/vignettes/blop.Rmd
Website https://maelle.github.io/blabla/articles/blop.html

It seems to be a regression as the TOC on https://dplyr.tidyverse.org/articles/base.html looks fine

**Comment by maelle** [comment]
Current selection https://github.com/r-lib/pkgdown/blob/e25bd0bb6a604ecc60d704c7154f291afbf0dd7b/inst/BS5/assets/pkgdown.js#L9

**Comment by DavisVaughan** [comment]
I think this is also the reason for this issue https://github.com/tidyverse/tidytemplate/issues/72

**Comment by hadley** [comment]
But you don't want "blop" added to the TOC?
