### ISSUE TITLE
Cannot modify width of code-chunks

### ISSUE THREAD

**Issue by strengejacke** [r-lib/pkgdown#2011]
From the news file:

> You can globally set the width of code output (in reference and articles) with
> 
> code:
>  width: 50

I guess this needs to be defined in the yaml header, or _pkgdown.yaml? But no matter where I add those lines (I would like code chunks to have vertical scroll bars, so I tried width 100 and 120), code lines are always wrapped at the same length. Is this a bug or did I add the code-width definition to the wrong place?

**Comment by hadley** [comment]
This is unrelated to vertical scroll bars; it just sets the `width` option in R. The patch release (coming out shortly) reverts the change to using wrapping and moves back to scroll bars.

**Comment by strengejacke** [comment]
Great, thanks!
