### ISSUE TITLE
Static html files

### ISSUE THREAD

**Issue by royfrancis** [r-lib/pkgdown#2013]
Is there a location for static html files that will be copied over to the **docs/** folder? I don't know if I can call them vignettes, but they are not actively rendered from Rmd or md. They are static html files. And I don't really want them in the R package, just on the documentation site.

I have tried placing it in **vignettes/web**, but it doesn't seem to be getting copied to **docs/**.

**Comment by maelle** [comment]
Only commenting with workarounds as I suspect this out-of-scope for what pkgdown does.

You might want to check out "articles" in case you don't know about them, they're like vignettes but not included in a built package. Cf [`usethis::use_article()`](https://usethis.r-lib.org/reference/use_vignette.html).

If you really want to include your ready-made HTML files as is and if you build your website with e.g. [GitHub Actions](https://usethis.r-lib.org/reference/github_actions.html), you could

* have the static HTML files in a folder called e.g. `my-html`;
* add `my-html` to `.Rbuildignore`;
* add a step in the GitHub Actions workflow copying the files to the website destination folder (docs or docs/dev).

Now they won't have the footer / navbar so you might want to generate them from Rmd/md instead.

**Comment by maelle** [comment]
Also note that if you add pages to the website outside of what pkgdown does then the content of these pages won't be included in the sitemap nor the search index (what the search bar uses).

**Comment by hadley** [comment]
Yeah, I _think_ this is out of scope for pkgdown, but we do need #2064 to make sure that files you do copy in manually don't get deleted.
