### ISSUE TITLE
No longer possible to build a website with install=FALSE

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2019]
Because of https://github.com/r-lib/pkgdown/blob/f85cfa24fbf0c809c4ca9dbd23a53742165367cb/R/build-reference.R#L218 (that tries to load the package)

**Comment by maelle** [comment]
Noticed when writing tests with a non-existing package. :slightly_smiling_face:

**Comment by maelle** [comment]
The workaround I used was to also have `examples = FALSE`.

**Comment by hadley** [comment]
I'm pretty sure the intent here is that if you set `install = FALSE`, pkgdown assumes that you've installed the package some other way.
