### ISSUE TITLE
Institutional logo not rendered

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#2020]
I have the institutional logo indicated in `_pkgdown.yml`:

https://github.com/maialab/grantham/blob/091bd0b97cad9a1eaad26c88fdda0aa241b5a071/_pkgdown.yml#L13-L15

It is located in the source here: https://maialab.org/grantham/reference/figures/cintesis.svg.

And it is rendered on the right of my website rendered with pkgdown: https://maialab.org/grantham/index.html. In this specific page the logo is also rendered correctly in the footer. However, in the footer of any other pages it is not, e.g.:

- https://maialab.org/grantham/news/index.html
- https://maialab.org/grantham/reference/index.html
- https://maialab.org/grantham/reference/amino_acid_pairs.html

**Comment by maelle** [comment]
It is the same as #1996: you should use an absolute link, not a relative one, so that it might work from all pages. I've made a small PR https://github.com/maialab/grantham/pull/2

**Comment by maelle** [comment]
Related https://github.com/r-lib/pkgdown/pull/2021 :-)

**Comment by ramiromagno** [comment]
Thank you so much for the PR!
