### ISSUE TITLE
Search query highlighting no longer works

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2023]
pkgdown used to highlight (using mark.js) the search string used to find pages. Seems to have broken at some point.

https://pkgdown.r-lib.org/reference/build_site.html?q=build

(`build` should be highlighted everywhere on the page)

**Comment by maelle** [comment]
Good catch, thanks @jayhesselberth! I see the issue was introduced via #1918, I'll make a PR to update the JS (that still tries to find something in a div rather than in "main").
