### ISSUE TITLE
Create new `use_git_ignore_template` based on toptal.com (former gitignore.io)

### ISSUE THREAD

**Issue by kalaschnik** [r-lib/pkgdown#2027]
`usethis` may benefit a lot from the API provided by https://www.toptal.com/developers/gitignore

For example,
`use_git_ignore_template(c("linux", "macos", "windows", "r"))`, would translate to the API response of:
https://www.toptal.com/developers/gitignore/api/linux,macos,windows,r

As you see the response link, the entries of line 2 could be parsed and recycled if a users wants to modify this.

My usual .gitignore has the following pattern:
```
# my stuff
raw/
subjectdata/
token.R

# gitignore.io part (DO NOT MODIFY HERE USE use_git_ignore_template() to update the components below)
# Created by https://www.toptal.com/developers/gitignore/api/linux,macos,windows,r
# Edit at https://www.toptal.com/developers/gitignore?templates=linux,macos,windows,r

### Linux ###
*~

# temporary files which can be created if a process still has a handle open of a deleted file
.fuse_hidden*
# ...
```

**Comment by maelle** [comment]
:wave: @kalaschnik this is actually pkgdown repo. In any case you might be interested in https://docs.ropensci.org/gitignore/

**Comment by kalaschnik** [comment]
Yeah, sorry wrong repo 😬
