### ISSUE TITLE
Are `@return` sections being stripped of new lines?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#2029]
I have a `@return` section that looks like:

```r
#' @return
#' For `iv_merge()`, an iv with the same type as `x`.
#'
#' For `iv_replace_merged()`, an iv with the same type and size as `x`.
#'
#' For `iv_locate_merge_bounds()`, a two column data frame with `start` and
#' `end` integer columns.
#'
#' For `iv_locate_merge_groups()`, a two column data frame with a `key` column
#' containing the result of `iv_locate_merge_bounds()` and a `loc` list-column
#' containing integer vectors.
```

And in the `?iv_merge` Rd file it renders as:

<img width="832" alt="Screen Shot 2022-01-28 at 10 33 27 AM" src="https://user-images.githubusercontent.com/19150088/151575279-b222b3a6-444f-47dd-95ac-49c1ce8281e2.png">

but on the site I see:
<img width="839" alt="Screen Shot 2022-01-28 at 10 33 36 AM" src="https://user-images.githubusercontent.com/19150088/151575313-c23aec3c-3f0b-4230-babb-2d98e1ac42b8.png">

This is with bootstrap 5 but not with tidytemplate.

**Comment by maelle** [comment]
the function https://github.com/r-lib/pkgdown/blob/e2d5e2344f35783954dc15fff23bf8e6da39412f/R/rd-data.R#L90 returns the new lines as `\n`, maybe they should be converted to `<br/>` (or the function should create `<p>`). :thinking: 

Good that the workaround you found is linked from here, in the meantime. :grin:

**Comment by hadley** [comment]
Minimal reprex:

``` r
pkgdown:::value2html("
First para

Second para

Third para
")
#> [1] "<p>First para"  "Second para"    "Third para</p>"
```

<sup>Created on 2022-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Possibly introduced in #1777
