### ISSUE TITLE
Allow syntax highlighting to be disabled

### ISSUE THREAD

**Issue by matt-dray** [r-lib/pkgdown#2033]
Is it it possible to turn off syntax highlighting for a {pkgdown} site? [I asked this question in the RStudio Community](https://community.rstudio.com/t/remove-syntax-highlighting-from-pkgdown-site/127666/2) and @maelle suggested to raise an issue here.

I understand from the {pkgdown} docs that Bootswatch [themes can be added and tweaked](https://pkgdown.r-lib.org/articles/customise.html#bootswatch-themes), but I would like to remove highlighting from code blocks _entirely_. That would include places like the README and the 'usage' section of function definitions in the 'reference' section of the site.

Perhaps this could be possible as an option passed to _pkgdown.yml in [the style of `highlight: null` for a {bookdown} book](https://bookdown.org/yihui/rmarkdown/html-document.html#appearance-and-style)?

I'm asking for aesthetic reasons related to a package I'm building and understand that this may be low priority.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think we're unlikely to make this a priority. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
