### ISSUE TITLE
Enabling cross references and htmlwidgets together in >=v2.0.0

### ISSUE THREAD

**Issue by jplecavalier** [r-lib/pkgdown#2035]
The refactor of the `as_is` option in v2.0.0 broke the possibility of having htmlwidgets and custom output format used together (see https://github.com/r-lib/pkgdown/pull/1793#issuecomment-931752561).

I'm probably not the only one who used the `html_document2` format solely for having cross references in articles since this was discussed in #323.

Without including full support for custom format and htmlwidgets, would it be possible to implement a cross reference mechanism working together with htmlwidgets?

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I don't think it's possible — the supporting the two features individually is already complex, and supporting them together unfortunately seems like more trouble than it's worth. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄

**Comment by jplecavalier** [comment]
No problem, thanks for considering the issue!
