### ISSUE TITLE
Awkward formatting in "DBI specification" article

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#2037]
https://dbi.r-dbi.org/articles/spec

![image](https://user-images.githubusercontent.com/1741643/152423980-2595980f-30be-4156-b0b7-62ee51bbf49e.png)

This vignette is generated with a very unconventional way, so might be not representative. I'd appreciate any hints on how to fix the layout on my end.

**Comment by hadley** [comment]
The key problem is that the divs for each section somehow get the class `"container"`. If you remove that, the problem goes away. How are you making this vignette?

**Comment by hadley** [comment]
Still a problem today. Vignette source at https://github.com/r-dbi/DBI/blob/main/vignettes/spec.Rmd

**Comment by krlmlr** [comment]
Looks okay to me in Firefox now. What browser are you using, what is wrong with the display? https://dbi.r-dbi.org/articles/spec.html

The rendering process has changed, the contents are now essentially this Markdown file: https://raw.githubusercontent.com/r-dbi/DBI/a23c544adb11eebc4f3372e99177172f723cee23/vignettes/spec.md .

**Comment by hadley** [comment]
I still see the same problem as in your initial screenshot, i.e. `DBI: R Database Interface` and subheadings are indented. I'm using safari.

**Comment by krlmlr** [comment]
Right, the subheaders are indented, but they no longer overflow.

Confirming the "container" class as likely cause of this problem, also on Firefox (right-clicking "DBI: R Database Interface" -> Inspect, the outer element has this "container" class).

The vignette is now dead simple, a single "asis" chunk:

https://github.com/r-dbi/DBI/blob/453148fa5327356cd29e543eb49b472fc2d7144a/vignettes/spec.Rmd#L26-L28

This chunk reads an `.md` file from disk and prints it: https://github.com/r-dbi/DBI/blob/453148fa5327356cd29e543eb49b472fc2d7144a/vignettes/spec.md

Coud the "asis" chunk be the problem here? @maelle: can you please help?

**Comment by maelle** [comment]
Ok, planning to have a look tomorrow

**Comment by maelle** [comment]
Now suspecting Pandoc as it renders fine locally.

**Comment by maelle** [comment]
https://maelle.github.io/notdbi/articles/spec.html is fine :upside_down_face: (same source as the DBI vignette)

**Comment by maelle** [comment]
but these two workflows are using the same Pandoc version.

https://github.com/r-dbi/DBI/actions/runs/8505670650/job/23294557762

https://github.com/maelle/notdbi/actions/runs/8702331645/job/23866158124

**Comment by maelle** [comment]
knitr               1.45       2023-10-30 in  DBI

vs

knitr         1.46       2024-04-06 [1] RSPM in my reprex

@krlmlr could you please delete the actions cache for the DBI pkgdown workflow?

**Comment by krlmlr** [comment]
Looks good in dev: https://dbi.r-dbi.org/dev/articles/spec.html

I've pushed to the docs branch, now looks good on the main site too: https://dbi.r-dbi.org/articles/spec.html

Closing, please reopen if needed.
