### ISSUE TITLE
A place for RStudio addins?

### ISSUE THREAD

**Issue by hfrick** [r-lib/pkgdown#2038]
Would it be possible/a good idea to document addins on a pkgdown site, e.g., on the reference page?

**Comment by jayhesselberth** [comment]
Not sure what you mean by addins.

You can include arbitrary content in sites: https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files.

**Comment by hfrick** [comment]
I was thinking of the [addins for the RStudio IDE](https://rstudio.github.io/rstudioaddins/) and whether they (could) have a canonical place on a pkgdown site. I think that would increase their visibility.

**Comment by matt-dray** [comment]
Hi @hfrick, perhaps I'm misunderstanding, but I think exported RStudio Addin functions appear in the reference page by default, don't they? That was the case in [the pkgdown (v2.0.2) site](https://co-analysis.github.io/a11ytables/reference/index.html) for a package I've been developing.

**Comment by hadley** [comment]
Or #1899
