### ISSUE TITLE
Autolinking in README looks good on pkgdown but displays some html code on github

### ISSUE THREAD

**Issue by uriahf** [r-lib/pkgdown#2059]
Hi, I'm working on  a package and I want to display functions in the README file as part of a quick start section.

On pkgdown it looks great and the autolinking works:
https://uriahf.github.io/rtichoke/#naming-convention

But on github it shows some html code that is probably related:
https://github.com/uriahf/rtichoke#naming-convention

Original Code:
https://github.com/uriahf/rtichoke/blob/main/README.Rmd#:~:text=library(magrittr)-,tibble%3A%3Atribble(~%22Output%22%2C%20~%22Predictions%20and%20Outcomes%22%2C%20~%22Performance%20Data%22%2C,),-%60%60%60

What are my alternatives? Ideally the table on github should be identical to the table on pkgdown, but I'm not sure if that's possible.

**Comment by cderv** [comment]
Hi @uriahf, 

I think you have two different issues here: 

* You want to have function in README be autolink() like in **pkgdown**. **downlit** needs to be supported in `github_document()` and this is tracked in https://github.com/rstudio/rmarkdown/issues/2284 

* You are using **gt** to create a table, and this introduce in your markdown output some `<div>` and `<style>` component 
https://github.com/uriahf/rtichoke/blob/616f2446f178145a2bea50eb03f29132859012af/README.md?plain=1#L44
It seems you need to account for that in your README somehow - maybe https://github.com/rstudio/gt/issues/104 ?

I am not **gt** expert so you may also ask on their issue board. Or more generally, if you have some questions, do not hesitate to ask on https://community.rstudio.com

Hope it helps.

**Comment by cderv** [comment]
Yes that is the idea behind https://github.com/rstudio/rmarkdown/issues/2284 we just need some adjustment in different places to make this works.

**Comment by uriahf** [comment]
Sounds great, looking forward to it!
