### ISSUE TITLE
CSS class for version number in navbar doesn't have best contrast for some bootswatch themes

### ISSUE THREAD

**Issue by dchiu911** [r-lib/pkgdown#2061]
The default CSS class text-muted for the version number makes the text appear grey, which isn't the best contrast with the Cerulean bootswatch theme, for example.
```css
<small class="nav-text text-muted me-auto" data-bs-toggle="tooltip" data-bs-placement="bottom" title="">2.2.1</small>
```
Can we create this styling dynamically based on the theme with maybe different shades of grey?

**Comment by MLopez-Ibanez** [comment]
Or reverse fg/bg like in the classic themes, so it looks like: https://future.apply.futureverse.org/

**Comment by hadley** [comment]
I _think_ this is a buglet with the theme, so I'd suggest fixing it with (s)css and manually overriding the styling of `text-muted`.
