### ISSUE TITLE
packages with private dependencies

### ISSUE THREAD

**Issue by d-morrison** [r-lib/pkgdown#2074]
I'm trying to use `usethis::use_pkgdown_github_pages()` to build a pkgdown website for a package in a private repo; that package (let's call it "pkgA") depends on second package ("pkgB"), also in a private repo.  The `pkgdown` job in GitHub actions is failing, because the GH Actions job can't find the GitHub repo for "pkgB". Is there a way to get around this?

Due to the private setting on the repos, it's hard to provide a reprex for this, but if anyone has suggestions for how to make the problem reproducible, please let me know!

**Comment by maelle** [comment]
This probably depends on the scope of the GitHub Actions token? What's the error message? If my assumption is correct

- you'd need to create a GitHub Personal Access Token with access to both repos (probably the case for a PAT created for your account)
- save it as GitHub Actions secret e.g. as `GH_PAT`
- refer to it in the GHA workflow like in https://github.com/tbep-tech/github-backup/blob/42da24f815326a8ed77270865703fe1ed4da53eb/.github/workflows/archive.yaml#L20

Just to be sure, you want to have a public website but the source won't be public, correct? (GitHub pages websites are public, well at least without further customization)

Also note that you can ask such questions on community.rstudio.com :smile_cat:

**Comment by d-morrison** [comment]
That worked - thanks!!

Just for reference if anyone finds this thread in the future, I was trying to create a private GitHub Page (using an Enterprise-level account for my organization), and the error I was getting was:

```
 Error: Error: <callr_remote_error: Cannot install packages:
  * local::.: Can't install dependency [organization-name]/pkgB
  * [organization-name]/pkgB: Can't find GitHub repo [organization-name]/pkgB.>
```

**Comment by maelle** [comment]
Just a note that a PAT is less secure because of the greater access it has see point 5 in https://github.blog/2022-04-22-5-simple-things-every-developer-can-do-to-ship-more-secure-code/ (but I can't think of a workaround here, so hopefully the secret is safe :-) )
