### ISSUE TITLE
Can't parse alternative text for figure tag on multiple lines 

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2080]
Say the roxygen2 tags are

```r
#' @section The function output:
#' \figure{logo.png}{Package logo
#' blablablablablabla}
```

then the Rd is

```r
\figure{logo.png}{Package logo
blablablablablabla}
}
```

Which creates an error via

https://github.com/r-lib/pkgdown/blob/b273ac6e9057e5c5abcf45730e8f8770de0e890c/R/rd-html.R#L332

because `opt` has length 2.

Should

- pkgdown collapse `opt`?
- or roxygen2 do the parsing differently?

A workaround is to write alternative text on one line in the roxygen2 tags.

**Comment by maelle** [comment]
Reprex https://github.com/maelle/minirelter
pkgdown run https://github.com/maelle/minirelter/runs/6253919939?check_suite_focus=true

**Comment by hadley** [comment]
Should collapse `opt`, IMO.
