### ISSUE TITLE
https://pkgdown.r-lib.org/reference/build_home.html should say "even if listed in .Rbuildignore"

### ISSUE THREAD

**Issue by MLopez-Ibanez** [r-lib/pkgdown#2082]
https://pkgdown.r-lib.org/reference/build_home.html should say:

Extra markdown files in the base directory (e.g. ROADMAP.md) or in .github/ (e.g. CODE_OF_CONDUCT.md) are copied by build_home() to docs/ and converted to HTML _even if listed in .Rbuildignore_

**Comment by maelle** [comment]
For future reference #2081

**Comment by hadley** [comment]
You can only include those files in a valid package if they are listed in `.Rbuildignore`?

**Comment by MLopez-Ibanez** [comment]
> You can only include those files in a valid package if they are listed in `.Rbuildignore`?

I don't want the files to be included in the package nor the website, that is why I included them in `.Rbuildignore`. But I didn't know that pkgdown ignores what `.Rbuildignore` says. That's fine. I guess it makes sense in 99% of the cases that pkgdown does not follow `.Rbuildignore` and my use-case is the 1% who would like a way to exclude those files. I can live with that or move them somwhere where pkgdown will not find them.

But I didn't find any mention of `.Rbuildignore` in the docs. Hence the PR suggested by @maelle

**Comment by maelle** [comment]
Yes I was thinking adding that caveat somewhere, maybe "@details" of that doc page, wouldn't hurt.

**Comment by hadley** [comment]
It's a sufficiently rare edge case that I don't think it's really worth documenting because no one would know where to look for it.

**Comment by MLopez-Ibanez** [comment]
Works for me.
