### ISSUE TITLE
ragg_png device and python examples?

### ISSUE THREAD

**Issue by cboettig** [r-lib/pkgdown#2091]
Apologies I haven't been able to track this down to a more minimal example yet. When I have a vignette that includes python/matplolib chunks, e.g. https://github.com/eco4cast/EFIstandards/blob/d6696dea04dd1b746cb51a60e7434720a252b808/vignettes/logistic-metadata-example.Rmd#L202, 

pkgdown fails to render with the error: 

```
Quitting from lines 203-215 (logistic-metadata-example.Rmd) 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: ValueError: Format 'ragg_png' is not supported (supported formats: eps, pdf, pgf, png, ps, raw, rgba, svg, svgz)
```

It looks like pkgdown is hard-wiring in the choice of device? (https://github.com/r-lib/pkgdown/pull/1386) (at least I don't see how to swap this out).  I'm guessing the matplotlib plotting engine isn't compatible with the new device?

**Comment by cboettig** [comment]
I think is is related to #2067, i.e. I can avoid the error by setting `dev='png'` in the chunk options, but then pkgdown cannot find the image.  (though at least that is a warning rather than an error so pkgdown will still deploy).

**Comment by hadley** [comment]
@cboettig do you think you could make a minimal package that illustrates the problem? That'll make it faster for us to fix it when we're next working on pkgdown.

**Comment by cboettig** [comment]
@hadley good call, thanks.  https://github.com/cboettig/pkgdowntest/commit/c931f898f4beb87b894ebd4ce1dca208435419c0 should reproduce the error, e.g. as seen when enabling the GitHub CI action for pkgdown on the default 'new package' template with a single matplotlib plot in the vignette: https://github.com/cboettig/pkgdowntest/runs/6679106820?check_suite_focus=true#step:7:45

**Comment by hadley** [comment]
Thanks!

**Comment by hadley** [comment]
@cboettig wanted to confirm that this is still a problem for you before I dig into it again.

**Comment by cboettig** [comment]
I think we're all good; at least hasn't been a issue for me.
