### ISSUE TITLE
pandoc-fail.rmd does not fail

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2096]
https://github.com/r-lib/pkgdown/blob/main/tests/testthat/assets/pandoc-fail.Rmd

**Comment by maelle** [comment]
at least it does not fail for me locally which surely depends on the Pandoc version. :zany_face:

**Comment by hadley** [comment]
Oh funny, we were just talking about the opposite problem to this (vignettes that link to external images failing on CRAN because of the old pandoc there). From that discussion, the difference happened around pandoc 1.18.

**Comment by cderv** [comment]
Yes Pandoc 2.18 has now make this specific "resource not found" a warning by default, while it was previously an error preventing rendering when `--self-contained` was used.

You can call pandoc with `--fail-if-warnings` if you still want to produce an error in that case.

**Comment by hadley** [comment]
@cderv it looks like `--fail-if-warnings` has been around for a while so I think we can use it unconditionally.

**Comment by cderv** [comment]
@hadley correct, the CLI flag is here since Pandoc 2.0.
