### ISSUE TITLE
"cannot open the connection" issue when using child RMarkdown documents

### ISSUE THREAD

**Issue by jhelvy** [r-lib/pkgdown#2109]
This issue may be related to [this one](https://github.com/rstudio/learnr/issues/408).

I use several child RMarkdown documents that I reference in multiple articles in my package vignettes. I use the {here} package to generate the path to those files, like this:

````
```{r, child=here::here('man', 'rmdchunks', 'header.Rmd')}
```
````

I put all my chunks in a folder in `man/rmdchunks`.

This has always worked, but now I am getting the following error:

```
Quitting from lines 22-22 (/private/var/folders/76/nlsnjw657tjbphtcthmwvkqm0000gq/T/RtmpShD69g/man/rmdchunks/header.Rmd) 
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/private/var/folders/76/nlsnjw657tjbphtcthmwvkqm0000gq/T/RtmpShD69g/man/rmdchunks/header.Rmd': No such file or directory
```

I'm not sure why it can't find the path anymore. I'm using {pkgdown} version 2.0.3.

**Comment by jhelvy** [comment]
Okay, if I put my `rmdchunks` folder inside the `vignettes` folder and use all local paths, it works.

This will render the child RMarkdown doc:

````
```{r, child='rmdchunks/header.Rmd'}
```
````

I don't even remember why I had originally put all these child docs in the upper level `man` folder. I did this years ago for some reason, but I'll just put them local in the `vignettes` folder.

**Comment by cderv** [comment]
You should be able to use relative path 
````
```{r, child="../man/rmdchunks/header.Rmd"}
```
````

**Comment by jhelvy** [comment]
This works! 

I'm still puzzled why my solution using {here} stopped working. I've used that approach for years without fail. 

Out of curiosity I also tried using `file.path()` to make a local path to `/rmdchunks/header.Rmd` with my `rmdchunks` folder inside my `vignettes` folder like this:

````
```{r, child=file.path('rmdchunks', 'header.Rmd')}
``` 
````

But this too gets the same error. It seems only hard-coded paths are working. Maybe it was a change in how RMarkdown handles child paths?

**Comment by dmurdoch** [comment]
Your `file.path('rmdchunks', 'header.Rmd')` gives `rmdchunks/header.Rmd', but @cderv 's path was `../man/rmdchunks/header.Rmd`.  Those aren't the same thing...

**Comment by cderv** [comment]
> with my rmdchunks folder inside my vignettes folder like this:

Resources used in vignettes, and stored in `vignettes/` folder are not available by default during build. See R Manuals about writing vignette: https://rstudio.github.io/r-manuals/r-exts/Creating-R-packages.html#writing-package-vignettes

> When R CMD build builds the vignettes, it copies these and the vignette sources from directory vignettes to inst/doc. **To install any other files from the vignettes directory**, include a file vignettes/.install_extras which specifies these as Perl-like regular expressions on one or more lines. (See the description of the .Rinstignore file for full details.)

See also https://blog.r-hub.io/2020/06/03/vignettes/#overview-of-vignettes-states about this 

So it is possible that the `rmdchunks` folder is not available in the process. Not sure when you encountered the error. Storing in `man/` won't have this issue, to it works well, especially for rmd child you also want to use with roxygen for help page. 

>  It seems only hard-coded paths are working. Maybe it was a change in how RMarkdown handles child paths?

Computed paths or hard coded paths are working, as long as they are valid from within the vignette. Regarding using `here::here()`, this will create a absolute paths and sometimes this can lead to issue within Rmd files. Using relative paths is always better for Rmd file. `xfun::from_root()` is an alternative to `here::here()` that will return relative path by default. Maybe it helps here.

**Comment by jhelvy** [comment]
The `rmdchunks` folders seems to be available from within the `vignettes` folder during build, though this is probably poor practice. But I'm only seeing the hard paths work for local paths to folders inside `vignettes`, so `./rmdchunks/header.Rmd` works but `file.path('rmdchunks', 'header.Rmd')` fails. Neither are ideal though as all the chunks inside `rmdchunks` will also build. 

For now I'm going to keep the chunks in `man/rmdchunks` and use the `../man/` approach as that works just fine.
