### ISSUE TITLE
Reference section with only internal functions?

### ISSUE THREAD

**Issue by josherrickson** [r-lib/pkgdown#2135]
Aside from manually listing all internal functions, is there an automated way to define a section in the Reference that is only functions which have `@keywords internal`?

I was hoping that this would work:

```
- title: Internal Functions
- contents:
    - has_keyword("internal")
```
Nothing appears here, since `has_keyword` doesn't accept an `internal = TRUE` argument per https://pkgdown.r-lib.org/reference/build_reference.html?q=internal#topic-matching

**Comment by hadley** [comment]
It doesn't accept that argument because it never removes internal topics. But you might've been hitting #2129 which I just fixed.
