### ISSUE TITLE
`display: block` on `<table>` elements can cause table semantics to be dropped

### ISSUE THREAD

**Issue by glin** [r-lib/pkgdown#2140]
The Bootstrap 5 theme sets `display: block` on HTML `<table>` elements, which can cause accessibility issues for some browsers and screen readers that no longer interpret them as tables. I think there's something similar in the Bootstrap 3 theme as well.
https://github.com/r-lib/pkgdown/blob/5203a63f002405e99b8510debe809ff3d9f18b02/inst/BS5/assets/pkgdown.scss#L217-L220

These articles go into more detail on the issues with changing a table's `display` property:
https://www.tpgi.com/short-note-on-what-css-display-properties-do-to-table-semantics/
https://adrianroselli.com/2018/02/tables-css-display-properties-and-aria.html

The second article does mention that this problem is fixed in Chrome 80 as of February 2020, but not in Safari. From quick testing, I did find tables with `display: block` to be interpreted as tables in Safari 13, so maybe it's not an issue anymore. But this could still affect other browsers and older browser versions - I was able to reproduce the issue on the latest Android Chrome with TalkBack.

On my site, I'm adding a `display: table` override in `extra.css` to work around this:
```css
main table {
  display: table;
}
```
I'm not sure why `display: block` was originally added for tables, but it would be nice to find an alternative solution to what it was added for.

Here are some examples to reproduce this:
- https://dplyr.tidyverse.org/articles/base.html#one-table-verbs
- The first table here: https://v0-3-0-9000-aff79d2--reactable-docs.netlify.app/articles/custom-rendering.html. Undoing `display: block` on this table made it stretch to full width, so this change can affect styling in some cases

**Comment by hadley** [comment]
Have you seen any discussion of this problem in/around the bootstrap community?

**Comment by glin** [comment]
I haven't seen any mentions of `display: block` on tables in Bootstrap specifically. But if `display: block` was added to get tables to scroll with `overflow: auto`, Bootstrap's way of doing that is to add a scrolling container using its `.table-responsive` class: https://getbootstrap.com/docs/5.0/content/tables/#responsive-tables. Or without Bootstrap, wrapping tables in a `<div style="overflow: auto;"></div>` container would also work.

Most HTML table libraries I've seen in R also already have a way to add a scrolling container (e.g., DT, kableExtra) or have it built-in (gt).

**Comment by hadley** [comment]
I wonder if I should wrap every table in a `.table-responsive`?

**Comment by hadley** [comment]
Hmmmm, judging from https://github.com/mdn/content/issues/11206, it's possible that this might be less of a problem in modern browsers.

**Comment by hadley** [comment]
I'm worried about the unintentional consequences of this change, and I had @jooyoungseo take a look and it was ok in his screen reader. So I think it's safest to leave at this point.
