### ISSUE TITLE
vignettes with child documents now fail

### ISSUE THREAD

**Issue by mpadge** [r-lib/pkgdown#2144]
The `package_vignettes()` function just grabs [all `.[Rr]md` files](https://github.com/r-lib/pkgdown/blob/b6affbcb84411e961d9ec721f184e0a377b8e657/R/package.R#L229), and errors if any of the resultant name entries are missing from the index. Vignettes can, however, be constructed with child documents which should *not* be specified in the index. This new error-instead-of-warning behaviour prevents building any packages which use that structure. Fixing that behaviour would be appreciated. Thanks!

**Comment by dbosak01** [comment]
Hi Maelle:

On my pkgdown sites I like to have a FAQ that is in the top navbar, but not in the Articles list.  I used to be able to do this in the YAML as follows:

navbar:
  type: inverse
  structure:
    right: [home, intro, articles, reference, faq, news, github]
  components:
    faq:
      text: FAQ
      content:
      href: ./articles/procs-faq.html

Now I get this error.  Appending an underscore to the file name does indeed avoid the error.  But the FAQ file is also entirely excluded from the pkgdown site.  I want it as part of the site.  Just don't want it in my articles list.  It seems like there should be a way to do this.  Do you have any recommendations?

Thanks,

David

**Comment by maelle** [comment]
Could you add a comment to #2205 describing your use case? Compared to that feature request, you want the vignette built but not linked from the articles index, which is different, but, well, related. :smile_cat:
