### ISSUE TITLE
pkgdown tries to load namespace of package in unevaluated code

### ISSUE THREAD

**Issue by juliasilge** [r-lib/pkgdown#2145]
The rsample package has the [output of a reprex in its README](https://rsample.tidymodels.org/). This decision was originally made because we don't want to include those packages as dependencies; they are not needed for anything except the demo in the README. 

- In older versions of pkgdown, this worked and that chunk was not evaluated. 
- In the newest version of pkgdown released yesterday, it looks like pkgdown attempts to load these packages and [we get an error](https://github.com/tidymodels/rsample/runs/7047333134?check_suite_focus=true#step:6:84):

> Error in loadNamespace(name) : there is no package called ‘mlbench’

As a temporary fix, I have added this package to `Config/Needs/website:`, which is fine, I guess. It was surprising, though, since this is in an unevaluated bit of markdown. What do you all think about this? Do you have a recommended solution for us?

**Comment by dmurdoch** [comment]
Maybe it is trying to load the package to help with links to the functions used in the example.  I see that `library()`, `data()` and `set.seed()` are linked.  If `mlbench` exported functions with those names to replace the standar ones, the links would be going to the wrong place.

**Comment by maelle** [comment]
Yeah maybe it's a downlit thing :detective:

**Comment by maelle** [comment]
Can confirm I only saw the error in https://github.com/maelle/buggybug after updating downlit.

**Comment by hadley** [comment]
Sorry about this; I'll release a new version of downlit shortly.
