### ISSUE TITLE
Chunk option `class.source` not applied in vignettes

### ISSUE THREAD

**Issue by etiennebacher** [r-lib/pkgdown#2147]
I use the chunk option `class.source` to customize the code chunks as I want. This works when I manually knit vignettes:
````r
---
output: rmarkdown::html_vignette
---

```{css, echo=FALSE, eval = TRUE}
.my-class {
  background-color: red;
}
```

```{r select1, class.source = "my-class"}
print("Hello there")
```
````
![image](https://user-images.githubusercontent.com/52219252/175986748-d512b464-d119-4ffd-b07f-5c46aa98ee8d.png)

However, if I use `pkgdown::build_article()`, then the class "my-class" is not applied to the code chunk and therefore the CSS is in the article but useless.

![image](https://user-images.githubusercontent.com/52219252/175987421-f3ee9643-9002-48a9-9587-6e2d17489ad7.png)

`build_article()` documentation says that output formats in the YAML are not considered and the vignette is rendered with `rmarkdown::html_document` (which works correctly for applying the custom class), but nothing is said about the chunk option `class.source`. Is this behaviour a bug or is `class.source` unsupported?

(I tried with `pkgdown` devel version)

---

Edit: reprex [here](https://github.com/etiennebacher/PkgdownHighlighting). Knitting the vignette works, `build_articles()` removes the highlighting

**Comment by cderv** [comment]
in **pkgdown**, as you've seen the format will be change. There is one feature that will be applied by default which is **downlit** highlighting and auto linking. 

I believe this is an issue with **downlit**. This will not have the `class.source` also 

````rmarkdown
---
output: 
  rmarkdown::html_document:
	highlight: pygments
    highlight_downlit: true
---

```{css, echo=FALSE, eval = TRUE}
.my-class {
  background-color: red;
}
```


```{r select1, class.source = "my-class"}
print("Hello there")
```
````

**downlit** is replacing the whole code block and in the process, it does not keep `class.source`  and `attr.source` that **knitr** applies on the code block. 

For the context: 

* Knitr will output this Markdown code block 
````markdown
```{.r .my-class}
print("Hello there")
```
````

Pandoc will convert to 
````html
<div class="sourceCode" id="cb1">
<pre class="sourceCode r my-class"><code class="sourceCode r">
<span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="st">&quot;Hello there&quot;</span>)</span>
</code></pre></div>
````

**downlit** will replace the whole `<pre>`
````html
<div class="sourceCode" id="cb1"><
pre class="downlit sourceCode r"><code class="sourceCode R">
<span class="fu"><a href="https://rdrr.io/r/base/print.html">print</a></span><span class="op">(</span><span class="st">"Hello there"</span><span class="op">)</span>
</code></pre></div>
````

Hope it helps

**Comment by etiennebacher** [comment]
Thank you for the explanation. Is it worth opening an issue for this in **downlit** repo? I see that https://github.com/r-lib/downlit/issues/133 is slightly related
