### ISSUE TITLE
Using library or require in an example inside \dontrun may cause an error

### ISSUE THREAD

**Issue by gsrohde** [r-lib/pkgdown#2148]
To illustrate this problem, suppose we want to give an example using `deSolve` but don't want to make it a package requirement.  We might add something like this to the `\examples{ ... }` section of one of the `man` files:
```
\dontrun{
  library("deSolve")

  [ ... some code that uses deSolve ...]
}
```
If we don't actually have `deSolve` installed, `R CMD check` won't complain, but trying to build the `pkgdown` documentation gives rise to an error like
```
x Failed to parse Rd in system_derivatives.Rd
ℹ there is no package called ‘deSolve’
Caused by error in `loadNamespace()`:
! there is no package called ‘deSolve’ 

Execution halted
```

This certainly isn't expected!

It's not a huge problem—one can simply use fully-qualified function names, e.g. `deSolve::lsodes`, instead of calling the `library` function.  Alternatively, one could (again, leaving out the `library()` call) simply include a comment to the user who may wish to try the example saying that the example assumes that `deSolve` has been loaded and attached.  Nevertheless, it's disconcerting, to say the least, to get an error message from code that is supposedly "not run."

**Comment by dmurdoch** [comment]
I'm pretty sure this is the same issue as #2145, which is a `downlit` issue that has been fixed there.

**Comment by gsrohde** [comment]
Sorry—I forgot to search the issues before posting.
