### ISSUE TITLE
Don't include getting started article in check

### ISSUE THREAD

**Issue by cromanpa94** [r-lib/pkgdown#2150]
Hi folks,

I'm developing an R package (`phruta`) that uses your (amazing!!) package to deploy a website of my vignettes. Everything works great locally (i.e. using `build_site()`). However, I'm not able to pass the relevant checks in github due to an error with `build_site_github_pages()`. The [issue](https://github.com/cromanpa94/phruta/runs/7124965668?check_suite_focus=true) is related to my "Get started" site, which is based on `phruta.Rmd`:

```
-- Building articles -----------------------------------------------------------
Error in `data_articles_index()`:
! Vignettes missing from index: phruta
```
Do you know how I can solve this problem? Thanks in advance for your advice!!

**Comment by cromanpa94** [comment]
Sounds good! Thanks @hadley!!

**Comment by olivroy** [comment]
Will open a new issue, but this could leverage `pkgdown:::article_is_intro()`?

Because if your getting started vignette is an article i.e. `articles/pkg`, this error happens too.
