### ISSUE TITLE
Display R version compatibility badges

### ISSUE THREAD

**Issue by royfrancis** [r-lib/pkgdown#2156]
After running an automated github actions R CMD check on my package using a few different versions of R (say for example R 3.6,4.0,4.1,4.2), is there a way to add badges on the pkgdown documentation homepage that shows which versions passed or failed R CMD check?

**Comment by maelle** [comment]
I think this is outside the scope of pkgdown: pkgdown will include all README badges you include, adding these badges is your responsability.

Now as regard "per R version" GitHub Actions badges, this would mean different badges based on the build matrix. It does not seem currently possible https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge (i also saw https://github.community/t/separate-workflow-badges-when-using-matrix-testing-possible/16708 but it's a bit old now) so you'd have to have one workflow file per R version. It sounds a bit cumbersome and I wonder if such badges might confuse users as the actual R version compatibility is the one that'd be listed in DESCRIPTION?

Note that in order not to confuse users, dev badges are not shown on the released website when development is "auto" see #2054
