### ISSUE TITLE
Should pkgdown check DESCRIPTION validity

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2167]
Via https://github.com/r-lib/pkgdown/issues/2158#issuecomment-1185821705=

If a package DESCRIPTION has a wrong Authors field (without the `@R`) then the line

https://github.com/r-lib/pkgdown/blob/956f076f661eb2de9413f64ea24a580cf444466d/R/build-home-citation.R#L74

results in an error.

The error message is not clear.

Although that DESCRIPTION format might be rare, should pkgdown check the validity of the DESCRIPTION file before building?

**Comment by maelle** [comment]
It could be a part of `check_pkgdown()` maybe.

**Comment by hadley** [comment]
IMO this is out of scope for pkgdown.
