### ISSUE TITLE
Using in-body syntax for knitr chunk options creates problems for pkgdown in presence of child documents

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#2168]
While converting from the in-header chunk option syntax to new the in-body syntax, I have noticed that this new syntax trips up `{pkgdown}`'s vignette rendering when child documents are present. 

For a minimal reprex, see this PR:
https://github.com/IndrajeetPatil/minimalReprex/pull/3

When I try to build the website locally, I see the following backtrace:

```r
Backtrace:
1. pkgdown::build_site()
2. pkgdown:::build_site_external(pkg = pkg, examples = examples, run_dont_run = run_dont_run, …
3. callr::r(function(..., cli_colors, pkgdown_internet) { …
4. callr:::get_result(output = out, options)
5. callr:::throw(callr_remote_error(remerr))
6. callr:::callr_remote_error(remerr)
7. callr:::throw(err, parent = remerr[[3]])
---
Subprocess backtrace:
 1. pkgdown::build_site(...)
 2. pkgdown:::build_site_local(pkg = pkg, examples = examples, run_dont_run = run_dont_run, …
 3. pkgdown::build_articles(pkg, lazy = lazy, override = override, preview = FALSE)
 4. purrr::walk(pkg$vignettes$name, build_article, pkg = pkg, quiet = quiet, …
 5. purrr::map(.x, .f, ...)
 6. local .f(.x[[i]], ...)
 7. pkgdown:::render_rmarkdown(pkg, input = input, output = output_file, output_format = format, …
 8. base::tryCatch(callr::r_safe(function(...) rmarkdown::render(...), …
 9. base::tryCatchList(expr, classes, parentenv, handlers)
10. base::tryCatchOne(expr, names, parentenv, handlers[[1L]])
11. value[[3L]](cond)
12. rlang::abort("Failed to render RMarkdown", parent = cnd)
13. | rlang:::signal_abort(cnd, .file)
14. | base::signalCondition(cnd)
15. global (function (e) …
```

**Comment by maelle** [comment]
:wave: @IndrajeetPatil! Thanks for the reprex and bug report.

Setting a `browser()` deeply enough in the functions I get the actual error message!

```
Quitting from lines 12-13 (/tmp/RtmpeywYCq/../man/rmd-fragments/boilerplate.Rmd) 
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/tmp/RtmpeywYCq/../man/rmd-fragments/boilerplate.Rmd': No such file or directory
```

:thinking:

**Comment by IndrajeetPatil** [comment]
Thanks for digging into this!

This is strange. Why does this happen only with in-body syntax?

> cannot open file '/tmp/RtmpeywYCq/../man/rmd-fragments/boilerplate.Rmd': No such file or directory

The child document is [there](https://github.com/IndrajeetPatil/minimalReprex/tree/main/man/rmd-fragments) and `{pkgdown}` works [fine](https://indrajeetpatil.github.io/minimalReprex/articles/test2.html) on the `main` branch where in-header chunk option is used to specify child document.

**Comment by maelle** [comment]
ah no your syntax is the correct one anyway

**Comment by IndrajeetPatil** [comment]
Btw, I used the [new `{knitr}` function](https://github.com/yihui/knitr/pull/2149) to convert the old syntax to the new syntax.

**Comment by maelle** [comment]
oh good to know about, thank you!

**Comment by maelle** [comment]
I wonder if somehow the problem could be linked to https://github.com/yihui/knitr/blob/553b6929f0b737f02fffc20cd10a10d0268b1487/NEWS.md?plain=1#L234

I'm stuck so will leave this aside for now.

**Comment by maelle** [comment]
Posting the whole trace

```r
Quitting from lines 12-13 (/tmp/RtmpXwp60l/../man/rmd-fragments/boilerplate.Rmd) 
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :
  cannot open file '/tmp/RtmpXwp60l/../man/rmd-fragments/boilerplate.Rmd': No such file or directory
Backtrace:
  1. knitr::knit(..., tangle = TRUE)
  2. knitr:::process_file(text, output)
  5. knitr:::process_tangle.block(group)
  6. base::lapply(sc_split(params$child), knit_child)
  7. knitr (local) FUN(X[[i]], ...)
  8. knitr::knit(..., tangle = opts_knit$get("tangle"), envir = envir)
  9. xfun::read_utf8(input)
 10. base::readLines(con, encoding = "UTF-8", warn = FALSE)
 11. base::file(con, "r")
```

**Comment by maelle** [comment]
I see the same error with `rmarkdown::render("vignettes/test2.Rmd", intermediates_dir = tempdir())`

**Comment by IndrajeetPatil** [comment]
Thanks for digging deeper!

Do you think this is `{rmarkdown}` issue then?

**Comment by maelle** [comment]
I think so, I'm about to open an issue, I'm 99% I found the problem :smile_cat:

**Comment by maelle** [comment]
https://github.com/rstudio/rmarkdown/issues/2393

**Comment by IndrajeetPatil** [comment]
Thanks! Closing this issue in favour of that issue then :)

**Comment by maelle** [comment]
And we'll re-open if I'm wrong there :sweat_smile:
