### ISSUE TITLE
render_rmarkdown() should surface R Markdown errors better

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2169]
I think there's a bug somewhere, see the non informative errors encountered in #2168 and #2166

**Comment by maelle** [comment]
the only error one gets is something à la

```r
Error in `$<-.data.frame`(`*tmp*`, "call_text", value = c("pkgdown::deploy_to_branch(new_process = FALSE)",  : 
  replacement has 15 rows, data has 14
Calls: <Anonymous> ... trace_format -> trace_as_tree -> $<- -> $<-.data.frame
```

**Comment by joelnitta** [comment]
+1: I have also just [encountered this](https://github.com/joelnitta/canaper/runs/8031830170?check_suite_focus=true), and even though a similar [cryptic warning as above](https://github.com/r-lib/pkgdown/issues/2169#issuecomment-1228274536) was issued, the actual problem (missing `library()` call for a particular package) had nothing to do with a data frame, and was completely different from the cause of the problem in #2166.

**Comment by hadley** [comment]
This was a bug in rlang that's now fixed. You can update rlang to get the real error.
