### ISSUE TITLE
Only output from the first example is shown for examples in an `if()` block

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#2175]
If the examples are being run conditionally in an `if()` block, `{pkgdown}` displays output only from the first example.

For a minimally reproducible example, see [this](https://indrajeetpatil.github.io/minimalReprex/reference/std.html) page for a function that computes standard deviation:

<img width="585" alt="Screenshot 2022-08-04 at 07 59 42" src="https://user-images.githubusercontent.com/11330453/182773944-fcbb84cd-382f-4109-a84a-bf6694075f76.png">

**Comment by dmurdoch** [comment]
That looks like the usual way R works:  it is actually the second result that autoprints, because it is the result of the full expression `if { ... }`.

**Comment by IndrajeetPatil** [comment]
Ah, thanks for the clarification!

Hmm, well if R itself doesn't support it, then I guess `{pkgdown}` can't support it either.

I will just either have only a single example in the block, or just reduce the conditional usage of dependencies.
