### ISSUE TITLE
Is it possible to link objects showing up inside other-than-R preformatted text blocks?

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#2176]
Say I have `Rf_ScalarLogical`:

```
#' Rf_ScalarLogical
#'
#' A nice function indeed.
#'
#' @name Rf_ScalarLogical
NULL
```

and `hello`:

```
#' Hello
#'
#' @description
#' Just some random description.
#'
#' # C Examples
#'
#' ```C
#' // just some C code
#' int x = 2;
#' SEXP y;
#' y = PROTECT(Rf_ScalarLogical(x));
#' UNPROTECT(1);
#' return y;
#' ```
#'
#' # YAML examples
#' ``` yaml
#' url: https://pkgdown.r-lib.org
#' ```
#'
#' # Some other R examples
#' ```R
#' x <- sum(2) + Rf_ScalarLogical()
#' ```
#'
#' @examples
#' x <- sum(2) + Rf_ScalarLogical()
#'
hello <- function() {
  "hello!"
}
```

In a rendered website page, `Rf_ScalarLogical` is transformed to an hyperlink in both the ```R block and in block generated by `@examples`.  Is it possible to make it also a link from within the C block?

![snap](https://user-images.githubusercontent.com/19862384/183324879-470a3d3c-4ff5-4ab9-9707-ca882870b8dc.png)

**Comment by maelle** [comment]
Unfortunately no. The R code is highlighted using [downlit](https://downlit.r-lib.org/) (that does the [autolinking](https://pkgdown.r-lib.org/articles/linking.html)) whereas other code snippets are highlighted using Pandoc.

**Comment by ramiromagno** [comment]
Thanks for the clarification!
