### ISSUE TITLE
Pushing package to github fails when vignette includes "library(xtable)"

### ISSUE THREAD

**Issue by martinlaw** [r-lib/pkgdown#2177]
First time reporting any issue, apologies in advance.

As title: pushing a package to pkgdown fails when a vignette uses the command `library(xtable)`.

I have reproduced this in a package here: [https://github.com/martinlaw/pkgdowntest](https://github.com/martinlaw/pkgdowntest), where the package consists of a single vignette: [https://github.com/martinlaw/pkgdowntest/blob/main/vignettes/vignette1.Rmd](https://github.com/martinlaw/pkgdowntest/blob/main/vignettes/vignette1.Rmd)

The command `pkgdown::build_site()` runs without error.

The failed part of the report is here [https://github.com/martinlaw/pkgdowntest/runs/7804676907?check_suite_focus=true](https://github.com/martinlaw/pkgdowntest/runs/7804676907?check_suite_focus=true) and the logged error is directly below:

```
Reading 'vignettes/vignette1.Rmd'
-- RMarkdown error -------------------------------------------------------------
--------------------------------------------------------------------------------
Error in `$<-.data.frame`(`*tmp*`, "call_text", value = c("pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)",  : 
  replacement has 14 rows, data has 13
Calls: <Anonymous> ... trace_format -> trace_as_tree -> $<- -> $<-.data.frame
Execution halted
Error: Process completed with exit code 1.`
```

Incidentally, it took me a lot of trial and error to discover that this line was causing the failure. Is there a faster way to test than the cycle of edit -> save -> commit -> push -> wait on github? As I state, `pkgdown::build_site()` runs without error.

**Comment by dmurdoch** [comment]
I don't see `xtable` as a dependency listed in your DESCRIPTION file.  Is it just that it isn't being installed, so the vignette fails because of that?

**Comment by martinlaw** [comment]
You are correct -- this is the true source of the failure. My apologies. I realise now that I could have found this using `devtools::check()`. I will close now.
