### ISSUE TITLE
Page width is larger than viewport width on mobile

### ISSUE THREAD

**Issue by netique** [r-lib/pkgdown#2179]
On devices with narrower screens, the page width is larger than the viewport resulting in a user being able to scroll horizontally, which is unwanted, generally. From my inspection, this is due to the `aside` class putting extra margins around and even though there is `width: calc(100wv - 1rem)` to compensate, this is "deactivated" by the `.row` which has `width: 100%`. You can see it at https://pkgdown.r-lib.org/, for instance.

Note that this issue cannot be replicated on pages using {tidytemplate}, such as https://rstudio.github.io/shinytest2/.

**Comment by maelle** [comment]
Thank you for the bug report @netique! Would you mind adding screenshots to the issue? (I think I am not looking at the correct part of the page / at the correct behavior) Thanks, and no worries if you can't.

**Comment by maelle** [comment]
Noting http://crumplab.com/reference/index.html is an example with a too wide navbar (might be another issue though)

**Comment by netique** [comment]
Sure, here is a demo of the behaviour.

![ezgif-5-3c654ca029](https://user-images.githubusercontent.com/34926852/186432382-9da9ee5b-a30c-4d40-9b4d-e79dc0663b91.gif)

You can see it quite easily on the code chunk (it is supposed to fill the viewport width 100% so horizontal scrolling is not possible).

Here is the behaviour when I disable the `margin` in the `aside` class:
<img width="1271" alt="Snímek obrazovky 2022-08-24 v 15 38 23" src="https://user-images.githubusercontent.com/34926852/186433237-da609a10-144a-4ecc-bdfa-a40d1a8c5e67.png">

The website [you mentioned](http://crumplab.com/reference/index.html) works great (you cannot scroll horizontally), as there is no object of class `aside` used.

**Comment by hadley** [comment]
Fun terminology: this is called a scrollburglar.

Looks like the root cause is I sets the width of an aside to `calc(100vw - 1rem)`, ensuring that there's enough room for the margin. But bootstrap's `.row > *` override the width to `100%`. So I think I just need to get a bit more specific here.
