### ISSUE TITLE
Can the title for the reference be changed?

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#2181]
The title of the reference page is by default "Function reference". Can I change it?

**Comment by maelle** [comment]
At the moment no unless you provide a custom template https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files

Your question made me think of #2183, but I wouldn't bet on it. :smile_cat:

**Comment by ramiromagno** [comment]
Thanks!

**Comment by courtiol** [comment]
Flexibility would be nice, but if not, perhaps changing the title would be enough.
What I personally don't like with "Function reference" is that it lists datasets as well which are clearly not functions.
What about "Package objects" or similar?

**Comment by hadley** [comment]
Maybe we should just change it to reference index?

**Comment by hadley** [comment]
Or package index, as suggested by @hfrick and @mikemahoney218.
