### ISSUE TITLE
Suppress logo if it is already included in the `README` at a location other than H1 header

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#2184]
## Motivation

This is similar to https://github.com/r-lib/pkgdown/issues/2083.

Sometimes I want to include the package logo at a custom location in the `README`.

For example, instead of including it in the H1 header:

```r
# Minimal reprexes for `{pkgdown}` issues  <img src="man/figures/logo.png" align="right" width="240" />
```

I include it below the header:

```r
# Minimal reprexes for `{pkgdown}` issues 

<img src="man/figures/logo.png" align="right" width="240" />
```

## Issue

If I do this, on `README`, this looks [good](https://github.com/IndrajeetPatil/minimalReprex/blob/main/README.md):

<img width="1244" alt="Screenshot 2022-09-06 at 20 07 20" src="https://user-images.githubusercontent.com/11330453/188708226-75bfdf83-6436-4205-95e5-1713ffe02518.png">

But, on the `{pkgdown}` website [homepage](https://indrajeetpatil.github.io/minimalReprex/), the logo is now included twice:

<img width="912" alt="Screenshot 2022-09-06 at 20 11 46" src="https://user-images.githubusercontent.com/11330453/188708401-6992e55d-5c8b-4630-8cc9-c2c3ee97ea8a.png">

Is it possible to not include it in the header if it is to be displayed somewhere else in the `README`?

## Reprex

Minimally reproducible example: https://github.com/IndrajeetPatil/minimalReprex

**Comment by egouldo** [comment]
Any update on when this issue is planned for?

**Comment by nvelden** [comment]
Running into the same issue. I now every time have to go to the docs/index.html file and remove the  `<img src="logo.png" class="logo" alt=""><h1>` line.

**Comment by pepijn-devries** [comment]
Wouldn't adding `class="pkgdown-hide"` to the `<img>` tag solve this issue? See:

https://pkgdown.r-lib.org/news/index.html#pkgdown-200

**Comment by hadley** [comment]
I formally endorse the use of `pkgdown-hide` for this purpose. Thanks for the suggestion @pepijn-devries!
