### ISSUE TITLE
Style code blocks

### ISSUE THREAD

**Issue by sgvignali** [r-lib/pkgdown#2197]
Hi, thank you for this fantastic package.

I have noticed that a custom css class defined using the chunk option `class.source` is not created in the website.

As an example you can see the rmarkdown code [here](https://github.com/ConsBiol-unibern/SDMtune/blob/4babf589fb9de690a6e98d8e2e8d3a54a287d77b/vignettes/articles/train-model.Rmd#L121-L123) and the relative web page [here](https://consbiol-unibern.github.io/SDMtune/articles/train-model.html#try-yourself) (watch the page source).

Is this the expected behaviour? A while ago it worked.

Thank you in advance,
Sergio

**Comment by etiennebacher** [comment]
Hi, I already opened an issue on this (#2147) and it actually comes from https://github.com/r-lib/downlit/issues/149

**Comment by sgvignali** [comment]
Ops, I didn't see your issue

**Comment by maelle** [comment]
Thanks @etiennebacher (and thanks @sgvignali for the bug report!). I guess we can close this one.
