### ISSUE TITLE
Update build_home() docs

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2198]
With what was changed in #2114

What happens to the badges by default for production and for development websites. What can one customize or not (the presence of the dev section in the sidebar, the removal of badges from the main div)

**Comment by maelle** [comment]
It'd also be useful to clarify that if the configuration for the sidebar does not contain "dev" as an element, the current logic means the badges won't be removed from the body. https://github.com/r-lib/pkgdown/blob/956f076f661eb2de9413f64ea24a580cf444466d/R/tweak-homepage.R#L52

I was surprised by this but it does not mean it isn't logical :sweat_smile:

**Comment by maelle** [comment]
To clarify if you have a customized sidebar configuration AND want the badges removed from the main README for the production website, you need to add "dev" to the sidebar configuration. There will be no "dev status" section in the sidebar and the badges will be removed.

**Comment by maelle** [comment]
https://community.rstudio.com/t/badges-stoped-being-visible-on-website-html-using-pkgdown/152056/4

**Comment by maelle** [comment]
Summary of what I understood

- Badges are not shown on released website. #2233 
- This behavior can NOT be customized.
- Confusing behavior regarding badges removal from the main content. If you use a custom sidebar configuration, and want the badges removed from the main content, you need the sidebar configuration to include "dev" *even if that does not mean the badges will appear in the sidebar configuration*, since that does not happen for released websites.

**Comment by hadley** [comment]
The first two bullets make sense to me. I don't understand the last one.

**Comment by maelle** [comment]
Sorry. Here is a reprex https://github.com/maelle/badgey

In that package there is a custom sidebar configuration that does not include the "dev" section. https://github.com/maelle/badgey/blob/e100afa9cb285147f6d3e5340782b2ef96103c5c/_pkgdown.yml#L9

Because of that, the badges are not removed from the main content.

![image](https://user-images.githubusercontent.com/8360597/201677238-41357044-f67d-4b78-bfd2-4460690b4619.png)

To remove the badges from the main content, one needs to add the "dev" section to the custom sidebar configuration.

It is a bit confusing because in the end, there is no dev section in the sidebar anyway for that released website.

I wonder
- whether it is a niche problem so should be ignored. :sweat_smile: 
- whether the removal of badges from the main content should be controlled differently, independently from whether they are included or not in the sidebar.

**Comment by hadley** [comment]
Oh that seems like a bug, and we should just fix it.

**Comment by maelle** [comment]
I'll try to get to it soon-ish.

Is the expected behavior that pkgdown should **always** remove the badges from the main content (when it can detect it), and that one can**not** prevent (customize) pkgdown from doing so?

**Comment by hadley** [comment]
Yes, that's the current expected behaviour. We could add a setting if needed.
