### ISSUE TITLE
strip_header causes the navigation bar to overlap content

### ISSUE THREAD

**Issue by igordot** [r-lib/pkgdown#2199]
I noticed that with Bootstrap 5 and `strip_header` enabled, the content will be overlapping with the navigation bar.

Here is an example with the simplex theme with `strip_header: false`:
<img width="458" alt="image" src="https://user-images.githubusercontent.com/6363505/192031678-40bcef70-9f16-4efb-b21b-9e389edcea3f.png">
And with `strip_header: true`:
<img width="433" alt="image" src="https://user-images.githubusercontent.com/6363505/192031505-34c3c295-539d-49f1-81fd-f3d2a2dd5101.png">

This might be more of a Bootstrap bug than a pkgdown one. Is there any way to fix or get around this issue?

**Comment by maelle** [comment]
:wave: @igordot, thanks for the report.

I'd recommend using the `pkgdown-nav-height` bslib variable https://pkgdown.r-lib.org/dev/articles/customise.html#bootswatch-themes (at least for a workaround for now)

**Comment by hadley** [comment]
Since we don't really use or recommend this any more, I think we should remove from the docs.
