### ISSUE TITLE
Unexpected token in bootstrap-toc.js

### ISSUE THREAD

**Issue by GregorDeCillia** [r-lib/pkgdown#2207]
Thank you very much for this exceptional R package

I am currently getting javascript errors in one of my pkgdown sites which seems to break several functionalities of `pkgdown.js`. 
 This includes (among others) the table of contents in the sidebar.

```
Uncaught SyntaxError: Unexpected token '<'          bootstrap-toc.min.js:1  
Uncaught ReferenceError: Toc is not defined         jquery-3.6.0.min.js:2
    at HTMLDocument.<anonymous> (pkgdown.js:7:5)
    at e (jquery-3.6.0.min.js:2:30038)
    at t (jquery-3.6.0.min.js:2:30340)
```

After looking closer in the chrome devtools, it seems `bootstrap-toc.js` is not properly loaded from https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.js which is the cdn location from the pkgdown template

https://github.com/r-lib/pkgdown/blob/d1a64f28518dc83905c6dc36ce68eeaaa80d3505/inst/BS5/templates/head.html#L26-L27

My browser is recieving HTML rather than JS from the cdn. Here is a screenshot where I prettified the contents of `bootstrap-toc.min.js` by hand for easier readability. 

![image](https://user-images.githubusercontent.com/9311130/193962769-db42bf37-5d97-4289-a725-d6348ad090ef.png)

Any advice on how this might happen would be very much appreciated.

**Comment by GregorDeCillia** [comment]
I was just able to reproduce this isse with a simple webpage, which baiscally just loads `bootstrap-toc`.

```html
<head>
  <script src="https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.js"></script>
</head>
<body></body>
```

Replacing the link with `https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.js` resolves the issue. This fix also works when the pkgdown sites are post processed.

```r
url_pkgdown <- "https://cdn.rawgit.com/afeld/bootstrap-toc/v1.0.1/dist/bootstrap-toc.min.js"
url_custom  <- "https://cdn.jsdelivr.net/gh/afeld/bootstrap-toc@1.0.1/dist/bootstrap-toc.min.js"

for (file in list.files('docs/articles', pattern = "*.html", full.names = TRUE)) {
  readLines(file) %>% 
    sub(url_pkgdown, url_custom, ., fixed = TRUE) %>% 
    writeLines(file)
}
```

**Comment by maelle** [comment]
Thanks so much!

**Comment by GregorDeCillia** [comment]
@maelle  Thank you for this timely fix. I can confirm that my pgkgdown site no longer needs patching when it is built with [pkgown@7fe9e80](https://github.com/r-lib/pkgdown/tree/7fe9e802df2964d483d0267f1d5a59aa7b3c685d).

### Note for future readers of this issue

This bug only affects pkgdown websites which use bootstrap 5. All sites using bootstrap 3 (the default) are not affected and still work with the current CRAN version of pkgdown (2.0.6). Already deployed pkgdown websites which use bootstrap 5 need to be rebuild with the dev-version of pkgdown. To check if your package is affected, make sure to clear the browser cache using `Ctrl + F5`.
