### ISSUE TITLE
Chrome tab icon not updating - only updates after using search bar 

### ISSUE THREAD

**Issue by telphick** [r-lib/pkgdown#2212]
Hello,

After updating my icon to a new logo and using build_favicons(), the tab in Google Chrome is not updating ONLY until after I use the search function. I have had a look through my repo and tried to find if there was any remains of my old logo but nothing to be found. Has any one experienced this before. 

If other information is needed, let me know and I will get it to you.

Thank you!

**Comment by maelle** [comment]
- Could you try (if you haven't done so) deleting the browser cache?
- Does it look good in another browser?

**Comment by telphick** [comment]
Ahh, yes, thank you!! Clearing the browser cache worked!
