### ISSUE TITLE
Rsconnect folder created in docs/ after using rsconnect::deployApp

### ISSUE THREAD

**Issue by telphick** [r-lib/pkgdown#2214]
Hello,

Has anyone else experienced a folder named rsconnect being created in /docs after using rsconnect::deployApp? Is there a way to stop it being built? It seems to inhibit future building of the site as it is treated as if it should be built along with the rest of the site.

Code used currently:
  rsconnect::deployApp(appDir = "docs/",
                       appPrimaryDoc = "index.html",
                       server = 'server_here',
                       appId = 'app_id_here')

TIA!

**Comment by maelle** [comment]
Were you deploying a pkgdown website? For more visibility of your question, you could also post on https://community.rstudio.com/

**Comment by telphick** [comment]
> Were you deploying a pkgdown website? For more visibility of your question, you could also post on https://community.rstudio.com/

Hi, yes I was deploying a pkgdown website. Thanks for the link. I will also post in there

**Comment by maelle** [comment]
Posting the link to your post there for future reference https://community.rstudio.com/t/rsconnect-folder-created-when-using-rsconnect-deployapp/150234

**Comment by maelle** [comment]
was the problem solved?

**Comment by tbowling87** [comment]
I recently hit a similar issue, found the recordDir parameter in rsconnect::deployApp could be used to change the location the rsconnect folder is created, allowing you to sidestep the issue
