### ISSUE TITLE
Release pkgdown 2.0.7

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2222]
Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_pkgdown.html) #2223
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [ ] `revdepcheck::cloud_check()`
* [x] Update `cran-comments.md`
* [x] `git push`
* [x] Check that 'test/widget.html' responds to mouse clicks

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`

**Comment by hadley** [comment]
@maelle the portalr failure is a false positive because it doesn't actually call pkgdown inside the package (it only uses it for a GitHub action)

**Comment by maelle** [comment]
I added 3 more small issues (with corresponding PRs) to this milestone since the version has not been released.

Should #2240 be in the same release? It does not need many new lines of code/docs.
