### ISSUE TITLE
Provide check_pkgdown() as an expectation for testthat?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2224]
Like https://lintr.r-lib.org/reference/expect_lint_free.html but it'd be `expect_pkgdown_config_errorfree()` or so.

This feature suggestion is motivated by rOpenSci packages whose website gets built externally, but I'm opening this here in case it might be more generally useful, for instance locally. In https://github.com/ropensci/webchem/issues/373#issuecomment-1275171734 the authors added a GHA workflow running `check_pkgdown()`.

**Comment by hadley** [comment]
I don't think it makes sense to include this in R CMD check; it's better as a separate action (which already works).

**Comment by maelle** [comment]
:+1: 

I :eyes: https://github.com/r-lib/actions/issues/267
