### ISSUE TITLE
Better description of the test/widget.html test?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2225]
@hadley reg https://github.com/r-lib/pkgdown/blob/5dc177d24dcbbdf0ecea6553b064640481c58899/R/pkgdown.R#L10

1. It responds to clicks on 10/50/100 but it overlays the text beneath it. It is the same for the released website. Is it a problem?

![image](https://user-images.githubusercontent.com/8360597/198281798-564540e6-b080-4cdf-aa10-ce7613a73c15.png)

2. It actually took me a while to see where to click (now it seems obvious of course) so maybe the text of the vignette could be super explicit about what's to click?
3. The bullet point could link to the vignette in the development version of the website directly?

**Comment by hadley** [comment]
I tweak the bullet to be more clear.

I think the spacing issue is long-standing, and there's nothing to do about it.
