### ISSUE TITLE
process inst/NEWS.Rd if no ./NEWS.xx in package root?

### ISSUE THREAD

**Issue by GeoBosh** [r-lib/pkgdown#2229]
Currently pkgdown doesn't look for  `inst/NEWS.Rd` when creating the 'Changelog' section. Would you consider processing it, perhaps if no `NEWS.md` or `NEWS` are present in the root directory of a package?

Here is an excerpt from WRE:
> Things you might like to add to inst are a CITATION file for use by the citation function, and a 
> NEWS.Rd file for use by the news function. See its help page for the specific format restrictions 
> of the NEWS.Rd file.

Examples of packages that have `inst/NEWS.Rd` are Matrix (https://r-forge.r-project.org/scm/viewvc.php/pkg/Matrix/inst/NEWS.Rd?view=markup&root=matrix) and fGarch (https://r-forge.r-project.org/scm/viewvc.php/pkg/fGarch/inst/NEWS.Rd?view=markup&root=rmetrics).

**Comment by jeroen** [comment]
More generally, we could use the NEWS data parsed by R, which supports all common formats:

```r
tools:::.build_news_db('dplyr')
tools:::.build_news_db('curl')
tools:::.build_news_db('Rcpp')
```

**Comment by hadley** [comment]
We could do that, but the majority of folks these days seem to use `NEWS.md`, and we already have our own home grown parsing system working for that. So I think unfortunately the cost-reward tradeoff for this issue means it'll never rise to the top of our to do lists, hence I'm going to close the issue.
