### ISSUE TITLE
Bug: `has_keyword()` adds all instead of nothing if the keyword does not occur

### ISSUE THREAD

**Issue by bundfussr** [r-lib/pkgdown#2234]
If a reference section is created using `has_keyword()` and the keyword does not occur, all functions are added to the section.
For example
```
- subtitle: BDS Derivations
  contents:
  - has_keyword("der_bds_gen")
  - has_keyword("der_bds_findings")
```
generates a section with all functions if the `der_bds_gen` keyword isn't used by any function. The issue occurs only if there is another entry in `contents:` which is not empty. I.e.,
```
- subtitle: BDS Derivations
  contents:
  - has_keyword("der_bds_gen")
```
creates an empty section as expected.

**Comment by maelle** [comment]
Thanks for reporting. Would you have time to create a minimal reproducible example, for instance a package with a few manual pages and this configuration? https://pkgdown.r-lib.org/CONTRIBUTING.html#package-reprexes This would save time on this end. No worries if not. :smile_cat:

**Comment by maelle** [comment]
draft PR #2243
