### ISSUE TITLE
More consistency in DE translations

### ISSUE THREAD

**Issue by lhdjung** [r-lib/pkgdown#2235]
Some translations in R-de.po might be improved further:

1. "Sponsor" is not gendered like comparable nouns, i.e., "Sponsor:in".
2. "Citation" is translated as "Zitierung" in line 101, but as "Zitiervorschlag" in line 281. I think "Zitation" is more common in German academia than "Zitierung", but I'm not sure what the best solution would be here.
3. "References" is translated as "Literaturangaben" in line 217. However, "Literaturverzeichnis" is much more common (according to Google and Google Scholar), and more consistent with the translation of "reference" as "Verzeichnis" in lines 169 and 197.

**Comment by maelle** [comment]
Danke schön! Do you want to make a PR for this?

**Comment by maelle** [comment]
Example PR: #2149

**Comment by lhdjung** [comment]
Gern geschehen! :) I hope this helps.

**Comment by maelle** [comment]
Yep it does help! :pray:
