### ISSUE TITLE
Support `.yaml` extension for config files everywhere?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#2244]
Supporting it in the root directory, but not in `inst/` and `pkgdown/` directory violates user's mental model 

P.S. See FAQ#1 [here](https://yaml.org/faq.html) for why `.yaml` might be preferred by some users.

---

Changing the follwing

https://github.com/r-lib/pkgdown/blob/2766829b0b6310be5f92820ab6174607353e7f03/R/package.R#L119-L128

to

```r
pkgdown_config_path <- function(path) {
  path_first_existing(
    path,
    c(
      "_pkgdown.yml", "_pkgdown.yaml",
      "pkgdown/_pkgdown.yml", "pkgdown/_pkgdown.yaml",
      "inst/_pkgdown.yml", "inst/_pkgdown.yaml"
    )
  )
}
```

should fix this.

**Comment by salim-b** [comment]
NOTE: If this proposal is implemented, the changes have to be reflected in the [`rprojroot::is_pkgdown_project`](https://rprojroot.r-lib.org/reference/criteria.html) root criterion ([source](https://github.com/r-lib/rprojroot/blob/main/R/root.R#L322)).

**Comment by hadley** [comment]
@salim-b thanks for the reminder, I filed https://github.com/r-lib/rprojroot/issues/104.
