### ISSUE TITLE
Inconsistent behavior displaying external image files build_articles

### ISSUE THREAD

**Issue by samuel-marsh** [r-lib/pkgdown#2246]
Hi,

This may be something obvious but as of right now it is stumping me.  In short I'm preparing to submit package that I have currently just hosted on GitHub to CRAN.  The vignettes I’ve written for the package which are hosted on pkgdown site are not truly vignettes in CRAN sense (as they rely on large local data files to compile).  Therefore, I want to move them to be articles in the pkgdown sense so that they can be displayed on package website but not built with package.

However, I’m having error when doing this with a couple of articles that display an external image file not rendering properly in current package repo.  I’ve worked to get as reproducible example of problem as possible and am including that below along with link to current package repo.

As they are written now (https://github.com/samuel-marsh/scCustomize) `build_site()` works with no issues.  So I simply tried creating subdirectory called “articles”, moving .Rmd files there, adding to Rbuildignore, and modifying the file paths of external images based on presence in new subdirectory.  However, when I then run `build_site` or `build_articles` that fails with error:
```
Missing images in 'vignettes/articles/NAME….Rmd': 
ℹ pkgdown can only use images in 'man/figures' and 'vignettes'
```

In effort to try and isolate the issue and provide as reproducible example as possible I’ve done the following:

This is all based on following instructions from pkgdown vignettes and r-pkgs.org.

**Working:**
If create new RStudio package project and run `usethis::use_article(“test”)`.  That creates the vignettes and subdirectory articles with .Rmd inside it.  I then make folder subdirectory inside articles called “img” and place my .png image file there.  I leave everything in .Rmd as it was following `use_articles` but change the R chunk.  So the full .Rmd file looks like:
```
---
title: "test"
---

CHUNK
{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
CHUNK

CHUNK
{r setup}
print("hi")
knitr::include_graphics("img/Iterate_named_plots.png")
CHUNK
```

If I then run `build_site()` or `build_articles` it runs with no issues, renders the image, and everything looks good.

**Failing:**
In the current package repo (https://github.com/samuel-marsh/scCustomize), I first move all current .Rmd files back to vignettes folder and delete the articles subdirectory.  Then I run the exact same process (as I did in blank package project usethis::use_articles, etc).  But then when I run `build_article(“articles/test”)` I get the following error (written CHUNK instead of the chunks so the text in this issue displays properly):

```
> pkgdown::build_article(name = "articles/test")
Reading 'vignettes/articles/test.Rmd'
Writing 'articles/test.html'
Warning message:
Missing images in 'vignettes/articles/test.Rmd': '../../../../Bioinformatics%20Tools/scCustomize/articles/articles/img/Iterate_named_plots.png'
ℹ pkgdown can only use images in 'man/figures' and 'vignettes'
```

So I’m bit stumped as to why it works with no issues in blank package project but fails in my current repo.

Thanks!
Sam

**Comment by samuel-marsh** [comment]
Sorry forgot to add in previous post:
R4.1.2
Mac OS 12.4 (Intel Chip)
pkgdown v2.0.6
knitr v1.41
rmarkdown 2.18

**Comment by maelle** [comment]
:wave: @samuel-marsh!

Would the `external_resources` YAML field help https://pkgdown.r-lib.org/reference/build_articles.html#external-files?

To get a reprex, you could also start from a copy of your repo at the stage it's failing and then remove things one by one especially dependency and code to see if you still get the error?

(it could also be a bug! a reprex can only help :-))

**Comment by maelle** [comment]
Thank you! With an example that wouldn't have the dependencies (or even with the dependencies, just something I could easily clone) it'd be easier for me to experiment and try to pinpoint the problem. However, I'm glad you found a workaround and can imagine it has already been a lot of trouble. Good luck with the CRAN submission!

**Comment by samuel-marsh** [comment]
Thanks!!
Ya it was pretty confusing especially since it was working no issues before moving to subdirectory.  Also glad I randomly tried that path (literally right before I’d been planning to post the rest of my reply).  Thanks again!
