### ISSUE TITLE
Name of "release" development mode is confusing to me

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#2255]
I think I've brought this up before, but I thought about it again while working on the website chapter for R Packages.

Sorry for the homely ascii art, but here's how I explained development mode there.

Here's "release" development mode, where the website is **not** built from the release, but rather from `HEAD`:

```
    ...
     |
     V
    Tweaks before release     v0.1.9000
     |
     V
    Increment version number  v0.2.0     <-- install.packages() gets this
     |
     V
    Increment version number  v0.2.9000  
     |
     V
    Improve error message     v0.2.9000  <-- site documents this
     |
     V
    ...
```

Here's "auto" development mode:

```
    ...
     |
     V
    Tweaks before release     v0.1.9000
     |
     V
    Increment version number  v0.2.0     <-- install.packages() gets this
     |                                       main site documents this
     V
    Increment version number  v0.2.9000  
     |
     V
    Improve error message     v0.2.9000  <-- dev/ site documents this
     |
     V
    ...
```

I know this is just a naming thing, but the name "release" seems kind of regrettable. Because such a website will almost never be built from a released version of the package. I guess it means "build from `HEAD` but style it like a released version"? Maybe that way of thinking of the development mode just needs to be more clear.

Perhaps this ship has already sailed, but alternatives that make more sense to me are "simple" and "current".

**Comment by hadley** [comment]
Yeah, this is about how the site is styled, not where it's built from. I'll have a go at clarifying the docs.
