### ISSUE TITLE
[WARNING] Could not convert TeX math z = s\sqrt{n}, rendering as TeX

### ISSUE THREAD

**Issue by cthombor** [r-lib/pkgdown#2261]
Hi, I have been trying to add a couple of inline equations to a github-hosted website using RStudio.  It's my first such project -- and I'm unfamiliar with the workflow features in github and RStudio, so my localisation may be incorrect ... but I *think* it's most likely to be an issue with pkgdown or its setup on my RStudio client.   If that's not a likely root cause please aim me elsewhere for assistance.

I have a few inline math callouts in my README.Rmd. The single-variable callouts (e.g. $s$) don't throw warnings when I invoke the "Build pkgdown" affordance in the AddIns of my project; but warnings are issued for $\sqrt{n}$.  Screenshot below:

![Screenshot_20221229_113347](https://user-images.githubusercontent.com/12578824/209916963-68bdde1c-8336-4b27-a8bf-3ac2a903a506.png)

The `README.md` looks fine to me, e.g. at $z = s\sqrt{n}$.

I believe `docs/index.html` exhibits a defect at `<span class="math inline">$z = \sqrt{n}$</span>`, due to the dollar signs -- which I imagine should be suppressed, as in the subsequent `<span class="math inline"><em>s</em></span>`.

![Screenshot_20221229_082446](https://user-images.githubusercontent.com/12578824/209918578-9b8d3412-d51b-48b6-923c-a177a75cec6f.png)

I have tried `usethis::use_pkgdown_github_pages()`; but I get the same defective rendering of $\sqrt{n}$.  I don't see any warning messages on the bot-triggered Action, screenshots below.

Please advise.

![image](https://user-images.githubusercontent.com/12578824/209918504-0a8fe9f3-aae4-46fa-8275-f97343e8aec1.png)

![image](https://user-images.githubusercontent.com/12578824/209919247-75311564-dd4b-4cb8-a1a0-e69d42bdf146.png)

**Comment by maelle** [comment]
Locally I get the error too for https://github.com/maelle/tex, interesting. It's an error from Pandoc, I wonder whether that happens for only certain versions of Pandoc.

Does your rendered website on GitHub Actions look ok? I assume so since the math rendering is actually done by Mathjax not Pandoc. (the warning is still a problem of course!)

**Comment by maelle** [comment]
The problem does not happen if the same math is used in a vignette.

**Comment by cthombor** [comment]
@maelle thanks for looking into this.  I'm grateful that R has volunteers like you who are doing the hard yards of maintenance!  I pushed my current version just now to github, with a workflow on readme.md (rather than on readme.Rmd as before) -- but https://cthombor.github.io/SafeVote/ still has the defective index.html:

![image](https://user-images.githubusercontent.com/12578824/211139064-4605ce69-f8a6-4a52-b92c-3fb13e1750e4.png)

Curiously -- and perhaps this is an important clue -- the sqrt callouts in https://github.com/cthombor/SafeVote are rendered correctly:

![Screenshot_20230107_082340](https://user-images.githubusercontent.com/12578824/211139213-1849a176-a7f4-4441-98c4-66d79b88861c.png)

**Comment by maelle** [comment]
@cthombor I opened a PR #2263 with a possible fix (emphasis on possible) :-)
