### ISSUE TITLE
Support autolinking for Bioconductor packages

### ISSUE THREAD

**Issue by willgearty** [r-lib/pkgdown#2264]
I have a Bioconductor package ([ggtree](https://www.bioconductor.org/packages/ggtree)) that I would love to be able to link to in one of my vignettes, but the auto-linking doesn't seem to work. In fact, for this package, `{ggtree}` ends up linking to a book listing on Amazon! The same occurs within code blocks (`library(ggtree)` will include a link to this Amazon listing).

**Comment by maelle** [comment]
Indeed 

``` r
downlit::autolink("library('ggtree')")
#> [1] "<a href='https://www.amazon.com/Integration-Manipulation-Visualization-Phylogenetic-Computational-ebook/dp/B0B5NLZR1Z/'>library('ggtree')</a>"
```

<sup>Created on 2023-01-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Now, it is expected (I think?) as the `DESCRIPTION` links to this book. https://github.com/YuLab-SMU/ggtree/blob/6bc28f3948ef64176c25ebc8086db5cf4d397f62/DESCRIPTION#L61

I'd recommend reading https://pkgdown.r-lib.org/articles/linking.html You'll need to link to the pkgdown website URL of ggtree in both `DESCRIPTION` and the pkgdown config file.

**Comment by willgearty** [comment]
Ah, I hadn't even noticed the Description specified the Amazon link as the official URL (which seems like an odd decision). I've just gone ahead and made my own links to the actual website for ggtree (which is not a pkgdown site).
