### ISSUE TITLE
Weird looking package site

### ISSUE THREAD

**Issue by maRce10** [r-lib/pkgdown#2265]
I used pkgdown to create a package site but there seems to be something wrong with the website layout. I try removing/changing the css file with no success. 

https://marce10.github.io/Rraven/

**Comment by maelle** [comment]
Which pkgdown version are you using? I cloned your repository, ran `pkgdown::build_site()` (with pkgdown latest CRAN version) and the website looks good. :bird: 

![image](https://user-images.githubusercontent.com/8360597/214360005-c9696aa8-acc5-4daf-8d92-fcccd8dc4abe.png)

I'd recommend using GitHub Actions to build the pkgdown website automatically, you'd need to run [`usethis::use_github_action("pkgdown")`](https://usethis.r-lib.org/reference/github_actions.html) once to add the corresponding GitHub Actions workflow. The workflow would push the website to the gh-pages branch.

Note that at the moment you deploy your website from the docs/ folder on the main branch, but you list docs/ in .gitignore, which I find surprising. (With GitHub Actions, as mentioned above, you wouldn't use that folder but instead the gh-pages branch; and in that scenario it's great to list docs/ in .gitignore)

**Comment by maelle** [comment]
@maRce10 regarding customization ICYMI see https://pkgdown.r-lib.org/articles/customise.html

**Comment by maRce10** [comment]
thanks!
