### ISSUE TITLE
build demo files in pkgdown?

### ISSUE THREAD

**Issue by friendly** [r-lib/pkgdown#2267]
(First: thanks to all pkgdown developers for your work on this!!)

Before vignettes were widely used, a `demo/` directory was used in a package to have more extensive examples than reasonable/possible with std `.Rd` help pages. These appeared in the package help documentation and could be executed via `demo()`. 

I have several older, but still maintained, packages with a collection of such `demo/` files, that I'd like to see reflected in pkgdown sites.  But how??

Can this be considered for a future enhancement? The idea might be to have folder in the site with the source and output of the demos.   The convention was that there is a 00index file there giving the names and descriptions of the demos.

Failing an enhancement, is there some way for me to process these demo files so they can be seen on the pkgdown site?

**Comment by dmurdoch** [comment]
You can make a vignette that runs the demos.  It's not quite the same as running them in the console, but it's somewhat acceptable.

I think you'd need to write a `knit_print` or `pkgdown_print` method to display the list that `demo()` prints, I couldn't spot an obvious way to do that.  But if you actually run one of them, it displays the code and output.

For example, with a demo file containing these lines:
```
x <- 123
x
print(x)
```
in "testpackage/demo/test.R", and a vignette containing this:
````
This is a demo:
```{r}
library(testpackage)
demo("test", package = "testpackage")
```
````
my vignette shows this:
![Screen Shot 2023-01-25 at 12 04 10 PM](https://user-images.githubusercontent.com/1935680/214630831-ba54ede5-a8c0-4fc9-b79c-cb272af2a532.png)

Using chunk option `comment = ""` gets rid of the `#>` prefix on each line.

**Comment by friendly** [comment]
This is a very good idea. Solves the need for any pkgdown enhancement.  Maybe not so pretty, but I can try to work with that.

**Comment by dmurdoch** [comment]
On 25/01/2023 12:25 p.m., Michael Friendly wrote:
> This is a very good idea. Solves the need for any pkgdown enhancement. 
> Maybe not so pretty, but I can try to work with that.

It might be better to just copy the code into a vignette and do away 
with the demos.

Duncan

**Comment by hadley** [comment]
What @dmurdoch says — we recommend you turn your demos into vignettes 😄
