### ISSUE TITLE
How to not show plots when running examles?

### ISSUE THREAD

**Issue by eitsupi** [r-lib/pkgdown#2268]
Comes from https://github.com/nx10/httpgd/pull/129#discussion_r1086752392

First, thank you for your continued development of this wonderful package. I really like the pkgdown ecosystem.

Is there any way to suppress the display of plots in the examples?
Unwanted images were displayed in the examples of the httpgd package that provides a graphics device.

![image](https://user-images.githubusercontent.com/50911393/214597589-1e23bee8-401e-44a6-be25-634539c6d573.png)

I feel that using `in_pkgdown()` in examples is overkill.

**Comment by dmurdoch** [comment]
You could wrap the code in `\dontrun{}` or`if (interactive()) {}`.

**Comment by eitsupi** [comment]
> You could wrap the code in `\dontrun{}` or`if (interactive()) {}`.

Thank you for your prompt response.
Sorry my question is not clear, I am looking for a way not to use those methods (i.e. I want to run examples outside of pkgdown).

**Comment by dmurdoch** [comment]
In that case, I think you should use `if (!in_pkgdown())`.  I don't know why you think it is overkill; it does just what you want.  You could open a non-screen device and close it at the end, all wrapped in`\dontshow{if (in_pkgdown()){...}}`, but to me that seems like overkill.

**Comment by nx10** [comment]
@dmurdoch Thank you for your response. We used `\dontrun{}` for that reason (and others). But were now advised by CRAN to not use it anymore: https://github.com/nx10/httpgd/issues/128#issuecomment-1402297135

**Comment by hadley** [comment]
`if (!in_pkgdown())` sounds like the right fix to me.
