### ISSUE TITLE
Can pkgdown generate direct links to argument documentation?

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#2269]
i.e. I wanted to create a direct link to the `.transformer` argument of `glue()` here

<img width="808" alt="Screen Shot 2023-01-27 at 4 29 52 PM" src="https://user-images.githubusercontent.com/19150088/215209501-c1297555-296a-4208-b628-ef37d7da5b1a.png">

but the closest i can link to is Arguments https://glue.tidyverse.org/reference/glue.html#arguments

I'm fairly certain I have wanted this a few different times

**Comment by maelle** [comment]
Yes it'd be nice, I think this is a duplicate of #2228

**Comment by DavisVaughan** [comment]
Yea definitely a duplicate!
