### ISSUE TITLE
`primary` font colour not respected in navbar since new version

### ISSUE THREAD

**Issue by rempsyc** [r-lib/pkgdown#2270]
I have updated my site recently and lost the colour on the top menu banner font (it now defaults to black font). `primary` colour now only seems respected for hyperlinks. Whereas my other site has not been updated since December and looks fine:

https://rempsyc.remi-theriault.com/
https://lavaanextra.remi-theriault.com/

You can see that the menu at the top of the site is still light blue on the second but not the first one. Yet, both use the same colour for `primary`:

```
template:
  bootstrap: 5
  bslib:
    primary: "#5d8aa6"
```

https://github.com/rempsyc/rempsyc/blob/main/pkgdown/_pkgdown.yml
https://github.com/rempsyc/lavaanExtra/blob/main/pkgdown/_pkgdown.yml

Both sites are built automatically with a GHA action workflow so don't rely on local versions of packages but on development versions:

https://github.com/rempsyc/rempsyc/blob/main/.github/workflows/pkgdown.yaml
https://github.com/rempsyc/lavaanExtra/blob/main/.github/workflows/pkgdown.yaml

Is this due to a documented change in `pkgdown` not in NEWS or that I have missed? Or is there something else and obvious going on that I'm missing? Thanks,

**Comment by rempsyc** [comment]
This can also be seen on the `pkgdown` site:

`primary` is set to a type of blue:

``` r
template:
  bootstrap: 5
  bslib:
    primary: "#0054AD"
```

But the menu font is still black: https://pkgdown.r-lib.org/index.html

**Comment by maelle** [comment]
Thanks for the report. I'm now wondering what the intended behavior was. According to https://pkgdown.r-lib.org/articles/customise.html#bslib-variables it seems the current behavior is correct

> primary sets the link colour and the (translucent) hover colour in the navbar and sidebar.

:thinking: 

A workaround if you really want that color to be used for the navbar (be careful about the contrast by the way :innocent:) is to use a further BS5 variable, maybe `navbar-light-color`.

**Comment by rempsyc** [comment]
Thanks for the suggestion, I'll try that.

You mention that according to the docs the current behaviour is correct. But the docs you quoted mention that primary sets the colour for the navbar. Is the navbar not the top-level site menu? Then what is it?

**Comment by maelle** [comment]
Primary sets the hover color which is the color of the rectangle over the text. Or do you mean another sentence? (yes the navbar = the top level menu)

**Comment by maelle** [comment]
I'll let this open anyway so the maintainer can weigh in around the next release. I can't remember how pkgdown website used to look :see_no_evil: (however the home icon was removed from the default I think?)

**Comment by rempsyc** [comment]
Thanks!

- - I added the home icon manually as part of the navbar so it's strange it's not taking the specified colour of the navbar, like our option applies to text only and not icons. I also wonder if the package name is considered text or something else, perhaps that's why it's also not changing colour.

**Comment by hadley** [comment]
Current behaviour on the pkgdown website looks right to me.
