### ISSUE TITLE
Obscure equation number-related bug

### ISSUE THREAD

**Issue by gsrohde** [r-lib/pkgdown#2273]
After reading issue #323 to learn how to get equation numbers and cross references to equations to work in _pkgdown_, I found that I was getting warning messages about unfound equation labels for a few, but by no means all, of the equation references in my document.  

Since the equation numbering and references seem to be working fine in spite of the warnings, I hesitated to post an issue report about this, but as I've already spent far too long trying to narrow down the problem to a minimally-sized file, I thought I might as well post it, in case it is a sign of some larger, more consequential problem (and also since it would be reassuring not to be getting bogus warning messages).

Here's the file I came up with:
````
---
title: "Bug demo"
output: bookdown::html_document2
vignette: >
  %\VignetteIndexEntry{Bug demo}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
pkgdown:
  as_is: true
---

```{r}
"chunk 1 (with blank line)"

```

\begin{equation}
V_c = \min \{ W_c, W_j, W_p \}. (\#eq:a)
\end{equation}

```{r}
"chunk 2"
```

See Equation \@ref(eq:a).
````

Here are the messages from _pkgdown_ when building:
```
> pkgdown::build_article('bug_demo')
Reading 'vignettes/bug_demo.Rmd'
Warning message:
The label(s) eq:a not found 
```

If either chunk is removed, or if the blank line is removed from chunk 1, the warning message goes away.  With or without the warning message, the resulting document looks correct.

Also, the vignette-related lines in the metadata are inconsequential, and unnecessary when building with _pkgdown_.  But if I keep them, and build using `tools::buildVignette`, I don't get a warning message in this case either.

I'm using _pkgdown_ version 2.0.7 on _macOS_ 10.15.7 with _R_ version 4.2.0 and _Pandoc_ 3.0.1.

**Comment by hadley** [comment]
Closing in favour of #2210 where we'll have an official mechanism for this.
