### ISSUE TITLE
Long Article Title is Partially Obscured by Menu Bar

### ISSUE THREAD

**Issue by DarioS** [r-lib/pkgdown#2276]
The top part of the first line is obscured by the menu bar. A better default would be nice.

![image](https://user-images.githubusercontent.com/631218/218004020-422e3429-5e13-4251-9e52-8fe601cf9b57.png)

**Comment by maelle** [comment]
@DarioS do you use Bootstrap 3 or 5? https://pkgdown.r-lib.org/articles/customise.html#getting-started

**Comment by DarioS** [comment]
I haven't set `bootstrap: 5` so presumably version 3.

**Comment by maelle** [comment]
I've tried building your website with Bootstrap 5, in that case the title is no longer obscured by the menu bar.

**Comment by DarioS** [comment]
It works after upgrading.
