### ISSUE TITLE
use_pkgdown_github_pages permissions issue

### ISSUE THREAD

**Issue by gregorypenn** [r-lib/pkgdown#2279]
I realize this is really an issue with GitHub and not with pkgdown itself, but it has prevented me from publishing on GitHub Pages, but I have been unable to find documentation to resolve it, and I'm hoping someone here can help, and possibly add documentation to pkgdown on this topic.

I used `usethis::use_pkgdown_github_pages` to set up publishing on GitHub pages. When I push a commit to GitHub (no problem with that) it triggers the action to deploy and build the site as expected. The site appears to build successfully, but deployment fails because of a write-access issue. That seems inconsistent with being able to push, so clearly there's something I'm not understanding. The relevant section of the build/deploy log follows. I would greatly appreciate any advice and would gladly write up the solution to go somewhere in pkgdown's documentation if that would be appropriate.

```
Switched to a new branch 'github-pages-deploy-action/yg1mydceg'
/usr/bin/git commit -m Deploying to gh-pages from @ gregorypenn/BetaBayes@214677f2a17201f8004e29144b58f8613a73e0b0 🚀 --quiet --no-verify
Force-pushing changes...
/usr/bin/git push --force ***github.com/gregorypenn/BetaBayes.git github-pages-deploy-action/yg1mydceg:gh-pages
remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/gregorypenn/BetaBayes.git/': The requested URL returned error: 403
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/yg1mydceg
Reset branch 'github-pages-deploy-action/yg1mydceg'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Error: The deploy step encountered an error: The process '/usr/bin/git' failed with exit code 128 ❌
Notice: Deployment failed! ❌

```

**Comment by gregorypenn** [comment]
I suppose it's an option to remove docs from .gitignore so that gets pushed, then have Pages point there, but I'd really like to get the auto-build and deploy working.

**Comment by dmurdoch** [comment]
I think this is a relatively recent change on Github.  The solution is to set up a "personal access token" and give it permission to write to your repository.  I think `usethis` has a function to set up the token, but I noticed recently it had read-access only.  I forget where I had to go to give it write access, but that's what you need to do.

**Comment by maelle** [comment]
Could it be due to https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/? Is it a new repository?

**Comment by dmurdoch** [comment]
@maelle, I'm pretty sure that's exactly it.

**Comment by gregorypenn** [comment]
I should have mentioned that I think the personal access token I'm using is correctly configured. It originally had read-only access, but I updated it to have nearly full privileges, a lot of which appear irrelevant but these seemed like they might matter:

- Full control of private repositories
- Update GitHub actions and workflows
- write:packages
- admin:repo_hook
- project

Maybe I should try deleting the personal access token and re-creating it?

**Comment by dmurdoch** [comment]
I found the spot where I made the change.  In the repository settings, go to 

Actions | General | Workflow Permissions

and make sure "Read and Write Permissions" are selected.

**Comment by gregorypenn** [comment]
> I found the spot where I made the change. In the repository settings, go to
> 
> Actions | General | Workflow Permissions
> 
> and make sure "Read and Write Permissions" are selected.

That did it! Well, at least now GitHub says the deployment succeeded, but I'm still getting a 404 error at the URL for the site. Would that be a new issue?

**Comment by dmurdoch** [comment]
The log for the "Deploy" part of my "Pages build and deployment" action contains this near the end:

```
Created deployment for 413....
{"page_url":"https://dmurdoch.github.io/tables/","status_url":"https://api.github.com/repos/dmurdoch/tables/pages/deployment/status/413....","preview_url":""}
```

and the link in `page_url` is working for me.  Maybe you just looked too quickly?

**Comment by gregorypenn** [comment]
@dmurdoch 

I don't have that line in my deploy log. Here's the whole thing after the header:

```
Checking configuration and starting deployment… 🚦
Deploying using Deploy Token… 🔑
Configuring git…
/usr/bin/git config --global --add safe.directory /home/runner/work/BetaBayes/BetaBayes
/usr/bin/git config user.name gregorypenn
/usr/bin/git config user.email 2105889+gregorypenn@users.noreply.github.com
/usr/bin/git config core.ignorecase false
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git remote rm origin
/usr/bin/git remote add origin ***github.com/gregorypenn/BetaBayes.git
Git configured… 🔧
Starting to commit changes…
/usr/bin/git ls-remote --heads ***github.com/gregorypenn/BetaBayes.git refs/heads/gh-pages
172cf58a2c31b4209b1601120b1fadc521ce1599	refs/heads/gh-pages
Creating worktree…
/usr/bin/git fetch --no-recurse-submodules --depth=1 origin gh-pages
From https://github.com/gregorypenn/BetaBayes
 * branch            gh-pages   -> FETCH_HEAD
 * [new branch]      gh-pages   -> origin/gh-pages
/usr/bin/git worktree add --no-checkout --detach github-pages-deploy-action-temp-deployment-folder
Preparing worktree (detached HEAD f9127ff)
/usr/bin/git checkout -B gh-pages origin/gh-pages
Previous HEAD position was f9127ff Testing GitHub Pages deploy.
Switched to a new branch 'gh-pages'
branch 'gh-pages' set up to track 'origin/gh-pages'.
/usr/bin/chmod -R +rw /home/runner/work/BetaBayes/BetaBayes/docs
/usr/bin/rsync -q -av --checksum --progress /home/runner/work/BetaBayes/BetaBayes/docs/. github-pages-deploy-action-temp-deployment-folder --exclude .ssh --exclude .git --exclude .github
Checking if there are files to commit…
/usr/bin/git add --all .
/usr/bin/git checkout -b github-pages-deploy-action/b0c1xifyk
Switched to a new branch 'github-pages-deploy-action/b0c1xifyk'
/usr/bin/git commit -m Deploying to gh-pages from @ gregorypenn/BetaBayes@f9127ff4f20c938fab724422fc4f37f7dab8310b 🚀 --quiet --no-verify
Force-pushing changes...
/usr/bin/git push --force ***github.com/gregorypenn/BetaBayes.git github-pages-deploy-action/b0c1xifyk:gh-pages
To https://github.com/gregorypenn/BetaBayes.git
   172cf58..b381843  github-pages-deploy-action/b0c1xifyk -> gh-pages
Changes committed to the gh-pages branch… 📦
Running post deployment cleanup jobs… 🗑️
/usr/bin/git checkout -B github-pages-deploy-action/b0c1xifyk
Reset branch 'github-pages-deploy-action/b0c1xifyk'
/usr/bin/chmod -R +rw github-pages-deploy-action-temp-deployment-folder
/usr/bin/git worktree remove github-pages-deploy-action-temp-deployment-folder --force
Completed deployment successfully! ✅

```

**Comment by gregorypenn** [comment]
Should the build process be creating a docs directory in the repo code? In the build log I see `Writing to:   '/home/runner/work/BetaBayes/BetaBayes/docs'` and a bunch of expected stuff like `Writing 'reference/HDIofICDF.html'`, but docs doesn't appear in the repo code afterwards, so of course no docs/reference or docs/articles, either.

**Comment by dmurdoch** [comment]
Sorry, I don't know the answers.  Your log looks different than mine (which I think you can see here:  https://github.com/dmurdoch/tables/actions/runs/4178628565).  Maybe a different version of the workflow code?

**Comment by gregorypenn** [comment]
I'm going to mark this issue as closed, because the permissions issue is resolved. I'll open a new issue about the build process not going as expected.
