### ISSUE TITLE
order of news entries with one_page: false

### ISSUE THREAD

**Issue by ecmerkle** [r-lib/pkgdown#2285]
This is about the displayed order of package versions for multi-page news. 

When my changelog is all displayed on one page, the newest version of my package appears first, then the next-newest version, and so on, which seems desirable. But when I set `one_page: false` in the yaml, each individual page displays the oldest package versions first (for example, version 0.4-1 appears before 0.4-2, which appears before 0.4-3, etc). I wonder whether this is intended, and whether there is a way to make the newest package versions appear first under multi-page news.

In case it helps, the package in question is [here.](https://github.com/ecmerkle/blavaan)

**Comment by maelle** [comment]
:eyes: This is due to the `rev()` in

https://github.com/r-lib/pkgdown/blob/c354aa7e5ea1f9936692494c28c89e5bdd31fc68/R/build-news.R#L125

I am not sure why it is so (= not sure whether it's a bug or intended).

**Comment by hadley** [comment]
Sounds like a bug to me.

**Comment by hadley** [comment]
Thinking about this more, I think it's intentional, because this way each major release (which will presumably have the greatest amount of detail) will appear at the top of the page.
