### ISSUE TITLE
`<->` doesn't show up in rendered sites

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#2286]
Reported here
https://github.com/tidyverse/dplyr/issues/6769

Where you can see that the dplyr pkgdown site has a vignette title like `dplyr <-> base R` but the `<->` doesn't show up on the rendered page. It does seem to show up when looking at the title of the article in the nav bar though.

I think I'm remembering that `<->` is some kind of comment in HTML? So maybe this can't be worked around? But it would be good to confirm

**Comment by hadley** [comment]
I reviewed all the places we set the `pagetitle` and they all seem to be raw text. Even for reference topics which already does `paste0(strip_html_tags(out$title), " \u2014 ", out$name)`. So I think the right move is to escape in the template.
