### ISSUE TITLE
Add security headers

### ISSUE THREAD

**Issue by merliseclyde** [r-lib/pkgdown#2287]
I am building the website for my package `bark` using `pkgdown`. (https://github.com/merliseclyde/bark and https://merliseclyde.github.io/bark) and as part of the OpenSSF Best Practices there is a check for security and hardening of headers.   Checking this via https://securityheaders.com

[https://securityheaders.com/?q=https%3A%2F%2Fgithub.com%2Fmerliseclyde%2Fbark%2F&followRedirects=on](https://securityheaders.com/?q=https%3A%2F%2Fgithub.com%2Fmerliseclyde%2Fbark%2F&followRedirects=on) the github site passes but the  check of the pkgdown site [https://securityheaders.com/?q=https%3A%2F%2Fmerliseclyde.github.io%2Fbark%2F&followRedirects=on](https://securityheaders.com/?q=https%3A%2F%2Fmerliseclyde.github.io%2Fbark%2F&followRedirects=on) gets a D grade.

Can the security enhancements for the pkgdown site be enforced when building the website ?  (website is built via GitHub Actions)

**Comment by maelle** [comment]
Thanks for reporting! Is this something related to how the website is served, or to the source? Is the fix adding a few lines to https://github.com/r-lib/pkgdown/blob/main/inst/BS5/templates/head.html? If so you could customize your website with these few more lines (as a workaround for you, and as an example for this issue) via https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files

This might also be related to #2099 (as far as "sources" are concerned)

**Comment by hadley** [comment]
This is low priority as the majority of these headers are irrelevant for pkgdown sites.

**Comment by hadley** [comment]
Given that these headers don't do anything for pkgdown sites, I think it's unlikely we'll ever be motivated to add them, and the best approach would be to add them in your own customisations.
