### ISSUE TITLE
Custom icon in navbar

### ISSUE THREAD

**Issue by john-ioannides** [r-lib/pkgdown#2289]
Is it possible to have a custom icon in the navbar?
I've been trying using the _pkgdown.yml but can't seem to make it work.

**Comment by maelle** [comment]
What exactly is your goal? Is your website public, or could you create a reprex? https://pkgdown.r-lib.org/CONTRIBUTING.html

An example navbar with icons is https://github.com/rempsyc/rempsyc/blob/459d3150a55367de7b2ca62be3735329e3fc6c22/pkgdown/_pkgdown.yml#L14 with the resulting website https://rempsyc.remi-theriault.com. The docs are in https://pkgdown.r-lib.org/reference/build_site.html#navigation-bar

**Comment by maelle** [comment]
Where would the icon be? Could you add an annotated screenshot to this issue? 

See https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files -- note that overriding default templates is "for expert users".

**Comment by hadley** [comment]
Closing this issue since there's been no further discussion in over a month.
