### ISSUE TITLE
Formatted, plain and short titles are all displayed at the top of rendered vignette

### ISSUE THREAD

**Issue by GFabien** [r-lib/pkgdown#2296]
Hi! Thanks for the great package. It looks really nice!
We are working on submitting our package to the [Journal of Statistical Software](https://www.jstatsoft.org/index), so we created a vignette with a formatted title, a plain title, and a short title. Unfortunately, when we run `pkgdown:build_site()`, the three versions of the titles are concatenated at the top of the page. Is this a bug, or is there a way to specify somewhere that only one of the three versions should be used?
Here is a small reproducible example:
``` rmd
---
documentclass: jss
title:
  formatted: "Dummy package"
  plain:  "This is a dummy package"
  short:  "dummy"
output: rticles::jss_article
vignette: >
  %\VignetteIndexEntry{dummy}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(dummy)
```
The title on the top of the generated html page looks like this: "Dummy package,This is a dummy package,dummy".
Thank you for your help!

**Comment by GFabien** [comment]
I found the JSS example: https://github.com/r-lib/pkgdown/blob/main/vignettes/test/jss.Rmd, which directly takes the pdf vignette and solves all my problems. Therefore I wonder if this issue is relevant...

**Comment by maelle** [comment]
Nice work exploring the repo. :ok_hand: Does https://pkgdown.r-lib.org/reference/build_articles.html?q=as_is#output-formats answer all your questions then?

**Comment by GFabien** [comment]
Yes, thanks a lot!
