### ISSUE TITLE
More robust CRAN/Bioconductor package sidebar linking

### ISSUE THREAD

**Issue by AEBilgrau** [r-lib/pkgdown#2297]
Perhaps a "fringe issue". In [`cran_link`](https://github.com/r-lib/pkgdown/blob/610a3315e61272772b8b03a3ffdbc8ec6e73d1c6/R/build-home-index.R#L187) URLs are hardcoded. If these cannot be resolved, for whatever reason, the code fail. 
You can reproduce the error by pointing to non-resolvable host. 

We currently hit this as our company's corporate filter currently blocks "cloud.r-project.org". While we hopefully wait for a whitelisting, my initial thought was to use "cran.r-project.org" (which is not blocked).

Our current workarounds with disabling internet or the sidebar has undesired additional effects.

Do you consider this an issue at all?

If so, would you be willing to consider one or more of the following fixes

  1) Allowing users (e.g. via option `pkgdown.cran_mirror` and similar) to specific alternative mirrors? So that the canonical `https://cran.r-project.org/package=foo` could be used.
  2) Make more robust checks on R errors as well and not only http errors.
  3) Option to disable "`cran_link`ing" in the sidebar entirely.

Or others solutions?

**Comment by dvg-p4** [comment]
This is also a problem for me right now, since r-project.org is down at the moment. I'd like to use the https://cran.rstudio.com/ mirror, but there's no way to do so--the only workaround is to disable cran linking entirely (undesirable). I think option 1 you suggest, allowing the cran mirror to be configured, would be a reasonable solution.

**Comment by AEBilgrau** [comment]
@dvg-p4 It's quite some time since I looked at it, but I (think I) remember that toggling that option disabled some other things as well that depends on internet connectivity.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think given the other demands for pkgdown features and the relatively limited impact of this one, it's unlikely we will ever implement it. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
