### ISSUE TITLE
Incorrect rendering of comparison generics `<`, `>`, etc.

### ISSUE THREAD

**Issue by bnprks** [r-lib/pkgdown#2303]
The usage section of the html docs for S4 method implementations of comparison generics incorrectly renders `<` and `>` with `&lt;` and `&gt;`

Minimal reproducible package example here: https://github.com/bnprks/pkgdownbug (incorrectly rendered reference [here](https://bnprks.github.io/pkgdownbug/reference/ComparisonMethods.html))

An R file with text:
```R
#' Comparison methods
#'
#' Generic methods and built-in functions for MyType objects
#'
#' @name ComparisonMethods
#' @rdname ComparisonMethods
NULL

setClass("MyType")

#' @describeIn ComparisonMethods Less than comparison
setMethod("<", signature(e1= "MyType", e2= "numeric"), function(e1, e2) {return(TRUE)})
#' @describeIn ComparisonMethods Less than comparison
setMethod("<=", signature(e1= "MyType", e2= "numeric"), function(e1, e2) {return(TRUE)})
#' @describeIn ComparisonMethods Less than comparison
setMethod(">", signature(e1= "MyType", e2= "numeric"), function(e1, e2) {return(TRUE)})
#' @describeIn ComparisonMethods Less than comparison
setMethod(">=", signature(e1= "MyType", e2= "numeric"), function(e1, e2) {return(TRUE)})
```

gets a usage section rendered to html as follows:
```
# S4 method for MyType,numeric
&lt;(e1, e2)

# S4 method for MyType,numeric
&lt;=(e1, e2)

# S4 method for MyType,numeric
&gt;(e1, e2)

# S4 method for MyType,numeric
&gt;=(e1, e2)
```

**Comment by maelle** [comment]
Thanks for reporting! I don't have time to investigate right now but it looks related to #2286

**Comment by hadley** [comment]
It's already using `{{{ }}}` in the template, so it must be getting escaped elsewhere 🤔

**Comment by hadley** [comment]
Ok, at least two problems here:

* The `escape_html()` in the fallback for `highlight_text()` is (I think) generally unnecessary because `flatten_text()` calls `as_html()` which already escapes text (will need to double check this)
* We're only hitting that fallback because we're generating invalid R code because we're not handling methods for infix functions correctly.

**Comment by hadley** [comment]
Ok, the root problem is that the Rd looks like this:

```
\S4method{<}{MyType,numeric}(e1, e2)
```

and we want to generate a usage like this:

```R
# S4 method for MyType,numeric
e1 < e2
```

In particular, note that `(e1, e2)` is not the call to `\S4method{}` so we can't the existing Rd tokenization to help us solve this problem. 

It looks like [base R](https://github.com/wch/r-source/blob/e4f0669116c0837dacfa949c76f6b0f0b777b16d/src/library/tools/R/Rd2txt.R#L56-L281) effectively uses a hand-rolled tokeniser to solve this problem so we'll need to implement something similar in pkgdown.

**Comment by hadley** [comment]
After PR motivating example looks like this: 
![Screenshot 2024-06-03 at 09 59 40](https://github.com/r-lib/pkgdown/assets/4196/d165b3c6-716c-42f1-8c95-cd056f210f9e)
