### ISSUE TITLE
GitHub workflow: `Error in curl::curl_fetch_memory(url, handle = handle) :  SSL peer certificate or SSH remote key was not OK: [www.bioconductor.org]`

### ISSUE THREAD

**Issue by jack-davison** [r-lib/pkgdown#2325]
Good afternoon,

We're encountering issues with the GitHub workflow to automatically build a `{pkgdown}` site.

You can see the action here: https://github.com/davidcarslaw/deweather/actions/runs/5603209961/jobs/10249495996

The specific issue appears to be:

```r
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL peer certificate or SSH remote key was not OK: [www.bioconductor.org] SSL: no alternative certificate subject name matches target host name 'www.bioconductor.org'
```

I'm not quite sure how to handle this (especially as I don't believe we're using any bioconductor packages) so please do advise!

The site is able to be rendered locally.

**Comment by jack-davison** [comment]
Closing as this appears to have resolved itself 🙂

**Comment by maelle** [comment]
For context https://fosstodon.org/@gaborcsardi/110741646942210567
