### ISSUE TITLE
FR: Add `preview` argument to `build_reference_index()`

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2328]
To avoid having to click on the hyperlink and pressing Enter.

Happy to contribute a PR.

I see the preview argument working like `build_reference()`

Related to rstudio/rstudio#13460

**Comment by hadley** [comment]
In general, I now prefer explicitly clicking on a link to automatically popping up a browser, so while the existing auto-open behaviour won't change, I don't want to add it to more places.

**Comment by olivroy** [comment]
Makes sense! Since pkgdown links now run automatically in RStudio 2023.12 (Daily) , there is less of a need for that!
