### ISSUE TITLE
Documentation/recommendation to avoid getting stuck with an old version on the home page?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/pkgdown#2331]
Following up https://github.com/r-lib/lintr/issues/2045.

It seems the crux of our issue was two commits getting pushed at once, thus skipping the GH workflow for the first.

While this makes some sense, it does seem like a pretty easy trap to fall into, and I was not able to self-correct poking around the pkgdown documentation.

 - Is it possible for pkgdown itself to correct the mistake encountered here?
 - If not, where would be a good place to document the recommended workflow around updating the CRAN version of a pkgdown website? Maybe there should be a {usethis} helper?

**Comment by maelle** [comment]
Does https://pkgdown.r-lib.org/articles/how-to-update-released-site.html help at all? I might have misunderstood your question.

**Comment by MichaelChirico** [comment]
Thanks Maëlle, I hadn't seen that and it's indeed helpful!
