### ISSUE TITLE
Add a link to `inst/AUTHORS` page if `inst/AUTHORS` exists

### ISSUE THREAD

**Issue by eitsupi** [r-lib/pkgdown#2332]
If `inst/AUTHORS` exists, CRAN seems to automatically generate a link to that file.

![image](https://github.com/r-lib/pkgdown/assets/50911393/573888c5-e304-49f6-a2b2-76de8f7d3833)
https://CRAN.R-project.org/package=prqlr

It would be great if pkgdown could also link to the AUTHORS file in the same way.

For now, the following text is displayed, so it is not clear what `inst/AUTHORS` is to the viewer of this page.

![image](https://github.com/r-lib/pkgdown/assets/50911393/22040b56-e5b3-47ea-9dea-37ee27fb5d08)
https://eitsupi.github.io/prqlr/authors.html

**Comment by hadley** [comment]
Also note that "see inst/AUTHORS for details" is included in the DESCRIPTION, so it's not something that I think pkgdown needs to deal with.

**Comment by hadley** [comment]
Actually maybe it could just be tacked on to the end of `authors.html`.
