### ISSUE TITLE
Should `check_pkgdown()` warn if a topic is present, but has `@keywords internal`

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2337]
This would be an opinionated choice. 

But adding `@keywords internal` mostly means that the function should not be advertised.

hence my suggestion for warning in case `check_pkgdown()` finds an internal topic on the reference index.

Possibly add an argument, `warn_internal = FALSE` to make this warning go away.

**Comment by hadley** [comment]
Sometimes you do deliberately want to include an internal function, so I think this is probably something that would be annoying for many people.
