### ISSUE TITLE
Link functions to their source code on github

### ISSUE THREAD

**Issue by jranke** [r-lib/pkgdown#234]
If the source code is maintained on github.

**Comment by krlmlr** [comment]
Related: #181.

**Comment by jranke** [comment]
Ah yes - I believe I have even seen that before but didn't remember ... Closing this issue then.

**Comment by krlmlr** [comment]
Well, the function's source may be a different link than the documentation source, so this looks like a slightly different issue to me.

**Comment by jranke** [comment]
Well, if roxygen is used, these may be the same. But in other cases, the docs live in different files, so reopening... Thanks for the heads up!

**Comment by hadley** [comment]
Is this possible? How do you go from a documentation file to a srcref? The only way I can see would be to parse the usage and look up the object in the package, but that's going to be a lot of work to do in general.

**Comment by krlmlr** [comment]
From `?dplyr::bind`:

```r
parse(text = "bind_rows(..., .id = NULL)

bind_cols(...)

combine(...)
") %>%
  lapply("[[", 1) %>%
  lapply(as.character) %>%
  lapply(get) %>%
  lapply(getSrcref)
```

This is for functions, S3/S4 methods could be harder indeed. Where would you place the links in the rendered documentation -- in the usage section?

**Comment by hadley** [comment]
Ideally, you'd link to specific line numbers, but that would tie it to a specific commit in the code.

**Comment by krlmlr** [comment]
For editing documentation: The "source" of an .Rd file is given in the backref comments in the first two lines, and these may be very different from the source of the function. So we'd need to parse both usage and backref comment.

**Comment by hadley** [comment]
Hmmm, I think I've been overthinking this. A good place to start would be to simply link each .html file back to the source .Rd/.R/.Rmd. For .Rd generated by roxygen2 we can parse the first line, and then link to each file mention there.

**Comment by jranke** [comment]
Sorry about this. I think the whole issue was just a bit of wishful thinking...

**Comment by hadley** [comment]
For now, I'm most interested in enabling people to edit the file that generated the webpage. That's simple enough to do, and we can work out how to link to the function source later

**Comment by krlmlr** [comment]
Excited to try it out!

**Comment by bmreiniger** [comment]
Would it be easy to extend this to Enterprise Githubs?
