### ISSUE TITLE
pkgdown fails to include rendered gifs in rmd articles

### ISSUE THREAD

**Issue by thomasp85** [r-lib/pkgdown#2341]
Using gganimate to render animation into gifs no longer works in vignettes/articles, with pkgdown throwing the following type of warning:

```
Warning message:
Missing images in 'vignettes/gganimate.Rmd': '../docs/articles/gganimate_files/figure-html/unnamed-chunk-3-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-4-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-5-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-6-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-8-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-9-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-10-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-11-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-12-1.gif', '../docs/articles/gganimate_files/figure-html/unnamed-chunk-14-1.gif'
ℹ pkgdown can only use images in 'man/figures' and 'vignettes' 
```

Looking at the rendered site, the gifs has been removed from the output. However, the rendered gifs are present in the corresponding `figure-html` folder

**Comment by hadley** [comment]
Could you provide a minimal reprex to help us to track down the root cause?

**Comment by trevorld** [comment]
I've created a minimal reprex of this issue here: https://github.com/trevorld/pkgdown.gganimate

**Comment by hadley** [comment]
Is this the same problem as #2334? i.e. does setting `options(knitr.graphics.rel_path = FALSE)` in the doc fix the problem?

**Comment by hadley** [comment]
Hmmm, seems similar, but setting that option doesn't appear to help.
