### ISSUE TITLE
Tabs in Articles not working

### ISSUE THREAD

**Issue by djhocking** [r-lib/pkgdown#2346]
It looks like tab functionality in articles was added a while ago but they are not working for me. I'm not sure what the problem is. I tried removing my custom _pkgdown.yml file, installing the pgkdown version from github, deleting the docs/ folder, and then rerunning build_site(). I even tried adding the rendering.Rmd test example (https://github.com/r-lib/pkgdown/blob/HEAD/vignettes/test/rendering.Rmd) and that doesn't display the tabs when it builds, it just has them as normal sections. The tabs do work fine when I knit outside of building the package webpage with pkgdown.

Is there something else I need to do that I missed? Thanks for any help.

Session/System Info:
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux 8.8 (Ootpa)

**Comment by maelle** [comment]
:wave: @djhocking!

Does https://pkgdown.r-lib.org/articles/test/rendering.html#tabsets work for you?

I've just rebuilt pkgdown website locally using the latest versions of all the dependencies and it still works.

On what browser are you? Do you see any error in the [web developer console](https://rmd-blogging-blr.netlify.app/webdev/devtools/)?

Can you link to your repo so I might try and build it?

**Comment by djhocking** [comment]
Hi @maelle :)

When I view the pkgdown site that you link above the tabs look great. When I knit my own they look great. But when I build them the site in pkgdown it doesn't render the tabs. My package has confidential info so I created a new test package and have the same issue: https://github.com/noaa-garfo/testtabs

We have checkpoint running on our server so all users starting RStudio with the startup message:

> Using checkpoint directory /home/dhocking/.checkpoint/2022-06-23/lib/x86_64-pc-linux-gnu/4.2.1

but in troubleshooting this I installed the github version of pkgdown into my personal library which would override any version in the shared library that checkpoint uses. The only thing I can think of is that pkgdown loads an older version from the checkpoint when building in a clean environment (not using my local version).

I'm using google chrome. I see webkit-box-sizing: border box crossed out in the developer console but I am not familiar with it. I can look into it more tomorrow and maybe compare it to what happens when I knit it and it renders fine. 

Thanks for any help or ideas

**Comment by maelle** [comment]
I can reproduce the problem, and fix it by switching to Bootstrap 5 in the website pkgdown configuration https://pkgdown.r-lib.org/articles/customise.html#getting-started 

Could you please try that?

**Comment by djhocking** [comment]
Oh that worked! I remember the announcement for the switch to bs5 but I was thinking using the pkgdown >2.0 meant it was automatic. I should have tried the configuration. Thanks so much!

**Comment by maelle** [comment]
what's automatic is the configuration by `usethis::use_pkgdown()`
