### ISSUE TITLE
Feature request: Add "report an issue" link/button

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/pkgdown#2347]
One feature I love about the [quarto documentation](https://quarto.org/docs/reference/formats/presentations/beamer.html) is that it includes links to "Edit this page" and "Report an Issue". These would be nice to have in pkgdown sites as well. At least as an option

<img width="828" alt="Screenshot 2023-10-03 at 11 46 04 AM" src="https://github.com/r-lib/pkgdown/assets/14034784/a394ea29-250a-4df9-a315-d5f35d79d8f1">

**Comment by dmurdoch** [comment]
I think you can already do that following the instructions in https://pkgdown.r-lib.org/articles/customise.html .  For example, add this to your pkgdown.yml file:

    home:
      links:
      - text: Edit this page
        href: https://some.url
      - text: Report an issue
        href: https://github.com/you/yourpackage/issues

**Comment by EmilHvitfeldt** [comment]
True, but the edit this page url would need to be different for each document. Which I don't see possible with the current way to customize

**Comment by hadley** [comment]
The problem is that this would only work for vignettes, as tracing references docs from .Rd back to the correct line in the `.R` files is not currently possible. So to me, that makes me feel like it's not worth the effort since it will only affect a few packages.
