### ISSUE TITLE
build_site: Datetime of site build in footer

### ISSUE THREAD

**Issue by esimms999** [r-lib/pkgdown#2356]
Apologies if this has already appeared in Issues; I looked through and did not see any mention. And it MUST have been discussed many times before!

The default footer produced with pkgdown::build_site() looks like this:

![current_footer](https://github.com/r-lib/pkgdown/assets/10915780/b95cccb1-fd37-43f5-bfbb-92cb1a77c338)

I would like to also display the datetime when the site was last modified:

![proposed_footer](https://github.com/r-lib/pkgdown/assets/10915780/4c92009f-9af6-41d7-aed0-bdece3421084)

I expected that pkgdown would have this available, but I have not been successful in finding anything on this. When it comes to having dates visible on package-related documentation, I found the following in [R Packages: Chapter 17.2](https://r-pkgs.org/vignettes.html#metadata), which mentions the yaml for a vignette:

```datee: we think this usually does more harm than good, since it’s not clear what the date is meant to convey. Is it the last time the vignette source was updated? In that case you’ll have to manage it manually and it’s easy to forget to update it. If you manage date programmatically with Sys.date(), the date reflects when the vignette was built, i.e. when the package bundle was created, which has nothing to do with when the vignette or package was last modified. We’ve decided it’s best to omit the date.```

I think it is worthwhile to automatically display the date when the entire site was last built, and to do so in a manner which makes it obvious we are talking about the entire package. This is useful information, which should be readily available, for developers and users. Once in production, the reason(s) for modification can be mentioned in the NEWS.md file.

I have found a way to do this, but it is messy. I hope there is a better way; I would appreciate any comments about this.

According to the [pkgdown documentation](https://pkgdown.r-lib.org/reference/build_site.html#footer), there are three pre-defined components available for the footer block:

  + developed_by, a sentence describing the main authors of the package
  + built_with, a sentence advertising pkgdown
  + package, the name of the package.
and the default structure makes use of two of them:

```
footer:
  structure: 
    left: developed_by
    right: built_with
```

Unfortunately, something like build_date is not available.

We can create our own components and these can be text or R expressions. In my _pkgdown.yml, I have defined two components and then specified, in the structure, where I want these components to appear:

```
footer:
  structure:
    left: developed_by
    right: [built_with, built_text, built_date]
  components:
    built_date: !expr "format(Sys.time(), '%Y-%m-%d %H:%M %Z')"
    built_text: "<br>on "
```

Running pkgdown::build_site() produces the following footer:

![unresoled](https://github.com/r-lib/pkgdown/assets/10915780/8b926bc0-61ef-44f7-b045-c52bff629f48)

It will work properly if I do this:
```
options(yaml.eval.expr = TRUE)
```

... which I would prefer to avoid; there are security concerns, which is why this option defaults to FALSE.

**Comment by esimms999** [comment]
To summarize, I am hoping that a pre-defined component, build_date, can be made available. :)

**Comment by esimms999** [comment]
```It will work properly if I do this:

options(yaml.eval.expr = TRUE)
... which I would prefer to avoid; there are security concerns, which is why this option defaults to FALSE.
```

I just discovered {withr}:

```
withr::with_options(list(yaml.eval.expr = TRUE), pkgdown::build_site()
```
... which should take care of security concerns.

I am still hoping for an easier (more obvious) way to do this.

**Comment by hadley** [comment]
Thanks for filing this issue! Unfortunately, I think it's out of scope for this package: developing good software requires relentless focus, which means that we have to say no to many good ideas. Even though I'm closing this issue, I really appreciate the feedback, and hope you'll continue to contribute in the future 😄
