### ISSUE TITLE
Run html-validate on docs/ to find problems to fix?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2369]
Examples of things I see

- Prefer to use the native <button> element (for the navbar dropdown, there are elements with `role="button"`)
- Trailing whitespaces
- Use of conditional comments are deprecated (in the head, something about IE)

Maybe some of those are worth fixing.

https://www.npmjs.com/package/html-validate

**Comment by hadley** [comment]
IMO this is only worth doing if we can automate, preferably with an R package.

**Comment by hadley** [comment]
Maybe we could just make it part of the release process? i.e. run `vnu` on pkgdown's own site?

**Comment by maelle** [comment]
yes! I'd need to run it on the current website, to see what it returns. :sweat_smile:

**Comment by hadley** [comment]
A lot of repeated warnings like this:

```
"file:/Users/hadleywickham/Documents/devtools/pkgdown/docs/dev/reference/build_site.html":2.140-2.161: error: A document must not include both a “meta” element with an “http-equiv” attribute whose value is “content-type”, and a “meta” element with a “charset” attribute.
"file:/Users/hadleywickham/Documents/devtools/pkgdown/docs/dev/reference/build_site.html":270.1-270.17: error: Duplicate ID “cb1-3”.
```

I can't figure out where either of those is generated 😭

**Comment by maelle** [comment]
Reading the docs for `read_html()` reminded me of https://github.com/r-lib/xml2/issues/432 (I nearly opened a duplicate issue :sweat_smile:)

**Comment by maelle** [comment]
https://gitlab.gnome.org/GNOME/libxml2/-/issues/507

**Comment by hadley** [comment]
Having tried `html-validate`, it produces vastly superior output to vnu. I've fixed the most obvious low-hanging fruit and I think that's probably sufficient. I don't think running it regularly is going to be terribly useful as there a few false positives or things that just aren't going to be worth fixing given the potential gain.
