### ISSUE TITLE
Request to use logos in publication figure

### ISSUE THREAD

**Issue by bschilder** [r-lib/pkgdown#2370]
Our [manuscript](https://www.researchsquare.com/article/rs-2399015/v1) introducing [`rworkflows`](https://github.com/neurogenomics/rworkflows) has been conditionally accepted to Nature Communications pending some edits. 

Currently, Figure 1 includes the `pkgdown` and `Rstudio` logos (see attached). However in order to use these we would need the explicit approval of the copyright holders (which would be [Posit](https://posit.co/), if I'm not mistaken).
[fig1.pdf](https://github.com/r-lib/pkgdown/files/13364394/fig1.pdf)

If for any reason you'd prefer us not to reproduce the logos, please do let us know and we can remove them instead.

All the best, 
Brian
_______________
Brian M. Schilder
PhD Candidate
Neurogenomics Lab
Faculty of Medicine, Department of Brain Sciences
UK Dementia Research Institute, Imperial College London
CV | [bschilder.github.io/CV/CV](https://bschilder.github.io/CV/CV.html)
LinkedIn | [linkedin.com/in/brian-schilder](https://www.linkedin.com/in/brian-schilder/)
Website I | [bschilder.github.io/BMSchilder](https://bschilder.github.io/BMSchilder/)
Twitter | [twitter.com/BMSchilder](http://www.twitter.com/BMSchilder)
Lab | [neurogenomics.co.uk](https://www.neurogenomics.co.uk/)

**Comment by hadley** [comment]
All our logos are licensed as CC0, so no need to ask permission: https://github.com/rstudio/hex-stickers

**Comment by bschilder** [comment]
Thanks @hadley. It's since been published in Nature Communications: 

> Schilder, B.M., Murphy, A.E. & Skene, N.G. rworkflows: automating reproducible practices for the R community. Nat Commun 15, 149 (2024). https://doi.org/10.1038/s41467-023-44484-5
