### ISSUE TITLE
Resize Posit logo on citations page

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2379]
https://pkgdown.r-lib.org/authors.html#citation

**Comment by hadley** [comment]
The `img` correctly has `height="16"`, but the CSS `main img` overrides it was `height: auto`.  Not immediately obvious to me how to fix this 🤔

**Comment by hadley** [comment]
Hmmmm, why are we setting `height: auto` in the first place?  

A bit of spelunking revealed that the css has been there a long time, https://github.com/r-lib/pkgdown/commit/3c000b70af1d57bcc09d91689e7e0882eda5b1b6, but it's not clear to me why its needed.

**Comment by hadley** [comment]
Ok, the problem is that if we just set the max-width, when the page is made narrow, the height is not rescaled.

But if I set the width of the image explicitly, the problem goes away. So I think the simplest fix is to add an explicit width in tidytemplate.

**Comment by hadley** [comment]
Oops, but pkgdown doesn't use tidytemplate, so I also needed to fix locally.
