### ISSUE TITLE
Run a `pkgdown_sitrep()` at the end of each build?

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2380]
Seems useful to debug problems early.

**Comment by hadley** [comment]
We do put two important versions in https://pkgdown.r-lib.org/pkgdown.yml. Do you think it's worth adding more there? 

Otherwise we usually do a sitrep earlier in the build process in our GitHub actions.

**Comment by jayhesselberth** [comment]
I was thinking of adding it at the end of `build_site()` so that users get feedback interactively after a build.

**Comment by hadley** [comment]
If we do this, I think we'd need to figure out how to automate the "double-check" advice, since it's not going to be useful to advice people to double-check the urls after every run.

Also, the warning for first check could be improved:

```R
# old
" is misconfigured. See {.vignette pkgdown::metatdata}."

# new
" is absent. See {.vignette pkgdown::metadata}."
```
