### ISSUE TITLE
Markdown syntax for resizing images in README.md breaks on pkgdown site

### ISSUE THREAD

**Issue by DeepanshKhurana** [r-lib/pkgdown#2389]
Markdown offers an image resizing mechanism with the following syntax.

```md
![alt_text](man/figures/image.png =WIDTHxHEIGHT)
```

When used in a markdown document, this resizing works great. But when this same README.md is used by pkgdown, the path it will create is `http://site.url/reference/figures/image.png%20=WIDTHxHEIGHT`.

This is a problem because the image exists at `http://site.url/reference/figures/image.png`.

It seems a quick and easy fix is to resize the images before putting them in but I wonder if this can be fixed on the `pkgdown` side of things anyway.

Of course, `pkgdown` does raise a warning for this which should be enough to at least investigate this issue but it seems a bit counter-intuitive when the images exist and only the path gets broken.

**Comment by DeepanshKhurana** [comment]
Essentially, something similar to the following could be called in the correct place (before the markdown is converted to HTML).

```r
strip_image_resize_params <- function(image_path) {
  gsub("\\s*=\\d+x\\d+", "", image_path)
}
```

**Comment by hadley** [comment]
That doens't look like any markdown syntax I'm familiar with, and doesn't look like it's supported by pandoc: https://pandoc.org/MANUAL.html#images. That makes it very difficult to support it in pkgdown.

**Comment by DeepanshKhurana** [comment]
Ah, so the better thing would be to raise it with `pandoc` instead. I also failed to mention that this was a document on [AzureDevOps](https://learn.microsoft.com/en-us/azure/devops/project/wiki/markdown-guidance?view=azure-devops#images:~:text=Resize%20image%3A%20IMAGE_URL%20%3DWIDTHxHEIGHT) and I've seen this implementation work in some but not all places. My bad for not including a reference.

I'll check if I can get `pandoc` to support this, and maybe then it can come downstream.

 In any case, thanks for the reply!
