### ISSUE TITLE
Usage of pkgdown for _not_ a package

### ISSUE THREAD

**Issue by rsangole** [r-lib/pkgdown#2405]
Hello!

Firstly, thank you to all the authors and maintainers of such a fantastic package! 👏🏼 

Now to my ❓ : Is it possible to use pkgdown to generate a website for an R project which is _not_ a package? I have a use case, where I have a couple of folders, each with files containing R functions. All the functions are documented with roxy comments. I do not wish to make these into R packages (for various reasons), but I'd love to have one website which gives the user the same experience as one would if it were an R package.

Cheers!
Rahul

**Comment by maelle** [comment]
You can try to use pkgdown for your use case, but it's off-label use so doesn't come with any warranty. :wink: 
For questions related to projects, I'd recommend using the forum https://community.rstudio.com/
Good luck!
