### ISSUE TITLE
build_articles() works locally but deployment to Github pages fails on build site because of error in article

### ISSUE THREAD

**Issue by margotbligh** [r-lib/pkgdown#2407]
Hello,

I am developing a package (margotbligh/GlycoAnnotateR) and using pkgdown to build the website. I wrote the tutorial (lcms_annotation_tutorial.Rmd) and saved it into the vignettes directory. It uses example data stored under inst/example_data. When I run `build_articles()` locally, the article for the tutorial is built successfully and looks as intended in the generated html file. However, when I push a commit with the tutorial from to Github remote, the deployment of the pages with the tutorial as an article fails. It repeatedly fails on the 'Build site' step, with the following error:

```
Quitting from lines 62-77 [import data] (lcms_annotation_tutorial.Rmd)
--------------------------------------------------------------------------------
Error in `map()`:
ℹ In index: 1.
Caused by error in `render_rmarkdown()`:
! Failed to render RMarkdown
Caused by error:
! in callr subprocess.
Caused by error:
! Can not open file /home/runner/work/GlycoAnnotateR/GlycoAnnotateR/inst/example_data/M31_20230717_stds_DDA_neg_06.mzML! Original error was: Error in eval(expr, envir, enclos): [MSDataFile::readFile()] Unsupported file format.
Backtrace:
     ▆
  1. └─MSnbase::readMSData(...)
  2.   └─MSnbase::hasSpectra(files)
  3.     ├─BiocGenerics::sapply(files, mzR:::.hasSpectra)
  4.     └─base::sapply(files, mzR:::.hasSpectra)
  5.       └─base::lapply(X = X, FUN = FUN, ...)
  6.         └─mzR (local) FUN(X[[i]], ...)
  7.           └─mzR::openMSfile(x)
  8.             └─base::tryCatch(...)
  9.               └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 10.                 └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11.                   └─value[[3L]](cond)
Execution halted
Error: Process completed with exit code 1.
```

While the error is related to the reading of the file by MSnbase, I believe the error is related to pkgdown, as the tutorial runs locally and the files are read successfully. Could you provide any assistance in identifying why this error is occurring? Or is there a way to use the rendered html file to add the article to the site?

Please let me know if you need any more information, cheers.

**Comment by dmurdoch** [comment]
Normally to read a file that you put in `inst` you would use `system.file` to find the installed copy.  In your case that would be `system.file("example_data/M31_20230717_stds_DDA_neg_06.mzML", package = "GlycoAnnotateR")`.

**Comment by margotbligh** [comment]
Thanks for the quick reply. I have updated the tutorial to find the data files using system.file, as such:

```
fp <- system.file(c('example_data/M31_20230717_stds_DDA_neg_06.mzML',
                    'example_data/M31_20230717_stds_MS1_neg_05.mzML',
                    'example_data/M31_20230718_stds_DDA_neg_04.mzML'), 
                  package = 'GlycoAnnotateR')
```

However, I get a similar error when I push the commit to Github remote and pkgdown tries to build the site:

```
Quitting from lines 56-74 [import data] (lcms_annotation_tutorial.Rmd)
--------------------------------------------------------------------------------
Error in `map()`:
ℹ In index: 1.
Caused by error in `render_rmarkdown()`:
! Failed to render RMarkdown
Caused by error:
! in callr subprocess.
Caused by error:
! Can not open file /home/runner/work/_temp/Library/GlycoAnnotateR/example_data/M31_20230717_stds_DDA_neg_06.mzML! Original error was: Error in eval(expr, envir, enclos): [MSDataFile::readFile()] Unsupported file format.
Backtrace:
     ▆
  1. └─MSnbase::readMSData(...)
  2.   └─MSnbase::hasSpectra(files)
  3.     ├─BiocGenerics::sapply(files, mzR:::.hasSpectra)
  4.     └─base::sapply(files, mzR:::.hasSpectra)
  5.       └─base::lapply(X = X, FUN = FUN, ...)
  6.         └─mzR (local) FUN(X[[i]], ...)
  7.           └─mzR::openMSfile(x)
  8.             └─base::tryCatch(...)
  9.               └─base (local) tryCatchList(expr, classes, parentenv, handlers)
 10.                 └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
 11.                   └─value[[3L]](cond)
Execution halted
Error: Process completed with exit code 1.
```

**Comment by dmurdoch** [comment]
Your script specifies `install = FALSE` in the call to `pkgdown::build_site_github_pages`.  Change this line:  https://github.com/margotbligh/GlycoAnnotateR/blob/c30022d3b84c85532fc4dc2f8e3a150afa92ac0f/.github/workflows/pkgdown.yaml#L39 to specify `install = TRUE`, and I think it should work.

**Comment by margotbligh** [comment]
Thank you for the suggestion. I changed line 39 to `install = TRUE`, but unfortunately I get the same error

**Comment by margotbligh** [comment]
Hi, I have realised that the issue is that the installed versions of the mzML example data files are not correct, so this is an installation issue not a pkgdown issue. Thanks for all your help!
