### ISSUE TITLE
Combine `check_pkgdown()` and `pkgdown_sitrep()`

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#2463]
Probably want to keep current behaviour where `check` errors and `sitrep` does not, but they should perform the same checks.

**Comment by olivroy** [comment]
Also shouldn't `build_site()`, especially `build_site_github_pages()` call `check_pkgdown()` first? It would error more quickly if it has to.

**Comment by jayhesselberth** [comment]
I would suggest running `check` at the top of `sitrep`, and if `check` throws an error, catch it, and add to the list of warnings:

		x Problems found in `_pkgdown.yml`. Run `check_pkgdown()`.

Agree that adding `sitrep` at the top of `build_site` is a good idea.
