### ISSUE TITLE
Numeric data formatted as phone numbers in mobile Chrome browser

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#2488]
In pkgdown websites, the mobile Chrome browser can sometimes format numeric outputs as phone numbers. 

E.g. 
https://testthat.r-lib.org/reference/expect_output.html#ref-examples

![image](https://github.com/r-lib/pkgdown/assets/11330453/9085d0ee-a0c9-4dd4-8c3e-baf9e9ed6e8a)

Since it's not guaranteed that accidentally clicking on it is going to be always innocuous, maybe it's better to turn off such formatting. IINM, the following meta tag might achieve that:

```html
<meta name="format-detection" content="telephone=no" />
```

**Comment by hadley** [comment]
IMO this seems like a browser specific issue to me, and not something that pkgdown should concern itself with.
