### ISSUE TITLE
`pkgdown::build_site()` ignores `override` argument when selecting development mode

### ISSUE THREAD

**Issue by dshemetov** [r-lib/pkgdown#2503]
In the docs for `build_site()`, it says that the intent behind the `override` argument is 

> An optional named list used to temporarily override values in _pkgdown.yml

However, to override the development mode, the separate `PKGDOWN_DEV_MODE` env var has to be set. This is reflected in the code [here](https://github.com/r-lib/pkgdown/blob/2dc1877830c823bed1aa89546e84fbd95141a818/R/development.R#L1-L56). It's a bit confusing and unexpected. What was the reason for needing two overrides here?

**Comment by hadley** [comment]
Judging from my read of the code, `PKGDOWN_DEV_MODE` will only be used if it is set. And this reprex looks fine to me:

``` r
library(pkgdown)

x <- pkgdown::as_pkgdown(override = list(development = list(mode = "devel")))
str(x$development)
#> List of 4
#>  $ destination  : chr "dev"
#>  $ mode         : chr "devel"
#>  $ version_label: chr "danger"
#>  $ in_dev       : logi TRUE

x <- pkgdown::as_pkgdown(override = list(development = list(mode = "release")))
str(x$development)
#> List of 4
#>  $ destination  : chr "dev"
#>  $ mode         : chr "release"
#>  $ version_label: chr "muted"
#>  $ in_dev       : logi FALSE
```

<sup>Created on 2024-04-29 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Perhaps you could explain the problem you are seeing?

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
