### ISSUE TITLE
I don't know how to choose a series of builds for devtools and pkgdown？

### ISSUE THREAD

**Issue by chuxinyuan** [r-lib/pkgdown#2507]
Like devtools::install_github and remotes::install_github，I don't know who is copying who, there are some cross-repeating functions that make me not know their differences and connections, and what is the optimal choice, and I want a package that only wants to do one thing and do it well.

I hope devtools includes the necessary and sufficient functions needed to develop R packages, where building websites is an unnecessary feature. pkgdown is responsible for generating all the functions needed for the website.

The above personal humble opinion is for reference.

**Comment by hadley** [comment]
What is your question?

**Comment by chuxinyuan** [comment]
The build_* function in the devtools package should be in pkgdown except for the blild package.

Or merge the two packages, or even merge more tools for developing R packages, instead of being scattered around, I just need to load pkgtools one package to complete all the tools I need to develop R.

**Comment by hadley** [comment]
I don't understand your point. All the website building code does live in pkgdown. devtools exists primarily to pull together multiple package development packages together (much like tidyverse) so you can (a) install them all at once and (b) have the most commonly used functions in one place.
