### ISSUE TITLE
Links to source files are wrong when package is located in a subfolder

### ISSUE THREAD

**Issue by MLopez-Ibanez** [r-lib/pkgdown#2531]
For this DESCRIPTION file: https://github.com/multi-objective/moocore/blob/main/r/DESCRIPTION
which contains:

```
URL: https://multi-objective.github.io/moocore/r/, https://github.com/multi-objective/moocore/r/
```

The source links should point to the subfolder "r/" within the repository. However, this is not the case: https://multi-objective.github.io/moocore/r/reference/epsilon.html

The source links point to : https://github.com/multi-objective/moocore/blob/HEAD/R/epsilon.R
instead of: https://github.com/multi-objective/moocore/blob/HEAD/r/R/epsilon.R

See also: https://github.com/multi-objective/moocore/blob/main/r/_pkgdown.yml

**Comment by hadley** [comment]
You'll need to manually add set the repo source, as described in URL: https://pkgdown.r-lib.org/reference/build_site.html#source-repository.

Our logic isn't quite sophisticated enough to handle every url variation, so sometimes you'll need to supply it explicitly.
