### ISSUE TITLE
Make sitrep reporting more obvious on GitHub

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#2549]
Using https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-warning-message

**Comment by hadley** [comment]
Also should flag missing favicons

**Comment by hadley** [comment]
I think we can just implement in `error_to_sitrep()`.

**Comment by maelle** [comment]
In a PR where the error happens for several commits in a row, how to not generate spam?

**Comment by hadley** [comment]
I think GitHub deals with it — this is the same technique that lintr uses and it does seem too annoying.

**Comment by hadley** [comment]
This comes our extremely subtly, so I no longer think it's worth it:

![Screenshot 2024-06-03 at 16 36 15](https://github.com/r-lib/pkgdown/assets/4196/ae26538c-679f-4337-8f21-3bc0dde04f02)
