### ISSUE TITLE
Generating favicons produces `"Path exists and overwrite is FALSE"` error with devel-pkgdown

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#2553]
CI logs: https://github.com/IndrajeetPatil/statsExpressions/actions/runs/9120963709/job/25079334023?pr=279

```r
── Building favicons ───────────────────────────────────────────────────────────
ℹ Building favicons with <https://realfavicongenerator.net/> ...
Error: Error: Path exists and overwrite is FALSE
```

**Comment by hadley** [comment]
There are two problems here:

* `build_favicons()` shouldn't be run by default in CI
* If you do manually run it, you shouldn't get that error

**Comment by IndrajeetPatil** [comment]
I am not manually running this step in CI, it is run as part of `pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)`; I am using the standard pkgdown GHA [workflow](https://github.com/IndrajeetPatil/statsExpressions/actions/runs/9120963709/workflow?pr=279).

The workflow has been working with devel-pkgdown fine for a long time; the change in behaviour seems to be related to changes made in https://github.com/r-lib/pkgdown/commit/350854a16b8cdccdabff4707d952c9b578bc598a#diff-26463c4a1c19b09efab07b1bf9d404f4103a028f98a8cd2dd0f810bded97cee0.

---

Here is a minimal reprex showing how that change is not backward-compatible:

### Before

``` r
tmp <- tempfile()
on.exit(unlink(tmp))
result <- httr::RETRY(
  "GET",
  "http://httpbin.org/status/200",
  httr::write_disk(tmp),
  quiet = TRUE
)
```

<sup>Created on 2024-05-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

### After

``` r
tmp <- withr::local_tempdir()
result <- httr::RETRY(
  "GET",
  "http://httpbin.org/status/200",
  httr::write_disk(tmp),
  quiet = TRUE
)
#> Error: Path exists and overwrite is FALSE
```

<sup>Created on 2024-05-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by hadley** [comment]
GHA = CI

**Comment by IndrajeetPatil** [comment]
Yes, I am aware. I have a [100-page slidedeck](https://indrajeetpatil.github.io/preventive-r-package-care/#/preventive-care-for-r-packages) on how to use GHA/CI for effective R package development.

**Comment by IndrajeetPatil** [comment]
A workaround here is to just store the favicons in `pkgdown/favicon` folder so that the pkgdown workflow doesn't need to generate it each time, sidestepping the current issue.
