### ISSUE TITLE
template_reference should not add single quotes and ` when they are not needed.

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2561]
They are only needed if there are spaces or special characters.

they are explicitly added in pkgdown:::default_articles_index, default_reference_index. That's possibly safer?

Maybe this could be made dependant on whether session is interactive or not?

And they seem to be automatically added by yaml::as.yaml().

`template_navbar()` on the other hand prints properly in interactive session!

**Comment by hadley** [comment]
Why is a problem that they're added?

**Comment by olivroy** [comment]
I thought that their use case was to help create organization reference interactively.

But if you call it, it is a bit ugly to use as a template with all these extra `' I can propose something.

1. I have a new package and I want to build its pkgdown index.
2. I call `template_reference()` as a starting point.

```r
template_reference()
reference:
- title: All functions
  contents:
  - '`as_pkgdown`'
  - '`build_articles`'
  - '`build_favicons`'
  - '`build_home_index`'
  - '`build_news`'
  - '`build_redirects`'
  - '`build_reference`'
  - '`build_search`'
  - '`build_site`'
  - '`build_site_github_pages`'
  - '`build_tutorials`'
  - '`check_pkgdown`'
  - '`clean_site`'
  - '`deploy_to_branch`'
  - '`in_pkgdown`'
  - '`init_site`'
  - '`preview_site`'
  - '`rd2html`'
  - '`render_page`'
  - '`template_navbar`'

```

I find the '` noisy, and I would have to delete them by hand, before organizing my functions in themes.

**Comment by hadley** [comment]
Oh, gotcha. I had forgotten what those functions were for.
