### ISSUE TITLE
Possible to change the default build directory ?

### ISSUE THREAD

**Issue by avhz** [r-lib/pkgdown#2569]
Hi, not really an issue, I am just wondering if it is possible to specify a different directory for where the `docs/` directory is placed when running `pkgdown::build_site()` ?

I can of course just `cp` it after building, but if I can do it with a `_pkgdown.yml` field or similar that would be nice. 

Cheers :)

**Comment by hadley** [comment]
You can set the `destination` field: https://pkgdown.r-lib.org/reference/build_site.html#general-config

**Comment by avhz** [comment]
Ah I missed that one, cheers Hadley.
