### ISSUE TITLE
Error when re-building site when package man pages have aliases starting with `[<-`

### ISSUE THREAD

**Issue by trevorld** [r-lib/pkgdown#2582]
* This seems to be is a duplicate of #2505 with a minimal reproducible example.
* I've created a minimal, reproducible example: https://github.com/trevorld/pkgdown.issue2505
* This reproduces for me with {pkgdown} development and release
* Seems to be an erorr when re-building site when the package has man pages that have aliases starting with `[<-`?
* Error doesn't occur if you delete the site and call `pkgdown::build_site()` but it will occur if you call `pkgdown::build_site()` a second time without deleting the site beforehand:

```r
unlink("docs", recursive = TRUE)
pkgdown::build_site()
pkgdown::build_site()
```
```
── Installing package pkgdown.issue2505 into temporary library ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
── Building pkgdown site for package pkgdown.issue2505 ─────────────────────────
Reading from: /home/trevorld/a/projects/R/pkgdown.issue2505
Writing to: /home/trevorld/a/projects/R/pkgdown.issue2505/docs
── Sitrep ──────────────────────────────────────────────────────────────────────
✔ URLs ok.
✔ Open graph metadata ok.
✔ Articles metadata ok.
✔ Reference metadata ok.
── Initialising site ───────────────────────────────────────────────────────────
── Building home ───────────────────────────────────────────────────────────────
Reading README.md
Writing 404.html
── Building function reference ─────────────────────────────────────────────────
Reading man/Extract.bm_matrix.Rd
── Building sitemap ────────────────────────────────────────────────────────────
Error: 
! in callr subprocess.
Caused by error in `.f(.x[[i]], ...)`:
! Failed to wrap URL "https://trevorldavis.com/R/pkgdown.issue2505/reference/[<-.bm_bitmap.html"
Caused by error in `read_xml.raw()`:
! StartTag: invalid element name [68]
ℹ See `$stderr` for standard error.
Type .Last.error to see the more details.

Enter a frame number, or 0 to exit   

1: pkgdown::build_site()
2: build_site_external(pkg = pkg, examples = examples, run_dont_run = run_dont
3: callr::r(function(..., cli_colors, hyperlinks, pkgdown_internet) {
    optio
4: get_result(output = out, options)
5: throw(callr_remote_error(remerr, output), parent = fix_msg(remerr[[3]]))
6: base::stop(cond)
```

**Comment by hadley** [comment]
Thanks for the reprex. So useful!

**Comment by trevorld** [comment]
* I think this may have been introduced by https://github.com/r-lib/pkgdown/pull/2501
* Maybe escape the file names when creating the alias files as well as the links to them?

```r
> xml2::url_escape("[<-.bm_bitmap.html")
[1] "%5B%3C-.bm_bitmap.html"
```

**Comment by trevorld** [comment]
* I guess if you escaped the file names upon creation you'd need to double escape the links?
* Or maybe just skip creating redirects for any of the `[<-` aliases?  Or skip if building on Windows?

**Comment by hadley** [comment]
Yeah maybe skipping creation makes sense?

Also makes me wonder how redirects should be correctly encoded in the sitemap.

**Comment by trevorld** [comment]
Besides `[<-` there may be other theoretical operator aliases that may cause similar issues like `>` and `&`?

```r
x <- numeric(1L)
class(x) <- "awkward"
g <- function(e1, e2) { "problematic alias?" }

`/.awkward` <- g
x / x

`+.awkward` <- g
x + x

`&.awkward` <- g
x & x

`<.awkward` <- g
x < x

`>.awkward` <- g
x > x
```

**Comment by hadley** [comment]
I'd suggest we just copy what roxygen2 does: https://github.com/r-lib/roxygen2/blob/main/R/utils.R#L12-L62

**Comment by hadley** [comment]
https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap suggests that the sitemap should include canonical urls, so we shouldn't include redirects there at all.
