### ISSUE TITLE
deprecated parameters are listed as a function deprecation in the reference index

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2584]
The recommended way to deprecate a parameter is to [add a lifecycle badge the Rd parameter](https://lifecycle.r-lib.org/articles/communicate.html#arguments).

New changes in pkgdown pick this up and add the deprecation into the reference index, even if the function itself is not, which looks a little odd and is misleading (i.e., only the parameter is deprecated, not the function).

**Comment by hadley** [comment]
Ooops, I should restrict my search for figures to just the description, not the entire Rd.

**Comment by jayhesselberth** [comment]
or alternatively pick param deprecations up separately and list by the param on the rendered Rd page.

**Comment by hadley** [comment]
@jayhesselberth yeah, that would be nice, but that's going to be a lot more work, and I'd like to see what the reaction to the function-level lifecycle labelling is first.
