### ISSUE TITLE
pkgdown generates a dark page without light-switch configuration

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2585]
New changes in pkgdown will generate a dark page by default in the absence of a `light-switch` configuration.

Reprex:

``` r
usethis::create_project("~/Desktop/testpackage")
# . . .rstudio restarts in new project . . .
# pkgdown::build_site() generates the normal light default page
pkgdown::build_site()
# inspect in browser.

# clean up that site
pkgdown::clean_site()

# Now, initialize pkgdown infra in the new package
usethis::use_pkgdown()
# Generates a dark default page (with a light navbar?), with no light-switch configuration.
pkgdown::build_site()
```

**Comment by hadley** [comment]
I can't reproduce this, either by removing the `light-switch` field from pkgdown's own `_pkgdown.yaml`, or by following the outline you created above.

**Comment by salim-b** [comment]
@hadley I can reproduce this in a vanilla Firefox profile.

Current `main` branch (@e808ba8) of pkgdown seems to respect the browser's color mode preference (via [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)?) regardless of the `light-switch` config setting (which in principle is fine). But the dark mode is imperfect/broken when `light-switch` is not set or set to `false`. It seems like part of the dark-mode CSS is only properly applied when `light-switch: true`.

In Firefox, we can choose our color mode preference in the settings under *Language and Appearance*:

![Bildschirmfoto vom 2024-05-28 18-45-33](https://github.com/r-lib/pkgdown/assets/20040931/a4f70c9b-1472-407c-bce9-e6f82530391e)

### Screenshots

| `light-switch` | Firefox setting | screenshot |
| --- | --- | ------------------------------------------------- |
| `false` | **Light** | ![Screenshot 2024-05-28 at 18-23-42 Use NocoDB's RESTful APIs](https://github.com/r-lib/pkgdown/assets/20040931/49449f70-b00e-4e48-ba8b-8fdce9374699) |
| `false` | **Dark** | ![Screenshot 2024-05-28 at 18-23-27 Use NocoDB's RESTful APIs](https://github.com/r-lib/pkgdown/assets/20040931/a5661ef4-8e89-4ab6-8c2a-1260c44ada3d) |
| `true` | **Light** | ![Screenshot 2024-05-28 at 18-25-13 Use NocoDB's RESTful APIs](https://github.com/r-lib/pkgdown/assets/20040931/ce82ae02-ae1b-453e-b38c-b28d3e77f04f) |
| `true` | **Dark** | ![Screenshot 2024-05-28 at 18-25-21 Use NocoDB's RESTful APIs](https://github.com/r-lib/pkgdown/assets/20040931/f532c5d2-7e65-41a4-94a2-ece1da574fc6) |

As can be seen in the table above, the styling is broken for `light-switch: false` when Firefox requests the dark color mode. Note also that the navbar styling differs for light color mode depending on `light-switch` (which I guess is not on purpose).

Apart from those issues, I really like the new dark mode!

**Comment by hadley** [comment]
Ooooooh, it's because I use light mode.

**Comment by hadley** [comment]
So the problem is that `setTheme(getPreferredTheme())` gets run even when the light switch isn't used. So the question is how should the js detect that the light switch is present.  I don't _think_ we can just check for the presence/absence of `var document.getElementById('dropdown-lightswitch');` because this code needs to run before the document is loaded. So maybe we need to make `pkgdown.js` a template? Or should we pull out the lightswitch code into a separate js that we conditionally include?
