### ISSUE TITLE
Syntax-highlighting for the full license page of AGPL-3 seems odd

### ISSUE THREAD

**Issue by eitsupi** [r-lib/pkgdown#2590]
Perhaps it is recognized as an R code block?

![image](https://github.com/r-lib/pkgdown/assets/50911393/ce9a1296-ed5b-43ab-8313-fb007f4e8b57)

<https://eitsupi.github.io/r-glaredb/LICENSE.html>

The source md file is this <https://github.com/eitsupi/r-glaredb/blob/93e3d68f09f2455a97b6101fd5562ed0b871cc6b/LICENSE.md?plain=1#L624-L646>

```
To do so, attach the following notices to the program. It is safest to
attach them to the start of each source file to most effectively state
the exclusion of warranty; and each file should have at least the
"copyright" line and a pointer to where the full notice is found.

        <one line to give the program's name and a brief idea of what it does.>
        Copyright (C) <year>  <name of author>

        This program is free software: you can redistribute it and/or modify
        it under the terms of the GNU Affero General Public License as
        published by the Free Software Foundation, either version 3 of the
        License, or (at your option) any later version.

        This program is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU Affero General Public License for more details.

        You should have received a copy of the GNU Affero General Public License
        along with this program.  If not, see <https://www.gnu.org/licenses/>.

Also add information on how to contact you by electronic and paper
mail.
```

**Comment by hadley** [comment]
Yes, pkgdown tells pandoc that the default for syntax highlighting is R. I think that makes the most sense and it's probably not worth trying to figure out how to undo it just for one license.

**Comment by eitsupi** [comment]
> Yes, pkgdown tells pandoc that the default for syntax highlighting is R. I think that makes the most sense and it's probably not worth trying to figure out how to undo it just for one license.

That makes sense.
Is there any possibility to update the relevant part of the AGPL-3 license file add by `usethis` from an indented code block to a fenced code block?

**Comment by hadley** [comment]
You could look into it, but it's pulled from some other source that you'd need to do a PR too.
