### ISSUE TITLE
Could pkgdown have a way to detect default branch?

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2597]
For "source" links of documentation pages

Let's say I read documentation online and spot a typo.

In the vignette for example: https://pkgdown.r-lib.org/articles/pkgdown.html

I click on the link on top to go edit the vignette

![image](https://github.com/r-lib/pkgdown/assets/52606734/249a06ea-4f7e-4ae4-8e3b-03d757096a9f)

This is the one: https://github.com/r-lib/pkgdown/blob/HEAD/vignettes/pkgdown.Rmd

However, I cannot edit it easily :

![image](https://github.com/r-lib/pkgdown/assets/52606734/78d7c44a-4690-405e-b313-ac6f61bc5d6f)

I have to select the main branch on the top left corner.

If the link were https://github.com/r-lib/pkgdown/blob/main/vignettes/pkgdown.Rmd, would remove one step from the process.

usethis has `usethis:::git_default_branch()` for this. So if something similar could be called once, to create all the links, it would be awesome.

I understand pkgdown doesn't have git related dependencies, but it would be possible via a system call? This would have the biggest impact on the R pkgdown ecosystem.

Worst case scenario (opt-in), but the impact would be fairly minimal across pkgdown ecosytems would be to have a way to specify what is the default branch in config?

**Comment by hadley** [comment]
Hmmm, I don't think we can do this generally, but I think we could optimise for the common case, looking for a branch named either main or master, and using that if present. That would cover 99% of cases, I think.

**Comment by hadley** [comment]
Maybe something like this:

```R
default_branch <- function(pkg) {
  if (Sys.which("git") == "") {
    return("HEAD")
  }

  if (has_branch(pkg$src_path, "main")) {
    "main"
  } else if (has_branch(pkg$src_path, "master")) {
    "master"
  } else {
    "HEAD"
  }
}

has_branch <- function(repo, branch) {
  withr::local_dir(repo)
  tryCatch(
    {
      git("show-ref", paste0("refs/heads/", branch), echo = FALSE, echo_cmd = FALSE)
      TRUE
    },
    error = function(e) {
      FALSE
    }
  )
}
```

**Comment by olivroy** [comment]
Sounds like a good idea!

**Comment by hadley** [comment]
Alternatively, we could use the REST API: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#get-a-repository

**Comment by maelle** [comment]
some possible inspiration https://github.com/r-lib/usethis/blob/da18e11fa311ba7034ab58e86bb7b7e0977d1d26/R/git-default-branch.R#L230

**Comment by hadley** [comment]
@maelle FWIW that code is for determining what the default branch is for new repos
