### ISSUE TITLE
Inconsistent alignment of navbar elements in default styling

### ISSUE THREAD

**Issue by salim-b** [r-lib/pkgdown#2606]
pkgdown's currrent default styling produces this:

![Screenshot 2024-05-30 at 17-07-47 Use NocoDB's RESTful APIs](https://github.com/r-lib/pkgdown/assets/20040931/ce813529-c59d-45e1-b67b-3984c39a3d4d)

In the above, the search field is a bit off (too high). Proper alignment instead would look like this:

![Screenshot 2024-05-30 at 17-08-55 Use NocoDB's RESTful APIs](https://github.com/r-lib/pkgdown/assets/20040931/efc61b47-7238-4427-8367-e9d8e005b589)

Which could be achieved by adding the following CSS rule:

```css
nav.navbar {
  line-height: initial;
}
```

Would you accept adding this to pkgdown's default styling? Other thoughts?

**Comment by hadley** [comment]
Yes, definitely. That was a bug introduced in the navbar cleanup that I couldn't figure out how to easily remedy.
