### ISSUE TITLE
Syntax highlighting support for Rd's defining replacement methods?

### ISSUE THREAD

**Issue by SebKrantz** [r-lib/pkgdown#2616]
The following documentation page doesn't render well: https://sebkrantz.github.io/collapse/reference/indexing.html
Souce: https://github.com/SebKrantz/collapse/blob/master/man/indexing.Rd

**Comment by hadley** [comment]
Same underlying problem as #2303

**Comment by SebKrantz** [comment]
What gets sent into `downlit::highlight`, which returns `NA` (invalid R code), in case it is useful. Seems to have nothing to do with `>` or `<`.

```r
cat(ind$indexing.Rd$usage$contents)
## Create an 'indexed_frame' containing 'indexed_series'
findex_by(.X, ..., single = "auto", interact.ids = TRUE)
iby(.X, ..., single = "auto", interact.ids = TRUE)  # Shorthand

## Retrieve the index ('index_df') from an 'indexed_frame' or 'indexed_series'
findex(x)
ix(x)     # Shorthand

## Remove index from 'indexed_frame' or 'indexed_series' (i.e. get .X back)
unindex(x)

## Reindex 'indexed_frame' or 'indexed_series' (or index vectors / matrices)
reindex(x, index = findex(x), single = "auto")

## Check if 'indexed_frame', 'indexed_series', index or time vector is irregular
is_irregular(x, any_id = TRUE)

## Convert 'indexed_frame'/'indexed_series' to normal 'pdata.frame'/'pseries'
to_plm(x, row.names = FALSE)

# Subsetting & replacement methods: [(<-) methods call NextMethod().
# Also methods for fsubset, funique and roworder(v), na_omit (internal).

# S3 method for class 'indexed_series'
[(x, i, ..., drop.index.levels = "id")

# S3 method for class 'indexed_frame'
[(x, i, ..., drop.index.levels = "id")

# S3 method for class 'indexed_frame'
[(x, i, j) <- value

# S3 method for class 'indexed_frame'
$(x, name)

# S3 method for class 'indexed_frame'
$(x, name) <- value

# S3 method for class 'indexed_frame'
[[(x, i, ...)

# S3 method for class 'indexed_frame'
[[(x, i) <- value

# Index subsetting and printing: optimized using ss()

# S3 method for class 'index_df'
[(x, i, j, drop = FALSE, drop.index.levels = "id")

# S3 method for class 'index_df'
print(x, topn = 5, ...)
```

**Comment by hadley** [comment]
The problem is that `[(x, i, ..., drop.index.levels = "id")` is not valid R code.

**Comment by SebKrantz** [comment]
Yup, generated from `\method{[}{indexed_series}(x, i, \dots, drop.index.levels = "id")`...

**Comment by SebKrantz** [comment]
I've solved this in my fork as follows: 

https://github.com/SebKrantz/pkgdown/blob/fb5aace6ffb31acc934b8447c190e96e849c66c8/R/highlight.R#L3C1-L11C1

Probably not the way you'd go about it but works for me.

**Comment by hadley** [comment]
@SebKrantz #2621 should at least avoid the need for that hack. I'm still hoping that I can figure out how to generate the standard usage though.

**Comment by hadley** [comment]
And in #2622 it now works the way I would hope 😄 

![Screenshot 2024-06-03 at 10 42 34](https://github.com/r-lib/pkgdown/assets/4196/c04174c0-6f40-4d62-baf5-437adf15405d)

**Comment by SebKrantz** [comment]
Thanks, much appreciated!
