### ISSUE TITLE
FR: `build_home_index()` should always print a preview link in interactive sessions

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2618]
I think `build_home_index()` is the fastest way to preview navbar structure and general config without rendering everything? However, if home has not changed, then no preview_page link is printed to console.

From [build_home_index() docs](https://pkgdown.r-lib.org/dev/reference/build_home.html?q=preview#ref-usage):

`build_home_index()` rebuilds just the index page; it's useful for rapidly iterating when experimenting with site styles.

**Comment by hadley** [comment]
Yeah, but if nothing has changed, you can just refresh in the browser. Or use `preview_site()`. I'd rather keep it consistent with all the other displays.
