### ISSUE TITLE
Further Minors. 

### ISSUE THREAD

**Issue by SebKrantz** [r-lib/pkgdown#2630]
Not by any means wanting to keep anyone busy here. I just noticed that some recent commits introduced a weird rendering of the usage section of `collapse::pivot()` (`transpose` argument): [Docs](https://sebkrantz.github.io/collapse/reference/pivot.html) | [Source](https://github.com/SebKrantz/collapse/blob/master/man/pivot.Rd). 

 I believe as late as 3af98ac2ef8a78619d2d69aaffac6224fc3dc0de this was not the case. 

Then, I finally wondered why an empty line is placed above code chunks provided in [NEWS.md](https://sebkrantz.github.io/collapse/news/index.html) ([Source](https://github.com/SebKrantz/collapse/blob/master/NEWS.md)). 

Many thanks for any further consideration!

**Comment by SebKrantz** [comment]
Thanks. So for pivot, the site looks like this
![Screenshot at Jun 05 16-17-49](https://github.com/r-lib/pkgdown/assets/48053842/ae512c26-c580-48b3-8280-a1bb3de69f16)
Whereas the docs looks like this
![Screenshot at Jun 05 16-18-24](https://github.com/r-lib/pkgdown/assets/48053842/952d58c9-8b46-4b29-9b92-c273aa5120f0)

Of course I understand that such commentary of arguments is non-standard, but before the changes regarding the replacement functions pkgdown also rendered the pivot docs properly. 

Regarding the NEWS, there is an empty line before the code begins. In all such chunks in the NEWS. Not only in *collapse*, also in [*fixest*](https://lrberge.github.io/fixest/news/index.html) for example. 
![Screenshot at Jun 05 16-22-43](https://github.com/r-lib/pkgdown/assets/48053842/cf645b99-785a-4416-9091-f6a49ccdac1d)

**Comment by hadley** [comment]
Oooh, got it. I'll take a look. For future reference, since these are unlikely to have the same underlying cause, it would be useful if you created two separate issues.

**Comment by hadley** [comment]
The code blocks in https://pkgdown.r-lib.org/dev/news/index.html all look ok, but they are non-R code.  ... The space looks like it's the same size as the copy button but I think that's a red herring ... It looks like it's not coming from css, but because there's an extra empty line. So presumably something going wrong in the html highlight tweaking, but I didn't think I'd touched that code recently.

**Comment by hadley** [comment]
The messed up usage comes from #2626; I'd forgotten about the case where the final line in a one-line-per-argument usage will be parseable with a non-syntactic call to `=`. Maybe I can just special case `=`, but there might be other cases with multi-line default args where this also comes up.

**Comment by hadley** [comment]
Yeah, the news problem is because we're generating:

```html
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span></span>
<span><span class="st">"x"</span></span></code></pre></div>
</div>
```

instead of

```html
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="st">"x"</span></span></code></pre></div>
</div>
```

It's something to do specifically with syntax highlighting for R because you also don't see the gap if the R code doesn't parse.

**Comment by hadley** [comment]
The problem goes away if I comment out `downlit::downlit_html_node(html)`, but the syntax highlighting stays. That suggests downlit is getting double called. But why?

**Comment by hadley** [comment]
Minimal reprex:

```R
raw <- '<pre class="downlit sourceCode r">
<code class="sourceCode R"><span><span class="st">"x"</span></span></code></pre></div>'

html <- xml2::read_html(raw)

downlit::downlit_html_node(html)
cat(as.character(html))
```

....

I see the same problem in pkgdown 2.0.9, so doesn't look like a new issue.

**Comment by hadley** [comment]
Same problem with pkgdown 2.0.0 and downlit 0.4.0 so this has definitely been around for a while.

**Comment by hadley** [comment]
Phew. That was a journey of discovery.

**Comment by SebKrantz** [comment]
Thanks @hadley, much appreciated! *collapse*'s site looks great now. Cheers, Seb.
