### ISSUE TITLE
Could pkgdown avoid appending a trailing slash of the Github icon link?

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2670]
Even if `URL` has no trailing slash, pkgdown adds one

![image](https://github.com/r-lib/pkgdown/assets/52606734/100ea054-1e12-4dd5-8d24-dc50e1a1b4db)

Clicking here takes me to https://github.com/r-lib/pkgdown/

**Comment by hadley** [comment]
What's the problem? 😄

**Comment by olivroy** [comment]
The idea is just to avoid redirects, but not much of a priority :)
