### ISSUE TITLE
`check_pkgdown()`'s new requirement for `url` may be too much for internal packages

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2677]
I have a package that is not published anywhere, but I still build a pkgdown site for it (locally or on a shared drive).

I think the warning is good in 99% of situations as it will force users to add links where they are needed, but it should be conditional on certain things, like detection of a `.github` folder, a github link in DESCRIPTION (or just making this check on gh actions where we are sure that a url is required.

by default, `usethis::use_pkgdown() creates this template

```r
url: ~

template:
  bootstrap: 5
```

If a URL is present in DESCRIPTION, I think it may be acceptable ?

Also will create a lot of confusion for packages that don`t contain a url, but still succeed on GitHub actions currently.

**Comment by hadley** [comment]
I'm not sure we can recommend publishing pkgdown sites in this way, because they don't 100% work (i.e. search doesn't work, and some more sophisticated quarto stuff won't work either). I'm happy to revisit this if we see more user complaints, but for now I'd like to leave the existing behaviour.
