### ISSUE TITLE
Rmd articles are not highlighted in navbar

### ISSUE THREAD

**Issue by olivroy** [r-lib/pkgdown#2678]
Go to https://pkgdown.r-lib.org/dev/articles/quarto.html

![image](https://github.com/r-lib/pkgdown/assets/52606734/78254879-b32e-430e-ae85-a3a034d0b272)

Vs  https://pkgdown.r-lib.org/dev/articles/translations.html

![image](https://github.com/r-lib/pkgdown/assets/52606734/bd40e23e-cbd3-4bab-b978-b7adecc976dd)

See that the Articles button remains selected in Quarto vignettes. The difference is not bad (and I wouldn't have noticed it, but as gt has different css, it is very apparent)

I did some tests in gt. Let me know if gt should fix its css or if pkgdown + quarto will?

<details>
<summary>Example of quarto vignette with gt</summary>

![image](https://github.com/r-lib/pkgdown/assets/52606734/d616803c-910e-45f3-b494-ea17f7612928)
<details>

**Comment by hadley** [comment]
I'm pretty sure that the intent is for articles to be highlighted for all articles; i.e. the fact that it's not for the non-quarto articles is the bug.

**Comment by olivroy** [comment]
Makes sense, I will wait for your resolution and then see what's the best way for gt to respond to this change

**Comment by hadley** [comment]
I'd encourage you to take a look at the code that makes this work (I think it's in javascript?). I'm a terrible at getting the logic right.

**Comment by olivroy** [comment]
I don't really know where to start. This can always be left untouched until someone else cares about this.

**Comment by hadley** [comment]
Neither do I so we're in the same boat 😆

**Comment by hadley** [comment]
Adding a few pointers as I look into this a bit more. First discovery is that the code in `activate_navbar()`
