### ISSUE TITLE
Document how custom theming interact with the lightswitch

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2679]
If you use bslib variables for customization, how does that render in dark mode, etc.

Asking for a friend :wink: (I'll try to add some notes here)

Edit: https://getbootstrap.com/docs/5.3/customize/color-modes/#sass-variables is probably the answer :innocent:

**Comment by maelle** [comment]
Regarding themes, I see

> (Themes are unlikely to work with the light switch, but you can try it and see.)

In Quarto one can select a different theme for light and dark: https://quarto.org/docs/websites/website-tools.html#dark-mode

**Comment by hadley** [comment]
Yeah, the lightswitch works a bit differently to the quarto equivalent
