### ISSUE TITLE
Add CRAN's DOI in autogenerated CITATION

### ISSUE THREAD

**Issue by jmaspons** [r-lib/pkgdown#2681]
Recently, [all packages published at CRAN get a DOI](https://fosstodon.org/@zeileis/112597049943483012). Would be nice to add it at `authors.html#citation`.

**Comment by hadley** [comment]
The first problem to solve here is figuring out how to the get published DOI of a package.

**Comment by jmaspons** [comment]
I think that the DOI is deterministic

``` r
doi <- paste0("10.32614/CRAN.package.", pkg_name)
url <- paste0((https://doi.org/", doi)
```

Then it's just a matter of determining whether the package is published at CRAN or not, which it seems pkgdown already have functions for View on CRAN link.

**Comment by hadley** [comment]
Oh well that's very easy then 😄

**Comment by jmaspons** [comment]
Already in R utils::citation() https://github.com/r-devel/r-svn/commit/66292483683487a651e33e5fb9b63bc405e15015

**Comment by luisDVA** [comment]
citation is a complicated function, probably worth waiting until `utils::citation()` deals with DOIs in the next release of R. 
@hadley  approves of this strategy (dev day pers. comm)

**Comment by hadley** [comment]
Thanks for the exploration!
