### ISSUE TITLE
Replacing author name with logo

### ISSUE THREAD

**Issue by AliSajid** [r-lib/pkgdown#2682]
I am building a website for a package our lab has developed. I would like to have our lab's logo in the footer, just like there is one for Posit in the pkgdown's website. However, I can't quite find the specific steps to reproduce that on our site. I've looked in your _pkgdown.yaml but it has no customization of the footer.

Can you please point me in the right direction? Thanks

**Comment by maelle** [comment]
:wave: @AliSajid! Here's the relevant documentation section: https://pkgdown.r-lib.org/reference/build_home.html#yaml-config-authors

The dev version of pkgdown's own pkgdown website has no Posit logo https://pkgdown.r-lib.org/dev/ It was removed from the configuration file in https://github.com/r-lib/pkgdown/commit/978b9ae7a9f91ebc86e178afad0c3fb6929e2e1f#diff-4696b5e124c0b2a7e0ef4617c2e5be11de4ea153568c38fe79ee4925a8cb6b2e as I suppose it wasn't visible in dark mode.
