### ISSUE TITLE
Create fr-CA variant?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#2693]
cf #2692 

In fr-CA "paquet" would be "paquetage" for instance.

**Comment by olivroy** [comment]
I am French Canadian. I'd say I am so used to say "package" that both feel weird, but I'd still prefer paquet. Never heard paquetage before. Not here to start language war 😄

**Comment by hadley** [comment]
Since we're currently 50-50 on French Canadians and this term, I think we can try and skip creating a specific variant just for fr-CA.
