### ISSUE TITLE
tools::R_user_dir breaks usage with older R versions

### ISSUE THREAD

**Issue by al-obrien** [r-lib/pkgdown#2714]
The following additions of `tools::R_user_dir` in the pkgdown 2.1.0 version appears to break compatibility with R versions prior to 4.0

https://github.com/r-lib/pkgdown/blob/1407329e7a0027d6430684504c3d314fbc83b08f/R/external-deps.R#L94
https://github.com/r-lib/pkgdown/blob/1407329e7a0027d6430684504c3d314fbc83b08f/R/build-home-index.R#L222

If these are needed, then perhaps the CRAN dependency reference needs adjustment, as it currently sits at >3.6?

**Comment by jayhesselberth** [comment]
Yeah, we'll either need to do one or the other (bump the required version or eliminate use of `R_user_dir`).

Wondering if this could also be related to the cache issues in #2696

**Comment by jayhesselberth** [comment]
Addressed in #2715
