### ISSUE TITLE
Should `clean_site()` also delete the cache?

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2718]
Might help with intermittent cache-related issues.

See relevant work in now closed #2715

**Comment by hadley** [comment]
It doesn't feel quite right to me since the cache isn't associated with a specific package. Maybe it's worth having a separate `clean_cache()` function?

**Comment by shikokuchuo** [comment]
Just FYI I ran into some sort of cache issue after upgrading to the latest pkgdown locally. Kept running into a callr error for `readRDS(path)` that I couldn't clear. After I came across `clean_cache()`, clearing the cache fixed things. Thanks @jayhesselberth. Posting as it might be useful for others with the same problem.

**Comment by maelle** [comment]
@shikokuchuo I think you were a victim of https://github.com/r-lib/pkgdown/issues/2696
