### ISSUE TITLE
build_site() fails on readRDS(path)

### ISSUE THREAD

**Issue by dankelley** [r-lib/pkgdown#2724]
I'm finding that my project (https://github.com/dankelley/atmosphere) gets errors from `pkgdown::build_site()` as follows.  I used `pkgdown::clean_site()` first, as a test.  All packages on my machine were updated today with `update.packages()`.

I'm not too sure how to proceed in trying to fix this.  I think it must be something wrong with the setup for this repo, because another repo (https://github.com/dankelley/oce) doesn't have this problem.  (Note that `oce` takes maybe 5 minutes to build, whereas `atmosphere` fails in about 30 seconds.  Of the two, `oce` is by far the more important project because it has a lot of users.  I'm not panicked about `atmosphere` per se, but I do worry that I might be misunderstanding something, leading to breakage for `oce` at some point.)

Any suggestions on how I ought to proceed?

Thanks for pkgdown, which I love and use a lot.

```
> pkgdown::clean_site()

/Users/kelley/git/atmosphere/docs
> pkgdown::build_site()
── Installing package atmosphere into temporary library ─────────────
── Initialising site ───────────────────────────────────────────────────────────
Copying <pkgdown>/BS5/assets/katex-auto.js to katex-auto.js
Copying <pkgdown>/BS5/assets/lightswitch.js to lightswitch.js
Copying <pkgdown>/BS5/assets/link.svg to link.svg
Copying <pkgdown>/BS5/assets/pkgdown.js to pkgdown.js
Updating deps/bootstrap-5.3.1/bootstrap.bundle.min.js
Updating deps/bootstrap-5.3.1/bootstrap.bundle.min.js.map
Updating deps/bootstrap-5.3.1/bootstrap.min.css
Updating deps/bootstrap-toc-1.0.1/bootstrap-toc.min.js
Updating deps/clipboard.js-2.0.11/clipboard.min.js
Updating deps/font-awesome-6.4.2/css/all.css
Updating deps/font-awesome-6.4.2/css/all.min.css
Updating deps/font-awesome-6.4.2/css/v4-shims.css
Updating deps/font-awesome-6.4.2/css/v4-shims.min.css
Updating deps/font-awesome-6.4.2/webfonts/fa-brands-400.ttf
Updating deps/font-awesome-6.4.2/webfonts/fa-brands-400.woff2
Updating deps/font-awesome-6.4.2/webfonts/fa-regular-400.ttf
Updating deps/font-awesome-6.4.2/webfonts/fa-regular-400.woff2
Updating deps/font-awesome-6.4.2/webfonts/fa-solid-900.ttf
Updating deps/font-awesome-6.4.2/webfonts/fa-solid-900.woff2
Updating deps/font-awesome-6.4.2/webfonts/fa-v4compatibility.ttf
Updating deps/font-awesome-6.4.2/webfonts/fa-v4compatibility.woff2
Updating deps/headroom-0.11.0/headroom.min.js
Updating deps/headroom-0.11.0/jQuery.headroom.min.js
Updating deps/jquery-3.6.0/jquery-3.6.0.js
Updating deps/jquery-3.6.0/jquery-3.6.0.min.js
Updating deps/jquery-3.6.0/jquery-3.6.0.min.map
Updating deps/search-1.0.0/autocomplete.jquery.min.js
Updating deps/search-1.0.0/fuse.min.js
Updating deps/search-1.0.0/mark.min.js
── Building pkgdown site for package atmosphere ────────────────────────────────
Reading from: /Users/kelley/git/atmosphere
Writing to: /Users/kelley/git/atmosphere/docs
── Sitrep ──────────────────────────────────────────────────────────────────────
✔ URLs ok.
✔ Favicons ok.
✔ Open graph metadata ok.
✔ Articles metadata ok.
✔ Reference metadata ok.
── Initialising site ───────────────────────────────────────────────────────────
── Building home ───────────────────────────────────────────────────────────────
Writing authors.html
Error: 
! in callr subprocess.
Caused by error in `readRDS(path)`:
! error reading from connection
ℹ See `$stdout` and `$stderr` for standard output and error.
Type .Last.error to see the more details.
```

**Comment by maelle** [comment]
It might be a case of #2696: can you please try installing the httr2 dev version (`pak::pak("r-lib/httr2")`) or deleting the cache manually? (see https://github.com/r-lib/pkgdown/blob/9779d2890d39c68d47f43a6514c565e394ce4c71/R/build-home-index.R#L222 to find where the cache is on your machine)

**Comment by dankelley** [comment]
The `pak::pak("r-lib/httr2")` method fixed my problem.  Thanks *very* much for the rapid and detailed response.  I really appreciate the help because I was going around in circles.

I'll close the issue now, if it's OK for commenters to close their issues in this group.

**Comment by jkylearmstrong** [comment]
I had this same issue and updating `httr2` with `pak::pak("r-lib/httr2")` fixed the issue for me. Glad I looked at the closed issues to make sure it was an easy fix.

**Comment by hadley** [comment]
FWIW installing httr2 from CRAN will also fix the problem.
