### ISSUE TITLE
Error when building quarto articles on GH actions

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/pkgdown#2733]
Hi,

I tried setting up quarto vignettes, and while it works perfectly on my computer (local), I could not manage to make it work on GH actions.
Locally, even `pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)` works fine.

For instance, this is the last run I had:
https://github.com/DanChaltiel/EDCimport/actions/runs/10092641396/job/27907083693#step:7:393
![image](https://github.com/user-attachments/assets/0f9806a3-a700-457f-9e7f-d4d2847511ad)
Here is the workflow: https://github.com/DanChaltiel/EDCimport/actions/runs/10092641396/workflow
I hope I did it correctly, but at least I can say that the error message is not specific enough to let me debug this.
Note that my vignette uses tabsets.min.js to have tabs.

BTW, it would be nice to reference a minimal reproducible example in the vignette, so that we could simply grab the .qmd file, test that it runs on our setup, and then incrementally change our article it to make what we want.

**Comment by hadley** [comment]
@DanChaltiel could you please file the example rendering as a separate issue? For that it would be super useful if you could include a minimal qmd that illustrated the problem. Thanks!

**Comment by DanChaltiel** [comment]
I'm not sure what you meant, but I tried to add minimal vignettes to see which would fail.
Here is the output: https://github.com/DanChaltiel/EDCimport/actions/runs/10107819848/job/27952452580#step:7:385 
`aaaaa_test_1.qmd` is the exact copy of https://raw.githubusercontent.com/r-lib/pkgdown/main/vignettes/quarto.qmd and still fails.

I'd gladly give you more information but I'm a bit clueless on how to efficiently debug GHActions.

I separated the formula bug in the vignette into another issue as requested.

**Comment by olivroy** [comment]
@DanChaltiel You could try adding `tinytex: true` in the setup quarto action. You also no longer the pre-release version of Quarto.

Maybe try replacing this in  https://github.com/DanChaltiel/EDCimport/blob/b7e63cced82bdaf00deb1fc8367c5c978faa8f5e/.github/workflows/pkgdown.yaml#L30-L35

```yaml
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by DanChaltiel** [comment]
Thanks, I tried it, but the error remains: https://github.com/DanChaltiel/EDCimport/actions/runs/10111494027/job/27963549942#step:7:392

**Comment by olivroy** [comment]
Ok, but I see that this is an article. 
https://github.com/DanChaltiel/EDCimport/blob/main/vignettes/articles/adverse_events.qmd

If you want it to be a vignette, place it in the vignettes/ folder directly. 
If you want it to be an article, don't use the vignette declaration.

Use

````qmd
---
title: "Adverse Events"
description: > 
  Learn how to make AE tables.
format: html
knitr:
  opts_chunk: 
    collapse: true
    comment: '#>'
---
````

Not sure if this will solve the issue, but it may help.

I have been able to setup Quarto articles in gt.  https://github.com/rstudio/gt/blob/master/.github/workflows/pkgdown.yaml

**Comment by ethanbass** [comment]
I think the issue with Quarto articles is because they are being built by `quarto_render` into the "articles" subdirectory of the vignettes temp directory, but `build_quarto_articles` is looking for all the articles in the `vignettes` when it renders them into the pkgdown template, causing the error: "No built file found for <path to qmd>".

For example, if you clone my test package from github (https://github.com/ethanbass/quartoArticleError) and run 
```
pkgdown::build_articles()
```

However, Quarto articles seem to be built correctly if you modify `build_quarto articles` move the contents of the article folder (in the temp directory) to the parent vignettes directory after rendering, e.g.,

```
  output_dir <- quarto_render(pkg, src_path, quiet = quiet)
  article_dir <- fs::path(output_dir,"articles")
  if (fs::dir_exists(article_dir)){
    fs::file_move(dir_ls(article_dir), output_dir)
  }
```

After installing my patched version with the above modification, quarto articles are built correctly.

```
devtools::install_github("ethanbass/pkgdown", ref="qmd_articles")
pkgdown::build_articles()
```

**Comment by acastroaraujo** [comment]
@ethanbass Thank you so much. I thought I was losing my mind.
