### ISSUE TITLE
Bug in the formula in the quarto vignette

### ISSUE THREAD

**Issue by DanChaltiel** [r-lib/pkgdown#2734]
Hi,

There is a bug in the quarto vignette: [the formula is not shown properly](https://cloud.r-project.org/web/packages/pkgdown/vignettes/quarto.html#eq-black-scholes):
![image](https://github.com/user-attachments/assets/41331a8e-4b91-4ef8-9080-9255a4bffb24)

**Comment by hadley** [comment]
Can you please include a minimal reprex for this? i.e. what is the minimal qmd file that illustrates the problem?

**Comment by DanChaltiel** [comment]
I could not reproduce the problem, I am only seeing it on the various CRAN mirrors such as in my link.

**Comment by hadley** [comment]
Oh this is in pkgdown's vignette?

**Comment by DanChaltiel** [comment]
It seems that the problem is gone...
![image](https://github.com/user-attachments/assets/a68f7b52-9929-4bc5-ab26-7f19bbd44037)
