### ISSUE TITLE
Extra vertical space in math mode

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#2741]
See:

- Source: https://github.com/ramiromagno/hello
- Website: https://rmagno.eu/hello/index.html

<img src="https://github.com/user-attachments/assets/d936ccb5-6f54-4bc0-9915-1ec604e82ca7" width="600">

This seems to be the case also with current pkgdown's article about math: https://pkgdown.r-lib.org/articles/test/rendering.html?q=math#math.

**Comment by jayhesselberth** [comment]
I'm not clear what the issue is here. Too much vertical space? Not enough?

IMO the math on the pkgdown website looks fine, and the div is pretty cropped already.

You can [change the math rendering engine](https://pkgdown.r-lib.org/articles/customise.html?q=math-rendering#math-rendering) in pkgdown sites, and the rendered equations do have subtle differences (font types / sizes) between the engines.

You could also change spacing on a per-site basis with some custom CSS.

**Comment by hadley** [comment]
It looks fine to me too. What browser are you using?

![Screenshot 2024-08-01 at 07 44 53](https://github.com/user-attachments/assets/5976cc7e-bc18-49fa-963c-1ffab015a7fe)

**Comment by ramiromagno** [comment]
Thank you @hadley. 

I noticed a big difference in the spacing from earlier versions to the newest version. I'm trying to generate a new website using pkgdown 2.0.0 to hopefully illustrate what I mean more clearly, so that you guys don't get the impression that this is just a small styling difference.

BTW: I'm using Firefox 125.0.3 (64-bit).

**Comment by hadley** [comment]
This is how the pkgdown 2.1.0 website looks for me in safari:

![Screenshot 2024-08-01 at 09 24 13](https://github.com/user-attachments/assets/b283f753-1461-4965-bc88-67491bf2ba2c)

And this is what it looks like for me in firefox:

![Screenshot 2024-08-01 at 09 26 29](https://github.com/user-attachments/assets/bb989e5d-c915-4f09-826f-00b4e8dfc97b)

So seems like something weird is going on on your end.

**Comment by jayhesselberth** [comment]
These differences could also be attributable to the (very) old MathJax that pkgdown was using in 2.0.0.

**Comment by ramiromagno** [comment]
Yeah, I am investigating what on my end might be causing this. Using ArchLinux is definitely a good clue... 

I am looking into this: https://wiki.archlinux.org/title/Firefox#Some_MathML_symbols_are_missing.

But thanks for the all the help so far. Please don't close this issue just yet, even though it is clear that it is about my system, I would like to try to solve it and leave it here for others (even if that is a very tiny minority of users using Arch...) :)

**Comment by ramiromagno** [comment]
In firefox with pkgdown 2.1.0 after installing the Arch Linux package: https://archlinux.org/packages/extra/any/otf-latinmodern-math/, sanity is restored!

![snap](https://github.com/user-attachments/assets/58c59fb6-7617-412d-b50c-c0b813d1c89c)

## Solution

To Archlinux folks out there:

```bash
yay -S otf-latinmodern-math
```

@hadley and @jayhesselberth: Thanks a lot for taking the time to help me out troubleshoot this.
