### ISSUE TITLE
Test failure: `data_reference_index()`

### ISSUE THREAD

**Issue by HenningLorenzen-ext-bayer** [r-lib/pkgdown#2745]
```r
devtools::test(filter = "^build-reference-index$")
```

<pre>
── Failed tests ─────────────────────────────────────────────────
Failure (test-build-reference-index.R:115:3): can use a topic from another package
Snapshot of code has changed:
old[15:21] vs new[15:21]
        - is_installed()
        - check_installed()
        icon: ~
-     - path: https://rdrr.io/pkg/bslib/man/bs_bundle.html
+     - path: https://rstudio.github.io/bslib/reference/bs_bundle.html
        title: Add low-level theming customizations (from bslib)
        lifecycle: ~
        aliases:

* Run testthat::snapshot_accept('build-reference-index') to accept the change.
* Run testthat::snapshot_review('build-reference-index') to interactively review the change.
</pre>

**Comment by hadley** [comment]
Fixed in #2744 😄
