### ISSUE TITLE
Suggestion: match logo height to text's

### ISSUE THREAD

**Issue by ramiromagno** [r-lib/pkgdown#2748]
This is rather subjective but would you agree that logos shown in the extra authors page should match the text height? Currently, it also pushes the text that follows to the next line, e.g. _". Copyright holder, funder."_ is always on the next line which is not so nice...

For example, in tidyr's website, Posit's logo stretches to fill horizontally:

https://tidyr.tidyverse.org/authors.html

**Comment by hadley** [comment]
That's a buglet that we've fixed that will be fixed on next tidyr release: https://tidyr.tidyverse.org/dev/authors.html
