### ISSUE TITLE
Warning in `build_news()`

### ISSUE THREAD

**Issue by TanguyBarthelemy** [r-lib/pkgdown#2749]
Hello, 

I'm trying to build my gh pages with **{pkgdown}**. Only when building the `NEWS.md` file, I get the following warning:

``` r
> pkgdown::build_news()
── Building news ────────────────────────────────────────────────────────────────────────────────────────────────────
Writing news/index.html
Warning message:
In build_news_single(pkg) :
  In NEWS.md, no version headings found
ℹ See pkgdown::build_news for expected structure.
```

My [changelog](https://github.com/InseeFr/JDCruncheR/blob/master/NEWS.md) follows the conventions recommended by this website: https://keepachangelog.com/fr/1.0.0/.

So the first line is as follows: 

```
# Changelog
```

Why does the build fail and is it possible to soften the check rules to allow the `NEWS.md` to be built nonetheless?

Thank you!

**Comment by olivroy** [comment]
pkgdown expects first level headings in NEWS.md for each version. https://pkgdown.r-lib.org/reference/build_news.html?q=build_news#details

```md
# Unreleased

# 0.24

# 0.23 

```
