### ISSUE TITLE
Allow disabling the wrapping of `\dontrun{}` blocks with `if (FALSE) {}` in example sections

### ISSUE THREAD

**Issue by dvg-p4** [r-lib/pkgdown#2752]
We use `\dontrun{...}` in all of our examples, which require database connections or otherwise should not be automatically run when building our package docs. In R or Rstudio, these unfortunately render as `## Not run:` ... `## End(Not run)`, which at least renders in an easily-ignorable gray. However, pkgdown renders the tags as `if (FALSE) {...}`, which I think clutters up the page to very little benefit and looks kind of ugly. So, it would be nice if this could be turned off.

**Comment by jayhesselberth** [comment]
It's not clear to me what you're advocating for. Hiding the blocks completely? I'm guess not sure what you mean by "turned off".

**Comment by dvg-p4** [comment]
Current:
![image](https://github.com/user-attachments/assets/2014776a-ddf9-4834-bf5e-50a3a9a93a4e)

Proposed:
![image](https://github.com/user-attachments/assets/9a05f558-c891-45b3-b352-bc95b859a052)

**Comment by hadley** [comment]
I’d recommend using a different technique like `@exampleIf`

**Comment by dvg-p4** [comment]
> I’d recommend using a different technique like `@exampleIf`

`@exampleIf FALSE` actually removes the `## Not run:` from the R/Rstudio docs, but still leaves the `if (FALSE)` in pkgdown

**Comment by dvg-p4** [comment]
and `@excampleIf 1 == 0` yields `if (FALSE) { # 1 == 0`

**Comment by hadley** [comment]
You should use a real condition that evaluates to `TRUE` when pkgdown is running.

**Comment by dvg-p4** [comment]
What would that be?

**Comment by hadley** [comment]
Presumably you have some idea of when `connect()` will succeed. You might find https://r-pkgs.org/man.html#sec-man-examples-dependencies-conditional-execution helpful.

**Comment by dvg-p4** [comment]
In short, it won't ever, because the functions in our class require a live connection to an actual database, for which we don't want to put credentials in our package examples.

**Comment by dvg-p4** [comment]
I guess I'm confused as to why pkgdown wants to add this whole `if (FALSE)` in the first place. The point is to render examples on a webpage; the code isn't going to magically run itself (right?) -- and if someone manually copy-pastes the example code into an R terminal, the `if (FALSE)` won't stop them cause they can just not copy that part.

**Comment by dvg-p4** [comment]
@hadley Am I misunderstanding something about how these example blocks work, is pkgdown actually evaluating the code when it generates the site?
