### ISSUE TITLE
Unable to disable hyphenation by using pkgdown/extra.css

### ISSUE THREAD

**Issue by jonovik** [r-lib/pkgdown#2770]
My pkgdown-generated site got hyphenation (in https://github.com/r-lib/pkgdown/pull/1888) after I updated pkgdown, and I do not find it helpful. I believe I should be able to turn it off by [using pkgdown/extra.css](https://pkgdown.r-lib.org/articles/customise.html#additional-html-and-files), but while I am able to e.g. turn text red, I cannot turn off hyphenation.

I created [a public github repository](https://github.com/jonovik/testpkgdown) which reproduces the problem on my system, including a screenshot.

I have searched for other issues mentioning hyphen, hyphenate or hyphenation, and inspected the pkgdown source to find the abovementioned pull request, but am unable to get any further on my own.

## Details

`library(pkgdown)` introduced hyphenation in [r-lib/pkgdown@3d06c13](https://github.com/r-lib/pkgdown/commit/3d06c13cdc253b0cf6f915c073c46ee27b70da2b)
and I am unable to turn it off using `pkgdown/extra.css`.

This repository demonstrates that while extra.css manages to switch the text color to red, hyphenation ([css docs](https://developer.mozilla.org/en-US/docs/Web/CSS/hyphens)) persists despite `hyphens: none;`.

![hyphenation](https://github.com/user-attachments/assets/1da82aff-3048-4661-a135-b5ec783e2259)

To reproduce:

* RStudio > File > New Project > New Directory > R package
* usethis::use_pkgdown()
* pkgdown::build_site()
* Observe that the word para-graphs gets hyphenated in the default package description.
  (Adding README.Rmd will override the front page, but we can see the word hy-phenation instead.)
* Try to override CSS in pkgdown/extra.css:

      body {
        color: red;
        hyphens: none !important;
      }
  
  and re-run pkgdown::build_site(). The text gets red, but the hyphens persist.

There might actually be two issues here:

* **How can I turn off hyphenation?**
* From the commit message that introduced the change, it sounds as if hyphenation was meant to help out with extremely long words. Currently, even perfectly moderate words such as "paragraph" are hyphenated. Maybe the default hyphenation setting is not quite working as intended, either.

```
> devtools::session_info()
─ Session info ─────────────────
 setting  value
 version  R version 4.4.1 (2024-06-14)
 os       Ubuntu 24.04 LTS
 system   x86_64, linux-gnu
 ui       RStudio
 language (EN)
 collate  en_US.UTF-8
 ctype    en_US.UTF-8
 tz       Europe/Oslo
 date     2024-08-25
 rstudio  2024.04.2+764 Chocolate Cosmos (desktop)
 pandoc   3.1.11 @ /usr/lib/rstudio/resources/app/bin/quarto/bin/tools/x86_64/ (via rmarkdown)

─ Packages ──────────────────────
 package     * version     date (UTC) lib source
 base64enc     0.1-3       2015-07-28 [3] CRAN (R 4.0.2)
 bslib         0.8.0       2024-07-29 [3] RSPM (R 4.4.0)
 bspm          0.5.7       2024-04-10 [2] CRAN (R 4.4.1)
 cachem        1.1.0       2024-05-16 [3] RSPM (R 4.4.0)
 cli           3.6.3       2024-06-21 [3] RSPM (R 4.4.0)
 curl          5.2.1       2024-03-01 [3] RSPM (R 4.4.0)
 desc          1.4.3       2023-12-10 [3] RSPM (R 4.4.0)
 devtools      2.4.5       2022-10-11 [3] RSPM (R 4.4.0)
 digest        0.6.37      2024-08-19 [3] RSPM (R 4.4.0)
 downlit       0.4.4       2024-06-10 [3] RSPM (R 4.4.0)
 ellipsis      0.3.2       2021-04-29 [3] RSPM (R 4.4.0)
 evaluate      0.24.0      2024-06-10 [3] RSPM (R 4.4.0)
 fansi         1.0.6       2023-12-08 [3] RSPM (R 4.4.0)
 fastmap       1.2.0       2024-05-15 [3] RSPM (R 4.4.0)
 fontawesome   0.5.2       2023-08-19 [3] RSPM (R 4.4.0)
 fs            1.6.4       2024-04-25 [3] RSPM (R 4.4.0)
 glue          1.7.0       2024-01-09 [3] RSPM (R 4.4.0)
 htmltools     0.5.8.1     2024-04-04 [3] RSPM (R 4.4.0)
 htmlwidgets   1.6.4       2023-12-06 [3] RSPM (R 4.4.0)
 httpuv        1.6.15      2024-03-26 [3] RSPM (R 4.4.0)
 httr2         1.0.3       2024-08-22 [3] RSPM (R 4.4.0)
 jquerylib     0.1.4       2021-04-26 [3] CRAN (R 4.2.2)
 jsonlite      1.8.8       2023-12-04 [3] RSPM (R 4.4.0)
 knitr         1.48        2024-07-07 [3] RSPM (R 4.4.0)
 later         1.3.2       2023-12-06 [3] RSPM (R 4.4.0)
 lifecycle     1.0.4       2023-11-07 [3] RSPM (R 4.4.0)
 magrittr      2.0.3       2022-03-30 [3] RSPM (R 4.4.0)
 memoise       2.0.1       2021-11-26 [3] RSPM (R 4.4.0)
 mime          0.12        2021-09-28 [3] RSPM (R 4.4.0)
 miniUI        0.1.1.1     2018-05-18 [3] RSPM (R 4.4.0)
 pillar        1.9.0       2023-03-22 [3] RSPM (R 4.4.0)
 pkgbuild      1.4.4       2024-03-17 [3] RSPM (R 4.4.0)
 pkgconfig     2.0.3       2019-09-22 [3] RSPM (R 4.4.0)
 pkgdown       2.1.0       2024-07-06 [3] RSPM (R 4.4.0)
 pkgload       1.4.0       2024-06-28 [3] RSPM (R 4.4.0)
 profvis       0.3.8       2023-05-02 [3] RSPM (R 4.4.0)
 promises      1.3.0       2024-04-05 [3] RSPM (R 4.4.0)
 purrr         1.0.2       2023-08-10 [3] RSPM (R 4.4.0)
 R6            2.5.1       2021-08-19 [3] RSPM (R 4.4.0)
 ragg          1.3.2       2024-05-15 [3] RSPM (R 4.4.0)
 rappdirs      0.3.3       2021-01-31 [3] RSPM (R 4.4.0)
 Rcpp          1.0.13      2024-07-17 [3] RSPM (R 4.4.0)
 remotes       2.5.0       2024-03-17 [3] RSPM (R 4.4.0)
 rlang         1.1.4       2024-06-04 [3] RSPM (R 4.4.0)
 rmarkdown     2.28        2024-08-17 [3] RSPM (R 4.4.0)
 rstudioapi    0.16.0.9000 2024-08-16 [1] Github (rstudio/rstudioapi@d5d5a22)
 sass          0.4.9       2024-03-15 [3] RSPM (R 4.4.0)
 sessioninfo   1.2.2       2021-12-06 [3] RSPM (R 4.4.0)
 shiny         1.9.1       2024-08-01 [3] RSPM (R 4.4.0)
 stringi       1.8.4       2024-05-06 [3] RSPM (R 4.4.0)
 stringr       1.5.1       2023-11-14 [3] RSPM (R 4.4.0)
 systemfonts   1.1.0       2024-05-15 [3] RSPM (R 4.4.0)
 testpkgdown * 0.1.0       2024-08-25 [1] local
 textshaping   0.4.0       2024-05-24 [3] RSPM (R 4.4.0)
 tibble        3.2.1       2023-03-20 [3] CRAN (R 4.3.1)
 urlchecker    1.0.1       2021-11-30 [3] RSPM (R 4.4.0)
 usethis       3.0.0       2024-07-29 [3] RSPM (R 4.4.0)
 utf8          1.2.4       2023-10-22 [3] RSPM (R 4.4.0)
 vctrs         0.6.5       2023-12-01 [3] RSPM (R 4.4.0)
 whisker       0.4.1       2022-12-05 [3] RSPM (R 4.4.0)
 withr         3.0.1       2024-07-31 [3] RSPM (R 4.4.0)
 xfun          0.47        2024-08-17 [3] RSPM (R 4.4.0)
 xml2          1.3.6       2023-12-04 [3] RSPM (R 4.4.0)
 xtable        1.8-4       2019-04-21 [3] RSPM (R 4.4.0)
 yaml          2.3.10      2024-07-26 [3] RSPM (R 4.4.0)

 [1] /home/jonvi/R/x86_64-pc-linux-gnu-library/4.4
 [2] /usr/local/lib/R/site-library
 [3] /usr/lib/R/site-library
 [4] /usr/lib/R/library
```

**Comment by hadley** [comment]
I would think the css that you would need is:

```css
.row > main {
  hyphens: none;
}
```

Does that work?

**Comment by jonovik** [comment]
It does, and solves my issue. Thank you very much.

I guess this is a case of a [CSS specificity war](https://stuffandnonsense.co.uk/archives/css_specificity_wars.html). It surprises me that `!important` was not enough.

I'm not sure what could be done to make such solutions more discoverable. In hindsight, I could have tried this once I saw that the commit which introduced hyphenation used `.row>main`. However, this requires poking around inside the source code. Anyhow, case closed. Thanks!
