### ISSUE TITLE
Feature request in Quarto vignettes: code filenames

### ISSUE THREAD

**Issue by Nenuial** [r-lib/pkgdown#2776]
If I am not mistaken, [code filename](https://quarto.org/docs/output-formats/html-code.html#code-filename) are currently not implemented in the rendering of Quarto vignettes.

I believe this would be a really nice feature to have. Showing the filename makes documenting configuration for example, much more explicit and readable.

**Comment by jayhesselberth** [comment]
It would be helpful to add an example of the utility of these changes in the quarto features vignette (`vignettes/test/quarto-features.qmd`).

**Comment by Nenuial** [comment]
Of course! I added the example as requested.
