### ISSUE TITLE
Reinstate macro loading

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2782]
This code was accidentally removed from `rd_file()` in #2759 :

```r
macros <- tools::loadPkgRdMacros(pkg_path)
set_classes(tools::parse_Rd(path, macros = macros, encoding = "UTF-8"))
```

Should create a dummy macro for testing purposes?

```diff
 rd_file <- function(path, pkg_path = NULL) {
-  if (getRversion() >= "3.4.0") {
-    macros <- tools::loadPkgRdMacros(pkg_path)
-    set_classes(tools::parse_Rd(path, macros = macros, encoding = "UTF-8"))
-  } else if (getRversion() >= "3.2.0") {
-    macros <- tools::loadPkgRdMacros(pkg_path, TRUE)
-    set_classes(tools::parse_Rd(path, macros = macros, encoding = "UTF-8"))
-  } else {
-    set_classes(tools::parse_Rd(path, encoding = "UTF-8"))
-  }
+  set_classes(tools::parse_Rd(path, encoding = "UTF-8"))
 }
```

_Originally posted by @bastistician in https://github.com/r-lib/pkgdown/issues/2759#issuecomment-2357946639_

**Comment by jayhesselberth** [comment]
@bastistician can you install dev pkgdown and confirm that macros work? Thanks.

**Comment by bastistician** [comment]
I had already tried a patched version locally where I simply restored just the original `>= "3.4.0"` branch and that worked as expected. You seem to have done the same so it should be ok.
