### ISSUE TITLE
Missing date when adding additional citations

### ISSUE THREAD

**Issue by gowerc** [r-lib/pkgdown#2784]
Apologies in advance I'll admit I'm not 100% sure what I am doing so sorry if this is actually user error...

For our package we wanted to retain the default automatically generated citation but add in an additional publication citation.  It appears the recommended way to do this from the pkgdown [docs](https://pkgdown.r-lib.org/reference/build_home.html) is to use a `inst/citation` file.  Additionally from the R/CRAN [manual](https://cran.r-project.org/doc/manuals/R-exts.html#CITATION-files) they provide an example of retaining the automatic generated entry whilst including an additional static bibtex entry by populating the file as:

```
## R package reference generated from DESCRIPTION metadata
citation(auto = meta)

## NLME book
bibentry(bibtype = "Book",
         title = "Mixed-Effects Models in S and S-PLUS",
         author = c(person(c("José", "C."), "Pinheiro"),
                    person(c("Douglas", "M."), "Bates")),
         year = "2000", publisher = "Springer", address = "New York",
         doi = "10.1007/b98882")
```

However when we do this and then use `pkgdown::build_home()` we get the following warning
```
Warning message:
In citation(auto = meta) :
  could not determine year for ‘rbmi’ from package DESCRIPTION file
```
Which results in the citation date being populated as `???`:
![image](https://github.com/user-attachments/assets/c38f893e-15ec-450b-9ddd-d8218982dd83)

This appears to be due to the Date information not being populated in our DESCRIPTION file, though searching online I can see a couple of [posts](https://github.com/r-lib/usethis/issues/806) from tidyverse members who recommend not populating this field as it will be populated automatically upon CRAN submission and if done manually will likely get out of date. 

Would it be possible to address this within pkgdown or is there something I am missing here?  Currently I am working around this by adding the following to my `inst/citation` file (though it is not clear to me how robust this is):
```R
if (is.null(meta[["Date/Publication"]])) {
    meta["Date/Publication"] <- as.character(Sys.time())
}
```

**Comment by jayhesselberth** [comment]
Closing for now, please re-open if you still have an issue.

**Comment by schneiderpy** [comment]
I have the same issue. pkgdown uses the Description file on `build_site`, however, there is a CITATION file present (in `inst` folder). This file has a date field. As per the documentation if `auto=NULL `(default) and a CITATION file is present, then this file will be used. Interestingly, the code chuck in .rmd renders fine (with date), however, this is not reflected in the web site (with build_site). I use pkgdown Version 2.1.3
