### ISSUE TITLE
`pkgdown::build_favicons(overwrite = TRUE)` results in an `HTTP 500 Internal Server Error`

### ISSUE THREAD

**Issue by SpatLyu** [r-lib/pkgdown#2796]
```r
pkgdown::build_favicons(overwrite = TRUE)
```
── Building favicons ──
ℹ Building favicons with <https://realfavicongenerator.net>...
Error in `pkgdown::build_favicons()`:
! API request failed.
Caused by error in `httr2::req_perform()`:
! HTTP 500 Internal Server Error.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by SpatLyu** [comment]
The service has now been restored to normal use。

**Comment by maelle** [comment]
See also #2792 -- thanks for the bug report nonetheless!
