### ISSUE TITLE
News.md with second level header

### ISSUE THREAD

**Issue by LouisLeNezet** [r-lib/pkgdown#2798]
Hi,

I'm using your fantastic package to build my package website and it works really nicely.
The only issue I have is with the `News.md` file.

The titles in the markdown are not correctly detected if they use a level two headings `##`.
It works with a level one `#` but then I get complains with the linter that `MD025/single-title/single-h1: Multiple top-level headings in the same document`.

My document looks like:

```md
# Changelog

## Changes in v1.1.3

- Fix github workflows

## Changes in v1.1.2

- Use R version 4.4 and update workflows

## Changes in v1.1.1

- A [shiny application](https://shiny.posit.co/) is now available through
the `ped_shiny()` function.

## Changes in v0.99.0

- Kinship2 is renamed to Pedixplorer and hosted on Bioconductor.
```

Would it be possible to work with level two, and if so how should I write the `News.md` ?

**Comment by jayhesselberth** [comment]
If you remove the h1 line(`# Changelog`) line then it should build.

**Comment by LouisLeNezet** [comment]
Effectively but the I got:
`MD041/first-line-heading/first-line-h1: First line in a file should be a top-level heading`

**Comment by jayhesselberth** [comment]
If I copy your example, remove the first two lines, and run `pkgdown::build_news()` it builds without error.

Can you send `sessioninfo::session_info()`

**Comment by LouisLeNezet** [comment]
It effectively works without the two first line.
I just got a warning when linting the markdown that is all 😄 
I was just wondering if it was possible to have a `h1` and then `h2` with the versions changes.

**Comment by jayhesselberth** [comment]
That is what is done in the pkgdown NEWS file (h1 and then h2 with versions.

https://raw.githubusercontent.com/r-lib/pkgdown/refs/heads/main/NEWS.md

The differences come down to (I think) how you are specificying the version information. pkgdown is pretty opinionated about that.

Closing for now, let us know if you have other issues.
