### ISSUE TITLE
Incomplete sentence in error message

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#2800]
when topics are missing from reference index.

A reprex is provided in pkgdown tests.

Code: 

https://github.com/r-lib/pkgdown/blob/8d9cba19fe597bba170f8d4c99f351491ab4f4d1/tests/testthat/test-build-reference-index.R#L53-L61

Output:

https://github.com/r-lib/pkgdown/blob/8d9cba19fe597bba170f8d4c99f351491ab4f4d1/tests/testthat/_snaps/build-reference-index.md?plain=1#L53-L61

Relevant code chunk to modify:

https://github.com/r-lib/pkgdown/blob/8d9cba19fe597bba170f8d4c99f351491ab4f4d1/R/build-reference-index.R#L172-L179

**Comment by jayhesselberth** [comment]
It's not clear to me from the blame what was intended to follow "or".

**Comment by Bisaloo** [comment]
I suspect it was "or add them to *link to the config file*". I'm not completely sure either though.

**Comment by hadley** [comment]
Or add to the reference index, I assume.
