### ISSUE TITLE
Nav links flash a dark (from dark mode?) color during page load on chrome

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#2805]
Easy to see on the main pkgdown site, with light-switch off (light mode), click "references" and the link flash to a dark color before setting the light one.

I remember @gadenbuie mentioning something about colors flashing in the dark mode PR but I can't find it now.

**Comment by hadley** [comment]
Hmmm, I don't see that in Safari.

**Comment by jayhesselberth** [comment]
I'm on chrome.

**Comment by jayhesselberth** [comment]
I don't see this anymore on Chrome. Maybe there was a fix in a recent update? Closing.
