### ISSUE TITLE
allow linkifying the logo

### ISSUE THREAD

**Issue by mcol** [r-lib/pkgdown#2817]
I couldn't find a way to linkify the logo so that it points to a specific URL. For example, this sample `README.md` contains a link:
```markdown
# pkgdown <a href="https://pkgdown.r-lib.org/"><img src="man/figures/logo.png" align="right" /></a>
```
but the resulting html only contains:
```html
<div class="page-header">
<img src="logo.png" class="logo" alt=""><h1 id="pkgdown-">pkgdown 
<a class="anchor" aria-label="anchor" href="#pkgdown-"></a>
</h1>
</div>
```
It's as if the link is stripped. It would be nice if it was respected or if there was some yaml setting to control the URL associated to the logo.

**Comment by hadley** [comment]
For various complicated reasons, the logo is stripped from the HTML and re-added by pkgdown to each page. Unfortunately I think it's going to be a lot of work to fix this, especially given that there's already a prominent link to the home page.
