### ISSUE TITLE
Disable hyphenation by default

### ISSUE THREAD

**Issue by dvg-p4** [r-lib/pkgdown#2820]
pkgdown 2.1.0's changelog contains the following item:
> Very wide words are now automatically broken across lines and hyphenated (when possible) when they’d otherwise create a horizontal scrollbar on mobile ([#1888](https://github.com/r-lib/pkgdown/issues/1888)).

However, the [actual change made](https://github.com/r-lib/pkgdown/pull/1888/files#diff-42da929cc764e94ef6b729b3670bf1f2b086c8906ac4b67b8d0aefaba53133fa) seems to impact far more than just "very long words...on mobile". In fact, it seems to affect all content in the main body of any roxygen site page, and tends to be incredibly eager to hyphenate almost any word at the end of a line.

There are some fairly egregious examples in [your own development docs](https://roxygen2.r-lib.org/dev/articles/roxygen2.html):
<img width="819" alt="image" src="https://github.com/user-attachments/assets/889d60c2-3e63-4a99-89e2-24907368482c">

> ... for other de-
> velopers ...

> ... generics and class-
> es, ...

And even worse, long variable or function names inside of *code tags* can still get hyphenated:
<img width="782" alt="image" src="https://github.com/user-attachments/assets/ee50a19c-8513-44c9-b94c-84c2b690e643">

I think this loss in clarity and legibility is not at all worth it just to occasionally avoid horizontal scrollbars on mobile.

**Comment by dvg-p4** [comment]
another egregious example on your main site:
<img width="807" alt="image" src="https://github.com/user-attachments/assets/cb5fcad1-6e9e-40cd-a0b3-81bfa9bf3c30">

**Comment by jayhesselberth** [comment]
Yikes, that is some aggressive hyphenation. We could disable, but I'm wondering if there's a better CSS approach for more conservative treatment of word breaks.

**Comment by dvg-p4** [comment]
They're still `<code>` tags, so `code {hyphens:none}` works there...but I'd argue that they're also a significant bane to readability in the prose text as well.

As far as I can tell from a google search, the only middle ground between `hyphens: auto` and `hyphens: none` appears to be `hyphens: manual`, which inserts hyphens only where suggested by "soft hypen" characters (Unicode `U+00AD` / HTML `&shy;`) that are manually placed. I'm not sure if those are supported in roxygen/.Rd files generally?

**Comment by hadley** [comment]
Maybe we could only enable auto hyphenation when the page width is particularly narrow?
