### ISSUE TITLE
vignette 

### ISSUE THREAD

**Issue by tiozab** [r-lib/pkgdown#2825]
instead of using "build_site()" to preview which will lead to problems in many cases would it not be better to say to use the "preview_site()" function which will always work?
![image](https://github.com/user-attachments/assets/30b2442d-da09-46d4-bca4-52029228cdeb)

**Comment by hadley** [comment]
You need to build it before you can preview it.

**Comment by tiozab** [comment]
thanks @hadley I figured that out in the meantime. Yet, I think the reference https://pkgdown.r-lib.org/reference/build_site_github_pages.htmlis misleading because it says that it runs the build_site() in the process already which it seams it does not unless I am not using it correctly. I am a novice to building a webpage from a package, so this is my first time experience.
