### ISSUE TITLE
build_favicons generates 96x96 but not 16x16 and 32x32 as refrenced in browser

### ISSUE THREAD

**Issue by brandonerose** [r-lib/pkgdown#2831]
I was publishing my package and I used usethis::use_logo() and pkgdown::build_favicons() but it appears the API you all use returns a favicon-96x96.png but not 16 and 32 which for me are the ones refrenced in the HTML thats generated in docs. 

<img width="1373" alt="Screen Shot 2024-12-16 at 6 17 20 PM" src="https://github.com/user-attachments/assets/091dcee7-570b-454b-82e2-bc57420085cb" />

<img width="295" alt="Screen Shot 2024-12-16 at 6 16 26 PM" src="https://github.com/user-attachments/assets/3632866a-0553-48e3-b132-cde1c49b69ea" />

<img width="194" alt="Screen Shot 2024-12-16 at 6 03 19 PM" src="https://github.com/user-attachments/assets/353b0ae5-ba9c-48a0-9917-9c7a0c23c2f5" />

<img width="685" alt="Screen Shot 2024-12-16 at 6 02 29 PM" src="https://github.com/user-attachments/assets/1c673672-e325-49ba-9275-af9d2d9a33a3" />

My work around was cloning the 96x96 to those other two files but a better fix may be rendering the proper 96 file in the HTML (which I dont know how to do).

```
# while in the gh-pages branch I just ran this for my fix
file.copy(from = "favicon-96x96.png", to = "favicon-16x16.png")
file.copy(from = "favicon-96x96.png", to = "favicon-32x32.png")
```

**Comment by jayhesselberth** [comment]
This will be fixed in an upcoming release, see #2804.
