### ISSUE TITLE
support for custom syntax highligthing

### ISSUE THREAD

**Issue by lbusett** [r-lib/pkgdown#375]
Hi, 
   
  first of all, thanks for a really nice package ! 

Coming to the topic, I was wondering if there is the possibility to use a customized syntax hihligthing  scheme for rendering code chunks and examples. 

I know that I can customize code appearance by creating and tweaking the "extra.css" file in /pkgdown, but I think it could be nice to be able to use some ready-made color schemes such as the ones available form Rstudio when generating an html _via_ knitr.

**Comment by hadley** [comment]
Not at this time, sorry.
