### ISSUE TITLE
CONDUCT.md, CONTRIBUTING.md, and friends

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#381]
What should pkgdown do with these files? Or should it do anything?

**Comment by hadley** [comment]
Also need to tweak any local links in README to point to `.html` instead of `.md`

**Comment by hadley** [comment]
If both `LICENSE` and `LICENSE.md` exist (as with `use_mit_license()`), what should we do? Probably best to link to rendered `LICENSE`?

**Comment by hadley** [comment]
To do:

* [ ] Extract first heading and use as page title
* [ ] If `LICENSE.md` exists, don't write out `LICENSE`
* [ ] Also look in `.github`
* [ ] Tweak links to `.md` to point to .html
* [ ] Figure out why path is so wacky

**Comment by batpigandme** [comment]
Still getting #540 with the latest pkgdown build (which might totally be what you mean by `Extract first heading...`).

Example:
```
-<title>License • tidyr</title>
+<title>/Users/maraaverick/tidyr/LICENSE.md • tidyr</title>
```

**Comment by hadley** [comment]
@mara what top-level files should automatically get a link from the home page, or in the navbar, or elesewhere?

e.g. If code of conduct exists, should the footer link to it from every page?

**Comment by batpigandme** [comment]
I feel like the pkgdown site doesn't need to have easy access to those top-level files so much as have them be linkable (as they are now).

Like CoC link should def. work from contributing, but it doesn't nec. need to be easy to get to on its own (if that makes sense).
