### ISSUE TITLE
Build a single article

### ISSUE THREAD

**Issue by javierluraschi** [r-lib/pkgdown#382]
I would like to be able to filter what I build, say by saying:

```
pkgdown::build_articles(filter = "my-document.Rmd")
```

The challenge is that some documents take too long to render for other non-pkgdown reasons, so it would help me out to update only a subset of the site.

**Comment by hadley** [comment]
Maybe #337 would solve your problem without requiring a new param?

**Comment by hadley** [comment]
Alternatively, maybe we should expose `build_article()`?
