### ISSUE TITLE
After running build::site() index.html opens in text editor

### ISSUE THREAD

**Issue by jrosen48** [r-lib/pkgdown#384]
When I run `build::site()`, the `index.html` loads in my default text editor, instead of in my default browser. Is this due to an R or R Studio setting, password setting -- something else? The site still appears fine through GitHub pages.

**Comment by nsheff** [comment]
just a thought -- is it possible that your system is set to use a text editor as the default application for opening `html` files?

**Comment by hadley** [comment]
`preview_site()` calls `utils::browseURL()` which uses the default application associated with `.html` files.
