### ISSUE TITLE
Auto-preview on build_home(), build_reference()?

### ISSUE THREAD

**Issue by lbusett** [r-lib/pkgdown#392]
Hi, 

  Similarly to what happens when running `build_site()` I'd propose adding the possibility to automatically open a preview of the modified sections after running `build_home()` (opens index.html), `build_reference()` (opens reference/index.html), `build_articles()` (opens articles/index.html), etc... . It's a small thing, but it would allow quickly checking  changes without having to navigate to the appropriate /docs subfolder to  open the file manually in a browser. 

On a side note, since I'm not accustomed in contributing to other people's repositories: If I'd wish to make a PR to try to implement such a feature would it be better to first discuss it here (to see if it is of interest/makes sense), or should  I just make it and leave the maintainer to decide wheter to implement it ?

**Comment by hadley** [comment]
I like the idea of adding a `preview` argument to every `build_xyz()` and then `build_site()` would call them all with `preview = FALSE`. A PR would be lovely! (And yes, it's generally good practice to ask)
