### ISSUE TITLE
Build of index.html fails due to path issues with README.Rmd

### ISSUE THREAD

**Issue by nhejazi** [r-lib/pkgdown#394]
If you use a BibTex file to store references that are referred to in the `README.Rmd` (and that builds perfectly fine into a `README.md` for presentation on GitHub locally via pandoc), building the file `index.html` fails (with pandoc error either 83 or 85 -- I've tried this with homebrew version of pandoc and pandoc-citeproc on MacOS and remotely on a Red Hat system). Perhaps I'm missing some way to work around this?

**Comment by mvuorre** [comment]
I can't reproduce the problem. Using a .bib file works for index.html here: 

<https://github.com/mvuorre/exampleDataPackage/> (GitHub repo)
<https://mvuorre.github.io/exampleDataPackage/> (pkgdown website based on above)

Can you give more details on what you're trying and what exactly is the problem?

**Comment by nhejazi** [comment]
Sure -- specifically, I tried to add BibTeX-style references to the README for my `biotmle` repo [here](https://github.com/nhejazi/biotmle).

I get the following output when (re-)building the `pkgdown` site:
```
R > pkgdown::build_site()
Initialising site -------------------------------------------------------------
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/jquery.sticky-kit.min.js'
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/link.svg'
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/pkgdown.css'
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/pkgdown.js'
Building home -----------------------------------------------------------------
Updating README.md
Building article 'index.html'
Error: pandoc document conversion failed with error 83
R >
R >
```

**Comment by mvuorre** [comment]
This is an issue with the .bib file not being found in the directory where the document is rendered. Fortunately, there's an easy fix: install the [here](https://cran.r-project.org/web/packages/here/index.html) package, then include this as the path to your .bib file:

```
bibliography: "`r here::here('README-refs.bib')`"
```

In the future, pkgdown may make this fix obsolete, but for now this should work for you.

**Comment by hadley** [comment]
Would either of you minding making the simplest possible package that illustrates this problem?

**Comment by hadley** [comment]
Also can you please use a more informative title?

**Comment by nhejazi** [comment]
Hello ---

Here's the simplest R package I could make that reproduces this problem: https://github.com/nhejazi/pkgdown_rmd

I've confirmed that the use of `pkgdown` on the `README.Rmd` of this package creates a problem similar to what I initially reported:

```
Initialising site -------------------------------------------------------------
Creating 'docs/'
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/jquery.sticky-kit.min.js'
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/link.svg'
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/pkgdown.css'
Copying '/Users/nimahejazi/.Rlibrary/pkgdown/assets/pkgdown.js'
Building home -----------------------------------------------------------------
Writing '/Users/nimahejazi/git/pkgdown_rmd/docs/authors.html'
Updating README.md
Building article 'index.html'
Error: pandoc document conversion failed with error 83
```

FWIW, use of `bibliography: "`r here::here('README-refs.bib')`"` as recommended by @mvuorre does fix this problem, but maybe this should at least be added to the `pkgdown` documentation, unless a different fix is preferred.

Re: title (assuming this refers to the issue), I've changed it to hopefully be more helpful/informative.

**Comment by hadley** [comment]
Hmmm, fixing this is going to be a little complicated. Building `index.html` happens in two phases. In the first phase, `README.Rmd` is rendered to `README.md` in the package directory. This phase succeeds, and generates a bibliography in the `.md` file.

The second phase renders `README.md` to `index.html`, after it has been copied to the documentation directory. It's copied to this directory so any figures are output in the correct place. It fails because (even though it doesn't actually need it), it can no longer find the bibliography. One possible solution is to use `output_dir` in `rmarkdown::render()`, but this seems like such an obvious approach, I suspect I tried it previously and it had some unappealing side-effect.

**Comment by nhejazi** [comment]
Thanks for looking into this and diagnosing the issue @hadley. I think I see why this could be a bit convoluted to resolve, at least in as much as it's going to require changing an aspect of how the `pkgdown` build process currently works. While I'm not sure about the side-effects that might emerge from specifying `output_dir`, it seems like another option would be to copy the `.bib` file to the documentation directory along with `README.md`; in this case, the conversion to `index.html` shouldn't fail (even though it doesn't need the `.bib` file, `README.md` can still find it at least). Maybe I'm missing something here though. In any case, if there's a preferred solution that I can help with, do let me know and I'll do what I can at that point.
