### ISSUE TITLE
FR: Generate sitemap.xml files

### ISSUE THREAD

**Issue by stephlocke** [r-lib/pkgdown#400]
To help SEO and screen readers, a sitemap.xml file would be very helpful
https://support.google.com/webmasters/answer/183668

**Comment by hadley** [comment]
How does this help screen readers?

**Comment by stephlocke** [comment]
Having multiple ways of navigating site structure is useful for screenreaders and is a recommended part of the guidelines from webAIM https://webaim.org/standards/wcag/checklist

**Comment by hadley** [comment]
I'm pretty sure that guideline is referring to an html sitemap, not a `sitemap.xml`

**Comment by hadley** [comment]
This looks like quite a bit of work, so I'm going to close for now. We might reconsider in the future.
