### ISSUE TITLE
tables should have a bottom margin

### ISSUE THREAD

**Issue by kevinushey** [r-lib/pkgdown#403]
E.g.

![screen shot 2017-08-25 at 1 37 53 pm](https://user-images.githubusercontent.com/1976582/29731792-b1bf9712-899a-11e7-8f63-72deedb25343.png)

Note that there is no spacing between the table and the following text.

**Comment by kevinushey** [comment]
Alternatively, this could be resolved by wrapping the inner text of the table cells in `<p>` (as is done for argument tables).

(For reference, this table was created with `\tabular{ll}{...}`)

**Comment by hadley** [comment]
Where does this come from?

**Comment by kevinushey** [comment]
Documentation generated from here: https://github.com/rstudio/tfestimators/blob/45247bfae53766c8992aa6bf63d56ebc02ab7f89/R/tf_custom_estimator.R#L115-L126

Associated page: https://tensorflow.rstudio.com/tfestimators/reference/estimator.html

Looks like the `pkgdown` styling has changed since then so all looks well:

![screen shot 2018-02-20 at 3 34 30 pm](https://user-images.githubusercontent.com/1976582/36455119-972ad470-1653-11e8-8112-2a8722d6e157.png)

The preformatted block above feels a little cramped though:

![screen shot 2018-02-20 at 3 35 04 pm](https://user-images.githubusercontent.com/1976582/36455136-abb04628-1653-11e8-9bca-008fc6dfe6fa.png)

**Comment by hadley** [comment]
I _think_ that's a problem with the custom style sheet that tensorflow uses — note that the font of that pre block does not match the usage.
