### ISSUE TITLE
error running pkgdown

### ISSUE THREAD

**Issue by pachevalier** [r-lib/pkgdown#411]
Trying to run build_site() on my new package : https://github.com/SGMAP-AGD/opensirene, I've got the following error : 

> Error: inherits(x, "xml_node") is not TRUE

**Comment by jayhesselberth** [comment]
Your README is empty. Add a single markdown header (e.g. `# opensirene`) to `README.md` and the rest of the docs build.

**Comment by kforner** [comment]
still, should either not fail or fail with a more explicit message.
