### ISSUE TITLE
<details> tag rendered incorrectly when used with r-chunk

### ISSUE THREAD

**Issue by adibender** [r-lib/pkgdown#419]
In the screenshot below the first `details` tag is rendered correctly, while the second is rendered as 
```html 
<details> </details> 
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> ...
```
when using `pkgdown::build_site()`. Interestingly, the closing `</details>` tag is set correctly, when using `knit` button in RStudio IDE. For both output ist set to `output: rmarkdown::html_vignette`

![bildschirmfoto vom 2017-10-09 13 52 28](https://user-images.githubusercontent.com/1672665/31336978-9c0714fe-acf9-11e7-9443-6344a31e97b3.png)

**Comment by hadley** [comment]
Can you please give me some more context? What is the problem? Where are the `<details>` coming from?

**Comment by adibender** [comment]
Certainly. Sometimes, when wirtting vignettes, I want to hide some R-Code chunks, like so: 

<details>
<summary> Expand here for R-Code</summary>

```r 
some_code_i_want_to_hide <- rnorm(10)
```

</details>

</br>

Consider this (example) vignette: https://gist.github.com/adibender/115d3cd1004bfd12f1944214ac712c7f

When rendering this vignette using `rmarkdown::render("atest.Rmd")`, it renders correctly as follows (dretails Tag is not expanded and code is hiden): 
![render](https://user-images.githubusercontent.com/1672665/36502770-3aebb898-174b-11e8-84c3-9efd909b2f4a.png)


When rendering with `build_articles()` it renders as follows (details tag is not extended, code chunk is visible nevertheless): 
![build_articles](https://user-images.githubusercontent.com/1672665/36502651-e353b69e-174a-11e8-9e64-3d30394ea90a.png)

**Comment by hadley** [comment]
Do you happen to have a link to a public facing page with that problem?

**Comment by adibender** [comment]
For example here: https://adibender.github.io/pammtools/articles/tveffects.html

I'd like to hide the code for the 2nd Figure from the bottom. As it is not essential for understanding and the content of the vignette. However, I would like the reader to be able to reproduce the graph, if so desired.

**Comment by hadley** [comment]
I made a simple test case, and it seems to work just fine for me: http://pkgdown.r-lib.org/articles/test/details.html

Can you please see if you can isolate exactly what is making it fail for your vignette?

**Comment by adibender** [comment]
I cloned pkgdown and the error persisted. I've updated pandoc from v1.17.1 to 2.1.1-1, now it works. 
Thanks, and sorry for not realizing earlier.
