### ISSUE TITLE
build_site() adds an invalid regrex to .Rbuildignore

### ISSUE THREAD

**Issue by friendly** [r-lib/pkgdown#423]
My first time trying `pkgdown` (very nice work!).  After an error in my `_pkgdown.yml` file was corrected, I got a mysterious error:

    > pkgdown:::build_site_rstudio()
    Updating matlib documentation
    Loading matlib
    Error in FUN(X[[i]], ...) : 
      invalid regular expression '^C:\Dropbox\R\projects\matlib\docs$'
    In addition: Warning message:
    In FUN(X[[i]], ...) : PCRE pattern compilation error

It turned out that `build_site()` had added this line to `.Rbuildignore`:

    ^C:\Dropbox\R\projects\matlib\docs$

That should have been simply

    docs/

**Comment by tjmahr** [comment]
I ran into this issue too. Reported in #409 and submitted a fix in #410.

**Comment by maurolepore** [comment]
Same here.
