### ISSUE TITLE
Error building articles

### ISSUE THREAD

**Issue by friendly** [r-lib/pkgdown#424]
After correcting the error described in #423, I get the following error, when articles are being built.
This is for the `matlib` package, https://github.com/friendly/matlib.
The vignettes in the site do seem to be built under `docs/articles`.

    Processing vectors3d.Rd
    Writing 'C:\Dropbox\R\projects\matlib\docs/reference/vectors3d.html'
    Processing workers.Rd
    Writing 'C:\Dropbox\R\projects\matlib\docs/reference/workers.html'
    Building articles -------------------------------------------------------------
    Creating 'C:\Dropbox\R\projects\matlib\docs/articles/'
    Building article 'det-ex1.html'
    Error in process_initialize(self, private, command, args, commandline,  : 
      processx error, create process: #0 The operation completed successfully.
     at 'win/processx.c:678'
    Calls: withCallingHandlers ... process_initialize -> .Call -> .handleSimpleError -> h
    Execution halted
     
    Error in process_initialize(self, private, command, args, commandline,  : 
      processx error, create process: #0 The operation completed successfully.
     at 'win/processx.c:678'
    > traceback()
    4: stop(err[[2]])
    3: get_result(output = out, options)
    2: callr::r(function() pkgdown::build_site(), show = TRUE)
    1: pkgdown:::build_site_rstudio()
    >

**Comment by maurolepore** [comment]
Can you please try installing a development version of __processx__ (https://github.com/r-lib/processx)?

This seems related to a similar issue in __reprex__ (https://github.com/tidyverse/reprex/issues/136#issuecomment-345590577)
