### ISSUE TITLE
feature request: facilitate creating `_pkgdown.yml` via @category

### ISSUE THREAD

**Issue by friendly** [r-lib/pkgdown#435]
For a package with functions in different categories, creating the `_pkgdown.yml` reference: section would be much easier if support could be added for an `@category:` roxygen comment.
Or, is there something already available that I've missed?

**Comment by hadley** [comment]
That might be something to consider in the future, but currently there's no connection between roxygen2 and pkgdown, except via the generated `.Rd`files
