### ISSUE TITLE
show method and class in reference listing

### ISSUE THREAD

**Issue by topepo** [r-lib/pkgdown#436]
It would be good to have an _option_ to something to show `method.class` at least for S3 methods. 

For example, `tidyposterior` defines a new class (`Bayes_resample`) with a bunch of methods and the [reference](https://topepo.github.io/tidyposterior/reference/index.html) page has an entry for "Bayes_resample". This makes a lot of sense.  

The package also has a `tidy` method (`tidy.Bayes_resample`) and the reference page just has an entry for "tidy". That's a little confusing since that original function/class is in another package. 

Also, the package has two `summary` methods for different classes and these are listed twice just as "summary". 

I'm not sure that I have a crisp recommendation of what I think it should do, but the existing reference listing is a little confusing.

**Comment by aaronrudkin** [comment]
I noticed this in [one of our packages](http://estimatr.declaredesign.org/reference/index.html) as well -- we implement a half-dozen object types with standard S3 methods so the reference page is a ton of apparently duplicate method names that you need to deduplicate by reading the method descriptions.

**Comment by hadley** [comment]
How does this sound for a heuristic: 

* If a generic and methods are documented together in the same file, only show the generic name
* If a method is documented without the generic, show the full S3 method name

?

**Comment by hadley** [comment]
<img width="742" alt="screen shot 2018-03-16 at 2 37 19 pm" src="https://user-images.githubusercontent.com/4196/37541176-90586b08-2927-11e8-8825-919241f3e690.png">

New display of methods; haven't yet started filtering out methods if generic documented.

@topepo I think you are picking up my consonant doubling habits 😉

**Comment by hadley** [comment]
<img width="297" alt="screen shot 2018-03-16 at 2 46 11 pm" src="https://user-images.githubusercontent.com/4196/37541486-c9b56f30-2928-11e8-8081-8048521041be.png">

And now with method trimming
