### ISSUE TITLE
Ensure that formatting in section headings is correctly translated 

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#437]
e.g. http://ggplot2.tidyverse.org/reference/geom_text.html#-code-geom-label-code-

Moved from https://github.com/tidyverse/ggplot2/issues/2231

**Comment by jennybc** [comment]
Just adding more concrete detail:

``` r
#' @section `use_travis()`:
#' blah blah blah
```

leads to an `.Rd` file that looks as expected but problems in pkgdown

<img width="866" alt="screen shot 2018-02-18 at 4 53 57 pm" src="https://user-images.githubusercontent.com/599454/36359097-5d57c2ea-14cc-11e8-9fd8-622f00468a7d.png">
