### ISSUE TITLE
pandoc: Unknown extension: smart

### ISSUE THREAD

**Issue by flaviobarros** [r-lib/pkgdown#443]
I am receiving this error on Linux Mint 18.1, RStudio 1.1.383 and R 3.4.2. I thought the problem was pandoc version but I just installed pandoc 2.0 and the problem remains.

I just found the related issue #439. But I am surprised that it is closed. I saw the workaround in Linux but I don't that this fixes the issue.

**Comment by flaviobarros** [comment]
#439

**Comment by hadley** [comment]
The code now contains `if (!rmarkdown::pandoc_available("2.0")) "--smart"` which I believe should have fixed your issue
