### ISSUE TITLE
Add release dates to news

### ISSUE THREAD

**Issue by batpigandme** [r-lib/pkgdown#444]

**Comment by jayhesselberth** [comment]
Are you thinking dates would be populated from `git tag` information?

**Comment by batpigandme** [comment]
That's a good question. My thought was that it would be similar to the `change log`, but restricted to major and minor, (e.g. below— just happened to know Nick Tierney has dates there for [visdat](http://visdat.njtierney.com/news/index.html)), but that's as far as I'd gotten. 
![image](https://user-images.githubusercontent.com/831732/32951861-704f3384-cb79-11e7-835e-50534d78be06.png)

**Comment by hadley** [comment]
I think we'd have to cross-reference with some database of CRAN info. 

@gaborcsardi can you please suggest the best place to start?

**Comment by gaborcsardi** [comment]
I guess you would need sg. like 
```r
httr::GET("http://crandb.r-pkg.org/dplyr/all") %>% 
  httr::content() %>% 
  `[[`("timeline")
```

Is this all the info you need?
