### ISSUE TITLE
Skip selected vignettes

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#457]
I was looking for a way to skip building some (yet incomplete, therefore failing) vignettes.

I *can* skip it for `R CMD check` with `.rbuildignore`, but this doesn't affect `pkgdown::build_site()` (as intended).

I was hoping that *manually* listing only a subset of `*.Rmd`s inside my `_pkgdown.yml` would make `pkgdown` skip the remainder, but nope.

So I ended up putting the drafts in a hidden `vignettes/.drafts/` subdirectory, which is quite ugly.

**Comment by hadley** [comment]
One easy fix would be to just add `knitr::opts_chunk$set(eval = FALSE)` to the start of the document.

Adding something to `_pkgdown.yml` is either going to be quite a lot of work or quite hacky, so I'd prefer not to implement right now.

**Comment by pokyah** [comment]
maxDiscovering pkgdown and was encountering the same problem as @maxheld83 

What would you think about adding a key in the header specifying that the vignette is still in draft mode ? 

---
title: "Future Vignette"
author: "pokyah"
date: "11/27/2018"
output: html_document
draft: TRUE
---

Would it make sense to implement this proposition ?
