### ISSUE TITLE
rstudio addin doesn't show build messages and warnings

### ISSUE THREAD

**Issue by dracodoc** [r-lib/pkgdown#459]
Usually `build_reference` will warn for non-internal functions not included in reference. However when using the RStudio addin to build site, the build messages and warnings are not shown.

[This line](https://github.com/r-lib/pkgdown/blob/master/R/build.r#L193) is supposed to show them because of `show = TRUE`, I don't know why it didn't work.

```r
callr::r(function() pkgdown::build_site(), show = TRUE)
```

**Comment by hadley** [comment]
This works for me - you may need to update your version of callr
