### ISSUE TITLE
orphan files are not cleaned up in building

### ISSUE THREAD

**Issue by dracodoc** [r-lib/pkgdown#460]
I noticed that if some files were changed names or no longer used, the previously generated files become orphan files and will stay there.

There is a `clean_site` function but was not used. One simple way is to add a parameter `clean = FALSE`, and clean site when `clean = TRUE`. So default behavior should not change, but user can generate the site cleanly in the final run before publishing them.

The change is simple but I want to hear more comments before making a PR.

**Comment by hadley** [comment]
For now, I think the cleaning needs to be manual. But a PR to the docs would be appreciated!
