### ISSUE TITLE
404 Page not found error when following first link in README

### ISSUE THREAD

**Issue by ras44** [r-lib/pkgdown#461]
README.md references http://hadley.github.io/pkgdown/ in the first paragraph, but it leads to a 404 Page not found Error.

**Comment by gustavdelius** [comment]
That link should be changed to http://r-lib.github.io/pkgdown/ or to http://pkgdown.r-lib.org/

**Comment by znmeb** [comment]
The bad link is also showing up at the bottom of a pkgdown-built site! See issue #481

**Comment by hadley** [comment]
Fixed a while back - thanks for reporting!
