### ISSUE TITLE
refactor alternating citations

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#466]
[Sites with multiple citations](https://pat-s.github.io/mlr/authors.html) have alternating html and bibtex citations, which makes copying the bibtex unwieldy. Better to display (numbered?) html citations together, then bibtex together.

**Comment by pat-s** [comment]
Thanks for taking care :smile: :+1: haven't noticed yet

**Comment by hadley** [comment]
I don't quite understand the workflow here - do people usually cite all the citations en masse? Wouldn't you normally just copy and paste the one or two papers that you cited?

**Comment by hadley** [comment]
What if we continued to have the bibtex appear after each text citation, and then include all of them in one place at the bottom of the page?

**Comment by jayhesselberth** [comment]
I don't think it's worth having the bibtex in two places. I was just trying to make it easy to copy all the bibtex rather than have to think about one by one. Interleaved is probably fine as most packages likely only have 1 or 2 citations.
