### ISSUE TITLE
Use globalenv for rmarkdown rendering in build_home

### ISSUE THREAD

**Issue by nbenn** [r-lib/pkgdown#467]
I have an issue with s3 dispatch in an rmarkdown chunk (in a readme). Consider something like

```r
point <- function(x, y) {
  stopifnot(is.numeric(x), is.numeric(y))
  structure(list(x = x, y = y), class = "point")
}

abs.point <- function(x) {
  sqrt(x$x ^ 2 + x$y ^ 2)
}

points <- mapply(point, runif(5), runif(5), SIMPLIFY = FALSE)

sapply(points, abs)
```

as a code chunk in an `.Rmd` file `README.Rmd`. Currently, `build_site()` will fail (or at least is does for me) with `non-numeric argument to mathematical function`.

As per suggestion by @gaborcsardi at r-lib/callr#33, this could be fixed by adding the argument `envir = globalenv()` to the `rmarkdown::render` call [here](https://github.com/r-lib/pkgdown/blob/d436a0ac943abbbb3a67dc2f6407116e4e458957/R/build-home.R#L74).

This might be related to #417.

**Comment by jennybc** [comment]
Just to link it all up, this is also the solution settled upon in consultation with @gaborcsardi for reprex, for the same reasons: https://github.com/tidyverse/reprex/blob/8cd9c5e51943281d278001df7252df370c20e87a/R/reprex.R#L336
