### ISSUE TITLE
"Developed by ..." and "Site built with pkgdown." are rendered incorrectly in Internet Explorer

### ISSUE THREAD

**Issue by alekrutkowski** [r-lib/pkgdown#470]
"Developed by ..." and "Site built with pkgdown." are rendered incorrectly in Internet Explorer (screenshot attached).
![iexplore_screenshot](https://user-images.githubusercontent.com/7509427/33996453-86eff3a8-e0e1-11e7-8206-d6ee4d1e996f.png)

**Comment by hadley** [comment]
What version of IE?

**Comment by alekrutkowski** [comment]
IE 11.248 and IE 11.0 (checked on different machines).



*Aleksander Rutkowski*

*mobile (+32) 488.572.733*
*office (+32) 2 298.01.60*

**Comment by hadley** [comment]
Probably explained in https://github.com/philipwalton/solved-by-flexbox/blob/master/assets/css/components/site.css#L2-L6

**Comment by hadley** [comment]
I don't have IE, but as far as I can I've now worked around the bug that was triggering the problem.
