### ISSUE TITLE
Show GitHub commit ID in "References"

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#473]
next to the version number. Perhaps with a GitHub link?

In the screenshot below, the commit ID could be added right of the highlighted text.

![screenshot from 2017-12-18 16-16-21](https://user-images.githubusercontent.com/1741643/34113066-d1c0b8ba-e40e-11e7-95d4-dc35eec537df.png)

**Comment by hadley** [comment]
I'd rather think this through in the context of https://github.com/r-lib/pkgdown/issues/393 and/or https://github.com/r-lib/pkgdown/issues/364
