### ISSUE TITLE
Make it possible to select single alias

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#479]
Take [fs](http://fs.r-lib.org/reference/index.html) - it has a number of functions like `dir_exists()`, `file_exists()` and `link_exists()`. They are documented in a single file because they're closely related, but end up duplicated in three different locations in the function reference. Ideally, each one would only show the aliases that match the topic.

**Comment by jennybc** [comment]
As requested, adding another concrete example.

http://usethis.r-lib.org/reference/index.html

If I want to list `edit_git_config()` in the "Git and GitHub" section, it's regrettable that all the `edit_*()` functions come along for the ride.

**Comment by hadley** [comment]
This would be really nice, but I can't see any straightforward way to implement it. The problem is that the section building code is very far away from the code that generates the terms that appear on the index page.

Therefore I'm going to declare problems like this to be a sign that you need to refactor your documentation and maybe use `@import` more than `@rdname`.
