### ISSUE TITLE
plain text and html support for navbar items via pkgdown.yml

### ISSUE THREAD

**Issue by mwillumz** [r-lib/pkgdown#482]
It'd be nice to have the option to include bothtext (without an href) and something like`<span class="badge badge-warning">Warning</span>` inside the pkgdown.yml navbar arguments.

I'd happily supply a pull request if you could point me to the relevant code.

**Comment by hadley** [comment]
Can you please give me an example oh what this would produce?

**Comment by hadley** [comment]
You can already include bare text and icons, as described inhttp://pkgdown.r-lib.org/reference/build_site.html#yaml-config-navbar
