### ISSUE TITLE
News page headings: not generated correctly, issues warning

### ISSUE THREAD

**Issue by sfirke** [r-lib/pkgdown#484]
At the end of `build_site()` I get
```
Building news --------------------------------------------------------------------------------------------------
Writing '/home/sam/git/janitor/docs/news/index.html'
Warning message:
Length of logical index must be 1 or 7, not 8
```

From trying to fix this I believe the problem is with the main headings in my NEWS.md file, those starting with a single `#`.  I have 7 of those, but the first one (0.4.0.9000 in the NEWS.md file itself) is missing along with all of the content for that release in my pkgdown news page: http://sfirke.github.io/janitor/news/index.html

At the end of it there appears an empty release header with version "NA" at the bottom of the NEWS page on the pkgdown site: http://sfirke.github.io/janitor/news/index.html, which I expect is related.

**Comment by mjsteinbaugh** [comment]
+1 I'm seeing this too…not sure how to fix it

**Comment by hadley** [comment]
Should be fixed in master 😄

**Comment by pat-s** [comment]
@hadley Still getting this error with the latest Github: 

```r
pkgdown::build_news()
── Building news ────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning message:
Length of logical index must be 1 or 13, not 14
```

**Comment by sfirke** [comment]
Still observing this behavior with today's version of the package `pkgdown    * 0.1.0.9000 2018-03-17 Github (r-lib/pkgdown@7cbafcd) `

**Comment by sfirke** [comment]
I was able to solve this by removing this overall header on my .Md file:
```
NEWS
===========
```
I noticed dplyr's NEWS page doesn't have one and when I removed this, my changelog page rendered correctly.

If the `=============` package title on a NEWS page is common, or if this is easy to address, then perhaps worth addressing.
