### ISSUE TITLE
Examples using templates_path

### ISSUE THREAD

**Issue by wlandau-lilly** [r-lib/pkgdown#486]
[Here](https://github.com/r-lib/pkgdown/blob/b620ea1cc17b3b959165f8de7c7a063bfd09b2f0/R/render.r#L9), the docs say that I can supply my own templates using the `templates_path` key in `_pkgdown.yml`. I am struggling to make `pkgdown` notice my custom footer from https://github.com/wlandau-lilly/drake/commit/2ca610f932be8d504560027b70106b5d57e3f0ea, and I have not been able to find any guiding examples.

**Comment by hadley** [comment]
Given that `template_path` only appears in the pkgdown source in the documentation, I'd say that this was never implemented 😞

**Comment by hadley** [comment]
I'm going to just remove this from the docs for now.

**Comment by wlandau-lilly** [comment]
I am glad I know now. Thanks, Hadley.
