### ISSUE TITLE
Order mismatch between docs & code

### ISSUE THREAD

**Issue by katrinleinweber** [r-lib/pkgdown#490]
Hello!

It seems to me upon cursory reading of the [homepage](http://pkgdown.r-lib.org/articles/pkgdown.html#home-page) and the [vignette](https://github.com/r-lib/pkgdown/blob/9213dbaca39d348744670d1d0c0799720454e2cf/vignettes/pkgdown.Rmd#L35), that the order for `index` & `ReadMe` files listed there, is different than in the [`build-home.R` code](https://github.com/r-lib/pkgdown/blob/c8726f9242b2b67f572c16422c83cdc8160c7628/R/build-home.R#L121-L123).

Is that a docu error? If yes, I please feel free to tell me to start a PR, aligning the docu with the code.

Cheers :-)

**Comment by hadley** [comment]
Looks like a doc problem! A PR would be 🎉
