### ISSUE TITLE
Use an optional build_path to protect sensitive information

### ISSUE THREAD

**Issue by wlandau** [r-lib/pkgdown#492]
## Feature

I picture something like `build_site(path = "docs", build_path = "some_different_path")`. The idea is to optionally build the site in a different location than the final destination of the output files. The default `build_path` could just be `path`.

## Intended use

For one of my packages, the rendered vignettes and examples often reference the current working directory. If I were to naively build the site on my company's systems, this output would include confidential information that I must not publish. `build_site(path = "docs", build_path = tempdir())` would make the precautions much easier. My current workaround is a clumsy hack that builds the site in a `tempdir()` and then copies the files to `"docs"`.

**Comment by hadley** [comment]
I don't think your workaround is clumsy - I think that's what you should do. I think this need is sufficiently small that I'm unlikely to implement, but I don't think it should be too hard to do yourself, particularly if you use [fs](http://github.com/r-lib/fs)
