### ISSUE TITLE
CITATION file rendering error: 'Error in if (!auto) { : argument is of length zero'

### ISSUE THREAD

**Issue by RLumSK** [r-lib/pkgdown#493]
## Issue 
If the CITATION file contains the call `citation(auto = meta)`, which is used by 
some R packages, the call `build_site()` stops with the error `Error in if (!auto) { : argument is of length zero`.  

## Reason
I tracked this issue back to the function `read_citation()` in 'build-home-citation.R':

```r
read_citation <- function(path = ".") {
  if (!has_citation(path)) {
    return(character())
  }
  path <- file.path(path, 'inst/CITATION')
  utils::readCitationFile(path)
}
```
It is basically the call `utils::readCitationFile(path)` which fails since `meta` is not a recognised object. In theory, the CITATION file itself could be changed to  `citation(package = 'packagename', auto = TRUE)`. This will work for 'pkgdown', but it will not work on CRAN. 

## Solution

I am struggling with a suggestion for a solution. It depends on what the package authors want. An obvious answer would be to remove the line  `citation(auto = meta)` in the CITATION file itself. Two reasons why this might be not the preferred solution:

*  Calling the object `meta` in the CITATION file is a documented example in the [R manual](https://cran.r-project.org/doc/manuals/R-exts.html#CITATION-files), means, it is something which appears to be allowed.
*  Apart from it, I think the problem is more general one: a failed call in the function `read_citation()` should not cause a full stop.

My suggestion, if something unexpected happened, a message and `character()` is returned. Or even better, the function falls back to `citation(package = 'packagename', auto = TRUE)` (and throws a message).

**Comment by jayhesselberth** [comment]
Example: https://github.com/cran/repo/blob/512909f15b8e637517447a64d1a7a4fdfccc09fd/inst/CITATION

Search "citation(auto = meta)" for other examples.

**Comment by jayhesselberth** [comment]
Should confirm behavior after #418

**Comment by hadley** [comment]
Looks like we need to define an object of called `meta`, doing some spelunking to figure out exactly what that object should be.

**Comment by jayhesselberth** [comment]
I think that `read_citation()` could be refactored to:

``` r
read_citation <- function(path = ".") {
  if (!has_citation(path)) {
    return(character())
  }

  name <- pkg$desc$get("Package")[[1]]
  citation(package = name, auto = TRUE)
}
```

However this requires that the package is *already installed* so that `citation()` can find it. I think it is safe to assume this is true?

**Comment by RLumSK** [comment]
Maybe you want to think of something like 

```r
read_citation <- function(path = ".") {
  if (!has_citation(path)) {
    return(character())
  }
  
  pkg <- try(as_pkgdown(path), silent = TRUE)
  
  if(inherits(pkg, "try-error")){
    return(character())
    
  }else{
   name <- pkg$desc$get("Package")[[1]]
   citation(package = name, auto = TRUE) 
    
  }
}
```
It would prevent that a function stop in case the package is not available in the library.

**Comment by hadley** [comment]
It might be installed, but it's possible that it's an older version. I'd prefer to read from the source package.

**Comment by RLumSK** [comment]
Thanks, it works perfectly!
