### ISSUE TITLE
Add special treatment for R consortium as funder

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#494]

**Comment by krlmlr** [comment]
Can we add a logo? I can't find the R Consortiums assets on the web, is there an SVG available somewhere?

**Comment by maelle** [comment]
Not the best version of the logo now that I think about it but here is rhub config https://github.com/r-hub/rhub/blob/6ae6f35e958f3beab1e2c8e6f704affa23c8ce29/_pkgdown.yml#L6
