### ISSUE TITLE
horizontal scrolling for code blocks

### ISSUE THREAD

**Issue by jimhester** [r-lib/pkgdown#497]
It would be nice to support horizontal scrolling for code blocks, e.g. http://seankross.com/notes/css-for-code/

This would prevent the code from wrapping, which often makes them difficult to read.

A simple css rule might be

```
pre code {
  overflow: auto;
  word-wrap: normal;
  white-space: pre;
}
```

**Comment by hadley** [comment]
Fixed in 03d93a1fccf4535c047e2965383aa2b93673414b
