### ISSUE TITLE
Sexpr issues: environment, working directory, multiple expressions

### ISSUE THREAD

**Issue by WastlM** [r-lib/pkgdown#502]
Support for `\Sexpr{}` is currently rudimentary in **pkgdown**:

1. Each Sexpr is evaluated in its own environment inheriting from `globalenv()`,
https://github.com/r-lib/pkgdown/blob/897ffbc016549c11c4263cb5d1f6e9f5c99efb45/R/rd-html.R#L219
while `tools:::prepare_Rd()` uses a common environment for all Sexprs in a file (such that an Sexpr can depend on code evaluated in an earlier Sexpr).

2. The system Rd macros `\packageTitle`, `\packageDescription`, `\packageAuthor`, `\packageMaintainer` (which make use of Sexpr, see https://github.com/wch/r-source/blob/trunk/share/Rd/macros/system.Rd) assume the working directory to be the package root (where the DESCRIPTION lives). This is currently not guaranteed. The working directory is switched temporarily to evaluate the example code in `format_example_chunk()`, but not for Sexpr parsing.

3. A single Sexpr may contain multiple R expressions (such as `\Sexpr{x <- runif(100); mean(x)}`), but only the first one is currently evaluated (see `[[1]]` in the above code snippet) and returned. Why?

I think the first two issues are not straightforward to fix (by design), but maybe the third one is?

**Comment by hadley** [comment]
Would you be interested in working on any of these features? I can offer some guidance, but I don't use `\Sexpr{}`s that much personally, so I'm not highly incented to work on them.

**Comment by WastlM** [comment]
As a first step, I have added a tiny test package at https://github.com/WastlM/pkgdown/tree/test-Sexpr/tests/testthat/site-Sexpr.

Rendering the documentation via
```
build_site(test_path("site-Sexpr"), path = tempfile())
```
fails because of issue 2 above (`\packageTitle` needs the working directory to be the package root).

If we switch the working directory,
```
setwd(test_path("site-Sexpr"))
build_site(path = tempfile())
```
fails because of issue 1 above (pkgdown evaluates the Sexpr's in independent environments).

Finally, if these two failures were prevented, issue 3 above causes the multline Sexpr in https://github.com/WastlM/pkgdown/blob/test-Sexpr/tests/testthat/site-Sexpr/man/Sexpr.Rd#L10 to output just the version from the first expression omitting the "Version:" prefix paste()d by the second expression.

**Comment by WastlM** [comment]
IMHO (and with a limited understanding of **pkgdown**) fixing these Sexpr issues requires a bunch of changes and additional functions. It also feels a bit like reinventing the wheel from what has been implemented in https://github.com/wch/r-source/blob/trunk/src/library/tools/R/RdConv2.R... and there are also options for the Sexpr macro such as `echo` and `results`...

**Comment by WastlM** [comment]
To answer you question: my incentive to work on Sexpr support in pkgdown is currently very limited. The issue could be left open, maybe somebody else likes to step in at some point.

**Comment by WastlM** [comment]
Meanwhile, I would suggest to wrap the evaluation of Sexpr tags, i.e.,

https://github.com/r-lib/pkgdown/blob/da9186355b88d9b660b12a5860273ef64308d3e7/R/rd-html.R#L219

 in `try()`. Upon failure, one could issue a warning saying that Sexpr's are not fully supported and return some placeholder value (or just the empty string).

**Comment by hadley** [comment]
BTW I think 1) is actually fairly easy to fix. We just need to register a "sexpr env" (in `scoped_file_context()`), then retrieve it in `as_html.tag_Sexpr()`. 2) is also simple - you can just copy the code from `format_example_chunk()`.

Providing full `\Sexpr` support is hard, but there's no need to do it all at once. As issues trickle in we can just gradually improve the code to bring it up to parity with the base R code. (And, yes, pkgdown is somewhat duplicative by its very nature - base R also converts `.Rd` to `.html` but there's basically no way to share any code)

**Comment by WastlM** [comment]
Great, thanks! I wouldn't have been able to implement these changes. I find the context stuff not that easy to follow.... :blush: 

I've tried building my test package (https://github.com/WastlM/pkgdown/tree/test-Sexpr/tests/testthat/site-Sexpr). It seems that `package_topics()` also needs to set the `src_path` to allow the `\packageTitle` Rd macro to be used in the Rd title.

https://github.com/r-lib/pkgdown/blob/61eef9b57ac7e30bcd531c65ac04ca4961621d10/R/package.r#L91

should probably be
```r
scoped_package_context(package, src_path = path) 
```

**Comment by hadley** [comment]
Thanks!

**Comment by WastlM** [comment]
Running the current version on my test package still fails because the environment issue is only fixed for multiple Sexpr's in the same Rd section. However, an Sexpr may depend on Sexpr's further above in the original Rd file, and the order in which `data_reference_topic()` causes the Sexpr's to be evaluated does not necessarily coincide with the order in the Rd file... I have no idea how to fix that. :confused:
