### ISSUE TITLE
Error building README: unused argument Updating README.md

### ISSUE THREAD

**Issue by mooresm** [r-lib/pkgdown#503]
This is with pkgdown version 0.1.0.9000 and my R package [serrsBayes](https://github.com/mooresm/serrsBayes). When I run `build_home` or `build_site`, I get the following error:

`Building home ------------------------------------------------------------`
`Updating README.md`
`Error in (function (variant = "markdown_strict", preserve_yaml = FALSE,  : `
`  unused argument (html_preview = FALSE)`

**Comment by mooresm** [comment]
`> traceback()`
`4: stop(err[[2]])`
`3: get_result(output = out, options)`
`2: callr::r_safe(function(input, encoding) {`
`       rmarkdown::render(input, output_options = list(html_preview = FALSE), `
`           quiet = TRUE, encoding = encoding, envir = globalenv())`
`   }, args = list(input = data$path, encoding = encoding))`
`1: build_home()`

**Comment by hadley** [comment]
You need to replace the yaml metadata in `README.Rmd` with

```yaml
---
output: github_document
---
```
