### ISSUE TITLE
named Authors@R do not render correctly in content-citation-authors template

### ISSUE THREAD

**Issue by WastlM** [r-lib/pkgdown#513]
If the Authors@R field is named (I know this is rare, but I did...), e.g.,

```
Authors@R: c(
    HW = person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre"))
    )
```

then authors won't be rendered on the authors page.
To see what you get, run:

```r
cat(render_template(find_template("content", "citation-authors"),
  data = list(authors = list(HW = list(name="Hadley Wickham", roles="Author")))))
```
```
<div class="row">
  <div class="contents col-md-9">

    <div class="page-header">
      <h1>Citation</h1>
    </div>

    <div class="page-header">
      <h1>Authors</h1>
    </div>

    <ul class="list-unstyled">
      <li>
        <p><strong></strong>. .
        </p>
      </li>
    </ul>

  </div>

</div>
```

as opposed to

```r
cat(render_template(find_template("content", "citation-authors"),
  data = list(authors = list(list(name="Hadley Wickham", roles="Author")))))
```

```
<div class="row">
  <div class="contents col-md-9">

    <div class="page-header">
      <h1>Citation</h1>
    </div>

    <div class="page-header">
      <h1>Authors</h1>
    </div>

    <ul class="list-unstyled">
      <li>
        <p><strong>Hadley Wickham</strong>. Author.
        </p>
      </li>
    </ul>

  </div>

</div>
```

The reason for this effect of the names can be found in **whiskers** (https://github.com/edwindj/whisker/blob/7d3dcc49527ad5a58f6f55e897f9e161aed9a0c8/R/section.R#L21), where a function performs differently if the value has names (I have no idea why).

To fix this, the authors list in `build_citation_authors()` needs to be `unname()`d either at
https://github.com/r-lib/pkgdown/blob/05db627e5ebb9fde47b49b71f59e70acf41849c5/R/build-home-citation.R#L43

or already at a lower level in `pkg_authors()` at
https://github.com/r-lib/pkgdown/blob/05db627e5ebb9fde47b49b71f59e70acf41849c5/R/build-home-authors.R#L23

PR?

**Comment by hadley** [comment]
PR would be great please!
