### ISSUE TITLE
build_home and build_news encoding issue

### ISSUE THREAD

**Issue by cderv** [r-lib/pkgdown#514]
This is following #339 
cc @antuki

There is an issue with encoding with `build_news` and `build_home` that do not render properly when building site on a french locale. Test 📦 is [COGuguaison](https://github.com/antuki/COGugaison) - a french one. 

`build_news` and `build_home` both parsed `.md`  file using an internal `markdown` function. It uses pandoc to convert markdown to html then makes changes in html using `xml2`, writes back the temp html file and then reads it line by line with `readLines` with no encoding provided.
The issue is here. 
https://github.com/r-lib/pkgdown/blob/05db627e5ebb9fde47b49b71f59e70acf41849c5/R/util.r#L58-L62

As `xml2::write_html` enforces UTF-8, readLines should assume UTF-8 input, but its default param is `encoding = "unknown") that assume the encoding based on `Sys.getlocale()`. On a french computer, it is not UTF-8 and the UTF8 html file is read misproperly.

Everything is working fine if I change to 
```r
lines <- readLines(tmp, warn = FALSE, encoding = "UTF-8")
```
or maybe more cleanly
```r
con <- file(tmp, encoding = "UTF-8")
lines <- readLines(con, warn = FALSE)
close(con)
```

I made the change in my fork. @antuki, you can try install to test on your system. 
```r
install_github("cderv/pkgdown@encoding-in-markdown")
``` 

Then I will make a PR if asked and if everything is fine after some checks. 

Question I still have: 

+ in COGuaison 📦 , all input file are saved as UTF8 which ease the process a lot. All the issue are because on system locale. I don't know how all this behave if file were not UTF-8 but latin-1
+ I can just test on french system but I assume it will work on others.

**Comment by antuki** [comment]
Thanks again @cderv for your help.
I tried and it seems that the encoding is working properly with your branch (cderv/pkgdown@encoding-in-markdown) (you're a hero !!) for every page built with build_site that I have in my pkgdown website. 
The only thing i've noticed is that it now opens a window called "R Graphics : Device 4 (ACTIVE)" when building every reference page and I don't think it was happening the same with pkgdown.

**Comment by cderv** [comment]
> The only thing i've noticed is that it now opens a window called "R Graphics : Device 4 (ACTIVE)" 

I do not have that on my side. 

Do you have that with pkgdown master ?

**Comment by antuki** [comment]
No. But I tried again with both branch (yours and pkgdown master) and the window did not open so I don't know what it was. It does't seem to be a real problem. so let's forget about it for the moment maybe !
