### ISSUE TITLE
Support dev version of highlight

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/pkgdown#521]
I've made some changes to [highlight](https://github.com/romainfrancois/highlight) a few months ago, and did not realize `pkgdown` was using it. It looks like `pkgdown` uses the old interface. 

I'll track this down.

**Comment by romainfrancois** [comment]
Not at the moment, in the PR, I have added `highlight` in the remotes. `highlight` is otherwise orphaned on CRAN. 

I'm not entirely sure yet about `highlight` syntax, although it is much simpler than it used to be (which is good). 

Are you planning a release of `pkgdown` soon ? I could try to release highlight if that's the case

**Comment by hadley** [comment]
No release imminent, just wondering why I wasn't seeing this problem.

**Comment by jayhesselberth** [comment]
@hadley should we address this before the 1.2.0 release?

**Comment by hadley** [comment]
@jayhesselberth I don't think it's needed yet.

**Comment by MichaelChirico** [comment]
Seems might be closeable by now?

**Comment by hadley** [comment]
Yeah, this can be closed now that we've un-orphaned highlight and are likely to switch to some alternative system in the future (#1234)
