### ISSUE TITLE
Structure References by S4 documentation

### ISSUE THREAD

**Issue by zappingseb** [r-lib/pkgdown#522]
In our deparment we write nearly all the code in S4 style. In object oriented programming it's important to identify your methods and classes.

Therefore I would like to have the reference / function documentation like this:

**MyClass Class**
This are the methods of the **MyClass2** class

- MyClass-class
- initialize (MyClass-method)
- .... (MyClass-method)

**MyClass2 Class**
This are the methods of the **MyClass2** class

- MyClass2-class
- initialize (MyClass2-method)
.....

** Topic **

.....

** Functions **

All non classified functions
This could be easily implemented in the `build-reference-index` function

**Comment by hadley** [comment]
This organisation seems a little odd to me because S4 methods don't belong to classes, but belong to generic functions.

**Comment by zappingseb** [comment]
But even if they are generic, you can change them for each class. So you would get the same function name multiple times in here. As you see, initialize is already mentioned twice. It does totally different things for each of the classes.

**Comment by hadley** [comment]
It's generally recommended to not create an `initialize()` method, so I don't think that's a good counter example.

**Comment by zappingseb** [comment]
```
setMethod("sides", signature("Triangle"), function(object) 3)
setMethod("sides", signature("Square"),   function(object) 4)
setMethod("sides", signature("Circle"),   function(object) Inf)
```

This is taken from your tutorial at http://adv-r.had.co.nz/S4.html

How would you document it?

**Comment by hadley** [comment]
For a simple method like that, I'd document them all in the same file. For now, I think you'll have to create the sections that you want by hand, using the existing features of `pkgdown.yaml`.
