### ISSUE TITLE
Handle `out` tags

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgdown#525]
For verbatim HTML:

```r
rd_text("\\out{verbatim}", fragment = TRUE)
```

Meant to be used conditionally, if that matters:

```r
rd_text("\\if{html}{\\out{verbatim}}", fragment = TRUE)
```

**Comment by hadley** [comment]
You'd expect this, right?

```
expect_equal(rd2html("\\out{<hr />}"), "<hr />")
```

So I also need to suppress escaping inside `\out`

**Comment by lionel-** [comment]
> You'd expect this, right?

Yes we'd use this to insert arbitrary HTML.

**Comment by lionel-** [comment]
Thanks!
