### ISSUE TITLE
Figures should be wrapped in <p>

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgdown#527]
To avoid the text following the figure to be layed out on the same line. AFAICT wrapping the figure in `<p>` would be consistent with how R generates html for doc pages.

My attempt in #526 doesn't work because it creates nested `<p>` blocks.

**Comment by hadley** [comment]
Can you show me an example of the problem?

**Comment by lionel-** [comment]
See http://rlang.tidyverse.org/reference/lifecycle.html

The stable, experimental and questioning badges were created with `\out{}` (so I can link to the lifecycle page) and are correctly layed out. On the other hand the soft-deprecated, deprecated and defunct badges were created with `\figure{}` and have text layed out on their RHS rather than in a new paragraph.

You can look at the HTML generated by R with `?rlang::lifecycle` with the latest dev version installed.

**Comment by hadley** [comment]
Can you please also link to the roxygen2 and Rd sources?

**Comment by lionel-** [comment]
roxy: https://github.com/r-lib/rlang/blob/9ea33dd3922c83304ab4a97b2fbc42a93113bd06/R/lifecycle.R#L163

Rd: https://github.com/r-lib/rlang/blob/9ea33dd3922c83304ab4a97b2fbc42a93113bd06/man/lifecycle.Rd#L157

**Comment by hadley** [comment]
Possible the same as #537
