### ISSUE TITLE
Render website in language other than English

### ISSUE THREAD

**Issue by samuel-rosa** [r-lib/pkgdown#528]
I am preparing a website for a package that need to be in Portuguese. Can default headers be automatically translated to Portuguese (or any other language)? If not, then is there a recommended way of proceeding?

**Comment by hadley** [comment]
Not at this time - there's a lot of work to be done on pkgdown before I could even consider translation, so I'm going to close this issue for now.

**Comment by samuel-rosa** [comment]
I perfectly understand. Perhaps I could use my own templates to render the pages. But I confess that it is not clear to me how to do that (or if pkgdown supports it).

**Comment by hadley** [comment]
Even providing your own templates won't help unfortunately.  I'm doing some major refactoring at the moment, so unfortunately I don't even have the brain space to figure out how much work it would be.
