### ISSUE TITLE
Major changes in pkgdown 

### ISSUE THREAD

**Issue by kimyen** [r-lib/pkgdown#533]
Hello, 

This is more of a question than an issue. 
I have been using "hadley/pkgdown" (now "r-lib/pkgdown") in my build system. The build that explicitly use pkgdown ran on a Mac machine. Recent changes broke the build because `fs` (pkgdown's dependencies) is not available for Mac.

There is 2 problems I'm trying to solve:
1. I want to subscribe to major changes (like dependency on fs), so that I can adjust my build system as needed.
2. Installing a previous stable version.

One practice I have been using to avoid making breaking changes is using the Github branches as follow:
- master branch - latest release (stable)
- develop branch - latest development work (unstable)
- release candidate branches - to test to-be-released code without impact our users. 

With this setup, our users can use devtools::install_github(\<our package\>) for the latest release and devtools::install_github(\<our package\>@develop) for latest development work.

The previous version ("hadley/pkgdown") without 'fs' dependency works for me. How do I install that version?

**Comment by jranke** [comment]
Of course `fs` should be available for Macs as it claims to be cross-platform. There is an issue where this is discussed: r-lib/fs#58.

Did you try to install the fs package from github using` devtools::install_github("r-lib/fs")? If you succeed this should solve your problem. If not the authors of the fs package would probably be interested in details as they obviously could not reproduce the segfault on the build system so far.

Regarding previous versions, you can easily see when the dependency on fs was introduced using githubs "blame" page:

https://github.com/r-lib/pkgdown/blame/master/DESCRIPTION

If you do not get fs installed, you could use the "ref" argument of `install_github' to install the parent of that commit, but missing out on the latest improvements

```
devtools::install_github("r-lib/pkgdown", ref = "d02fe9e")
```

**Comment by hadley** [comment]
I'd recommend installing from a specific sha. Unfortunately things are probably going to get (slightly) worse before they get better, as I start tackling bigger refactorings in order to make pkgdown easier to develop. There are currently few tests so that likely to lead to some more breakage in the short term.

**Comment by kimyen** [comment]
Thank you @jranke & @hadley! I am currently using a specific sha. I would love to be able to point to a branch in the future instead. So that when the branch is updated, I can get the latest stable version without making changes to my code.

**Comment by hadley** [comment]
Unfortunately there won't be a stable release until pkgdown goes to CRAN. I'm going to keep chipping award towards that goal over the next few weeks (or maybe months depending on other commitments)
