### ISSUE TITLE
Paragraphs are joined when next starts with a macro

### ISSUE THREAD

**Issue by rickhelmus** [r-lib/pkgdown#537]
Hello,

I'm starting quite a few paragraphs with a `\code` macro, however, it seems that `pkgdown` joins these (ie removes any newlines) when generating the reference pages.

Minimal example:
```R
#' Howdy
#'
#' Hello is what it prints
#'
#' @details Some details...
#'
#' @details Even more...
#'
#' @details \code{arg!} not a separated line :(
#' @export
hello <- function() {
  print("Hello, world!")
}
```
EDIT

In the above case the details section will only contain two paragraphs.

Note: I am using multiple `@details`  headers scattered around the source and join them to single files with `@rdname`.

**Comment by hadley** [comment]
Can you provide the generated `\details{}` section from the `.Rd` please?

**Comment by rickhelmus** [comment]
Of course!

```
\details{
Some details...

Even more...

\code{arg!} not a separated line :(
}
```

Interesingly enough, if I add a space (or any other character) in front of the `\code` macro the paragraphs are split properly.

**Comment by hadley** [comment]
This will need some fix to the logic in `flatten_para()`

**Comment by rickhelmus** [comment]
Great, thanks!
