### ISSUE TITLE
package_rd() does not ignore non-Rd files

### ISSUE THREAD

**Issue by WastlM** [r-lib/pkgdown#538]
The **fs** function `dir_ls()` is used to filter `.Rd` files as follows:
https://github.com/r-lib/pkgdown/blob/408dc8985028b7a95fb249ad44fad53eed198f58/R/package.r#L121

However, `fs::dir_ls()` ignores the `pattern` argument; the associated argument is named `regexp`. I stumbled upon this issue when I had an old `svn-commit.tmp~` inside `man/` which caused `as_pkgdown()` to fail with an "Error: Result 176 is not a length 1 atomic vector".

Note that `fs::dir_ls()` is used with an invalid `pattern` argument in two other **pkgdown** functions as well: `data_extras()` and `article_index_local()`.

BTW, I think `package_rd()` should employ a `[rR]d` pattern to also catch `.rd` files (this was not an issue previously since the `pattern` argument has been ignored).

**Comment by hadley** [comment]
Oops!
