### ISSUE TITLE
ERROR: dependency 'pkgload' is not available for package 'pkgdown'

### ISSUE THREAD

**Issue by statsandthings** [r-lib/pkgdown#548]
### System details

    OS Version      : Windows 7 64 Bit
    R Version       : 3.4.3

### Steps to reproduce the problem
`devtools::install_github("hadley/pkgdown")` I do this in R from the terminal, not using R Studio. I do not have any packages loaded when issuing the command. All my packages are updated via the `update_packages()` command, I also reinstalled tidyverse. Then re-opened fresh R session to try again. Same errors shown below.

### Describe the problem in detail
ERROR: dependency 'pkgbuild' is not available for package 'pkgload'
ERROR: dependency 'pkgload' is not available for package 'pkgdown'

### Describe the behavior you expected
I saw the other bug stating newer versions of devtools would eliminate this issue, but I just reinstalled devtools and the bug still happens.

**Comment by hadley** [comment]
If for some reason the automated install failed, you'll need to install those packages by hand.

**Comment by statsandthings** [comment]
`devtools::install_github("hadley/pkgload")` and then `devtools::install_github("hadley/pkgdown")` worked. Thank you.
