### ISSUE TITLE
left-justify articles/vignettes

### ISSUE THREAD

**Issue by zkamvar** [r-lib/pkgdown#552]
I've noticed that the articles justify everything as center.

case-in-point: https://grunwaldlab.github.io/poppr/articles/poppr_manual.html#citation

Is there a way to fix this so that it appears more like it does on CRAN?

**Comment by batpigandme** [comment]
That is very strange. What version of pkgdown did you use?
The screenshot below is from a site rendering I did < 15 mins ago with 7cbafcd. (I'd link it, but still in Travis build).
![image](https://user-images.githubusercontent.com/831732/37546734-a5537ada-2944-11e8-8b0d-74407e17b9a6.png)

**Comment by zkamvar** [comment]
I also have https://github.com/r-lib/pkgdown/commit/7cbafcd6b97e5108ccde816a00d300152534a192.

Here's how the page renders. The images don't show up (I think) due to #553 

https://htmlpreview.github.io/?https://github.com/grunwaldlab/poppr/blob/5697ce13af6a0931c82cbc739e4d8c6135fd1844/docs/articles/mlg.html

I thought it might be a css file, but there's only one css file I have that defines one class:

https://github.com/grunwaldlab/poppr/blob/5697ce13af6a0931c82cbc739e4d8c6135fd1844/docs/articles/poppr.css

I've been stumped by this for a while now. Happily, though, everything else is working 😃

**Comment by batpigandme** [comment]
Yeah, I saw #553 as well. Very strange— looking into it.

**Comment by hadley** [comment]
@zkamvar can you please provide a link to the vignette source?

**Comment by zkamvar** [comment]
https://github.com/grunwaldlab/poppr/blob/master/vignettes/poppr_manual.Rmd

**Comment by zkamvar** [comment]
Oh snap! This is the one linked to this issue: https://github.com/grunwaldlab/poppr/blob/master/vignettes/mlg.Rmd the other one is an example of #553

**Comment by batpigandme** [comment]
Yeah, so if you look at any of the articles in the dplyr site (e.g. http://dplyr.tidyverse.org/articles/window-functions.html), you can see that they're not centered. When I look at the htmlpreview rendering, it says that the `text-align` is coming from `user-agent-stylesheet`, which is why I was asking about the local rendering in #553. 
![image](https://user-images.githubusercontent.com/831732/37554339-65e244d0-29ad-11e8-9907-d954c22d33c5.png)

**Comment by hadley** [comment]
For some reason the closing centre tag that you have inserted is being lost

**Comment by zkamvar** [comment]
I think the issue may be the presence of the center tag before the level 1 section header. If I move the tag below the abstract text (https://github.com/grunwaldlab/poppr/commit/bd156375ebace83b4408a5767a1f283d45652386), the problem is fixed.

Since this was a PBKC error, I'd be okay with this issue being closed if it's okay with y'all.

Thank you for your patience on this!

**Comment by hadley** [comment]
Yeah, I'd say this is a slightly unfortunate intersection of your html, and pandoc's transformation. I'd say your use of center is technically correct, but pandoc wraps each section into a div.
