### ISSUE TITLE
Vignettes use absolute paths

### ISSUE THREAD

**Issue by zkamvar** [r-lib/pkgdown#553]
After updating, I notice that the vignettes/articles are using absolute paths to images instead of relative paths. 

case in point: https://github.com/grunwaldlab/poppr/commit/5697ce13af6a0931c82cbc739e4d8c6135fd1844#diff-f627caa64acaddf31682a506ff09110dR353

**Comment by batpigandme** [comment]
Hmm, there's something inconsistent happening, it seems, because the logo in your article below is definitely relative.
https://grunwaldlab.github.io/poppr/articles/mlg.html

**Comment by zkamvar** [comment]
Ignore the one hosted at grunwaldlab.github.io. That was built with the previous iteration of pkgdown.

This is the one you want:

https://htmlpreview.github.io/?https://github.com/grunwaldlab/poppr/blob/5697ce13af6a0931c82cbc739e4d8c6135fd1844/docs/articles/mlg.html

**Comment by batpigandme** [comment]
Does the view appear the same for you locally (i.e. without htmlpreview)?

**Comment by zkamvar** [comment]
Locally, I will get the correct images showing up, but I suspect if I change computers, this will not be true.

**Comment by hadley** [comment]
I changed how vignettes are built and didn’t have an example of embedding a plot. Oops!

I’ll reconsider my approach again. Might be able to fix by setting working directory instead of using output dir, or could try building in vignette dir with temp name and then copying to articles.

**Comment by hadley** [comment]
Setting the working directory doesn't seem to help. Now trying the copying approach.

**Comment by hadley** [comment]
Actually, I can't reproduce the problem. I added a new test vignette containing a figure, but I always get a relative path. How are you building the site?

**Comment by hadley** [comment]
And can you please provide a pointer to the source of the vignette?

**Comment by jayhesselberth** [comment]
I still see abs paths in README and vignettes, see #554 

I get the same result calling `pkgdown::build_site()` or using RStudio menu item.

**Comment by hadley** [comment]
Oh the problem is images, not figures.

**Comment by hadley** [comment]
Hmmm setting `output_dir` to anything (even `.`) appears to trigger absolute urls in the output.

**Comment by hadley** [comment]
And we can't set `output_file` because that affects the path used for R figures.

I think that implies that we have to build in the directory in which the article lives. We can't even copy that directory because we also have to copy all children, and in the case of `README.Rmd` that's the whole package. 

To figure out which files we need to copy, maybe we can `dir_ls()` before and after, and then move all new files?

**Comment by hadley** [comment]
Hmmm, that strategy will fail if you're previewing locally.

Another idea: copy `.Rmd` to output directory, build in that directory, then delete the `.Rmd`. Would also need to copy files found by `rmarkdown::find_external_resources()`, and document that if a neede file doesn't get imported, you'll need to add it to `resource_files` in the yaml header.

**Comment by hadley** [comment]
Alternatively, since the problem is only images, maybe it's easier to simply add another layer of html tweaking?

**Comment by hadley** [comment]
Ok, I've resolved the absolute path problem but it reveals a new problem - images in the vignettes directory are not currently copied to the documentation website. Should they be? R does not (unless you list in `.install_extras`). But this behaviour was probably designed in the era of pdf vignettes where there was no need to copy inputs. It seems like it would be more convenient if pkgdown copied these files; but precisely what should it copy?

Maybe a reasonable heuristic is to copy any "image" files found by `rmarkdown::find_external_resources()`? That should get the files you need, without copying over potentially large files that are needed to generate the article, but not to view it.
