### ISSUE TITLE
abs paths for README h1 images

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#554]
I'm including a logo in [README.Rmd](https://raw.githubusercontent.com/rnabioco/valr/master/README.Rmd) in an h1:

```
# valr <img src="man/figures/logo.png" align="right" />
```

This is now ending up as an abs path in the built index.html:

```html
<div class="contents">
<div id="valr" class="section level1">
<div class="page-header"><h1 class="hasAnchor">
<a href="#valr" class="anchor"></a>valr <img src="/Users/jayhesselberth/devel/valr/man/figures/logo.png" align="right">
</h1></div>
```

**Comment by batpigandme** [comment]
Related to https://github.com/r-lib/pkgdown/issues/553?

**Comment by hadley** [comment]
Yeah it’s a dup. I’ll take a look next week.
