### ISSUE TITLE
rticles vignettes issues

### ISSUE THREAD

**Issue by Enchufa2** [r-lib/pkgdown#555]
I'm trying to build [this vignette](https://github.com/r-simmer/simmer/blob/master/vignettes/simmer-02-jss.Rmd), which is a JSS paper. The first problem (after adding `as_is` and `pdf` options in the YAML header as documented in `build_articles`) comes from the fact that the `rticles` template for the JSS has two titles, plain and formatted:

```
title:
  formatted: "\\pkg{simmer}: Discrete-Event Simulation for \\proglang{R}"
  plain:     "simmer: Discrete-Event Simulation for R"
```

The error is `Error: Result 2 is not a length 1 atomic vector`, because `pkgdown` finds two titles. Then if I remove one of them, the compilation starts, but finally fails with another error:

```
Error: Failed to build the bibliography via bibtex
```

**Comment by batpigandme** [comment]
Was this working with the previous version of pkgdown?

**Comment by Enchufa2** [comment]
No, it wasn't. But AFAIK, PDF compilation in general wasn't implemented either until this version.

**Comment by hadley** [comment]
@Enchufa2 the most helpful thing you could do would be to make the smallest possible package that illustrates this problem.

**Comment by Enchufa2** [comment]
I found the problem. If `jss.bst` is present in the vignettes subdir, compilation succeeds. But this file is not required by R or CRAN (it's already part of R) to build vignettes.

**Comment by Enchufa2** [comment]
Reprex:

```r
# create a package skeleton
package.skeleton()
setwd("anRpackage")
desc::desc_add_author("Given", "Family")

# minimal jss rticle, including one reference
rmarkdown::draft("vignettes.Rmd", template="jss_article", package="rticles", edit=FALSE)
rmd <- readLines("vignettes/vignettes.Rmd")
rmd <- c(rmd[1], 
         "bibliography: jss.bib",
         "pkgdown:", 
         "  as_is: true", 
         "  extension: pdf", 
         rmd[-1],
         "[@onecite]")
write(rmd, file="vignettes/vignettes.Rmd")
write("@Article{onecite, title={Whatever}, author={Whoever}}", file="vignettes/jss.bib")

# without this file, compilation fails
file.remove("vignettes/jss.bst")
pkgdown::build_site()
```

**Comment by hadley** [comment]
If you can figure out where that file lives, and what arguments are needed to pass it down to rmarkdown, I'd be happy to incorporate. Otherwise I don't have the resources to support the idiosyncrasies of every existing rmarkdown template.

**Comment by Enchufa2** [comment]
Ok, let me investigate.

**Comment by Enchufa2** [comment]
Do you want me to arrange a PR?

**Comment by hadley** [comment]
Yeah, that'd be great.
