### ISSUE TITLE
extra.css still not applied

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#561]
First, `/pkgdown/extra.css` is not picked up in 

https://github.com/r-lib/pkgdown/blob/7cbafcd6b97e5108ccde816a00d300152534a192/R/build.r#L245

Then, if this is fixed (e.g. removing the `^`), the next error is thrown in 

https://github.com/r-lib/pkgdown/blob/7cbafcd6b97e5108ccde816a00d300152534a192/R/build.r#L206

`Error: The specified pathname is not a file: /home/pjs/git/mlr/docs`

by

https://github.com/r-lib/pkgdown/blob/7cbafcd6b97e5108ccde816a00d300152534a192/R/utils-fs.R#L37

Idk how you want to handle it so I did not provide a PR.

**Comment by hadley** [comment]
I couldn't replicate the second problem, possibly because I did a more sophisticated fix to the first problem. But there's a unit test now, so if you can replicate the problem after this commit, please tweak the test as needed.

**Comment by pat-s** [comment]
Test is working but it does not catch the problem when calling `buid_site()` from the package root.
Here's why:

In the test, the objects `from_rel` and `to_paths` contain:

```
from_rel
extra.css extra.js

to_paths
/home/pjs/git/pkgdown/tests/testthat/init-extra/docs/extra.css
/home/pjs/git/pkgdown/tests/testthat/init-extra/docs/extra.js
```

whereas when calling it from the package root, they contain:

```
from_rel
.

to_paths
/home/pjs/git/pkgdown/docs
```

This then throws the error `Error: The specified pathname is not a file` because `to_paths` is not a file but a dir.

`from_rel` is actually `.` because `from_dir` and `from_paths` contain both `/home/pjs/git/pkgdown/pkgdown/extra.css` (in the real world example) whereas in the test it looks like:

```
from_dir
/home/pjs/git/pkgdown/tests/testthat/init-extra/pkgdown

from_paths
/home/pjs/git/pkgdown/tests/testthat/init-extra/pkgdown/extra.css
/home/pjs/git/pkgdown/tests/testthat/init-extra/pkgdown/extra.js
```

So the question is why `from_dir` contains a file path instead of a dir path. 
`from_ dir` itself is defined as an argument in `file_copy_to()` with `path_common(from_paths)`.

Subsequently, this call is not correct. It should be a directory rather than a file. 

It works in the tests because `from_paths` is 2L and then `path_common` correctly extracts the dir and not just `.`. So a simple fix would be to require object `all` in 

https://github.com/r-lib/pkgdown/blob/9fcc3acd70db8ea9ccb2d55efe7cd573eecbbb4b/R/init.R#L66

to always be 2L because it is later passed onto `path_common`.

The test works because it tests with `extra.css` and `extra.js` while in reality only one might exist. 

The problem fixing this is that when manually tweaking `all` to be 2L in `data_extras()`:

* The filename must be different for every entry
* If we fake-add a file so that `path_common` works (e.g. adding a non-existent `extra.js`), `file_copy_to()` will error later because `extra.js` does not exist. 

(Sorry for the long report... :sweat_smile: ).
