### ISSUE TITLE
build_site_rstudio() does not preview site

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#564]
`pkgdown:::build_site_rstudio()` does not open the newly built site for me, when called directly or via the add-in. Seems like the indirection of [`callr::r()`](https://github.com/r-lib/pkgdown/blob/7cbafcd6b97e5108ccde816a00d300152534a192/R/build.r#L193) interferes with preview in current RStudio instance?

I get the message re: "Previewing site" but no preview is launched.

**Comment by hadley** [comment]
Oh it’s just that the default is `preview = interactive()`. The RStudio wrapper should override that.

**Comment by hadley** [comment]
Nope, it definitely passes `preview = TRUE` on. Hmmmmmm

**Comment by hadley** [comment]
Ok, I bet `browseURL()` does something less than useful in a non-interactive session
