### ISSUE TITLE
Error in usage_code.tag(.x[[i]], ...) : Undefined tag tag_dotstagFALSE

### ISSUE THREAD

**Issue by luca-scr** [r-lib/pkgdown#565]
I just updated pkgdown from GitHub and submit `pkgdown::build_site()` to my GA package as I did few weeks ago. Before it worked with no problems, but after upgrading I got the following error:

`Error in usage_code.tag(.x[[i]], ...) : Undefined tag tag_dotstagFALSE`

The package build with no issue and also checking is fine. I would like to provide more info for testing but I really don't know what to look for.

If I tried to install a previous version of pkgdown, for example using `devtools::install_github("r-lib/pkgdown@491a8fa")` then no issues appear as you can see at http://luca-scr.github.io/GA/index.html

Any help would be appreciated.

Luca

**Comment by batpigandme** [comment]
Is 491a8fa the exact commit at which things start working again for you?

**Comment by hadley** [comment]
I know what the problem is
