### ISSUE TITLE
Source links generated incorrectly

### ISSUE THREAD

**Issue by zkamvar** [r-lib/pkgdown#567]
Hello again,

I really like the github links on the pages, but as of 9fcc3acd70db8ea9ccb2d55efe7cd573eecbbb4b they are parsing incorrectly on my site. 

For example, the page https://grunwaldlab.github.io/poppr/reference/read.genalex.html should link to 
https://github.com/grunwaldlab/poppr/blob/master/R/file_handling.r, but instead lops off a slash from the protocol and ends up being interpreted as a relative path by github:

```html
<small>Source: <a href='https:/github.com/grunwaldlab/poppr/blob/master/R/file_handling.r'><code>R/file_handling.r</code></a></small>
```

Here's the source Rd file: https://github.com/grunwaldlab/poppr/blob/master/man/read.genalex.Rd
And the output html file: https://github.com/grunwaldlab/poppr/blob/master/docs/reference/read.genalex.html

I build my site by opening R and using:

```r
pkgdown::build_site()
```

Thank you for looking at all these silly corner cases.

**Comment by hadley** [comment]
Thanks!  I didn't notice this because safari seems to automatically fix links starting with `http:/`
