### ISSUE TITLE
ORCID buttons way too large

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#568]
see e.g. http://dplyr.tidyverse.org:

![screenshot from 2018-03-19 01-14-29](https://user-images.githubusercontent.com/1741643/37572957-e8b0ca88-2b12-11e8-984c-fe23b68d8bb4.png)

**Comment by jranke** [comment]
I had the same issue when I recently did a rebuild with a new version of pkgdown. Wiping docs/ and rebuilding from scratch fixed it.

**Comment by jayhesselberth** [comment]
https://github.com/tidyverse/tidytemplate/pull/8

**Comment by batpigandme** [comment]
@jayhesselberth even with the update to tidytemplate, it's still not rendering correctly
