### ISSUE TITLE
images are not moved if knitr fig.path is set

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#571]
I was setting `fig.path` in my vignettes to keep things tidy, e.g.:

```r
knitr::opts_chunk$set(fig.path = "img/overview-")
```
 Vignettes with that chunk have broken links to images because the images are built under `vignettes` and not under `docs/articles`. Either that or they aren't copied to `docs/articles`.

If I remove `fig.path`, then images show up under `docs/articles` and are linked correctly in the vignette.

Not sure how many people do this but is it easy to make the render respect `fig.path`?

**Comment by hadley** [comment]
Maybe pkgdown could just set `fig.path` for you?

**Comment by hadley** [comment]
Or is this a bug in `rmarkdown::render()`? I'd expect that setting `output_dir` should affect `fig.path`

**Comment by hadley** [comment]
I discussed this with @jjallaire, and defaulting `fig.path` is a strongly held assumption by rmarkdown. That means that changing the `fig.path` unfortunately can not be supported by pkgdown. I'll add some documentation to this effect.

**Comment by hadley** [comment]
`README.Rmd` will need special handling, however.
