### ISSUE TITLE
Switch Error to Warning for linking in NEWS?

### ISSUE THREAD

**Issue by batpigandme** [r-lib/pkgdown#572]
In an earlier build (Friday) of pkgdown, the NEWS.md for dplyr rendered fine, with the mention of `dplyr::select_helpers`, which no longer exists (see [here](http://dplyr.tidyverse.org/news/index.html)). Now `pkgdown::build_site()` errors out with:
```r
Error: 'select_helpers' is not an exported object from 'namespace:dplyr' 
```
(see also: https://github.com/tidyverse/dplyr/issues/3444). At least for NEWS, I think it makes sense to be able to mention a function that no longer exists, though I see how it could be a helpful warning to have!

**Comment by hadley** [comment]
Hmmm, that's definitely how it's supposed to behave. Let me add a test to make sure it stays fixed

**Comment by hadley** [comment]
I don't see why this wouldn't have failed before, unless NEWS wasn't get auto-linked at all. Regardless, it's now fixed.
