### ISSUE TITLE
Switch to bootstrap 4

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#577]
Main adjustment is to grid system (https://getbootstrap.com/docs/4.0/migration/#grid-system)

Will need minor tweaks elsewhere, and will need to reconsider custom css

**Comment by hadley** [comment]
I tried valiantly but there's too much css weirdness going on - the sticky header + navbar broke, and the mechanism I used to size the reference index table no longer works. Converting doesn't seem worth it.

**Comment by jayhesselberth** [comment]
I have toying around with this and have a functional build that needs more tweaking.

But you can take a peek at current progress: https://lucid-newton-271b44.netlify.com

I switched the reference index to a card layout. Layouts of card internals need tweaking but you get the idea.

All the TOC navs are currently broken. And the sticky stuff doesn't work at all.

**Comment by hadley** [comment]
That's rather nice! (And the navbar isn't aligned correctly)

**Comment by hadley** [comment]
I think getting sticky to work was what killed me
