### ISSUE TITLE
Feature request: Set header depth of articles

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#578]
Is currently fixed to `depth = 1`:

https://github.com/r-lib/pkgdown/blob/37e2fb60f78824c3367b70f3689ae95aa5ea4c86/R/build-articles.R#L105

Would be good if one could set it in `build_articles()` and `build_site()`
In `mlr` we start at `depth = 2` so currently we would have no headers at all.

Sorry for all the interruptions :smile_cat:

**Comment by hadley** [comment]
Controlling the location of top-level directories is not something that I want to allow right now. I think these should be considered fixed by the design of pkgdown.

**Comment by pat-s** [comment]
> the location of top-level directories

Sorry for asking again - but I have the feeling that you misunderstood me eventually. I was not referring to  top-level directories (idk what you mean by this in that context here) but just to the depth of the headers displayed in the sidebar of each article (see [example](https://pat-s.github.io/mlr/articles/tutorial/devel/nested_resampling.html)). 

The `depth = 1` prevents lower headers levels to be displayed there without any control for the user. We now have a completely empty sidebar for all articles as our headers are all `h2`. 

If your previous answer addressed exactly that, I am again sorry for not understanding your reply.

**Comment by hadley** [comment]
The `depth` argument controls how many levels up the generated links for the section need to go in order to get to the root. It's unrelated to the sidebar.
