### ISSUE TITLE
No active ORCID link with default pkgdown options

### ISSUE THREAD

**Issue by choisy** [r-lib/pkgdown#579]
With the default pkgdown options (https://choisy.github.io/gamar) the ORCID links are not active. Anyway to make them active?

**Comment by hadley** [comment]
You need to supply the ORCID id, not the url: `comment = c(ORCID = "0000-0003-4757-117X")`

**Comment by katrinleinweber** [comment]
Moved to https://github.com/r-lib/pkgdown/issues/583
