### ISSUE TITLE
No active ORCID link

### ISSUE THREAD

**Issue by choisy** [r-lib/pkgdown#583]
The ORCID links are still not active on the website https://choisy.github.io/gamar, despite having specified the ORCID ID correctly in the DESCRIPTION file: comment = c(ORCID = "0000-0002-5187-6390").

**Comment by batpigandme** [comment]
Can you please try with the `Authors@R`section using one line per author/contributor as in DESCRIPTION [here](https://github.com/tidyverse/dplyr/blob/6dd1976482cefe75d8836ed9474ea44aed5e68cb/DESCRIPTION#L5-L11)?

**Comment by hadley** [comment]
One per line shouldn't make any difference.

**Comment by hadley** [comment]
I suspect it's because @choisy is using an older version of pkgdown. Recent versions automatically write version info to https://github.com/r-lib/pkgdown/blob/master/docs/pkgdown.yml and I don't see that file in https://github.com/choisy/gamar/tree/master/docs

**Comment by batpigandme** [comment]
Duly noted and retracted.

**Comment by katrinleinweber** [comment]
I had the same issue, but it resulted from not using `c()`, see https://github.com/TIBHannover/BacDiveR/commit/5cba78d417f7cd95b24f16fd2852a8a0d60dfa0d.
