### ISSUE TITLE
Coupling websites from pkgdown with Hugo themes

### ISSUE THREAD

**Issue by wenlong-liu** [r-lib/pkgdown#590]
Thanks for reading my post.  

I have a personal website hosted in Github pages, using Blogdown with Hugo Themes.  I do not have too much background in developing webpages, but is there a possible way to use Hugo themes in pkgdown?  

Pkgdown works like a charm in my website.  It will be fancier if the package' pages share the same theme with the main page.  

Thank you advance for any comments or suggestions.

Best,
Wenlong

**Comment by hadley** [comment]
No, sorry.

**Comment by hadley** [comment]
Pkgdown and hugo use completely separate templating systems so there's no easy way to share appearance across them. The easiest approach would probably be to develop a hugo template that looks like pkgdown.

**Comment by wenlong-liu** [comment]
Thanks for the reply.
