### ISSUE TITLE
Vignette build does not happen within the package structure

### ISSUE THREAD

**Issue by thk686** [r-lib/pkgdown#593]
I have the following code in one of my vignettes.
```
cache_file = "../inst/extdata/query_benchmark_data"
if (use_cached_data && file.exists(cache_file)) {
  load(cache_file)
} else {
# do stuff that takes about 1 hour to run
  save(build, query, file = cache_file)
}
```
When I rebuild the site, it is apparently not building the vignette within the normal package structure as it does not find the cached data. Is there somewhere that data can be cached and reused?

**Comment by thk686** [comment]
I fixed it with
```
cache_file = "../inst/extdata/sort_benchmark_data"
if (!file.exists(cache_file))
  cache_file = system.file("extdata/sort_benchmark_data", package = "kdtools")
```
That at least lets me build the site locally.

**Comment by hadley** [comment]
I think you'd be much better off using `system.file()` here. Relying on a specific directory structure is perilous.
