### ISSUE TITLE
long labels cutoff in \describe{} blocks

### ISSUE THREAD

**Issue by t-kalinowski** [r-lib/pkgdown#595]
Hello, I'm not sure if this is a bug or intended behavior, but I didn't see any place in the documentation to turn this behavior off. 

Slightly long labels in a `\describe{}` block are cutoff. Here is a screenshot of an example, where the 1st and 4th entry are cutoff. 

![screen shot 2018-03-25 at 8 51 06 am](https://user-images.githubusercontent.com/8462255/37875185-ae67b4b2-3009-11e8-8278-deb053e9b0d3.png)
(live version [here](https://t-kalinowski.github.io/listarrays/reference/split-array.html), and the actual roxygen block is [here](https://github.com/t-kalinowski/listarrays/blob/master/R/split.R))

Is there an easy way to adjust the width of the label to prevent it being cutoff?

**Comment by yiluheihei** [comment]
pkgdown uses bootstrap 3.3.7 to create the package website. [The \describe{} blocks was translated to `dl` (description list) in class `dl-horizontal`](https://github.com/r-lib/pkgdown/blob/286f8b39b1424f06f6962cf4272890043c04c8fc/R/rd-html.R#L304-L306).  

And  for bootstrap 3, horizontal description lists will truncate terms that are too long to fit in the left column with text-overflow. In narrower viewports, they will change to the default stacked layout. More details in [https://getbootstrap.com/docs/3.3/css/#horizontal-description](https://getbootstrap.com/docs/3.3/css/#horizontal-description).

HTH

**Comment by t-kalinowski** [comment]
Thank you! Adding the custom css solved the issue for me.
