### ISSUE TITLE
`build_site()` fails when the file `_pkgdown.yml` is empty

### ISSUE THREAD

**Issue by nacnudus** [r-lib/pkgdown#600]
Thank you for this wonderful package.

The situation occurs when `usethis::use_pkgdown()` creates an empty file `_pkgdown.yml`.

```r
pkgdown::build_site()
# Error: is.list(x) is not TRUE
```

Relevant code.

https://github.com/r-lib/pkgdown/blob/5e4825875751c009444c56ce43d06324ec53e910/R/package.r#L84-L97

`yaml::yaml.load_file()` returns `NULL` when a file is empty.  You can test it with `yaml::yaml.load_file(character(0))`.

I would submit a PR, but I don't know what to suggest.

* Check for `NULL`?
* PR to the yaml project to return `list()`?
* Friendly error message?
* Non-blank template in `usethis::use_pkgdown()`?

**Comment by jayhesselberth** [comment]
related to #598

**Comment by hadley** [comment]
Fixed by #598
