### ISSUE TITLE
ENOENT on copying files in vignettes subdirectory

### ISSUE THREAD

**Issue by nealrichardson** [r-lib/pkgdown#602]
In a `crunch` package vignette, we load images from an [`images/` subdirectory of `vignettes/`](https://github.com/Crunch-io/rcrunch/tree/master/vignettes/images). These fail to copy to the built pkgdown site and halt the build:

```
Reading 'vignettes/subtotals.Rmd'
Writing 'articles/subtotals.html'
Error: [ENOENT] Failed to copy '/Users/neal.richardson/Documents/crunch/rcrunch/vignettes/images/manning_knowledge_subtotals.png' to '/Users/neal.richardson/Documents/crunch/rcrunch/docs/articles/images/manning_knowledge_subtotals.png': no such file or directory
```

This is similar to https://github.com/r-lib/pkgdown/issues/569 and https://github.com/r-lib/pkgdown/issues/570; and like said in #570, if you create the `images` subdirectory and retry, it completes successfully. Presumably `build_site()` should make sure this file copying doesn't fail the first time. 

The traceback points to `fs::file_copy()`:

```
7: copyfile_(path_expand(path), path_expand(new_path), isTRUE(overwrite))
6: file_copy(path(path_dir(input_path), ext_path), path(path_dir(output_path), 
       ext_path), overwrite = TRUE)
5: render_rmarkdown(pkg, input = input, output = output_file, output_format = format, 
       output_options = options, quiet = quiet)
4: .f(.x[[i]], ...)
3: purrr::walk(pkg$vignettes$name, build_article, pkg = pkg, quiet = quiet, 
       lazy = lazy)
2: build_articles(pkg, lazy = lazy, override = override, preview = FALSE)
1: pkgdown::build_site()
```

Given #569 / #570, this sounds like a general problem that could merit a general solution, so we might try to resolve this by wrapping `file_copy()` like this:

```
safe_file_copy <- function(path, new_path, ...) {
  fs::dir_create(unique(dirname(new_path)))
  fs::file_copy(path, new_path, ...)
}
```

to ensure that destination directories always exist before trying to copy. Alternatively, we could also just add the `dir_create()` inside `render_rmarkdown()` and fix it for vignettes. Happy to submit a PR that does either (or something else entirely); figured I'd file an issue and get guidance before going too far in one direction.

**Comment by hadley** [comment]
This issue is unrelated to #569 - README needs to be handled specially.

The best fix would be something in fs, but we don't yet know what the API should feel like. I think it would be better to fix in the `copy_images` block.  Do you want to do a PR?

**Comment by nealrichardson** [comment]
Sure, I can do that.
