### ISSUE TITLE
Error in is_call(x, "data") : could not find function "is_call"

### ISSUE THREAD

**Issue by carlosparadis** [r-lib/pkgdown#603]
I recently updated the pkgdown installation in a Windows machine, and the following error started appearing:

```
Error in is_call(x, "data") : could not find function "is_call"
```

After executing pkgdown::build_site(). 

Looking around, I traced the function to the lazyval package via `?is_call`. I've tried both CRAN stable, and Github's dev versions, but the error persists. 

I believe the error is caused by the following line introduced 9 days ago:

https://github.com/r-lib/pkgdown/commit/319a65935a3de6e4b60326cd9b51ff88c01aa724

Any thoughts on how to address this?

Edit:

Using:

```
devtools::install_github("r-lib/pkgdown",ref="490a660154a92242bcbda18028fe56f0e32b18df")
```

The commit immediately before when the function was added does not throw the error, and generate the website documentation without errors.

**Comment by hadley** [comment]
You need to update rlang. I've tweaked the DESCRIPTION to make it clear that a recent version is required.
