### ISSUE TITLE
Continuous build options

### ISSUE THREAD

**Issue by adibender** [r-lib/pkgdown#606]
It would be nice to have the homepage continuously build (in the background) and updating 
the current tab on save (rather than open a new tab), similar to `blogdown::serve_site()` and 
`xaringan::infinite_moon_reader()`

**Comment by jayhesselberth** [comment]
@hadley are you OK just modifying relevant code from [blogdown/serve.r](https://github.com/rstudio/blogdown/blob/master/R/serve.R) with appropriate attribution?

**Comment by hadley** [comment]
I think it would be better to start in process; I think the approach that blogdown takes is a bit hairy.

**Comment by hadley** [comment]
At this time, I think don't think the benefit of this feature outweighs the implementation cost, especially given the large number of outstanding issues.
