### ISSUE TITLE
docsearch config consistency

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#608]
There are now a few docsearch configs for pkgdown sites, and they all have somewhat different scrape parameters. This could probably be made more consistent by optimizing css ids/classes for scraping.

https://github.com/algolia/docsearch-configs/blob/master/configs/valr.json
https://github.com/algolia/docsearch-configs/blob/master/configs/pkgdown.json
https://github.com/algolia/docsearch-configs/blob/master/configs/mlr.json

I wonder if the Docsearch team should be made aware that several pkgdown sites may be submitted? I think they tweak each of these manually which could be a waste of time; you might be able to provide them with a standard scrape json.

**Comment by hadley** [comment]
I wonder if we could include a standard docsearch `.json` in the built site?

**Comment by s-pace** [comment]
👋 @jayhesselberth @hadley 

For such, would be glad to help your tool!

We could even fine tune it a bit in order to create the best pattern from a config POV (e.g. remove see-also external links, licences ...).

**Comment by jayhesselberth** [comment]
I'll put something together to build a suggested docsearch JSON.

**Comment by s-pace** [comment]
Nice.

Could you also try to:
- [add a sitemap](https://www.sitemaps.org/) which will be our unique source of truth for crawling the websites
- either encapsulate the sheer document content in a specific class (e.g. `.docSearch`) or wrap the interference content in a specific class (e.g. `notDocContent`) like see also or table of content?

Thanks

**Comment by batpigandme** [comment]
🎉 Oh, awesome! @s-pace, @jayhesselberth I think you just made it infinitely easier for me to adapt this to bookdown. So, here, an emoji of a trophy: 🏆. I know, it's verprestigious, and you'll probably hang it on your walls.

**Comment by jayhesselberth** [comment]
@s-pace Can you provide some insight into the relationship between the `lvl0`, `lvl1`, `text` selectors and how search results are displayed? I couldn't find in the docs where this is explicitly spelled out.

For example, consider the search on http://pkgdown.r-lib.org. If you search for "build", you get 5 entries back. But the information per entry is redundant. I.e. Each search result is the same information displayed 3 different ways (Build articles, Build articles, Build articles). Do you have a suggestion to eliminate the redundancy?

![image](https://user-images.githubusercontent.com/355367/38092806-820d001e-3326-11e8-9add-69accc0a5725.png)

**Comment by s-pace** [comment]
@jayhesselberth 

Those selectors defined a specific records structure. They are representing the extracted data thanks [to a specific algorithm](https://community.algolia.com/docsearch/documentation/docsearch/how-it-works/#building-your-index). They are also used in order [to fine tune the algolia ranking formula](https://www.algolia.com/doc/guides/ranking/ranking-formula/). 

You have repetition there because the result you are highlighting must have an empty `text` level and only the `lvl0` set. 

The [search UI is open source and available here](https://github.com/algolia/docsearch). I don't think you need to dig too much in this part.

Mostly the highest part is the `lvl0`, the left one is `lvl1` while the nested title is a breadcrumb of the other levels. 
For example:
![image](https://user-images.githubusercontent.com/32097720/38094015-e5d3aeae-336c-11e8-9191-e31cd415c695.png)

lvl0=Configuring the search results
lvl1=DocSearch Options
lvl2=handleSelected
text=We already bind...

**Comment by hadley** [comment]
I was thinking we might need different selectors for articles and reference, but I think this will do nicely:

```yaml
"selectors": {
  "lvl0": ".contents h1",
  "lvl1": ".contents h2",
  "lvl2": ".contents h3, .contents th",
  "lvl3": ".contents h4, .contents th",
  "lvl4": ".contents h5, .contents th",
  "text": ".contents p, .contents li, .usage"
}
```

It looks like there's a bit of inconsistency with the `.page-header` div; we should make sure it's either consistently inside of the `.contents` div or before it.

**Comment by hadley** [comment]
Hmmm, we might want to consider indexing `pre` in articles, since that will show function usage.

**Comment by hadley** [comment]
@s-pace is docsearch ok with the text form of the sitemap protocol? Or does it need to be xml?

**Comment by s-pace** [comment]
👋 @hadley 

So far sitemap must be xml. They must be compliant [with this standard](https://www.sitemaps.org/)

Most of the time we don't recommend to index code-like element since it introduces some noise.

We can even use specific classes (with no style). It might be easier to integrate in a html POV.

**Comment by hadley** [comment]
@s-pace that standard includes other formats: https://www.sitemaps.org/protocol.html#otherformats, so technically I am in compliance 😉

**Comment by hadley** [comment]
Here's the latest appearance (searching for "extra" on pkgdown)

<img width="519" alt="screen shot 2018-03-30 at 6 59 38 am" src="https://user-images.githubusercontent.com/4196/38140323-207fa870-33e8-11e8-997e-ef55c85281a4.png">

I think we need to include the alias/article name somewhere (perhaps in the `lvl0`?). We also need consider the default styling: few hits are going to use `lvl2` headings (only in parameter search) so we get the `lvl1` heading shown in two places.

**Comment by s-pace** [comment]
👋 @hadley,

I have tried to use your xml sitemap from our scrapper and it works well 👏. Let's use this one then.

I have tried to check on the result pages but I couldn't find what do you mean by alias/article name? We pick up every header. Could you show us a screenshot of which part you meant?

Regarding the "duplicate titles" when no lvl2 are set, we could think about adding a default value or what would you like to display instead? We highly recommend to have at least 3 different levels set.

**Comment by jayhesselberth** [comment]
For reference pages, I think we selectors like this, once #604 is done and there is something like `<meta func-name="init_site()">` implemented. Note that `h2` is demoted here.

```json
  "selectors": {
    "lvl0": ".title, .page-header h1",
    "lvl1": ".meta func-name",
    "lvl2": ".contents h2",
    "lvl3": ".contents h3, .contents table th",
    "lvl4": ".contents h4",
    "lvl5": ".contents h5",
    "text": ".contents p, .contents li, .usage"
  }

```

**Comment by hadley** [comment]
Documentation "name" now included in `.name`, which is hidden with css.

**Comment by jayhesselberth** [comment]
We can also hide one of the levels in the search results by modifying the algolia CSS. I think this is what they did in the docusaurus search results.

**Comment by s-pace** [comment]
@hadley Thank you for the heads up. 

You can otherwise use the active element from your `navbar-nav` as lvl0.

@jayhesselberth you can [use tags  and selectors_key](https://community.algolia.com/docsearch/documentation/docsearch-scraper/config-options/#start_urls-mandatory) if you want to enhance the scope of your config.

**Comment by hadley** [comment]
Let's try using the "filename" as lvl1: 

```json
{
  "index_name": "pkgdown",
  "start_urls": "http://pkgdown.r-lib.org",
  "sitemap_urls": "http://pkgdown.r-lib.org/sitemap.xml",
  "selectors": {
    "lvl0": ".contents h1",
    "lvl1": ".contents .name",
    "lvl2": ".contents h2",
    "lvl3": ".contents h3, .contents th, .contents dt",
    "lvl4": ".contents h4",
    "text": ".contents p, .contents li, .usage, .template-article .contents .pre"
  },
  "selectors_exclude": ".dont-index"
}
```

**Comment by s-pace** [comment]
For the reference part, you could use the section data type as a hidden object within the page.
e.g. http://valr.hesselberthlab.org/reference/index.html

**Comment by s-pace** [comment]
Quick feedback.
- `selectors_exclude`, `start_urls` and `sitemap_urls` should be an array
- Pages should not be available twice. Otherwise you will have duplicates. (e.g. http://valr.hesselberthlab.org/  & http://valr.hesselberthlab.org/index.html)

**Comment by hadley** [comment]
Can we just provide a site map instead of a start url? I think we only want to index the pages listed in the sitemap.

**Comment by s-pace** [comment]
Yes you can.

The url of `start_urls` (or their attribute url for more advanced object) behave as regex on the sitemap. You will have to put a regex that isn't available from a http request POV.

Otherwise you can use `sitemap_urls_regexs` and `sitemap_urls` together.

**Comment by hadley** [comment]
Like `"start_urls" = ["http://pkgdown.r-lib.org/DOESNTEXIST"]` ?

**Comment by hadley** [comment]
And maybe set `"force_sitemap_urls_crawling" = "true"` ?

**Comment by jayhesselberth** [comment]
It looks like you can just use the base URL for `start_urls`. E.g. see [this config](https://github.com/algolia/docsearch-configs/blob/de316544a070abd95ecf21e5d5218253902ecc12/configs/commercetools.json).

**Comment by s-pace** [comment]
> "start_urls" = ["http://pkgdown.r-lib.org/DOESNTEXIST"] ?
If you use a sitemap and if you want to use `tags` or `extra_attributes` or specific `selectors_key` you should do something like
```json
"start_urls": [
    {
      "url": "http://pkgdown.r-lib.org/reference/",
      "variables": {
        "tags": [
          "reference"
        ]
      },
      "selectors_key": "reference"
    }
  ],
```
> And maybe set "force_sitemap_urls_crawling" = "true" ?
This parameter is only involving `sitemap_urls` & `sitemap_urls_regexs`. It is there to say that the URL from the sitemap don't have to respect the `stop_urls`. It shouldn't be used here

> It looks like you can just use the base URL for start_urls. E.g. see this config.
You can use that indeed.

**Comment by jayhesselberth** [comment]
@s-pace thanks, moving `.contents dt` to the text selector does improve the granularity of display.

**Comment by hadley** [comment]
Isn't that `<td>` not `<dt>`?

**Comment by jayhesselberth** [comment]
Yep should be `<dt>`

**Comment by s-pace** [comment]
Actually since your `td` is wrapping a `p` element you shouldn't put it

**Comment by s-pace** [comment]
@hadley 
Could you PR the pkgdown like configs once it is live? Since we have some new pkgdown requests, we would like to update all of them in the same way.
Thanks and 👏
