### ISSUE TITLE
create sitemap.xml

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#609]
And add to docsearch json, e.g.:

```json
"sitemap_urls": [
 "http://pkgdown.r-lib.org/sitemap.xml"
],
```

https://stackoverflow.com/questions/12255359/how-to-create-a-sitemap-xml-file-using-r-and-the-xml-package

From #608

**Comment by hadley** [comment]
I don't see much point in this - any search engine will just spider in the same way. I think sitemaps are more useful for more complex sites where all the pages aren't reachable within two links from the homepage.
