### ISSUE TITLE
In-page highlighting of search results

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#610]
@s-pace is it possible to have docsearch add a query string (e.g. `?q=search_text`) so we can implement our own in-page highlighting?

**Comment by s-pace** [comment]
DocSearch is redirecting to the clicked pages. We can even know the exact matching part from the records and put it as  GET parameter [thanks to the transformData function](https://community.algolia.com/docsearch/documentation/docsearch-autocomplete/configuring-the-search/#transformdata). 

Is it what you aim at?

**Comment by hadley** [comment]
Yes, that would be great. Do you have any examples that you can point to? My javascript skills are not great, so it would be nice to have an existing example to build off of.

**Comment by jayhesselberth** [comment]
@s-pace I can see from [this page](https://code.osu.edu/little.129/bootstrap/blob/6436233a9c786d32990a5fbc0c7dcc9e1af8332b/_includes/scripts.html) that something like this would work to add a parameter to search results.

```js
docsearch({
    ...
    transformData: function(hits) {
      return hits.map(function (hit) {
        // modify URL to add GET method.
        // e.g. url => url?search=blerg
        hit.url = hit.url.XXX;
        return hit;
      }
    }
    ...
});
```

But how do I refer to the value of the search string? Is it just the value of the `inputSelector`?

**Comment by s-pace** [comment]
My point was the use the hit's attributes [that are described here](https://www.algolia.com/doc/api-reference/api-methods/search/?language=php#method-response-hits).

You can have a look [on this fiddle](http://jsfiddle.net/s_pace/bhLdo27h/). We only highlight the matching words and part from the query. It looks like it will be hard to implement from your side because of typo tolerance and synonym for example.

**Comment by hadley** [comment]
I'm happy to give up on typo tolerance etc; only matching the exact search term would be better than nothing.

**Comment by s-pace** [comment]
🆗 So `transformData` is the one to use

**Comment by jayhesselberth** [comment]
Do you want to do in-page highlighting with [mark.js](https://markjs.io/)?

**Comment by hadley** [comment]
That looks great!

**Comment by jayhesselberth** [comment]
Mostly functional implementation of in-page highlighting here: http://pkgdown-search.netlify.com/

Search for "search" or "pkgdown".

The markup is obnoxious, but I guess that's the point. Do you want a particular style (i.e., yellow, not orange). Or [animated text](https://codepen.io/levineuland/pen/AmwCL)? It's nice if the highlighted text pulses once when you are redirected to page.

**Comment by s-pace** [comment]
@jayhesselberth looks nice 🎉 

Feel free to let me know once it is live, we will update your configuration's template

**Comment by s-pace** [comment]
Done here https://github.com/r-lib/pkgdown/issues/610#issuecomment-383382074
