### ISSUE TITLE
Error: Can't find template for content-license.

### ISSUE THREAD

**Issue by wch** [r-lib/pkgdown#613]
This happens when running `pkgdown::build_site()` for shinytest.

```
> pkgdown::build_site()
Initialising site -------------------------------------------------------------------------------
Copying '/Users/winston/R/3.4/pkgdown/assets/jquery.sticky-kit.min.js'
Copying '/Users/winston/R/3.4/pkgdown/assets/link.svg'
Copying '/Users/winston/R/3.4/pkgdown/assets/pkgdown.css'
Copying '/Users/winston/R/3.4/pkgdown/assets/pkgdown.js'
Building home -----------------------------------------------------------------------------------
Error: Can't find template for content-license.
```

**Comment by hadley** [comment]
Are you using a custom template?

**Comment by wch** [comment]
I don't think so. It was built with an older version of pkgdown though, and after I did some hacking on pkgdown to get it to build one time, I can now build it with the un-hacked version of pkgdown. So maybe this is only a transient issue.

**Comment by soodoku** [comment]
had the same issue. nuked the docs folder and then re-ran pkgdown::build_site() and it worked. (just leaving this comment for other people who may be facing this issue.)
