### ISSUE TITLE
Article figures have exaggerated y dimension

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#614]
Figures on the README/home page now have an exaggerated y dimension.

Added `plot(rnorm(1000))` to the bottom of the pkgdown README: https://sharp-khorana-4efcff.netlify.com/

Figures in the reference seem fine:

https://sharp-khorana-4efcff.netlify.com/reference/test-figures.html

**Comment by hadley** [comment]
It's a problem in articles in general: https://sharp-khorana-4efcff.netlify.com/articles/test/figures.html

I thought I fixed this 😬

**Comment by IndrajeetPatil** [comment]
I am having the exact same issue! All figures from `README.Rmd` are all stretched out vertically on GitHub.

**Comment by michaellevy** [comment]
I'm not sure where I saw it or what it was doing, but I suspect the issue is related to the `fig.asp = ~` default. Including `fig.asp: NULL` in my yml allowed me to specify heights/ratios in the yml or individual files, which were getting overridden before making that change.

**Comment by IndrajeetPatil** [comment]
@hadley Not sure if this has anything to do with `pkgdown`, but my `README` document looks perfectly fine on GitHub (https://github.com/IndrajeetPatil/ggstatsplot), but it is all out of whack on `CRAN` (https://cran.r-project.org/web/packages/ggstatsplot/README.html). 

The version of README I submitted to CRAN was created **before** the issue in this thread was resolved, so I am wondering if it is relevant.
