### ISSUE TITLE
images not included in the rendered webpage

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#615]
I created a webpage for my package with `pkgdown` and, as recommended, all my figures from `man/figures/x.png` are getting copied to `reference/figures/x.png` (https://github.com/IndrajeetPatil/ggstatsplot/tree/master/docs/reference/figures) when I run `pkgdown::build_site()`.

But the resulting website still doesn't display any of the images:
https://indrajeetpatil.github.io/ggstatsplot/

What can I change to display the images properly?
Here is my-
source `README.Rmd`: https://github.com/IndrajeetPatil/ggstatsplot/blob/master/README.Rmd
and
`index.html` file: https://github.com/IndrajeetPatil/ggstatsplot/blob/master/docs/index.html

**Comment by hadley** [comment]
Hmmm, for some reason it's generating a bad link. Can you try installing the latest version of fs and rebuilding?

**Comment by IndrajeetPatil** [comment]
@hadley Thanks for the suggestion. 
I downloaded the recent, development versions of both `fs` and `pkgdown`, but now it's not even generating the `html` page. Here is the error-

```
> pkgdown::build_site()
== Building pkgdown site =======================================================
Reading from: 'C:/Users/Indrajeet Patil/Documents/ggstatsplot'
Writing to:   'C:/Users/Indrajeet Patil/Documents/ggstatsplot/docs'
-- Initialising site -----------------------------------------------------------
Writing 'docsearch.json'
-- Building home ---------------------------------------------------------------
Reading 'CONDUCT.md'
Reading '.github/ISSUE_TEMPLATE.md'
Reading 'README.Rmd'
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```

**Comment by hadley** [comment]
Can you remove the fig size customisation from your readme and see if that helps?

**Comment by IndrajeetPatil** [comment]
I removed all fig size customization arguments: `figure.height`, `figure.width`, and `dpi`. 
But `build_site()` still produces the same error. 
```
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```

**Comment by IndrajeetPatil** [comment]
I also tried this with another package:
`index.html`: https://github.com/IndrajeetPatil/groupedstats/blob/master/docs/index.html
`README.Rmd`: https://github.com/IndrajeetPatil/groupedstats/blob/master/README.Rmd

In this case, `build_site()` **doesn't** throw any errors, but it still doesn't display the only figure in the document:
https://indrajeetpatil.github.io/groupedstats/

**Comment by hadley** [comment]
The viewport error comes from the `combine_plots_purrr2` chunk.  If I delete that chunk, and rebuild home, I get an `index.htm` with correct image links. This suggests the problem is local to your system.

**Comment by hadley** [comment]
And the viewport error is because `fig.asp` beats `fig.height` in knitr.

**Comment by IndrajeetPatil** [comment]
I tried the new version of `pkgdown` with recent commits and it still doesn't work.

This holds even if I run `pkgdown::build_site()` function on `README.Rmd` document (https://github.com/IndrajeetPatil/groupedstats/blob/master/README.Rmd) that has just one figure with no figure customizations:
https://indrajeetpatil.github.io/groupedstats/

So there seems to be something in my system that is messing with the `pkgdown`. I am not sure what I can do to diagnose the problem though.

I am attaching my `session_info` it it's of any help.
``` r
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.4 (2018-03-15)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       America/New_York            
#>  date     2018-04-03                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version     date       source                            
#>  ansistrings   1.0.0.9000  2018-04-03 Github (r-lib/ansistrings@4e4d309)
#>  assertthat    0.2.0       2017-04-11 CRAN (R 3.4.1)                    
#>  backports     1.1.2       2017-12-13 CRAN (R 3.4.1)                    
#>  callr         2.0.2.9002  2018-04-03 Github (r-lib/callr@9c38827)      
#>  cli           1.0.0.9002  2018-04-03 Github (r-lib/cli@c408924)        
#>  clisymbols    1.2.0       2017-05-21 CRAN (R 3.4.3)                    
#>  crayon        1.3.4       2017-09-16 CRAN (R 3.4.3)                    
#>  debugme       1.1.0       2017-10-22 CRAN (R 3.4.3)                    
#>  desc          1.1.1.9003  2018-04-03 Github (r-lib/desc@387b732)       
#>  devtools      1.13.5.9000 2018-03-30 Github (r-lib/devtools@2f7bc84)   
#>  digest        0.6.15      2018-01-28 CRAN (R 3.4.3)                    
#>  evaluate      0.10.1      2017-06-24 CRAN (R 3.4.3)                    
#>  glue          1.2.0       2017-10-29 CRAN (R 3.4.4)                    
#>  hms           0.4.2       2018-04-03 Github (tidyverse/hms@c0cfc01)    
#>  htmltools     0.3.6       2017-04-28 CRAN (R 3.4.1)                    
#>  knitr         1.20        2018-02-20 CRAN (R 3.4.3)                    
#>  magrittr      1.5         2014-11-22 CRAN (R 3.4.2)                    
#>  memoise       1.1.0       2017-04-21 CRAN (R 3.4.1)                    
#>  pkgbuild      1.0.0       2018-04-03 Github (r-lib/pkgbuild@015f7f6)   
#>  pkgconfig     2.0.1       2017-03-21 CRAN (R 3.4.1)                    
#>  pkgload       1.0.0       2018-04-03 Github (r-lib/pkgload@f827a27)    
#>  prettyunits   1.0.2       2015-07-13 CRAN (R 3.4.2)                    
#>  progress      1.1.2.9003  2018-04-03 Github (r-lib/progress@e525de4)   
#>  R6            2.2.2       2017-06-17 CRAN (R 3.4.1)                    
#>  Rcpp          0.12.16     2018-03-13 CRAN (R 3.4.3)                    
#>  rlang         0.2.0       2018-02-20 CRAN (R 3.4.4)                    
#>  rmarkdown     1.9         2018-03-01 CRAN (R 3.4.3)                    
#>  rprojroot     1.3-2       2018-01-03 CRAN (R 3.4.1)                    
#>  selectr       0.4-0       2018-03-27 CRAN (R 3.4.4)                    
#>  sessioninfo   1.0.1.9000  2018-03-30 Github (r-lib/sessioninfo@c871d01)
#>  stringi       1.1.7       2018-03-12 CRAN (R 3.4.3)                    
#>  stringr       1.3.0.9000  2018-04-03 Github (tidyverse/stringr@097c0c0)
#>  testthat      2.0.0       2017-12-13 CRAN (R 3.4.1)                    
#>  usethis       1.3.0.9000  2018-04-03 Github (r-lib/usethis@ac247dc)    
#>  withr         2.1.2       2018-04-03 Github (r-lib/withr@79d7b0d)      
#>  xml2          1.2.0       2018-01-24 CRAN (R 3.4.1)                    
#>  yaml          2.1.18      2018-03-08 CRAN (R 3.4.3)
```

Created on 2018-04-03 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment]
Unfortunately I can't reproduce it and I have no idea why your system might be different 😢

**Comment by lorenzwalthert** [comment]
> Hmmm, for some reason it's generating a bad link. Can you try installing the latest version of fs and rebuilding?

I also encountered this problem on Windows, although in a slightly different form. The path to my image contains the top-level directory twice. I.e. I want
`file:///Z:/top_level/below/dir`
but I get this link:
`file:///Z:/top_level/top_level/below/dir`

I used `fs` 1.2.2, which is the current CRAN version. I also tried the devel version at  88b1f3b but it did not help.
