### ISSUE TITLE
Suppress (optionally?) method signatures from reference index

### ISSUE THREAD

**Issue by nealrichardson** [r-lib/pkgdown#616]
Here's a final unexpected issue I've noticed using the latest `pkgdown`, which otherwise has been excellent. The current version of `pkgdown` expands out all of the method signatures and includes them on the reference index page. That can get pretty verbose if the package has many classes. So what previously looked like this (currently deployed on http://crunch.io/r/crunch/reference/)

<img width="893" alt="screen shot 2018-03-29 at 9 37 44 pm" src="https://user-images.githubusercontent.com/2975928/38147392-fb23337a-3406-11e8-8334-1bef5482341a.png">

with the new pkgdown code looks like this:

<img width="904" alt="screen shot 2018-03-29 at 9 37 23 pm" src="https://user-images.githubusercontent.com/2975928/38147398-021c583c-3407-11e8-8eac-09406a0f40f0.png">

This makes browsing the reference index more challenging, so I'd like to be able to suppress the method signatures. [This commit on my fork](https://github.com/r-lib/pkgdown/commit/563d57a4469f5feb04012d95938ae26459a82ba7) does that, and more or less restores the previous behavior. 

Presumably there was a reason for the addition, so you wouldn't want a PR with that exact change. But would you consider accepting a way to make this optional, perhaps as a setting in `_pkgdown.yml`?

**Comment by hadley** [comment]
Where is the generic documented? The methods are suppressed when documented with the generic.

**Comment by nealrichardson** [comment]
Ah, so they are. For years I've been responding to the `R CMD check` messages that all methods must be documented by attaching the docs to the methods, and `check` doesn't complain about undocumented generics, so it never occurred to me to put docs there. But I can see that putting docs with the generic makes logical sense. 

I'll close this since it sounds like user error and just build off of the branch on my fork until I get a chance to move all of the docs to the generics. But if this becomes an issue for others, my offer to submit a PR to add an option stands.
