### ISSUE TITLE
htmlwidgets - Examples

### ISSUE THREAD

**Issue by JohnCoene** [r-lib/pkgdown#617]
A brilliant package, writing vignettes was much overdue. I encounter the following error in `@examples` for htmlwidget packages:

```r
Error in yaml.load(readLines(con), error.label = error.label, ...): argument "error.label" is missing, with no default
```

I tried with a few such htmlwidget, [here](https://johncoene.github.io/echarts4r/reference/e_area.html) is an examples. The package works fine otherwise, including in vignettes/articles and index.Rmd. I updated pandoc to `2.1.3` to no avail. I could be misunderstanding something.

**Comment by hadley** [comment]
HTML widgets aren't currently supported

**Comment by hadley** [comment]
See older work in #343 that needs to be updated based on changes to the package.

**Comment by jayhesselberth** [comment]
Closing in favor of new meta-issue #1256
