### ISSUE TITLE
Finalize with html tidying?

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#619]
whisker templates leave a lot of blank spaces etc. Would it be worth finalizing the package build with a sweep of the html outputs with [htmltidy](https://github.com/hrbrmstr/htmltidy/)?

**Comment by hadley** [comment]
Yeah, worth considering (if it doesn't add too much overhead)

**Comment by jayhesselberth** [comment]
I played a bit with htmltidy but it doesn't work as well as I'd hoped.

**Comment by hadley** [comment]
What if we just stripped blank lines in the header?
