### ISSUE TITLE
update workflow?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#624]
Thanks for this package 👌 

I was wondering what the recommended update workflow of the package website is /should be. Sorry if I missed this in the repo!

* Should it just rely on the developper's remembering to update it regularly enough?

* Should the website be updated every time one of its sources change and in this case should there be a pre-commit hook like the one `usethis` has for README.Rmd/README.md, with different functions recommended depending on the unreflected changes (e.g. `build_news` if NEWS changed)... it all seems a bit cumbersome maybe (to implement, and then to experience as an user).

* Will there be a question/custom check in e.g. `devtools::release()`?

**Comment by hadley** [comment]
I think the best workflow is likely to be a reminder in `release()`. Would you mind filing an issue in devtools?
