### ISSUE TITLE
docsearch result styling

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#626]
I've ported some algolia CSS from bootstrap into pkgdown. This display drops the subcategory (`lvl1`, I *think*) to make the results a little less redundant, and I think more naturally matches the organization of the documentation.

Compare this to a search for "extr" on the live pkgdown site.

![image](https://user-images.githubusercontent.com/355367/38401263-fdbddad0-3911-11e8-8e8d-5571e11fda7b.png)

**Comment by jayhesselberth** [comment]
moved to #627

**Comment by jayhesselberth** [comment]
Functional search with new styling is here: https://pkgdown-search.netlify.com/

**Comment by jayhesselberth** [comment]
Here it is with `.name` in `lvl2`.

https://5ac7cb6b0b79b75a6af0646f--pkgdown-search.netlify.com/

**Comment by hadley** [comment]
A few comments (not all related your tweaks, but just as I explore):

* Why is the contributor code of conduct getting indexed? I thought we were only explicitly indexing articles and man pages?

* We need a `lvl3` heading for the description - otherwise you see the filename in the context for a hit in the description. Otherwise, I don't ever see the file name, which is probably a good thing.

* Why can't we scroll results?

**Comment by jayhesselberth** [comment]
Here are a few search configs with `.name` in:

- [`lvl1`](https://pkgdown-search.netlify.com/)
- [`lvl2`](https://5ac7e910efbe5d73b8399c79--pkgdown-search.netlify.com/)
- [`lvl3`](https://5ac7e91792226a6a0b351fc7--pkgdown-search.netlify.com/)

In the `lvl3` config, the filename is nested under the top-level `h1`. Does this address your above comment?

I'll look into the sitemap and scrolling issue.

**Comment by jayhesselberth** [comment]
Here's ggplot2 configured with `lvl3` settings: http://ggplot2-search.netlify.com/

Unfortunately it's not the full index because this site exceeds the number of records one can have with a free Algolia account. There's 4400 records in this index.

**Comment by jayhesselberth** [comment]
Um my algolia account is suspended because there's a limit on operations. Searches above won't work. I applied for the free open source account, hopefully they'll get back soon.

**Comment by jayhesselberth** [comment]
This strategy improves the structure of displayed somewhat by treating reference and articles differently. It's not live currently.

![image](https://user-images.githubusercontent.com/355367/38595731-82e836a0-3d0a-11e8-9892-a03d13b9310a.png)


```json
{
  "index_name": "pkgdown-search2",
  "start_urls": [
    {
      "url": "http://pkgdown-search.netlify.com/index.html",
      "selectors_key": "homepage",
      "tags": [
        "homepage"
      ]
    },
    {
      "url": "http://pkgdown-search.netlify.com/reference",
      "selectors_key": "reference",
      "tags": [
        "reference"
      ]
    },
    {
      "url": "http://pkgdown-search.netlify.com/articles",
      "selectors_key": "articles",
      "tags": [
        "articles"
      ]
    }
  ],
  "stop_urls": [],
  "sitemap_urls": [
    "http://pkgdown-search.netlify.com/sitemap.xml"
  ],
  "selectors": {
    "homepage": {
      "lvl0": {
        "selector": ".contents h1",
        "default_value": "pkgdown Home page"
      },
      "lvl1": {
        "selector": ".contents h2"
      },
      "lvl2": {
        "selector": ".contents h3",
        "default_value": "Context"
      },
      "text": ".contents p, .contents li, contents .pre"
    },
    "reference": {
      "lvl0": {
        "selector": ".contents h1"
      },
      "lvl1": {
        "selector": ".contents .name",
        "default_value": "Argument"
      },
      "lvl2": {
        "selector": ".ref-arguments th",
        "default_value": "Description"
      },
      "lvl3": ".ref-arguments td, .ref-description",
      "lvl4": ".usage",
      "text": ".contents p, .contents li, .template-article .contents .pre"
    },
    "articles": {
      "lvl0": {
        "selector": ".contents h1"
      },
      "lvl1": {
        "selector": ".contents .name"
      },
      "lvl2": {
        "selector": ".contents h2, .contents .h3",
        "default_value": "Context"
      },
      "text": ".contents p, .contents li, .template-article .contents .pre"
    }
  },
  "selectors_exclude": [
    ".dont-index"
  ],
  "min_indexed_level": 2,
  "custom_settings": {
    "separatorsToIndex": "_"
  },
  "nb_hits": 519
}
```
