### ISSUE TITLE
Rd Table formating

### ISSUE THREAD

**Issue by aravind-j** [r-lib/pkgdown#630]
Tables in Rdocumentation specified by `\tabular` are not aligning properly and have no spacing between columns and rows.
For example.

https://aravind-j.github.io/rmelting/reference/melting.html

**Comment by hadley** [comment]
Can you please provide a link to the Rd source and the source of the generated html?

**Comment by aravind-j** [comment]
Here is the link to the Rd source and generated html.

https://github.com/aravind-j/rmelting/blob/master/man/melting.Rd

https://github.com/aravind-j/rmelting/blob/master/docs/reference/melting.html

**Comment by hadley** [comment]
https://github.com/aravind-j/rmelting/blob/master/man/melting.Rd#L228-L232 + https://github.com/aravind-j/rmelting/blob/master/docs/reference/melting.html#L430-L452
