### ISSUE TITLE
Package-level doc

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#634]
I'm talking about `foo-package.html`, for the package foo. Right now this is a bit of an orphan wrt the function reference page. It is neither automatically included, but neither do you get the usual `Warning: Topics missing from index: ...`. Should one of those be true? The html is getting generated, but isn't accessible by any series of clicks, I believe.

**Comment by hadley** [comment]
It's sort of hidden on purpose - I think we're moving towards this file being largely autogenerated (e.g. https://github.com/klutometis/roxygen/issues/669) so I'd rather not promote it.
