### ISSUE TITLE
Function error appears in vignette only during build_site()

### ISSUE THREAD

**Issue by katrinleinweber** [r-lib/pkgdown#635]
Hello,

I have the following piece of code that executes fine line-by-line, or when knit-ing the .Rmd within which the code is contained.

```{r}
extract_temps <- function(dataset, taxon_name) {
  dataset %>%
  purrr::map(~.x$culture_growth_condition$culture_temp$temp) %>%
  unlist() %>%
  as.numeric() %>%
  data.frame(temp_C = ., taxon = rep(taxon_name, length(.))) %>%
  return()
}

temperature_Bac <- extract_temps(Bac_data, taxon_1) 
temperature_At <- extract_temps(At_data, taxon_2) 
```

When running `pkgdown::build_site()` the following error appears, when `Building article '….html'`:

```
Error in .x$culture_growth_condition :
  $ operator is invalid for atomic vectors
Calls: <Anonymous> ... <Anonymous> -> do.call -> .f -> <Anonymous> -> get_result
```

But when stepping through the above code within the .Rmd document, everything works as expected.

I'm not sure how to make a proper reprex, because `Bac_data` & `At_data` stem from a web service that requires authentication. I attached the necessary .rda files to show that the code itself should be fine:

[Function-error-appears-in-vignette-only-during-build_site.zip](https://github.com/r-lib/pkgdown/files/1925524/Function-error-appears-in-vignette-only-during-build_site.zip)

**Comment by katrinleinweber** [comment]
This seems so strange, and I apologise if this turns out to be an issue with another package. I'm not sure where else to put this. Does pkdown somehow create a different environment, within the code is executed differently than interactively?

I re-ran `devtools::install_github("r-lib/pkgdown")` just now, but the error persists.

I tried `library(purrr) ... map(.x = ., .f = ~.x$culture_growth_condition...` as well to exclude any possibility of `purrr::map...` causing this.

**Comment by hadley** [comment]
How are `Bac_data` and `At_data` being loaded? Are you using caching?

**Comment by hadley** [comment]
Can you give me an easy way to get the complete package that's causing you this problem?

**Comment by katrinleinweber** [comment]
Good morning, and thanks for replying! They are generated from a JSON which is fetched from a web service. No caching.

I'm preparing the package publication within the next 2 weeks. Will link to it from here. Is the problem not reproducible with the [.Rda files in the .zip](https://github.com/r-lib/pkgdown/files/1925524/Function-error-appears-in-vignette-only-during-build_site.zip)?

**Comment by hadley** [comment]
I really need the whole package so I can understand what's going on. If you can't give me the whole package, could you give me a mini package that just has the bare minimum needed to reproduce the problem? Otherwise it's unlikely that I'll have time to figure it out.
