### ISSUE TITLE
Can we please have a bit more documentation on how to integrate docsearch search?

### ISSUE THREAD

**Issue by michaellevy** [r-lib/pkgdown#641]
I'm so excited that this functionality is available, thanks @jayhesselberth for all your work on this. With little web-dev experience, I'm having a hard time following the instructions in the getting started vignette. Specifically:

- Where do you put the CSS/JS snippets docsearch sends you?
- What are the values that go to the `apiKey` and `indexSelector` parameters? Where can they be found?

**Comment by michaellevy** [comment]
@jayhesselberth thanks. This is what I got from docsearch. Maybe they forgot to fill in the details? I'll contact them.

> Copy the following CSS/JS snippets and add them to your page 

```
<!-- at the end of the HEAD --> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" /> 

<!-- at the end of the BODY --> 
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script> 
<script type="text/javascript"> docsearch({ 
 apiKey: '### REPLACE ME ####', 
 indexName: 'healthcareai', 
 inputSelector: '### REPLACE ME ####', 
 debug: false // Set debug to true if you want to inspect the dropdown 
}); 
</script> 
```

**Comment by jayhesselberth** [comment]
Yea it looks like they forgot to fill in your `apiKey`.

**Comment by michaellevy** [comment]
I think the docs are clear then. You might consider adding a bit to the line before the yml codeblock to the effect of "You don't need to put docsearch's code snippet anywhere; instead, put the value of the apiKey and indexName parameters from their snippet into your _pkgdown.yml and pkgdown will build the necessary JS for you." But I think it's fine. Sorry to have troubled you about this. :)
