### ISSUE TITLE
Inaccurate Rd to html conversion for tables with empty cells

### ISSUE THREAD

**Issue by aravind-j** [r-lib/pkgdown#645]
Due to empty cells, the Rd to html conversion is off (https://aravind-j.github.io/rmelting/reference/melting.html) and shows the following error. 
```
In matrix(cell_contents, ncol = length(align), byrow = TRUE) :
  data length [14] is not a sub-multiple or multiple of the number of rows [4]
```
This is after  the alignment and spacing were fixed in #630 .

Here is the link to the Rd source and generated html.

https://github.com/aravind-j/rmelting/blob/master/man/melting.Rd

https://github.com/aravind-j/rmelting/blob/master/docs/reference/melting.html

**Comment by hadley** [comment]
Can you please link to specific lines?

**Comment by hadley** [comment]
Different error message but seems closely related to #664
