### ISSUE TITLE
Removal of `path` argument in `build_site`

### ISSUE THREAD

**Issue by nsheff** [r-lib/pkgdown#646]
A recent commit (1ba293f394d852447e904b76bf4564edaef6afee) removed the `path` argument to `build_site` in favor of a `_pkgdown.yaml` setting called `destination`.

I think this decision has reduced flexibility of the package. Have I missed something? Here are a few thoughts on my use case for your consideration:

Out of principle, I keep only code that I want to version control in my git repository, and I try to keep automatically generated documents out of the repository. These auto-generated docs include things like the output of pkgdown. I do not want to commit them into the repository, because they clutter the commit history and repo size, and I do not need to version control them because they are derived from my version-controlled code.

Even without this issue, running the web pages like this increases overhead for authors with many R packages. I have written many R packages, each in its own git repository that I keep on GitHub. Because I have many R packages, each with a site generated by pkgdown, it makes sense to keep all of these web pages in a separate location which is served on the web, rather than maintaining a *pages* site for each repository individually.  Therefore, I want to point the output of `pkgdown` to this web-server location that is common for all my R packages and potentially other web items. This greatly simplifies the setup of new R package web page deploys, and also simplifies maintenance of web pages, templating, etc.

In the past, I wrote a simple command-line function that would build the `pkgdown` site in this shared space:

```
pkgdowngen () 
{ 
    R --quiet -e "pkgdown::build_site('${HOME}/code/$1', path='/path/to/www/$1')"
}
```

Upon updating an R package documentation, this one-liner would update the pkgdown-generated web page in a separate space, which is easy to maintain for dozens of packages. This workflow, which I view as the most efficient for using `pkgdown` for authors with many R packages, is now no longer possible.

The alternative is to change the `_pkgdown.yaml` file for each R package to add the `destination` attribute. This would restore my workflow, but this is problematic for 2 reasons: First, it requires *hard-coding* the `/path/to/www` variable now in each package, when that variable actually has nothing to do with the package, but with my current environmental setup for web development. In fact, this makes these packages generally unbuildable anywhere except on the place where I usually build. This has reduced the portability of the package and reduced the utility of `pkgdown`. Second, it has now duplicated the `/path/to/www` variable across many places, where it was previously sufficient to have that in one place, making it much easier to move things around.

Thus, from my perspective, I view the change as both philosophically and practically inferior to the way it was previously. I just wanted to add this perspective in case it sparks some thought. If there is another intended way to accomplish what I'm trying to do that I've missed, please let me know.

**Comment by hadley** [comment]
Just supply the `destination` in the `override` argument:

```
pkgdowngen () 
{ 
    R --quiet -e "pkgdown::build_site('${HOME}/code/$1', override=list(destination = '/path/to/www/$1'))"
}
```

**Comment by nsheff** [comment]
:+1:  Makes sense, thanks for the pointer.
