### ISSUE TITLE
build in non interactive mode

### ISSUE THREAD

**Issue by merliseclyde** [r-lib/pkgdown#647]
It would be useful for `build_site()` to have the option to run  in a non-interactive R mode but in the terminal.   Currently, example code that creates multiple plots where the default in the code is ask=TRUE or shiny apps that should run only if in an interactive environment. i.e.

``` r
if (interactive()) run_my_shiny_app()
```

wait for user input.   In the case of plots, the build continues  (love having the plots in the example output!!!), however with shiny apps, the build stops and no additional Rd files are processed.  The shiny apps could be added to a `\dontrun` block, but I am currently being asked to use `\donttest` rather than `\dontrun` for submission to CRAN.   Testing for an interactive environment would avoid using either `\dontrun` or `\donttest` with the function documentation avoiding the confusing # NOT RUN wrapper).

**Comment by hadley** [comment]
This is the point of the RStudio add-in, which runs in a separate process. Maybe this should be an exported function?

**Comment by merliseclyde** [comment]
Thanks that works -  did not realize that the  add-in would run in non-interactive mode.  Exporting or documenting would be nice.  Thanks!
