### ISSUE TITLE
Feature Request for Automatic Sectioning in References

### ISSUE THREAD

**Issue by merliseclyde** [r-lib/pkgdown#648]
Would it be possible to use the @concepts tags in roxygen2 documentation (or something comparable) to group functions together in the reference section under headings?  (which is completely manual as far as I can tell now)

Ideally by default all functions and all concepts with the concept being used as the section header/title by default would be listed, but perhaps the _pkgdown.yml file  could allow users to specify which concepts (and with alternative titles)  would appear to provide a more automatic grouping of similar functions with less manual editing when new functions are added.

**Comment by hadley** [comment]
I thought about this, but I couldn't see how you'd control the ordering within the concept, or how you'd control the ordering of concepts, or how you'd add a description to a concept.
