### ISSUE TITLE
Site title instead of package name in navbar

### ISSUE THREAD

**Issue by Enchufa2** [r-lib/pkgdown#654]
Shouldn't [this](https://github.com/r-lib/pkgdown/blob/master/inst/templates/navbar.html#L11) be `{{#site}}{{title}}{{/site}}` instead of `{{#package}}{{name}}{{/package}}`?

Also it would be nice to be able to turn off the `version_label` under the `development` YAML setting with the default template. Would you consider a PR implementing this?

**Comment by Enchufa2** [comment]
What about the `version_label` in the navbar? Would you consider implementing a YAML setting to switch it off without changing the default template?

**Comment by hadley** [comment]
Please file one issue per issue.
