### ISSUE TITLE
latex formatting used for title instead of plain version when generating JSS article

### ISSUE THREAD

**Issue by jackwasey** [r-lib/pkgdown#658]
The JSS article template provides for YAML like:
```
title:
 formatted: \latex \pkg{pkgdown} stuff
 plain: latex pkgdown stuff
```

but pkgdown uses the formatted version in the index, but I believe should choose the plain version.

A work-around is to put the plain sub-item first:
```
title:
 plain: latex pkgdown stuff
 formatted: \latex \pkg{pkgdown} stuff
```

**Comment by Enchufa2** [comment]
The sub-item "plain" is specific of that type of article. Other types of articles may have other sub-item names, and thus it is probably not worth it to support specific sub-item names; especially given that the workaround is pretty straightforward.
