### ISSUE TITLE
News section lists latest version as unreleased

### ISSUE THREAD

**Issue by hrecht** [r-lib/pkgdown#661]
Hello, my pkgdown site is showing the latest version as unreleased, though it's released on both Github and CRAN. The other release dates seem to be coming in from CRAN maybe?
I haven't been able to find a way to update this - not sure if it's a bug or I'm missing a step. Any ideas?
https://hrecht.github.io/censusapi/news/index.html

_pkgdown.yaml for this is at https://github.com/hrecht/censusapi/blob/master/_pkgdown.yaml

**Comment by jayhesselberth** [comment]
Can you install dev pkgdown and rebuild? I just rebuilt your news locally and the date is filled in correctly.

**Comment by hrecht** [comment]
Will do! I last tried this with a pre-CRAN version too.
