### ISSUE TITLE
extend copy-to-clipboard to all source code?

### ISSUE THREAD

**Issue by ijlyttle** [r-lib/pkgdown#665]
This could be useful for articles, README, etc.

If you would like a PR, I would propose to add `div.sourceCode` to  [this line](https://github.com/r-lib/pkgdown/blob/90867f97221e9bd1c7a997f870eff28eb1083411/docs/pkgdown.js#L115) to read:

```js
    $(".examples, div.sourceCode").addClass("hasCopyButton");
```

This seems to work in my implementation.

**Comment by hadley** [comment]
PR would be great please!
