### ISSUE TITLE
Better heuristics for finding badges

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgdown#670]
Would be nice. I like to put a title and/or a logo at the beginning of the README and then pkgdown does not find the badges. E.g.:

```
# processx

> Execute and Control System Processes

[![lifecycle](https://img.shields.io/badge/lifecycle-maturing-blue.svg)](https://tidyverse.org/lifecycle/#maturing)
...
```

```
<h1 align="center">
    <br>
    <br>
    <img width="400" src="./inst/logo.png" alt="crayon">
    <br>
    <br>
    <br>
</h1>

> Stylish terminal output in R

[![Project Status: Active - The project has reached a stable, usable state and is being actively developed.](http://www.repostatus.org/badges/latest/active.svg)](http://www.repostatus.org/#active)
...
```

**Comment by gaborcsardi** [comment]
Or maybe allow marking the badges, e.g. putting them in a `div`:
```
<div id="badges">
  ...  
</div>
```

**Comment by hadley** [comment]
This approach doesn't work with gfm, so we'll need to try again in the next release.

**Comment by maelle** [comment]
I've had the issue again, on a package of @gaborcsardi's of course. :joy_cat: 

These days, if created with `usethis` a README has `<!-- badges: start -->` comments, that are in the html too. [On the README I'm looking at](https://github.com/r-hub/rhub/blob/master/README.md) I can extract the right paragraph with `xml2::xml_find_all(html, ".//*/comment()/following-sibling::p[1]")` but this might not be specific enough (it could be any paragraph after a comment) and I'm not good enough at XPath to find a good solution quickly. If no one else is, I can dig further.

**Comment by maelle** [comment]
Other example of a package where the badges paragraph isn't the first one
https://github.com/ropensci/qualtRics/blob/master/README.Rmd
https://ropensci.github.io/qualtRics/

I can work on a PR + better XPath query (and with a mention somewhere in the docs of `build_home()` of the tip to use the `<!-- badges: start -->` stuff) if that's of interest.

**Comment by hadley** [comment]
@maelle that would be great!
