### ISSUE TITLE
Error from build_articles() for package xtractomatic

### ISSUE THREAD

**Issue by rmendels** [r-lib/pkgdown#671]
I have successfully used pkgdown for a package I have under development, `rerddapXtracto` ( https://github.com/rmendels/rerddapXtracto )  but it fails trying to build my package `xtractomatic` which is both in CRAN and on Github at https://github.com/rmendels/xtractomatic .  If I use the command pkgdown::build_site() it fails on building the Vignette with  error:

Error in file.rename(from, to) : 
  (converted from warning) cannot rename file '/Users/rmendels/Workfiles/xtractomatic/docs/articles/Usingxtractomatic_files/figure-html' to '/private/var/folders/46/jyz1mm5x5bvbf59b5g8f7f580000gn/T/RtmpzBH0CO//Users/rmendels/Workfiles/xtractomatic/docs/articles/Usingxtractomatic_files/figure-html', reason 'No such file or directory'

I have also tried pkgdown::build_articles(quiet = FALSE).  It makes it all the way through the Vignette,  and then fails with essentially the same error.

**Comment by jayhesselberth** [comment]
This vignette is too long to debug effectively. Can you isolate the problem by deleting chunks a few at a time?

**Comment by rmendels** [comment]
Thanks for looking at this.  I may not be able to get to this till next week sometime.  Any suspicions on causes - sort of a guide on what chunks to remove first?

**Comment by jayhesselberth** [comment]
I suggest being draconian. Delete the the first half of the document, then the second. Repeat until you get to the offending chunk(s).

**Comment by rmendels** [comment]
Okay it is some interplay with ggplot2.  I have attached a greatly reduced vignette.  It fails with the same error messages.  However,  do the following:

1.  First run it outside of `build_site()` to see that it works.
2. Change the final code chunk so that the graph is calculated but not actually displayed,  run `build-site()` - it will work
3.  Change it so the graph is displayed.  `build_site()` fails


[Usingxtractomatic.Rmd.txt](https://github.com/r-lib/pkgdown/files/2526179/Usingxtractomatic.Rmd.txt)

**Comment by rmendels** [comment]
My apologies,  I believe I may have attached the wrong file.  The shortened version is attached.

[build_site_example.Rmd.txt](https://github.com/r-lib/pkgdown/files/2526192/build_site_example.Rmd.txt)

**Comment by rmendels** [comment]
And I should add that it is not just the one example.  The same issue happens with just about all of the other plots,  I can boil it down to almost any one of the plots and still produce the error.

**Comment by hadley** [comment]
Can you please create a minimal reprex package as described at https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md#package-reprexes? Without that, it's extremely unlikely that we will be able to locate and fix the problem.

**Comment by hadley** [comment]
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.
