### ISSUE TITLE
pkgdown does not create correct Umlauts from CITATION file

### ISSUE THREAD

**Issue by strengejacke** [r-lib/pkgdown#672]
while my family name (Lüdecke) is correctly shown accross my pkgdown sites, the _authors.html_ file does not properly render the `ü`:

```
    <p>LÃ¼decke D (2018).
<em>sjlabelled: Labelled Data Utility Functions</em>.
R package version 1.0.10, <a href="https://CRAN.R-project.org/package=sjlabelled">https://CRAN.R-project.org/package=sjlabelled</a>. 
</p>
    <pre>@Manual{,
  title = {sjlabelled: Labelled Data Utility Functions},
  author = {Daniel Lüdecke},
  year = {2018},
  note = {R package version 1.0.10},
  url = {https://CRAN.R-project.org/package=sjlabelled},
}</pre>
```

Not sure why.

**Comment by batpigandme** [comment]
Hi Daniel,

I just rebuilt the site with the dev versions of pkgdown and sjlabelled and it looks like things rendered correctly; would you be willing to give it another go?
```html
 <h1>Citation</h1>
    </div>

    <p>Lüdecke D (2018).
<em>sjlabelled: Labelled Data Utility Functions (Version 1.0.10)</em>.
doi: <a href="http://doi.org/10.5281/zenodo.1249216">10.5281/zenodo.1249216</a>, <a href="https://CRAN.R-project.org/package=sjlabelled">https://CRAN.R-project.org/package=sjlabelled</a>. 
</p>
    <pre>@Manual{,
  title = {sjlabelled: Labelled Data Utility Functions (Version 1.0.10)},
  author = {Daniel Lüdecke},
  year = {2018},
  url = {https://CRAN.R-project.org/package=sjlabelled},
  doi = {10.5281/zenodo.1249216},
}</pre>
```
![image](https://user-images.githubusercontent.com/831732/40268594-938da02e-5b3e-11e8-8078-25ff20c3be0e.png)

[_n.b._ I collapsed some of the vertical whitespace in the screenshot, but haven't changed any text.]

**Comment by strengejacke** [comment]
I just installed the current GitHub-version of _pkgdown_, but the issue remains. Here's the snippet from _authors.html_ (from another package):

```
<p>LÃ¼decke D (2018).
```

The CITATION file looks like this:

```
year <- sub("-.*", "", meta$Date)
note <- sprintf("R package version %s", meta$Version)

bibentry(bibtype="manual",
         title = "sjstats: Statistical Functions for Regression Models",
         author = person("Daniel", "Lüdecke"),
         year = year,
         note = note,
         url = "https://CRAN.R-project.org/package=sjstats")
```

Could it be an encoding-issue for Windows users?

**Comment by batpigandme** [comment]
It must be, because I just built that site, and it worked fine, too
![image](https://user-images.githubusercontent.com/831732/40270770-077b0ae0-5b61-11e8-871c-e5d1a47a3c54.png)
```html
      <h1>Citation</h1>
    </div>

    <p>Lüdecke D (2018).
<em>sjstats: Statistical Functions for Regression Models</em>.
R package version 0.14.3.9000, <a href="https://CRAN.R-project.org/package=sjstats">https://CRAN.R-project.org/package=sjstats</a>. 
</p>
    <pre>@Manual{,
  title = {sjstats: Statistical Functions for Regression Models},
  author = {Daniel Lüdecke},
  year = {2018},
  note = {R package version 0.14.3.9000},
  url = {https://CRAN.R-project.org/package=sjstats},
}</pre>
```

**Comment by strengejacke** [comment]
Do you get the information from two different sources, that (in my example) the `ü` is not correctly printed in the reference paragraph, but correctly in the bibtex-code?

**Comment by hadley** [comment]
Most likely explanation for difference is that @strengejacke uses windows.

**Comment by WastlM** [comment]
This issue is what I tried to highlight here: https://github.com/r-lib/pkgdown/pull/515#issuecomment-368486214

**Comment by hadley** [comment]
`read.dcf()` source code: [R](https://github.com/wch/r-source/blob/0b3d7724d214b2e1c05dab6b3457934e740170a1/src/library/base/R/dcf.R#L19) and [C](https://github.com/wch/r-source/blob/0b3d7724d214b2e1c05dab6b3457934e740170a1/src/main/dcf.c#L69). I don't see "Encoding" in either file.

That suggests that this documentation is describing something that we can do, not that `read.dcf()` already does:

> Note that read.dcf(all = FALSE) reads the file byte-by-byte. This allows a ‘DESCRIPTION’ file to be read and only its ASCII fields used, or its Encoding field used to re-encode the remaining fields.

**Comment by hadley** [comment]
@strengejacke @WastlM can you please try out #679 and see if it fixes the problem?

**Comment by strengejacke** [comment]
No, unfortunately not... I installed the repo using `devtools::install_github("r-lib/pkgdown", ref = "encode-desc")`, deleted the _authors.html_ and rebuilt the site.

Output is still:

```
    <p>LÃ¼decke D (2018).
<em>ggeffects: Create Tidy Data Frames of Marginal Effects for 'ggplot' from Model Outputs (Version 0.3.3.9000)</em>.
doi: <a href="http://doi.org/10.5281/zenodo.1249196">10.5281/zenodo.1249196</a>, <a href="https://CRAN.R-project.org/package=ggeffects">https://CRAN.R-project.org/package=ggeffects</a>. 
</p>
    <pre>@Manual{,
  title = {ggeffects: Create Tidy Data Frames of Marginal Effects for 'ggplot' from Model Outputs (Version 0.3.3.9000)},
  author = {Daniel Lüdecke},
  year = {2018},
  url = {https://CRAN.R-project.org/package=ggeffects},
  doi = {10.5281/zenodo.1249196},
}</pre>
```

**Comment by WastlM** [comment]
Sorry, I was confused. The issue I had in mind appears if the CITATION file contains `citation(auto = meta)` *and* the package uses a character encoding different from the native encoding, see my PR #689.

It seems that the lack of re-encoding in `create_meta()` was not causing the problem @strengejacke reports (which I cannot reproduce, probably because I'm using Linux).

**Comment by hadley** [comment]
Gist that might be helpful for testing — https://gist.github.com/wch/3a629cfe575846a14207 — gives non-UTF8 locale that should work on mac/linux.

**Comment by strengejacke** [comment]
You're right:

```r
cit <- citation("sjlabelled")
format(cit, style = "html")
#> [1] "<p>LÃ¼decke D (2018).\n<em>sjlabelled: Labelled Data Utility Functions (Version 1.0.10)</em>.\ndoi: <a href=\"http://doi.org/10.5281/zenodo.1249216\">10.5281/zenodo.1249216</a>, <a href=\"https://CRAN.R-project.org/package=sjlabelled\">https://CRAN.R-project.org/package=sjlabelled</a>. \n</p>"
```

**Comment by strengejacke** [comment]
So should I still try out https://github.com/r-lib/pkgdown/pull/689 ?

**Comment by jayhesselberth** [comment]
@strengejacke Can you confirm whether the changes in the dev version of pkgdown (which incorporate #692) fix this issue?

If not, it might be a bug in R on windows, or possibly another encoding corner-case in pkgdown.

**Comment by strengejacke** [comment]
I just installed the master-branch from GitHub, deleted an author.html file and rebuild with `build_home()`. Unfortunately, the issue still exists.

**Comment by jayhesselberth** [comment]
Can you try this?

```r
cit <- citation("sjlabelled", auto = meta)
format(cit, style = "html")
```

**Comment by strengejacke** [comment]
> Error in citation("sjlabelled", auto = meta) : object 'meta' not found

**Comment by jayhesselberth** [comment]
Try adding `citation(auto = meta)` to the bottom of your CITATION file like this:

https://github.com/r-lib/pkgdown/blob/master/tests/testthat/assets/site-citation/encoding-latin1/inst/CITATION

Re-install the package, then run:

```r
cit <- citation("sjlabelled")
format(cit, style = "html")
```

**Comment by strengejacke** [comment]
CITATION file

```
citEntry(entry = "manual",
         title="sjlabelled: Labelled Data Utility Functions.",
         author = "Daniel Lüdecke",
         year = 2018,
         url = "https://CRAN.R-project.org/package=sjlabelled",
         doi = "10.5281/zenodo.1249216",
         textVersion="test"
         )

citation(auto = meta)
```

Result:
```r
library(sjlabelled)
cit <- citation("sjlabelled")
format(cit, style = "html")
#> [1] "<p>LÃ¼decke D (2018).\n<em>sjlabelled: Labelled Data Utility Functions.</em>.\ndoi: <a href=\"http://doi.org/10.5281/zenodo.1249216\">10.5281/zenodo.1249216</a>, <a href=\"https://CRAN.R-project.org/package=sjlabelled\">https://CRAN.R-project.org/package=sjlabelled</a>. \n</p>"
#> [2] "<p>L&lt;U+663C&gt;&lt;U+3E63&gt;decke D (2018).\n<em>sjlabelled: Labelled Data Utility Functions</em>.\nR package version 1.0.10.9000, <a href=\"https://github.com/strengejacke/sjlabelled\">https://github.com/strengejacke/sjlabelled</a>. \n</p>" 
```

**Comment by jayhesselberth** [comment]
Hmm. The only other thing I can think to do on the pkgdown side is to write a re-encoded CITATION file from `inst/CITATION` to `docs/CITATION` and try using that during site build. But I'm not sure what problem that is fixing and in any case it seems likely we covered that problem in these other approaches.

**Comment by strengejacke** [comment]
The CITATION file is already UTF-8 encoded.
![citatoin-utf8](https://user-images.githubusercontent.com/26301769/40783898-2eb5ef12-64e4-11e8-994d-15aeb99d0296.png)

However, when I change the encoding to Windows-1252 or ISO-8859-1, the Ü is converted:
![citation-win1252](https://user-images.githubusercontent.com/26301769/40783930-46d8c33a-64e4-11e8-8bc5-11452b95c254.png)

So. I'm not sure, either, that copying the CITATION file would help. You may need to write your own parser for the CITATION file ;-)

Probably you can close this issue, if it's not related to pkgdown.
