### ISSUE TITLE
Re-enable algolia logo

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#673]
e.g. https://github.com/r-lib/pkgdown/blob/5eeb2aab0b68924bcde72ded0f7326070eaa0fa0/docs/docsearch.css#L125

This should never have been disabled.

**Comment by hadley** [comment]
@jayhesselberth could you have a look at this? Simply removing this block causes a different problem

**Comment by jayhesselberth** [comment]
Not sure why the logo went away, wasn't intentional. Getting it back and displaying correctly is fiddly.

The link to algolia remains at the bottom of the search results, is there a reason we need the logo *per se*?

**Comment by hadley** [comment]
It's required as part of algolia's attribution requirements.
