### ISSUE TITLE
replay_html has problems when dealing with user defined S3 classes in @examples

### ISSUE THREAD

**Issue by s-fleck** [r-lib/pkgdown#677]
It is a bit hard for me to provide a reprex, but I will try to describe the problem as accurately as possible.
It seems rather simple anyways.

I am working on a package that deals with year-quarter dates. I have a roxygen block like this, where `date_y()` is a constructor for a custom s3 class for years:

```
#' [...]
#' @examples
#' date_y(2013)
```
If I run pkgdown::build_site (dev version, ‘1.0.0.9000’) I get:
```
Error in UseMethod("replay_html", x) : 
  no applicable method for 'replay_html' applied to an object of class "c('date_y', 'date_xx', 'integer')"
```

I do have proper `format()` and `print()` methods defined for `date_y` Objects. The problem described above does not occur if I change my @example to:
```
#' [...]
#' @examples
#' as.character(date_y(2013))
```

I havent looked to much in the internals of pkgdown, but maybe it makes sense to define a `replay_html.default()` like `replay_html.character(format(x))` or `replay_html.character(capture.output(print(x)))`?

**Comment by s-fleck** [comment]
If you require a reproducible example to play around with, you can just clone https://github.com/s-fleck/dint. The package is rather small and simple an has not dependencies.

**Comment by hadley** [comment]
I think there's a deeper problem because it should be `replay_html.value` that handles this scenario - `replay_html()` should never get called directly on your object.

**Comment by hadley** [comment]
Hmmmm, it works just fine for me. Can you please show me exactly what code you're running to build the package, and give me a `traceback()` from the error?

**Comment by hadley** [comment]
(PS. I think it's bad practice to omit the generated `.Rd` files from the repository)

**Comment by s-fleck** [comment]
Apparently I changed something in the repository that fixed the issue between filing this bug and you checking it out. I could not figure out what that was, as I made little significant changes to the markdown.

The last commit where the error occured is: 3160e76a
The first commit where it does not occur is: c38f1f4f

Here is the Traceback

```
Error in UseMethod("replay_html", x) : 
  no applicable method for 'replay_html' applied to an object of class "c('date_y', 'date_xx', 'integer')"
> traceback()
14: replay_html(parts[[i]], ...)
13: replay_html.list(expr, topic = topic, obj_id = obj_id)
12: replay_html(expr, topic = topic, obj_id = obj_id)
11: .f(code = .l[[c(1L, 1L)]], run = .l[[c(2L, 1L)]], show = .l[[c(3L, 
        1L)]], ...)
10: .Call(pmap_impl, environment(), ".l", ".f", "character")
9: purrr::pmap_chr(list(code = code, run = run, show = show), format_example_chunk, 
       env = child_env(env), topic = topic, obj_id = id_generator$id)
8: as_data.tag_examples(tags$tag_examples[[1]], env = new.env(parent = globalenv()), 
       topic = tools::file_path_sans_ext(topic$file_in), examples = examples, 
       run_dont_run = run_dont_run)
7: as_data(tags$tag_examples[[1]], env = new.env(parent = globalenv()), 
       topic = tools::file_path_sans_ext(topic$file_in), examples = examples, 
       run_dont_run = run_dont_run)
6: data_reference_topic(topic, pkg, examples = examples, run_dont_run = run_dont_run, 
       mathjax = mathjax)
5: .f(.x[[i]], ...)
4: .Call(map_impl, environment(), ".x", ".f", "list")
3: purrr::map(topics, build_reference_topic, pkg = pkg, lazy = lazy, 
       examples = examples, run_dont_run = run_dont_run, mathjax = mathjax)
2: build_reference(pkg, lazy = lazy, examples = examples, run_dont_run = run_dont_run, 
       mathjax = mathjax, seed = seed, override = override, preview = FALSE)
1: pkgdown::build_site()

```

I made a branch to strip the package down to the minimal possible version where the bug still occurs:

https://github.com/s-fleck/dint/tree/test

**Comment by s-fleck** [comment]
Hmm now I can't reproduce the bug for the commits I mentioned, but for some older commits it still exists. I am sorry, but it seems quite hard to pinpoint why and how this happens.

Maybe this helps>

For the cases where `build_site()` fails, the line `expr <- evaluate::evaluate(code, env, new_device = TRUE)` in `format_example_chunk()` returns a list that contains some elements that are of my custom s3 class (`date_xx`), while for cases where `build_site()` succeeds, `expr` is a list that only contains character and source elements.

I am not sure what `evaluate()` is supposed to return, as I have not worked with that package before.

**Comment by jayhesselberth** [comment]
Closing for now. If the issue persists could you please build a [minimal package](https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md) that recreates the issue?

**Comment by s-fleck** [comment]
I was not able to pinpoint the issue. It persisted in some version of the package but not in others, without any changes in between that had much to do with the roxygen. Maybe it was just a weird combination of several unfortunate circumstances.

**Comment by s-fleck** [comment]
The problem occurred again to me today, after more than one year of not encountering the issue and for a different package. I am using the most recent github version of pkgdown (1.3.0.9100). I am not reopening the issue because I still can't produce a reprex.

```
Error in UseMethod("replay_html", x) : 
  no applicable method for 'replay_html' applied to an object of class "c('logger_tree', 'data.frame')"
```

The traceback is not really helpful:

```
5: stop(err[[2]])
4: get_result(output = out, options)
3: callr::r(function(..., crayon_enabled, crayon_colors, pkgdown_internet) {
       options(crayon.enabled = crayon_enabled, crayon.colors = crayon_colors, 
           pkgdown.internet = pkgdown_internet)
       pkgdown::build_site(...)
   }, args = args, show = TRUE, timeout = getOption("pkgdown.timeout", 
       Inf))
2: build_site_external(pkg = pkg, examples = examples, run_dont_run = run_dont_run, 
       seed = seed, lazy = lazy, override = override, preview = preview, 
       devel = devel)
1: pkgdown::build_site()
```
 
Here is a direct link to the package at the commit that caused the problem:
https://github.com/s-fleck/lgr/commit/54218c6c731e0946b75a958d02705f30d5c3f10e

When I posted this comment originally, other people were not able to reproduce my problem with the package in question. For me at least the problem persists across two different systems (both ubuntu, one with R 3.5.2 and one with R 3.6.0).

**Comment by s-fleck** [comment]
It seems implementing a `format()` method for the object fixed the problem. Before it only had a `print()` method (that returned the original object invisibly) but not a `format()` method.

**Comment by cpsievert** [comment]
Thanks @s-fleck, add a `format()` method in my case doesn't appear to fix the problem.

**Comment by ngreifer** [comment]
I was having this same problem with my package `MatchingFrontier` when trying to build the website from a [GitHub action](https://github.com/ngreifer/MatchingFrontier/runs/4050686791) that calls `pkgdown`. I also have a custom-classed object that seems to be causing the problem. I managed to fix it by ensuring my `print()` method for the object *invisibly* returned the object (i.e., using `return(invisible(x))` instead of `return(x)`). Not sure if this helps anyone.

**Comment by sorhawell** [comment]
I had the same issue as described here on some very customized S3-classed. For me @ngreifer simple suggestion did the trick. To spell it out, a corrected print method could like this: 

```
#' Print mys3class
#'
#' @param x mys3class
#'
#' @return invis selfie
#' @export
#'
print.mys3class = function(x) {
  cat("mys3class: ")
  #some code to print your s3 class could be added here
  invisible(x)
}
```
