### ISSUE TITLE
message if README.md is out of date

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#685]
Now that pkgdown doesn't render README.md from README.Rmd, I am constantly forgetting to do that.

Would it be useful to generate a message at the end of `pkgdown::build_site()` as a reminder to re-render README.R/md if it is out of date?

**Comment by hadley** [comment]
I was thinking maybe document() should handle this (and also handle installing your package into a temporary library) 

Cc @jennybc

**Comment by jennybc** [comment]
The matching issue in devtools: https://github.com/r-lib/devtools/issues/1762
