### ISSUE TITLE
Rmd output svg does interfere with default png extension

### ISSUE THREAD

**Issue by jakob-r** [r-lib/pkgdown#693]
I used the following to create svg files for my pkgdown sites:
```

---
output:
  html_document:
    dev: svg
---

\```{r setup}
knitr::opts_chunk$set(dev = "svg")
\```
```
It worked with the previus versions but now all files are saved with the ending png which results in unrendered graphics. 
I found out that I can change the defaults in `_pkgdown.yml` but it would be more convinient to have individual settings as some plots tend to be too big as svgs but in general svg seem preferable.

**Comment by jayhesselberth** [comment]
See previous comments in #563

**Comment by hadley** [comment]
This problem is easy to work around: just also set `fig.ext = "svg"`  (I feel like you maybe do need to do this normally, but using `.png` isn't a problem until you're actually serving files over the internet)
