### ISSUE TITLE
Any way to silence the non-standard file/directory found at top level warning?

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/pkgdown#709]
Hi,

I've just tested out pkgdown::build_site() and it does a beautiful job rendering the website for my package.

However, is there a way to then prevent the subsequent note in R CMD Check of having a non-standard file/directory at the top level (docs)? I totally understand why the warning is there - because it's not routinely expected to have a docs directory - but presumably there must be some way to silence this and get a 'clean' check? Are there any other recommended workarounds?

**Comment by jayhesselberth** [comment]
You need to build-ignore the docs directory.

See https://github.com/r-lib/pkgdown/blob/master/.Rbuildignore

[`usethis::use_pkgdown`](http://usethis.r-lib.org/reference/use_pkgdown.html) does this for you automatically.

**Comment by md0u80c9** [comment]
Aha - thanks for that. I thought there would be some way.

Could this be mentioned as part of the 'Get Started' on:

http://pkgdown.r-lib.org/articles/pkgdown.html ?

Best wishes,

Andrew

**Comment by rcorty** [comment]
Not sure if I've done something wrong, but after I run `pkgdown::build_favicons()` then `devtools::check` I'm getting this NOTE:  Non-standard file/directory found at top level: ‘pkgdown’.

Looks like `pkgdown::build_favicons()` creates a directory called `pkgdown` and a subdirectory of that called `favicon` and puts all the icons in there.   Maybe I should add that path to `.Rbuildignore`.  Or maybe the favicons should be saved somewhere else.  Not too sure.

**Comment by jayhesselberth** [comment]
Yes you need to add the `pkgdown` directory to `.Rbuildignore`.
