### ISSUE TITLE
Configurable author types on home page

### ISSUE THREAD

**Issue by md0u80c9** [r-lib/pkgdown#711]
Hi,

I've got a list of 5 team members for my R package: (https://ssnap.github.io/SSNAPInterface/index.html - the package is currently private pending approval from the project funders to release into the public domain, but the intent is to publish the source under a Mozilla license).

As can be seen, at the moment this is automatically converted into a link. However, it would naturally appear better if the authors were all on the one page. Is there a way to force-configure this?

**Comment by jayhesselberth** [comment]
If they are authors then you can just add the `aut` type to their entries in the DESCRIPTION.

Only `aut`, `cph`, and `fnd` types are displayed on the home page.

**Comment by md0u80c9** [comment]
Fab - thankyou for this! Pkgdown is really awesome - amazing how quickly you can build very professional-looking documentation from within the R package with it!

Also thankyou so much for your replies this morning - you'll see I've been able to use them to update my package documentation layout considerably!

Could you consider in a future release allowing those types to be configurable somewhere (_pkgdown.yml being the obvious place)? For example in our case our research director isn't an 'author' per se, but the series of packages plays a very integral part in accessing the UK national stroke database for research purposes, so his role (and contact details) is important because it influences what should be in the datasets and some of the strategic direction. It would be useful if this was in the to-do list for documentation too (I appreciate that the package is really early in its lifecycle - though it does do very cool things despite being freshly released!)

**Comment by jayhesselberth** [comment]
I think it's better to leave this with only aut, cre, fnd on the home page. Any others will end up on authors.html.
