### ISSUE TITLE
Access pkgdown search stats

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#722]
@s-pace is it possible to access pkgdown Docsearch search stats through the Algolia dashboard?

**Comment by s-pace** [comment]
👋 @jayhesselberth 

Yes it is possible. I have grant you access to your algolia account (gmail).

Feel free to send us the emails of the people you want to grant access via the first thread we have used (when you apply for DocSearch)

**Comment by jayhesselberth** [comment]
@hadley You should have received an email from Sylvain when you first requested that pkgdown be setup on Docsearch. Try searching for "documentationsearch@algolia.com" in gmail. It's an email with the subject "Help me improve my documentation search".

Can you reply to that email asking that our gmail addresses be added for Algolia dashboard access?

**Comment by s-pace** [comment]
@jayhesselberth I have actually added your gmail email address

I will add @hadley 's one too

**Comment by jayhesselberth** [comment]
Great, thanks for adding! I can see it in my dashboard.
