### ISSUE TITLE
Set up Google Analytics for pkgdown

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#723]
@batpigandme can help

**Comment by batpigandme** [comment]
Related: https://github.com/r-lib/pkgdown/pull/717#issuecomment-395260711
(For self reference!)

**Comment by batpigandme** [comment]
@hadley I need access for r-lib.org (the others we have setup are tidyverse.org-based)

**Comment by batpigandme** [comment]
^^ disregard – I forgot about GH pages (>ლ)

**Comment by jayhesselberth** [comment]
Is this feasible? Otherwise will close.

**Comment by batpigandme** [comment]
Oh, shoot! Yes, I just forgot. Will work on today.
