### ISSUE TITLE
appveyor weirdness

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#726]
Following up on #724, appveyor is behaving strangely.

After adding appveyor.yml etc to master, I can trigger pkgdown builds and they are clean (after getting rid of BiocInstaller in bcf6299).

But the recently-triggered builds only appear in my own appveyor project list, not r-lib's.

https://ci.appveyor.com/project/jayhesselberth/pkgdown-9bbhc
https://ci.appveyor.com/project/r-lib/pkgdown

Is this the weirdness that was previously mentioned?

I can delete the projects from my own appveyor account and see if that helps.

@jennybc Can you trigger a pkgdown build from r-lib appveyor and see if it syncs up?

Edit: the appveyor badge on the README currently says "pass", but if you click it, it goes to the failed build mentioned above.

**Comment by jayhesselberth** [comment]
I deleted my pkgdown projects from appveyor. The link above no longer works, but last build passed.

Will see if the next commits to pkgdown master trigger an appveyor build.

**Comment by jayhesselberth** [comment]
The most recent commit was either picked up automatically, or @jennybc kicked it off, or some other weird thing happened. In any case appveyor is now be building r-lib/pkgdown, and does so with passing status.

**Comment by jennybc** [comment]
It's not entirely clear which of the "fixes" actually made things work but let us just be glad it is working now.
