### ISSUE TITLE
Strip fragment off GitHub URL before appending to it

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#733]
If a package has a GitHub URL like so: <https://github.com/tidyverse/reprex#readme> (note the trailing `#readme`), it creates dysfunctional links in pkgdown.

For example the `Source: R/reprex.R` link here:
<http://reprex.tidyverse.org/reference/reprex.html>
links to
<https://github.com/tidyverse/reprex#readme/blob/master/R/reprex.R>
which doesn't resolve and redirects to the top level of the repo.

This same problem is solved in usethis here:
https://github.com/r-lib/usethis/blob/3cc50ae7c4877d5f10747d0e8f25469897206cfe/R/browse.R#L93-L115

If we ever create [a package to parse Git remote URLs](https://github.com/r-lib/ghurl/issues), we'd be able to use that.

**Comment by jayhesselberth** [comment]
Need to fix here: https://github.com/r-lib/pkgdown/blob/421296fc500fe9066e75c8b54fe5a8e11862454b/R/github.R#L1-L15
