### ISSUE TITLE
build_site() creates directory _docs/_ despite destination override

### ISSUE THREAD

**Issue by aqualogy** [r-lib/pkgdown#734]
https://github.com/aqualogy/pdtestdestination provides an example package illustrating the issue. During execution of `pkgdown::build_site()` in [_build.R](https://github.com/aqualogy/pdtestdestination/blob/master/_build.R) a directory _docs/_ is created, although a different output directory is specified (_public/R-3.5.0/_). The resulting static html file get stored in the specified directory, the reported **issue** covers simply the creation of an unneeded and unwanted _docs/_ directory.

```
══ Building pkgdown site ═══════════════════════════════════════════════════════
Reading from: '/srv/cifs-mounts/WeberA_home/WeberA/pdtestdestination'
Writing to:   '/srv/cifs-mounts/WeberA_home/WeberA/pdtestdestination/public/R-3.5.0'
── Initialising site ───────────────────────────────────────────────────────────
Writing 'sitemap.xml'
● Edit '_pkgdown.yml'
✔ Creating 'docs/'
── Building home ───────────────────────────────────────────────────────────────
Writing 'index.html'
── Building function reference ─────────────────────────────────────────────────
Updating pdtestdestination documentation
Loading pdtestdestination
Loading pdtestdestination
Reading 'man/df.flys1.Rd'
══ DONE ════════════════════════════════════════════════════════════════════════

```

It would also be nice to have a possibility to clean a custom output destination with an additional _destination_ argument for function `clean_site()`, which would be a feature request on top of the reported issue.

**Comment by aqualogy** [comment]
This issue also adds an unneeded _docs_ entry into `.Rbuildignore`.

**Comment by hadley** [comment]
I think this might be #861/#812
