### ISSUE TITLE
Select color of themes

### ISSUE THREAD

**Issue by koheiw** [r-lib/pkgdown#735]
We have a [pkgdown website with the **readable** theme](https://docs.quanteda.io/), but considering to change the theme to [**simplex**](https://bootswatch.com/simplex/). The theme comes with a red navbar by default, but there is a white variant. Is it possible to specify the color in `_pkgdown.yml`?

**Comment by jayhesselberth** [comment]
Have you tried setting inverse in `_pkgdown.yml`? See the Navbar section of http://pkgdown.r-lib.org/articles/pkgdown.html

```yaml
navbar:
  type: inverse
```
Currently there's no way to set the background color but it would be easy to implement (light/dark/primary).

**Comment by koheiw** [comment]
Thanks for quickly rely. I did use `inverse` but it made anchor texts red when mouseover. Adding an option to choose light/dark/primary would be a great.

**Comment by jayhesselberth** [comment]
Actually changing background color is a bootstrap 4 feature (pkgdown uses BS3).

You can configure link text color etc with custom CSS (http://pkgdown.r-lib.org/reference/init_site.html#custom-css-js)

**Comment by jayhesselberth** [comment]
And the link you posted is for BS4. The BS3 simplex theme is here: https://bootswatch.com/3/simplex/

**Comment by hope-data-science** [comment]
Any updates to set color or themes for the websites??
