### ISSUE TITLE
"highlight" package is orphaned

### ISSUE THREAD

**Issue by jameslamb** [r-lib/pkgdown#743]
Hello,

Are you aware that the `highlight` package ([a pkgdown import](https://github.com/r-lib/pkgdown/blob/master/DESCRIPTION#L30)) is [orphaned on CRAN](https://cran.r-project.org/web/packages/highlight/index.html)? 

Possibly no action required from you, just wanted to be sure you were aware of the risk.

**Comment by cderv** [comment]
Just to add that this has been reported in romainfrancois/highlight#20

**Comment by jameslamb** [comment]
I would take it over if I knew more C++ or could find someone who'd team up with me and help with that stuff.

The process for taking over a package is pretty straightforward.

**Comment by hadley** [comment]
Yes, I'm aware.
