### ISSUE TITLE
preserve custom classes (and other HTML?) in <table>...</table> in articles

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#746]
I ran into some funny/frustrating behavior of `pkgdown::build_article()` today.

I have my own special html5 table, with its own HTML, css and js assets – which all work fine via `htmltools`, and inside a bunch of rmarkdown outputs.

However, when rendered inside a vignette via `pkgdown::build_article()` my HTML goes to hell, because, as it turns out, [`pkgdown:::tweak_tables()`](https://github.com/r-lib/pkgdown/blob/580ec7462d640bc5b6b9a0d7d8ca2b500e602a17/R/html-tweak.R#L70) will **replace all existing classes**, and there seems to be no way to disable this behavior.

So if you add the following plain HTML to some `vignette.Rmd`:

```
<table class="foo">
</table>
```

The class `foo` will disappear in the rendered `vignette.html` and be replaced by a (bootstrappy?) `css = "table"`.

I'm not quite sure what the logic for this is, but I'm guessing streamlining the table layout.

However, sometimes a *custom* table layout (as, perhaps, inside an HTMLWIDGET) should be retained.

**Would it be possible to: *prepend* the css class `table` to any existing classes, rather than just delete it?**

In general, I'm now worried that any of the other `tweak_html()` functions might have such unexpected consequences on custom styling (and js) I might have for htmlwidgets and such.
Are there other potential dangers, and do you have a suggestion for how to avoid them?

Perhaps some special syntax to mark HTML areas as "off limits" to any `tweak_html()`-magic?

**Comment by jayhesselberth** [comment]
Can you confirm whether your tables render correctly if both class `table` and your custom class are present? This is what you suggest, but does it work?

htmlwidgets work fine in the home page and vignettes, but don't work (yet) in Rd examples (#742 WIP)

**Comment by hadley** [comment]
@jayhesselberth is this the reason that DT tables don't look right?

**Comment by maxheld83** [comment]
@jayhesselberth sorry, that was a premature suggestion.
My table does *not* render correctly when `class = "table foo"`.
It even does not render correctly when `class = "foo"`, because either way, existing bootstrap (?) CSS gets in the way.
I suppose I could (should) solve this by redefining all the css properties from bootstrap at play here. (`line-height` seems to be one of them; I never define that, but something in pkgdown does, probably bootstrap).

Even with my minimal css, the table renders fine inside a "normal" `html_document()` vignette. I am guessing this is because the template used there has less invasive css.

@jayhesselberth I have also wrapped my table inside an htmlwidget, and seen the same results, so my guess would be that all htmlwidgets with `<table>` elements may be affected (perhaps very few, if any).

I see now that the deletion of my `foo` class is only part of the problem here.

What would be your general recommendation for making custom elements (such as htmlwidgets) "pkgdown-proof"?

**Comment by jayhesselberth** [comment]
I built a minimal package for debugging htmlwidgets within pkgdown (https://jayhesselberth.github.io/widgetdown/).

Most widgets I have tested work fine in vignettes out of the box. The exception is DT. I can't tell yet whether DT has the same issue you are seeing, but I don't think so because the DT widget is not in a `<table>` per se.

Can you make a PR in that package that incorporates your broken table / widget combo?

My impresseion is that tables in bootstrap3 are notoriously finicky / don't play nice (and this apparently has been specifically improved in BS4).

**Comment by maxheld83** [comment]
thanks a bunch @jayhesselberth. 
Unfortunately, our widget is still in early development and we don't have all dependencies neatly wrapped up yet.

I will put up a PR to widgetdown once we've got our widget a little more stable -> https://github.com/maxheld83/pensieve/issues/394.

In the meantime, would think prepending the `class = "table foo"` rather than replacing `"foo"` might still be worthwhile to you?
I'd be happy to add a PR for that too.

Thanks for the generous work on pkgdown + widgets.

**Comment by maxheld83** [comment]
@jayhesselberth we've now figured out the conflicting css in our case:

- [`pkgdown.css`: `display: block` for *all <table>s](https://github.com/r-lib/pkgdown/blob/64749579060d79269356223c0760fd2d2c728276/inst/assets/pkgdown.css#L153) 
- `bootstrap.css`: as you predicted, some more shenanigans with `border-bottom` and friends.

We've now overwritten both of these with our own css (applied very narrowly only to our elements), and everything looks fine.

The *deletion* of our class from the table is now our only problem.

**And, as you asked, `class = "table foo"` now actually works**.
So it'd be great if pkgdown could, in fact, *prepend* its `.table` class, instead of replacing whatever it finds.

I'd be happy to add a PR to that effect and this issue can be closed.

**Comment by jayhesselberth** [comment]
Can you provide a PR? I think this should only require changes to how existing classes and handled in `tweak_tables`](https://github.com/r-lib/pkgdown/blob/master/R/html-tweak.R#L70-L76).
