### ISSUE TITLE
more narrowly select <table> elements in pkgdown

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#748]
this is well beyond my css paygrade, but we had table markup which conflicted with [`pkgdown.css`: `display: block` for *all* `<table>`s](https://github.com/r-lib/pkgdown/blob/64749579060d79269356223c0760fd2d2c728276/inst/assets/pkgdown.css#L153).

We've solved this for us (by overriding `display: table` for our css), but I'm wondering whether the css assignment in `pkgdown.css` could be designed a little more narrowly.

If not, feel free to close.

(this is a separate issue from #746)

**Comment by jayhesselberth** [comment]
Do you have a specific recommendation? pkgdown [supports custom css](http://pkgdown.r-lib.org/reference/init_site.html?q=extra#custom-css-js) wherein you can override the defaults.

**Comment by maxheld83** [comment]
Sorry about the late reply.

I agree that the custom css is a better way to go.
