### ISSUE TITLE
Update docs regarding concepts?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#755]
The docs currently say "Concepts are not currently well-supported by roxygen2, but may be useful if you write Rd files by hand." but with dev `roxygen2` concepts are parsed by, even derived from family tags, and `pkgdown` use of concept tags is fantastic so definitely useful nowadays, thanks for that! 😺  (I've just used dev `roxygen2`  and `pkgdown` to get https://itsalocke.com/optirum/reference/ from a very simple config file https://github.com/lockedata/optiRum/blob/master/_pkgdown.yml)

**Comment by jayhesselberth** [comment]
Will update when new roxygen2 is released.

**Comment by maelle** [comment]
Related to this, would a helper function generating config parts from such tags i.e for all concepts

```r
reference:
- title: tag1
  contents:
  - has_concept("tag1")
- title: tag2
  contents:
- has_concept("tag2")
```

make sense? One could then copy paste it in the actual config file.

**Comment by jayhesselberth** [comment]
I suppose `template_reference()` could be made to write the template for functions by first grouping by family or concept. It would then report functions that aren't in those groups.

```r
# write a template grouped by family
template_reference(family = TRUE)
# write a template grouped by concept
template_reference(concept = TRUE)
```
Is this what you're thinking?

**Comment by maelle** [comment]
Oh this is even better than what I was thinking! 🌟 Reporting functions that aren't in groups would be so useful.

Two questions: 

* Would the template feature function names or `has_concept` commands?

* Reg family vs. concept I thought that this didn't make any difference? In the new `roxygen2` version all family tags in .R get translated to concept tags in .Rd so I tend to see those as equivalent, one should use family tags to get both concepts in .Rd and links between functions in the local documentation I think? But I might be missing something!

**Comment by jayhesselberth** [comment]
Yes I was thinking that `template_reference(concepts = TRUE)` would automatically generate:

```yaml
reference:
- title: concepts
  contents:
  - has_concept("this")
  - has_concept("that")
- title: other
  concepts:
  - other
```
