### ISSUE TITLE
Change "All functions" to "All functions and data"?

### ISSUE THREAD

**Issue by arilamstein** [r-lib/pkgdown#757]
The "reference" section is great because it lists all the functions and data in the package, along with a summary and link to their help file.

However, I noticed that the header text for that section defaults to "All functions". About half the objects in my package are data. I'd like to change this text to say "All functions and data". I can make this change easily enough in the HTML file that pkgdown outputs, but I wonder if:

1. it makes sense for pkgdown to have this text say "All functions and data" by default?
2. Is there an option someone in the R code or yaml file to make this change?That is, is making this change in the output html the best way for me to make this change?

Thanks again for creating such a useful package.

**Comment by jayhesselberth** [comment]
You can create a custom template if you want to change that; this is not particularly well documented but see an example in:

https://github.com/tidyverse/dplyr/blob/master/_pkgdown.yml

which uses the template from:

https://github.com/tidyverse/tidytemplate

A simpler approach is to create a dedicated section for data in your reference index:

``` yaml
reference:
  - title: Functions
    contents:
    - func1
    - func2
  - title: Data
    contents:
    - data1
    - data2
```

**Comment by hadley** [comment]
I don't think it's worth changing the default as it only appears before you customise the reference (which every site should do)

**Comment by raubreywhite** [comment]
> I don't think it's worth changing the default as it only appears before you customise the reference (which every site should do)

Is it possible to have some sort of warning to remind us that we have forgotten to include a function in our customized reference page? Because the benefit of doing it automatically is that you never forget to add a function to the documentation!

**Comment by hadley** [comment]
There already is a warning?
