### ISSUE TITLE
Select topics by keyword

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#760]
Would it make sense for someone else than me to have a helper similar to `has_concept` that'd let me add all datasets in a section of the reference by simply typing something like `has_type("data")` in the config file? Thanks in any case.

**Comment by maelle** [comment]
Thanks! I'm worried that it wouldn't be specific enough because "data" could be a keyword in the doc of a function helping do something with data? And I'm also worried that using keyword means I'd have to write one more line of documentation instead of making the most of what I already have. 😉  But in general a keyword helper would be awesome!

**Comment by hadley** [comment]
The correct keyword is `datasets` which is added automatically by roxygen2, and is reserved for datasets.
