### ISSUE TITLE
not check remote url for pure GitHub package

### ISSUE THREAD

**Issue by dongzhuoer** [r-lib/pkgdown#762]
pkgdwon check remote urls like https://cloud.r-project.org, which makes it convenient to automatically create appropriate urls. But that also brings trouble for pure GitHub package. Although `httr::http_error()` makes it compatible with pure GitHub package, Chinese developers have to access _every_ foreign website with cautions. 

Here is the error message I get with my [rGEO](https://github.com/dongzhuoer/rGEO) package

```
── Building news ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds
Calls: withCallingHandlers ... request_fetch.write_memory -> <Anonymous> -> .handleSimpleError -> h
Execution halted
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds
```

I modified pkgdown's source code, comment out code which access remote url (`repo_link` & `pkg_timeline`), then everything works fine. (Maybe it's a general problem for pure GitHub package, not restricted to Chinese developers.)

**Comment by dongzhuoer** [comment]
I propose to add an option to mark pure GitHub package, and skip all remote url access for it:

`R/build-home-index.R`
```r
repo_link <- memoise(function(pkg) {
  if (is_pure_github()) return(NULL)

  cran_url <- paste0("https://cloud.r-project.org/package=", pkg)
  if (!httr::http_error(cran_url)) {
    return(list(repo = "CRAN", url = cran_url))
  }

  bioconductor always returns a 200 status, redirecting to /removed-packages/
  bioc_url <- paste0("https://www.bioconductor.org/packages/", pkg)
  req <- httr::HEAD(bioc_url)
  if (!httr::http_error(req) && !grepl("removed-packages", req$url)) {
    return(list(repo = "BIOC", url = bioc_url))
  }

  NULL
})
```

`R/build-news.R`
```r
pkg_timeline <- function(package) {
  if (is_pure_github()) return(NULL)

  url <- paste0("http://crandb.r-pkg.org/", package, "/all")

  resp <- httr::GET(url)
  if (httr::http_error(resp)) {
    return(NULL)
  }
  return(NULL)

  content <- httr::content(resp)
  timeline <- content$timeline

  data.frame(
    version = names(timeline),
    date = as.Date(unlist(timeline)),
    stringsAsFactors = FALSE
  )
}
```

**Comment by jayhesselberth** [comment]
What should `is_pure_github()` check for? Something in DESCRIPTION? Or a flag in _pkgdown.yml?

**Comment by jayhesselberth** [comment]
I may have been overthinking this. Perhaps just checking for connectivity to `r-project.org` would suffice without adding additional config options to pkgdown.

This is what [testthat](https://github.com/r-lib/testthat/blob/e7c930ddff1b76a63b06d827b9dc38730572813c/R/skip.R#L107-L113) will do in its next release.

Can you report the output of:

``` r
!is.null(curl::nslookup("r-project.org", error = FALSE))
```

**Comment by dongzhuoer** [comment]
```r
> !is.null(curl::nslookup("r-project.org", error = FALSE))
[1] TRUE

> system.time(!is.null(curl::nslookup("r-project.org", error = FALSE)))
   user  system elapsed 
  0.005   0.003   5.002 
```

**Comment by dongzhuoer** [comment]
From my personal experience, connecting to Internet always cause unexpected trouble, especially when one access foreign website from China. 

If user just don't need that, why would he bother to waste that time (5s isn't a short period) and leave a time bomb? (Of course, I think users would appreciate your efforts for the additional code)

**Comment by dongzhuoer** [comment]
```yml
development:
  remote_only: true
```

the inspiration of `remote_only` comes from `install_remote()`. I guess that name makes sense if one is familiar with the latter.
