### ISSUE TITLE
Link vignettes referred-to from Rd files

### ISSUE THREAD

**Issue by nbenn** [r-lib/pkgdown#772]
Although linking from an Rd file to a vignette is not officially supported, the workaround described [here](https://stackoverflow.com/a/51308071/3855417) works just fine for local docs. Unfortunately things break under pkgdown, as now vignettes are no longer located at `../doc/` but `../articles/`. How about adapting links of the form `../doc/filename.html` to `../articles/filename.html`?

**Comment by jayhesselberth** [comment]
A better approach would be to identify referred-to vignettes in Rd files (`vignette("moreinfo")`) and link to them under `articles/`.

**Comment by nbenn** [comment]
If I refer to the vignette as `\href{../doc/moreinfo.html}{\code{vignette("moreinfo")}}`, would your approach accommodate this as well? Or can I then not use a link for local docs, but only refer to the vignette as `\code{vignette("moreinfo")}`?

**Comment by hadley** [comment]
I don't think the hack described in the SO answer is a good idea, and I don't think pkgdown needs to support it.
