### ISSUE TITLE
Option to disable internet connections

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#773]
pkgdown connects to CRAN during the build process to check for:

- the package's existence there (https://github.com/r-lib/pkgdown/blob/master/R/build-home-index.R#L76)
- the package's release timeline (https://github.com/r-lib/pkgdown/blob/master/R/build-news.R#L161).

This causes build errors for users with limited internet connectivity (#762, #766).

Using `nslookup` is not ideal because even real connections might fail intermittently (#767).

We need a way to let users explicitly disable internet connections. This could be:

- A param (`internet = FALSE`) that is propagated through the build process.
- An user-defined option (#768) (e.g., `getOption(pkgdown.internet)`)

This flag would be checked by `build_news()` and `build_home_index()` before connecting to  CRAN.

**Comment by hadley** [comment]
I think an option would be easier, and it makes sense as it is a global setting.
