### ISSUE TITLE
Provide local CSS/JS libraries

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#776]
From https://github.com/r-lib/pkgdown/pull/774#issuecomment-409123723

pkgdown should provide local JS libraries for users with limited internet connectivity.

**Comment by hadley** [comment]
I don't think it is worthwhile to do this. We should definitely make it possible to build docs without internet (since this it is not uncommon to not have an internet connect on e.g. a production cluster), but the whole design of pkgdown is built around putting the final site on the internet.
