### ISSUE TITLE
build_site() error: is.call(x) is not TRUE

### ISSUE THREAD

**Issue by daviddoret** [r-lib/pkgdown#779]
At this point, I unfortunately have no clue why pkgdown::build_site() fails systematically on my package. It returns the following:
```
> pkgdown::build_site()
Error: is.call(x) is not TRUE
Execution halted
Error: is.call(x) is not TRUE
```
The package is rather basic and in a very early "alpha" stage at this point:
[https://github.com/daviddoret/haricot](https://github.com/daviddoret/haricot)

The only "special features" it uses are:
- figures are being embedded in package documentation with {\figure{blablabla}{blablabla}}
- R6 classes

Any idea what may cause this issue?

**Comment by jayhesselberth** [comment]
This error goes away if I remove all of your `@usage` tags. Do you really need them? pkgdown will automatically generate usage statements in the docs.

**Comment by daviddoret** [comment]
Thanks for your blazing fast answer! You are absolutely right, I was incorrectly using @usage tags. I changed them to @examples and pkgdown::build_site() runs smoothly now.
