### ISSUE TITLE
pkgdown consumed a huge amount (10+GB) of RAM on build_site()

### ISSUE THREAD

**Issue by Robinlovelace** [r-lib/pkgdown#783]
I'm not sure how or why this happened but I'm confident it's pkgdown because I tried it twice (both times it crashed my R session).

Here's the crash message:

```
<simpleError in process_initialize(self, private, command, args, stdin, stdout,     stderr, connections, poll_connection, env, cleanup, cleanup_tree,     wd, echo_cmd, supervise, windows_verbatim_args, windows_hide_window,     encoding, post_process): Cannot fork Unknown error -12 at unix/processx.c:333>
Warning message:
system call failed: Cannot allocate memory 
Error in process_initialize(self, private, command, args, stdin, stdout,  : 
  Cannot fork Unknown error -12 at unix/processx.c:333
```

 Here's the dramatic memory use log on Ubuntu: 

![image](https://user-images.githubusercontent.com/1825120/44046431-50d87ad2-9f23-11e8-90c7-00ff0d14ba9e.png)

With:

``` r
packageVersion("pkgdown")
#> [1] '1.1.0'
```

Created on 2018-08-13 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by Robinlovelace** [comment]
Live update: now trying with

```r
pkgdown::build_site(new = F)
```

In a terminal to see if that solves it - seems to be something to do with running in parallel. Update - crazy RAM use happened again - didn't solve it.

**Comment by Robinlovelace** [comment]
In the  name of reproducibility, I think others will be able to reproduce this by cloning this repo and running `build_site()` from in there: https://github.com/geocompr/geocompkg 

I suspect the culprit is https://github.com/geocompr/geocompkg/blob/master/vignettes/point-pattern-heatmap.Rmd which has some leaflet code.

**Comment by Robinlovelace** [comment]
Update on the last attempt run from a terminal with `new_process = F` - it was definitely the R session itself that was munching the session because when it stopped R with `quit()` this happened:

![image](https://user-images.githubusercontent.com/1825120/44047047-39d5df1c-9f25-11e8-98c1-71cdb56e861c.png)

**Comment by Robinlovelace** [comment]
Another update: thinking maybe running it on a bigger computer with a different OS might help I tried it on my work desktop and get an error - the error message should shed more light on it though, hope this helps:

![image](https://user-images.githubusercontent.com/1825120/44051587-2b18de68-9f32-11e8-9413-62d033348df0.png)

**Comment by Robinlovelace** [comment]
In any case, for users, all the vignettes can be built by running `build_articles()`, that seems to run fine.

**Comment by Nowosad** [comment]
I also got this problem today. Vignette works well when knitted, but there is a memory leak while using `build_site()`.

**Comment by jayhesselberth** [comment]
Could you please build a [minimal package](https://github.com/r-lib/pkgdown/blob/master/.github/CONTRIBUTING.md) that recreates the issue? The geocompkg package has too many dependencies to debug this effectively.

**Comment by Robinlovelace** [comment]
I think it was the number of vignettes, not the dependencies of the package the website of which we were trying to build, that caused the issue. Agree hard to debug.

**Comment by Robinlovelace** [comment]
FYI for anyone else reading this issue: run

```
build_article()
```

one-by-one and it seems to be fine. All good!

**Comment by samvaltenbergs** [comment]
@Robinlovelace did you ever resolve this issue (other than having to build each article individually, which I don't want to do as part of our CI/CD pipeline)? I see @hadley closed the issue, but I don't see details of a resolution. I'm having the same issue: vignettes knit by themselves NP and I can build each article manually by itself, but when `pkgdown::build_site()` runs and builds all the articles at once it crashed because it "cannot allocate vector of size 11.0 Gb". The behavior is the same on my local machine in RStudio as it is in a Docker EE container as part of a CI/CD pipeline.

**Comment by Nowosad** [comment]
Hi @samvaltenbergs I think the problem is still there. We (@Robinlovelace and I) haven't found a solution yet..

**Comment by Robinlovelace** [comment]
To confirm: no I didn't find a solution. I'm not 100% sure what led to the issue being closed. Any info on that @hadley would be appreciated. I think one thing that would help developers would be reproducible examples.

**Comment by jayhesselberth** [comment]
If you are running very large vignettes it is going to be very difficult to debug this, and I would also advocate for breaking these up anyway (or at least trimming your example data sets down a bit).

If this is a bug, it's probably reproducible by a very short vignette.

**Comment by Nowosad** [comment]
Hi @jayhesselberth, I spent an hour a few weeks trying to create a reproducible short example and I was unable to do so...

**Comment by hadley** [comment]
It was closed because we don’t have a reprex and it seems unlikely that the root cause is pkgdown.

**Comment by Robinlovelace** [comment]
I think it's possible to create a reproducible example. May be in `bash` or have lots of `system()` calls though. Will aim to do this when on a decent computer in a session I can afford to crash. Steps to reproduce as far as I remember:

```bash
git clone git@github.com:geocompr/geocompkg
cd geocompkg
R
pkgdown::build_site()
```

**Comment by samvaltenbergs** [comment]
@@hadley\@Robinlovelace\@Nowosad I understand that it's difficult to troubleshoot without a reproducible example, but unfortunately I can't share the vignettes due to corporate policy (The Man)... I can show a screenshot that demonstrates the failure signature: building the articles by themselves works okay but when `pkgdown` tries to put the site together after all the vignettes are turned into HTML it hits a wall. And then if I immediately run the same `build_articles()` command (at which point the vignettes are already turned into HTML) everything is AOK.

![build_site](https://user-images.githubusercontent.com/43759547/49659647-88143a00-f9f9-11e8-9ea4-15d588c40012.png)

What has me scratching my head is that the vignettes are all very simple: the only piece of R code that is executed across the seven vignettes is a call to `Sys.Date()`. That is, there isn't any R code being executed that could possibly create something in memory that's 11Gb in size. 

What is even more strange is that the "11Gb failure" _only_ occurs the first time `build_articles()` or `build_site()` is run for a given R session. If I delete the `docs\articles` folder (which will cause `pkgdown` to rebuild all the HTML vignettes) it runs without an issue. But if I then restart the R session and run it fresh, fails again...

![build_site_restart](https://user-images.githubusercontent.com/43759547/49661184-408fad00-f9fd-11e8-9178-0079f37d5d08.png)

Any ideas?

**Comment by Robinlovelace** [comment]
Reproducible example verified: https://asciinema.org/a/cIr5ez0sh1SOzeBR4h6jzvJXc

Heads-up @hadley and @jayhesselberth please try to reproduce.

**Comment by Robinlovelace** [comment]
Further evidence that this is an issue with `build_site()` and not the contents of the vignettes: when you build them individually, e.g. with the following commands, it works:

```r
# build site:
pkgdown::build_home()

# build vignettes one by one, e.g.
pkgdown::build_article("sea-level-rise")

pkgdown::build_articles()
# build all articles
articles = list.files(path = "vignettes/", pattern = ".Rmd")
articles = gsub(pattern = ".Rmd", replacement = "", articles)
for(i in articles) {
  pkgdown::build_article(i)
}
```

**Comment by hadley** [comment]
@Robinlovelace that video doesn't really add anything. All `build_articles()` does is call `build_article()` with `purrr::walk()`, so it's already basically equivalent to your code. Including the contents of `traceback()` would be more useful.

**Comment by hadley** [comment]
I have started the process of installing all the geocompr dependencies so I can reproduce locally.

**Comment by Robinlovelace** [comment]
Sure. 1st time I've used the function. Hope the output is useful (means nothing to me)!

```
traceback()
5: stop(err[[2]])
4: get_result(output = out, options)
3: callr::r(function(..., crayon_enabled, crayon_colors, pkgdown_internet) {
       options(crayon.enabled = crayon_enabled, crayon.colors = crayon_colors, 
           pkgdown.internet = pkgdown_internet)
       pkgdown::build_site(...)
   }, args = args, show = TRUE, )
2: build_site_external(pkg = pkg, examples = examples, document = document, 
       run_dont_run = run_dont_run, seed = seed, lazy = lazy, override = override, 
       preview = preview)
1: pkgdown::build_site()
```

**Comment by Robinlovelace** [comment]
The good news: with the work-around I've managed to re-build and update the site: https://github.com/geocompr/geocompkg 

Heads-up @samvaltenbergs that work-around https://github.com/r-lib/pkgdown/issues/783#issuecomment-445815333 may be of use if `build_site()` is still playing-up for you.

**Comment by Robinlovelace** [comment]
btw @hadley apologies for all the dependencies.

**Comment by hadley** [comment]
After running `pkgbuild::build_site(new_process = FALSE)` I see:

```
> traceback()
10: knitr::knit_meta_add(old_knit_meta, attr(old_knit_meta, "knit_meta_id"))
9: render(input = md_file, output_file = html_file, output_format = override_output_format, 
       output_options = list(self_contained = FALSE), quiet = TRUE, 
       encoding = "UTF-8")
8: discover_rmd_resources(input_file, encoding, discover_single_resource)
7: rmarkdown::find_external_resources(input_path, "UTF-8") at rmarkdown.R#48
6: render_rmarkdown(pkg, input = input, output = output_file, output_format = format, 
       output_options = options, quiet = quiet) at build-articles.R#216
5: .f(.x[[i]], ...)
4: purrr::walk(pkg$vignettes$name, build_article, pkg = pkg, quiet = quiet, 
       lazy = lazy) at build-articles.R#133
3: build_articles(pkg, lazy = lazy, override = override, preview = FALSE) at build.r#367
2: build_site_local(pkg = pkg, examples = examples, document = document, 
       run_dont_run = run_dont_run, seed = seed, lazy = lazy, override = override, 
       preview = preview) at build.r#287
1: pkgdown::build_site(new_process = F)
```

**Comment by hadley** [comment]
If I run it again, it fails later:

```R
Reading 'vignettes/solutions06.Rmd'
Error in CPL_geos_is_empty(st_geometry(x)) : 
  Evaluation error: IllegalArgumentException: Points of LinearRing do not form a closed linestring.
```

**Comment by Robinlovelace** [comment]
Thanks for reporting. I've raised an issue here: https://github.com/geocompr/geocompkg/issues/2
