### ISSUE TITLE
Definition list only displays short terms

### ISSUE THREAD

**Issue by GeoBosh** [r-lib/pkgdown#786]
The signatures of S4 methods described in `promptMethods()` style are truncated, see
https://geobosh.github.io/lagged/reference/bracket-methods.html.

For comparison, methods described in documentation of S4 classes in the style of `promptClasses()` are ok, see https://geobosh.github.io/lagged/reference/Lagged1d-class.html.

The difference between the two cases is that in methods described in a section on classes, the first argument to `\item` is the name of a function, which is never too long (the signature is in the second argument). In contrast, in methods described in documentation `xxx-methods`, the first argument to `\item` is the signature, which may be quite long.

**Comment by hadley** [comment]
Can you please create a self-contained issue? Off the top of my head, I don't know what `promptMethods()` style is. It would be useful if you could link to the precise line in your .Rd source as well as the precise line in the generated html.

**Comment by GeoBosh** [comment]
Sorry, the example is not clear since I failed to upload the compilation with the recent version of pkgdown as described in the issue. With pkgdown (1.0.0) there was no problem. I am away, far from computers, and will upload new compillation whan I am back in a few days.

I used '...  in the style of promptMethods()`', since S4 methods can be described also with `\S4method` macro in the usage section of a function.

In contrast, `promptMethods()` puts the signatures of S4 methods in section Methods as `\item`s in a `\describe` environment. With the devel versions of pkgdown and (off myhead with 1.1.0) the signatures in section Methods, ie the bold labels of the items, are clearly truncated and syntactically incorrect.

**Comment by GeoBosh** [comment]
I have now uploaded docs/ created with the devlopment version of pkgdown. I believe that the example for `bracket-methods` at https://geobosh.github.io/lagged/reference/bracket-methods.html clearly illustrates the issue described in the original post, in that all signatures (towards the end of that page) are truncated to a fixed width and are thus incomplete.

**Comment by GeoBosh** [comment]
Please see https://github.com/GeoBosh/reprexes/tree/master/pkgdownIssue786.

**Comment by hadley** [comment]
Input rd: https://github.com/GeoBosh/reprexes/blob/master/pkgdownIssue786/man/bracket-methods.Rd#L20-L45

Output html: https://github.com/GeoBosh/reprexes/blob/master/pkgdownIssue786/docs/reference/bracket-methods.html#L112-L118

Generated html: https://geobosh.github.io/lagged/reference/bracket-methods.html

**Comment by hadley** [comment]
This is an html styling issue — the Rd is translated correctly, but the current `<dl>` uses a tabular structure, and expects that the `<dt>` is short.
