### ISSUE TITLE
Image not showing when sharing URL on Facebook

### ISSUE THREAD

**Issue by liao961120** [r-lib/pkgdown#788]
My package's page: https://liao961120.github.io/pttR/

I looked at `<head>` region in the HTML files and found:
`<meta property="og:image" content="/logo.png">`

This seems to cause Facebook looking for `logo.png` in https://liao961120.github.io/ instead of https://liao961120.github.io/pttR/.

This issue may be similar to #390 .

**Comment by jayhesselberth** [comment]
I see the logo just fine using the [twitter card validator](https://cards-dev.twitter.com/validator). Do you know if there is an equivalent validator for facebook? The meta tags in the [live site](https://liao961120.github.io/pttR/articles/dev-functions-dep.html) have the full path to the logo in the content field.

**Comment by liao961120** [comment]
I replaced `<meta property="og:image" content="/logo.png">` with 
`<meta property="og:image" content="https://liao961120.github.io/pttR/logo.png">` using [bash script](https://github.com/liao961120/pttR/blob/master/deploy.sh)(line 25-29) before travis build, so the web page looks fine now.
