### ISSUE TITLE
build_cname() only works once

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#799]
The second and subsequent times you get:

```R
Skipping '/Users/hadley/Documents/tidyverse/tidytemplate/docs/CNAME': not generated by pkgdown
```

Because there's no pkgdown comment. @jimhester do you know if we can add comments to that file?

**Comment by jimhester** [comment]
I don't know, I can't find any examples of CNAME files with comments, but I guess you could try it and see what happens...

**Comment by jimhester** [comment]
So I don't think comments are possible in CNAME files, I tried `# <!-- Generated by pkgdown --!>` and got the following when GitHub tried to build the site.

```
The CNAME `#<!-- generated by pkgdown -->` is not properly formatted. See https://help.github.com/articles/troubleshooting-custom-domains/#github-repository-setup-errors for more information.
```

**Comment by jimhester** [comment]
I can send a PR to just check if the CNAME file exists first instead of using `write_if_different()`.
