### ISSUE TITLE
Page build warning with development version of `pkgdown`

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#803]
I downloaded the development version of `pkgdown` and, although there is no problem in page build, I get the following warning from `GitHub`:
```
The CNAME `indrajeetpatil.github.io/ggstatsplot/` is not properly formatted.
```
Should I just ignore it? Or there is a way to get rid of this warning?
(Corresponding `GitHub` repo here: https://github.com/IndrajeetPatil/ggstatsplot)

Thanks.

**Comment by IndrajeetPatil** [comment]
Yes, even with the new commit, I am getting the same warning.

**Comment by jayhesselberth** [comment]
Why are you using a CNAME for that URL? That is the default URL generated by Github Pages having a CNAME is redundant.

**Comment by IndrajeetPatil** [comment]
I actually didn't change anything since I initiated the website with `pkgdown`! I have no idea where this file came from. Should I delete the `CNAME` file?

**Comment by IndrajeetPatil** [comment]
I actually didn't change anything since I initiated the website with
`pkgdown`! I have no idea where this file came from. Should I delete the
`CNAME` file?

**Comment by IndrajeetPatil** [comment]
Thanks! That solved the issue.

**Comment by IndrajeetPatil** [comment]
I changed the `CNAME`, as suggested, and although the warning I mention here is gone, I get a different warning:
```
You cannot use CNAMEs ending with github.io or github.com. Instead, create a repository named IndrajeetPatil.github.io.
```
Also, I realized that it's `pkgdown::build_site()` that made changes to `CNAME` file, but I see that you've already opened a new issue for this.
