### ISSUE TITLE
Navbar highlighting wrong in reference individual pages

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#804]
When in docs/reference/index.html in the navbar "reference" is highlighted. When clicking on any link in reference, e.g. docs/reference/test_this.html, it's the small home symbol that's highlighted in the navbar whereas I'd expect "reference" to still be highlighted.

I've created a minimal package to see it for myself again before posting, but you can see that for `pkgdown` itself

https://pkgdown.r-lib.org/reference/index.html

![image](https://user-images.githubusercontent.com/8360597/45612271-ca655500-ba62-11e8-9d87-348f37e61817.png)

https://pkgdown.r-lib.org/reference/build_site.html

![image](https://user-images.githubusercontent.com/8360597/45612289-d81ada80-ba62-11e8-955e-47b3cdb89f77.png)

**Comment by jayhesselberth** [comment]
dup of #777
