### ISSUE TITLE
support for Fira code font ligatures?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#806]
I am trying to get the `pkgdown` website for my R package to show all displayed code in `Fira` code font. But it doesn't seem to work:
https://indrajeetpatil.github.io/ggstatsplot/ 

I have included the following `extra.css` file, based on documentation in `Fira` code's wiki:
 https://github.com/IndrajeetPatil/ggstatsplot/blob/master/docs/extra.css

What can I change to get this to work?

**Comment by jayhesselberth** [comment]
You need to put `extra.css` in `pkgdown/`, otherwise pkgdown won't add the file to page `<head>`s.

http://pkgdown.r-lib.org/reference/init_site.html?q=extra#custom-css-js

**Comment by IndrajeetPatil** [comment]
That worked! Thanks
