### ISSUE TITLE
Favicon link is missing from page head

### ISSUE THREAD

**Issue by mrchypark** [r-lib/pkgdown#807]
I check there is favicon from logo but not work in browser.

how do I set favicon work?

https://mrchypark.github.io/sendgridr/

https://github.com/mrchypark/sendgridr

https://github.com/mrchypark/sendgridr/blob/master/docs/favicon.ico

**Comment by peterdesmet** [comment]
I have the same issue. The favicon for our [pkgdown generated website](https://inbo.github.io/wateRinfo/index.html) does not load, even though it is available at https://inbo.github.io/wateRinfo/favicon.ico. Loading the `favicon.ico` from root seems to be the default browser behaviour, even it the file is not referenced in the `<head>` section.

The favicon does load for our site when hosting the site locally, so this might be a GitHub pages issue... but then I wonder why it works for the [pkgdown website](http://pkgdown.r-lib.org/): it that site not hosted on GitHub pages?

Have others with their pkgdown websites hosted on GitHub pages encountered the same issue?

In any case, an easy solution might be if pkgdown included the following in the `<head>` section of the generated html:

```html
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
```

**Comment by mrchypark** [comment]
@peterdesmet  I have the same question. why it works for the [pkgdown](http://pkgdown.r-lib.org/) website?

pkgdown team has any plan to add <head> section like comment?

**Comment by jayhesselberth** [comment]
I have seen the same thing on sites served from Github Pages. I am not so sure pkgdown is served via Github Pages, its CNAME seems to resolve elsewhere.

I have a pkgdown site [on netlify](https://valr.hesselberthlab.org/) and the the favicon appears; there it may just auto-populate without the head section if favicon.ico is present.

**Comment by jayhesselberth** [comment]
Can someone confirm if adding the header info to index.html allows the favicon to appear via Github Pages?

```html
<head>
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
...
</head>`

**Comment by peterdesmet** [comment]
@jayhesselberth it does: see the commit above, where I manually included it in index.html

- Shows up fine on https://inbo.github.io/wateRinfo/index.html (might need to hard refresh)
- Is missing on https://inbo.github.io/wateRinfo/reference/index.html, where it was not included

**Comment by jayhesselberth** [comment]
OK so we just need to add it to the head, if it exists (i.e., is made from logo.png).

**Comment by jayhesselberth** [comment]
How about copying over the pkgdown favicon.ico as a default in the case that a logo.png isn't present, or magick isn't installed?

That way we could just reference favicon.ico in the head template without having to check whether or not the package-specific favicon was created.

**Comment by peterdesmet** [comment]
So all pkgdown generated websites have the pkgdown website by default? That seems a bit odd imo + can be frustrating when adding custom favicon, but it doesn’t immediately replace the default one because of browser caching.
