### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#809]
Even though we have a seed in our files

https://raw.githubusercontent.com/mlr-org/mlr/master/vignettes/tutorial/advanced_tune.Rmd

we get frequent CI commits to `master` changing digits in some code output lately:
https://github.com/mlr-org/mlr/commits/master

Any idea why the seed is not respected?

https://github.com/mlr-org/mlr/issues/2435

**Comment by jayhesselberth** [comment]
How are you building the vignette? Is the seed respected of you do `pkgdown::build_site(new_process=FALSE)`?

**Comment by pat-s** [comment]
By calling `pkgdown::build_site()`. Argument `new_process` does not have an effect on the seeding. 

Btw, I cannot tell when this started or for how long it already exists. We just recognized it when switching from `gh-pages` to `docs/` of the master branch. Before we had a force push every build and nobody cared. But now that we deploy to the master branch..

**Comment by pat-s** [comment]
We have currently disabled the automatic pushing to avoid the cluttering. We currently only build the site but don't deploy it.

**Comment by hadley** [comment]
I can't imagine how pkgdown could be affecting this. Can you confirm that you don't see the same problem if you execute `rmarkdown::render()` directly?

**Comment by hadley** [comment]
Please open a new issue if you can make a simple reprex.
