### ISSUE TITLE
Message if a help page doesn't have an example

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#810]
All function documentation pages should have examples. They're often the easiest way to grasp the semantics of a function.

Maybe we could also compile a page that consists only of examples, with sections derived from the help page titles?

**Comment by jayhesselberth** [comment]
This will be a little work, but IMO is useful and worth trying to do for the next release.

**Comment by hadley** [comment]
I think this is out of scope for pkgdown.

**Comment by krlmlr** [comment]
`build_reference()` warns if a topic is not properly categorized, a similar warning for help pages without examples would do.

Agree that an automatic conversion "reference -> tutorial" probably isn't worth it, https://www.divio.com/blog/documentation/.
