### ISSUE TITLE
Support `method(<class>)` notation to reference a function in markdown

### ISSUE THREAD

**Issue by peterdesmet** [r-lib/pkgdown#811]
Functions in the README or vignettes written as `function_name()` are referenced automatically to their documentation in the pkgdown website (which is great!). I was wondering how to reference S3 methods of the form `method.class` and tried different notations.

I noticed that the format `package::method.class` works. See the blue link for `bioRad::plot.scan` in the screenshot):

<img width="511" alt="screen shot 2018-09-25 at 12 21 56" src="https://user-images.githubusercontent.com/600993/46008662-a090db80-c0bd-11e8-953c-65aef39e747e.png">

Would it be possible to support `method(class)` and `package::method(class)` as well, to align it with other functions? Or as `method(<class>)` and `package::method(<class>)`, like how they are displayed in the function reference list (#436)?

**Comment by hadley** [comment]
I don't think `generic(class)` might be a bit confusing, and `generic(<class>)` isn't valid R code so it would require considerable changes to the existing auto-linker. I'd also not clear that either is much of an improvement over `generic.class()`. 

Overall, I think this is nice idea, but it probably isn't worth it given the estimate cost of implementing it.
