### ISSUE TITLE
use_pkgdown() more effectively

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#812]
related to https://github.com/r-lib/usethis/pull/467

We should pass the build_dir and config_file paths to use_pkgdown here:

https://github.com/r-lib/pkgdown/blob/07e5735b224cd54f61eb8fcac15b7cd6213a7552/R/init.R#L44

**Comment by jayhesselberth** [comment]
We should also store the path to the config file during `as_pkgdown()` so its available in pkg. Factor out file-finding code in read_meta:

https://github.com/r-lib/pkgdown/blob/923eea8c4379e200640a8c98578e82d335561478/R/package.r#L86

**Comment by hadley** [comment]
I don't think we should be calling `use_pkgdown()` there at all, see #862

**Comment by jayhesselberth** [comment]
This is moot now that we are not calling usethis.
