### ISSUE TITLE
weird characters rendered in messages produced by functions

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#814]
All of my functions that produce messages have weird characters in their `pkgdown` documentation (https://indrajeetpatil.github.io/ggstatsplot/reference/index.html#section-helper-functions-statistics-subtitles-):

Example 1
![image](https://user-images.githubusercontent.com/11330453/46088691-e8296d00-c17a-11e8-870c-298465be1d72.png)

Example 2
![image](https://user-images.githubusercontent.com/11330453/46089006-97feda80-c17b-11e8-9d02-07b93594ad60.png)

Is this because I am using `crayon` to display colorful messages? 
For example, here is code for one sample message:
```
      base::message(cat(
        crayon::red("Warning: "),
        crayon::blue("Proportion test will not be run because it requires"),
        crayon::yellow(legend.title),
        crayon::blue("to have at least 2 levels with non-zero frequencies.")
      ))
```

**Comment by IndrajeetPatil** [comment]
I can get rid of this problem by adding `sep = ""` to my `cat()` function call used to produce the message. So seems like the spaces are being rendered with these strange characters. 

```
      base::message(cat(
        crayon::red("Warning: "),
        crayon::blue("Proportion test will not be run because it requires"),
        crayon::yellow(legend.title),
        crayon::blue("to have at least 2 levels with non-zero frequencies."),
        sep = ""
      ))
```

But I still think that it will be nice if this is something that `pkgdown` takes care of automatically.

**Comment by jayhesselberth** [comment]
dup of #847
