### ISSUE TITLE
Improve TOC for long articles

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#817]
Useful for long vignettes. The sidebar ToC gets messy for long vignettes.

![selection_017](https://user-images.githubusercontent.com/8430564/46155051-c01f3400-c276-11e8-8890-d0d8fd939bb5.png)

Can be triggered by adding the following block in `content-article.html`:

```html
$if(toc)$
<div id="toc">
<h3>Table of Contents</h3>
$toc$
</div>
$endif$
```

However, I would prefer to have a separate flag separating the ToC inline and in the navbar (in case someone just wants to have the navbar one).

Currently (I guess) its triggered by the `toc` `rmarkdown` flag when the header looks like this:

````r
---
title: "Resampling"
pkgdown:
  as_is: true
output: 
  rmarkdown::html_document:
    toc: true
---
````

I don't know if its possible to add an argument to `build_site()` which then triggers a custom html variable in `content-article.html`.

**Comment by jayhesselberth** [comment]
We could trigger feature this and depth (#741) via the yaml config file.

```yaml
toc:
  inline: true
  depth: 2
```

Not sure if we could make this configurable per-vignette; it would be easier to implement as a global setting.

**Comment by hadley** [comment]
An inline TOC doesn't seem that useful to me; I'd rather figure out how to make the sidebar handle more complex docs.
