### ISSUE TITLE
Paragraphs are merged when processing \Sexpr

### ISSUE THREAD

**Issue by GeoBosh** [r-lib/pkgdown#819]
In the following `\Sexpr` the two phrases represent two paragraphs, separated by an empty line:
```
\Sexpr[stage=build,results=rd]{paste0("First phrase.\n\nSecond phrase.")}
```
pkgdown renders them as a single paragraph. An example of a rendered page with this is at  https://geobosh.github.io/cvar/reference/cvar-package.html, towards the end of section References. 
The above line is inserted in the source of that page to give a simple example (https://github.com/GeoBosh/cvar/blob/master/R/cvar-package.R, lines 84, 88).  The references should also be in three separate paragraphs (since there are three references).

**Comment by GeoBosh** [comment]
Please see https://github.com/GeoBosh/reprexes/tree/master/pkgdownIssue819.

**Comment by GeoBosh** [comment]
Any chance of looking into this? Besides the reprex package at  https://github.com/GeoBosh/reprexes/tree/master/pkgdownIssue819 from my previous comment, a reprex for a similar issue which appeared in R-devel recently is at https://github.com/GeoBosh/reprexes/tree/master/disappearingParagraphs and described in my R-devel report at http://r.789695.n4.nabble.com/disappearing-paragraphs-in-html-rendering-of-text-from-Rd-macros-td4753409.html.

**Comment by hadley** [comment]
Starting on minimal reprex:

```R
load_all()
scoped_package_context("pkgdown")
scoped_file_context()

rd2html('\\Sexpr[stage=build,results=rd]{"First phrase.\\n\\nSecond phrase."}')
rd2html('First phrase.\n\nSecond phrase.')
```

Doesn't yet reveal any problems.

**Comment by hadley** [comment]
Ok, I have a reprex:

```R
load_all()
scoped_package_context("pkgdown", src_path = ".")
scoped_file_context()

flatten_para(rd_text('\\Sexpr{"X\\n\\nY"}'))
#> [1] "<p>X\n\nY</p>"
flatten_para(rd_text("X\n\nY"))
#> [1] "<p>X</p>\n<p>Y</p>"
```

**Comment by hadley** [comment]
Hmmm, fixing this is going to be tricky because it (I think) requires evaluating the Sexpr tags before parsing the text. Consider these two examples:

```
A
\Sexpr{"\n"}
B
```

```
A

\\Sexpr{"B"}
```

Currently pkgdown assumes that each element of the Rd is either a text fragment or one or more paragraphs. Fixing this is likely to require considerable thought and likely rethinking of the basic approach. That means it's out of scope for 1.2.

**Comment by GeoBosh** [comment]
It is better to use explicit stages in reprexes and probably to evaluate \Sexpr's for both build and install stages (the third stage, render, you are doing yourself). Off my head, the default stage in \Sexpr is 'build', which means that after that there may still be unexpanded macros.

**Comment by hadley** [comment]
pkgdown evaluates all Sexprs, ignoring the stage, because it does not have separate stages. As you can see in the reprexes, the Sexpr is evaluated.

**Comment by GeoBosh** [comment]
I agree in general but consider this:
```
rd_text("\\Sexpr{'\\\\doi{xxx.yyy.zzz}'}")
## {'\doi{xxx.yyy.zzz}'}
```
The `\doi` macro is not expanded. Applying `flatten_para()` expands it:
```
flatten_para(rd_text("\\Sexpr{'\\\\\\\\doi{xxx.yyy.zzz}'}"))
## [1] "<p>doi: <a href='http://doi.org/xxx.yyy.zzz'>xxx.yyy.zzz</a></p>"
```
Effectively, a staged expansion happens but not fully consistently - first `rd_text()` expands the macro `\Sexpr` (and no other user level macros, including those in base R), then `flatten_para()` expands `\doi`. Note that `\Sexpr` could easily return another `\Sexpr`, as can any other macro.

`rd_text()` calls `tools::parse_Rd()` and the latter takes into consideration the options in `\Sexpr{}`, so they matter for it, even if `pkgdown` doesn't care (or maybe pkgdown strips options from `\Sexpr`s?).

**Comment by hadley** [comment]
That is unrelated to the stage of the `\Sexpr` and would appear to be a different bug.

**Comment by hadley** [comment]
I'm closing this issue in recognition of the fact it's 3 years old and I've despite a couple of attempts I've made no progressive on solving it. Given that it seems to affect few people, I think unfortunately we don't have the development resources to spend on this problem.
