### ISSUE TITLE
Update JS libs for security vulnerability

### ISSUE THREAD

**Issue by batpigandme** [r-lib/pkgdown#822]
* @gaborcsardi gen'd a report from `npm audit` [see here](https://gist.github.com/batpigandme/d01ef90a6c86e51f471e7567e3dc9d49).

From @jimhester: 
> I think they are just js libraries used in the examples on the pkgdown site, so not very serious

**Comment by batpigandme** [comment]
Huh, the vulnerability alert is gone, so maybe it's not a problem after all. (Previously there was a big yellow box with a warning if you came to the pkgdown repo).

**Comment by gaborcsardi** [comment]
It was for files in `/docs` and after rebuilding the site, it does not have these files any more.
