### ISSUE TITLE
including vignette only in pkgdown website but not on CRAN

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#823]
I have a data visualization package and, as much as I want to include a lot of examples in vignettes, I am always limited by how many examples I can include because the `CRAN` package size limit is so easily crossed. 

Is there any way that I can include a `vignette` in a package and ignore it for the R build for `CRAN` (`.Rbuildignore`), but render it for the `pkgdown` website under `articles` section?

**Comment by jayhesselberth** [comment]
This could be made more clear in http://pkgdown.r-lib.org/reference/build_articles.html#suppressing-vignettes

**Comment by jayhesselberth** [comment]
You can see vignettes specifically built "web only" for mkin:

https://github.com/jranke/mkin/blob/master/_pkgdown.yml#L83-L86
