### ISSUE TITLE
Examples that use try()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#829]
show an error message in the output, but not in the generated documentation. See e.g. https://tibble.tidyverse.org/dev/reference/new_tibble.html .

I'm aware that `try()` has some deficiencies, but it's a concise way to write an example that is run and shows the error that occurs. Do we want to show the error message, like a previous version did IIRC?

**Comment by krlmlr** [comment]
We can work around, but it's not pretty:

``` r
evaluate::evaluate(quote(rlang::catch_cnd(stop())))
#> [[1]]
#> $src
#> [1] "rlang::catch_cnd(stop())"
#> 
#> attr(,"class")
#> [1] "source"
#> 
#> [[2]]
#> [1] "<simpleError in force(expr): >\n"
evaluate::evaluate(quote(tryCatch(stop(), error = identity)))
#> [[1]]
#> $src
#> [1] "tryCatch(stop(), error = identity)"
#> 
#> attr(,"class")
#> [1] "source"
#> 
#> [[2]]
#> [1] "<simpleError in doTryCatch(return(expr), name, parentenv, handler): >\n"
```

<sup>Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

@lionel-: Is `catch_cnd()` here to stay? Maybe use tidy evaluation for a better error message?

``` r
my_catch_cnd <- function(expr) {
  quo <- rlang::enquo(expr)
  rlang::eval_tidy(
    rlang::quo(tryCatch(!!quo, error = identity))
  )
}
evaluate::evaluate(quote(my_catch_cnd(stop())))
#> [[1]]
#> $src
#> [1] "my_catch_cnd(stop())"
#> 
#> attr(,"class")
#> [1] "source"
#> 
#> [[2]]
#> [1] "<simpleError in ~stop(): >\n"
```

<sup>Created on 2018-11-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by lionel-** [comment]
`catch_cnd()` is likely stable but it doesn't seem right for documenting errors.
