### ISSUE TITLE
Support radix articles

### ISSUE THREAD

**Issue by maxheld83** [r-lib/pkgdown#835]
[radix](https://rstudio.github.io/radix/) is a new rmarkdown format for data scienc-y articles, based on Google's [distill](https://distill.pub) web framework.
Compared to the vanilla (slightly altered) `rmarkdown::html_document()` currently used within pkgdown, it has a couple of advantages:

- some layouting sugar (full-width figures, gutter footnotes, ...)
- extensive scholarly metadata support
- hoverable footnotes and citations

So I thought it'd be nice to support radix as an *article* format within pkgdown websites. 

I haven't thought through just how this might be accomplished, and there might be some stumbling blocks (conflicting css?).

If the maintainers might see some value in this, I'd be happy to research this further and give it a go if doable.

**Comment by jayhesselberth** [comment]
One issue is that It doesn't look like radix will support sidebar toc anytime soon (https://github.com/rstudio/radix/issues/16).

**Comment by maxheld83** [comment]
yes I thought about that too.
But the sidebar toc in pkgdown is courtesy of `rmarkdown::html_document()`, correct?
So if, instead of that, `radix::radix_article()` is run, then there should never be a the need to also show a sidebar toc, correct?
(radix also has tocs, but only at the top).

**Comment by hadley** [comment]
I think it would be nice if we could do this, but I suspect the complexity of the radix formatting coupled  with pkgdown's special needs is going to make this a complex task.

**Comment by maxheld83** [comment]
on second thought, I'm not so fond of my own idea now, because radix has a lot of (JS) dependencies and compares unfavorably to the relatively clean, bootstrappy design of rmarkdown websites and pkgdown.

Perhaps a better way might be to ["backport" some radix design niceties to rmarkdown](https://github.com/rstudio/rmarkdown/issues/1501), so as to keep pkgdown nice and tight and clean.

Also, supporting books inside pkgdown as per #853 might address a good share of these niceties.

I love this aspect about rmarkdown and pkgdown, as opposed to many other rmarkdown formats – that it's mostly bs 3.3.7 under the hood.
