### ISSUE TITLE
Blank embedded Shiny app in pkgdown article

### ISSUE THREAD

**Issue by lrutter** [r-lib/pkgdown#838]
Hello:

I am attempting to embed a Shiny app into a pkgdown article. The article is located in vignettes/shinyArticle.Rmd. If I issue the command rmarkdown::run("vignettes/shinyArticle.Rmd"), it converts into a .html file that successfully embeds the Shiny app. However, if I run pkgdown::build_site() and view my pkgdown instance in a web browser, this article simply creates a static blank square in place of the interactive Shiny app.

My minimal example can be found here: https://github.com/lrutter/pkgDownExample

Any ideas on how to successfully embed the Shiny app into the pkgdown article would be much appreciated. Thank you!

**Comment by GregorDeCillia** [comment]
pkgdown only produces static html files which means there is no R server in the background to process the outputs of your application. If you want to add an app to your articles, you can host it on `shinyapps.io` and embed it via an iframe.

**Comment by jayhesselberth** [comment]
We should add a blurb to the docs about manually adding shiny apps in iframes. The [Shiny gallery](https://shiny.rstudio.com/gallery/) has many examples.

**Comment by jayhesselberth** [comment]
This works as a vignette but requires a bit more css tweaking to get the layout right.

```r
---
title: "test: Shiny"
---

<style>
.shiny-app-frame {
  position: fixed;
  left: 0;
  top: 50px;
  bottom: 0;
  right: 0;
}
.shiny-app-frame iframe {
  width: 100%;
  height: 100%;
  border: none;
}
</style>

<div class="shiny-app-frame"> 
<iframe src="https://gallery.shinyapps.io/083-front-page">
</iframe>
</div>
```

**Comment by lrutter** [comment]
Thank you for the helpful explanation and suggestions here!

**Comment by ijlyttle** [comment]
@haleyjeppson and I will have a crack at this
