### ISSUE TITLE
Classify pkgdown-generared files as "generated files" via linguist

### ISSUE THREAD

**Issue by GregorDeCillia** [r-lib/pkgdown#842]
When browsing through commits in github, [linguist](https://github.com/github/linguist) helps to classify code and make sure that "generated files", like roxygen-generated `.Rd` files, are not rendered in the diffs.

![diff](https://user-images.githubusercontent.com/9311130/46907789-34650300-cf18-11e8-9fcd-3238f8712c5a.png)

Currently, this logic does not work with static html files generated by pkgdown. I would suggest to take measures for that to work in the future by registering 

    

in the linguist repository. See [here](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L495) for the corresponding .Rd  entry.

**Comment by jayhesselberth** [comment]
It would be great to have this enabled for all sites *except* the main pkgdown site; the diffs are useful for pkgdown development. I had a quick look and it doesn't look there is an option to disable rendering for specific sites (but maybe I just missed it).

**Comment by GregorDeCillia** [comment]
The section overrides/documentation in the readme of linguist claims that `.gitattributes` (on the root of a repository) can be used to change the default behavior. For pkgdown this would be

    docs/* linguist-documentation=false

to render the diffs. I'll set up a test repo and link it here.

**Comment by GregorDeCillia** [comment]
See [here](https://github.com/GregorDeCillia/linguistTest/commit/42445c24f8454ce5daa9e4c34c286e2544ee4f8d) for a commit where I managed to render the diffs for a roxygen-generared `.Rd` file by setting `.gitattributes` to

    man/* linguist-generated=false

For commits that where made before `.gitattributes` was added, the diffs still behave as usual. See [here](https://github.com/GregorDeCillia/linguistTest/commit/3c01506ad1ff7eda69e78c483a9a7c6461eac3a9).

**Comment by jayhesselberth** [comment]
This needs to be submitted as a PR in linguist, near the [roxygen2 section](https://github.com/github/linguist/blob/master/lib/linguist/generated.rb#L495):

```ruby
    # Internal: Is this a pkgdown-generated file?
    #
    # A pkgdown-generated file typically contains:
    # <!-- Generated by pkgdown: do not edit by hand -->
    # on the first line.
    #
    # Return true or false
    def generated_pkgdown?
      return false unless extname == '.html'
      return false unless lines.count > 1

      return lines[0].include?("<!-- Generated by pkgdown: do not edit by hand -->")
    end

```

**Comment by GregorDeCillia** [comment]
Taking [this commit](https://github.com/github/linguist/commit/5dff91d493dfcb9ecede8a8ec26966bb08295c85#diff-fa6c788e8ff418405feddecdab7cc29d) as a reference, it seems there should also be a test file in [samples/HTML](https://github.com/github/linguist/tree/master/samples/HTML) for the new rule.

@jayhesselberth I can craft a PR soon if this is alright with you.

**Comment by jayhesselberth** [comment]
Let's see what @hadley thinks before proposing this PR in the linguist repo.

We also need to sort out why the home page (index.html) has this information on the second line, not the first.

**Comment by hadley** [comment]
Sounds reasonable to me.

**Comment by jayhesselberth** [comment]
Closed by https://github.com/github/linguist/pull/4301
