### ISSUE TITLE
REPL option

### ISSUE THREAD

**Issue by Fazendaaa** [r-lib/pkgdown#843]
Is there any way of adding a REPL option in the generated example, kind of how currently is done but adding it the possibility to the user type and then modify on the fly the code to see how his changes affect the content.

**Comment by jayhesselberth** [comment]
We are unlikely to implement this but happy to review a PR.

**Comment by Fazendaaa** [comment]
Thanks, @jayhesselberth. Maybe in the future, I will look into it.
