### ISSUE TITLE
build_site() error

### ISSUE THREAD

**Issue by mvinaixa** [r-lib/pkgdown#844]
Thanks a lot for this package. I am a newbie.  I am getting this error regardless of the pkgdown installed version (either CRAN or GiHub)
>build_site()
<simpleError in fun_info(x): is.call(x) is not TRUE>
Error in fun_info(x) : is.call(x) is not TRUE

Any thoughts? Any advice or suggestion will be appreciated. Thanks again

**Comment by jayhesselberth** [comment]
May be related to #795 

Are you using `@usage` tags? They can cause problems. pkgdown builds a usage statement for you in the reference pages.

**Comment by mvinaixa** [comment]
Yes, it was about @usage tag thanks a lot!. I removed usage tag from my documentation and it works!
Thanks again
