### ISSUE TITLE
Use PNG favicon instead of ICO

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#845]
I think it would be better to use PNG logos directly as favicons instead of converting them.

- This removes the dependency to `magick` and reduces code complexity.
- [PNG favicons are supported by all browsers (that use favicons at all)](https://caniuse.com/#feat=link-icon-png).
- 32x32 is way too small compared to nowadays standards and will probably look terrible on high-res retina screens.
- It may sound problematic to load a potentially heavy image file as favicon instead of a resized 32x32 img but most clients will cache it and it is already loaded in the body of `index.html` anyways.

If you agree, I can submit a PR with this change.

**Comment by hadley** [comment]
Yes, that would be great! 

Can you please provide a link to the spec (or a good blog post) discussing this?

**Comment by Bisaloo** [comment]
This [blog post](https://css-tricks.com/favicon-quiz/#article-header-id-2) seems quite good but it is a bit old already and the web ecosystem is moving fast.

> Altough all desktop browsers support `favicon.ico`, this file is mostly deprecated. Yes, you can still rely on this file and it will work as expected. But seriously, it's an old deprecated format. It is not used anywhere else in web technology. PNG is much more consistent.

Unfortunately, I could not find anything more recent that treated all aspects of the question. About the sizes only, [this SO answer seems more up-to-date](https://stackoverflow.com/a/48969053).

> Historically, there was a single favicon.ico file, still supported. However, most recent browsers rather pick PNG icons, which are lighter. Plus some browsers are not able to select the proper icon in the ICO file (this format can embed several versions of an icon), leading a low resolution icon being wrongly used.

To be honest, those links also recommend to keep the old `ICO` file alongside the `PNG` files for older browser compatibility. However, as shown in the [link I provided in my previous post](https://caniuse.com/#feat=link-icon-png), only IE 6-10 do not support `PNG` icons (and support `ICO`), and it only represents 0.37% of the browser share.

I don't know if we should provide all the sizes mentioned in this question or limit ourselves to a smaller subset though...

**Comment by hadley** [comment]
Thanks for the links. Reading through, I think we should probably make 32x32 and 96x96 `favicon,png`s, and a 180x180 `apple-touch-icon.png`. 

Somewhat related, I'd ideally like to eliminate the magick dependency, since as we build more sites automatically on travis, the size of the dependencies become more of a problem. But the png package is very basic.

**Comment by hadley** [comment]
Alternatively, rather than building the favicon every time, we could require the user to explicitly do something to build it.

**Comment by hadley** [comment]
In the long run, we should use the real favicon generator API, which I've recorded in #869

**Comment by Bisaloo** [comment]
Sounds good! I'll try to have a look in the next couple of weeks and possibly tackle #869 at the same time.

Do you have a deadline for the 1.2.0 release or not?

**Comment by hadley** [comment]
Hopefully the last week of November.
