### ISSUE TITLE
ANSI escapes in examples

### ISSUE THREAD

**Issue by lionel-** [r-lib/pkgdown#847]
Following https://github.com/r-lib/pkgdown/pull/801, the examples are printed with ANSI escapes.

**Comment by jayhesselberth** [comment]
@jimhester Do you know what the issue might be here?

**Comment by jimhester** [comment]
yeah, we are explicitly enabling crayon by setting an option, but for examples we should be relying on the auto-detection instead.

A better solution would be to merge / update https://github.com/r-lib/pkgdown/pull/620 so we would have colored results in the examples.
