### ISSUE TITLE
better formatting for authors in `-package.R` files 

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#850]
The way package description files (`-package.R`) are currently rendered in `references` section using `pkgdown` need better formatting of the author list (in my view). The second person's name always appears on the same line as the first person's name. It will be better to have it on the second line. 

Here are a couple of examples:

- `ggstatsplot` (https://indrajeetpatil.github.io/ggstatsplot/reference/ggstatsplot-package.html)

![image](https://user-images.githubusercontent.com/11330453/47618988-b70cc700-daaf-11e8-8d7c-863fa37447f1.png)

- `broom` (https://broom.tidyverse.org/reference/broom.html)

![image](https://user-images.githubusercontent.com/11330453/47618969-76ad4900-daaf-11e8-8204-d9984006beb0.png)

**Comment by hadley** [comment]
Looks fine on the pkgdown site.

<img width="189" alt="screenshot 2018-11-08 at 1 28 23 pm" src="https://user-images.githubusercontent.com/4196/48222422-2dd07c80-e35a-11e8-93a0-0ae0834775fd.png">

And looks fine on broom today.

Are you sure this isn't just an old version of pkgdown?

**Comment by jayhesselberth** [comment]
This issue refers specifically to the case where the package contains a "-package.R" file. 

You can see the issue on [this page](https://broom.tidyverse.org/reference/broom.html) in broom (which is built from broom-package.R).

Are these files treated differently at the template level?

**Comment by hadley** [comment]
Oh got it - it's probably incorrect rendering of `\author{}` fields

**Comment by hadley** [comment]
This was an easy fix 😄

**Comment by hadley** [comment]
I agree, but I think that's now a roxygen2 issue; pkgdown is rendering to html correctly.
