### ISSUE TITLE
bogus link if missing BugReports

### ISSUE THREAD

**Issue by bastistician** [r-lib/pkgdown#855]
If the package does not contain a `BugReports` field in its DESCRIPTION file, the generated home page will currently contain

> Report a bug at
> <a href="NA">NA</a>

among the links generated from `data_home_sidebar_links()` at https://github.com/r-lib/pkgdown/blob/36bedb20e8d68ee91d33834c76f0e3dd03d5086a/R/build-home-index.R#L82.

A solution could be to mimic what R's `bug.report()` does since R 2.11.0, i.e., fall back on the maintainer's e-mail address if `BugReports` is unspecified:

> Report a bug to
> Joe.Developer@some.domain.net

Alternatively, not including such a link at all would actually best reflect the package DESCRIPTION and possibly the authors intention, so I would favour this more defensive solution. Note that it is always possible for the package authors to manually add intended bug report links to the homepage via the **pkgdown** configuration file.

**Comment by jayhesselberth** [comment]
Could be merged with #694

**Comment by bastistician** [comment]
I could prepare a PR which modifies `data_home_sidebar_links()` in that it generates a link for bug reports only if the DESCRIPTION actually has a "BugReports" field. Is that acceptable?

**Comment by hadley** [comment]
@bastistician yes, that would be great!

**Comment by bastistician** [comment]
Oops, I now see that @jayhesselberth has also worked on a solution for this issue (#871), where the maintainer's e-mail address is used as a fallback link. As mentioned above, I would prefer if **pkgdown** took the more defensive approach of only including a link in the sidebar if and only if there actually is a BugReports field in the DESCRIPTION (#872). That also avoids spreading plain-text e-mail addresses on websites.

**Comment by jayhesselberth** [comment]
Yours is the simpler solution and I think preferable. Closing #871 for now.
