### ISSUE TITLE
feature request: table of contents for the home page

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#858]
This is definitely a low priority feature request but I was wondering if it would be possible to have a table of contents for the `Home` page which will make navigating long `README` files easier (e.g., https://indrajeetpatil.github.io/ggstatsplot/).

![image](https://user-images.githubusercontent.com/11330453/47966051-0ad16000-e01c-11e8-944b-aadf4b1d95e1.png)

Something similar to what is currently the default for the `vignettes`-

![image](https://user-images.githubusercontent.com/11330453/47966022-c8a81e80-e01b-11e8-904e-d2942d344191.png)

**Comment by hadley** [comment]
My current position is that if your readme is long enough to need a table of contents, you need to refactor it some other way. (This is partly a post-hoc justification of my inability to see a good way to add a TOC to the sidebar, but I don't think it's an unreasonable position).

**Comment by IndrajeetPatil** [comment]
I understand your position. 

I personally treat `README`s as _crash course_ a user can do to quickly start using the package and typically include a much more exhaustive documentation in the `vignettes`, which, let's face it, not a lot of users actually read. 

In terms of implementation, how about creating the `Contents` section right below the `Developers` section?

![image](https://user-images.githubusercontent.com/11330453/48289688-58940100-e43e-11e8-96cc-87553c1aa14b.png)

**Comment by IndrajeetPatil** [comment]
Supported in https://github.com/r-lib/pkgdown/commit/d40ebb31624474d1a2f5bad750cefed109c1f4f6.

Thanks, @maelle! 😄
