### ISSUE TITLE
deploy_site_github() nukes the production site when bumping to dev version

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#860]
When you have a production site auto deployed to `gh-pages`, say for `0.0.2`, and then you bump the package version to `0.0.2.9000`, the auto-build on Travis only creates the `docs/dev/` folder and then force pushes that to the `gh-pages` pages branch. This overwrites the existing top level `docs/` folder that held the production site.

Expected behavior is to just write to `docs/dev` and not also remove the production site.

I'm assuming that the change can be made [here](https://github.com/r-lib/pkgdown/blob/master/R/deploy-site.R#L81) and it is just a matter of getting the right git incantation going.

**Comment by DavisVaughan** [comment]
Related is that the force push results in only having 1 commit logged in `gh-pages` (See [yardstick](https://github.com/tidymodels/yardstick/commits/gh-pages) where I have done multiple commits but only 1 shows). Maybe if just a push was used it would create a commit history and also not overwrite the existing site

**Comment by hadley** [comment]
Will be fixed by #851.
