### ISSUE TITLE
build_reference() errors with roxygen 6.1.1

### ISSUE THREAD

**Issue by pat-s** [r-lib/pkgdown#874]
At least on Travis: https://travis-ci.org/mlr-org/mlr/jobs/452051115#L2263

Due to this issue: https://github.com/klutometis/roxygen/issues/822

The following call

https://github.com/r-lib/pkgdown/blob/7f564ddbcad38ba3c49bc4c2fed72696021b0fff/R/build-reference.R#L108

does not work with roxygen2 v6.1.1

**Comment by hadley** [comment]
Just fixed in  3eb2f10
