### ISSUE TITLE
Should footer include pkgdown version?

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#876]
(including sha if installed from GitHub)

This would make it easier to quickly verify that a bug report is for the latest version. 

@jayhesselberth what do you think?

**Comment by jayhesselberth** [comment]
Sounds reasonable to me. I would suggest something like:


- Site built with pkgdown (1.1.0)
- Site built with pkgdown (1.1.0.9000@sha)

**Comment by hadley** [comment]
If we do this, it's basically the kiss of death for reviewing html diffs in pkgdown. Are you ok with that?
