### ISSUE TITLE
adding option to place hex sticker on sidebar

### ISSUE THREAD

**Issue by yonicd** [r-lib/pkgdown#886]
Currently the hex sticker comes out on the same line as the homesite header.

It would be a nice option to have the sticker to the top of the sidebar, so the sticker can still be viewed while scrolling the main div of the home page.

this can be done by adding an a url path to point to the sticker in the _pkgdown.yml.

This is the screenshot of the new placement.

![image](https://user-images.githubusercontent.com/1755487/48385741-af5b3e00-e6bd-11e8-9cc0-463acf2477b3.png)

**Comment by hadley** [comment]
We'd review a PR that implemented this, but otherwise I think it's unlikely to rise to the top of our priority list.

**Comment by yonicd** [comment]
https://github.com/r-lib/pkgdown/pull/867
