### ISSUE TITLE
Spurious links in news items

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#889]
I think a recent change is causing non-sensical links to be generated to files in NEWS items.

These [news items](https://pkgdown.r-lib.org/dev/news/index.html) (on the dev page) have links to seemingly random rdocumentation pages:

- Can now build sites for older packages that don’t have a Authors@R field (#727).
- build_site() now uses colors even if new_process = TRUE (@jimhester).
- build_home() now uses the content-home.html template when the content is a .Rmd file (@goldingn #787).
- build_home(): a link to the source inst/CITATION was added to the authors page (#714).

*Edit*: Basically anything in backticks is being linked now.

**Comment by hadley** [comment]
I don't think they're random; they're calls to `:` and `@` functions 😦

**Comment by jayhesselberth** [comment]
This is caused by the changes in b5911489cd5c702512d48e6f5db3d2ebb326cb30.

```r
pkgdown:::href_expr_(Authors@R)
# [1] "https://www.rdocumentation.org/packages/base/topics/slotOp"
```

A test like this should pass:

```r
test_that("only valid functions are linked", {
  scoped_package_context("test")

  expect_equal(href_expr_(Authors@R), NA_character_)
})
```

One fix would be to only link references to functions with terminal parens. `href_expr` already kind of does this:

```r
pkgdown:::href_expr_(median())
# [1] "https://www.rdocumentation.org/packages/stats/topics/median"
# names without parens are not linked
pkgdown:::href_expr_(median)
# [1] NA

```

**Comment by jayhesselberth** [comment]
I think `href_expr()` needs a check like this:

``` r
library(rlang)

check <- function(x) {
  x <- substitute(x)
  length(x) == 1 || is_call(x, c("::", ":::"))
}

# checks that should pass
check(stats::median())
#> [1] TRUE
check(median())
#> [1] TRUE
check(stats::median)
#> [1] TRUE
check(median)
#> [1] TRUE

# checks that shouldn't pass
check(Authors@R)
#> [1] FALSE
check(content-home.html)
#> [1] FALSE
check(toc: depth)
#> [1] FALSE
```

<sup>Created on 2018-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
