### ISSUE TITLE
deploy_site_github() can't find gh-pages branch (b/c it doesn't exist yet)

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#890]
I think `deploy_site_github()` used to create the `gh-pages` branch for you the first time you tried to build the pkgdown site from travis. With the new `clone` command, it no longer does this. I just tried to use it for a new package that does not have a `gh-pages` branch yet, and got this in the travis output:

```
── Cloning existing site ───────────────────────────────────────────────────────
Running git clone --single-branch -b gh-pages --depth 1 \
  'git@github.com:DavisVaughan/rray.git' /tmp/RtmpH4l5ns/file657a4ca69c1f
Cloning into '/tmp/RtmpH4l5ns/file657a4ca69c1f'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.

warning: Could not find remote branch gh-pages to clone.

fatal: Remote branch gh-pages not found in upstream origin
Error in processx::run("git", c(...), echo_cmd = TRUE, echo = TRUE) : 
  System command error
Calls: <Anonymous> -> deploy_local -> github_clone -> git -> <Anonymous>
Error: [ENOENT] Failed to search directory '/tmp/RtmpH4l5ns/file657a4ca69c1f': no such file or directory
Execution halted
Script failed with status 1
```

Would it be possible to check for the existence of the branch before cloning, and create it if it doesn't exist yet?

**Comment by hadley** [comment]
@jimhester do you know how to do this?

**Comment by jimhester** [comment]
Probably the way you would have to do it is try to clone and if the clone fails create a new branch, but that seems brittle, what happens if the clone fails for a different reason...

An maybe more robust alternative would be to use ls-remote with the `--exit-code` switch, it will return a 2 exit code if the ref does not exist on the remote. e.g.

```shell
git ls-remote -q -h --exit-code https://github.com/r-lib/pkgdown gh-pages
#> 1b0c8395173912e7b995ce44be9c41b89c02669c        refs/heads/gh-pages
echo #?
#> 0
# readr does not have a gh-pages branch
git ls-remote -q -h --exit-code https://github.com/tidyverse/readr gh-pages
echo #?
#> 2
```

**Comment by DavisVaughan** [comment]
One more related note (could be a separate issue but maybe you can fix it all at once). I made a commit that did not update any documentation, and that failed with:

```
── Commiting updated site ──────────────────────────────────────────────────────
Running git add -A .
Running git commit -m 'Built site for rray: 0.0.0.9000@3f1c012'
On branch gh-pages

Your branch is up to date with 'origin/gh-pages'.
nothing to commit, working tree clean

Error in processx::run("git", c(...), echo_cmd = TRUE, echo = TRUE) : 
  System command error
Calls: <Anonymous> ... github_push -> with_dir -> force -> git -> <Anonymous>
Execution halted
Script failed with status 1
```

- [Travis](https://travis-ci.org/DavisVaughan/rray/jobs/455525925#L1497)
- [Commit](https://github.com/DavisVaughan/rray/commit/3f1c0128f90af7d3f3982c828f97955e5dd70ea3) (a one line whitespace change to test this)

Maybe it could not force push if the commit didn't change anything? I'm not sure how you'd detect that though. Alternatively, you could always add a random dummy variable somewhere (maybe to `pkgdown.yml`?) so _something_ always changes.

**Comment by jimhester** [comment]
Probably the easiest way to check if there were any changes to the working directory is to check the exit code of `git diff-index` (if it is != 0 there are changes)

```sh
git diff-index --quiet HEAD --
```

**Comment by hadley** [comment]
Maybe it would be simply easier to document this in the setup

**Comment by DavisVaughan** [comment]
@hadley there was a second issue in the comments https://github.com/r-lib/pkgdown/issues/890#issuecomment-439064265. Do you want me to open this somewhere else?
