### ISSUE TITLE
wrong URLs generated for vignette sources

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#895]
All sources for `.Rmd` files point to rdocumentation webpage for arithmetic in R.

Here is a preview of this error for `ggstatsplot` package website (https://indrajeetpatil.github.io/ggstatsplot/)-

![source](https://user-images.githubusercontent.com/11330453/48667046-a4c4ee00-ea9b-11e8-95c5-6eb1018532e7.gif)

**Comment by jayhesselberth** [comment]
dup of #889

**Comment by jayhesselberth** [comment]
Re-opening for reference.

**Comment by jayhesselberth** [comment]
Seems to be fixed by #896
