### ISSUE TITLE
Make sure that url field always (or never) requires a protocol 

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#903]
As requested in https://github.com/tidyverse/ggplot2/pull/3006.

We should ensure that the `url` field in `_pkgdown.yml` either always or never requires a protocol. Also possibly add a check to ensure that users provide the required format.

Currently, it needs a protocol to:

- build a standard compliant sitemap

On the other hand, it doesn't accept a protocol to:

- ??

Non-issues:

- CNAME needs to be a domain name, and therefore not have any protocol but it is stripped in `cname_url`

**Comment by hadley** [comment]
GitHub cname, although I have a vague memory we strip it.

**Comment by jayhesselberth** [comment]
The protocol is stripped from the url for the CNAME:

https://github.com/r-lib/pkgdown/blob/5f28dd1e87b6dfecb5426b21fc5353e486e6deb9/R/build-cname.R#L25-L26
