### ISSUE TITLE
Only deploy a clean site?

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#905]
The fix to the function linking bug (#889) is not being applied to pages on the dev branch. See [this page](https://pkgdown.r-lib.org/dev/articles/pkgdown.html) where `inst/CITATION` is still linking to rdocumentation.org.

One fix would be to push only a complete, clean site when using deploy. I think we'd just need to call `clean_site()` prior to the build.

**Comment by hadley** [comment]
Why do you think that cleaning is the problem?

**Comment by hadley** [comment]
I just rebuilt locally and I still see the problem.  The problem is I forgot `/` in the infix list. I'll fix momentarily.
