### ISSUE TITLE
server IP address could not be found

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#907]
I am using `pkgdown` to create a website for a [repo](https://github.com/IndrajeetPatil/devtoolverse) and running `pkgdown::build_site()` works fine locally. But if I go to https://devtoolverse.com/, I get this error-

![image](https://user-images.githubusercontent.com/11330453/48785679-35294b80-ecb3-11e8-8634-350f86842486.png)

Here is the `_pkgdown.yml` for the same-
https://github.com/IndrajeetPatil/devtoolverse/blob/master/_pkgdown.yml

I have created two `pkgdown` websites thus far for my R packages and this recipe has worked. Not sure why it's not working now.

**Comment by hadley** [comment]
That sounds like a domain name configuration problem and hence is not a pkgdown problem.
