### ISSUE TITLE
When using a custom navbar, the home page button is lost

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#911]
One of two things is supposed to happen when you use a custom navbar, as ggplot2 does:

![image](https://user-images.githubusercontent.com/19150088/48859862-4181d700-ed8d-11e8-8fd6-d873ace1aa84.png)

1) The home button (the little house) is lost, but `Reference` should not be highlighted as it is when you go to the home page. If the loss of the home button is the correct behavior, I guess there should be an easy way to get that home button back when you use a custom navbar, and make sure it highlights appropriately when you do go to the home page?

2) The home button should never have been lost in the first place, even with a custom navbar. Then the highlight behavior should be correct because it will highlight the home button since it will be the first element in the navbar

**Comment by hadley** [comment]
This bug was probably introduced when fixing #777

**Comment by hadley** [comment]
I think this might be an off-by-one error. 😱

**Comment by hadley** [comment]
It worked locally, but the published version of the ggplot2 site now doesn't highlight any navbar: http://ggplot2.tidyverse.org/
