### ISSUE TITLE
Deploy instructions create branch that pkgdown won't write to

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#915]
Because `README.md` is not on the whitelist. Should change to "CNAME"? Or adjust `is_non_pkgdown_site`?

**Comment by hadley** [comment]
And recommend doing it outside of outside to avoid `.Rproj.user` issues

**Comment by jayhesselberth** [comment]
If we adjust the suggestion for initialization to this:

```
git checkout --orphan gh-pages
git rm -rf .
git commit --allow-empty -m 'initial gh-pages commit'
git push origin gh-pages
git checkout master
```

Then `is_non_pkgdown_site()` could check that either `pkgdown.yml` exists (i.e., there is an existing pkgdown site that needs updating) or that the directory is empty (i.e., it was just initialized).

**Comment by hadley** [comment]
Ooh, I didn't know about `--allow-empty`. Thanks!

**Comment by hadley** [comment]
But an empty site should be ok too?
