### ISSUE TITLE
R output format from examples in help/reference pages

### ISSUE THREAD

**Issue by luca-scr** [r-lib/pkgdown#921]
The R output from examples in help/reference pages is formatted as
```
> summary(iris$Sepal.Length)
#>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>  4.300   5.100   5.800   5.843   6.400   7.900 
```
Is it possible to customise the output as in **knitr**? i.e.
```
> summary(iris$Sepal.Length)
##   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  4.300   5.100   5.800   5.843   6.400   7.900 
```
Not a big issue, but it would be coherent with vignettes' output.

**Comment by jayhesselberth** [comment]
You mean use `##` instead of `#>` for a comment character? That's the only different I see between your examples.

**Comment by luca-scr** [comment]
yes, exactly.

**Comment by jayhesselberth** [comment]
Would have to propagate an alternative prompt string through to `label_lines`.

https://github.com/r-lib/pkgdown/blob/c980e84a573614087c6e151d5e6e19a22748b761/R/replay-html.r#L1

**Comment by hadley** [comment]
I don't think the benefit of implementing this feature is worth the cost, and I strongly prefer `#>`.

**Comment by luca-scr** [comment]
Hi Hadley, thanks for your reply. I can see your point. But, it would be really that hard to include a field in _pkgdown.yaml to set the comment string?
In any case, thanks to you and all your collaborator for providing pkgdown to the R community, it is great.
Luca
