### ISSUE TITLE
Vertical alignment of params and param docs is wonky

### ISSUE THREAD

**Issue by jennybc** [r-lib/pkgdown#925]
Noticed here:

https://tibble.tidyverse.org/dev/reference/tibble.html#arguments

The spatial relationship between `.rows` and its associated text and `.name_repair` and its text is very easy to mis-read.

<img width="838" alt="screen shot 2018-12-03 at 1 44 12 pm" src="https://user-images.githubusercontent.com/599454/49403412-8e589c80-f701-11e8-87cf-4b565d582ecb.png">

**Comment by jayhesselberth** [comment]
I think we need to vertically align the param value, i.e. `.rows` and `.name_repair` in this example.

**Comment by hadley** [comment]
Oops that wasn't the problem - the problem is that the entire tibble site formatting is messed up for similar reasons to reprex.
