### ISSUE TITLE
Rd tabular formating is mangled by `\code` calls in html output 

### ISSUE THREAD

**Issue by stufield** [r-lib/pkgdown#928]
I ran into an issue where the formating conversion from *.Rd -> HTML gets confused in a **\tabular** environment within the *.Rd when a **\code** call is used in one (or many) of the elements (cells).
Here is a pseudo-`reprex`. The back-ticks are converted into **\code** elements by `roxygen2` (\code{b}) and this causes the issue. This should be a 2x2 table, but it results in a 3x2 table. When the \code is removed, everything is fine.
```
#' Foo
#'
#' A *tabular* test of `pkgdown`.
#'
#' @section: A Table
#' \tabular{lll}{
#'   a     \tab `b` \cr
#'   foo   \tab bar \cr
#' }
#' @param x A character string.
#' @export foo
foo <- function(x) print(x)
```
And the resulting HTML:
![image](https://user-images.githubusercontent.com/25203086/49469063-c3c5be80-f7c3-11e8-8e9f-b4970589a58d.png)

The issue might(?) be traced to here:
```
# correct 2x2 table:
table <- '\\tabular{ll}{a \\tab b \\cr foo \\tab bar}'
pkgdown:::rd2html(table)

# incorrect 3x2 table:
table <- '\\tabular{ll}{a \\tab \\code{b} \\cr foo \\tab bar}'
pkgdown:::rd2html(table)
```

Note that a new line is generated between "a" and "b" when it shouldn't be.
This might be related to #348 or #630, but I don't think so. Or ... is this intentional and you should not have **\code** formatting inside elements of tables?

**Comment by pat-s** [comment]
Just tested it with v1.1.0 and it worked. So if the rest of your pkgdown site setup is back compatible, you can use the old release until the issue is fixed.

**Comment by jayhesselberth** [comment]
This sounds like a regression, possibly introduced in e1e6e6847e36c83f734baa6ca1627220ba8f9322.

**Comment by mjsteinbaugh** [comment]
I'm seeing this pop up in my [bcbioRNASeq](https://github.com/steinbaugh/bcbioRNASeq) package, but I'm not entirely sure where or how to make a reprex:

```
Warning in matrix(cell_contents, ncol = length(align), byrow = TRUE) :
  data length [15] is not a sub-multiple or multiple of the number of rows [8]
Calls: build_reference ... flatten_para -> <Anonymous> -> .f -> as_html.tag_tabular -> matrix
```

**Comment by wviechtb** [comment]
Seeing the same issue here. I had to downgrade to 1.1, as both 1.2, 1.3, and the development version mangled the tables.
