### ISSUE TITLE
Title is cutoff on tablet 

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#930]
I think tweaking of the h1 top margin in 74d7a383e49d2812a23332124c5ca9ebf799ede4 caused the title to be cut off on tablets (768 px). We could just hide the search box for this size class.

![image](https://user-images.githubusercontent.com/355367/49691562-7ec2c480-fb02-11e8-857f-d1fb25c347c5.png)

**Comment by hadley** [comment]
Yeah, we need to tweak the navbar here since it should never occupy two lines
