### ISSUE TITLE
Support custom printing in example rendering

### ISSUE THREAD

**Issue by thomasp85** [r-lib/pkgdown#935]
Currently, the rendering of example code uses the standard `print` method for the output. It would be great to be able to have more complex output by providing a `pkgdown_print()` method in the same veins as `knit_print`, or alternatively use knitr to render the example section.

**Comment by jayhesselberth** [comment]
I think unmerged #742 might be what you want.

Can you provide an example of something you need to work in the examples section?

**Comment by thomasp85** [comment]
It is indeed partly related to #742, but output other than htmlwidgets could be relevant as well

My own use case is for gganimate, and printing of different output types, e.g. 

https://github.com/thomasp85/gganimate/blob/7c07d6b82c11d944688fa86f62cfab309f254888/R/renderers.R#L265-L289

**Comment by jayhesselberth** [comment]
@thomasp85 Does this error look familiar? Seems I'm not passing `res` for replaying a `gif_image`, but not sure *what* needs it:

``` r
Error in .geometry(width, height, units, res): 'res' must be specified unless 'units = "px"'
```

**Comment by thomasp85** [comment]
Haven't seen it before... how do you come by it?

**Comment by thomasp85** [comment]
A `gif_image` object is basically just a path to a gif image so no rendering etc is needed at that point

**Comment by jayhesselberth** [comment]
This will require a considerable refactoring of the way examples are processed to make arbitrary outputs (gifs and htmlwidgets) work. WIP.

**Comment by jayhesselberth** [comment]
Rendering the examples with knit_print helps (changes in #941), but when I evaluate:

``` r
library(ggplot2)
library(gganimate)

ggplot(iris, aes(Sepal.Width, Petal.Width)) +
  geom_point() +
  labs(title = "{closest_state}") +
  transition_states(Species, transition_length = 3, state_length = 1)
```
 I see this error:
```
[[1]]
$src
[1] "library(ggplot2)\n"

attr(,"class")
[1] "source"

[[2]]
$src
[1] "library(gganimate)\n"

attr(,"class")
[1] "source"

[[3]]
$src
[1] "\n"

attr(,"class")
[1] "source"

[[4]]
$src
[1] "ggplot(iris, aes(Sepal.Width, Petal.Width)) +\n  geom_point() +\n  labs(title = \"{closest_state}\") +\n  transition_states(Species, transition_length = 3, state_length = 1)\n"

attr(,"class")
[1] "source"

[[5]]
<simpleError in get_knitr_options(options): argument "options" is missing, with no default>
```
The fact that I'm seeing `get_knitr_options` indicates I'm hitting `knit_print.gganim` in gganimate. But then there are required options that I'm not sending.

**Comment by jayhesselberth** [comment]
Maybe getting there. Now I see this error:

```
library(ggplot2)
library(gganimate)

ggplot(iris, aes(Sepal.Width, Petal.Width)) +
  geom_point() +
  labs(title = "{closest_state}") +
  transition_states(Species, transition_length = 3, state_length = 1)
#> Error: Unsupported device
```

I *think* this is because pkgdown uses a qualified device name ([`grDevices::png`](https://pkgdown.r-lib.org/reference/build_reference.html?q=figures#figures)) but gganimate is only matching on `png`:

https://github.com/thomasp85/gganimate/blob/7436321b2b5465b83a4761a27016ec0c12f44cb5/R/animate.R#L249

**Comment by thomasp85** [comment]
The `options` are the chunk options that knitr feeds into the `knit_print` method. An idea is that this could be defined in `_pkgdown.yml`?

**Comment by thomasp85** [comment]
I know it isn’t “relevant”. Just suggesting a way to use it to allow some control over the rendering of the output... does it hang or merely take a long time? Rendering animations is not instantaneous...

**Comment by jayhesselberth** [comment]
Almost there:

https://zen-brahmagupta-530ffe.netlify.com/reference/test-gganimate.html

Need to:

+ give the image a css class for some top / bottom padding 
+ figure out why the img name is always `-1.gif`; passing `fig.path` does not have an effect.
+ figure out a nicer way to pass img options. example images should always have the same fig opts.

**Comment by thomasp85** [comment]
You’ll probably have to look into the chunk-name in terms of the file naming

**Comment by jayhesselberth** [comment]
Here's a version of the gganimate site with all examples rendered.

https://youthful-khorana-cae3a9.netlify.com/index.html

There are a few pages with issues; not sure what to do on the pkgdown side:

+ [This page](https://youthful-khorana-cae3a9.netlify.com/reference/transition_layers.html) has several warnings.

+ A direct call to `animate` seems to affect figure height / width. See [this page](https://youthful-khorana-cae3a9.netlify.com/reference/shadow_mark.html). And [this page](https://youthful-khorana-cae3a9.netlify.com/reference/ease_aes.html) doesn't have animations at all.

**Comment by thomasp85** [comment]
How do you pass in the arguments to print? Do you simply make up a chunk option and mimick knitr?

**Comment by jayhesselberth** [comment]
Code is in #941. This replaces `print` with `knitr::knit_print` for all examples.

**Comment by thomasp85** [comment]
Hmm. `animate` grabs the chunk options dynamically if called within knitr. I can do a special grab if part of pkgdown run as well. How can I get the right settings from within the `animate()` call?

**Comment by jayhesselberth** [comment]
If pkgdown put the chunk opts in the environment:

``` r
options(pkgdown.fig_chunk_opts = chunk_opts)
```

then you could fetch in `animate()`:

``` r
if (in_pkgdown()) chunk_opts <- getOption('pkgdown.fig_chunk_opts')
```

**Comment by thomasp85** [comment]
I’ll look at it over the holidays

**Comment by flying-sheep** [comment]
I propose using repr instead.

It’s simpler, and allows more control over what is rendered, having one function per output format. Check #959 for discussion.

**Comment by jayhesselberth** [comment]
Closing in favor of new meta-issue #1256
