### ISSUE TITLE
FR: Open all links in tabs

### ISSUE THREAD

**Issue by krlmlr** [r-lib/pkgdown#938]
Occasionally one might want to browse all targets pointed to, e.g. from the reference index or from a function's documentation. An "open all in tabs" link would be handy, similarly to what "Refined GitHub" offers for notifications. We should

- only open each target once
- only open links from the main text, not from the menu
- alert if more than n tabs are about to be opened.

I'm aware there are browser extensions that do this, but our implementation could provide better value here.

**Comment by hadley** [comment]
I think this is out of scope for pkgdown
