### ISSUE TITLE
template: assets can't include directories

### ISSUE THREAD

**Issue by thomasp85** [r-lib/pkgdown#939]
It would be nice to be able to have directories in the assets location in order to better organise the additional assets. Currently I get this

```
Copying 'pkgdown/assets/images' to 'images'
Error : [EISDIR] Failed to copy '/home/travis/build/thomasp85/gganimate/pkgdown/assets/images' to '/tmp/RtmpYIWlqe/file55306a496d1e/images': illegal operation on a directory
Error: [EISDIR] Failed to copy '/home/travis/build/thomasp85/gganimate/pkgdown/assets/images' to '/tmp/RtmpYIWlqe/file55306a496d1e/images': illegal operation on a directory
```

when setting assets to `pkgdown/assets/` and having an `images` folder in it

**Comment by jayhesselberth** [comment]
@hadley can chime in but my impression is that the `pkgdown` directory is intended for configuration assets. If you have static images, they can be included in the site by placing them in `man/figures`.

**Comment by thomasp85** [comment]
This was just an example. There are lots of potential assets you may want to include in the site that don’t fit into `man/figures` (and this was for a md file in the `.github` directory so it seemed like bad practice to put it there anyway). 

In general I’m asking that any folder pointed to by `template$assets` is allowed to contain subfolders

**Comment by ijlyttle** [comment]
Hi, just to add my two cents: I think that this capability would be useful to create datasets packages, publishing the data (or larger versions of the data than opne might distribute in the package itself) using GitHub Pages. 

If you permitted, or made it easier, to put arbitrary content in `pkgdown/assets/`, then I could make datasets available, while keeping the pkgdown documentation-goodness.

I realize that this may be scope-creep, but this capability would let me keep all of my "stuff" in one place.

**Comment by hadley** [comment]
Yeah, I think it's fine for the assets to include directories; it's just a matter of tweaking the coping code.
