### ISSUE TITLE
Better cross-links between release and dev versions

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#943]

**Comment by gustavdelius** [comment]
Would it make sense to make the version number into a drop-down menu? I find it quite natural to click on the version number to change to a different one.

One might then also allow packages to keep documentation for previous releases online, in which case the drop-down could contain those versions as well.

**Comment by maelle** [comment]
Also, there should probably be only one 404 for all sites.

**Comment by hadley** [comment]
Closing in favour of #1373
