### ISSUE TITLE
Automatically build favicon once

### ISSUE THREAD

**Issue by cboettig** [r-lib/pkgdown#949]
It looks like `find_logo()` prefers the `svg` type logo, and using a vector graphic when available makes sense.  However, it seems that `pkgdown` will only create a favicon (and apple-touch icons etc) if I manually supply a `logo.png` as well.  Is this the expected behavior? (i.e. a user ought to provide both `svg` and `png` hexes?)  Would it be possible to automate the favicon png creation from the svg, or would that be introducing an undesirable dependency load?  Apologies if I've overlooked somewhere that already documents all of this!

**Comment by hadley** [comment]
I wonder if we can send a `.svg` to realfavicongenerator? Otherwise, a PR to do the conversion would be great!

**Comment by jayhesselberth** [comment]
Just confirmed that realfavicongenerator will convert SVG files.

**Comment by jayhesselberth** [comment]
@cboettig I just confirmed that a logo in `man/figures/logo.svg` works as-is. Did you get an error when you tried this? Note that created favicons are written to the `pkgdown/` directory.

**Comment by cboettig** [comment]
Yes, looks like this could have been a user error on my part; build_favicon() does work with just the svg.  Minor note, but I think `build_favicon()` ought to be adding `pkgdown/` dir to `.Rbuildignore` automatically as well? 

Looks like `build_site()` doesn't call `build_favicon()` by default either, which I think may have confused me.  Should it?

**Comment by jayhesselberth** [comment]
I updated the build-ignore suggestions.

`build_favicon()` only needs to be called once per-site (unless the logo changes) and so probably shouldn't be something `build_site()` calls every time.

**Comment by cboettig** [comment]
Great.  Sure we don't want to rebuild the favicon each time, but I wonder if `build_site()` should have some logic to detect that we have a logo.svg but no `pkgdown` dir with favicons, and thus can build it the first time automatically?  Users might otherwise not discover this cool feature!   (e.g. scanning through our recent rOpenSci submissions, many have hex logos but basically none have hexes.  Also I only `build_site` appears on the pkgdown Addin menu in RStudio).
