### ISSUE TITLE
Empty lines are not formatted correctly in verbatim text

### ISSUE THREAD

**Issue by s-fleck** [r-lib/pkgdown#951]
Empty lines in verbatim / preformatted text that render correctly inside the R documentation
produce an indent of the following line, instead of an empty line. 

So this:
```
#' ```
#' foo
#' 
#' bar
#' ```
```
renders as this:
```
foo
   bar
```

Example from another r-lib package: [processx](https://processx.r-lib.org/reference/process.html)

**Comment by kevinushey** [comment]
I think this bug ultimately comes down to `parse_section()` treating the code chunk as multiple paragraphs:

``` r
x <- structure(list(
  structure("\n", class = c("TEXT", "tag")),
  structure("Here is a code section.", class = c("TEXT", "tag")),
  structure(
    list(
      structure("Line 1\n", class = c("VERB", "tag")),
      structure("\n", class = c("VERB", "tag")),
      structure("Line 2\n", class = c("VERB", "tag")),
      structure("\n", class = c("VERB", "tag")),
      structure("Line 3\n", class = c("VERB", "tag"))
    ),
    class = c("tag_preformatted", "tag")
  ),
  structure("\n", class = c("TEXT", "tag"))
),
class = c("tag_details", "tag"))

pkgdown:::parse_section(x, "Details")
#> $title
#> [1] "Details"
#> 
#> $contents
#> [1] "<p>Here is a code section.</p><pre>Line 1"
#> [2] "Line 2"                                   
#> [3] "Line 3\n</pre>"
```

<sup>Created on 2019-04-09 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I think `parse_section()` needs to better understand `tag_preformatted` blocks.

**Comment by jayhesselberth** [comment]
The newline stripping done by `split_at_linebreaks()` in `parse_section()` needs to be moved into `flatten_para()`, where `block_tags` (e.g. `tag_preformatted`) are still available.
