### ISSUE TITLE
Pass `quiet` down to `pkgdown::build_home()`

### ISSUE THREAD

**Issue by DavisVaughan** [r-lib/pkgdown#952]
When building pkgdown docs on travis, it might be useful to let `verbose = TRUE` display the output you get from `build_home(quiet = FALSE)` as well. It seems like that would have helped debug [this](https://travis-ci.org/jimhester/vroom/builds/473081296#L3761) travis issue as the `quiet` argument is passed all the way down to the `callr::r_safe()` call that failed, see [here](https://github.com/r-lib/pkgdown/blob/923eea8c4379e200640a8c98578e82d335561478/R/rmarkdown.R#L30).

I think it would require the following changes:

- `build_site_local()` gets a `quiet` argument which is passed through to `build_home()`
- `build_site_external()` gets a `quiet` argument which is passed through to `build_site()`
- `build_site()` gets a `quiet` argument which is passed through to `build_site_local()` and `build_site_external()`
- `deploy_local()` gets a `quiet` argument which is passed through to `build_site()`
- `deploy_site_github()`'s `verbose` argument is passed through as `deploy_local(quiet = !verbose)`

Or maybe it would make sense for `deploy_site_github()` to also have a `quiet` argument, but that may be confusing.

**Comment by hadley** [comment]
Rather than making an option, I think that we can mostly resolve this situation by printing more information when `callr::r()` fails. The install case is not really a problem any more (since we now recommend installing outside, as in the new github actions pkgdown workflow), so I've focussed on RMarkdown rendering.
