### ISSUE TITLE
parameter clash for pkgdown: as_is: true

### ISSUE THREAD

**Issue by GregorDeCillia** [r-lib/pkgdown#955]
Hello,

I am currently building vignettes for a package and run into issues when I try to use 

    ---
    pkgdown:
       as_is: true
    output: html_vignette
    ---

together with a custom theme in `_pkgdown.yml`. It seems that the pkgdown theme is passed to the `html_vignette` function. However, `html_vignette` throws an error when the theme parameter is used.

> Error in html_document(fig_width = fig_width, fig_height = fig_height,  : 
  formal argument "theme" matched by multiple actual arguments
Calls: <Anonymous> ... create_output_format -> do.call -> <Anonymous> -> output_format
Execution halted

This error message is explained in detail in https://github.com/rstudio/rmarkdown/issues/1110. Despite this issue being marked as solved, the only changes on the rmarkdown side was to update the documentation. Can this be resolved in pkgdown or should I issue this in the rmarkdown repository?

**Comment by hadley** [comment]
If you use `as_is: true` you're responsible for making an RMarkdown theme that works. Unfortunately we just don't have the resources to support every possible combination.

**Comment by GegznaV** [comment]
> Unfortunately we just don't have the resources to support every possible combination.

You shouldn't support all possible combinations, but I think that there should be a possibility to use `html_vignette` in **pkgdown** with `as_is: true`. I created PR #1352 to address this issue.
