### ISSUE TITLE
pkgdown github page optimize for seo

### ISSUE THREAD

**Issue by manish-saraswat-olx** [r-lib/pkgdown#956]
Apparently, github pages can be seo optimized as shown here: https://help.github.com/articles/search-engine-optimization-for-github-pages/

I made a website with pkgdown and I tried using the steps defined in link above, but I couldn't figure out where to start, where to add seo tags.

Can someone please guide me ?

**Comment by hadley** [comment]
pkgdown does not use jekyll, so you can not use that advice.  But pkgdown does set up the meta tags for you automatically, so I doubt it would have much impact even if you could get it to work.
