### ISSUE TITLE
Provide way to override title of home page

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#957]
Since package title might not always be appropriate (since CRAN might require quoting)

**Comment by maelle** [comment]
Ah something else I'd like to see implemented! Would it be ok to make it work via a `title` field of the config?

Then in `data_home()`

```r
pagetitle = pkg$desc$get("Title")[[1]]
```

could become

```r
pagetitle = pkg$meta[["title"]] %||% pkg$desc$get("Title")[[1]]
```

? 

If so I can make a PR.

**Comment by jayhesselberth** [comment]
Yes, that looks like the right change. Can you make a PR?

**Comment by maelle** [comment]
Will do, will just wait for my other PR to be merged in order to have learned lessons and not make the same mistakes twice! :-)

**Comment by maelle** [comment]
This has to be re-opened cf https://github.com/r-lib/pkgdown/pull/1005#issuecomment-492178755: my implementation used a param name that was already used for something else, so I've opened a PR removing my changes as requested by @jayhesselberth.

**Comment by hadley** [comment]
I suggest we make it a subcomponent of home:

```yaml
home:
  title: "This is my package title"
```

**Comment by maelle** [comment]
So there would be a "general" title and a title under home, correct?

**Comment by hadley** [comment]
@maelle do you want to take another stab at this?

**Comment by hadley** [comment]
Yes exactly (sorry for out of order reply)

**Comment by maelle** [comment]
Yep, will try to next week!

**Comment by maelle** [comment]
Btw would a similar parameter for "og:description" make sense? The Description field from DESCRIPTION also contains quotes.

**Comment by maelle** [comment]
I mean tweaking

```r
opengraph = list(description = pkg$desc$get("Description")[[1]])
```

into 

```r
opengraph = list(description = pkg$meta$home[["description"]] %||% pkg$desc$get("Description")[[1]])
```

I can open a separate issue (or add that to my open PR) if of interest.

**Comment by hadley** [comment]
Is that used on every page or just the home page?

**Comment by maelle** [comment]
Just the homepage I think

https://github.com/r-lib/pkgdown/blob/9800c853e1c85a18990cdd694f1adf9dd1739a55/R/build-articles.R#L178

https://github.com/r-lib/pkgdown/blob/72391933f693e1d9509edade4951486883d64382/R/build-reference.R#L229

**Comment by hadley** [comment]
Great — please wrap that up into your PR too.

**Comment by maelle** [comment]
Would it be too extreme for pkgdown to unquote all quoted words of Title and Description (uncranify them) by default? Only for the ' quotes. Users might still want to use the home fields in config for more customization (or to requote words). 🤔

**Comment by hadley** [comment]
Oh yes, that's a good idea!

**Comment by maelle** [comment]
In a separate PR or the same?

**Comment by hadley** [comment]
I think it can be in the same PR since it's going to touch the same code.
