### ISSUE TITLE
Test: crayon on website have confusing results

### ISSUE THREAD

**Issue by EmilHvitfeldt** [r-lib/pkgdown#958]
Is it intended behavior that the output isn't colored in this article?
https://pkgdown.r-lib.org/articles/test/crayon.html

<img width="867" alt="screen shot 2019-01-10 at 12 41 02 pm" src="https://user-images.githubusercontent.com/14034784/50995823-1423f080-14d5-11e9-9692-d7f8eaab82cf.png">

**Comment by jayhesselberth** [comment]
No, this is not intended. I vaguely remember @hadley expressing frustration getting this to work in a commit message. Will have to revisit.

**Comment by hadley** [comment]
I think it works for docs, but not vignettes, currently. So this isn't a surprise.
