### ISSUE TITLE
Use repr_html for values in examples.

### ISSUE THREAD

**Issue by flying-sheep** [r-lib/pkgdown#959]
The [repr](https://github.com/IRkernel/repr) package allows to format values in a nicer way than just by text.

It would be great if pkgdown would use `repr::repr_html` to render the output of example code in `replay_html.value`, instead of just text via `capture.output(print(x$value))`

**Comment by hadley** [comment]
Can you please link to an example that shows repr output?

**Comment by flying-sheep** [comment]
> Can you please link to an example that shows repr output?

Just start a R notebook from here and play around! https://jupyter.org/try ([direct link](https://mybinder.org/v2/gh/binder-examples/r/master?filepath=index.ipynb))

But if you want I can create a gist with a few examples. It handles all of the following as HTML:

- vectors of all standard types (elision is configurable – a “…” replaces the middle items, 1-element and named vectors are handled)
- factors (displays levels as `<details/>` element in HTML, i.e. expandable)
- matrices, data.frames, and derivatives (elision is configurable)
- lists (handles mixed named and unnamed elements)
- help pages and listings (packageIQR)
- time series
- functions (highlighted using highr if installed and enabled)

**Comment by thomasp85** [comment]
Om curious (and perhaps ignorant) but isn’t it more likely that an object has a `knitr_print` method as developers are likely to ensure that their objects look nice in documents. What is the benefit of repr?

**Comment by thomasp85** [comment]
Ah, I see that it provides a richer output for the default objects... still, it would require a broad support from other packages to be meaningful IMO

**Comment by hadley** [comment]
Can you please just provide a few representative screenshots?

**Comment by flying-sheep** [comment]
Here you go! https://gist.github.com/flying-sheep/c20b098ccdff2830ea632f7f03fabacb

With some CSS styling (more is possible since repr adds classes):

![grafik](https://user-images.githubusercontent.com/291575/51176244-b882aa00-18bc-11e9-81f0-3a7aba283731.png)

**Comment by jayhesselberth** [comment]
Closing in favor of new meta-issue #1256
