### ISSUE TITLE
feature request: stomp gh-pages branch

### ISSUE THREAD

**Issue by GregorDeCillia** [r-lib/pkgdown#962]
I recently stumbled over the [packagedocs](https://github.com/hafen/packagedocs) package which provides functionalities that are very similar to pkgdown. It has its own version of `deploy_site_github()`, that stomps the deployment branch in order to avoid a repository bloat.

I think it would be very useful to also make this possible with `deploy_site_github()` by introducing a new parameter `stomp` (defaulting to `FALSE` for backward compatibility).

**Comment by hadley** [comment]
This is how pkgdown used to work, but it doesn't work if you're building both dev and release versions.

**Comment by hadley** [comment]
The development version generates a `dev/` directory inside the released version.
