### ISSUE TITLE
pkgdown freeze for package RHawkes

### ISSUE THREAD

**Issue by scizmeli** [r-lib/pkgdown#964]
Hi 

I try to run build the website for the latest version of the package "RHawkes", but before completion build_site() hangs. The only way to get out is CTRL+C.

I tested both on windows and linux, in Rstudio or in command line, same results.

Any ideas? Is that a bug?

`pkgdown::build_site()`

During startup - Warning messages:
1: Setting LC_TIME failed, using "C" 
2: Setting LC_MONETARY failed, using "C" 
3: Setting LC_PAPER failed, using "C" 
4: Setting LC_MEASUREMENT failed, using "C" 
══ Building pkgdown site ═══════════════════════════════════════════════════════
Reading from: '/home/acizmeli/RHawkes'
Writing to:   '/home/acizmeli/RHawkes/docs'
── Initialising site ───────────────────────────────────────────────────────────
── Building home ───────────────────────────────────────────────────────────────
Writing 'index.html'
── Building function reference ─────────────────────────────────────────────────
Updating RHawkes documentation
First time using roxygen2. Upgrading automatically...
Loading RHawkes
Loading required package: IHSEP
Warning: The existing 'NAMESPACE' file was not generated by roxygen2, and will not be overwritten.
Loading RHawkes
Reading 'man/EM1partial.Rd'

**Comment by jayhesselberth** [comment]
Can you provide a link to the package (on Github)?

**Comment by scizmeli** [comment]
looks like to be https://cran.r-project.org/web/packages/RHawkes/index.html and https://github.com/cran/RHawkes

**Comment by jayhesselberth** [comment]
I don't think this is a "freeze" but rather a long-running example. I can reproduce the long running part, but didn't let it finish. Fixing this is outside the scope of pkgdown, please ask the maintainer to create a smaller example.
