### ISSUE TITLE
Error : Unknown type: character when building site

### ISSUE THREAD

**Issue by andrie** [r-lib/pkgdown#965]
When I build my package docs (`surveydata`), I get  this error message:

```
Error : Unknown type: character
```

This happens because I have this code in my package:

`<edit>`

```
#' Updates names and variable.labels attribute of surveydata.
#'
#' @usage "names(x) <- value"
#' @param x surveydata object
#' @param value New names
#' @export
#' @seealso [surveydata-package()], [is.surveydata()]
`names<-.surveydata` <- function(x, value) {
  xattr <- attributes(x)
  ret <- as.data.frame(x)
  names(ret) <- value
  names(attr(ret, "variable.labels")) <- value
  as.surveydata(ret, ptn = pattern(x))
}
```

`</edit>`

The root cause is that `usage_type()` in `usage.R` checks for various object types, but throws an error when the parsed object is of type `character`.

I have a fix for this and will submit a PR imminently.

**Comment by hadley** [comment]
What specifically do you think is causing the problem?

**Comment by andrie** [comment]
After spending quite a bit of time tracking down the root cause, I realized the problem is this:

```
#' @usage "names(x) <- value"
```

In other words, I used a character string for usage, instead of an R statement.  I think it's a remnant of the olden days, when `roxygen2` didn't handle `'# @usage` properly.  So I wrote my own `@usage` statement, in this case using quotes.  Since `roxygen2` doesn't warn or comment about this, I never had any indication I shouldn't do this.

My pull request #966 handles this case (character strings) and also displays a helpful message for other cases that might fail.

**Comment by jayhesselberth** [comment]
I wonder if we should recommend against `@usage` statements. pkgdown generates one automatically for the docs, and the peculiarities of their use in others' documentation keeps coming up.

**Comment by hadley** [comment]
I'm now reasonable confident that your Rd code is incorrect — the usage should be a function expression, not a string.

**Comment by hadley** [comment]
But I did improve the error message as you suggested.

**Comment by andrie** [comment]
Thank you!
