### ISSUE TITLE
CNAME auto-generation can break CDN fronted sites

### ISSUE THREAD

**Issue by davidski** [r-lib/pkgdown#969]
The improved `build_cname()` functionality included with V1.2.0 causes me a bit of grief with my deployment architecture.

I have a GitHub hosted site (davidski.github.io/evaluator) that is fronted by AWS CloudFront at evaluator.severski.net. I need to put https://evaluator.severski.net into my `_pkgdown.yml` for links to be generated correctly for the canonical form of my site. With this in the URL field, pkgdown generates a CNAME which, if deployed, causes an infinite loop between my CDN and my origin site.

I'm able to work around this by putting the CNAME file into my .gitignore, but I wonder if there isn't a more elegant solution for this.

**Comment by hadley** [comment]
I wonder if `build_cname()` should be moved out of `init_site()` and into one of the deploy functions, since it's specifically concerned with deployment via github pages.

**Comment by hadley** [comment]
Maybe we should have to `deploy_to_github_pages()` which would be a thin wrapper around `build_cname()` + `deploy_to_branch()`
