### ISSUE TITLE
Set "Dev Status" Badges Manually

### ISSUE THREAD

**Issue by surmann** [r-lib/pkgdown#971]
Is it possible to add badges to the "Dev Status" section manually?

I like to show the badges on the top of my GitLab repository. Here is an [Example](https://gitlab.com/camLine/CornerstoneR). GitLab has extra badge settings to provide them on the top. Hence, the badges are not in the README.md any more but I would like to show them in the static documentation.

**Comment by jayhesselberth** [comment]
This is likely outside the scope of pkgdown. Is there something about GitLab that precludes you from including badges in a README? I.e. putting them in the README should fix your issue.

**Comment by surmann** [comment]
You will see the badges twice if I put them additionally in the README. Please take a short look in the linked example in my first post. I like the badges at the top and they will be redundant in the README. However, it would be good to have the on the static help page.
