### ISSUE TITLE
R6 class error

### ISSUE THREAD

**Issue by NEONKID** [r-lib/pkgdown#974]
Error when checking R6 method in fun_info function
Does this package support the R6 method?

**Comment by jayhesselberth** [comment]
We're going to need a bit more context. Is this equivalent to the error you're seeing?

``` r
library(pkgdown)
library(R6)

Rand <- R6Class(
  "Rand", 
  active = list(
    rand = function() rnorm(1)
  )
)

r <- Rand$new()
r$rand
#> [1] -0.3824484

pkgdown:::fun_info(r$rand)
#> Error in pkgdown:::fun_info(r$rand): is.call(fun) is not TRUE
```

<sup>Created on 2019-02-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by NEONKID** [comment]
Here are the errors I get:
```R
Error in fun_info(x) : Unknown call: $
```

**Comment by NEONKID** [comment]
Reorganize the errors and upload them again.

```R
DBMSIO <- R6::R6Class(classname = "DBMSIO",
  private = list(
    con = NULL
    connectDBMS = function(server, user, pw, dbms, port) {
      ...
      return(con)
    },
  ),

  public = list(
    initialize = function(server, user, pw, dbms, port = 0) {
       ....
    },

    finalize = function() disconnect(private$con)
  )
)
```
An example is the code for these R6 classes. If you load it and call the function fun_info.

```R
pkgdown:::fun_info(db$finalize)
#>Error: is.call(fun) is not TRUE
````

If you call the init_site function, you will get the following error:

```R
pkgdown::init_site()
#>Error in fun_info(x) : Unknown call: $
```
The above error also shows the same error when calling the build_site function, and after debugging, we confirmed that it appears in the fun_info function.

**Comment by jayhesselberth** [comment]
Are you using the R6 class in a `@usage` tag?

**Comment by NEONKID** [comment]
Yes, I am using the usage tag. Do you have to remove this tag?

**Comment by jayhesselberth** [comment]
If you remove `@usage` tags referencing R6 classes, the error should go away.

**Comment by NEONKID** [comment]
Great! it works. Thanks
