### ISSUE TITLE
UTF-8 encoding not preserved in authors.html

### ISSUE THREAD

**Issue by paul-buerkner** [r-lib/pkgdown#975]
Thanks for making this amazing package!

I have found one small problem in the generation of the `authors.html` based on `inst/CITATION` of an R package when characters are included that require UTF-8 encoding.

You can find an example of this problem here (umlaut ü is broken on two occasions, but not everywhere): 
https://paul-buerkner.github.io/brms/authors.html

The corresponding raw file, which correctly specifies UTF-8 encoding, is provided here:
https://github.com/paul-buerkner/brms/blob/master/inst/CITATION

**Comment by jayhesselberth** [comment]
Yes we've previously encountered encoding issues in CITATION files, might still be some lingering issues.

[This package](https://github.com/privefl/bigsnpr) uses `citEntry()` with UTF-8 characters and seems to work fine. So might be an issue with the newer `bibentry()`.

**Comment by paul-buerkner** [comment]
Thanks for the quick reply! Are you suggesting to switch to `citEntry` or wait for a fix for `bibentry()`?

**Comment by jayhesselberth** [comment]
Would you mind checking if using `citEntry()` fixes your issue, and report back?

**Comment by paul-buerkner** [comment]
Sure. Using `citEntry()` results in the same error. This is what I used:

```R
citEntry(
  entry = "Article",
  title = "Advanced {Bayesian} Multilevel Modeling with the {R} Package {brms}",
  author = person(given = "Paul-Christian", family = "Bürkner"),
  journal = "The R Journal",
  year = "2018",
  volume = "10",
  number = "1",
  pages = "395--411", 
  doi = "10.32614/RJ-2018-017",
  textVersion = "Paul-Christian Bürkner (2018). Advanced Bayesian Multilevel Modeling with the R Package brms. The R Journal, 10(1), 395-411. doi:10.32614/RJ-2018-017",
  encoding = "UTF-8"
)
```

**Comment by jayhesselberth** [comment]
I just checked your authors.html page, and the umlauts appear fine now. Can you confirm?

https://paul-buerkner.github.io/brms/authors.html

**Comment by paul-buerkner** [comment]
I just manually edited them after the fact.

**Comment by krlmlr** [comment]
I'm working around with UTF-8 escapes: https://github.com/r-dbi/DBI/blob/master/DESCRIPTION#L12

**Comment by hadley** [comment]
I've made a stab at it in the attached PR. 

@paul-buerkner I think you're setting the encoding in the wrong place — it needs to be set in `DESCRIPTION`, not in the CITATION file (setting the encoding within the file itself is usually too late because you have to read the file before you can read the desired encoding sitting inside of it)

@krlmlr I think your problem is different since DBI doesn't have an `inst/CITATION`. If you still have the problem, could you please create a minimal reprex? I just tried by changing my name to Hådléy Wickhaµ, and didn't see any problems.

**Comment by paul-buerkner** [comment]
Thank you! brms sets the encoding in the DESCRIPTION to UTF-8 as well (https://github.com/paul-buerkner/brms/blob/master/DESCRIPTION) so I am not sure if this is the issue here. I will try it out soon though and report back.
