### ISSUE TITLE
stop building website if examples fail to work?

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#976]
I don't know if this is deliberate, but, `pkgdown` doesn't quit the build process if any of the examples fail to run. On the other hand, if any of the chunks in the vignettes produces an error, `pkgdown` stops building the website. Any particular reason why the same doesn't happen for examples?

Often I realize that although the tests and the vignettes are working properly, some of my `dontrun` examples are completely out of date and not working. But since `pkgdown` never fails while building the website, I never notice this in the documentation.

**Comment by jayhesselberth** [comment]
pkgdown could probably do a better job of at least reporting errors in examples, if not stopping altogether. A hard stop would certainly encourage writing better (i.e., working) examples. One problem with the current situation is that you have to check all the examples one by one to see if you have errors.

pkgdown does not run code in `dontrun` blocks; so it's no surprising that you can have broken code in them.

**Comment by hadley** [comment]
I don't think it's pkgdown's job to check that your examples work. If you're having problems, I'd recommend running `R CMD check` first

**Comment by IndrajeetPatil** [comment]
Yeah, I know that that's not its job, but it's also not its job to check vignettes and it fails when vignette chunks don't run.

Ultimately, it comes down whether you are happy with having a website that shows broken examples. Here is an example from `tidyverse` (https://github.com/tidyverse/dplyr/issues/4394)-
![image](https://user-images.githubusercontent.com/11330453/58715302-8ae25d00-8394-11e9-91ab-bc2d40b9a6bf.png)
