### ISSUE TITLE
News sections not rendered if version is in parentheses

### ISSUE THREAD

**Issue by jayhesselberth** [r-lib/pkgdown#980]
Rendering NEWS.md with a version in paretheses causes it to be dropped from the rendered page.

If a section begins with this header, it is not present in the rendered page:

`# pkgdown (development version)`

This renders fine:

`# pkgdown 1.3.0.9000`

This explains why the [development version section](https://github.com/r-lib/pkgdown/blob/master/NEWS.md) is not present on [the dev docs](https://pkgdown.r-lib.org/dev/news/index.html)

**Comment by jayhesselberth** [comment]
This regex fails to capture parenthetical versions:

https://github.com/r-lib/pkgdown/blob/59cc923c953d483091aae2b6b626b195674efb5f/R/build-news.R#L149

**Comment by jayhesselberth** [comment]
Notably this header renders fine:

`# pkgdown 1.3.0.9000 (development version)`

but makes for a long section title.

**Comment by jayhesselberth** [comment]
The usethis [behavior](https://github.com/r-lib/usethis/blob/a221165022507d9388ed2173f8da1d9a72de0030/R/version.R#L48-L52) could be updated to add the dev version before the parentheses.

**Comment by kwathen** [comment]
Same thing also happens if you put a v in front of the version, 
For example, 
# pkgdown v1.3.0.9000 

Would cause the news to be dropped on the site.  The page is there but no content.

**Comment by jayhesselberth** [comment]
I think we should accommodate these formats:

```
# pkgdown 1.3.0

# pkgdown v1.3.0

# pkgdown (development version)
```
