### ISSUE TITLE
Include {.tabset} functionality in rendered articles 

### ISSUE THREAD

**Issue by seanhardison1** [r-lib/pkgdown#981]
Is it possible to include {.tabset} style dropdowns in pkgdown articles? This would be helpful for creating visualization-heavy articles.

**Comment by hadley** [comment]
How does this work outside of pkgdown? That's the first problem to solve.

**Comment by seanhardison1** [comment]
Here's an example of what I'm talking about in a standard rmd rendered to html
````r
---
title: "tabset test"
author: "Sean Hardison"
date: "3/1/2019"
output: html_document
---


## Section X {.tabset}


### X.1

```{r, echo = T}
plot(rnorm(30))
```


### X.2 

```{r, echo = T}
plot(rnorm(30))
```

````

The output looks like this:

![image](https://user-images.githubusercontent.com/31781107/53648474-ff7af380-3c0d-11e9-842d-90804d4d0964.png)

Maybe this is already possible through pkgdown? Tabset syntax is ignored in pkgdown::build_articles() as far as I'm aware.

**Comment by jayhesselberth** [comment]
The tabset classes are in the pkgdown vignette output, so I think we'd just need to copy the [rmarkdown jquery plugin](https://github.com/rstudio/rmarkdown/blob/ec8fd0fe0cb82d1a2a0160c8e728486ca45c9891/inst/rmd/h/navigation-1.1/tabsets.js) and some [css](https://github.com/rstudio/rmarkdown/blob/a0c0c681f03049a8e017d6ca5295160698cc17a1/inst/rmd/h/default.html#L300-L354) into pkgdown.

**Comment by jgranja24** [comment]
Is this still an outstanding feature? The tabsets are incredibly useful for building nice turorials.

**Comment by hadley** [comment]
I think unfortunately this is out of scope for pkgdown; in order to get the output of RMarkdown into pkgdown's templates we already have to do a lot of fiddly manipulation, so adding this feature is both difficult and likely to introduce unexpected issues further down the road.

**Comment by debruine** [comment]
FYI: You can roll your own as follows (YMMV, but I haven't had any problems with it, see [this vignette](https://debruine.github.io/faux/dev/articles/contrasts.html)).

Top of your script (you need some js and css from jquery-ui and to run some js to set up tabsets after the page loads):

```
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script>
  $( function() {
    $( ".mytabset" ).tabs();
  } );
</script>
```

Where you want a tabset (make sure "tabs" and all the "tabs-{x}" are unique IDs on your page):

```
<div id="tabs" class="mytabset">
  <ul>
    <li><a href="#tabs-x">X</a></li>
    <li><a href="#tabs-y">Y</a></li>
  </ul>

<div id="tabs-x">

Rmarkdown content for tab X...

</div>

<div id="tabs-y">

Rmarkdown content for tab Y...

</div>
</div>

```

**Comment by maelle** [comment]
Not sure why GitHub is showing me this issue in my notifications, but in the meantime there are tabsets for articles via #1694
