### ISSUE TITLE
Error if documenting S4 method for class NULL

### ISSUE THREAD

**Issue by chfleming** [r-lib/pkgdown#982]
I have an S4 method that I want to return `NULL` if the argument is `NULL`.

```
projection.NULL <- function(x,asText=TRUE) { return(NULL) }
setMethod('projection', signature(x='NULL'), projection.NULL)
```

The method seems to work as intended. `R check --as-cran` mandates that I document this function, which I do as 

```
\S4method{projection}{NULL}(x,asText=TRUE)
```

This all seems to work fine for rendering and passing `R check --as-cran`, but then any `pkgdown` function crashes, such as

```
> library(ctmm)
> pkgdown::build_news()
Error: Result 1 must be a single string, not a character vector of length 0
Call `rlang::last_error()` to see a backtrace
```

We have tracked this down to `purrr::map_chr(as.list(x[[3]][-1]), as.character)`, which doesn't like `NULL` (https://github.com/ctmm-initiative/ctmm/issues/29#issuecomment-468299470)

If I've done something non-kosher with S4 methods, I apologize for wasting your time. I'm not very familiar with S4 and am importing this method from another package.

**Comment by jayhesselberth** [comment]
This was fixed in #988 but need to re-implement the logic, possibly without using `pluck()`.
