### ISSUE TITLE
Adding "creator" field to citation details in pkgdown

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-lib/pkgdown#983]
Currently, the citation author details show everything (e.g., author, contributor, maintainer, etc.) but the creator of the package. 

I will use the pkgdown website for the package `sjstats` as an example ( https://strengejacke.github.io/sjstats/authors.html).

Here is the `DESCRIPTION` file for the package in question:
https://github.com/strengejacke/sjstats/blob/296c36e55b9b1d1628a23f8a053361b4bb81d042/DESCRIPTION#L4-L9

Note that the citation details for the author in `pkgdown` website mentions everything but the creator status of the author:
![image](https://user-images.githubusercontent.com/11330453/53743404-ba9ec900-3e68-11e9-927d-0c2654c2080a.png)

Also, another instance of UTF-8 encoding issue:
https://github.com/r-lib/pkgdown/issues/975

**Comment by jayhesselberth** [comment]
pkgdown equates `cre` with maintainer.

https://github.com/r-lib/pkgdown/blob/72391933f693e1d9509edade4951486883d64382/R/build-home-authors.R#L26-L28

This is a reasonable assumption for most packages. Is there a way to disambiguate "creator" and "maintainer" in DESCRIPTION?

**Comment by hadley** [comment]
In R-land creator = maintainer.

**Comment by IndrajeetPatil** [comment]
![image](https://user-images.githubusercontent.com/11330453/57981591-37bcf180-7a07-11e9-9f56-e97b05445eec.png)

**Comment by hadley** [comment]
That package supplies a custom maintainer field: https://cran.r-project.org/web/packages/corrr/DESCRIPTION. I am surprised that works and I don’t think it’s good practice.

**Comment by IndrajeetPatil** [comment]
Sure, but just contesting your claim that the creator will always be synonymous with the maintainer for R packages. The example I gave is not isolated; I have seen other packages that do a similar thing.
