### ISSUE TITLE
Adding basic docs about styling?

### ISSUE THREAD

**Issue by maelle** [r-lib/pkgdown#987]
(sorry if it's already there and I missed it!)

Docs along the line of the "basics of styling pkgdown" section of https://enpiar.com/2017/12/18/integrating-pkgdown-with-your-personal-website/ would be nice. :smile_cat:

**Comment by jayhesselberth** [comment]
Yes it would probably be have a styling vignette; that link is a good place to start.

**Comment by maelle** [comment]
Just keeping some notes here, maybe I could make a PR for such a vignette if I get things right. 

4 ways to tweak the styling, that could be used in complement of each other (I'd tend to imagine it's correct for Bootswatch theme + tweaks via extra.css/other assets; maybe less so for package+other assets?).

* Easiest solution, used an existing Bootswatch theme. In the config file

```yaml
template:
  params:
    bootswatch: cerulean
```

* "For finer-grained control, you can put any custom CSS you want in a pkgdown/extra.css file, and it will override any other styles on the page." from https://enpiar.com/2017/12/18/integrating-pkgdown-with-your-personal-website/ (so you could choose a Bootswatch theme or the default theme, and add your few tweaks).

More advanced, in both cases for things not described by templates/assets, the default or the chosen Bootswatch theme is used. Develop assets and templates and use them in a single package or in many packages by packaging the assets and templates.

* assets and templates used once

```yaml
template:
  path: path/to/templates
  assets: path/to/assets
  default_assets: false
 ```

* assets and templates packaged up

```yaml
template:
  package: mycustompackage
```

**Comment by maelle** [comment]
To add to further resources of that potential future vignette in [my question on RStudio community about pkgdown templates](https://community.rstudio.com/t/docs-on-how-to-best-create-a-custom-pkgdown-template/25867/7) Mara recommended Bootstrap docs since pkgdown uses Bootstrap https://bootswatch.com/ (the link should be added with the mention of the Bootstrap version pkgdown uses).

**Comment by maelle** [comment]
Maybe I should make a PR of a vignette draft this way I wouldn't open useless issues about things I should have known :woman_facepalming:

**Comment by maelle** [comment]
Also, if one develops custom CSS/HTML, how does one keep that up to date with the default template.

**Comment by maelle** [comment]
Theming vs layout.
