### ISSUE TITLE
Use VignetteIndexEntry to build articles index

### ISSUE THREAD

**Issue by Bisaloo** [r-lib/pkgdown#989]
Currently, the vignette `index.html` page (https://pkgdown.r-lib.org/articles/ or https://pkgdown.r-lib.org/articles/index.html) is a list with the titles of the vignettes.

Given that it's an index of the vignettes, it would make more sense to use `\VignetteIndexEntry` rather than `title` IMO. Plus, it would match the listing on CRAN.

**Comment by jayhesselberth** [comment]
I agree it would make sense to use `\VignetteIndexEntry`, if it is defined, with `title` being the default.

**Comment by hadley** [comment]
I think using different fields here will be a recipe for confusion.

**Comment by jayhesselberth** [comment]
I think if `\VignetteIndexEntry` is defined but `title` is *not*, then pages are rendered with "Unknown" as the title.

**Comment by hadley** [comment]
Our policy is for `title` and `VignetteIndexEntry` to be identical — it's really my mistake in the design of  `html_vignette()` that they were ever allowed to be different.

**Comment by cderv** [comment]
> I think if `\VignetteIndexEntry` is defined but `title` is _not_, then pages are rendered with "Unknown" as the title.

I noticed this thread and I just wanted to let you know that in next Rmarkdown version, if no title is provided, the vignette index entry will be used. See https://github.com/rstudio/rmarkdown/pull/1789
