### ISSUE TITLE
Vignette containing reexported S4 generic fails to render in `build_articles()` call

### ISSUE THREAD

**Issue by mjsteinbaugh** [r-lib/pkgdown#993]
I'm hitting an issue that I can't figure out how to troubleshoot, which is related to a reexported S4 generic. In my [bcbioRNASeq](https://github.com/acidgenomics/bcbioRNASeq) package, I'm reexporting the `sampleData()` generic from my [bioverbs](https://github.com/acidgenomics/bioverbs) package.

I call the `sampleData()` function in my [example vignette R Markdown](https://github.com/acidgenomics/bcbioRNASeq/blob/master/vignettes/bcbioRNASeq.Rmd), which knits correctly. The `sampleData()` function also passes `R CMD check` and other build checks. However, pkgdown is having trouble locating the function when attempting to link it during the `build_articles()` call -- see `pkgdown:::find_reexport_source()` step in the backtrace.

I'm only seeing this issue pop up with reexported S4 generics but not standard functions.

Here's the complete backtrace, for reference:

```
Reading 'vignettes/bcbioRNASeq.Rmd'
Error in asNamespace(ns) : not a namespace
Calls: build_articles ... ns_env_name -> unname -> getNamespaceName -> asNamespace
Backtrace:
     █
  1. └─global::build_articles()
  2.   └─pkgdown::build_articles(...)
  3.     └─purrr::walk(...)
  4.       └─purrr::map(.x, .f, ...)
  5.         └─pkgdown:::.f(.x[[i]], ...)
  6.           └─pkgdown:::render_rmarkdown(...)
  7.             └─pkgdown:::update_html(path, tweak_rmarkdown_html, input_path = path_dir(i
nput_path))
  8.               └─pkgdown:::tweak(html, ...)
  9.                 └─pkgdown:::tweak_code(html)
 10.                   └─`%>%`(...)
 11.                     ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
 12.                     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 13.                       └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
 14.                         └─pkgdown:::`_fseq`(`_lhs`)
 15.                           └─magrittr::freduce(value, `_function_list`)
 16.                             ├─base::withVisible(function_list[[k]](value))
 17.                             └─function_list[[k]](value)
 18.                               └─purrr::map(., tweak_pre_node)
 19.                                 └─pkgdown:::.f(.x[[i]], ...)
 20.                                   └─purrr::map_chr(text[!has_pkg], href_topic_local)
 21.                                     └─pkgdown:::.f(.x[[i]], ...)
 22.                                       └─pkgdown:::find_reexport_source(obj, ns, topic)
 23.                                         └─rlang::ns_env_name(get_env(obj))
 24.                                           ├─base::unname(getNamespaceName(pkg))
 25.                                           └─base::getNamespaceName(pkg)
 26.                                             └─base::asNamespace(ns)
```

The relevant code is here in the pkgdown repo: https://github.com/r-lib/pkgdown/blob/master/R/utils.r#L44

See related issue #666.

Is there a way to completely disable automatic linking of functions in pkgdown?

**Comment by mjsteinbaugh** [comment]
Also, on occasion I hit this `Error in asNamespace(ns) : not a namespace` error (particularly with deprecated functions in `NEWS.md`), which is due to reexported functions not getting detected correctly in pkgdown. Can we make this error more informative, to indicate which line in the file where this is occurring?

**Comment by mjsteinbaugh** [comment]
Following up, disabling `autolink_html()` calls for this package would be useful. Can that be accomplished by using a custom theme?

**Comment by jayhesselberth** [comment]
Can you please generate [a reprex](https://pkgdown.r-lib.org/CONTRIBUTING.html) for this issue?

It's not currently possible to control autolinking. If we tagged autolinked functions with a unique class, you would be able to turn them off.

**Comment by mjsteinbaugh** [comment]
Thanks @jayhesselberth, I'm working on trying to make a minimal reprex, and will report back.

**Comment by mjsteinbaugh** [comment]
Here's a minimal example R Markdown that reproduces the reexports error.
[pkgdown-reprex.Rmd.txt](https://github.com/r-lib/pkgdown/files/3117853/pkgdown-reprex.Rmd.txt)

**Comment by mjsteinbaugh** [comment]
Basically, I'm seeing namespace detection errors with S4 generics reexported from other packages, when using this roxygen2 documentation style:

```
#' @importFrom syntactic camel
#' @export
syntactic::camel
```

**Comment by mjsteinbaugh** [comment]
Switching to this roxygen2 reexport approach appears to fix this issue. I think it has to do with reexported functions that don't have `@usage` defined in an Rd file.

```
#' @rdname reexports-syntactic
#' @name camel
#' @importFrom syntactic camel
#' @usage camel(object, ...)
#' @export
NULL
```

**Comment by mjsteinbaugh** [comment]
I'm closing this issue for now. It's stemming from Rd files not containing usage documentation for each reexported generic.
