### ISSUE TITLE
Documentation inconsistent with usethis

### ISSUE THREAD

**Issue by rorynolan** [r-lib/pkgdown#994]
`usethis::use_pkgdown_travis()` implements (and suggests in its docs) the `pkgdown` site via the `gh-pages` branch but the `pkgdown` docs advise to do it via `master/docs`. Not a big deal but probably better to be consistent? Perhaps the `pkgdown` docs should suggest setup via `usethis`? Happy to implement this for you as a PR if you have an opinion on how these changes should look.

**Comment by jayhesselberth** [comment]
A PR would be great! We should probably alert users early on that there are two site workflows:

1. An interactive one using `build_site()` whose default is to write to `docs/`.
2. An automatic one using `deploy_site()` whose default is to write to the `gh-pages` branch. We should emphasize that this is not to be used interactively.

**Comment by cderv** [comment]
I believe `use_pkgdown_travis` will deploy to gh_page and not use `master/docs`. It uses a `docs` folder but put it in gitignore. The function from `usethis` will set everything up to create a `.travis.yml` that will use `pkgdown::deploy_site_github()`. 

I agree the function from usethis could be mentioned in the doc.

**Comment by hadley** [comment]
We're going to attempt to overhaul this process using Github actions (which should be much simpler).
