### ISSUE TITLE
Use rdrr.io instead of rdocumentation.org

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgdown#998]
e.g. https://rdrr.io/cran/ggplot2/man/aes.html

https://twitter.com/malco_barrett/status/1118177175201411072

**Comment by jayhesselberth** [comment]
@hadley To generate correct links for rdrr.io, we need to determine whether a package is cran, bioc. Do you want to include a package index in pkgdown? Or dynamically look it up?
