### ISSUE TITLE
Error with build_site() on Building home 

### ISSUE THREAD

**Issue by Fredo-XVII** [r-lib/pkgdown#999]
Hello,

I have search everywhere but I am not getting anywhere with this error (pasted below) can you tell me why you would normally see this error?  This is running on an enterprise github, so I can't get you a regex...sorry about that.

I just installed package down and reinstalled yaml (>=2.20).

Current list of file names in docs folder: 
```
 list.files(path = "./docs")
[1] "docsearch.css" "docsearch.js"  "index.html"    "link.svg"      "pkgdown.css"   "pkgdown.js"   
[7] "pkgdown.yml"   "sitemap.xml"
```

Code + Error:
```
> pkgdown::build_site()
-= Building pkgdown site ================================================================================
Reading from: 'C:/Users/xxxxx/co/pkg_R/pkg'
Writing to:   'C:/Users/xxxxx/co/pkg_R/pkg/docs'
|- Initialising site ------------------------------------------------------------------------------------
Writing 'sitemap.xml'
-- Building home ----------------------------------------------------------------------------------------
simpleError in `*tmp*`[[1]]: subscript out of bounds>
Error in `*tmp*`[[1]] : subscript out of bounds
```

Any ideas would be greatly appreciated.

```
- Session info ----------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2019-04-17   
```

**Comment by jayhesselberth** [comment]
I'ver never seen this error. I suggest trying to isolate the problem starting with a minimal package; start with `usethis::create_package()` and add pieces in.

**Comment by Fredo-XVII** [comment]
@jayhesselberth Thanks for the debug idea!! I found that my description file is causing the error.  My description file is below.  Any ideas? I have been commenting out lines, but it continues to error out.

```
Package: XXXX
Type: Package
Title: Package house all the R functions for XXXX
Version: 0.1.0
Author@R: person("Alfredo","Marquez", email = "Author@co.com", role = c("aut","cre"))
Description: Package house all the R functions for XXXX.
License: file LICENSE
Encoding: UTF-8
LazyData: true
ByteCompile: true
Imports:
    XXXXX (>= 1.2.0),
    stringr (>= 1.3.1),
    readr (>= 1.1.1),
    RJDBC (>= 0.2-7.1),
    DBI (>= 1.0.0),
    rJava (>= 0.9-10),
    dbplyr (>= 1.2.2),
    data.table (>= 1.11.8),
    sqldf (>= 0.4-11),
    stats (>= 3.4.4),
    magrittr (>= 1.5),
    rlang (>= 0.0.1)
Suggests:
    tidyverse (>= 1.2.1),
    knitr (>= 1.20),
    rmarkdown (>= 1.9),
    testthat
VignetteBuilder: knitr
RoxygenNote: 6.1.1
```

**Comment by jayhesselberth** [comment]
The correct field is `Authors@R` (plural), not `Author@R`.

**Comment by Fredo-XVII** [comment]
Yup! Just got that myself. I used you same methodology by starting with a clean DESCRIPTION file, `usethis::use_description()`, then populating line by line.  I also put the Imports and suggests at the bottom, but don't think that would have mattered.  Thank you for your help on this, lost most of a day trying to figure this out earlier this week.  Sorry, that it wasn't an issue, and cluttered up your issue space.

I have to say it would be a nice feature if the @ params didn't highlight blue when typing the ":" unless you have the right paramater, but that is probably more work than its worth.  I will try to do better at debugging.

Thanks again!!!
